### ISSUE TITLE
missing babel-runtime in package.json?

### ISSUE THREAD

**Issue by mvberg** [mifi/lossless-cut#1]
After `npm install && npm start` I get the below, running `npm install --save babel-runtime` allows app to run.

> C:\Users\Mike\git\lossless-cut (master)
> λ npm start
> 
> > lossless-cut@1.0.0 start C:\Users\Mike\git\lossless-cut
> > electron src
> 
> App threw an error during load
> Error: Cannot find module 'babel-runtime/core-js/object/assign'
>     at Module._resolveFilename (module.js:455:15)
>     at Function.Module._resolveFilename (C:\Users\Mike\git\lossless-cut\node_modules\electron-prebuilt-compile\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
>     at Function.Module._load (module.js:403:25)
>     at Module.require (module.js:483:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (C:\Users\Mike\git\lossless-cut\node_modules\electron-prebuilt-compile\node_modules\electron-compile\lib\index.js:3:15)
>     at Module._compile (module.js:556:32)
>     at Object.Module._extensions..js (module.js:565:10)
>     at Module.load (module.js:473:32)
>     at tryModuleLoad (module.js:432:12)
>     at Module._resolve

**Comment by mifi** [comment]
Are you using npm 3 or 2? For me it's working without babel-runtime with npm3. babel-runtime is provided by dependency babel-cli.

npm 3 has a flat node_modules structure which i guess is why it is able to find the babel-runtime module even though it's not explicitly declared.

I think this is more an issue with electron-compile / electron-prebuilt-compile which is use for development.

**Comment by mvberg** [comment]
Gotcha, yes was using 2.x - works as-is with npm 3.x

Cheers.
