### ISSUE TITLE
Linux problem

### ISSUE THREAD

**Issue by DracotMolver** [mifi/lossless-cut#10]
I'm using a linux OS (not a distro): Solus os 1.2.1
The app is launched well, but when I select the area that I want, the video generated is empty but the file is created.

**Comment by mifi** [comment]
Can you try to open developer tooks (ctrl+shift+i or f12) before doing the cut? And please share the ouput from the javascript console

**Comment by eexpress** [comment]
Developer tools is for debug? I have been wondering why we need this development interface.

**Comment by mifi** [comment]
I don't understand the question

**Comment by mifi** [comment]
Ah ok. It's already included in Electron which the app is based on, so I don't really see a good reason to disable it.

**Comment by DracotMolver** [comment]
This is an error that happened right now loading a flv file. It's not the error I was reporting above, but it's something new. The video was loaded with no problem, but when i did click in a space of time to cut off, then the devtools throws 66 times the same error. I'm recreating the first issue I reported :)
[error.zip](https://github.com/mifi/lossless-cut/files/879982/error.zip)

**Comment by mifi** [comment]
I think the problem here is that the HTML5 video player does not support FLV. If you press play it will say "format not supported", i'm thinking?
I shall fix this error spamming. I guess it came from when you tried to seek in the video

**Comment by mifi** [comment]
What about your original error, can you reproduce it?

> The  app is launched well, but when I select the area that I want, the video generated is empty but the file is created.

**Comment by DracotMolver** [comment]
Sorry, I replicated the issue and the app ss working fine now -.-.
