### ISSUE TITLE
[Request Enhancement] Combine all cut segments from same original to a new one.

### ISSUE THREAD

**Issue by kaikaiiiiiii** [mifi/lossless-cut#100]
1. An original video named A.mkv.

2. Cut it and export some segments:
    * a.mkv-00.00.12.909-00.00.41.310.mkv
    * a.mkv-00.01.43.276-00.02.09.095.mkv
    * a.mkv-00.03.07.511-00.03.30.426.mkv

3. I'm now using 

    * CMD prompt `dir /w/b >x.txt`
    * edit the x.txt, del unused lines, adding prefix `file '` and suffix `'` to every rest lines.
![code_2018-10-04_18-22-23](https://user-images.githubusercontent.com/1635138/46468243-79938180-c802-11e8-8395-70fdf64a7c28.png)

    * use ffmpeg command line `ffmpeg.exe -f concat -safe 0 -i x.txt -c copy a-combine.mkv` to make a new video.

4. If there could be a function in menu, that combine all `originfilename.ext-starttime-endtime.ext` files and export a new file `originfilename-combined.ext`. It will be much convenient.

**Comment by mifi** [comment]
Good simple idea for imLementation. Will look into when time. See #7

**Comment by mifi** [comment]
This is now implemented in 2.0.0
