### ISSUE TITLE
Deleting files 

### ISSUE THREAD

**Issue by DerpDiego** [mifi/lossless-cut#1000]
**Is your feature request related to a problem? Please describe.**
When I export a project with the same name as a different project in the same directory it deletes it.

**Describe the solution you'd like**
I would be really happy if you could put a warning before exporting or change the name of the project and add (1) like in windows.

I know this isn't a big problem and its me being lazy to check if the name is available but it will be a nice thing to have. TY and i love your program.

**Comment by mifi** [comment]
thanks, this was already suggested here #916
