### ISSUE TITLE
Add option to store project files in the working directory (like old behavior)

### ISSUE THREAD

**Issue by parasiteoflife** [mifi/lossless-cut#1004]
Please first search for your feature request under Issues or Discussions, maybe someone else already suggested it.

**Is your feature request related to a problem? Please describe.**
Currently the project files are stored in the video directory. If I have 4000 files and edit 1000, the directory will end up with 5000 files, which is not optimal.

**Describe the solution you'd like**
Add an option to store project files in a centralized directory, like the working dir.

**Comment by mifi** [comment]
If a lot of people need want I will implement, but I think it can be worked around by moving the project files after finish cutting? (sort by file type, then select,drag,drop)
