### ISSUE TITLE
Latest Versions not displaying segments in output from using the B key.

### ISSUE THREAD

**Issue by Desenrrollado** [mifi/lossless-cut#1005]
I updated a couple of versions back to the current version of Lossless cut. It no longer does quick cutting with the B key on windows properly. The segments show up sure but they're not automatically put into the segment to export and instead show up as cut below. I installed this program because of the quick capabilities of being able to to just hit b and the segment being recognized as end. The closet thing that works is using the thumb buttons but it's not something I really like.

![Screenshot_3](https://user-images.githubusercontent.com/92115460/151678942-5d20d84e-c8e3-409c-8e80-d0af2ab627ff.png)

Only working with thumbs to indicate start and finish...
![Screenshot_2](https://user-images.githubusercontent.com/92115460/151678952-69eec0f6-8f0a-4bd2-a832-aad274f9c3a6.png)

**Comment by DasFragezeichen** [comment]
Do you mean, that if you set keyframes and export the segments, than it's exporting ~two secounds before the keyframe is set and the video starts ~two secounds to early? Thats my problem for now.
If yes, than I can confirm this problem.

**Comment by Desenrrollado** [comment]
Perhaps I didn't properly explain myself. Perhaps my wording was to vague, if so I'm sorry.

Lossless Cut has a neat feature that allows you to quickly create segments on any video if you simply hover above any point in a video and click with your cursor then hit the B key. You'll have the initial segment and then the rest as another individual segments. They should immediately appear in the output section. My issue is that when you try to repeat the process in version 3.42.0 is that segments aren't appearing in the output. The only way I can make segments appear is using these two buttons in V.3.42.0
![Screenshot_2](https://user-images.githubusercontent.com/92115460/151705616-6bc5ca39-6aec-4a9d-856d-45d5b745cb8c.png)


Demonstrated with function working v 3.39.0
![Screenshot_1](https://user-images.githubusercontent.com/92115460/151705141-c3c1309b-b67f-4e66-9e6a-7161e040a477.png)

I'll continuing using this version simply because it works the way I want it to.

**Comment by mifi** [comment]
Oh, thanks for reporting back. so it works with the newest version too for you now?

**Comment by Desenrrollado** [comment]
Yeah it works fine now. Sorry for taking time out of your day to disturb you.

**Comment by mifi** [comment]
Thanks for the kind words. Don’t worry, I’m always looking to iron out any bugs so if you see this problem again later and are able to reproduce it, then please let me know!
