### ISSUE TITLE
Windows defender anti-virus dramatically slows seek performance on AVI files

### ISSUE THREAD

**Issue by jedmeister324** [mifi/lossless-cut#1006]
**Describe the bug**
On version 3.42, windows 10.  
Seeking through AVI files that were 'converted to supported format' when opened, is very slow on windows 10.

Checking task manager, when CTRL+right arrow is pressed to seek forward, the "Antimalware Service Executable" process cpu usage jumps to 20-30% for several seconds before the seek operation completes.   

**Share information to help me understand**
This seems to occur more often on files that are not MP4.   eg, open an AVI file, xvid format.

**To Reproduce**
1. Open an Xvid format AVI file, which is "converted to supported format"
2. Open task manager, choose details tab, sort by cpu usage descending order
3. On lossless cut, press CTRL-RightArrow , to seek forward. 
4. On task manager, the Antimalware Service Executable process jumps to 20-30%, before seek operation completes. 

**Expected behavior**
Seeking should not trigger an antimalware scan. 

Disabling windows defender anti-virus real time protection fixes the issue, and dramatically improves seek performance.

**Comment by mifi** [comment]
Unfortunately, I don't know how to fix this. I can only think of that it has to do with the fact that it's an unsigned app. Does it work with older versions of losslesscut? I can only suggest trying that, disabling windows defender or purchasing the signed version of losslesscut from the windows store
