### ISSUE TITLE
Wrong error message when output directory doesn't have enough space to save the file

### ISSUE THREAD

**Issue by romerojp** [mifi/lossless-cut#1015]
First of all, thanks for this tool. I love the UI and it is very intuitive to use.

Now to the issue, I kept getting the "Failed to merge files. Make sure they are all of the exact same codecs" error message, and spent an embarrassing amount of time validating each file, and seeing they all were effectively the exact same codecs... and then it hit me. I was saving to an external drive that was full. Perhaps the error could be more descriptive.

**Comment by mifi** [comment]
Hi! thanks for reporting. I have now added an out of space check for the merge function as well, so in the next version it should report a better error when that's the case!

Related to #328
