### ISSUE TITLE
Enlarge Play/Pause button or space it out more

### ISSUE THREAD

**Issue by andoruB** [mifi/lossless-cut#1016]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Make the Play/Pause button larger, or more spaced out from the Frame Forward/Backwards buttons, to avoid accidentally clicking on them.

**Additional context**
It happens often that when I want to pause the video, I accidentally press on the One Frame Forward button instead, also the detection for those two buttons seems to be off, as even if I press right at the edge of the play button, I still get One Frame Forward instead. I think those buttons are a bit too close to each other, so maybe either making the Play/Pause button larger, or adding more space between those two buttons might be in order?

**Comment by mifi** [comment]
now improved:
<img width="790" alt="Screenshot 2022-02-13 at 17 28 17" src="https://user-images.githubusercontent.com/402547/153747005-d19b8568-ec2a-438f-9584-afa2910dbc5a.png">

will be avail in the next version

**Comment by andoruB** [comment]
Thank you, you're the best!
Will test them out once the new version comes out!

**Comment by fumakotaro** [comment]
Thank you andoruB for the request and mifi for the work!

Could you please make the blue circle also clickable? It seems you still have to hit the white triangle pretty much.

**Comment by andoruB** [comment]
I can confirm the same for the pause button and the play button as well. Both have rather tight "hit detection", would be easier to set the whole circle clickable as @fumakotaro fumakotaro suggested.

**Comment by mifi** [comment]
thanks for reporting. Indeed a bug. fixed it now
