### ISSUE TITLE
Keyframe jump feature behaves strangely when turning off showkeyframes

### ISSUE THREAD

**Issue by andoruB** [mifi/lossless-cut#1018]
**Describe the bug**
Keyframe jump feature behaves strangely when turning off showkeyframes. When disabling show keyframes option, I'm no longer able to seek properly to next keyframe

**To Reproduce**
1. Open video file
2. Use the seek keyframe button - works as expected
3. Disable showkeyframes option if it was already enabled
4. Use seek keyframe button - jumps randomly to an earlier part of the video instead of jumping to the next keyframe, or doesn't do anything at all
5. Try out using the keyboard shortcuts instead - works as expected
6. Enable showkeyframes option again - works as expected with seek keyframe button

**Expected behavior**
To be able to disable showkeyframes option and to still be able to use the seek keyframes buttons

**Desktop (please complete the following information):**
 - OS: Manjaro 21.2.2 Qonos - Cinnamon flavour + LosslessCut 3.42.0 Appimage

**Comment by mifi** [comment]
Actually the show keyframes button is not only for showing keyframes, but it's for enabling extraction of keyframes. What's the reason you need to hide keyframes but still want to "use" them?

**Comment by mifi** [comment]
Ok, I see. I'll close this then. Can revisit this if more people are confused by it

**Comment by mifi** [comment]
@cyzs233 thanks for your report. Could this be happening because you don't have any keyframes loaded between 01:03 and 00:46? After https://github.com/mifi/lossless-cut/issues/563#issuecomment-1013707144 it will buffer old keyframes. So if there are no keyframes between, then it will jump to the previous keyframe which could be at 00:46

**Comment by mifi** [comment]
yes the buffer of 1000 last keyframes is already out. problem is that loading a long window of many minutes will take a long time
