### ISSUE TITLE
Missing HDR format (Dolby Vision) on the generated file

### ISSUE THREAD

**Issue by the123blackjack** [mifi/lossless-cut#1031]
- When combining / merging two files which shows up as HDrFormat as Dolby vision in mediainfo , when merged by losslesscut doesnt show that info in mediainfo. Still the video is 10bit 

I presume the Dolby vision metadata is lost during the merge.

This is observed on the version 3.42.0 in windows platform.

When i later checked with cut operation its observed the same.

Obviously i have flagged to keep the metadata for mp4/mov

(*Not sure if it is a bug but the export options for merge operation either doesnt show up or doest ask to keep the metadata, but it appears only on cut operation - will have to log a separate issue for this)

**Comment by the123blackjack** [comment]
Also i am not sure how the missing DV tag affects playback in players

**Comment by mifi** [comment]
Did you try with the "Experimental flag" enabled?
See also #329 - I believe iPhone videos are also dolby vision, judging from discussion here: https://trac.ffmpeg.org/ticket/8632

**Comment by the123blackjack** [comment]
Original Files:
![image](https://user-images.githubusercontent.com/39509137/154665621-c6dc723a-2889-44f7-97d8-4362c43cfb67.png)


Merged By Lossless Cut (with or withour experimental flag)
![image](https://user-images.githubusercontent.com/39509137/154665128-f3af0166-a0c2-4df8-afd9-811b37a76fac.png)

**Comment by the123blackjack** [comment]
This is Iphone 12, 13 ++ files with Dolby vision HDR. Post concatenation / merging the Dolby Vision Metadata is stripped off leaving only as HLG

**Comment by mifi** [comment]
Ok. It's definitely an ffmpeg issue. you can confirm it by doing the same with ffmpeg from the command line. Hopefully they will fix it in the future

**Comment by the123blackjack** [comment]
Yes for sure even on the command line this issue was reproduced as is an issue with ffmpeg

**Comment by ValZapod** [comment]
Not ffmpeg issue, you forgot -strict unofficial in ffmpeg.

**Comment by mifi** [comment]
@ValZapod  I thought `-strict experimental` is a superset of `-strict unofficial`? https://superuser.com/a/543593/658247

**Comment by ValZapod** [comment]
> is a superset

Yes, but it may be more complex, since experimental stuff.

**Comment by mifi** [comment]
I'm not sure what you mean. Do you mean that `unofficial` will preserve Dolby Vision HDR format, while `experimental` will not? Could you show an example file to reproduce this?

**Comment by the123blackjack** [comment]
@mifi  @ValZapod There is some good news with some extensive testing with the -strict experimental flag ffmpeg is maintaining Dolby Vision Metadata but only if i output it to mp4 container. I was actually outputting to .mov container as the source file are .mov / iphone videos.

@mifi in lossless cut can we have an enhancement to have output / merge to .mp4 / .mkv... well it is still lossless just a container change

ffmpeg -f concat -safe 0 -i VideoList.txt -n -c copy -strict experimental output.mp4 2> Output.log

**Comment by the123blackjack** [comment]
@mifi is this error serious and how to mitigate this. Also how to see ffmpeg logs of Losslesscut

[mp4 @ 000001d82f5b3480] Non-monotonous DTS in output stream 0:0; previous: 5311072, current: 5304544; changing to 5311073. This may result in incorrect timestamps in the output file.
[mp4 @ 000001d82f5b3480] Non-monotonous DTS in output stream 0:0; previous: 5311073, current: 5304864; changing to 5311074. This may result in incorrect timestamps in the output file.

**Comment by mifi** [comment]
@the123blackjack that’s good news! Losslesscut already lets the user choose output format, so they can change it to mp4 to make it work. But maybe we should show them a warning if they try to use .mov and the input file is dolby? Not sure how to detect dolby using ffprobe but im sure it’s possible

**Comment by the123blackjack** [comment]
ffprobe does return the DOVI value in Side Date so we are good for detection and to display a warning for all iphone users :)  @mifi 
**Side data:
      DOVI configuration record: version: 1.0, profile: 8, level: 6, rpu flag: 1, el flag: 0, bl flag: 1, compatibility id: 4**


Unfortunately the output from Losslesscut is still stripping away the Side Data even after selecting .mp4

The command i run successfully is the below

ffmpeg -f concat -safe 0 -i VideoList.txt -n -c copy -strict experimental output.mp4 2> Output.log

FFMPEG Version I am on : ffmpeg version n5.0-4-g911d7f167c-20220310 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (crosstool-NG 1.24.0.533_681aaef)

**Comment by mifi** [comment]
1. Cool!
2. Did you enable the experimental setting in losslesscut?

**Comment by the123blackjack** [comment]
Yes it is enabled, however till i am unable to get the metadata in LosslessCut. Is this the FFMEG Version of the backend command being used by you?

**Comment by mifi** [comment]
losslesscut currently includes ffmpeg 4.4.1. But as of latest losslesscut you can specify an external ffmpeg command to use too. Maybe 5.0 is needed for this to work?

**Comment by the123blackjack** [comment]
Yes this Support for Dolby vision for mp4 was included 4 months back. Is adding version 5 in Losslesscut in the pipeline

**Comment by Subfader** [comment]
Found this tool today and it was a big downer to see Dolby HLG is not supported.
2nd shock was to find out the App Store app is 3.36 from 11 months ago.
3rd shock was to see that the latest version here on GitHub uses an 11 months old ffmpeg 4 version while 5.0 has been available for 3 months.

I cancelled the 18 € app, sorry. I would be happy to pay that for an up to date version that can handle my iPhone videos..

**Comment by Subfader** [comment]
And I can confirm that adding `-strict experimental` to `copy` will keep it HLG

**Comment by Subfader** [comment]
And I can confirm that just using ffmpeg 5 wil do the trick (`-strict experimental` not needed).
I just ran the command from the last ffmpeg command list in Terminal using ffmpeg 5.0 via brew:

`ffmpeg -hide_banner -ss '4.66639' -i '/path/in.MOV' -t '48.05855' -avoid_negative_ts make_zero -map '0:0' '-c:0' copy -map '0:1' '-c:1' copy -map_metadata 0 -movflags '+faststart' -default_mode infer_no_subs -ignore_unknown '-metadata:s:v:0' 'rotate=360' -f mov -y '/Upath/out.mov'`

The result was perfect a perfect HLG MOV file.

**Comment by the123blackjack** [comment]
@Subfader i had this checked and required exporting to .mp4 container with strict experimental flags.

HLG may be intact by the Dolby Vision (DvCC) is getting stripped off otherwise

**Comment by Subfader** [comment]
OK, I just checked for HLG in MediaInfo and dropped it into Final Cut using my HLG to Rec709 presets.

**Comment by mifi** [comment]
> Yes this Support for Dolby vision for mp4 was included four months back. Is adding version 5 in Losslesscut in the pipeline? @mifi

Yes, it will be included in the not too far future. See #981

> 2nd shock was to find out the App Store app is 3.36 from 11 months ago.

Where do you see that? According to AppStoreConnect the latest version is 3.39.2 which was [released on 30.oct 2021](https://github.com/mifi/lossless-cut/releases/tag/v3.39.2). (4+ months ago). Anyways, I have implemented a lot of new features and refactoring of losslesscut lately, that's why I don't release it immediately to the app stores. I want those who pay for the app to have the most stable experience, and I consider the latest github versions to be a public "beta". In fact there are currently multiple bugs in the latest version that I'm working on fixing.

> 3rd shock was to see that the latest version here on GitHub uses an 11 months old ffmpeg 4 version while 5.0 has been available for 3 months.

I have been busy implementing a bunch of new features and I wasn't aware that ffmpeg 5 supported dolby, so I haven't spent much time on upgrading ffmpeg unfortunately, but will definitely be prioritizing it now.

BTW FYI all: the newest github version of losslesscut lets you select an external ffmpeg command to use, so if you want a sneak peek of ffmpeg 5 with losslesscut you can do that.

**Comment by Subfader** [comment]
> Where do you see that? According to AppStoreConnect the latest version is 3.39.2 

Sorry, my mis-reading on the mini About popup. macOS App Store has 3.39.2 :)

> BTW FYI all: the newest github version of losslesscut lets you select an external ffmpeg command to use, so if you want a sneak peek of ffmpeg 5 with losslesscut you can do that.

THANKS! I just re-installed 3.44.0 and HLG is preserved by default (?).

**Comment by mifi** [comment]
Latest losslesscut now includes ffmpeg 5.0.1. will push to stores once tested a bit more.

**Comment by mifi** [comment]
Because losslesscut now includes ffmpeg5 and I saw comments saying that ffmpeg5 solves the problem, i’ll close this.

**Comment by mifi** [comment]
> > Because losslesscut now includes ffmpeg5 and I saw comments saying that ffmpeg5 solves the problem, i’ll close this.
> 
> Hi, I'm on the latest 3.65.0 and Dolby Vision is preserved only when I enable `ffmpeg experimental` flag.

that's great to know, thanks for sharing!

**Comment by harryqt** [comment]
I tested this with v3.68.0, and the exported files are still missing Dolby Vision metadata. It appears that this issue has not been fixed yet and is still present in the latest version.

Do I need to use .mp4 and not .mov?

**Comment by mifi** [comment]
Did you try both mp4 and mov and none include the metadata? one thing you could try is to use external ffmpeg from losslesscut (download from https://www.ffmpeg.org/) and see if it makes a difference.
