### ISSUE TITLE
Can't merge HEVC file

### ISSUE THREAD

**Issue by leedashone** [mifi/lossless-cut#1032]
**Describe the bug**
Can't merge HEVC files.

**To Reproduce**
My video files was converted with Handbrake (H.264 to HEVC), use AMD VCE hardware encoder)
for example,  I convert 3 h.264 file part1.mp4, part2.mp4, part3.mp4 to H.265: part1.m4v, part2.m4v, part3.m4v
I drag all 3 .m4v files to main window and click  merge, but always got error message while progress in 0%.
(Error message say I must keep all video files in same format)
(If I merge h.264 files, it's work fine)

**Desktop **
 - OS: Windows 10 & Windows 11, same result.
 
**Additional context**
App version 3.42.0

Video files detail format:
   Codec: HVC1 - Native D3D9 DXVA Decoder(VLD) - Radeon RX Vega M GL Graphics
   Format: HVC1(24 bits)
   Size: 1920 × 1080(1.78:1)
   FPS: 29.97
   BitRate: Unknow

Audio Codec: AAC(0xaac0) - FFmpeg Decoder (aac)
   Freq: 44100 -> 44100 Hz
   Data rate: 16 -> 16 bit
   Channels: 2 -> 2 channel
   Bitrate: 160 kbps

Thanks a lot.

**Comment by leedashone** [comment]
Sorry I don't know how to delete post.
I Tried re-install FFMpeg to the last version,, and everything is fine now!
Just ignore or delete my original post.
Thanks!

**Comment by mifi** [comment]
could u check developer tools for any errors there?

**Comment by leedashone** [comment]
main.515c04aa.js:2 Version 3.43.0
main.515c04aa.js:2 ffmpeg -hide_banner -f lavfi -i 'nullsrc=s=256x256:d=1' -f null -
DevTools failed to parse SourceMap: file:///C:/Users/lee-1/AppData/Local/Temp/25PY2mf8KOUvphtaqYVvq2cCTYU/resources/app.asar/build/static/js/main.515c04aa.js.map
DevTools failed to parse SourceMap: file:///C:/Users/lee-1/AppData/Local/Temp/25PY2mf8KOUvphtaqYVvq2cCTYU/resources/app.asar/build/main.js.map
DevTools failed to parse SourceMap: file:///C:/Users/lee-1/AppData/Local/Temp/25PY2mf8KOUvphtaqYVvq2cCTYU/resources/app.asar/build/signals.js.map
DevTools failed to parse SourceMap: file:///C:/Users/lee-1/AppData/Local/Temp/25PY2mf8KOUvphtaqYVvq2cCTYU/resources/app.asar/build/core.js.map
DevTools failed to parse SourceMap: file:///C:/Users/lee-1/AppData/Local/Temp/25PY2mf8KOUvphtaqYVvq2cCTYU/resources/app.asar/build/realtime.js.map
DevTools failed to parse SourceMap: file:///C:/Users/lee-1/AppData/Local/Temp/25PY2mf8KOUvphtaqYVvq2cCTYU/resources/app.asar/build/cue.js.map
DevTools failed to parse SourceMap: file:///C:/Users/lee-1/AppData/Local/Temp/25PY2mf8KOUvphtaqYVvq2cCTYU/resources/app.asar/build/index.js.map
DevTools failed to parse SourceMap: file:///C:/Users/lee-1/AppData/Local/Temp/25PY2mf8KOUvphtaqYVvq2cCTYU/resources/app.asar/build/node.js.map
DevTools failed to parse SourceMap: file:///C:/Users/lee-1/AppData/Local/Temp/25PY2mf8KOUvphtaqYVvq2cCTYU/resources/app.asar/build/utf8.js.map
DevTools failed to parse SourceMap: file:///C:/Users/lee-1/AppData/Local/Temp/25PY2mf8KOUvphtaqYVvq2cCTYU/resources/app.asar/build/match.js.map
DevTools failed to parse SourceMap: file:///C:/Users/lee-1/AppData/Local/Temp/25PY2mf8KOUvphtaqYVvq2cCTYU/resources/app.asar/build/unicode.js.map
DevTools failed to parse SourceMap: file:///C:/Users/lee-1/AppData/Local/Temp/25PY2mf8KOUvphtaqYVvq2cCTYU/resources/app.asar/build/mbcs.js.map
DevTools failed to parse SourceMap: file:///C:/Users/lee-1/AppData/Local/Temp/25PY2mf8KOUvphtaqYVvq2cCTYU/resources/app.asar/build/sbcs.js.map
DevTools failed to parse SourceMap: file:///C:/Users/lee-1/AppData/Local/Temp/25PY2mf8KOUvphtaqYVvq2cCTYU/resources/app.asar/build/iso2022.js.map
DevTools failed to parse SourceMap: file:///C:/Users/lee-1/AppData/Local/Temp/25PY2mf8KOUvphtaqYVvq2cCTYU/resources/app.asar/build/command.js.map
DevTools failed to parse SourceMap: file:///C:/Users/lee-1/AppData/Local/Temp/25PY2mf8KOUvphtaqYVvq2cCTYU/resources/app.asar/build/cuesheet.js.map
DevTools failed to parse SourceMap: file:///C:/Users/lee-1/AppData/Local/Temp/25PY2mf8KOUvphtaqYVvq2cCTYU/resources/app.asar/build/static/css/main.24f89f29.css.map
main.515c04aa.js:2 userOpenFiles
main.515c04aa.js:2 C:\Users\lee-1\Desktop\Part1.m4v
C:\Users\lee-1\Desktop\Part2.m4v
main.515c04aa.js:2 Merging files {paths: Array(2)} to C:\Users\lee-1\Desktop\Part1-merged.m4v
main.515c04aa.js:2 getFormatData C:\Users\lee-1\Desktop\Part1.m4v
main.515c04aa.js:2 ffprobe -of json -show_format -i 'C:\Users\lee-1\Desktop\Part1.m4v' -hide_banner
main.515c04aa.js:2 getFormatData C:\Users\lee-1\Desktop\Part2.m4v
main.515c04aa.js:2 ffprobe -of json -show_format -i 'C:\Users\lee-1\Desktop\Part2.m4v' -hide_banner
main.515c04aa.js:2 ffmpeg -hide_banner -f concat -safe 0 -protocol_whitelist file,pipe -i - -c copy -movflags +faststart -default_mode infer_no_subs -ignore_unknown -strict experimental -y C:\Users\lee-1\Desktop\Part1-merged.m4v
main.515c04aa.js:2 file 'file:C:\Users\lee-1\Desktop\Part1.m4v'
file 'file:C:\Users\lee-1\Desktop\Part2.m4v'
main.515c04aa.js:2 Failed to merge files Error: Command failed with exit code 1: C:\Users\lee-1\AppData\Local\Temp\25PY2mf8KOUvphtaqYVvq2cCTYU\resources\ffmpeg.exe -hide_banner -f concat -safe 0 -protocol_whitelist file,pipe -i - -c copy -movflags +faststart -default_mode infer_no_subs -ignore_unknown -strict experimental -y C:\Users\lee-1\Desktop\Part1-merged.m4v
Input #0, concat, from 'pipe:':
  Duration: N/A, start: -0.047891, bitrate: 1626 kb/s
  Stream #0:0(und): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 1505 kb/s, 29.97 fps, 29.97 tbr, 90k tbn, 90k tbc
    Metadata:
      creation_time   : 2021-02-21T18:05:11.000000Z
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 121 kb/s
    Metadata:
      creation_time   : 2021-02-21T18:05:11.000000Z
      handler_name    : Stereo
      vendor_id       : [0][0][0][0]
[ipod @ 0000021da4b1b040] Could not find tag for codec hevc in stream #0, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:1 -- 
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
    Last message repeated 1 times
    at makeError (C:\Users\lee-1\AppData\Local\Temp\25PY2mf8KOUvphtaqYVvq2cCTYU\resources\app.asar\node_modules\execa\lib\error.js:60)
    at handlePromise (C:\Users\lee-1\AppData\Local\Temp\25PY2mf8KOUvphtaqYVvq2cCTYU\resources\app.asar\node_modules\execa\index.js:118)
    at async file:/C:/Users/lee-1/AppData/Local/Temp/25PY2mf8KOUvphtaqYVvq2cCTYU/resources/app.asar/build/static/js/main.515c04aa.js:2
    at async file:/C:/Users/lee-1/AppData/Local/Temp/25PY2mf8KOUvphtaqYVvq2cCTYU/resources/app.asar/build/static/js/main.515c04aa.js:2
(anonymous) @ main.515c04aa.js:2
async function (async)
(anonymous) @ main.515c04aa.js:2
onConfirm @ main.515c04aa.js:2
onClick @ main.515c04aa.js:2
Ve @ main.515c04aa.js:2
Ke @ main.515c04aa.js:2
(anonymous) @ main.515c04aa.js:2
Ar @ main.515c04aa.js:2
Rr @ main.515c04aa.js:2
(anonymous) @ main.515c04aa.js:2
Le @ main.515c04aa.js:2
(anonymous) @ main.515c04aa.js:2
Pr @ main.515c04aa.js:2
Jt @ main.515c04aa.js:2
Zt @ main.515c04aa.js:2
t.unstable_runWithPriority @ main.515c04aa.js:2
qi @ main.515c04aa.js:2
Me @ main.515c04aa.js:2
Qt @ main.515c04aa.js:2`

**Comment by mifi** [comment]
Did it work in previois versions?

**Comment by leedashone** [comment]
No, Merge HEVC file never success via any version which I used before. (about 5~6 versions)
( H.264 file is OK)

**Comment by mifi** [comment]
Could you try to rename the parts to .mp4 instead of .m4v. If that doesnt work, try to rename to .mov instead?

**Comment by leedashone** [comment]
OOOOH !!!

**_rename .m4v to .mp4 is work!!!!!_**
(.mov also work!)

Thanks a lot!!!

**Comment by mifi** [comment]
Cool. BTW be sure to check the output file if it's playable in the video player you want to use. I think there is some issue with playing back hvc1 videos converted with ffmpeg (losslesscut) in QuickTime. I'm working in fixing that
