### ISSUE TITLE
zip is larger than executable itself

### ISSUE THREAD

**Issue by senhalil** [mifi/lossless-cut#1037]
If zipping makes the file bigger, there might be something wrong with the zip parameters.

https://github.com/mifi/lossless-cut/releases/tag/v3.42.0

```
LosslessCut-win.exe 93.3 MB
LosslessCut-win.zip 136 MB
```

**Comment by mifi** [comment]
Maybe the self-extracting exe is using a better compression algorithm than zip or maybe there's a bug where the exe is missing some files. Feel free to test and report back.

**Comment by senhalil** [comment]
> Feel free to test and report back.

I am not a user in fact; I saw the discrepancy while "passing by".

**Comment by oliko-tk** [comment]
A MI ME PARECE QUE VA SUPER EL PROGRAMA .. Y GRACIAAS AL CREADOR DEL SOFWARE

**Comment by mifi** [comment]
Ok. I also don't know what to do about this, sorry. can reopen if anyone has advice or trouble
