### ISSUE TITLE
github.com/mifi/lossless-cut/releases/latest/download/LosslessCut-linux.AppImage does not get newest AppImage?

### ISSUE THREAD

**Issue by slrslr** [mifi/lossless-cut#1039]
Hello,

I am using command
`/usr/bin/wget -NcqO $HOME/LosslessCut-linux.AppImage https://github.com/mifi/lossless-cut/releases/latest/download/LosslessCut-linux.AppImage`

to download latest AppImage. Yet when i run it and then run:

`$HOME/LosslessCut-linux.AppImage`

it says:

> Current version 3.42.0
> Newest version 3.43.0

if not issue on my end, can this be made working so there is permanent URL where one can download latest AppImage please?

**Comment by mifi** [comment]
check the main readme: https://github.com/mifi/lossless-cut#download
there is a link there that works

**Comment by slrslr** [comment]
@mifi If you mean the link:

> Linux: [tar.bz2](https://github.com/mifi/lossless-cut/releases/latest/download/LosslessCut-linux.tar.bz2) / [AppImage](https://github.com/mifi/lossless-cut/releases/latest/download/LosslessCut-linux.AppImage)

then it is the same link that i have mentioned and that is causing non-latest release be used. Did you try mine mentioned commands?

**Comment by slrslr** [comment]
@mifi 

Yes, "wget -N" not downloaded the new version because new version has same size as old version (i do not know why):
New:
138692882 Feb 21 08:45 LosslessCut-linux.AppImage
Old:
138692882 Feb 23 15:11 LosslessCut-linux.AppImage_old

i am not mistaken, i ran both files and each has a bit different interface, showing different version.

Do you have idea how to make it so the file size differ or such

so wget -N (timestamping) recognize this as a new file?

wget manual:

> When running Wget with -N, ..., the decision as to whether or not to download a newer copy of a file depends on the local and remote timestamp and size of the file.

If not possible to achieve different size (by the way quite large) i would have to use additional command to discover current version:
`wget -q https://github.com/mifi/lossless-cut/releases/latest -O - | grep "title>Release" | cut -d " " -f 4`

and compare it with mine version which i would have to store in some file i guess.

**Comment by mifi** [comment]
Huh? File size of v42 and 43 is exactly the same but different code? How is that even possible 😄 
Maybe you can use ETag? It should differ if content differs
