### ISSUE TITLE
Reorder files before merging

### ISSUE THREAD

**Issue by efoxbr** [mifi/lossless-cut#1041]
"Move merge / batch functionality from top menu into a menu on the batch file list"

Since version 3.43.0 I can't reorder files before merging, batch file list is not sortable (Windows).

**Comment by mifi** [comment]
Barch file list is not sortable, but when you click merge from the batch menu, the merge popup shows up, and that one is sortable, no?

**Comment by efoxbr** [comment]
You're right. I didn't click to proceed because I thought it was going to merge directly, sorry about that and thanks for your attention.

**Comment by mifi** [comment]
I will try to make it easier to understand. Thanks for your feedback
