### ISSUE TITLE
Batch file list can't sort file 

### ISSUE THREAD

**Issue by taozi1996** [mifi/lossless-cut#1043]
![GIF 2022-2-24 21-19-10](https://user-images.githubusercontent.com/31797996/155532811-edfa3339-75cc-47c6-82dd-78e568084994.gif)

**Comment by mifi** [comment]
Hi. Why do you need to sort? It was never possible to sort it

**Comment by taozi1996** [comment]
> Hi. Why do you need to sort? It was never possible to sort it

I might miss some files if not in natural order.

**Comment by mifi** [comment]
Ok, I'll move the sorting from the merge dialog into the batch list!
