### ISSUE TITLE
Fade in & out video & audio!

### ISSUE THREAD

**Issue by Droyk** [mifi/lossless-cut#1044]
Someone else wanted this too but only for audio it seems #696 I want it for both! 
& users should be able to do this per segment/chapter not only one as a whole!

This feature is already present in [shutter encoder](https://github.com/paulpacifico/shutter-encoder)
![image](https://user-images.githubusercontent.com/15848350/155659469-fbd9372b-b1f6-4869-84b6-c2f1f4cf33ef.png)

Since you're adding lossy operations #372 I thought why not be the one shop stop for all!

**Comment by mifi** [comment]
Hi! I agree it would be nice to have. I referenced this issue from the lossy operations issue and I’ll be closing this to keep issue count down. Thanks for the input!
