### ISSUE TITLE
Add shortcut keys

### ISSUE THREAD

**Issue by On-Memory** [mifi/lossless-cut#1045]
I hope you can modify the minimize shortcut key or add a shortcut key of boss key (quick hide) in the setting. Thanks！

**Comment by On-Memory** [comment]
> Hi. What do you mean by minimize or boss key (quick hide)? Could you visualize examples maybe?

It is now "ctrl+m" this shortcut key can modify or add a shortcut key for hidden software

**Comment by On-Memory** [comment]
It is now "ctrl+m" this shortcut key can modify or add a shortcut key for hidden software

**Comment by mifi** [comment]
this is a bit more tricky because it's handled by the menu (Window -> Minimize). I'll close this and instead add it to #254
