### ISSUE TITLE
Play/pause button only responds in very center

### ISSUE THREAD

**Issue by wolftune** [mifi/lossless-cut#1048]
I'm Linux, and the cursor clicking on the big green button doesn't respond unless I click in the very center. The outer part of the green circle does nothing when I click it. On latest 3.43.0

**Comment by andoruB** [comment]
I can confirm this as well on Manjaro with Cinnamon.
Was already raised as an issue in  #1016 by fumakotaro

**Comment by mifi** [comment]
thanks for reporting. Indeed a bug. fixed it now
