### ISSUE TITLE
Need Crop, Resize, Blur Features...

### ISSUE THREAD

**Issue by appysrinath** [mifi/lossless-cut#1057]
Please first search for your feature request under Issues or Discussions, maybe someone else already suggested it.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mifi** [comment]
dup of #372 - **please** at least try to search first, so I don't have to keep closing issues. thank you.
