### ISSUE TITLE
Crashing after upgrading to 3.43

### ISSUE THREAD

**Issue by RafaelLinux** [mifi/lossless-cut#1058]
After I upgraded to LossLessCut 3.43, I can't launch LossLessCut:

CLI arguments { _: [] }
Current version 3.43.0
Newest version 3.43.0
[26726:0306/032530.781343:FATAL:gpu_data_manager_impl_private.cc(1034)] The display compositor is frequently crashing. Goodbye.
`trap' para punto de parada/seguimiento (`core' generado)

**Desktop (please complete the following information):**
Operating System: openSUSE Tumbleweed 20220304
KDE Plasma Version: 5.24.2
KDE Frameworks Version: 5.91.0
Qt Version: 5.15.2
Kernel Version: 5.16.11-1-default (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-6600K CPU @ 3.50GHz
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2

**Comment by mifi** [comment]
dup #1025
