### ISSUE TITLE
Please add the flags of Somalia and Syria to the software open interface

### ISSUE THREAD

**Issue by yukminnie** [mifi/lossless-cut#1060]
Please first search for your feature request under Issues or Discussions, maybe someone else already suggested it.

**Is your feature request related to a problem? Please describe.**

> The lives of the Somali and Syrian people are also lives, as are those of Ukraine .

**Describe the solution you'd like**

> Please add the flags of Somalia and Syria to the software open interface .

**Describe alternatives you've considered**

>  I think, as a good developer with a sense of justice, this should be easy for you, sir.

**Additional context**

> Yemen and Syria are sovereign countries ,  we should condemn such aggression by the US and Israel . In fact, Israel has been bombing Syria since 2011.

[israeli-air-strikes-kill-three-syrian-soldiers-near-damascus-syrian-media-says](https://www.france24.com/en/middle-east/20220224-israeli-air-strikes-kill-three-syrian-soldiers-near-damascus-syrian-media-says)    24/02/2022 - 03:11

[return-of-us-airstrikes-big-relief-in-al-shabaab-war-in-somalia](https://www.garoweonline.com/en/news/somalia/return-of-us-airstrikes-big-relief-in-al-shabaab-war-in-somalia)   24/02/2022 - 10:31

**Comment by yukminnie** [comment]
> I've found the flag link for you, sir, for your convenience.

<a href="https://flagpedia.asia/syria"><img alt="旗叙利亚" src="https://flagpedia.asia/data/flags/small/sy.png" width="120" height="80" /></a>

<a href="https://flagpedia.asia/somalia"><img alt="旗索马里" src="https://flagpedia.asia/data/flags/small/so.png" width="120" height="80" /></a>

**Comment by mifi** [comment]
Thank you for your suggestion. While I agree that these are also notable incidents, I still believe that the ongoing Russia-Ukraine conflict is of utmost importance right now and I will keep supporting Ukraine for now. No disrespect to Somalia or Syria. Maybe in the future I will show support to victims of other armed conflicts. Please keep any discussions regarding the Ukraine conflict and politics to this issue: #1055 - I will delete any other issues about this matter in the future.

**Comment by mifi** [comment]
fyi the app now shows 50% ukraine, 50% palestine suport due to the severe genocide currently happening

**Comment by BreakMate** [comment]
So severe that their population increased. Typical European.

**Comment by mifi** [comment]
> So severe that their population increased. Typical European.

although there are also other serious atrocities happening, i need to prioritise the largest and most serious war crimes. and currently it is still Israel's occupation and mass murder in its neighbouring countries.

**Comment by BreakMate** [comment]
Jews will always "Occupy" wherever they are, because they are inferior in your eyes. So inferior, they cannot self determine their own destiny, or respond to constant violent attacks and threats of annihilation. You care more to stroke your ego than to actually learn anything. Propaganda over facts. You are helping spread the modern day blood libel, just like many Europeans before you. Don't feel special, because you are just another drop of blood in the annals of Jew-Hatred. At least you made a decent tool and shared it for free.

**Comment by mifi** [comment]
> because they are inferior in your eyes

Stop putting words in my mouth. I never said anything about jews. The only thing you and every other zionist do is to gaslight the discussion with the only false argument which is "anti-semitism". I can tell you most anti-zionists have nothing against jewish people, in fact many **jews** are anti-zionists and anti-israel. This is not about hating jews, this is about stopping a genocidal expansionist movement by the regime of Israel.

**Comment by BreakMate** [comment]
You know nothing of the Arabic language, history, the Middle East, or Islamic Colonialism. There have been many massacres that happened to Jewish communities (and minorities) across the Middle east for centuries before Israel even became a state (in 1948). Maybe you don't believe you hate Jews, but you actively give your support to those that do. Do you know what a genocide even is, what it looks like, what needs to take place? While Israel shows restraint, sends messages and drops leaflets for civilians to evacuate, opens humanitarian corridors and allows aid through their own border (looking at Egypt here), does that show intent to commit genocide? Is going after the rapists and murderers and butchers of October 7th not justified? Don't all wars has casualties? Was October 7th an act of genocide? I mean, they just went in with the intent to kill and maim anyone that they could, even pets, and took pleasure in it. One even exclaimed from the phone of the girl he just slaughtered "I killed a Jew!", the father responds in admiration. Is that not something worth reacting to? Why doesn't anyone break down the 70,000 number, like how many active Militants/terrorists/legitimate targets? why only mention the civilian casualties? 

I will extend an olive branch and agree that you didn't say Jews, rather you direct your grievances towards "Israel". That means mostly Jews. There are also Christians, Druze, Muslims, all who are a part of Israel and some (voluntarily) even serve in the IDF. So while your "many Jews" makes up an extreme minority, the majority of Jews are Zionist, and the majority of those who are anti-Zionist are also in one form or another anti-Jewish. The only Jews you could point to that are anti-Zionist are either Far Left (usually also very secular) or Neturei Karta.

At anti-Israel protests, did you chant along in the Arabic? Did you call to globalize the intifada? Maybe "Khaibar, Khaibar, Ya Yahud"!

**Comment by mifi** [comment]
I'm sorry but this is just a soup of baseless claims and arguments for which I don't know what you're trying to prove.
I'm not denying attrocities that happened to jews. again I'm not talking about jews. I'm talking about the state of israel. I'm not denying that oct 7 was a war crime but seen in the larger picture it's a relatively small tragedy.

> So while your "many Jews" makes up an extreme minority, the majority of Jews are Zionist

This is another baseless claim (unless you're talkign about israeli jews). for other jews around the world, not so much the case if you do some basic research.

> and the majority of those who are anti-Zionist are also in one form or another anti-Jewish

you are saying that jews who are anti-zionist are anti-jewish? i mean come on... what does that even mean?

I really cannot continue this conversation. you can read more about my stance here in the FAQ https://genocide.no/palestine/more/ and suggest improvements if you have any concrete criticism for any of those points. If you want to continue the discussion do so here: #1055 - i will not answer in this issue any more, it is off topic here.

**Comment by BreakMate** [comment]
amazing, I give you a chance to answer any of my questions and you cant, no words or thoughts of your own, just point me to a link actually filled with baseless claims and quotes out of context, and then point me to continue somewhere else. fuck that, just don't respond. 

By the way, what does a anti-Zionist Jew at a Passover seder do when we say "Next year in Jerusalem?"

bye

**Comment by mifi** [comment]
I invited you to join the discussion at #1055 instead because it is off topic here.
