### ISSUE TITLE
Please add the flags of Yemen to the software open interface .

### ISSUE THREAD

**Issue by yukminnie** [mifi/lossless-cut#1061]
The lives of the Yemen people are also lives, as are those of Ukraine .

Please add the flags of Yemen to the software open interface .

[yemen-has-lost-internet-after-saudi-led-airstrikes](https://www.npr.org/2022/01/21/1074659054/yemen-has-lost-internet-after-saudi-led-airstrikes#:~:text=DUBAI%2C%20United%20Arab%20Emirates%20%E2%80%94%20A,poorest%20country%20off%20the%20internet.)  21/01/2022 

---

**Before：** **issues has closed**

[issues 1060](https://github.com/mifi/lossless-cut/issues/1060) Please add the flags of Somalia and Syria to the software open interface

somalia and Syria are sovereign countries , we should condemn such aggression by the US and Israel . In fact, Israel has been bombing Syria since 2011.

[israeli-air-strikes-kill-three-syrian-soldiers-near-damascus-syrian-media-says](https://www.france24.com/en/middle-east/20220224-israeli-air-strikes-kill-three-syrian-soldiers-near-damascus-syrian-media-says) 24/02/2022 - 03:11

[return-of-us-airstrikes-big-relief-in-al-shabaab-war-in-somalia](https://www.garoweonline.com/en/news/somalia/return-of-us-airstrikes-big-relief-in-al-shabaab-war-in-somalia) 24/02/2022 - 10:31

---

The fact is that air strikes by the United States and Israel against countries in the Middle East are **happening right now**. 

Why can't their flag be displayed in the software interface to show support for them? Or on **which version of the software** do you plan to show your support for them, sir? 

Do you believe that the lives of people in the Middle East are not as **even important** as the lives of Ukrainians, sir?

Maybe it's only OK for you to express political demands on github, but not for others? That's the reason for closed issues,  sir?

**Comment by taozi1996** [comment]
Do you know what organization the Somali Al-Shabaab is? It was a terrorist who killed a lot of people, including the Chinese. 
https://baike.baidu.com/item/%E7%B4%A2%E9%A9%AC%E9%87%8C%E9%9D%92%E5%B9%B4%E5%85%9A/3777024
http://www.xinhuanet.com/world/2015-07/27/c_128064130.htm
https://ww.wiki.fallingwaterdesignbuild.com/wiki/%E7%B4%A2%E9%A9%AC%E9%87%8C%E9%9D%92%E5%B9%B4%E5%85%9A
The US military bombed the Somali al-Shabaab at the request of the Somali government, not a war of aggression.
(I say this, it does not mean that I support other illegal military operations of the US military.)

Everyone has limited information, don't impose your will on others.
You can also create a software by yourself to support what you support.

**Comment by mifi** [comment]
@yukminnie i am the maintainer of this project. I have the right to close issues. *You are welcome to express your opinion about the matter but please do so in #1055* - if you keep creating new issues , I will have to report spam/abuse. Thank you for respecting that.

**Comment by yukminnie** [comment]
> @yukminnie i am the maintainer of this project. I have the right to close issues. _You are welcome to express your opinion about the matter but please do so in #1055_ - if you keep creating new issues , I will have to report spam/abuse. Thank you for respecting that.

OK, I respect your rules for issues.

So,  the United States and Israel against countries in the Middle East are happening right now, and on which version of the software do you plan to show your support for them, sir?

**Comment by yukminnie** [comment]
> Do you know what organization the Somali Al-Shabaab is? It was a terrorist who killed a lot of people, including the Chinese. https://baike.baidu.com/item/%E7%B4%A2%E9%A9%AC%E9%87%8C%E9%9D%92%E5%B9%B4%E5%85%9A/3777024 http://www.xinhuanet.com/world/2015-07/27/c_128064130.htm https://ww.wiki.fallingwaterdesignbuild.com/wiki/%E7%B4%A2%E9%A9%AC%E9%87%8C%E9%9D%92%E5%B9%B4%E5%85%9A The US military bombed the Somali al-Shabaab at the request of the Somali government, not a war of aggression. (I say this, it does not mean that I support other illegal military operations of the US military.)

- In fact, as I said before, I support the underclass people of Ukraine, not Russia and the Ukrainian government likewise, for Syria and Somalia as well.

- At the request of " so and so government ", if this reason is valid, then the Vietnam war was also at the request of the South Vietnamese government, the Korean war was also at the request of the South Korean government, there are no more unjust wars in the world. Any country has an opposition, is it up to other countries to define who can represent their country?  Is it okay to have a third party country bombing before you figure this out?

- Can I then say that Russia is carrying out the removal of Nazi operations from Ukraine at the request of the Lugansk opposition?

- In fact, all of them were not under UN authorization and they were illegal.

- So, I would like to ask the author to add the flags of Syria, Somalia, and Yemen to the software interface, to express support for the war-torn underclass people.

> Everyone has limited information, don't impose your will on others. You can also create a software by yourself to support what you support.

 - So, you're answering “ it's only OK for you to express political demands on github, but not for others? ”

**Comment by taozi1996** [comment]
> > Do you know what organization the Somali Al-Shabaab is? It was a terrorist who killed a lot of people, including the Chinese. https://baike.baidu.com/item/%E7%B4%A2%E9%A9%AC%E9%87%8C%E9%9D%92%E5%B9%B4%E5%85%9A/3777024 http://www.xinhuanet.com/world/2015-07/27/c_128064130.htm https://ww.wiki.fallingwaterdesignbuild.com/wiki/%E7%B4%A2%E9%A9%AC%E9%87%8C%E9%9D%92%E5%B9%B4%E5%85%9A The US military bombed the Somali al-Shabaab at the request of the Somali government, not a war of aggression. (I say this, it does not mean that I support other illegal military operations of the US military.)
> 
> * In fact, as I said before, I support the underclass people of Ukraine, not Russia and the Ukrainian government likewise, for Syria and Somalia as well.
> * At the request of " so and so government ", if this reason is valid, then the Vietnam war was also at the request of the South Vietnamese government, the Korean war was also at the request of the South Korean government, there are no more unjust wars in the world. Any country has an opposition, is it up to other countries to define who can represent their country?  Is it okay to have a third party country bombing before you figure this out?
> * Can I then say that Russia is carrying out the removal of Nazi operations from Ukraine at the request of the Lugansk opposition?
> * In fact, all of them were not under UN authorization and they were illegal.
> * So, I would like to ask the author to add the flags of Syria, Somalia, and Yemen to the software interface, to express support for the war-torn underclass people.
> 
> > Everyone has limited information, don't impose your will on others. You can also create a software by yourself to support what you support.
> 
> * So, you're answering “ it's only OK for you to express political demands on github, but not for others? ”

Somali al-Shabaab attacked UN fleet, This US operation has authorized by UN.

**Comment by mifi** [comment]
@yukminnie to answer your question: I do not have any concrete plans or schedule/version for supporting any other causes.

**Comment by yukminnie** [comment]
> Somali al-Shabaab attacked UN fleet, This US operation has authorized by UN.

- I think you are misunderstanding that the UN authorized the fight against Somali pirates, not the bombing of pirates and civilians together. Which is more credible, the "probably no civilian casualties" paragraph in the press release after each bombing of Somalia, or the bloody pictures?

**Comment by yukminnie** [comment]
> @yukminnie to answer your question: I do not have any concrete plans or schedule/version for supporting any other causes.

- Okay, thank you for your reply, which confirms my previous determination.
