### ISSUE TITLE
Meaning of cut buttons has reversed

### ISSUE THREAD

**Issue by howff** [mifi/lossless-cut#1062]
**Describe the bug**
Clicking the "Set cut start to current position" button sets the cut *end* to the current position.
(This used to work as expected in previous versions)

**To Reproduce**
1. Click in the middle of the timeline
2. Click the "Set cut start" button
3. The section prior is cut and the section after is kept

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by mifi** [comment]
Hi. I think you need to toggle the yin yang symbol (possibly toggle advanced view first)

**Comment by howff** [comment]
Maybe the bug is in the tooltips, because they read the same whichever way the yin yang is toggled.

**Comment by mifi** [comment]
so the issue you're having is just that the tooltip text for "Set cut start to current position" is the same no matter the yin yang setting?

**Comment by howff** [comment]
That's right.

**Comment by mifi** [comment]
I believe that has always been the case, but it's something that could be fixed

**Comment by mifi** [comment]
I will change the buttons to instead of saying `Set cut ...` will say `Start current segment at current time`

**Comment by howff** [comment]
Thank you.

Can the tooltip text can be changed dynamically depending on the setting of the yinyang button?

I had an idea - I wondered whether, instead of two buttons, there's just a single button which toggles the keep/discard state at the current cursor position.

**Comment by mifi** [comment]
> Can the tooltip text can be changed dynamically depending on the setting of the yinyang button?

I think that's not needed because now it will say `Start/end current segment at current time`. and the segments are always the same on the timeline regardless of the "yin yang" setting.

> I had an idea - I wondered whether, instead of two buttons, there's just a single button which toggles the keep/discard state at the current cursor position.

I'm not sure how that would work. maybe you could try to illustrate.
