### ISSUE TITLE
Increase clickable area for play/pause button to include blue circle

### ISSUE THREAD

**Issue by richlux** [mifi/lossless-cut#1064]
I know this is a minor complaint, but I keep running into it because I don't have the steadiest mouse hand, so I figured I'd submit a feature request for it.  I often think I'm clicking on the play/pause button, but nothing happens and finally I realized it's because I'm clicking on the blue circle area and not directly on the white play arrow.  Apparently, clicking the blue area doesn't do anything, so it would be great if clicking anywhere on the while or blue area executed the command.

Thanks,
Rich

**Comment by mifi** [comment]
Hi and thanks for reporting. this has been fixed and should be solved in the next version. See #1048
