### ISSUE TITLE
Chinese Tag Exporting An Empty File name

### ISSUE THREAD

**Issue by yuuwubvwby** [mifi/lossless-cut#1067]
1、When I type a tag of chapter in Chinese,it seems work.
![image](https://user-images.githubusercontent.com/90454636/157802175-b9e8301a-e23b-4f85-ab7e-dd2ec1e13b5f.png)
2、But when I set my file name with the Chinese tag, it replaces Chinese with space
![image](https://user-images.githubusercontent.com/90454636/157802226-36cef224-4b73-4c53-bd96-a71ba30e71ea.png)
3、And output a file with name as——
![image](https://user-images.githubusercontent.com/90454636/157802546-fec023cd-3cd3-48e3-8cb7-8289ecea663f.png)

System：Windows 10 Pro
Language：Chinese(Simplified)

**Comment by mifi** [comment]
Hi. Can you try to toggle the "sanitize file name" button? Related #889

**Comment by taozi1996** [comment]
![GIF 2022-03-12 13-25-31](https://user-images.githubusercontent.com/31797996/158005145-3aef1e34-5a7e-4314-99b4-a02f0fb2d5d5.gif)

**Comment by yuuwubvwby** [comment]
谢谢！解决了！~
✿✿ヽ(°▽°)ノ✿

**Comment by mifi** [comment]
Ok great! I think this can be closed then
