### ISSUE TITLE
Scene detection / Auto segmentation (based on fade-to-black)

### ISSUE THREAD

**Issue by SpaceAgeHero** [mifi/lossless-cut#1068]
Hi,
would it be possible to implement a function, that automatically segments a video file based on fade-to-black incidents?
This would seriously help me to cut my ... documentaries.
Cheers

**Comment by mifi** [comment]
Hi. Do you mean detect all frames that are (almost) black and make segments around those frames? If so, I think this would be the same as #623

**Comment by SpaceAgeHero** [comment]
Yes, exactly. Sorry for dupe requesting then. https://github.com/mifi/lossless-cut/issues/623
