### ISSUE TITLE
Please make the AppImages updateable?

### ISSUE THREAD

**Issue by slrslr** [mifi/lossless-cut#1069]
Hello,

[as described, wget fails to update appimage](https://github.com/mifi/lossless-cut/issues/1039#issuecomment-1048877382), so i have [tried AppImage updater](https://github.com/AppImage/AppImageUpdate/issues/200#issuecomment-1065506458), yet when i supply LC 3.43.0 AppImage to it, then it says:

`Error reading AppImage: Could not find update information in the AppImage. Please contact the author of the AppImage and ask them to embed update information.`

Here I have found instructions making AppImages updateable:
https://docs.appimage.org/packaging-guide/optional/updates.html

**Comment by mifi** [comment]
Hi. There have been requests for this before, see #535 and #484.

Unfortunately I'm not so familiar with the appimage ecosystem that I can work on that. PR is welcome however. I can reopen #484 if someone wants to work on it
