### ISSUE TITLE
Give ability to disable audio fade at cut

### ISSUE THREAD

**Issue by Diranus** [mifi/lossless-cut#107]
This tool would be one of the best choices to cut long sequences of music videos (recorded from tv) into single music videos.

But the added audio fade is annoying long for that task (destroys audio quality in the beginning) and makes the tool totally useless for such a task.

Please add an user option to change the length of the fade (down to 100 samples or so would be nice to prevent clicking AND audible fading).

**Comment by mifi** [comment]
Hi. What do you nean by fade? The audio is also cut losslessly and there shouldn’t be any fade

**Comment by Diranus** [comment]
There is an audio fade-in and -out if I use your tool to cut a video (a simple mp4/h264/aac one).
That fade is approx 1s long.
If I use ffmpeg directly from command-line to do the same task by hand, there is no fade.
OS: Ubuntu 18.04
Application version: The latest one from here: https://github.com/mifi/lossless-cut/releases

**Comment by mifi** [comment]
Can you link directly to a video?
the page you linked is saying
```
Sorry, der Browser kann nicht alle Elemente dieser Seite laden.

Bitte prüfen Sie,
ob ein Werbeblocker oder ein anderes Programm das Laden aus Unterverzeichnissen verhindert.

Weitere Hinweise finden Sie zum Beispiel unter www.spiegel.de
```

**Comment by Diranus** [comment]
It wants you to disable your ad-blocker.

**Comment by mifi** [comment]
reopen if you can reproduce
