### ISSUE TITLE
视频剪切异常

### ISSUE THREAD

**Issue by Humbert34** [mifi/lossless-cut#1076]
当我准备剪辑视频时，发现视频剪辑后的市场和原视频一样没有发生变化，我是手动输入切割点进行剪辑的。
No error

{
  "state": {
    "filePath": "E:\\讯飞教育\\视频录制\\片段2.mp4",
    "fileFormat": "mp4",
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "Constrained Baseline",
        "codec_type": "video",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1080,
        "closed_captions": 0,
        "has_b_frames": 0,
        "pix_fmt": "yuvj420p",
        "level": 40,
        "color_range": "pc",
        "chroma_location": "left",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "10/1",
        "avg_frame_rate": "10/1",
        "time_base": "1/10240",
        "start_pts": 1024,
        "start_time": "0.100000",
        "duration_ts": 420864,
        "duration": "41.100000",
        "bit_rate": "239899",
        "bits_per_raw_sample": "8",
        "nb_frames": "411",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "VideoHandler",
          "vendor_id": "[0][0][0][0]"
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "44100",
        "channels": 1,
        "channel_layout": "mono",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/44100",
        "start_pts": 1014,
        "start_time": "0.022993",
        "duration_ts": 1807360,
        "duration": "40.983220",
        "bit_rate": "167497",
        "nb_frames": "1765",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "SoundHandler",
          "vendor_id": "[0][0][0][0]"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "E:\\讯飞教育\\视频录制\\片段2.mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {
        "start": 15.023,
        "end": 41.023
      }
    ],
    "mainFileFormatData": {
      "filename": "E:\\讯飞教育\\视频录制\\片段2.mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.022993",
      "duration": "41.100000",
      "size": "2106926",
      "bit_rate": "410107",
      "probe_score": 100,
      "tags": {
        "major_brand": "isom",
        "minor_version": "512",
        "compatible_brands": "isomiso2avc1mp41",
        "encoder": "Lavf58.17.101"
      }
    },
    "rotation": 360,
    "shortestFlag": false
  },
  "platform": "win32",
  "version": "3.44.0"
}

**Comment by mifi** [comment]
Hi. what's your export mode (merge/segments/chapters)? and how far apart are your keyframes on the timeline?
