### ISSUE TITLE
Buttons 'One frame forward' and 'One frame  back' don't work

### ISSUE THREAD

**Issue by DanielBielak** [mifi/lossless-cut#1079]
Buttons 'One frame forward' and 'One frame  back' don't work.

Lossless-Cut versions 3.44.0 and 3.43.0
macOS 10.14.6

**Comment by mifi** [comment]
What happens if you press the button? Nothing? What about pressing one of the buttons two times? Also could you provide a report from the help menu?

**Comment by oliko-tk** [comment]
Ami me funcionan normal en windows.

**Comment by mifi** [comment]
Thanks. I see now what is wrong. one frame back/forward skips one video frame. Your file is audio and therefore has no fps. In the previous version if no fps it would just seek by a fixed amount. I will fix this bug and make it like it was before.

**Comment by DanielBielak** [comment]
Thanks.
