### ISSUE TITLE
Program opens as a blank page and then closes

### ISSUE THREAD

**Issue by IvoAndonov** [mifi/lossless-cut#1082]
Since the last update, released by AUR, the program starts as a blank page and then closes without ever showing the menu. I thought this was an AUR issue, so I downloaded several different appimages (of a few older versions) but they behave the same, even a version that I used in December - 3.39.0.
The thing is that with this issue I can' access the requested menus in order to create the logs.

2 months ago the program was working just fine,

I made a video using SimpleScreenRecorder:

https://drive.google.com/file/d/1OrIBjh9rqJ_943nXV6MbVRghYWjiy3CT/view?usp=sharing

`[rado@arch]: ~>$ sysinfo
 rado@arch
 OS: Arch Linux 
 Kernel: x86_64 Linux 5.16.14-arch1-1
 Uptime: 3d 21h 26m
 Packages: 1553
 Shell: bash
 Resolution: 1920x1080
 DE: Cinnamon 5.2.7
 WM: Muffin
 WM Theme: BGT-v1.7 (Cinnamox-Rhino)
 GTK Theme: BGT-v1.7 [GTK2/3]
 Icon Theme: Humanity-Dark
 Font: Open Sans Semi-Bold 11
 Disk: 1,6T / 5,0T (33%)
 CPU: Intel Core i7-4770 @ 8x 3.4GHz [31.0°C]
 GPU: NVIDIA GeForce GTX 1660 Ti
 RAM: 3112MiB / 32024MiB`

**Comment by mifi** [comment]
Hi. Just to be sure, you're saying that old versions are also currently failing the same way? Could you try to run it from the command line and see if it makes a difference? And is there any way for you to open developer tools?

**Comment by IvoAndonov** [comment]
Yes. As I said, I downloaded an appimage from here and they failed to start as well.

This is what I get from the terminal:
[rado@arch]: ~>$ losslesscut
CLI arguments { _: [] }
Current version 3.44.0
Newest version 3.44.0
[58867:0318/090914.598875:FATAL:gpu_data_manager_impl_private.cc(1034)] The display compositor is frequently crashing. Goodbye.
Trace capture / breakpoint (memory unloaded)

If developer tools is somehwere inside the program, as I suspect, then no. If you saw the video, the program's interface doesn't load at all.

**Comment by mifi** [comment]
Ok, I see. Seems like this is the same issue as #1025 then - you can try the suggestions from there.

**Comment by IvoAndonov** [comment]
Yep, adding `--no-sandbox`fixed it. So I added that to the 'exec=' line in the desktop file as a permanent solution. :)
