### ISSUE TITLE
It's easy to make the mistake and export file without extension by removing `${EXT}` from the template

### ISSUE THREAD

**Issue by chrisbbqi** [mifi/lossless-cut#1083]
does anyone encounter this？
I am using MacBook Pro, Monterey system.
the exported files are the format that can not be read, not video files. I have tried a lot video formats， but always the same.

**Comment by mifi** [comment]
I'm going to need some more info to help you

**Comment by Yneth** [comment]
I see no export button, except the one in the right bottom corner, but it does not do any exports

**Comment by Yneth** [comment]
figured it out, this button persists on popup, and needs to be clicked again.
from UI UX perspective it would be nice to add this button to the popup.
otherwise, at least for me, it seems unintuitive

**Comment by chrisbbqi** [comment]
> 

thank you. the output file seems like a text file， I can't even open it， however the size of it is similar to the video format.

**Comment by chrisbbqi** [comment]
> I'm going to need some more info to help you

could you give me an email？ I will record the screen to show you what the problem looks like.

**Comment by mifi** [comment]
If you could report some info like suggested in the issue template, that would be helpful. Also what do you mean by text file? Does it end with .txt?

You can send to losslesscut@mifi.no if you want

**Comment by mifi** [comment]
I think the problem you're having with the file being output as a text file, is that you have removed the extension from the output name template (in the export dialog). You can try to reset the output name to the standard, and it should work.

There's a reset button in the output file name editor: <img width="25" alt="Screenshot 2022-08-06 at 12 11 36" src="https://user-images.githubusercontent.com/402547/183244521-a51126fb-0b19-49de-b925-fff705784242.png">

The key here is that you need to keep `${EXT}` in your template, or the file will be created without an extension. the standard file output template name is `${FILENAME}-${CUT_FROM}-${CUT_TO}${SEG_SUFFIX}${EXT}`

I can see that this is a common problem so I will find a way to improve this, probably by either:
- always appending the extension regardless, or
- give a warning if extension is missing
