### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by xcybermanx** [mifi/lossless-cut#1086]
Hello Is possible to Add lossless-cut as Docker image

Thank You

**Comment by mifi** [comment]
Hi. I'm not sure what would be the benefit of running losslesscut in docker. Is it even possible (and easy) to run GUI apps in docker? I thought docker was usually for backend services and command line utilities?

**Comment by xcybermanx** [comment]
because must of video editing has make Docker image with web browser like : 
https://hub.docker.com/r/jlesage/mkvtoolnix
https://hub.docker.com/r/jlesage/handbrake/

like me i use web browser to run video editing in chrome or Firefox because i run my Ubuntu in command line only.
Thank You for you reply

**Comment by mifi** [comment]
Cool! So I think it depends on losslesscut first being able to run in the browser, right? Unfortunately it does not support that and will probably not support any time soon, see #1022

**Comment by mifi** [comment]
thanks. i'll close this then, since not much that can be done

**Comment by HarryMuscle** [comment]
Just a quick note on how those other applications actually function in Docker.  They don't natively support running in a browser.  The Docker image contains a GUI environment that the application runs in and that environment is configured to be accessible via an RDP tool like VNC and it exposes only the one application.  The end result is that the application in question is made to look and function like a web application when it reality it never had that functionality before.  This should be doable with Lossless Cut also.

**Comment by mifi** [comment]
Cool! If anyone wants to make a Dockerfile for LosslessCut, I'm happy to merge it, as long as it doesn't make any intrusive changes in the app's source code.

**Comment by outlyer-net** [comment]
For anyone interested, I created docker images. They are barely tested and probably need some more polish, but appear to be working fine.

GitHub repository: https://github.com/outlyer-net/docker-losslesscut
DockerHub images: https://hub.docker.com/r/outlyernet/losslesscut

<img src="https://user-images.githubusercontent.com/9115720/202476141-d66807c4-4cd0-405a-8911-b543954e713f.png" width="250" alt="LosslessCut WebUI on Firefox (dark mode)"><img src="https://user-images.githubusercontent.com/9115720/202476128-ed09183f-ebce-412b-9b8b-b361ee3a101e.png" width="250" alt="LosslessCut WebUI on Firefox"><img src="https://user-images.githubusercontent.com/9115720/202476136-462edeb1-3aaa-4b96-b73b-dd5f5f6977b7.png" width="250" alt="LosslessCut over VNC">
