### ISSUE TITLE
Provide convenient ways to import project

### ISSUE THREAD

**Issue by rieje** [mifi/lossless-cut#1092]
**Is your feature request related to a problem? Please describe.**

In my opinion, it is cumbersome to import a project (e.g. select a csv file containing timestamps). When I launch losslesscut with a video, "File > Import Project (LLC)... > ..." defaults to a basic file selector with a list of Recent Files that is not helpful unless you've previously worked on a project for it to remember. Navigating a deep file hierarchy using a mouse is inefficient, particularly for someone who uses a CLI-manager and would like to avoid the mouse as much as possible, hence why I created a .csv file and want to to have LosslessCut just process the video with it.

**Describe the solution you'd like**

A few ideas to make it more convenient:

- [x] CLI option(s) to import project file
- [x] If given a full path as an argument, LosslessCut can use this to determine the directory to default to for the file selector
- [ ] Smartly suggest to also import project file when a video is opened, e.g. if a file in the same directory as the video is named `<video_name>*.<project_ext>` when the video name is `<video_name>.<ext>`, ask (or even better, provide an option to auto-accept) importing the project. Or just simply detect any potential project files and prompt the user if there are such files (I think this is pretty reasonable, I imagine it is rare that people tend to have videos stored in the same directory as e.g. non-project-related .csv files unless it's project-related. #1185

**Comment by mifi** [comment]
> * CLI option(s) to import project file

this should already work:

```bash
/Applications/LosslessCut.app/Contents/MacOS/LosslessCut /path/to/MyProject.llc 
```

The other two points are good suggestions.

**Comment by mifi** [comment]
the last point will be tracked in a different issue, closing this

**Comment by rieje** [comment]
> > * CLI option(s) to import project file
> 
> this should already work:
> 
> ```shell
> /Applications/LosslessCut.app/Contents/MacOS/LosslessCut /path/to/MyProject.llc 
> ```
> 
> The other two points are good suggestions.

I have a .csv file containing time segments to import but it does not seem to work: `losslesscut /path/to/myproject.csv` or `losslesscut /path/to/myvideo.mp4 /path/to/myproject.csv`. For the latter, it treats both the .csv file and the video as items for the batch file list. I suppose the .csv file is not a real .llc project because it does not reference the path to the video so I'm wondering if `losslesscut /path/to/myvideo.mp4 /path/to/myproject.csv` should be supported.

**Comment by mifi** [comment]
maybe #1185 could solve the problem: if a csv file is named the same as the video file, then if that feature is implemented, it would auto-load the csv file if the video file is loaded
