### ISSUE TITLE
Bug: “LosslessCut is installation is broken” | Flatpak

### ISSUE THREAD

**Issue by 0av** [mifi/lossless-cut#1095]
Hello,

there is a problem in the Flatpak package of LosslessCut. The error message is:

    LosslessCut is installation is broken
    Command failed with ENOENT: /app/lossless-cut/resources/ffmpeg -hide_banner -f lavfi -i nullsrc=s=256x256:d=1 -f null - spawn /app/lossless-cut/resources/ffmpeg ENOENT

The concerning installed packages are:

    LosslessCut – no.mifi.losslesscut – 3.44.0
    ffmpeg-full – org.freedesktop.Platform.ffmpeg-full – 21.08

**Comment by mifi** [comment]
I don't officially distribute flatpak. Maybe you can file an issue at their repo: https://github.com/flathub/no.mifi.losslesscut/issues
