### ISSUE TITLE
UI performance regression

### ISSUE THREAD

**Issue by howff** [mifi/lossless-cut#1097]
I think there's been a UI performance regression somewhere between 3.39 and 3.44. Operations like seeking and single-stepping through frames has a very noticeable delay on 3.44 which wasn't present on 3.39. And I can run the two side-by-side with the same video to verify this. It's not related to any particular video file.

```
{
  "state": {
    "filePath": "C:\\Users\\arb\\Documents\\2022_04_01_18_00_01.mp4",
    "fileFormat": "mp4",
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 3840,
        "height": 2160,
        "coded_width": 3840,
        "coded_height": 2160,
        "closed_captions": 0,
        "has_b_frames": 0,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuvj420p",
        "level": 51,
        "color_range": "pc",
        "color_space": "bt470bg",
        "color_transfer": "smpte170m",
        "color_primaries": "bt470bg",
        "chroma_location": "left",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "30/1",
        "avg_frame_rate": "20491875/683491",
        "time_base": "1/90000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 10935856,
        "duration": "121.509511",
        "bit_rate": "42066075",
        "bits_per_raw_sample": "8",
        "nb_frames": "3643",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "rotate": "90",
          "creation_time": "2022-04-01T17:02:04.000000Z",
          "language": "eng",
          "handler_name": "VideoHandle",
          "vendor_id": "[0][0][0][0]"
        },
        "side_data_list": [
          {
            "side_data_type": "Display Matrix",
            "displaymatrix": "\n00000000:            0       65536           0\n00000001:       -65536           0           0\n00000002:            0           0  1073741824\n",
            "rotation": -90
          }
        ]
      }
    ],
    "copyStreamIdsByFile": {
      "C:\\Users\\arb\\Documents\\2022_04_01_18_00_01.mp4": {
        "0": true
      }
    },
    "cutSegments": [
      {}
    ],
    "mainFileFormatData": {
      "filename": "C:\\Users\\arb\\Documents\\2022_04_01_18_00_01.mp4",
      "nb_streams": 1,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "121.511000",
      "size": "639738808",
      "bit_rate": "42118906",
      "probe_score": 100,
      "tags": {
        "major_brand": "mp42",
        "minor_version": "0",
        "compatible_brands": "isommp42",
        "creation_time": "2022-04-01T17:02:04.000000Z",
        "com.android.version": "10"
      }
    },
    "rotation": 360,
    "shortestFlag": false
  },
  "platform": "win32",
  "version": "3.44.0"
}
```

I might try and find which in version it started, unless you've got some ideas?

**Comment by mifi** [comment]
Hi. Is the delay
1. between the time you press the seek button and the video seeks to the correct frame
2. or between the time you press the seek button and the cursor moves on the timeline?

**Comment by howff** [comment]
I think it's both, there is a pause and then the cursor moves at the same time as the video updates.

**Comment by mifi** [comment]
Is it possible to capture the phenomena on video? Also is it consistent? (Happens every single time) I cannot see any consitent difference on macos

**Comment by Apposite245** [comment]
Just to chime in, I'm experiencing similar behavior. 

Upon Seeking it will seek smoothly and quickly for around 10 seconds and then hang for 2-3 seconds before continuing to seek smoothly.

**Comment by mifi** [comment]
@Apposite245 is this also on Windows? And are you talking about the video image or the timeline marker?

**Comment by 77722m** [comment]
Me, too.

**Comment by mifi** [comment]
I assume you're both on Windows and that the problem doesn't exist in v3.39, is that correct @Apposite245 @77722m ?

**Comment by 77722m** [comment]
> 我假设您都在 Windows 上，并且 v3.39 中不存在该问题，对吗？ @Apposite245 @77722m ?

yes

**Comment by mifi** [comment]
from https://github.com/mifi/lossless-cut/discussions/1065#discussioncomment-2683341

> I'm using 3.39.0 presently; tried upgrading to 3.44.0 but the preview performance (using keyboard to seek) is much poorer, so I suppose I will stick with 3.39 for now
> Edit: I stepped back through more recent versions and it seems that performance issue was introduced between 3.42 and 3.43, so now I'll begin using 3.42.

**Comment by mifi** [comment]
Maybe react 18 with concurrent mode could also solve some of these issues.

**Comment by Apposite245** [comment]
> I assume you're both on Windows and that the problem doesn't exist in v3.39, is that correct @Apposite245 @77722m ?

Sorry for the late reply, been busy. Anyway yes I am also on windows. Started on Windows 10 and now 11 and the issue is still occurring in version 3.44.0. I concur with the comment you linked, the issue does seem to be alleviated in version 3.42

**Comment by PlumErrand** [comment]
Just wanted to say I am also experiencing this issue on Windows 10, version 3.44.0. The seeking is normal for around 5-10 seconds then a delayed 2-3 second pause happens after seeking, then back to normal speed for 5-10 secs, etc. This issue was not occurring in any of the previous versions. Thanks.

**Comment by Apposite245** [comment]
Small update, after using 3.42 for a while, the issue is better than the current release however it is still present. On the current release my experience is identical to what @PlumErrand described.  In 3.42 the behavior is the same however the pause/delay is only for 1-2 seconds instead of 2-3 seconds.

Hardware information:
Windows 11 Version:21H2 Build:22000.675
CPU:AMD Ryzen 3700x
GPU:Nvidia RTX 2070 Super
RAM:16 GB 3600 mhz
Video is being read from an Nvme SSD.

**Comment by mifi** [comment]
if someone could record a little screen recording showing the issue, that would be extremely helpful

**Comment by Apposite245** [comment]
https://www.youtube.com/watch?v=LB20fyxMDU4

The HD version is still processing at the time I'm posting this so you may want to wait until it's done.

Anyway, the most noticeable example of the issue is at 33 seconds, however it's occurring throughout the clip.
I'm holding down Right Arrow aka Seek Forward the entire clip.
Test was done on version 3.44.0 under the same computer and OS specs as I listed above.

**Comment by mifi** [comment]
Thanks. It seems like the whole UI is freezing for a second, am I right? I'm suspecting that if you try to click on anything at the time that it hangs, it will not respond until 1 second later?

**Comment by Apposite245** [comment]
I'm not sure, I can give clicking on other ui elements a shot later tonight. Will update when I do.

**Comment by Apposite245** [comment]
@mifi You're right about the full UI locking up. Can't interact with any UI elements when the freezes occur.

**Comment by mbs** [comment]
Still seems to exist on 3.45.0.  Some extra experience details: Does not seem to make a difference what quality/size/bitrate the video is.   3.45.0 has about 1s delay on my machine between single cursor button press from idle and seek bar/video frame update.  If I hold down the cursor button, or press it quickly (which would be my normal use case looking for my cutpoints), I can see it quickly updates the 'seek' carat (with the triangle pips), plus the timestamp, but not the 'position' carat (line without triangles) for a while (so they are shown separately), without updating the video.  Eventually the whole UI hangs for a few seconds while it catches up.  Once caught up, it updates the video and the position carat simultanously, then the pattern repeats.  If at any point during the cycle I let go of the cursor key, the position carat and video frame update to the seek carat location with various performance between instant and up to about a second.

**Comment by mifi** [comment]
@mbs thanks for details. you on windows too?

**Comment by mbs** [comment]
> @mbs thanks for details. you on windows too?

Yes, correct.  Windows 10.0.19042.1706

**Comment by mifi** [comment]
Ok guys I think I've found the issue. fix coming in next version
