### ISSUE TITLE
Export Video at 1.25x Speed

### ISSUE THREAD

**Issue by ms-2525** [mifi/lossless-cut#1098]
Please add a feature whereby the videos can be exported at a higher playback speed.
Right now if i increase the Playback rate and then export the file, the duration of the file is not reducing
If the length of the video is 4 mins then if I export it at a higher playback rate of 126%, the the duration/length of the exported file should be around 3 mins 12 sec. While playing the video in the software, the speed of the video is increased but the exported file is not at the higher speed i.e. it remains at 4 mins duration.

I thought the MOV Faststart will help me achieve this but it did not. I tried both exporting when the MOV Fastrack was enabled and then disabled but in both the cases the duration of the video is not reducing.

**Comment by mifi** [comment]
Hi. The playback rate is just for preview, it will not change the file in any way. In fact as far as I know it’s not possible to change playback rate of a video losslessly, so it’s not aomething that can be implemented.
