### ISSUE TITLE
[Request] Release portable builds

### ISSUE THREAD

**Issue by FatOrangutan** [mifi/lossless-cut#11]
Please consider releasing self-contained [portable](http://portableapps.com/about/what_is_a_portable_app) builds.

Thanks.

**Comment by mifi** [comment]
Which steps are needed for it becoming a portable app? It should already run fine from usb sticks etc. PRs are welcome. Or an example shell script for packaging it as a portable app is welcome.

**Comment by TechManiacHD** [comment]
It is running like a portable app :) Sometimes I am using Windows machine that has no admin account and it's perfectly fine.

**Comment by mifi** [comment]
Ok, I'll close this because of no answer.
