### ISSUE TITLE
Select thumbnail / cover art from timeline (screenshot)

### ISSUE THREAD

**Issue by mifi** [mifi/lossless-cut#1100]
Currently there is no way to directly select cover art as a frame from the timeline.

As a workaround until this is implemented, you can take a snapshot using the <kbd>C</kbd> hotkey, (be sure to select JPEG output format first), then follow the instructions in this video https://www.youtube.com/watch?v=4pYJ93cn80E in order to attach the snapshot you just took as a cover art for your video.

### Originally Discussed in https://github.com/mifi/lossless-cut/discussions/1099

<div type='discussions-op-text'>

<sup>Originally posted by **fade0ff** April  2, 2022</sup>
I'm aware of the possibility to add an external image as thumbnail, but given that the tool already has access to all necessary resources, it would be much more convenient if there was an option to use the currently displayed frame as embedded thumbnail for the exported video. Any chance this could happen?</div>

**Comment by mifi** [comment]
now implemented. In the next version, a new bindable keyboard shortcut "Set current frame as cover art" will be available

**Comment by rd-sf** [comment]
I tested this by binding "META + U" on MacOS, then stopped the LC timeline on a keyframe, and using the shortcut.  An image file was created in the same directory as source video, but after exporting the video I don't see a difference in Plex.  I.E. the thumbnail that Plex displays is different, but it's not the frame I chose.  Is the Cover Art image muxed into the output file (in this case an MKV) ?
![IMG_8640-00_00_35_212_jpeg_and_Plex](https://user-images.githubusercontent.com/2807325/196009966-8464af66-dc44-4e35-8e0d-92cdceabef89.jpg)

**Comment by fade0ff** [comment]
Thanks! Seems to work for me.
But is it on purpose that a screenshot is created in the same folder? Shouldn't it at least be automatically deleted?

**Comment by mifi** [comment]
@rd-sf you can try to open the file with VLC, it should show the thumbnail under Window -> Media Information, does it not? maybe try mp4 instead and see if that works?

@fade0ff  TBH I don't know how to do it without creating a file first. losslesscut could indeed auto delete the file, i was just a bit lazy when implementing this
