### ISSUE TITLE
Batch list: need to reorder items before merging

### ISSUE THREAD

**Issue by slrslr** [mifi/lossless-cut#1101]
Hi,
when i want to merge multiple files - lets say 15 into one, the fastest method seems to be drag & drop these from file manager to LC 3.43.
It currently trigger batch sidebar (previously it triggered different dialog which seemed better for merging).

So in this side batch menu i can remove selected items which is good, but i am unable to drag/drop the item to re-order it. Someone [mentioned sorting option](https://github.com/mifi/lossless-cut/issues/1043) but that i had not needed so far. Can you allow mouse drag drop items within batch list sidebar to re-order it? Dropping file from file manager seems to add file to the end of the list, not to exact position in the list.

**Comment by mifi** [comment]
Hi. Please try the newest version before reporting issue, it has this already implemented

**Comment by slrslr** [comment]
Indeed, new version has this feature. Thank you!
