### ISSUE TITLE
Text chapters/Youtube import not working properly

### ISSUE THREAD

**Issue by Hlurbre** [mifi/lossless-cut#1102]
On importing mp4 file downloaded from youtube I wanted to add chapters present in youtube video to the mp4 file since there is that option but once imported the chapter timings were totally off. 

This is the video:
https://www.youtube.com/watch?v=qwA6MmbeGNo

these are the chapters:

0:00 - Introduction/whoami
5:13 - Important Disclaimer
7:37 - OSINT Overview
12:06 - Taking Effective Notes
20:09 - Introduction to Sock Puppets
22:52 - Creating Sock Puppets
37:19 - Search Engine Operators
1:00:39 - Reverse Image Searching
1:07:58 - Viewing EXIF Data
1:14:27 - Physical Location OSINT
1:23:43 - Identifying Geographical Locations
1:34:16 - Where in the World, Part 1
1:35:34 - Where in the World, Part 2
1:46:58 - Creepy OSINT
1:47:49 - Discovering Email Addresses
2:03:42 - Password OSINT - Introduction
2:07:25 - Hunting Breached Passwords Part 1
2:19:25 - Hunting Breached Passwords Part 2
2:29:23 - Hunting Usernames & Accounts
2:38:07 - Searching for People
2:47:54 - Voter Records
2:51:46 - Hunting Phone Numbers
3:03:04 - Discovering Birthdates
3:06:42 - Searching for Resumes
3:11:51 - Twitter OSINT Part 1
3:26:46 - Twitter OSINT Part 2
3:41:57 - Twitter OSINT Part 3
3:47:22 - Facebook OSINT
4:00:33 - Instagram OSINT
4:09:07 - Snapchat OSINT
4:11:37 - Reddit OSINT
4:17:32 - LinkedIn OSINT
4:25:41 - TikTok OSINT
4:29:05 - Conclusion

but..once imported it looks like this:

![image](https://user-images.githubusercontent.com/102910897/161454573-f668188c-eb88-4c17-8bef-a1ea118ec523.png)

And error report:

No error

{
  "state": {
    "filePath": "G:\\Download\\the cyber mentor\\Open-Source Intelligence (OSINT) in 5 Hours - Full Course - Learn OSINT!.mp4",
    "fileFormat": "mp4",
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1080,
        "closed_captions": 0,
        "has_b_frames": 1,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 40,
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "30/1",
        "avg_frame_rate": "30/1",
        "time_base": "1/90000",
        "start_pts": 2970,
        "start_time": "0.033000",
        "duration_ts": 1457622000,
        "duration": "16195.800000",
        "bit_rate": "246438",
        "bits_per_raw_sample": "8",
        "nb_frames": "485874",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "VideoHandler",
          "vendor_id": "[0][0][0][0]"
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "44100",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/44100",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 714237952,
        "duration": "16195.871927",
        "bit_rate": "127999",
        "nb_frames": "697498",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "SoundHandler",
          "vendor_id": "[0][0][0][0]"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "G:\\Download\\the cyber mentor\\Open-Source Intelligence (OSINT) in 5 Hours - Full Course - Learn OSINT!.mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {
        "start": 0,
        "end": 33
      },
      {
        "start": 33,
        "end": 39
      },
      {
        "start": 39,
        "end": 184
      },
      {
        "start": 184,
        "end": 222
      },
      {
        "start": 222,
        "end": 313
      },
      {
        "start": 313,
        "end": 402
      },
      {
        "start": 402,
        "end": 445
      },
      {
        "start": 445,
        "end": 457
      },
      {
        "start": 457,
        "end": 478
      },
      {
        "start": 478,
        "end": 547
      },
      {
        "start": 547,
        "end": 697
      },
      {
        "start": 697,
        "end": 711
      },
      {
        "start": 711,
        "end": 726
      },
      {
        "start": 726,
        "end": 867
      },
      {
        "start": 867,
        "end": 1052
      },
      {
        "start": 1052,
        "end": 1165
      },
      {
        "start": 1165,
        "end": 1209
      },
      {
        "start": 1209,
        "end": 1372
      },
      {
        "start": 1372,
        "end": 1423
      },
      {
        "start": 1423,
        "end": 1541
      },
      {
        "start": 1541,
        "end": 1606
      },
      {
        "start": 1606,
        "end": 1745
      },
      {
        "start": 1745,
        "end": 1763
      },
      {
        "start": 1763,
        "end": 2056
      },
      {
        "start": 2056,
        "end": 2134
      },
      {
        "start": 2134,
        "end": 2239
      },
      {
        "start": 2239,
        "end": 2287
      },
      {
        "start": 2287,
        "end": 2517
      },
      {
        "start": 2517,
        "end": 2818
      },
      {
        "start": 2818,
        "end": 2842
      },
      {
        "start": 2842,
        "end": 2869
      },
      {
        "start": 2869,
        "end": 2874
      },
      {
        "start": 2874,
        "end": 3106
      },
      {
        "start": 3106
      }
    ],
    "mainFileFormatData": {
      "filename": "G:\\Download\\the cyber mentor\\Open-Source Intelligence (OSINT) in 5 Hours - Full Course - Learn OSINT!.mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "16195.872000",
      "size": "774546824",
      "bit_rate": "382589",
      "probe_score": 100,
      "tags": {
        "major_brand": "isom",
        "minor_version": "512",
        "compatible_brands": "isomiso2avc1mp41",
        "encoder": "Lavf58.29.100"
      }
    },
    "rotation": 360,
    "shortestFlag": false
  },
  "platform": "win32",
  "version": "3.44.0"
}

**Comment by mifi** [comment]
thanks for reporting. there was indeed a bug with parsing short hour format. will fix this
