### ISSUE TITLE
MPEGTS file after conversion to MP4 Video is not shown in LosslessCut

### ISSUE THREAD

**Issue by GeorgS1** [mifi/lossless-cut#1103]
I'm new to LosslessCut and I'm very enthusiastic with it. 
Today I got a problem with an MPEGTS file, which is transferred from a TV. 
1. I open the file
2. Cutting it is very slow because the file is big (5GB) and the format is not supported so it is internally converted
3. I want to convert it first to MP4 and then reopen it so cutting will be easy and fast.
4. I cut the first minute only to have an example and save it to my disk
5. Viewing the 1 minute clip with MPC-HC or VLC under Windows10 works perfectly
6. Close LosslessCut and reopen it
7. Open the new 1 minute file
8. File is read and can be cut, but the video preview while cutting is not there. The thumbnails can be shown, but no video. Audio is played in LosslessCut.

My idea is that it might be maybe related to the tracks in the original mpeg2 video.

I attach a hardcopy of the track selection.
The protocol of the the first step, the conversion of 1 minute from TS to MP4 (I selected MPEG-4 Part 14)
![Track-Selection](https://user-images.githubusercontent.com/102989342/161606686-1518984a-7141-412b-8d7e-acaa2dc13746.JPG)
[mp2 to mp4 1 minute .txt](https://github.com/mifi/lossless-cut/files/8412154/mp2.to.mp4.1.minute.txt)

A hardcopy of the trial to edit the 1 minute mp4 file which is not showing the video
![Edit of 1 minutes MP4](https://user-images.githubusercontent.com/102989342/161606796-4414d962-58e7-42fe-a94f-8546464dcca5.JPG)
[Edit mp4 1 minute file .txt](https://github.com/mifi/lossless-cut/files/8412159/Edit.mp4.1.minute.file.txt)

Here comes the 1 minute video. 
Ok it was to big I did cut it with LosslessCut to 20 seconds, and the effect is the same. LosslessCut does not show the video itrself, other programs do.

https://user-images.githubusercontent.com/102989342/161608369-26254bf3-01c9-418b-bd94-14975d2e0472.mp4

**Comment by GeorgS1** [comment]
Maybe the problem was that the video track was not the first one? Or probably the track 0 which was for EPG, which was empty too?

**Comment by mifi** [comment]
Hi. Sorry for the delay! I'm not sure if putting mpeg2 video and mp2 audio is even officially supported in MP4 format. Maybe you could try MKV?

I tried your file and it does not play back on MacOS (quicktime). This probably indicates that it is not a supported combination. It does however work in VLC (but it plays almost everything).

I'm not sure I understand your initial problem, is it just that converting to supported format is slow? If so, there's not much to do about that right now unfortunately. in the future I plan on supporting more formats natively

**Comment by GeorgS1** [comment]
Hi Mikael, thank you for the reply.
The conversion from MPEG2 to MP4 works perfect and the speed of the conversion is also ok. 
I did also convert other MPEG2 videos to MP4 with LossLessCut and am very satisfied.

The problem with the file which I mentioned is that in LossLessCut I cannot see the "video preview". The thumbnails are shown. In the other converted MPEG2 videos both was shown the thumbnails and the "video preview".

I looked into what was different between the converted MPEG2 files and the main difference was that in the tracks for the file which did not show the "video preview", the video track was not on position 0 but on poosition 2.

Anyhow, I could cut it with zooming to the thumbnails so it is solved for me. Maybe just a hint for you that LossLessCut might look to the tracks to show the video track, even it is not on position 0.

**Comment by mifi** [comment]
Oh. I think the problem is that your video is mpeg2 / h262 codec, which is not supported by chromium and therefore also not lossslesscut. reference:
- https://groups.google.com/a/chromium.org/g/chromium-dev/c/8j1kXxWiWco?pli=1
- https://www.chromium.org/audio-video/

however in the future better suppport might come when i implement this #88

as a workaround you can "convert to supported format" -> "Fastest: Low playback speed (no audio)"

hope that helps.
