### ISSUE TITLE
Avoid superfluous cuts on contiguous segments?

### ISSUE THREAD

**Issue by Mrnofish** [mifi/lossless-cut#1104]
**Is your feature request related to a problem? Please describe.**
LossLessCut can be used to mark chapters in the exported file, absent material being cut in-between segments; these contiguous segments are simply a logical demarcation that has to do with the nature of the content instead, acting as bookmarks.

When a project includes both actual cuts (non-contiguous segments) and chapter marks (contiguous ones), applying Merge Cuts mode leads to all segments being saved to separate files, performing cuts, regardless of the segments being contiguous or not.

If Keyframe Cut is being used, this can lead to the chapter marks being shuffled around, whenever the chapter mark is not aligned with a keyframe.

**Describe the solution you'd like**
Ideally, I'd like LLC to avoid splitting consecutive, contiguous segments, i.e. whenever there is no material being cut in-between, and instead limit itself to placing a chapter mark.
If avoiding the extra splits is not feasible or exceedingly hard, it would be neat if LLC could "remember" the original position of the chapter mark, placing it on the selected frame, rather than moving it to the nearest keyframe.

**Describe alternatives you've considered**
The two alternatives I can see ATM are:

- Aligning chapter marks to a keyframe, and swallow the degree of inaccuracy.
- Using smart cuts, this however increase resource consumption, processing time, and there's a picture quality cost to be paid.

**Comment by mifi** [comment]
If what you're looking for is to just edit the chapters of a file, then you can use the special "Chapters only" export mode. It will not do any cuts but instead just modify chapters according to segments. Does that solve your problem?

**Comment by Mrnofish** [comment]
I'm aware of the Chapters mode, it does not address the scenario I've described above.

Let's say you have a project like this:

[###1###][###2###]---x---[###3###]

The 'cut' between segments 1 and 2 is virtual, there is no material being cut between 1 & 2, hence it's just a chapter mark.

However there is at least a real cut in the project, in this example between 2 and 3, thus Chapters Only won't do.

The cut between 1 and 2 is superfluous, i.e. LLC is exporting two different files which it then merges, but under certain circumstances the result is not equivalent to the source.

**Comment by mifi** [comment]
Ok I understand. I think it's a bit complicated to implement because not only would losslesscut need to prevent cutting/merging the contiguous segments, but I would need to correctly mark two or more chapters in the output segment of the non-cut segments with the correct actual timestamps (after cutting).

A simple alternative workaround would be to create a new function in the app's menu called something like "combine all contiguous segments", that will combine 1 and 2 in your example into 1 segment. although it would obviously lose the chapter information (they would be combined into one resulting chapter).

**Comment by Mrnofish** [comment]
> A simple alternative workaround would be to create a new function in the app's menu called something like "combine all contiguous segments", that will combine 1 and 2 in your example into 1 segment. although it would obviously lose the chapter information (they would be combined into one resulting chapter).

For new projects, one might as well not mark Chapters, but only real cuts, and then add back the missing chapter marks by editing the export at a later stage.

So for me personally, it wouldn't be an exceedingly useful addition.

My suggestion had the benefit to enable significant time savings, because chapter marking and cutting could be done in one step, instead of two.

**Comment by mifi** [comment]
I think it's such a complex change that it's not going to happen anytime soon unfortunately. I'm closing now, but can reopen if it becomes a popular feature request
