### ISSUE TITLE
aivx on export

### ISSUE THREAD

**Issue by bevels** [mifi/lossless-cut#1110]
Exported files from my Sony A7IV - Mov - Quicktime / MOV (Detected) - won't play in any media player. VLC error is...

_VLC could not decode the format "aivx" (No description for this codec)_

The files cannot be edited in Premiere Pro either, a similar "aivx" error occurs when trying to import the files.

Windows 10 X64

**Comment by mifi** [comment]
if you could provide the requested info, or a sample file, then I can try to look into it

**Comment by mifi** [comment]
possibly related #280

**Comment by mifi** [comment]
closing as duplicate of #280 then
