### ISSUE TITLE
您好，我将一个其它的音轨合并到我当前视频后，在视频播放时还是只播放我视频原有的音乐，又什么办法能把视频的音轨和我加进来的音轨给融合起来吗，让它们一起播放。简单点说就是我想要给我的视频添加背景音乐。万分感谢

### ISSUE THREAD

**Issue by grayVI** [mifi/lossless-cut#1111]
Please first search for your feature request under Issues or Discussions, maybe someone else already suggested it.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by taozi1996** [comment]
这是有损操作，losslesscut不能实现这点

**Comment by mifi** [comment]
Hi. From what I can tell from Google Translate you want to mix two audio tracks into one. this is not possible to do in a lossless way. It has already been suggested here #607
