### ISSUE TITLE
Import chapters is not detecting cut segments while opening a video in V3.44.0

### ISSUE THREAD

**Issue by tarungupta012345** [mifi/lossless-cut#1112]
While opening a video containing chapter it is not loading the cut segments while chapters are loading correctly
![image](https://user-images.githubusercontent.com/72178058/162800274-9377638a-89fa-492a-a5c2-661700dcb682.png)
![image](https://user-images.githubusercontent.com/72178058/162800979-31254975-280c-4e17-85a7-9db6c46a6ee9.png)

**Comment by mifi** [comment]
hi. try to toggle the YinYang symbol
