### ISSUE TITLE
installation is broken?

### ISSUE THREAD

**Issue by wicatfly** [mifi/lossless-cut#1114]
Hi，
When I opened LosslessCut.exe first time it show me the follow words:

LosslessCut is installation is broken
Command failed with EPERM: C:\Tools\LosslessCut-win-x64\resources\ffmpeg.exe -hide_banner -f lavfi -i nullsrc=s=256x256:d=1 -f null - spawn EPERM

And when I opened a file, it show me this

Failed to open file
Command failed with EPERM: C:\Tools\LosslessCut-win-x64\resources\ffprobe.exe -of json -show_chapters -show_format -show_entries stream -i I:\xxxxxxx.mp4 -hide_banner spawn EPERM

I'm running win10 on PC, thank you

In order to make it easier for me to help you, I ask that you please try these things first:
- Try with the newest version from GitHub: https://github.com/mifi/lossless-cut/releases/latest
- Check https://github.com/mifi/lossless-cut and **Known issues** / **Troubleshooting**
- Search for your problem under Issues or Discussions
- Please try other type of file and see if it works.

**Share information to help me understand**
- If you have an issue cutting a particular file, please also share the file, if possible. (or mail a link to finstaden@gmail.com if private.) Also please try to cut it with the ffmpeg command line directly.
- If you have a problem or an unexpected bug or crash, please open developer tools after starting LosslessCut and before doing the failing operation. Then share the output from the javascript Console. (Menu: Tools > Toggle Developer Tools)
- Please provide the error report if you got one (Menu: Help -> Report an error)

**Describe the bug**

**To Reproduce**
1. Open file '...'
2. Click on '...'
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]

**Additional context**

**Comment by mifi** [comment]
Hi
I assume you’re running the .exe download version. Can you try to zip version?

**Comment by wicatfly** [comment]
> Hi I assume you’re running the .exe download version. Can you try to zip version?

I've tried both two versions, the same issues.

**Comment by mifi** [comment]
Ah ok. Can you see if the file «C:\Tools\LosslessCut-win-x64\resources\ffprobe.exe» indeed exists or it’s missing? If it’s there, try to run it by double clicking. Maybe you need to click through some dialogs by Windows blocking unsafe executable. Same for ffmpeg.exe

Unfortunately there are issues with unsigned executables on windows, so not much I can do about it. The Windows Store version is signed and will not have this problem.

**Comment by mifi** [comment]
Alternatively if you cannot make it work, maybe you need to allow the exe files in your anti virus

**Comment by wicatfly** [comment]
> Ah ok. Can you see if the file «C:\Tools\LosslessCut-win-x64\resources\ffprobe.exe» indeed exists or it’s missing? If it’s there, try to run it by double clicking. Maybe you need to click through some dialogs by Windows blocking unsafe executable. Same for ffmpeg.exe
> 
> Unfortunately there are issues with unsigned executables on windows, so not much I can do about it. The Windows Store version is signed and will not have this problem.

Thanks, I'll try it later.

**Comment by mifi** [comment]
@kotep which version of losslesscut?

**Comment by mifi** [comment]
you're getting `EPERM` error from `ffprobe.exe` right?

do previous versions of llc work? if so, which version starts failing?

what happens if you run the included ffprobe.exe in the resources folder from the command line e.g. `C:\Tools\LosslessCut-win-x64\resources\ffprobe.exe -version`?

**Comment by mifi** [comment]
that's very odd. I can only think of windows' built in executable or virus protection preventing executing the new ffmpeg.exe because losslesscut recently upgraded to ffmpeg 5.0.1 in v3.46.2. (in 3.45.0 it was ffmpeg v4). Maybe it takes a while for windows to consider ffmpeg.exe v5.0.1 to be "safe". I know this is how MacOS works with its protection system for apps downloaded from the internet, so I assume Windows works similarly.

Just to be sure: You're also getting the error popup "LosslessCut is installation is broken" when opening losslesscut, right?

**Comment by mifi** [comment]
do you have anti-virus? does it work if you disable antivirus, or flag the ffmpeg.exe/ffprobe.exe files as "safe/whitelisted" in the antivirus software?

One theory I have is that it's something about your anti-virus or windows defender flagging the file you downloaded from gyan.dev as "safe" because it knows that many other people have downloaded that before (that URL or hash signature). But this new losslesscut version it has never seen before, so it flags the ffmpeg.exe as potentially a virus, because it doesn't know it as a safe origin.

**Comment by mifi** [comment]
so there's really something about that version. do you also get the error if you run 5.0.1 ffmpeg build downloaded from gyan.dev from the command line?

**Comment by mifi** [comment]
closing due to lack of response

**Comment by sujfuy** [comment]
Yep, love the program but I tried to update to the newest update and now I can't install it.  Can't uninstall the old one either... windows doesn't find it to uninstall.  Won't let me just delete the folder/directory.  I'll just have to switch back to the undesired program.

**Comment by mifi** [comment]
there is no installer for losslesscut, so there is no uninstall either. you just extract the folder in the zip and run it. then you delete the folder when you want to get rid of losslesscut
