### ISSUE TITLE
Error during playback triggers conversion even though video is playable (PIPELINE_ERROR_DECODE: VDA Error 4 3)

### ISSUE THREAD

**Issue by WestleyArgentum** [mifi/lossless-cut#1115]
**Describe the bug**
When previewing videos in Lossless Cut sometimes I will hit "problem points" (is what I'm calling them) which cause Lossless Cut to think the video is not playable and to run a conversion on it. The video is definitely playable, however, and if I know where one of these problem points is I can hop over it and continue to play the rest of the video just fine.

I think this could be caused by a number of things, including:
- Corruption in the video file
- My camera inserting weird things into the video (the problem points don't seem to occur at regular intervals, so this seems unlikely)
- Some problem with ffmpeg on my computer
- Something else?

I would love and appreciate any assistance anyone is willing to give in debugging this. I'm attaching a ~1 minute clip which contains one of these "problem points" at 23.971 seconds in (other than that the video plays back fine, skip over that point and the rest will play back as expected). EDIT: I cannot cut a section small enough to upload to github, here is a google drive link: https://drive.google.com/file/d/1LzKuzGPQR4PYRWX3DqlWqrEyRo1fk4xo/view?usp=sharing

I doubt the problem is Lossless Cut itself, but realistically I think the solution might be. I don't know enough yet to say for sure, but I suspect that when Lossless Cut encounters one of these problem points something could be done to "retry" playback (maybe a millisecond in the future or something) before resorting to conversion.

What I know so far:
- The error in the ffmpeg console says `onVideoError PIPELINE_ERROR_DECODE: VDA Error 4 3`
- It's a specific point in the video, not something that happens after X number of minutes playback
- There does not seem to be a consistent interval where these problem points occur. The first problem points that I encountered happened 16min 4seconds into a clip so I thought maybe it was long videos or something. But I have found sections of video longer than 16:04 that play back fine and sections where a problem point occurs in a short < 5 min clip.

**To Reproduce**
1. Open the provided video file
2. Play back until 23.971 seconds in
3. See `main.276ec257.js:2 onVideoError PIPELINE_ERROR_DECODE: VDA Error 4 3` in console

**Screenshots**
<img width="772" alt="Screen Shot 2022-04-15 at 16 06 30" src="https://user-images.githubusercontent.com/1900307/163591065-dfe9804c-bbfb-4377-8729-2e02b37cb5e2.png">

**Versions:**
 - OS: Mac OS 12.3
 - Lossless Cut: Version 3.44.0 (3.44.0)
 - Camera: Sony a6400
 - Video: 4k at 30 frames a second into an MPEG-4
 - ffmpeg:
 ```
ffmpeg version 5.0 Copyright (c) 2000-2022 the FFmpeg developers
  built with Apple clang version 13.0.0 (clang-1300.0.29.30)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/5.0 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
 ```

**Comment by mifi** [comment]
Hi.

Thanks for your detailed explanation. I think there's probably a bug in electron/chromium that is getting triggered here. The reason why losslesscut is auto converting to supported format when it hits this error is because some files trigger this error immediately, and it means the file is not playable and needs to be converted. See #804

I think the only right solution is to introduce an option in losslesscut for whether or not losslesscut should automatically convert a file to supported format. what do you think?

**Comment by mifi** [comment]
I think this is the same issue as #776

See if disable "Auto convert to supported format" in settings helps

**Comment by mifi** [comment]
I also noticed this happening just now. No idea why, I cannot reproduce also
