### ISSUE TITLE
Issue- Cutting mp4 using NC mode exports audio only

### ISSUE THREAD

**Issue by profucius** [mifi/lossless-cut#112]
The idea behind the new feature to cut multiple segments at a time is great. However, whenever I make the multiple clips and export using NC (Normal Cut) mode, it does clip the times correctly however there is only audio and no video. I wish to be able to do this when clipping smaller video files with too-few keyframes.

I have reproduced this on multiple machines and video codecs using the same version 2.1.0.

**Comment by mifi** [comment]
Your issue happens with just one segment too right? So it doesn't have anything to do with multi cut?

I tried multi cutting a mkv file with NC, and it works for me, there is only sound in the beginning of the video but that's a known issue #13

**Comment by profucius** [comment]
Ah yes I just tried a single cut and the same issue occurred.

This is an .mp4 file. I've tried two types of mp4 files, one was from my phone camera, and another was from a screen recording app on windows. Both same issue.

**Comment by mifi** [comment]
Which player are you using? Does it work in vlc?

**Comment by profucius** [comment]
Yes, VLC and Pot player and the Windows media player all play audio with no video.

**Comment by mifi** [comment]
yeah, please upload

**Comment by profucius** [comment]
[](https://tinyurl.com/example-audioonly)

I clipped a section of a video with the issue using KC, which works. If you download this video and load it into LosslessCut, then cut any section and export using NC, you'll see it only exports the audio and not the video.

**Comment by mifi** [comment]
So your problem is solved if you use KC?

**Comment by profucius** [comment]
If I use KC, yes audio+video export successfully. However the reason that I wanted to use NC is because as I understand it, NC can cut at an exact time, while KC only cuts at the nearest keyframe. Some of the videos that I process, I do need the exact time precision, as there may be unnecessary video/audio that play between the nearest keyframe and when I want the video to actually start.

**Comment by geh** [comment]
Can confirm this is happening with Losslesscut  3.23.8, cutting a mp4 file generates a merged file with no video, only keyframe cut maintains video. Original file seems fine (a mp4 generated from a zoom meeting recording).

**Comment by geh** [comment]
It also happens with Losslesscut  3.17.27.

**Comment by geh** [comment]
A "workaround" I discovered was to re-encode the Zoom recording with ffmpeg inserting crazy amounts of keyframes:

ffmpeg -i zoom_recording.mp4 -x264opts no-scenecut -g 10 ready_for_losslesscut.mp4

(ready_for_losslesscut.mp4 is a HUGE file of course)

Then in losslesscut I use keyframe mode to edit, which works reasonably well.

Then I run again ffmpeg from command line, without flags, to obtain a small file again.

**Comment by mifi** [comment]
I think this issue is due to not enough keyframes. closing this because there are many issues like this
