### ISSUE TITLE
.mov Unsupported No Audio Playback Help

### ISSUE THREAD

**Issue by pvtpilot** [mifi/lossless-cut#1124]
I have been, for the past month, using LossLessCut on Windows to cut/parse videos (taken with various iPhones) from 2016-present, in chronological order.  I've had no problems until October 2019, but now have a vexing issue at import.  When I drag the movie to import into LossLessCut, it says it is converting to a supported format.  Not all videos have this "error," though all videos were taken with the same iPhone!  For example, Video 1, taken with iPhone X on Oct 14, 2019 imports FINE, but a Video B, taken with the same phone just 2 days later has that import issue.  Video C, taken with the same phone, but another 10 hours later, has NO issues with import.  Do you have any idea what the issue could be?

**Comment by mifi** [comment]
Hi. Could you check developer tools if there is any error message? Even better if you could share a file that shows the problem

**Comment by pvtpilot** [comment]
[Please do not share these videos of my children.  I had to remove the GPS data in a frustrating way, and then trim them on my MacBook before uploading here.  I tested the new files on LossLessCut, and they perform the same ways as the originals.]
IMG_4427 does NOT import the way I expect, IMG_4732 does.

https://user-images.githubusercontent.com/34127618/164264606-b7c7c887-ab58-4bbd-b7c0-1993166e6310.mov

https://user-images.githubusercontent.com/34127618/164264934-bb538359-5b31-4fff-867a-b7ffe03f2452.mov

![error message](https://user-images.githubusercontent.com/34127618/164262638-b1179967-e328-4275-a132-d856bd664a7a.png)

**Comment by mifi** [comment]
Thanks for providing the files

the reason why the first file needs to be converted to a supported format, and the second file does not is that the first one is in HEVC/H265 format which is not natively supported in losslesscut, while the second one is h264 which is supported.
h265 support is something I want to add but haven't found a good solution yet, see #88
