### ISSUE TITLE
High write to SSD of ffmpeg.exe

### ISSUE THREAD

**Issue by Tery1108** [mifi/lossless-cut#1126]
Hello.

Lossless-cut is great software, thank you.

(I'm sorry I'm not good at English)

When I checked the amount of writing to SSD because I wanted to save writing to SSD,
When I output a 4GB MP4 cut with a Lossless cut, 16GB is written to the SSD.
The files output to the working folder are a 4GB split file and a 4GB completed MP4 file.
But ffmpeg.exe writes 16GB to SSD.

Is there a way to reduce writes?

**Comment by Tery1108** [comment]
I also tried other software.

Separated and merged with LosslessCut or Vidcutter and output 5GB MP4, it was written to SSD 3-4 times 5GB (15-20GB),

And when I separate and merge with CutAssistant (Mp4box), it writes to SSD twice as much as 5GB MP4 (10GB).
However, Cut Assistant is quite slow in output.

When only separate file output with LosslessCUT, twice as much as 5GB MP4 is written to SSD(10GB).

When only merging 5GB MP4 + 5GB MP4 with Avidemux or Area61 Movie Maker(ffmpeg), write 10GB to SSD.

**Comment by mifi** [comment]
Hi. So what you're saying is that all the different software you tried will write 2x or more of the file's size as output to the SSD? I don't really know why that is, but it could be due to some internal operating system mechanism, and I don't know how losslesscut can improve upon that.

**Comment by Tery1108** [comment]
Thank you mifi,

When the completed file after cutting and merging is 5GB,
Older software called Cut Assistant only writes 5GB separate and 5GB merge to SSD.(10GB)
Lossless CUT and Vidcutter write 3-4 times 5GB to SSD.(15-20GB)

Lossless Cut is perfect for editing and very easy to use.
However, considering the write life of SSD, I thought it would be good if the number of writes to SSD was reduced.

However, I am very grateful to use Lossless Cut.

**Comment by mifi** [comment]
I don't really know how to reduce this writing from ffmpeg/losslesscut, but as a remedy maybe you could mount a RAM-filesystem and write files there. Then after the export is finished you can move the file to the SSD and it should only write 5gb.

**Comment by Tery1108** [comment]
mifi,Thank you very much.

It's a good idea to use a RAM drive.

I edit a lot of videos,so
for the time being, I decided to separate only large videos with Lossless cut and merge it with the joiner app.

**Comment by mifi** [comment]
ok, i'm going to close this because i don't know how to improve this

**Comment by mattack1** [comment]
Aren't there prefs to change the temp file locations? If they use a different location for temp files, then only the 'final' file will be written to the SSD?  (MAYBE I'm thinking of a different program I use often, kmttg, which does various interactions with Tivos.. and basically all of my use of LosslessCut is from video files I get via use of kmttg).

**Comment by mifi** [comment]
by temp file, i'm assuming you mean the exported segments? you can change working directory which is where losslesscut will output all files. if you want to save ssd cycles, maybe you can set working directory to a different place, then later you can move the final file to the ssd manually (or with some automation tool/script)

> Though not exactly the same thing, I guess I do wish it would 'assemble in place' the destination file, instead of making a bunch of separate cuts then merging them. That would just save space for disk space reasons.

I don't think this is possible unfortunately
