### ISSUE TITLE
Feature request- Timeline zoom in/out

### ISSUE THREAD

**Issue by profucius** [mifi/lossless-cut#113]
For larger videos (ex. 1 hour) it is nearly impossible to be accurate when creating clips without the ability to zoom in to the timeline. A simple zoom in/out feature would be great.

**Comment by mifi** [comment]
I agree. For now you can use the arrow keys and `,` `.`

**Comment by mifi** [comment]
zoom now implemented

**Comment by YousufSSyed** [comment]
@mifi I couldn't figure out how to zoom in and out the timeline, I made [a discussion](https://github.com/mifi/lossless-cut/discussions/1638) about it.
