### ISSUE TITLE
Allow defaulting to no audio export

### ISSUE THREAD

**Issue by aaime** [mifi/lossless-cut#1135]
When working on my bike recordings, it's a bit annoying to have to disable audio export for every single file (I add music on top instead).

While it's just one click away in the main UI, it would be nicer to have a setting that allows setting a default "audio export" value, or
having a "lock" icon like it's available for the default export format.

**Comment by mifi** [comment]
sounds like a useful feature. It's already in the task list of the issue #371 - so I'll close this issue to increase maintainability
