### ISSUE TITLE
Option to register as CLI app

### ISSUE THREAD

**Issue by mklaber** [mifi/lossless-cut#1136]
**Is your feature request related to a problem? Please describe.**

I'm having trouble executing the CLI example from the README: https://github.com/mifi/lossless-cut#open-one-or-more-files

**Describe the solution you'd like**

It would be helpful if there were an option within LLC to register the app as a CLI app—the readme shows CLI examples like [this one](https://github.com/mifi/lossless-cut#open-one-or-more-files) but doesn't really say how to register `LosslessCut` in your terminal. Perhaps under the "Tools" menu?

For example, VS Code has a "Install 'code' command in PATH" as described [here](https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line).

**Describe alternatives you've considered**

I'm using an `alias` registered in my dotfiles: `alias losslesscut='/Applications/LosslessCut.app/Contents/MacOS/LosslessCut'`

**Additional context**

Apologies if it already does this somehow and I missed it :-)

**Comment by mifi** [comment]
I think this issue is specific to MacOS because on Linux and Windows you can just run `./LosslessCut.exe arg1 arg2` but I agree that it makes sense to add to readme. I will add.

**Comment by mifi** [comment]
I think an option to register it from within losslesscut is not something im going to implement due to differences between platforms adding complexity... Unless it can be done with a single function call to an npm module that handles this for electron apps, then I'm open for a PR

**Comment by wthueb** [comment]
> I think this issue is specific to MacOS because on Linux and Windows you can just run `./LosslessCut.exe arg1 arg2` but I agree that it makes sense to add to readme. I will add.

On Windows if you install via the Microsoft Store, you cannot directly run the .exe (anymore, as of Windows 11 24H2). There's ways to run it using PowerShell (see [here](https://github.com/nushell/nushell/issues/15158)), but that requires using PowerShell as your shell. An app execution alias would allow Windows users to get around all of that.

**Comment by mifi** [comment]
I don’t know much about this, but if someone can provide some step by step instructions on how to add an app execution alias for losslesscut (ms store), i can add those to the cli docs
