### ISSUE TITLE
[Enhancement] Use JSON as the format for `lossless-cut` project file

### ISSUE THREAD

**Issue by pidgeon777** [mifi/lossless-cut#1137]
**Is your feature request related to a problem? Please describe.**

It would be great to parse `lossless-cut` project files so that parsed data could be used by other tools, for example for defining complex FFmpeg conversion tasks by making use of Python scripts.

**Describe the solution you'd like**

I propose to adapt the `lossless-cut` project file format to JSON format. Hopefully it won't be too much work to implement this, considering that the project file format is already quite similar to JSON.

**Describe alternatives you've considered**

As an alternative, JSON could be added as a further export format, and the tool could optionally be configured to automatically save and load project files in JSON format. This would guarantee a backward compatibility with the original `lossless-cut` project file format.

**Comment by mifi** [comment]
Hi. Unfortunately I think I'm not going to support JSON, because I like JSON5 much more and it's easier to work with (less sensitive to syntax errors). You can easily create a json5 to json converter though. just use the npm json5 module
