### ISSUE TITLE
there is an error in file  name  tempalte .templete result in duplicate file name 

### ISSUE THREAD

**Issue by maloadjav** [mifi/lossless-cut#1138]
i just try to cut file and i think i have problem with setting  but i dont know how to do

i try to  create a file name 34  when i cutting movies and there is 2 file  

34.mp4

and  34  hhd800.com@COGM-006-00.00.01.697-00.04.23.298-seg1  

how to solve this problem

[url=https://ibb.co/zmZhHLj][img]https://i.ibb.co/zmZhHLj/1.jpg[/img][/url] [url=https://ibb.co/G9db3MV][img]https://i.ibb.co/G9db3MV/2.jpg[/img][/url]

**Comment by maloadjav** [comment]
[url=https://imgbb.com/][img]https://i.ibb.co/sgqvJDk/1.jpg[/img][/url]
[url=https://ibb.co/G9db3MV][img]https://i.ibb.co/1M0wJX9/2.jpg[/img][/url]
[url=https://imgbb.com/]image upload[/url]

**Comment by mifi** [comment]
you cannot have 2 files with the same name, so you need to add some unique identifier to the template
