### ISSUE TITLE
[Feature suggestion] Visualize each subtitle line's display duration in waveform

### ISSUE THREAD

**Issue by cyzs233** [mifi/lossless-cut#1142]
- This will save users trouble to figure out where the dialogue begins&ends. Otherwise, they'll have to use other tools to log its corresponding timestamps.
- This will help avoid the awkward situation where dialogue is cut abruptly and leave unfinished conversation for viewers to wonder. Let the man speak!

Plus: Button/shortcut to quickly navigate between subtitle lines.

**Comment by mifi** [comment]
Hi. I'm not sure what you mean. Do you want to show the start and end time of the currently shown subtitle line, e.g. above the subtitle's text?

**Comment by cyzs233** [comment]
Something like this in the waveform. Green areas represent neighboring subtitles
![Untitled](https://user-images.githubusercontent.com/25927091/169672654-c72ad05a-9803-477d-bff4-fdb4e94dea48.png)
.

**Comment by mifi** [comment]
Ok now I see, you want to show all the subtitles somehow in the timeline. Does it have to be in the waveforms or just somewhere above the timeline?

**Comment by mifi** [comment]
I'll close this because I added your suggestion as a feature point in this issue: #250
thanks!
