### ISSUE TITLE
[Feature request] Smaller disk footprint

### ISSUE THREAD

**Issue by skycommand** [mifi/lossless-cut#1143]
Hello. 😊

After installing LosslessCut today, I noticed that its disk footprint could be significantly smaller. Currently, LosslessCut comes with two large files, FFmpeg.exe and FFprobe.exe, which occupy 182 MB. They are from the **static build** of FFmpeg.

You could reduce this 182 MB to half if you use the **shared build** of FFmpeg. There is only a small drawback: Instead of two files, you have to include 10 files. (LosslessCut already has 71.)

<details><summary>Here is where to get the shared build (click here to expand)</summary>

![FFmpeg builds](https://user-images.githubusercontent.com/17097175/167525476-dc8fe877-20f8-4fdc-8300-31f6d1805108.png)

</details>

**Comment by mifi** [comment]
Hi!
i'm not sure if this could have some other negative implications. I'm thinking that because they are not static builds, they might be missing some dependencies that are not installed on all computers, like core Windows libraries that might differ from OS to OS, possibly causing users to get an error if they are missing thse dependencies or have the wrong version

**Comment by skycommand** [comment]
Hi again.

The concern you are voicing is called "dependency hell." It is a known problem of Linux, not Windows. Ironically, the absence of dependency hell in Windows is because of its non-free, closed-source.

If you are still in doubt, you can:
- Run Dependency Walker
- Test your app on all versions of Windows released in the last ten years. There are just three of them.
- Let me do the above for you. I can test it on the five different versions of Windows released in the last 15 years.

**Comment by mifi** [comment]
Thanks for researching. This is definitely an improvement that I should test.
I'm not sure why the static builds are so much larger though. One would think that linking the exact same code but instead in a static way would yield approximately the same size as the sum of the non-static dlls

**Comment by skycommand** [comment]
Hello, @mifi. I made this simple request 17 releases ago, all of which could have had from smaller sizes. I hate to be pushy but fulfilling this request takes very little time.

**Comment by mifi** [comment]
Hi.
Im not using BtbN builds now. Am using gyan essentials build, so I would need to find out which build (if any) in btbn corresponds with the one I’m using now. Did you figure out why shared builds are smaller than static builds? Is it because ffmpeg and ffproble commands don’t need to duplicate their common dependencies?

**Comment by skycommand** [comment]
> I would need to find out which build (if any) in `btbn` corresponds with the one I’m using now.

Please see the screenshot I've posted. I've marked the correct item.

That said, [Gyan has shared builds too](https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z). Here is a comparison of their extracted sizes.

Build name | Size
-----------|-----
Essential, static build | 241 MB
Essential, static build, without `ffplay.exe` | 154 MB
Full, shared build | 148 MB

> Did you figure out why shared builds are smaller than static builds? Is it because `ffmpeg` and `ffproble` commands don’t need to duplicate their common dependencies?

Exactly. That's essentially why DLLs were invented – to reduce the app size by eliminating code duplication.

**Comment by mifi** [comment]
Ok i will try to use those for ffmpeg 6

**Comment by mifi** [comment]
Ive created a build that seems to pass. maybe you can test it: https://github.com/mifi/lossless-cut/actions/runs/4614814877
scroll down to find the artifacts

**Comment by skycommand** [comment]
I tried three projects with it. I can't even feel a difference!

**Comment by mifi** [comment]
ok, should be all good then!

**Comment by mifi** [comment]
do you happen to know if this also works for linux? i did the same for .so files (same as for .ddl files, place them in the same directory), but I don't know if that will actually work.

**Comment by skycommand** [comment]
I grabbed a copy of Ubuntu and tested it. It was tricky. Here is a screenshot.

![Ubuntu 64-bit-2023-04-07-05-36-58](https://user-images.githubusercontent.com/17097175/230527513-ae9959d3-44ec-461f-9d7e-5c867578a401.png)

Do you see those blue items, each with a 20—22 bytes size? They are symbolic links. (A symbolic link is not an actual file. It points to another file.) You need to be careful so as to preserve those.

**Comment by mifi** [comment]
I believe they are already preserved in LosslessCut, aren't they? Did you try to run losslesscut from the linux binary from here? https://github.com/mifi/lossless-cut/actions/runs/4614814877

**Comment by skycommand** [comment]
Yes. You have. A beta release will tell you if everything works.

**Comment by mifi** [comment]
what were the results when you tried to run dynamic linked ffmpeg on ubuntu?

**Comment by skycommand** [comment]
Here is how I got `ffmpeg` to work, with no symlinks.
![Ubuntu 64-bit-2023-04-07-20-23-30](https://user-images.githubusercontent.com/17097175/230656919-8b981681-f8e1-4012-af5a-91412ad69f34.png)

Here is proof that it worked.
![Ubuntu 64-bit-2023-04-07-20-46-15](https://user-images.githubusercontent.com/17097175/230656941-0c2b270d-8e6e-4051-b9d4-b043dbd098b8.png)

And here is LosslessCut using it.
![Ubuntu 64-bit-2023-04-07-20-49-19](https://user-images.githubusercontent.com/17097175/230656983-55c3d00a-519f-487a-b7ac-da12c94f9ab9.jpg)

**Comment by mifi** [comment]
nice, thanks. do you have ffmpeg (libav*) insalled in your system though? I'm afraid it's using those instead.

I think I will do something like this to be safe:
```js
spawn('ffmpeg', [], {env: {LD_LIBRARY_PATH: '/path/to/losslesscut'}})
```

- https://stackoverflow.com/questions/51930254/run-a-binary-file-with-shared-object-dependencies-on-nodejs-express-server
- https://stackoverflow.com/questions/25356641/distribute-so-file-on-linux
