### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by ibay770** [mifi/lossless-cut#1144]
Please first search for your feature request under Issues or Discussions, maybe someone else already suggested it.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

If its possible, integrate this into windows, so when you click on a video in explorer, options show up to cut /merge videos using LC engine under the hood.

**Comment by mifi** [comment]
i'm not sure what you mean. I think you can already right click a file in explorer and open with LosslessCut

**Comment by mifi** [comment]
Thanks for clarifying. I think this is not something LosslessCut will implement because this feature is very specific to Windows, while LosslessCut is a cross-platform app that is generalized to work on windows, macos and linux. Thanks anyways!
