### ISSUE TITLE
not merging files

### ISSUE THREAD

**Issue by L0rdsfav0r** [mifi/lossless-cut#1146]
I always have issues merging files. The only way I've ever been successfully merged files is by running them through handbrake first which defeats the purpose of having a software that can merge files without re-encoding. I have even tried exporting them from lossless cut in the same file format and it still will not merge them. It keeps doing that thing where it goes to like 300% and then gives up. I have videos that I rendered from shotcut in h264 format that I need merged...it only seems to work with videos encoded from handbrake.

**Comment by mifi** [comment]
are the files of the exact same format and codec parameters? resolution, fps, timebase, audio codec, audio rate etc? does it also fail with just 2 files? if so is it possible to share 2 small files that show the problem?

**Comment by L0rdsfav0r** [comment]
One file is very large….10 hr video the other is just a 7 second intro. They are the same format but I will check the other specifications. If I load each file into lossless cut and export individually before merging them shouldn’t that put them both in the same format FPS etc? As long as I export them with the same settings.

**Comment by mifi** [comment]
when exporting with LosslessCut it preserves the **original file's** codec parameters so if you cut multiple files from different sources, they will **not** magically get the same FPS etc after exporting. The source files you want to merge need to be from exactly the same camera (or encoding)
