### ISSUE TITLE
is this software support "remove middle"?

### ISSUE THREAD

**Issue by kucingkembar** [mifi/lossless-cut#1148]
hi, sorry for my bad English,
I have a video with orders A,B,C,D,E
I like to remove A,C,E and keep the B and D,
can this software do this, if it can, can you provide a guide?
thank you, have a nice day

**Comment by mifi** [comment]
Hi. Yes, just split into ABCDE with the <kbd>B</kbd> key, then delete segments ACE

**Comment by lyctw** [comment]
@mifi 
It doen't work for me.
I split with B key 

![image](https://user-images.githubusercontent.com/12937401/169675818-0187a546-b692-4b48-80dd-8a1c80796914.png)

and export (merge and seperate), it exports 3 file,
1. ABCDE-00.00.02.311-00.00.04.499-seg1.mp4
2. ABCDE-00.00.06.612-00.00.08.454-seg2.mp4
3. ABCDE-cut-merged-1653186925999.mp4

|   | expect | actual |
| --- | --- |--- |
|1  |  B |   AB |
|2  |  D |   CD |
|3  |  BD  |  ABCD  |

I've version 3.39.0 & 3.44.0 and got the same issue.

**Comment by mifi** [comment]
i think the problem here is that your file has too few keyframes and you are trying to cut between keyframes which is not possible, see https://github.com/mifi/lossless-cut#known-issues--limitations
you can try the experimental "smart cut" and see if that works for you

**Comment by lyctw** [comment]
Thanks @mifi, normal mode fixed my issue.
