### ISSUE TITLE
How to prevent overwriting previous files of same name?

### ISSUE THREAD

**Issue by Neekalos** [mifi/lossless-cut#1149]
If a file that has not been run through LosslessCut exists with the same name as the output, you receive an error message and it refuses to export. However, if the file _has_ been exported from LosslessCut, it will simply replace it, and it doesn't appear there's a way to undo it. Why exactly does the program make a distinction between files that have and haven't been run through it?

I've tried changing input/output folders, but it still replaces it no matter what. Is there any way to prevent this? Or convert/modify your exports in a way that the program will not detect them as a previous output? I like the program a lot, but it's hard to justify using it when previous files can be wiped so easily. I use it for editing gaming clips, so I end up with a lot of repeat file names by accident. My only solution has been to watch the file, rename it in Windows to see if it's a duplicate, and then trim it. I also use a buffer folder as the output, rather than the input folder. This all gets to be a hassle when going through large numbers of videos though.

**Comment by mifi** [comment]
Could you show me the error message that you receive when you try to export with the same name as an existing file?
AFAIK there is no distinction between files created by losslesscut or other programs. LosslessCut will always replace the existing file, **but** it will give an error if you try to export multiple segments with a template that results in duplicate output names

**Comment by mifi** [comment]
Closing in favor of #916
