### ISSUE TITLE
Resize windows with kept aspect ratio (height/width)? 

### ISSUE THREAD

**Issue by bsto** [mifi/lossless-cut#115]
Assume I load a video into LC.
When I drag now the lower left corner of LC window to resize the video then the video aspect ratio (height/width) is NOT kept.

Is there an option to achieve this?
Or can such an option be added in the next release?

Thank you
Ben

**Comment by mifi** [comment]
I don't understand - please clearify.

**Comment by mifi** [comment]
I think I will not implement this. Don't see the point
