### ISSUE TITLE
[Feature suggest] Display & Toggle subtitle's "Default track" flag

### ISSUE THREAD

**Issue by cyzs233** [mifi/lossless-cut#1152]
Use cases could be: When you want to change the default subtitle track to English. (preferably, able to change this tag on audio tracks too)

Having it done in LC could save users a lot trouble to re-mux it using other tools like mkvtoolnixgui. 
![Untitled](https://user-images.githubusercontent.com/25927091/169677654-5d87d54b-70bd-4186-aa13-39e071001bd8.png)

**Comment by mifi** [comment]
I think this can already be done in this dialog, for each track (including audio tracks):

<img width="620" alt="Screenshot 2022-05-21 at 21 41 26" src="https://user-images.githubusercontent.com/402547/169679013-aa6abd3c-cbd9-494e-88c0-6af22d0cd8ef.png">

**Comment by cyzs233** [comment]
yeah, that's how you set it. But in the current interface, you can't really tell if a track is set as default or not, or which one has been set as default.  I think by adding a "Default track" volume in "Tracks" panel, it should be good enough if it's already togglable.

**Comment by mifi** [comment]
ok! next version will instead show each track's disposition in the tracks table's rows and allow editing there

<img width="662" alt="Screenshot 2022-05-23 at 21 41 53" src="https://user-images.githubusercontent.com/402547/169950559-75b74290-8c49-4596-b570-265bc22c6cac.png">

**Comment by cyzs233** [comment]
awesome and fast update! thanks !! ❤
