### ISSUE TITLE
Generate random segments

### ISSUE THREAD

**Issue by mifi** [mifi/lossless-cut#1153]
from email:

> I record all my gameplays and they end up being very long like 1-6 hours and I just hate going through it manually to pick my own segments.
> all I really want is to make my long gameplay videos turned into a 8-10 min montage where its just a mixture of different parts of the video.

- min-max value popup for the length of the segments?
- min-max value popup for the gap between segments?

**Comment by kibbblz** [comment]
Patiently waiting for this feature. Got a lot of back log on videos waiting for this. Hope to see it soon, thanks for your hard work, appreciated.
