### ISSUE TITLE
Time as an unit of zoom

### ISSUE THREAD

**Issue by jtagcat** [mifi/lossless-cut#1154]
**Is your feature request related to a problem? Please describe.**
With varying lengths of video, it's hard finding a good zoom level right away.

**Describe the solution you'd like**
Show zoom in units of time, ie the visible timeline is 1min, 10min, 2h, 5s. This means time passed in same zoom level across different times is consistent.

**Additional context**
Keyboard shortcuts for these + custom input would be nice.

**Comment by mifi** [comment]
closing in favor of #483
