### ISSUE TITLE
Feature Request: Add CLI Support

### ISSUE THREAD

**Issue by HarryMuscle** [mifi/lossless-cut#1157]
I've been reading up on Lossless Cut and it looks like it's a great tool.  However, it doesn't look like it has any command line support for invoking the application from the command line to perform a specific function and then exit.  For example, I would like to be able to invoke Lossless Cut for a single video file and a single EDL file and generate an output file that has all the cuts/mutes/etc. from the EDL file applied, all from the command line without having to invoke the GUI.

**Comment by mifi** [comment]
LosslessCut's UI was never designed to be fully scriptable so it's not very easy to implement.

I think something like this is better done directly with the ffmpeg command line using bash scripting.
Or maybe you could use a keyboard macro utility to trigger the correct keypresses in the correct order.

Closing in favor of existing feature request #980
