### ISSUE TITLE
Scrubbing through a video with keyboard is slow and sluggish

### ISSUE THREAD

**Issue by DenMoore** [mifi/lossless-cut#1162]
From Version 3.42 to Version 3.43 and later, 
moving forward and backward through video with keyboard left arrow + right arrow, became sluggish and slow.

Version 3.42 had smooth and quick frame changes. Really snappy moving through the material.
Version 3.43+ has slow frame changes, skips a lot of frames if you hold the keyboard key, and stalls frequently while moving through the material. 

According to VLC, my Material is H264 - MPEG-4 AVC (part10) (avc1), 30 FPS, 1920x1080 in a MP4 container. 
OS is Windows 10 21H2 latest patch level
Setting for the keyboard in LosslessCut is: 
- Seek speed 0.5
- Seek acceleration: 1.02

Reproducing the issue is easy for me 
by just switching back and forth between 3.42 and 3.43+, leaving the configuration untouched.

**Comment by mifi** [comment]
dup of #1162
