### ISSUE TITLE
When using a CSV for segment specification, add an option that the segment name will be used as-is

### ISSUE THREAD

**Issue by akrk1986** [mifi/lossless-cut#1164]
Thanks for providing and maintaining this awesome tool!

I'm using the option 'Import project -> times in seconds (CSV)'. It works great and solves a use case that I have.
The problem is that the generated files names are constructed from the original file name + start-time + end-time + segment-description.

This algorithm creates very long file names and also, at least for me, I don't care about the original name.
I suggest to add a configuration: 'Output file name: - use description only / use default (=current behavior)'

Thank you and keep up this great work.

**Comment by mifi** [comment]
Hi. In the export dialog you can customize output file name (template). does that solve your problem?

**Comment by akrk1986** [comment]
Feature already exists
