### ISSUE TITLE
"Unsupported File" when trying to open MKV files

### ISSUE THREAD

**Issue by petermg** [mifi/lossless-cut#1165]
Windows 10
Worked fine on version 3.43.0 that one opens MKV files no problem.
Any version above that one isn't opening my MKV files and just says "Unsupported File" when I drag and drop it.

**Comment by mifi** [comment]
Could you provide the requested report?

**Comment by petermg** [comment]
Sorry, I just looked in the console and noticed it failed to find the path. It was set to use an external ffmpeg version. Not sure why this happened in the new version but not in the old one. I just set it to use the internal ffmpeg and it's working now. Also the path it was looking for was not valid. I don't know why it was doing that with the new version and not with the older version I didn't change settings and I don't see this option in the older one?  :\
