### ISSUE TITLE
Export selected segment WITHOUT merge and/or without removal partial segments at end?

### ISSUE THREAD

**Issue by pstein** [mifi/lossless-cut#1167]
Assume I selected several segments from a loaded video.
Now I want to export them individually WITHOUT later merge resp more precisely WITHOUT removal of the partial segments.

How can I achieve this?

Currently all partial segments a merged and removed.

**Comment by pstein** [comment]
""merge+separate" sounds exactly what I need.
BUT: Where do I switch to the export mode?
I found no Option

**Comment by mifi** [comment]
upper right
<img width="320" alt="Screenshot 2022-06-02 at 12 49 03" src="https://user-images.githubusercontent.com/402547/171725995-071aaed1-7b6b-478a-922c-83eb6fa0e0ba.png">

**Comment by pstein** [comment]
Ok, thank you

**Comment by mifi** [comment]
did it solve your problem?

**Comment by pstein** [comment]
Yes, thank you
