### ISSUE TITLE
Text chapters/Youtube import keyboard shortcut

### ISSUE THREAD

**Issue by viktorblack** [mifi/lossless-cut#1168]
like the title said if there is a way to get the info without going in the program to speed uploading up?

**Comment by mifi** [comment]
you mean a keyboard shortcut for the menu item?

**Comment by viktorblack** [comment]
yeah sry my English isnt so good  but yeah that and also maybe a option to auto import chapters :)

**Comment by mifi** [comment]
Auto import chapters from youtube? Im not sure how that would be possible

**Comment by viktorblack** [comment]
nah i mean when you put vids in the software it ask if you want to import the chapters so what i want is to have a option that doesn't ask that and just does it . again sry for my english :)

**Comment by mifi** [comment]
Ahh. I think I won't implement such an option but a hotkey should be fine for speeding up the workflow

**Comment by mifi** [comment]
closing as the feature request already exists here: https://github.com/mifi/lossless-cut/issues/254#issuecomment-932649424
