### ISSUE TITLE
Commands history shows in the help menu is not compatible on Windows

### ISSUE THREAD

**Issue by syanle** [mifi/lossless-cut#1169]
Hi, I rely on lossless-cut to expolore the basic usage of ffmepg. If I simply cut some segments and click merge, your tool tracks the command history of ffmpeg, and the latest version even track the complex merge command. That is great for me to copy and paste the commands and run it on linux, but failed on Windows with ffmepg provide in your [realeased zip file](https://github.com/mifi/lossless-cut/releases/download/v3.45.0/LosslessCut-win-x64.zip). 

My copied command is like this:
`ffmpeg -hide_banner -ss '227.88474' -i 'D:\test.ts' -t '88.26522' -avoid_negative_ts make_zero -map '0:0' '-c:0' copy -map '0:1' '-c:1' copy -map_metadata 0 -movflags '+faststart' -default_mode infer_no_subs -ignore_unknown -f mpegts -y 'D:\test-00.26.46.427-00.28.14.692-seg3.ts'`
The error is:
`Invalid duration specification for ss: '227.88474'`

I tried to rewrite the seconds to a format in [HH:]MM:SS[.m...] and even remove the `-hide_banner` flag, but nothing helps, ffmpeg just spits out the `Invalid argument` error.

**To Reproduce**
1. cut the mpeg-ts file
2. merge with default parameters
3. get the commands history

**Desktop (please complete the following information):**
 - OS: Windows 7

Please don't worry about my environment path that overwrite the ffmpeg version, since I carefully drag your version of ffmpeg to cmd and run it directly.

**Comment by mifi** [comment]
I suspect the issue is the single quotes `'` around the arguments - could you try replacing with double quotes `"` instead?

**Comment by syanle** [comment]
> ffmpeg -hide_banner -ss '227.88474' -i 'D:\test.ts' -t '88.26522' -avoid_negative_ts make_zero -map '0:0' '-c:0' copy -map '0:1' '-c:1' copy -map_metadata 0 -movflags '+faststart' -default_mode infer_no_subs -ignore_unknown -f mpegts -y 'D:\test-00.26.46.427-00.28.14.692-seg3.ts'

:+1: Awesome! It works! Thank you mifi!
I also tried to remove the single quotes `'`, and it works as well!
By the way, to help the others may meet the same incompatibility on Windows, please notice that `echo -e` piping multiple files to ffmpeg is likely to fail, it should be `echo file file:<filename> & echo file file:<another filename> | ffmpeg <...>`

**Comment by mifi** [comment]
> By the way, to help the others may meet the same incompatibility on Windows, please notice that `echo -e` piping multiple files to ffmpeg is likely to fail, it should be `(echo file file:<filename> & echo file file:<another filename>) | ffmpeg <...>`

Actually it's not a file being piped to ffmpeg, but it's a string in the command line itself (the concat file's text content). I'm not sure if that's even possible to do that on Windows

**Comment by syanle** [comment]
> > By the way, to help the others may meet the same incompatibility on Windows, please notice that `echo -e` piping multiple files to ffmpeg is likely to fail, it should be `(echo file file:<filename> & echo file file:<another filename>) | ffmpeg <...>`
> 
> Actually it's not a file being piped to ffmpeg, but it's a string in the command line itself (the concat file's text content). I'm not sure if that's even possible to do that on Windows

It's OK on Windows 7 :smile:
