### ISSUE TITLE
Missing control: Jump to next/prev key(!) frame (NOT frame)?

### ISSUE THREAD

**Issue by bsto** [mifi/lossless-cut#117]
I miss two "arrow" controls: Jump to next keyframe and jump to previous keyframe.

Or do I miss it somehow?

The "normal" tiny arrows between the two timestamp fields are for frames in general.

Can these keyframe jump controls be added in the next release?
Alternatively the existing frame controls should be customizeable by user to a new meaning "jump keyframe".

Thank you
Ben

**Comment by mifi** [comment]
Already had the discussion about seeking to keyframes in #13, this is not yet implemented. Need to find a way to quickly extract keyframe intervals for a long video.

**Comment by mifi** [comment]
#41
