### ISSUE TITLE
Remember cursor position

### ISSUE THREAD

**Issue by jtagcat** [mifi/lossless-cut#1170]
**Is your feature request related to a problem? Please describe.**
I want to check where my current position actually is. By playing. If it is what I want, I have to go back to the position, inaccurate.

**Describe the solution you'd like**
Separate pause and stop (jump back to where you started playing or clicked with mouse) (+ keyboard) keys. Video editors generally prefer to use the stop behavior. Some use enter/space to differentiate them.

**Comment by mifi** [comment]
thanks. I've added your suggestion here: #254 so I'll close this issue
