### ISSUE TITLE
Smart cut: output is cut + original

### ISSUE THREAD

**Issue by jtagcat** [mifi/lossless-cut#1171]
Files: https://q.c7.ee/losslesscut_1171/

v3.45.0, Appimage
run1: Using external ffmpeg: /usr/bin; ffmpeg-5.0.1-3.fc36.src.rpm from rpmfusion-free
run2: Using internal

The output file is selected region + concatenated original. Desired: only cut / selected region.

**Comment by mifi** [comment]
same issue in 3.44.0?

**Comment by jtagcat** [comment]
Yes. Reproducible on v3.44.0 (Appimage, internal ffmpeg).

**Comment by mifi** [comment]
this is definitely caused by losslesscut/ffmpeg's inability to consistently seek to the correct frame. Closing in favor of #1216
