### ISSUE TITLE
Preserve audio tracks names

### ISSUE THREAD

**Issue by danielwerg** [mifi/lossless-cut#1174]
**Describe the bug**
Lossless Cut renames audio tracks names on export

**Expected behavior**
Preserve audio tracks names instead of renaming them to `Track N`

**Screenshots**
VLC
Before:
![before](https://user-images.githubusercontent.com/35052399/171316905-baddb1ba-ca88-4a59-bb60-4e4f8ac77412.png)
After:
![after](https://user-images.githubusercontent.com/35052399/171316917-5cbddc3a-c6f5-4637-ae19-49054498e5f8.png)

**Desktop**
 - OS: Windows 10
 
**Workaround**
Is there a way to batch rename videos audio tracks names with some kind of cli?

**Comment by mifi** [comment]
any chance you could provide a file that has audio tracks with different names? I've never seen such a file

**Comment by danielwerg** [comment]
@mifi I record it using obs, what would be the best way for me to share example video with you?
![obs](https://user-images.githubusercontent.com/35052399/171786569-bf18ef09-2fd1-49f6-8b7f-5791d6423f57.png)

**Comment by danielwerg** [comment]
@mifi here is dropbox link: https://www.dropbox.com/s/umixn6nb6byi36p/2022-06-03.mp4

**Comment by mifi** [comment]
Thanks. It seems like ffmpeg and ffprobe does not support reading track names/titles:
- https://superuser.com/questions/1600254/how-to-read-the-name-of-audio-track-using-ffmpeg
- https://superuser.com/questions/1632322/ffprobe-missing-title-tag-with-mp4-files

running `ffprobe 2022-06-03.mp4`:

```
[libdav1d @ 0x7f7f08705640] libdav1d 1.0.0-1-g87f9a81
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '2022-06-03.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomav01iso2mp41
    encoder         : Lavf58.76.100
  Duration: 00:00:03.32, start: 0.000000, bitrate: 755 kb/s
  Stream #0:0[0x1](und): Video: av1 (Main) (av01 / 0x31307661), yuv420p(tv, bt709), 2560x1440, 32 kb/s, 60 fps, 60 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 321 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 2 kb/s
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
  Stream #0:3[0x4](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 57 kb/s
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
  Stream #0:4[0x5](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 309 kb/s
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
  Stream #0:5[0x6](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 2 kb/s
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
  Stream #0:6[0x7](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 2 kb/s
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
[libdav1d @ 0x7f7f08719300] libdav1d 1.0.0-1-g87f9a81
```

However I tried recording with a custom audio track name from OBS using `matroska` instead of `mp4`, and importing to losslesscut, then exporting from losslesscut, and I can see that the **audio track name is then preserved**.

so maybe you can use mkv instead? then possibly use losslesscut to change it to mp4 and it might preserve the track names

**Comment by danielwerg** [comment]
@mifi Just tested and `mkv` indeed preserves track names. Thank you!
