### ISSUE TITLE
It does not cut my video at the beginning

### ISSUE THREAD

**Issue by haihao888** [mifi/lossless-cut#1175]
**Describe the bug**
This is the first time I have used this software, I inserted a 3 min 56 sec video, I wanted to cut the beginning by 2 seconds and another 4 seconds at the end, I exported the video in mp4 format and it only took off the 4 seconds at the end, the first 2 seconds remained in the video.

**Screenshots**
![image](https://user-images.githubusercontent.com/71890453/171458904-d761c3d2-c309-4908-9616-19dc4d5fa33d.png)
![image](https://user-images.githubusercontent.com/71890453/171459103-9e47e490-a403-4537-8591-237422387fbd.png)

**Desktop (please complete the following information):**
Windows 11

No error

{
  "state": {
    "filePath": "D:\\Users\\liuhaihao\\Desktop\\3°bozza PCTO v.1 mp4-reformatted.mp4",
    "fileFormat": "mp4",
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1080,
        "closed_captions": 0,
        "has_b_frames": 1,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 42,
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "60/1",
        "avg_frame_rate": "42642000/710699",
        "time_base": "1/90000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 21320970,
        "duration": "236.899667",
        "bit_rate": "4160649",
        "bits_per_raw_sample": "8",
        "nb_frames": "14214",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "VideoHandler",
          "vendor_id": "[0][0][0][0]"
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/48000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 11370480,
        "duration": "236.885000",
        "bit_rate": "187265",
        "nb_frames": "11104",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "SoundHandler",
          "vendor_id": "[0][0][0][0]"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "D:\\Users\\liuhaihao\\Desktop\\3°bozza PCTO v.1 mp4-reformatted.mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {
        "start": 2.51161,
        "end": 231.779852
      }
    ],
    "mainFileFormatData": {
      "filename": "D:\\Users\\liuhaihao\\Desktop\\3°bozza PCTO v.1 mp4-reformatted.mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "236.900000",
      "size": "129229481",
      "bit_rate": "4364017",
      "probe_score": 100,
      "tags": {
        "major_brand": "isom",
        "minor_version": "512",
        "compatible_brands": "isomiso2avc1mp41",
        "encoder": "Lavf58.76.100"
      }
    },
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "separate"
  },
  "platform": "win32",
  "version": "3.45.0"
}

**Comment by mifi** [comment]
please read instructions first
