### ISSUE TITLE
Allow importing all exported segment formats

### ISSUE THREAD

**Issue by akrk1986** [mifi/lossless-cut#1176]
The CSV import supports start/end times expressed in seconds. However, most video players and sites display the time in human-readable format HH:MM:SS.
It would be great if an option could be added to support this format (7 columns).
My workaround:
1. Create an Excel with 7 columns (start-hh/mm/ss, end-hh/mm/ss, name)
2. Run a Python script that converts the start/end times to seconds format and writes out a CSV as LLC expects.

Thanks

**Comment by mifi** [comment]
I'm collecting all import/export format requests in one issue #1340 to keep issue count down - closing this
