### ISSUE TITLE
This problem occurred when converting an MP4 file to a hevc file

### ISSUE THREAD

**Issue by PingGai** [mifi/lossless-cut#1178]
This problem occurred when converting an MP4 file to a hevc file

![image](https://user-images.githubusercontent.com/70486553/171681447-4fdbbe29-8bfc-4887-af25-519ffabbbb8a.png)
![image](https://user-images.githubusercontent.com/70486553/171681333-315acfa2-56b9-483c-804b-4b9a67031078.png)

I tried a few of the tips above and it was still not working, so sent this report as per the last tip

[Error.txt](https://github.com/mifi/lossless-cut/files/8825906/Error.txt)
Error: Command failed with exit code 1: C:\Users\30367\AppData\Local\Temp\29bEkJpRUy1jupU0zGDBfALgrbp\resources\ffmpeg.exe -hide_banner -i C:\Users\30367\Videos\PR\Base Profile 2022.05.09 - 01.03.03.05.DVR.mp4 -map 0:0 -c:0 copy -map 0:1 -c:1 copy -map_metadata 0 -movflags use_metadata_tags -movflags +faststart -default_mode infer_no_subs -ignore_unknown -f hevc -y C:\Users\30367\Videos\PR\Base Profile 2022.05.09 - 01.03.03.05.DVR-00.00.00.000-00.00.19.285.hevc
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\30367\Videos\PR\Base Profile 2022.05.09 - 01.03.03.05.DVR.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    creation_time   : 2022-05-08T17:09:15.000000Z
  Duration: 00:00:19.29, start: 0.000000, bitrate: 11022 kb/s
  Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 10714 kb/s, 59.94 fps, 59.94 tbr, 60k tbn, 119.88 tbc (default)
    Metadata:
      creation_time   : 2022-05-08T17:09:15.000000Z
      handler_name    : ?Mainconcept Video Media Handler
      vendor_id       : [0][0][0][0]
      encoder         : AVC Coding
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s (default)
    Metadata:
      creation_time   : 2022-05-08T17:09:15.000000Z
      handler_name    : #Mainconcept MP4 Sound Media Handler
      vendor_id       : [0][0][0][0]
[hevc @ 000001ecc439b900] hevc files have exactly one stream
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:1 -- 
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
    Last message repeated 1 times
    at makeError (C:\Users\30367\AppData\Local\Temp\29bEkJpRUy1jupU0zGDBfALgrbp\resources\app.asar\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\30367\AppData\Local\Temp\29bEkJpRUy1jupU0zGDBfALgrbp\resources\app.asar\node_modules\execa\index.js:118:26)
    at async file:///C:/Users/30367/AppData/Local/Temp/29bEkJpRUy1jupU0zGDBfALgrbp/resources/app.asar/build/static/js/main.3131d877.js:2:304769
    at async file:///C:/Users/30367/AppData/Local/Temp/29bEkJpRUy1jupU0zGDBfALgrbp/resources/app.asar/build/static/js/main.3131d877.js:2:305537
    at async file:///C:/Users/30367/AppData/Local/Temp/29bEkJpRUy1jupU0zGDBfALgrbp/resources/app.asar/build/static/js/main.3131d877.js:2:2449876

{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "filePath": "C:\\Users\\30367\\Videos\\PR\\Base Profile 2022.05.09 - 01.03.03.05.DVR.mp4",
    "fileFormat": "hevc",
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "Main",
        "codec_type": "video",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1080,
        "closed_captions": 0,
        "has_b_frames": 0,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 42,
        "chroma_location": "left",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "60000/1001",
        "avg_frame_rate": "60000/1001",
        "time_base": "1/60000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 1155154,
        "duration": "19.252567",
        "bit_rate": "10714016",
        "bits_per_raw_sample": "8",
        "nb_frames": "1154",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "creation_time": "2022-05-08T17:09:15.000000Z",
          "language": "eng",
          "handler_name": "\u001fMainconcept Video Media Handler",
          "vendor_id": "[0][0][0][0]",
          "encoder": "AVC Coding"
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/48000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 924123,
        "duration": "19.252562",
        "bit_rate": "317093",
        "nb_frames": "904",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "creation_time": "2022-05-08T17:09:15.000000Z",
          "language": "eng",
          "handler_name": "#Mainconcept MP4 Sound Media Handler",
          "vendor_id": "[0][0][0][0]"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "C:\\Users\\30367\\Videos\\PR\\Base Profile 2022.05.09 - 01.03.03.05.DVR.mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {}
    ],
    "mainFileFormatData": {
      "filename": "C:\\Users\\30367\\Videos\\PR\\Base Profile 2022.05.09 - 01.03.03.05.DVR.mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "19.285333",
      "size": "26571906",
      "bit_rate": "11022638",
      "probe_score": 100,
      "tags": {
        "major_brand": "mp42",
        "minor_version": "0",
        "compatible_brands": "mp42mp41",
        "creation_time": "2022-05-08T17:09:15.000000Z"
      }
    },
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "merge"
  },
  "platform": "win32",
  "version": "3.45.0"
}

**Comment by mifi** [comment]
see the error "hevc files have exactly one stream"

try to disable the audio track (stream) in the tracks panel
