### ISSUE TITLE
Empty trash can

### ISSUE THREAD

**Issue by ruediheimlicher** [mifi/lossless-cut#1179]
I use losslessCut for stripping tv recordings. 
Version: Newest.
Works great with one exception:
After exporting, I klick on the trash symbol to move the unnecessary files to trash. 
But when I empty the trash can in Finder, it is not cleared. Only quitting LosslessCut releases the occupied memory.
Is that a planned feature?
Ruedi Heimlicher
MacOS 11.4, MacMini M1

**Comment by mifi** [comment]
thanks. this is a known problem, closing this in favor of main issue https://github.com/mifi/lossless-cut/issues/272#issuecomment-1146516180
