### ISSUE TITLE
Multi-interval selection and interval deletion possible?

### ISSUE THREAD

**Issue by bsto** [mifi/lossless-cut#118]
As far as I can see users can NOT select multiple intervals. Only one interval at a time is possible.

Is this correct?

Furthermore I oftentimes want to delete a commerical ad inside (0in the mid) a video clip and export/save the remaining stuff.

How can I achieve this?

I miss a "delete interval and keep remaining video" function.

Ben

**Comment by mifi** [comment]
You can select multiple sections by pressing <kbd>+</kbd> or the `c+` button. You can toggle the `nm` (no merge) button to `am` (auto merge), and it will merge all your cut segments into one, which effectively deletes all invervals that are not selected.

I want to make it more clear that this is possible somehow.
