### ISSUE TITLE
separate audio function

### ISSUE THREAD

**Issue by cotagxrdhy** [mifi/lossless-cut#1180]
Hi! The software is very good! We would like to add a separate audio function for quick！

And  add export presets.

Thanks!

**Comment by mifi** [comment]
hi. im not sure what separate audio function means. could you elaborate?

**Comment by cotagxrdhy** [comment]
![image](https://user-images.githubusercontent.com/80959178/171985954-1916ef34-526e-4ef1-81b3-10e5736e542d.png)
I mean here to add a separate 'extract audio track.

**Comment by mifi** [comment]
you can go to the tracks panel and extract single tracks

<img width="123" alt="Screenshot 2022-06-03 at 22 59 47" src="https://user-images.githubusercontent.com/402547/171986711-83cb5437-c7b3-43e6-b535-9c03515ef23c.png">

**Comment by cotagxrdhy** [comment]
> Yes, this works. But it's not fast, and I often need to extract audio tracks！

**Comment by mifi** [comment]
so you want a way to export multiple audio tracks as files in one click?

**Comment by mifi** [comment]
closing due to lack of response
