### ISSUE TITLE
Undo redo message pop-up

### ISSUE THREAD

**Issue by ffontcl** [mifi/lossless-cut#1183]
I recently upgraded to the latest version and now every time I use my keyboard (cmd+z or cmd+shift+z) to undo or redo I get a popup message. In previous versions I did not have this problem.

Is there any way to disable it so I can do multiple undo or redo? 

<img width="438" alt="Screen Shot 2022-06-04 at 20 00 20" src="https://user-images.githubusercontent.com/37421896/172029436-d40a0085-410e-4284-bf0d-69637732ddd5.png">

**Comment by mifi** [comment]
This was an "improvement" I added to warn people who try to use undo/redo from the menu, but it turns out an unexpected side-effect is that keyboard shortcuts also trigger this menu (sometimes). So this is a bug I will fix!

**Comment by mifi** [comment]
it was added because of https://github.com/mifi/lossless-cut/issues/610#issuecomment-1080746921
