### ISSUE TITLE
Auto import EDL files based on extension and/or same file name

### ISSUE THREAD

**Issue by jleiss** [mifi/lossless-cut#1185]
**Describe the solution you'd like**
An option to auto import EDL would be handy instead of having to import them each time.. caveats would be that the EDL file would need to match the name of the video file with an edl extension, and it would need to reside in the same directory as the video

**Comment by mifi** [comment]
what do you mean by EDL file?

**Comment by jleiss** [comment]
Edit Decision Lists generated by like comskip, can import them one by one
but having an option to auto import would be handy as I use them all the
time for removing commercials.

**Comment by mifi** [comment]
You mean "Import project -> EDL (Mplayer)"?
I'm not sure how to auto-detect based on extension though. Is there a default extension for mplayer files?

**Comment by jleiss** [comment]
The default extension for edl is .edl.

**Comment by forart** [comment]
It would be great if LC will be able to manipulate those files !

Edit Decision List (EDL) infos here: https://en.wikipedia.org/wiki/Edit_decision_list

Some - maybe - inspiring links:
- @bilaloguz's [Edit Decision List Cutter](https://github.com/bilaloguz/edlcutter), of course;
- @ThomasWeckenmann's [py_edl_editor](https://github.com/ThomasWeckenmann/py_edl_editor) that is cool;
- @kcsry's [ffmpeg-edl](https://github.com/kcsry/ffmpeg-edl) too;
- @pietrop's [Edl Composer](https://github.com/pietrop/edl-composer#readme);
- [PySceneDetect-CSV-to-Vegas-EDL](https://github.com/Mirellanmawl/PySceneDetect-CSV-to-Vegas-EDL#readme) by @Mirellanmawl;
- [Silent-EDL](https://github.com/Kisaiyuki/silent-edl#readme) by @Kisaiyuki;
- the old [edledit](https://github.com/sbidoul/edledit#readme) by @sbidoul.

Hope that helps !

**Comment by forart** [comment]
These are some various implementations of EDL format support (in/ex-port).

Does LC supports multitrack (= multicamera) EDLs - exported by NLEs - too ?

Thanks for your work.

**Comment by mifi** [comment]
> Does LC supports multitrack (= multicamera) EDLs - exported by NLEs - too ?

probably not, because losslesscut only supports cutting a single file at a time (and it will cut all tracks/streams)

**Comment by mifi** [comment]
so the biggest problem with this feature is that a file ending with `.edl` can mean many things. so we have to decide what to do when encontering such a file, if we want to auto import it. (e.g. how to parse it). i've added a reference to this issue in #1340 - closing this issue
