### ISSUE TITLE
Issue- Some videos load but show nothing visually

### ISSUE THREAD

**Issue by profucius** [mifi/lossless-cut#119]
I've found that videos recorded with my Nikon DSLR will load the file into LosslessCut, will not show any video on the screen, but it will play audio. Yet the video and audio both play fine in VLC v3.

If I use KC to cut a section of this file and export, that section will play fine in VLC v3. But LosslessCut is not showing anything on the screen.

It is successful also with NC cut. But without the ability to see the video in LosslessCut, it is impossible to know what you are cutting.

[Example video](https://tinyurl.com/example-novideo)

**Comment by mifi** [comment]
Probably it contains a format/codec that is not supported by chromium. For now you can try: convert to friendly codec (slow)

**Comment by mifi** [comment]
This video has HEVC (H265), which is indeed not supported by chromium. See #88

```
    Stream #0:0(eng): Video: hevc (Main) (hev1 / 0x31766568), yuv420p(tv), 1080x1920 [SAR 1:1 DAR 9:16], 8380 kb/s, 58.81 fps, 59 tbr, 170325000.00 tbn, 58.81 tbc (default)
    Metadata:
      creation_time   : 2017-09-05T06:39:31.000000Z
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 194 kb/s (default)
    Metadata:
      creation_time   : 2017-09-05T06:39:31.000000Z
      handler_name    : SoundHandler
```

**Comment by killaz47** [comment]
> This video has HEVC (H265), which is indeed not supported by chromium. See #88
> 
> ```
>     Stream #0:0(eng): Video: hevc (Main) (hev1 / 0x31766568), yuv420p(tv), 1080x1920 [SAR 1:1 DAR 9:16], 8380 kb/s, 58.81 fps, 59 tbr, 170325000.00 tbn, 58.81 tbc (default)
>     Metadata:
>       creation_time   : 2017-09-05T06:39:31.000000Z
>       handler_name    : VideoHandler
>     Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 194 kb/s (default)
>     Metadata:
>       creation_time   : 2017-09-05T06:39:31.000000Z
>       handler_name    : SoundHandler
> ```

heres the solution from the chrnoium developers
https://github.com/henrypp/chromium/blob/master/hevc_support.md
https://github.com/henrypp/chromium/blob/master/hevc_support_new.md
