### ISSUE TITLE
【功能请求】五个问题

### ISSUE THREAD

**Issue by jkqxl** [mifi/lossless-cut#1191]
1. export file location = where to cut the video，auto configuration

2. customize Export video file name，For example prefix [SHANA]

3.Preview directly
direct preview，video section left，but does not include the abridged part of the video。
An option added in the cut interface, choose whether to open or not。

5.Compressed video quality preview
when i use a low configuration device，When editing 4K, 8K and higher video files，will freeze, or even stop working at all。
An option can be added to the interface，Option to compress video quality (resolution) while previewing，1/2、1/4...

**Comment by mifi** [comment]
Unfortunately I can't read Chinese, but if someone wants to translate, that would be nice. Google translate didn't help much

**Comment by jkqxl** [comment]
> Unfortunately I can't read Chinese, but if someone wants to translate, that would be nice. Google translate didn't help much

My English is not very good, and if you can't understand it, there is nothing I can do
