### ISSUE TITLE
Right click to paste into input fields

### ISSUE THREAD

**Issue by Ampa1941** [mifi/lossless-cut#1192]
I appreciate your product.

When I run your program I know where I want to make the cuts.  I have a text list of start and end times of the segments I want to include in the video.  If the "seek to timecode" entry would allow "Paste" into the field it would provide for more accuracy and reduce user input.

**Comment by mifi** [comment]
Hi. doesn't CTRL+V work for pasting? If not, please share some more info

**Comment by mifi** [comment]
closing in favor of #1217
