### ISSUE TITLE
Mixed questions & ideas to improve LosslessCut

### ISSUE THREAD

**Issue by Dean-Corso** [mifi/lossless-cut#1194]
Hi guys,

so I was trying to test the LosslessCut tool and I found some issues I would like to ask about it and whether it would be an good idea to change it etc.

1.) I like the feature to create segment cuts so many I want which are shown on right pane/side. 
Q: How to play a single segment without to play go on? How to loop a single segment? How to play all segments and JUST ONLY the segments without to play the not segment part (trashcan)? How to trim all segments and removing the trash between? I would like to make some accurate cuts (not keyframe cuts) in a video but for this I need to play the created segments one by one to see and hear it (audio) but at the moment its not possible because I can not play any single segment and just the segment.

S: Just add another button on the Segments with a PLAY sign and another button with a LOOP sign. Now if I as user press the play button on the segment then it should just play that single segment and stop at the end of it or just loop it if the loop is also enabled. Something like that would be great.

You also need to add a feature to play all segments ONLY so that I as user can preview the entire output before I do export anything. Lets say I have created 5 segments and then it should be possible to play all 5 segments one by one. Otherwise a option to cut away all video parts (trashcan) and just showing the segments would be also good...
```
[seg1]......trash.... [seg2].trash.[seg3]........trash.....[seg4][seg5]
to
[seg1][seg2][seg3][seg4][seg5]
```
Important is that I can preview all single segments and also all segments together.

2.) AudioWaveForm. Good idea but in your tool its not really helpfully if I try to make accurate cuts to set markers for the segmnets. The WaveForum must be shown much larger and detailed so that I can see where something is happen and not like silence. I'am using VirtualDub/2 what also can show the audio curve / display and something like this you need in your tool or otherwise the AudioForm is not really helpfully because of missing details to make exact cuts at word ends.

3.) Seek to timecode. Users need this function very offten but your timecode seek jumper is limited and I as user have to enter the exact right format which is "00:00:00.000". So this you should improve. I your tool I need to enter the whole lenght of digits and also the dot.

```
Example: 
00:06:39.730 <-- timecode works
00:06:39       <-- timecode works not
00:06:39,730 <-- timecode works not because of comma "," instead of dot
06:39.730      <-- timecode works not
```
The best is if you just check the format the timecode the user did enter new so that not all digits are needed to enter and also check for entered comma and make a dot etc to allow it. Also timecodes with only one digit where 2 are needed you  could check this before and out a 0 before like here...

Example: Timecode of srt subtitle file...
`00:06:1,260 --> 00:06:3,120`

As you can see the timecodes here are not using all digits places "00:06:1,260". In case of seconds its just using the last digit place without to use 0 digit before and your tool will not accept it and I have to set a 0 manually before and I also need to change the comma to dot to make it work in your tool. Would be nice if you could check & fix that format so that this also works. Would be nice if you could also add a PASTE button next the OK & Cancel button to prevent using keyboard shortcuts strg+v.

Idea: Doubleclick on video player screen could / should show the video in fullscreen mode. Don't mean F11 style. Just good to have a full screen preview.

Maybe you could add / change some features to make the handling better if you don't mind. 

Thank you.

**Comment by mifi** [comment]
Hi. thanks for your suggestions. there are all good improvements and I agree with them. Some have been suggested already in different issues. I will dissect this and put it into the correct issues, stay tuned.

**Comment by webmutation** [comment]
This tools is pretty amazing... Indeed the waveform is the main issues I have as well, since I use the audio to guide my cutting. But being lossless is really awesome.

**Comment by mifi** [comment]
1. See #574 and #253
2. and @webmutation - See #260
3. I created a new issue #1217

> Idea: Doubleclick on video player screen could / should show the video in fullscreen mode. Don't mean F11 style. Just good to have a full screen preview.

See #543

> Would be nice if you could also add a PASTE button next the OK & Cancel button to prevent using keyboard shortcuts strg+v.

see #1192
