### ISSUE TITLE
Multiple In-Out points

### ISSUE THREAD

**Issue by codyolsen** [mifi/lossless-cut#12]
Enhancement: Set point in, set point out, set point in, set point out, etc.

Export = Multiple clips base on in-out points.

**Comment by mifi** [comment]
What is the use case for this? Why is it more useful than the way it is now?

**Comment by codyolsen** [comment]
Let's say you have a 40 minute clip and want to pull all the best stuff from it. Having multiple in-outs laid out and represented before you run your export allows you to have an overall view of your project rather than jumping back and forth looking at cuts you've already made. 

"Did I cut this part? oh.. Where did the last cut end... wait... um..."

**Comment by mifi** [comment]
Good point. I'll leave it open to see if more people would like this

**Comment by mgmalheiros** [comment]
I guess it would be a nice addition, as I have a different scenario: I censor some movie parts before showing them for my kids. For example, deleting the more bloody or violent parts from a typical blockbuster.

I've used to do this by hand-editing in Kdenlive, but reencoding the full movie takes a long time and also degrades its quality.

In fact, there is a simple text format that achieves this, but only a few media players support this:

https://en.wikipedia.org/wiki/Edit_decision_list

**Comment by jmcintyre** [comment]
I'd like to add my vote for this. I do a lot of computer based dvr recording, and as the streams move to H264, I need a new tool that can losslessly cut out the parts of the recording I don't want to save space.

**Comment by conorhub** [comment]
I will add my vote also. I was very excited to see a lightweight lossless mpeg trimmer for osx but cannot use it as it can only create a new video from a single segment. I too want to archive recordings I make from my dvr by trimming out the commercial breaks or the over and anything recorded before or after the show.

This feels like it would be a task that a large amount of people seeking such an app would use, no?

**Comment by winddiesel** [comment]
+1 - to be able to cut out commercials ect.

GREAT Tool by the way - Love it !

**Comment by hellbuster** [comment]
Another user case: I stream videogame tournaments, and I have a long video file with the whole stream. This feature would help cut the clips of individual matches.

**Comment by eexpress** [comment]
I know "vidcutter" does this. I also need this.

**Comment by mifi** [comment]
Thanks. I will have a look at how vidcutter does it.
If anyone has any ideas for simple but efficient UX for this, then I welcome that.

**Comment by conorhub** [comment]
A similar method to that used in EyeTV may suit lossless-cut:

You have three options when making a multiple point cut.

1. The first is to select the multi-edit tool. You are going to be directly working with the playhead and timeline.
2. The second option is to add a new trim point
3. The third is to complete the trim.

So when you click on the timeline while having the multi-trim tool/mode selected, it creates a trim in and out point which you can stretch to the desired in and out time. You click (2) to add a second, and a third, etc. until you have a collection of in and out points. When you click (3), these segments will be subtracted/removed from the timeline and file.

I felt it was quite straightforward and intuitive when I used this method before.

**Comment by Sailing74** [comment]
+1 for multiple in and out points resulting in one stream (e.g. to cut out commercials, as mentioned above).

Regarding the possible user interface, how about just using what is already there? E.g., smart cutter also works on one timeline. You set an in point (and can change it until you set an out point), then you can set an out point (and can change it, until you set the next out point), ... The part between in and out points that will be used in the "cut" movie is marked by a colored line on the time line.

**Comment by debuggeek** [comment]
I'm working on the beginning of this in my own fork right now if there is interest.  
My first addition is to add a bunch of 'bookmarks' with a hotkey that is saved to a known file.  
Happy to provide PR if interested
The follow-on is to set an Input/Output cut per bookmark via a well defined variable, then batch through all the bookmarks

**Comment by malte1989** [comment]
@debuggeek 

I have built today a working multi-cut feature.

How can I  can make a new branch for testing and then afterwards a merge?

**Comment by debuggeek** [comment]
@mifi is the project owner, but if you fork the repo and post a PR he can decide on the feature, but I'd personally be interested in looking at the branch

**Comment by malte1989** [comment]
@debuggeek @mifi 

I created a fork at:
https://github.com/malte1989/lossless-cut

Tell me what you think about it. I think there could be a little improvment of the ui, but I can work with that.

**Comment by kencl** [comment]
+1 for this feature.  Extremely useful.  Example UX from Ezvid, right-click -> split, then you can delete individual segments.  Another alternative would be click the scissors icon (balloon help could read "set splitpoint a current timeline position")

A workaround until this cool feature arrives is do your single cut, then export, then close lossless-cut, then open the exported file.  Repeat as needed :)

I love single focus, simple yet quality utilities like this.  Keep up the great work!

**Comment by mifi** [comment]
Thanks for trying this out! Maybe you can make a binary so people can test this out and come with feedback?

**Comment by Scott274** [comment]
> As this is a relatively big ui changing feature, I don't wanna merge this immediately without properly testing it out first.

So is there any update on adding this useful feature to LosslessCut. I don't think this can be a big UI changing feature; currently when user selects one "In-Out" points on a given video and then further down the video, user tries to select another "In" point, the previous "In-Out" points disappears. Some minor UI modification can make so that user can select multiple In-Out points over the length of the video and then when user clicks on "Cut", program can issue a dialog box asking user if they want to "save all cut positions as single file" (merge/append), or "save all cut positions as individual files".

**Comment by malte1989** [comment]
> > As this is a relatively big ui changing feature, I don't wanna merge this immediately without properly testing it out first.
> 
> So is there any update on adding this useful feature to LosslessCut. I don't think this can be a big UI changing feature; currently when user selects one "In-Out" points on a given video and then further down the video, user tries to select another "In" point, the previous "In-Out" points disappears. Some minor UI modification can make so that user can select multiple In-Out points over the length of the video and then when user clicks on "Cut", program can issue a dialog box asking user if they want to "save all cut positions as single file" (merge/append), or "save all cut positions as individual files".

One year ago I created a fork. See above.
Try to make a binary for testing purpose and then mifi maybe will merge it into the project.

**Comment by Scott274** [comment]
> One year ago I created a fork. See above.
> Try to make a binary for testing purpose and then mifi maybe will merge it into the project.

Dunno how, I'm a hardware guy (electronics)....mine was just a loose suggestion; probably silly considering the author (mifi!) never replied back..

**Comment by mifi** [comment]
I have implemented a lot of new things in 2.0.0, also this. But it needs some testing and feedback.

**Comment by mifi** [comment]
Closing this, open new issues if problems
