### ISSUE TITLE
Can't cut the first few seconds

### ISSUE THREAD

**Issue by forteller** [mifi/lossless-cut#120]
Hi. Thanks for a really great tool! Unfortunately I have issues cutting just the first few seconds of a .webm file created with Cheese 3.30 in Ubuntu 18.10.

I've tested it now and found that the minimum I can cut is 00:00:08.507. If I try to cut at 00:00:08.506 or earlier nothing at all gets cut.

I've also tested it with Kdenlive and an online video cutter, and both where able to cut at before 8 seconds out. Cutting with ffmpeg also worked:

`ffmpeg -i 2019-01-31-195903.webm -ss 00:00:04 -t 00:02:35 -async 1 cut.webm`

Here's the output of the dev tools console when trying to cut a bit over 4 seconds in LosslessCut:

`Download the React DevTools for a better development experience: https://fb.me/react-devtools
You might need to use a local HTTP server (instead of file://): https://fb.me/react-devtools-faq
/home/artig/Apps/LosslessCut-linux-x64/resources/app.asar/renderer.js:880 Version 2.1.0
/home/artig/Apps/LosslessCut-linux-x64/resources/app.asar/renderer.js:303 Load {filePath: "/home/artig/Videos/Webcam/2019-01-31-195903.webm", html5FriendlyPath: undefined}
/home/artig/Apps/LosslessCut-linux-x64/resources/app.asar/ffmpeg.js:213 getFormat /home/artig/Videos/Webcam/2019-01-31-195903.webm
/home/artig/Apps/LosslessCut-linux-x64/resources/app.asar/ffmpeg.js:218 formats matroska,webm
/home/artig/Apps/LosslessCut-linux-x64/resources/app.asar/ffmpeg.js:224 fileType detected format {"ext":"webm","mime":"video/webm"}
/home/artig/Apps/LosslessCut-linux-x64/resources/app.asar/ffmpeg.js:60 Cutting from 4.138629 to 155.676141
/home/artig/Apps/LosslessCut-linux-x64/resources/app.asar/ffmpeg.js:73 ffmpeg -ss 4.138629 -i /home/artig/Videos/Webcam/2019-01-31-195903.webm -avoid_negative_ts make_zero -acodec copy -vcodec copy -scodec copy -map 0 -map_metadata 0 -f webm -y /home/artig/Videos/Webcam/2019-01-31-195903.webm-00.00.04.138-00.02.35.676.webm
/home/artig/Apps/LosslessCut-linux-x64/resources/app.asar/ffmpeg.js:46 00:02:31.47
/home/artig/Apps/LosslessCut-linux-x64/resources/app.asar/ffmpeg.js:48 151.47
/home/artig/Apps/LosslessCut-linux-x64/resources/app.asar/ffmpeg.js:81 `

Hope this is what you need. Let me know if I can do anything else. Thanks!

Here's the file:

[2019-01-31-195903.zip](https://github.com/mifi/lossless-cut/files/2824429/2019-01-31-195903.zip)

**Comment by mifi** [comment]
Try to toggle `kc` to `nc`

**Comment by forteller** [comment]
Thanks! But I have no idea what that means. Care to elaborate? :)

**Comment by mifi** [comment]
the button in the UI, bottom right

**Comment by forteller** [comment]
Ah, I see. Tried it, and then it did cut when I set the timeline to ~4 seconds. But it did not cut at the point I asked it to.

BTW, my ffmpg test seems to not have cut at the exact correct place either.

**Comment by mifi** [comment]
yea I think it's because of keyframes. you cannot cut between two keyframes, and i guess your video has 8 seconds between the first 2 keyframes. In the future I plan to implement a function where it will do a (lossy) re-encode of the portion between two keyframes

**Comment by mifi** [comment]
I'm closing this. See #41 and #126

**Comment by hueldoeu** [comment]
keyframes. interesting to know. i have to keep in mind that after starting the record, i shouldn't move or take actions for at least 8 seconds.
