### ISSUE TITLE
Make_zero and make_non_negative shift timestamps settings cause frame skipping in VLC media player.

### ISSUE THREAD

**Issue by benzefid** [mifi/lossless-cut#1206]
I have cut a lot of mp4 clips always cutting on keyframes and on a significant amount there is a problem of frame skipping in the beginning, the very first frame is proper, but some frames after it skip and there is a visible stutter, the problem appears only when I play the clips in VLC media player, they play properly in Google Chrome and Microsoft Photos, changing shift timestamps setting to "auto" or "disabled" also makes them work properly in VLC media player. I don't have any idea why would this be an issue with VLC media player in particular.

**Comment by mifi** [comment]
Hard to say. I also had some problems with make_zero sometimes, maybe losslesscut should change the default setting to 'auto'

**Comment by benzefid** [comment]
Now I also have one clip (this one is an mkv originally which I save to mp4 if that matters, and also has audio track encoded with mp2 codec which doesn't play at all in LosslessCut) which when using "auto" or "disabled" works properly in VLC media player, has a stutter with missing frames in Google Chrome and somehow plays several frames before the keyframe at the beginning in Microsoft Photos, so I think there are some significant differences in how different players interpret timestamps. Wish there was some option that "just works" so I wouldn't have to worry about such compatibilities.

**Comment by GamerBene19** [comment]
I'm experiencing the same issue, but for me using `auto` does not solve it. It occurs on whichever `shift timestamps` setting i choose.

**Comment by mifi** [comment]
@GamerBene19 what about "disabled"?

**Comment by GamerBene19** [comment]
> @GamerBene19 what about "disabled"?

>  It occurs on whichever shift timestamps setting i choose.

I also tried out "disabled" iirc and the problem persisted

**Comment by mifi** [comment]
nothing actionable here unfortunately, closing.
