### ISSUE TITLE
Improvements for the future...

### ISSUE THREAD

**Issue by rubinrot59** [mifi/lossless-cut#1210]
Please first search for your feature request under Issues or Discussions, maybe someone else already suggested it.

**Is your feature request related to a problem? Please describe.**
Yes, see the following chapter. #2

**Describe the solution you'd like**
1. Format converting in a batch mode. I have in one folder around 40 flv video files which can converted without any problems as mp4 files (which my TV set understands). Actual I have to convert one file by the other.
2. The rotation of the clips don't works correct. The clip rotates but not the aspect ratio of the clip.
3. Sometimes I need a mirroring of clips (esp. for tik tok clips)
4. Sometimes I need a feature to correct the aspect ratios of a clip (f.e. a clip in youtube in the 16 to 9 format is in reality a clip in a 4 to 3 format).

*Describe alternatives you've considered**
See the next chapter

**Additional context**
I have a video clip collection with around 25.000 files. Collected during the last 15 years and in many formats (some are meanwhile outdated), The new standard should be now mp4. So I use your program to shorten / trim clips, convert them if necessary, assemble single files and make often chapter markers for the playback with my TV set. The easiest way to short / trim clips is the split segment at cursor feature, I have problems to use your default split feature. A keyboard shortcut for this split segment at cursor feature would be also nice. 
The flv to mp4 conversion works at best with youtubes 640x480 clips, Other formats or clips from other sites fails very often.
In such cases I use xMediaRecode (but this program needs too often an extra entry for the digitization rate), the converting tool of VLC (f.e. for exotic cases like ram/rm/asf/asx files), a batch file for VLC (mirroring/aspect ratio) or a video processor program (actual I try out KDEnlive for Linux).

**Comment by mifi** [comment]
> * Format converting in a batch mode. I have in one folder around 40 flv video files which can converted without any problems as mp4 files (which my TV set understands). Actual I have to convert one file by the other.

you can lock the output format so you don't have to change it one by one. If you want to batch convert many files from flv to mp4, I think using ffmpeg from the command line is the easiest way. Although It's possible that losslesscut could implement a function like this, I'm not sure how many people needs it because it's so easy to do with the command line:

```bash
for f in *.flv; do ffmpeg -i $f -c copy $f.mp4
```

> * The rotation of the clips don't works correct. The clip rotates but not the aspect ratio of the clip.

do you have some screenshots or an example file to explain what you mean by this?

> * Sometimes I need a mirroring of clips (esp. for tik tok clips)

not possible losslessly AFAIK. see https://github.com/mifi/lossless-cut/issues/372

> 4\. Sometimes I need a feature to correct the aspect ratios of a clip (f.e. a clip in youtube in the 16 to 9 format is in reality a clip in a 4 to 3 format).

ditto.

> A keyboard shortcut for this split segment at cursor feature would be also nice.

already exists. please see the keyboard shortcuts screen

does this answer your questions?

**Comment by mifi** [comment]
I'm going to close this for now - can reopen if you had more to add
