### ISSUE TITLE
Include a step (adding an exemption to LosslessCut and ffmpeg in Controlled Folder Access) in the export problem report dialog.

### ISSUE THREAD

**Issue by Anubeia** [mifi/lossless-cut#1211]
I wasn't sure where to put this as it's not really a feature nor a bug.

I like having Controlled Folder Access enabled (and by extension I must love breaking programs), and I need to add an exemption to the two processes stated above to complete my task. Consider adding a line or two to the "Unable to export this file" dialog to save headaches for both user and developers.

**Comment by mifi** [comment]
Hi. Im not sure what do you mean by «controlled folder access» and «exemption». Could you provide some more info about your error and operating system?

**Comment by Anubeia** [comment]
Controlled folder access is a setting you can toggle that stops files and folders from being changed by programs and processes that isn't on the whitelist. When an action is blocked, it appears in the notifications area -- clicking on it brings you to the ransomware protection screen where an option to add a program to the whitelist is available.


Windows Security [→] Virus & threat protection [→] Ransomware protection [→] Manage ransomware protection

**Comment by mifi** [comment]
Ok, I don't how losslesscut can detect that it's getting blocked by CFA. Do you have any more info about the error that occurs? (see troubleshooting)

**Comment by mifi** [comment]
closing due to lack of response
