### ISSUE TITLE
BUG REPORT

### ISSUE THREAD

**Issue by patricksun2807** [mifi/lossless-cut#1213]
Error: Command failed with exit code 1: C:\Users\patrick\AppData\Local\Temp\29bEkJpRUy1jupU0zGDBfALgrbp\resources\ffmpeg.exe -hide_banner -ss 82.00000 -i G:\[直播 2022 MP4]\[Cut 2022]\Minana 2022-01-02-225411.mp4 -t 196.60000 -avoid_negative_ts auto -map 0:0 -c:0 copy -map 0:1 -c:1 copy -map_metadata 0 -movflags +faststart -default_mode infer_no_subs -ignore_unknown -f mov -y G:\[Dance Cut 2022]\Minana 2022-01-02-225411-00.01.22.000-00.04.38.600-seg1.mov
'C:\Users\patrick\AppData\Local\Temp\29bEkJpRUy1jupU0zGDBfALgrbp\resources\ffmpeg.exe' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
    at makeError (C:\Users\patrick\AppData\Local\Temp\29bEkJpRUy1jupU0zGDBfALgrbp\resources\app.asar\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\patrick\AppData\Local\Temp\29bEkJpRUy1jupU0zGDBfALgrbp\resources\app.asar\node_modules\execa\index.js:118:26)
    at async file:///C:/Users/patrick/AppData/Local/Temp/29bEkJpRUy1jupU0zGDBfALgrbp/resources/app.asar/build/static/js/main.3131d877.js:2:304769
    at async file:///C:/Users/patrick/AppData/Local/Temp/29bEkJpRUy1jupU0zGDBfALgrbp/resources/app.asar/build/static/js/main.3131d877.js:2:305537
    at async file:///C:/Users/patrick/AppData/Local/Temp/29bEkJpRUy1jupU0zGDBfALgrbp/resources/app.asar/build/static/js/main.3131d877.js:2:2449876

{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "filePath": "G:\\[直播 2022 MP4]\\[Cut 2022]\\Minana 2022-01-02-225411.mp4",
    "fileFormat": "mov",
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1080,
        "closed_captions": 0,
        "has_b_frames": 1,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 42,
        "color_range": "tv",
        "color_space": "bt470bg",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "60/1",
        "avg_frame_rate": "418240000/6970669",
        "time_base": "1/16000",
        "start_pts": 32080,
        "start_time": "2.005000",
        "duration_ts": 13941338,
        "duration": "871.333625",
        "bit_rate": "8017661",
        "bits_per_raw_sample": "8",
        "nb_frames": "52280",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "VideoHandler",
          "vendor_id": "[0][0][0][0]"
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "44100",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/44100",
        "start_pts": 617,
        "start_time": "0.013991",
        "duration_ts": 38512639,
        "duration": "873.302472",
        "bit_rate": "129101",
        "nb_frames": "38469",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "SoundHandler",
          "vendor_id": "[0][0][0][0]"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "G:\\[直播 2022 MP4]\\[Cut 2022]\\Minana 2022-01-02-225411.mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {
        "start": 82,
        "end": 278.6
      },
      {
        "start": 393,
        "end": 610.1
      }
    ],
    "mainFileFormatData": {
      "filename": "G:\\[直播 2022 MP4]\\[Cut 2022]\\Minana 2022-01-02-225411.mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.013991",
      "duration": "873.303000",
      "size": "888997051",
      "bit_rate": "8143767",
      "probe_score": 100,
      "tags": {
        "major_brand": "isom",
        "minor_version": "512",
        "compatible_brands": "isomiso2avc1mp41",
        "encoder": "Lavf58.45.100"
      }
    },
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "separate"
  },
  "platform": "win32",
  "version": "3.45.0"
}

**Comment by mifi** [comment]
can you try zip version instead?
probably related: #1073
