### ISSUE TITLE
Improve "seek to timecode"

### ISSUE THREAD

**Issue by mifi** [mifi/lossless-cut#1217]
- [x] Right click to paste
  - See #1192
  - https://github.com/electron/electron/issues/4068
  - https://github.com/sindresorhus/electron-context-menu

## Seek to timecode

- [x] support more timecode formats in input field

from #1194: Users need this function very often but your timecode seek jumper is limited and I as user have to enter the exact right format which is "00:00:00.000". So this you should improve. I your tool I need to enter the whole length of digits and also the dot.

```
Example: 
00:06:39.730 <-- timecode works
00:06:39       <-- timecode works not
00:06:39,730 <-- timecode works not because of comma "," instead of dot
06:39.730      <-- timecode works not
```
The best is if you just check the format the timecode the user did enter new so that not all digits are needed to enter and also check for entered comma and make a dot etc to allow it. Also timecodes with only one digit where 2 are needed you  could check this before and out a 0 before like here...

Example: Timecode of srt subtitle file...
`00:06:1,260 --> 00:06:3,120`

As you can see the timecodes here are not using all digits places "00:06:1,260". In case of seconds its just using the last digit place without to use 0 digit before and your tool will not accept it and I have to set a 0 manually before and I also need to change the comma to dot to make it work in your tool. Would be nice if you could check & fix that format so that this also works. Would be nice if you could also add a PASTE button next the OK & Cancel button to prevent using keyboard shortcuts strg+v.

**Comment by mifi** [comment]
now implemented

**Comment by Dean-Corso** [comment]
> support more timecode formats in input field - Right click to paste https://github.com/mifi/lossless-cut/issues/1217

Not working! No paste menu showing on right mouse click or paste operation on right mouse click when the “Seek to timecode” window is showing.

**Comment by mifi** [comment]
Oops i mustve mixed together two concepts here.
The two lower set-cutpoints input boxes now support this, but the seek to timecode popup still does not

**Comment by mifi** [comment]
in the next version there will be a context menu on all input fields

<img width="369" alt="Screenshot 2023-07-26 at 10 03 15" src="https://github.com/mifi/lossless-cut/assets/402547/e078c943-3335-42c2-92cf-ed5dbd24af65">
