### ISSUE TITLE
Cannot View x265 Files Black Screen

### ISSUE THREAD

**Issue by defencedog** [mifi/lossless-cut#1218]
Windows 10

Screen shows black while playing x265 files; I have tried x2 different files. The audio plays fine also i can view / generate thumbnail strips but cannot view file?

I have tries last x2 versions of the application. 
I have tried using latest FFMPEG build (from setting `Using external ffmpeg')

Following x2 different file tracks are shown

![out](https://user-images.githubusercontent.com/831749/176594610-f629e513-4d13-4a8f-9a2c-633c96b41499.png)

**Comment by mifi** [comment]
is it possible to share a small file that reproduces the problem?

what about if you try this file: https://github.com/mifi/lossless-cut-fixtures/blob/master/Tears_400_x265.mp4

**Comment by defencedog** [comment]
I suppose sharing my clip isn't necessary. I cannot even play ur provided file **using built-in ffmpeg**

PS: I freshly downloaded win64 build & extracted it

**Comment by defencedog** [comment]
Further observation
When i snapshot (in any format png/jpeg) of a general mp4 file x264 all is well. When i repeat this with mp4 x265; a zero byte txt file is generated

**Comment by mifi** [comment]
any errors in dev console?

**Comment by mifi** [comment]
i assume you cannot cut/export either?

**Comment by defencedog** [comment]
> i assume you cannot cut/export either?

Weird I **blindly** selected x3 segments ...& project was properly exported / merged

**Comment by mifi** [comment]
hm. i don't see any errors. this probably means there's something with the canvas element which is used for rendering these kind of files. possibly related #575 #277
any chance of trying on a different computer? could be some issue with your GPU/driver conflicting with the chromium version that electron v8 uses, and might get automatically fixed in the future after #714

**Comment by defencedog** [comment]
@mifi  I acknowledge ur knowledge far surpass mine regarding such issue but i beg to differ regarding ur GPU statement. I have tried following but either way same black screen
![Screenshot_1](https://user-images.githubusercontent.com/831749/176851340-56fd6060-3e74-49ac-b9d2-b538967bb166.png)

**Comment by defencedog** [comment]
@mifi Ok I belive i get the issue sorted out
In my settings I had unchecked _Auto convert to supported format_ Then was hearing sound but no video!
Afterwards I loaded the video navigated to _File > Convert to supported format_ there existed multiple options; **2nd** option worked for me but the video was poor quality (although with sound). The video you provided doesnt have an audio track it also worked with **1st** option
Afterwards I tried 5th option _Remux Video only_ but it didn't work & i don't think viewing HEVC video with poor quality does any good! Also tried **4th option** but video still black

So it seems native support (without conversion to low quality preview video) for HEVC video codec isn't available. So any solution to this?

To be sure i isolated video track via
`ffmpeg -i "junia.mp4" -c:v copy -an out.mp4` & then loaded _out.mp4_ alone & it clearly displayed **Unsupported format** popup

![Screenshot_1](https://user-images.githubusercontent.com/831749/176966854-b1787d53-2a49-4fcb-a93e-1ee430c65dc8.png)

**Comment by mifi** [comment]
oh, ok. I assumed that you had already tried to convert to supported format as suggested under [Known issues & limitations](https://github.com/mifi/lossless-cut#known-issues--limitations) and that's what was giving a black screen... but then i guess the mystery is solved!

> Afterwards I tried 5th option _Remux Video only_ but it didn't work & i don't think viewing HEVC video with poor quality does any good! Also tried **4th option** but video still black

the idea behind the low resolution preview is that you can probably still figure out what's happening, enough to make the cuts, and when exporting the full original resolution will obviously be preserved

native support for h265 is not possible yet, as for higher resolution preview playback, that is something im looking into improving also, see #88

**Comment by defencedog** [comment]
#the idea behind the low resolution preview is that you can probably still figure out what's happening, enough to make the cuts,

your understanding is correct but i perfectly use this application as a viewer as well... 
Maybe u can take a look at this project ...here i can view / make cuts in situ for HEVC
https://github.com/ozmartian/vidcutter

**Comment by mifi** [comment]
unfortunately vidcutter is built on a completely different tech. but I'm hopeful that I will be able to allow increasing the playback quality (maybe using an option), just need to get some time to work on that

**Comment by defencedog** [comment]
Extremely thanks
