### ISSUE TITLE
Frame rate problem

### ISSUE THREAD

**Issue by xXHenlolXx** [mifi/lossless-cut#122]
I have a problem while cutting some anime videos. The cutted video register a very high frame rate, even if it is played back at the original frame rate (24). This is a problem because I want to use SVP to transcode it to 60fps, but it is impossible like this. Here is an example: 
Frame rate mode                : Variable
Frame rate                     : 724.747 FPS

And the original file:
Frame rate mode                : Constant
Frame rate                     : 23.976 (24000/1001) FPS

**Comment by passat1** [comment]
Remux output file with MKVToolnix and will have correct info.
See https://github.com/mifi/lossless-cut/issues/123

**Comment by mifi** [comment]
closing in favor of #123
