### ISSUE TITLE
Clip Hide Panel Toggle needs to be Static

### ISSUE THREAD

**Issue by defencedog** [mifi/lossless-cut#1220]
![Screenshot_1](https://user-images.githubusercontent.com/831749/177039406-73142950-75ea-4a05-b4ab-ebedb14e2a60.png)

If you have multiple clips; bcz of screen size limitation the toggler button gets hidden; to approach it one have to navigate by clicking segments in the panel until it reappears.

This button needs to be in FIXED position

**Comment by mifi** [comment]
hi. i'm not sure exactly what you mean. do you mean that "segments to export" title should have a fixed position so that it doesn't scroll?

**Comment by defencedog** [comment]
@mifi Yes ....if u have many segments you cannot approach this button

**Comment by mifi** [comment]
Ok I have now fixed that. thanks
