### ISSUE TITLE
Detect black-scene change - From Cursor position

### ISSUE THREAD

**Issue by adoenz** [mifi/lossless-cut#1226]
It's pretty cool how you implemented #623 ! And it works very well!

One small addendum I would have though: Would it be possible to have the "Detect black scenes" functionality working from cursor position onward?
Currently I have already created some segments they all are being deleted by Detect black scenes".
Starting the black scenes from cursor position onward would result in the following benefits:
a) It would take less time to process seeking for black scenes (e.g. if the cursor is in mid-file, only have the file would have to be processed)
b) The existing segments (left of cursor position that is) would remain existing.

**Comment by mifi** [comment]
would an alternative be to make the black scene change always append segments, instead of deleting existing segments? then you won't lose any existing segments when calling black scene

**Comment by mifi** [comment]
I've changed the black detect so that it searches only the interval defined by the currently selected segment

**Comment by mifi** [comment]
I think you can now achieve your initial request of only detecting segments to the right of the cursor by doing this:
- Create a new segment starting from the cursor position and onwards towards the end of the video.
- make sure this segment you just created is selected
- Detect black scenes, now it will only detect to the right of the cursor (the current segment)
- now you can delete the original segment you created

If that's not what you want, I'm not sure what you exactly mean by "content segments" vs "black segments".

**Comment by adoenz** [comment]
Your approach works fine for me. 
What I mean by "content segments" vs "black segments": Lossless currently creates segments for the blacks (instead of the scences with actual footage, i.e. "a dog running"); this requires me to always "invert segments" so that I have segments with actual content.
