### ISSUE TITLE
Error loading file

### ISSUE THREAD

**Issue by grahamck** [mifi/lossless-cut#1229]
This is a big file - about 10GB - which is why i want to cut it. :-)

Tried on 3 different computers and get this error. Anyone know what might cause this? 

Thanks!

Failed to open file
Command was killed with SIGTERM (Termination): C:\Users\idled\AppData\Local\Temp\29bEkJpRUy1jupU0zGDBfALgrbp\resources\ffprobe.exe -of json -show_chapters -show_format -show_entries stream -i Y:\Music\Strings, Billy\7-17-22.mp4 -hide_banner

**Comment by mifi** [comment]
So it works with all other files except that one? I'm thinking that some other program is killing ffprobe with SIGTERM, but I don't know what. And I don't know why it would happen on 3 separate computers, unless they're all running the exact same setup.

**Comment by grahamck** [comment]
Well - the only thing these 3 systems had in common was they were all accessing the videofiles from a NAS. I moved the file to local disk and this issue went away. Odd though - I have been running from this NAS for a long time - perhaps it has develpoed a performance issue. Marking closed, thanks for the help!
