### ISSUE TITLE
3.45.0 problem

### ISSUE THREAD

**Issue by kimooxx** [mifi/lossless-cut#1230]
When I use this program to edit the video merged by this program, the editing screen will shake.

Editing with other programs does not cause this problem.

**Comment by mifi** [comment]
you're going to have to provide more info than that.

**Comment by kimooxx** [comment]
In addition to the above problems. When I continue the clip is complete, it can't be merged.







----------------------------------------------------------------------

Error: Command failed with exit code 1: F:\Tools\LosslessCut-win-x64\resources\ffprobe.exe -of json -show_format -i G:\System Drivers\LOSSLESS CUT EDIT\hhd800.com@FC2-PPV-1876178_3-merged-00.04.50.049-00.05.22.347-seg5.mp4 -hide_banner
G:\System Drivers\LOSSLESS CUT EDIT\hhd800.com@FC2-PPV-1876178_3-merged-00.04.50.049-00.05.22.347-seg5.mp4: No such file or directory
{

}
    at makeError (F:\Tools\LosslessCut-win-x64\resources\app.asar\node_modules\execa\lib\error.js:60:11)
    at handlePromise (F:\Tools\LosslessCut-win-x64\resources\app.asar\node_modules\execa\index.js:118:26)
    at async Db (file:///F:/Tools/LosslessCut-win-x64/resources/app.asar/build/static/js/main.f18f3ad4.js:2:296057)
    at async file:///F:/Tools/LosslessCut-win-x64/resources/app.asar/build/static/js/main.f18f3ad4.js:2:297287
    at async Fb (file:///F:/Tools/LosslessCut-win-x64/resources/app.asar/build/static/js/main.f18f3ad4.js:2:297215)
    at async file:///F:/Tools/LosslessCut-win-x64/resources/app.asar/build/static/js/main.f18f3ad4.js:2:2382031

{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "filePath": "G:\\System Drivers\\LOSSLESS CUT EDIT\\hhd800.com@FC2-PPV-1876178_3-merged.mp4",
    "fileFormat": "mp4",
    "externalFilesMeta": {},
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1080,
        "closed_captions": 0,
        "film_grain": 0,
        "has_b_frames": 2,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 40,
        "chroma_location": "left",
        "field_order": "progressive",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "id": "0x1",
        "r_frame_rate": "2997/100",
        "avg_frame_rate": "721437840/24073009",
        "time_base": "1/11988",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 96291812,
        "duration": "8032.350017",
        "bit_rate": "8520714",
        "bits_per_raw_sample": "8",
        "nb_frames": "240720",
        "extradata_size": 50,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "VideoHandler",
          "vendor_id": "[0][0][0][0]"
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "HE-AAC",
        "codec_type": "audio",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "id": "0x2",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/48000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 385552544,
        "duration": "8032.344667",
        "bit_rate": "70968",
        "nb_frames": "188256",
        "extradata_size": 7,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "Sound Media Handler",
          "vendor_id": "[0][0][0][0]"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "G:\\System Drivers\\LOSSLESS CUT EDIT\\hhd800.com@FC2-PPV-1876178_3-merged.mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {
        "start": 132.565899,
        "end": 136.235843
      },
      {
        "start": 156.562671,
        "end": 159.162504
      },
      {
        "start": 197.306193,
        "end": 205.682546
      },
      {
        "start": 252.769091,
        "end": 261.041147
      },
      {
        "start": 290.049003,
        "end": 322.346734
      },
      {
        "start": 357.841797,
        "end": 364.209683
      },
      {
        "start": 2191.816419,
        "end": 2197.99232
      },
      {
        "start": 2907.942015,
        "end": 2930.165564
      },
      {
        "start": 2948.493337,
        "end": 2961.220307
      },
      {
        "start": 2969.014971,
        "end": 2986.625544
      },
      {
        "start": 2998.372044,
        "end": 3019.339846
      },
      {
        "start": 3024.514598,
        "end": 3034.531493
      },
      {
        "start": 3041.501074,
        "end": 3052.47708
      },
      {
        "start": 3064.946644,
        "end": 3080.450923
      },
      {
        "start": 3095.646375,
        "end": 3115.214137
      },
      {
        "start": 3139.084249,
        "end": 3210.390686
      },
      {
        "start": 3229.647584,
        "end": 3239.243244
      },
      {
        "start": 3372.794233,
        "end": 3380.690032
      },
      {
        "start": 3607.288912,
        "end": 3615.696892
      },
      {
        "start": 3680.549633,
        "end": 3686.509914
      },
      {
        "start": 3816.820468,
        "end": 3833.90139
      },
      {
        "start": 3838.589613,
        "end": 3845.09358
      },
      {
        "start": 3852.568024,
        "end": 3873.656231
      },
      {
        "start": 3879.158183,
        "end": 3926.48471
      },
      {
        "start": 3946.962542,
        "end": 3961.930434
      },
      {
        "start": 3981.876233,
        "end": 3991.828004
      },
      {
        "start": 4157.546867,
        "end": 4160.394966
      },
      {
        "start": 4167.084119,
        "end": 4172.939848
      },
      {
        "start": 4258.345016,
        "end": 4264.79291
      },
      {
        "start": 5423.593838,
        "end": 5438.3301
      },
      {
        "start": 5572.806277,
        "end": 5581.353145
      },
      {
        "start": 5651.478373,
        "end": 5655.646527
      },
      {
        "start": 5739.338129,
        "end": 5748.721842
      },
      {
        "start": 5758.206695,
        "end": 5765.239074
      },
      {
        "start": 5838.203618,
        "end": 5851.77296
      },
      {
        "start": 5993.57197,
        "end": 6002.636153
      },
      {
        "start": 6027.64241,
        "end": 6031.82525
      },
      {
        "start": 6051.96484,
        "end": 6066.61479
      },
      {
        "start": 6098.939772,
        "end": 6104.315719
      },
      {
        "start": 6126.201854,
        "end": 6137.682223
      },
      {
        "start": 6223.393013,
        "end": 6240.001189
      },
      {
        "start": 6360.839277,
        "end": 6370.871508
      },
      {
        "start": 6451.402715,
        "end": 6455.106464
      },
      {
        "start": 6465.764414,
        "end": 6470.676197
      },
      {
        "start": 6521.626707,
        "end": 6530.064651
      },
      {
        "start": 6543.798261,
        "end": 6552.890585
      },
      {
        "start": 6566.027633,
        "end": 6572.011857
      },
      {
        "start": 6576.612946,
        "end": 6585.973618
      },
      {
        "start": 6675.846748,
        "end": 6689.160808
      },
      {
        "start": 6698.592906,
        "end": 6768.356082
      },
      {
        "start": 6776.486644,
        "end": 6789.783811
      },
      {
        "start": 6824.113873,
        "end": 6839.250854
      },
      {
        "start": 6855.355645,
        "end": 6884.24509
      },
      {
        "start": 6952.687129,
        "end": 6957.165446
      },
      {
        "start": 6994.617728,
        "end": 7001.655674
      },
      {
        "start": 7025.299942,
        "end": 7088.756612
      },
      {
        "start": 7117.737618,
        "end": 7125.425339
      },
      {
        "start": 7155.502393,
        "end": 7167.750183
      },
      {
        "start": 7175.672668,
        "end": 7179.177672
      },
      {
        "start": 7236.153893,
        "end": 7253.785858
      },
      {
        "start": 7265.086453,
        "end": 7278.254296
      },
      {
        "start": 7300.188265,
        "end": 7311.891712
      },
      {
        "start": 7323.861831,
        "end": 7335.389856
      },
      {
        "start": 7368.82537,
        "end": 7380.998623
      },
      {
        "start": 7637.352479,
        "end": 7655.648587
      },
      {
        "start": 7686.497723,
        "end": 7691.940071
      },
      {
        "start": 7829.76895,
        "end": 7835.001065
      },
      {
        "start": 7844.221613,
        "end": 7889.453511
      },
      {
        "start": 7915.437917,
        "end": 7938.136105
      },
      {
        "start": 7960.621351,
        "end": 7974.888714
      },
      {
        "start": 8020.922054,
        "end": 8031.466171
      }
    ],
    "mainFileFormatData": {
      "filename": "G:\\System Drivers\\LOSSLESS CUT EDIT\\hhd800.com@FC2-PPV-1876178_3-merged.mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "8032.351000",
      "size": "8632420498",
      "bit_rate": "8597652",
      "probe_score": 100,
      "tags": {
        "major_brand": "isom",
        "minor_version": "512",
        "compatible_brands": "isomiso2avc1mp41",
        "encoder": "Lavf58.76.100"
      }
    },
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "merge"
  },
  "platform": "win32",
  "version": "3.46.2"
}

**Comment by mifi** [comment]
Unfortunately im struggling to I understand what’s the problem here. Could you provide a more detailed instructions for how to reproduce the problem you’re having, maybe with screenshots? You can use this form if it’s easier:

https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml
