### ISSUE TITLE
Feature Request: Allow delete inner segment inside outer segment - New function "split segment"

### ISSUE THREAD

**Issue by pstein** [mifi/lossless-cut#1237]
Assume I load a video and select a segment/interval inside with a start and an end cutpoint.

Now I recognize that I need to delete an inner segment/intervall inside this mentioned, just created outer segment interval.

If I click somewhere inside this existing segment and set an endpoint the previous end cut point is removed.
Similarly it happens when I set a new start cut point.

Ok, I could set the just removed cutpoints again manually.
But thats bad since it is often difficult to find and re-position and re-set the just removed exact cutpoints.

I would appreciate if LosslessCut could provide a new "split" action which inserts a new endpoint=start point at the current cursor position. That way the existing cutpoints are preserved and I am free to set/move new start/end cutpoints inside an existing interval

Thank you.

**Comment by mifi** [comment]
hi. i'm not sure i understand, could you try to illustrate? there is already a split function that will split segment into two segments at the cursor, how is this different?

**Comment by pstein** [comment]
Found it!
Sorry I expect in near the controls in the mid and not below the segment list
...Problem solved
