### ISSUE TITLE
Option to autoimport chapters

### ISSUE THREAD

**Issue by HolgerJeromin** [mifi/lossless-cut#1240]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

I import the files from my tvheadend recordings which contains always three chapters (padding before the recording, the recording itself and padding after it).
If I drop the file LC asks me to import the chapters.
I found "Ask about importing chapters from opened file?" in the settings.
But this is a boolean and when disabled the chapters are not detected.

I would like to have a three way option:
> Import chapters from opened file? `Yes`, `Ask`, `No`.

**Comment by mifi** [comment]
thanks. i added it here: #371 so i'll close this to keep issue count down
