### ISSUE TITLE
Task complete notice

### ISSUE THREAD

**Issue by patricksun2807** [mifi/lossless-cut#1242]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Hope add notification when tasks complete in next version
[Notice.txt](https://github.com/mifi/lossless-cut/files/9175166/Notice.txt)
.

**Comment by mifi** [comment]
please explain what you mean by that
