### ISSUE TITLE
Trusted Cert Error cannot install appx

### ISSUE THREAD

**Issue by tidypy** [mifi/lossless-cut#1243]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with a different kind of file to confirm that the problem is related to just this file.
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut and **Known issues / Troubleshooting**
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Steps to reproduce

download the appx.  double click.  

### Expected behavior

installation begins.

### Actual behavior

Signed Certificate error, preventing install.

### Provide an error report

This app package is not signed with a trusted certificate. Contact your system administrator or the app developer to obtain a new certificate or app package with trusted certificates. The root certificate and all immediate certificates of the signature in the app package must be trusted (0x800B010A)

### Share the file

none

### Share log

trusted cert needed windows is blocking the install

**Comment by tidypy** [comment]
Even if I "Unblock" via right-clicking on the file --> going to  properties --->  I then get "Unknown Publisher" error instead.  
It will still not let me install.

**Comment by tidypy** [comment]
running CMD as admin and trying to install did not work either.

**Comment by tidypy** [comment]
![2022-07-24 14_32_52-Window](https://user-images.githubusercontent.com/50213641/180663151-9a385a18-692a-4eb7-829d-152558109912.png)

**Comment by mifi** [comment]
this has been reported many times, please search first before creating an issue :|
https://github.com/mifi/lossless-cut/search?q=appx&type=issues

i will try to somehow make it more clear that it's not possible to run the appx
