### ISSUE TITLE
Dummy files not working properly

### ISSUE THREAD

**Issue by XEVON01** [mifi/lossless-cut#1246]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut and **Known issues / Troubleshooting**
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 11

### Steps to reproduce

here is a issue I'm facing with lossless cut
whenever I try to cut a .ts file, a dummy file is created which doesn't work properly 
the frame takes time or it comes late, like I went 1 second forward but the frame appears after sometime
which consumes a lot of time 
please make .ts file also supportable and fix this issue

### Expected behavior

please make .ts file also supportable and fix this issue

### Actual behavior

whenever I try to cut a .ts file, a dummy file is created which doesn't work properly 
the frame takes time or it comes late, like I went 1 second forward but the frame appears after sometime

**Comment by mifi** [comment]
i think this is working as expected. there is a latency because of the way the dummy preview works.

you can try file -> convert to supported format:
- Fast: Full quality remux, likely to fail
- Slow: Low quality encode (no audio)

**Comment by XEVON01** [comment]
I see
I will try the method you told 
but if possible please make .ts also a supported format with .m2ts also

**Comment by mifi** [comment]
for native support for more formats like .ts, see existing issue #88
