### ISSUE TITLE
need Control playback volume

### ISSUE THREAD

**Issue by ircopdd** [mifi/lossless-cut#125]
need Control playback volume

**Comment by mifi** [comment]
I just use my system volume, but I can leave it open to see if more ppl want this

**Comment by CKoewing** [comment]
that would be awesome

**Comment by kkeonline** [comment]
Yes, I also need it, especially mute button (effect playback only not exported vdo)

**Comment by mifi** [comment]
what's the use case for this? wanna listen to music while cutting vids?

**Comment by Jinksi** [comment]
> what's the use case for this? wanna listen to music while cutting vids? 🎶

Yeh, music and/or podcasts 😅

**Comment by mifi** [comment]
now implemented
