### ISSUE TITLE
Can't add audio

### ISSUE THREAD

**Issue by LaVelaPodcast** [mifi/lossless-cut#1254]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut and **Known issues / Troubleshooting**
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

1 Open my MKV file on LosslessCut
2 Extract the tracks
3 Edit audio (just compressor and normalizing) on Audacity.
4 Exporting the audio as MP3· or M4a from Audacity.
5 Open the extracted video track on LosslessCut
6 Drag and drop the mp3 or m4a file into LosslessCut
7 Check that both tracks appear as green at the Export dialogue.
8 Export as mp4

### Expected behavior

Get an mp4 file with audio

### Actual behavior

No audio in the video. Only video is exported

**Comment by mifi** [comment]
if you can share log (codec parameters) for each file you're trying to combine tracks for, i can try help you

**Comment by glecas** [comment]
I had this same problem today trying to join video and audio in version 3.46.2

**Video:**
```
Format                      : MPEG-4
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : High@L3.1
Format settings             : CABAC / 4 Ref Frames
Format settings, CABAC      : Yes
Format settings, Reference  : 4 frames
Codec ID                    : avc1
Duration                    : 1 min 27 s
Bit rate                    : 861 kb/s
Width                       : 270 pixels
Height                      : 480 pixels
Display aspect ratio        : 0.563
Frame rate mode             : Constant
Frame rate                  : 23.976 (24000/1001) FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Bits/(Pixel*Frame)          : 0.277
Stream size                 : 8.94 MiB (100%)
Writing library             : x264 core 164
Encoding settings           : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=0 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=15 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=8 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=50 / keyint_min=5 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=crf / mbtree=1 / crf=18.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=2025 / vbv_bufsize=2700 / crf_max=0.0 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:1.00
Color range                 : Limited
Color primaries             : BT.709
Transfer characteristics    : BT.709
Matrix coefficients         : BT.709
Codec configuration box     : avcC
```

**Audio:**
```
Format                      : MPEG Audio
File size                   : 1.26 MiB
Duration                    : 1 min 27 s
Overall bit rate mode       : Variable
Overall bit rate            : 121 kb/s
Writing library             : LAME3.99r

Format version              : Version 1
Format profile              : Layer 3
Format settings             : Joint stereo / MS Stereo
Minimum bit rate            : 32.0 kb/s
Channel(s)                  : 2 channels
Sampling rate               : 44.1 kHz
Frame rate                  : 38.281 FPS (1152 SPF)
Compression mode            : Lossy
Stream size                 : 1.26 MiB (100%)
Encoding settings           : -m j -V 2 -q 0 -lowpass 18.5 --vbr-new -b 32
```

**NOTE!** Tried the same files using version 3.42.0 instead and it worked fine 🙂

**Comment by mifi** [comment]
I just tested this exact same thing with 3.46.2 and lame `lame -m j -V 2 -q 0 --vbr-new -b 32 in.mp3 out.mp3`, but it works for me, the audio is being played back.
I used MOV as output format.
If someone can share some files that reproduce the problem then I can look into it

**Comment by glecas** [comment]
Try these files for example. For me it works in some versions but not in others as listed below:
[KanDuInteCykla.zip](https://github.com/mifi/lossless-cut/files/9316334/KanDuInteCykla.zip)

**Works in:**
- 3.42.0
- 3.43.0

**Does not work in:**
- 3.46.2
- 3.45.0
- 3.44.0

**Comment by mifi** [comment]
I tried to combine your mp4 and mp3 and it works for me with 3.46.2 if I select output format **MOV**. In quicktime it plays back successfully with audio. which player are you using?
Note that if I select output format **mp4**, there is no audio

**Comment by glecas** [comment]
It doesn't work for me using **.mp4** or **.mov** format. I tried playing the files using **VLC 3.0.16** or **QuickTime 7.7.9** (1680.95.84).

I am on a Windows system. If I combine the same files with **LosslessCut 3.43.0** I get both video + audio 👍 so that's my workaround at the moment 🙂

**Comment by mifi** [comment]
maybe you can provide an error report from the help menu after opening the exported file. it will show whether there is an audio track at all.
also please try with the newest version of llc

**Comment by glecas** [comment]
I uninstalled other video editor (Cyberlink PowerDirector) and rebooted computer. Now it works on all versions. So the problem I had was probably not related to LLC 🙂👍 I am not sure what the problem was but now it all works (for me) and I am happy. Not sure about the OP (@LaVelaPodcast) though.

**Comment by mifi** [comment]
can reopen if still a problem with the latest version
