### ISSUE TITLE
Dropping the same file on losslesscut window ignores it. I think it's a bug because:

### ISSUE THREAD

**Issue by trollcop** [mifi/lossless-cut#1256]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut and **Known issues / Troubleshooting**
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

I wanted to merge a bunch of files together repeatedly (think making like 1 hour youtube video) which would involve repeating a bunch of same small clips over and over. I selected ~8 files and dropped them, resulting in a merge window appearing.
I wanted to add them again, and dropped the same 8 again, but nothing happened.

I ended up merging 8 clips once, then opening a new project, merging result of the previous merge twice, then again.
Seems kinda silly.

### Expected behavior

Dropping same files should just add them to merge list again? I think.

### Actual behavior

Additional drops were ignored.

**Comment by mifi** [comment]
This would be a feature request. Unfortuantely I don't think it's so easy to implement because the file path is used as a unique key (index) in the code, so it cannot be duplicated

**Comment by trollcop** [comment]
Ah, I see.
I thought it was specifically made to ignore dupes.
Because technically in ffmpeg command line you can specify multiple copies of same file and it would merge them happily.
Hm..

**Comment by mifi** [comment]
I will close this, because it's very closely related to #597 - because more people are asking for it, maybe i could implement it in the future

**Comment by trollcop** [comment]
Thanks, that works. I subscribed to the other feature request.
