### ISSUE TITLE
MEJORAR LA TRADUCCION a otros idiomas

### ISSUE THREAD

**Issue by oliko-tk** [mifi/lossless-cut#1257]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

El programa viene con idioma predeterminado en ingles..  cuando  cambio al idioma español..  algunas  palabras (en configuración de botones) no terminan de traducirse, eso quiere decir que aun falta traducir ciertas palabras.  se quedan en idioma ingles. 

Para un mejor aprovechamiento  de este fabuloso programa seria bueno que la traducción a otros idiomas sea completa.

Agradecer al desarrollador por tan fabuloso y genial programa.

**Comment by mifi** [comment]
you are free to help translate the app at https://hosted.weblate.org/projects/losslesscut/losslesscut/

puede ayudar a traducir la aplicación en https://hosted.weblate.org/projects/losslesscut/losslesscut/
