### ISSUE TITLE
INCREASE THE AUDIO VOLUME OF A VIDEO

### ISSUE THREAD

**Issue by oliko-tk** [mifi/lossless-cut#1260]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Add the option to raise only the volume of the audio, so that it sounds louder. (Only the volume .. and NOT the volume quality, so that it does not harm the weight of the video file)

**Comment by mifi** [comment]
I'm not sure what you mean by "volume quality". I assume you want to losslessly change volume of a file, see this existing issue #71
