### ISSUE TITLE
option to increase volume in export window

### ISSUE THREAD

**Issue by cliveod** [mifi/lossless-cut#1261]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

please can we have an option to increase volume in the export window. maybe just a text box to input a number to increase by or decrease by inputting a negative number,

I see you already have a volume up but it stops at 100%,
during export there is a option to increase volume of the audio track way above 100%

see https://trac.ffmpeg.org/wiki/AudioVolume for details
thanks 
Clive

**Comment by mifi** [comment]
please search first before creating an issue :| https://github.com/mifi/lossless-cut/issues?q=is%3Aissue+volume
