### ISSUE TITLE
Exported File Not Cutted

### ISSUE THREAD

**Issue by LenKiMo** [mifi/lossless-cut#1262]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut and **Known issues / Troubleshooting**
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 11

### Steps to reproduce

I recorded a video of the game through OBS and saved it as an MKV file of AVC1/AAC. I imported the software for editing, and removed the clip from 00:01.867~01:12.726. In the sidebar window, I can see that the software has correctly obtained the clip to be cut.
However, when exporting the file, LosslessCut does not export the cut file, but re-exports the original, complete video file. Even if the output format is modified to mp4.

Demo File: https://pan.lun.im/s/5XK53HGLsKBLSEr

### Expected behavior

The software can export the edited video file normally

### Actual behavior

The software exports the original unedited files.

### Share log

No error occurred.

{
  "state": {
    "filePath": "C:\\Users\\[Deleted]\\Desktop\\3炸弹倒计时的航海日.mkv",
    "fileFormat": "mp4",
    "externalFilesMeta": {},
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1080,
        "closed_captions": 0,
        "film_grain": 0,
        "has_b_frames": 1,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 42,
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "field_order": "progressive",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "60/1",
        "avg_frame_rate": "60/1",
        "time_base": "1/1000",
        "start_pts": 17,
        "start_time": "0.017000",
        "bits_per_raw_sample": "8",
        "extradata_size": 61,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "DURATION": "00:01:13.266000000"
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/1000",
        "start_pts": 17,
        "start_time": "0.017000",
        "extradata_size": 5,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "title": "simple_aac_recording",
          "DURATION": "00:01:13.254000000"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "C:\\Users\\[Deleted]\\Desktop\\3炸弹倒计时的航海日.mkv": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {
        "start": 1.8666666666666667,
        "end": 72.726057
      }
    ],
    "mainFileFormatData": {
      "filename": "C:\\Users\\[Deleted]\\Desktop\\3炸弹倒计时的航海日.mkv",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "matroska,webm",
      "format_long_name": "Matroska / WebM",
      "start_time": "0.017000",
      "duration": "73.266000",
      "size": "99941982",
      "bit_rate": "10912781",
      "probe_score": 100,
      "tags": {
        "ENCODER": "Lavf58.76.100"
      }
    },
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "separate"
  },
  "platform": "win32",
  "version": "3.46.2"
}

**Comment by mifi** [comment]
Hi

> removed the clip from 00:01.867~01:12.726

By default losslesscut will not remove the segment, but it will **keep** the segment and export it. Anything around the segment will be removed. However it seems that you are trying to cut right before the first keyframe, which will not work. alternatively you can try the "smart cut feature". please see the readme https://github.com/mifi/lossless-cut#known-issues--limitations

**Comment by danzpaim** [comment]
> Hi
> 
> > removed the clip from 00:01.867~01:12.726
> 
> By default losslesscut will not remove the segment, but it will **keep** the segment and export it. Anything around the segment will be removed. However it seems that you are trying to cut right before the first keyframe, which will not work. alternatively you can try the "smart cut feature". please see the readme https://github.com/mifi/lossless-cut#known-issues--limitations

I have this same problem. Thanks for support!
I solved using KDENLiVE.

**Comment by GoroDaimon** [comment]
> Hi
> 
> > removed the clip from 00:01.867~01:12.726
> 
> By default losslesscut will not remove the segment, but it will **keep** the segment and export it. Anything around the segment will be removed. However it seems that you are trying to cut right before the first keyframe, which will not work. alternatively you can try the "smart cut feature". please see the readme https://github.com/mifi/lossless-cut#known-issues--limitations

I solved with KDENLIVE too.

**Comment by LenKiMo** [comment]
The problem is that the , key jumps to the previous frame or the next frame normally, though. However, LossLessCut considers the keyframes of a series of MKV files to be differentiated in 5 second intervals. This causes the software to not capture the keyframes for cutting. I don't know if this is due to the file itself or a problem with the software recognizing keyframes.

**Comment by mifi** [comment]
losslesscut uses ffprobe to detect keyframes. Either something wrong with the way ffprobe detects keyframes, or something wrong with the way losslesscut reads the output from ffprobe. If someone has a file that shows incorrect keyframes, then sharing it would help me look into the problem

**Comment by LenKiMo** [comment]
> losslesscut uses ffprobe to detect keyframes. Either something wrong with the way ffprobe detects keyframes, or something wrong with the way losslesscut reads the output from ffprobe. If someone has a file that shows incorrect keyframes, then sharing it would help me look into the problem

The video attached to the link below is the one I originally posted in issue, in the 3.46.2 software it has keyframes listed in 5 second increments (as seen in the progress bar), but the `,` key or `.` keys to move slowly between frames.

If you select any part between two keyframes for export, the software will not recognize the keyframes and will eventually export the entire file.

The source video was recorded using OBS.

https://pan.lun.im/s/6QiGbdYnC8PYG4S

**Comment by mifi** [comment]
I just tested your file in the latest losslesscut and I can see that it has keyframes about 4 sec apart.

<img width="867" alt="Screenshot 2022-10-14 at 20 37 10" src="https://user-images.githubusercontent.com/402547/195917435-878e4ff1-297f-41e2-ba2f-9c470337c38a.png">

I tried to export a short segment between two keyframes and it does **not** result in the **entire file ** being exported, but rather a 3 second segment
Not sure how to reproduce your problem. I'm using Keyframe cut, and no smart cut.

**Comment by KatieBelli** [comment]
I had the same issue but I found out how to solve the problem (at least for me):

Choose "Seperate Files" in the right corner, next to the output format.

![solution](https://user-images.githubusercontent.com/109644887/203597354-9f40d165-2610-4a8a-81c1-221694c0df91.JPG)

Hope this helped.

**Comment by ArtisanDejure** [comment]
Thanks, this helped me!  Separate files it is!

**Comment by J-Broadway** [comment]
I ran into a similar issue. I fixed by enabling `Smart Cut (Experimental)` in the export settings

**Comment by gabselksiqueira10-art** [comment]
I tried to cut at the exact time in the video, but it kept snapping a little before the mark—probably because of the 5-second interval mentioned above.
For me, the Smart Cut option in the Export Settings worked as well.
