### ISSUE TITLE
Merged mkv/H.264 videos are dropping frames in sections when uploaded to youtube.

### ISSUE THREAD

**Issue by M-Walrus** [mifi/lossless-cut#1264]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut and **Known issues / Troubleshooting**
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

Using NVEnc NEW (H.264) in OBS to create the videos as I always have, but now with recent changes to this program the resulting files are being mangled when re-encoded on youtube's side.  This results in every third frame being dropped, giving consistently stuttery playback in specific sections that were merged.  I'm only using keyframe cuts in lossless cut when needed, but the most recent video I spliced together did not even use lossless cut to splice anything, just joined the parts together, and this is creating consistent and reproducible visual glitches every time a video is processed by youtube now.  The originating file when viewed on my PC does not have any of these stuttering issues when I play back the video with MPC-HC/MadVR.  Some change in the program is causing this, and I've wasted several hours re-recording and uploading video and then waiting again for it to process.

This is a new occurrence since a change was made in this program, though I do not know what change that was.  I need to revert to an older version because of this, which I was planning on doing anyway so that toggling keyframe/normal cut is not hidden behind a menu system and is again usefully on the main interface window.  

I have used lossless cut for many years now and am certain this behavior is something new.

It's possible this issue is related to issue report #1206 , though I am not sure as I do not use VLC.

### Expected behavior

It should produce a smoothly playing video that can be uploaded to youtube without issues in the re-encoding process after merging mkv/H.264 sections of videos.

### Actual behavior

Stutter often occurs in various sections of the video that have been joined together by using the new "merge" workflow.

**Comment by M-Walrus** [comment]
I am currently re-uploading the exact same video merged with version 3.32.0 this time, and will respond back as to whether that works when it finishes processing.

**Comment by M-Walrus** [comment]
I tested joining this footage many previous versions and got the same result.  I think the cause may be that I merged the early intro/demo segment of my video in the most recent build of losslesscut.  I'll provide links to examples here if it may help figure out whats going on.  When I re-recorded the intro/demo segment and then merged it again in an earlier version, the resulting video did not have stutter on youtube in the later gameplay portion. (timestamped examples on youtube below)

Here is the mkv of the merged intro/demo segment from the most recent losslesscut build that I think is the root of the issue:
https://mega.nz/file/iFszkYaI#NhvroglUBct50oOsI5pCzlil06XZBO-vQhEUTvR4tLg

This is the Intro and all character demo loops for Mortal Kombat 2.  I merged the CPU demos together using losslesscut to prevent having to show the intro over and over again during the character demos.  8 segments were merged to make this particular video, and every time I uploaded it with the gameplay portion merged afterwards, I got the frame skipping issue in the gameplay portion after youtube had processed the video.  My primary use for losslesscut (and has been for years) is to show the demo and intros for games without having to record those segments every time I want to restart a run through the actual game.  It's worked very well for me up until recently when I noticed these stutter issues.


Here is what it looks like on youtube after the above linked demo/intro video was merged with the following gameplay segment, timestamped to where the skipping is most clearly visible:  https://youtu.be/xsdJw5HidTg?t=509
The scrolling/animation there should be a completely smooth 60fps, but obviously is not anymore. Every third frame skips.


Here is what it looks like on youtube now that I re-recorded the intro/demo segment and joined it with the same gameplay segment as before, all performed in an older version (2.7.1): https://youtu.be/bT-P61HO6w8?t=512


I also downloaded VLC and was able to confirm that this seems to be completely unrelated to issue #1206 referenced in my original report, as the video that had issues in youtube played without stutter/skips in VLC, just as it did in MPC-HC for me.

**Comment by mifi** [comment]
Sorry for the delay. This is a hard one. It could possibly be due to ffmpeg having been continuously upgraded in recent LLC versions, maybe ffmpeg has changed some behavior in some newer version. If you run the newest version and enable the "Check files" checkbox in the Merge dialog, it will compare the codec parameters of each file, and it will warn about any differences it finds - That might give some clues.

**Comment by M-Walrus** [comment]
I have been using version 3.22.2 for 5 months now and the issue has not happened again.  I'll continue to use it throughout the year and report back if any instance of this occurs.  It is very obvious and something I would not miss, as I verify all uploads to youtube to ensure it encodes on their side properly with the heavy scanline filtering I typically use.

**Comment by M-Walrus** [comment]
I would like to follow-up on this and close it out now that I have encountered the issue again and a workable fix.  It seems to stem from the use of mkv files and occasional reliability issues with the container compared to other options like mp4, when using ffmpeg.

I encountered this issue again with my latest video last week (timestamped example: https://youtu.be/u-RfqB3jj8g?si=592Z39MpUX-IGGGF&t=8407) , while still using the ancient version of losslesscut I mentioned above that I didn't have the issues with before that incident, or since.  That turned out to be a red herring, because the issue is so uncommon that it rarely shows up.  I had used losslesscut for many videos before this instance occurred, so it was unclear if reverting really was a proper fix.  It turns out that it wasn't and the issue is just so rare that I had not encountered it again afterwards until now. 

The troubleshooting updates in the readme helped steer me down the right path here, as I saw other mentions of mkv having potential issues with ffmpeg.  After this issue happened with my latest video this past week, I re-uploaded it several times and tried many things, including "fix incorrect duration" and combining smaller chunks instead of all 9 parts at once.  I cannot fathom why the issue happens in the way it does, since I combined the problematic part and both adjacent parts together and was able to upload that and get a smooth resulting video on youtube (timestamped example: https://youtu.be/RxchPfZ8LnE?si=l8SpW6hXUqiTxyIz&t=1647) , but as soon as I combined the rest of the portions with that chunk and uploaded again, the exact issue happened on youtube once more.  

**Converting all the files from mkv to mp4 via the losslesscut interface, finally resulted in the complete video playing back smoothly, with absolutely no stutter as noticed before.**  (timestamped example: https://youtu.be/WFIQWOuAY4M?si=do74MP_g-IG8DSt1&t=8406)

I uploaded the video 5 times before this in mkv format, even going so far as to re-record that middle segment, and had the stuttering issue occur each and every time.  Not until converting to mp4 and uploading was I finally able to get it to play back correctly.  Truly confusing, but I believe this is solved now and wanted to follow-up on this issue ticket.

Since OBS now supports fMP4 (fragmented MP4) in a recent update, I will use that going forward.  I used mkv before since it had a lower risk of losing data in case a recording stopped for any reason.  If the issue happens to arise again after making this switch to mp4, I'll report back, but for now I think this is solved.  I would wholeheartedly recommend everyone using losslesscut to use mp4 instead of mkv, to minimize the chance of weird stuff like this arising from ffmpeg.

Thanks for making this great program- 5 years later I'm still using it regularly.  Cheers.


(Be sure to watch the example videos in 60fps so you can fully see the difference in smoothness I'm referring to.)
