### ISSUE TITLE
Auto Close When Export Complete

### ISSUE THREAD

**Issue by ChicagoScanningMG** [mifi/lossless-cut#1265]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

I would love to have the option to enable closing the program when a file finishes exporting.

**Comment by mifi** [comment]
what's the use case for this?

**Comment by ChicagoScanningMG** [comment]
This is in Windows 10 by the way.

**Comment by mifi** [comment]
Could an alternative be that LosslessCut would check for an existing running instance when starting up, and only start up if not already running (probably behind a setting)? I believe this is how it works on MacOS out of the box

**Comment by ChicagoScanningMG** [comment]
That would be fine so long as the new file opens in place of the old one in the currently running instance.
