### ISSUE TITLE
Add new merge mode that exports only merged movie

### ISSUE THREAD

**Issue by TehPlayer14** [mifi/lossless-cut#127]
It would be the same as exporting the cut and merged but remove the separate fragments after merging

**Comment by mifi** [comment]
Maybe I can just change it so that when merging, it will always remove the segments, because there no need to keep both.

**Comment by TehPlayer14** [comment]
Great idea

**Comment by mifi** [comment]
Will implement this when I have time. Should be easy

**Comment by kkeonline** [comment]
Thanks for your great free software, I'm waiting for this feature too.
and it would be great if the add segment button (c+) move to center button group. (and may be change c+ to only + sign in green button is already make sense)

**Comment by mifi** [comment]
I have implemented this, will be included in the next version. created a new issue for your other suggestion @kkeonline #150
