### ISSUE TITLE
The .appx installer cannot install LosslessCut because of unverified publisher certificate.

### ISSUE THREAD

**Issue by Hasselshoff** [mifi/lossless-cut#1270]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with a different kind of file to confirm that the problem is related to just this file.
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut and **Known issues / Troubleshooting**
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Steps to reproduce

Open the "LosslessCut-win-x64.appx" installer file.

### Expected behavior

Running the "LosslessCut-win-x64.appx" installer file should open an installer, where the program can be installed.

### Actual behavior

![image](https://user-images.githubusercontent.com/69090157/184587934-a8dfb0ec-af0e-4d84-bf85-895e77d126bb.png)

This error appears in the installer. The "Install" button is greyed out.

The following error message is provided:

> This app package’s publisher certificate could not be verified. Contact your system administrator or the app developer to obtain a new app package with verified certificates. The root certificate and all immediate certificates of the signature in the app package must be verified (0x800B010A)

### Provide an error report

N/A

### Share log

N/A

**Comment by Hasselshoff** [comment]
I can provide my specific .appx installer file if necessary, but the same error occurred with 3 downloads so I doubt me providing a file will be helpful.

**Comment by mifi** [comment]
> * [x]  Read all the documentation at https://github.com/mifi/lossless-cut and **Known issues / Troubleshooting**
>         
>       
>   
>       Create an issue with the title Read all the documentation at https://github.com/mifi/lossless-cut and Known issues / Troubleshooting. Press Enter to convert to an issue instantly. Press Option-Enter to open the create new issue form in the current tab. Press Shift-Enter to open the create new issue form.
> *

**Comment by Hasselshoff** [comment]
Derp. I literally read the Troubleshooting section before posted and somehow read that last sentence as "The appx is not signed but will still work." RIP, my first bad look github issue. Sorry for the waste of time!

**Comment by mifi** [comment]
everyone makes mistakes :)
