### ISSUE TITLE
 allow exported clips to be named with the name of the tag

### ISSUE THREAD

**Issue by phoney32** [mifi/lossless-cut#1274]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Hi, can you add a function to allow exported clips to be named with the name of the tag

**Comment by mifi** [comment]
By tag you mean segment tag? If so this is already supported by using `${SEG_TAGS.XX}`

**Comment by phoney32** [comment]
${SEG_TAGS.XX} is not working now ,When I use Chinese to tag each segment, the export format using ${SEG_TAGS.XX} does not display correctly.
![PixPin_2024-06-26_18-56-51](https://github.com/mifi/lossless-cut/assets/92145664/be1d3d31-27fc-467b-83e0-34bb0929e134)
![PixPin_2024-06-26_18-57-03](https://github.com/mifi/lossless-cut/assets/92145664/8b661987-2bd4-4570-ac75-125041caeb0a)

**Comment by mifi** [comment]
Turn off «sanitize filenames»
