### ISSUE TITLE
Select segment from cursor position

### ISSUE THREAD

**Issue by adoenz** [mifi/lossless-cut#1284]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

It would be very useful if there's a way to select the segment in which cursor is currently on the timeline. Preferably also having the option of assigning that functionality to a keyboard short cut.

Use Case: After using "Detect black scenes" I often end up with loads of very small non-black-segments which are too small to select using the mouse on the timeline. I then end up either navigating through the segments using arrow up/down to select the righ segment or having to create new segments (appended) over the existing ones and ignore/delete the created ones.

**Comment by mifi** [comment]
I addded your suggestion to https://github.com/mifi/lossless-cut/issues/254#issuecomment-1279310708 - closing this

**Comment by mifi** [comment]
next version will have a new action `selectSegmentsAtCursor`
