### ISSUE TITLE
¿Could it be possible to add a thumbnail preview?

### ISSUE THREAD

**Issue by Gitubhu** [mifi/lossless-cut#129]
If you have an issue with cutting a particular file, or an unexpected bug or crash, please open developer tools after starting LosslessCut and before doing the failing operation. Then share the output from the javascript console.

If you have an issue cutting a particular file, please also share the file, if possible. Also please try to cut it with the ffmpeg command line directly.

How to open developer tools:
- Windows: <kbd>F12</kbd> or <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>
- Mac: <kbd>Cmd</kbd>+<kbd>Opt</kbd>+<kbd>I</kbd>

**Comment by Gitubhu** [comment]
this is an enhancement not a bug itself

**Comment by mifi** [comment]
I don't understand, can you please elaborate?

**Comment by Gitubhu** [comment]
Sorry for taking so long to answer.
something like this:
![Captura de pantalla (27)](https://user-images.githubusercontent.com/37759562/54298534-3b706a00-45b9-11e9-9a72-a5288458ddd0.png)

**Comment by PartyLich** [comment]
So you're looking for thumbnail images added to the timeline? I suppose in order to give the user an idea of what they're jumping to when using the timeline for navigation?

**Comment by Gitubhu** [comment]
Basically yes

**Comment by mifi** [comment]
This is now implemented.
