### ISSUE TITLE
Merged files are missing the "Media Created Date" or Encoded date.

### ISSUE THREAD

**Issue by DZUCKER** [mifi/lossless-cut#1296]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut and **Known issues / Troubleshooting**
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 11

### Steps to reproduce

After creating a merged file. Right click / Properties / Details ... Media Created Date is missing. Or if using Media Info, the "Encoded Date" is missing under the General tab. 

Solution, I use BulkFileChanger to add the missing date under "Media Files - Date Encoded."

This is a problem because when I import such files into Lightroom, they get tagged as being created in the year 1904.

### Expected behavior

![image](https://user-images.githubusercontent.com/9269149/188309075-cd034286-98ba-4149-b639-8a5e63c8ef34.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/9269149/188309038-e87ea1a0-f65b-4577-836c-a1640baff9a7.png)

**Comment by mifi** [comment]
see #1027
