### ISSUE TITLE
any way to mix in mp4 audio tracks into the final?

### ISSUE THREAD

**Issue by diyjobber** [mifi/lossless-cut#130]
sometimes i record separate desktop and mic commentary audio tracks and i'd really like it if this program knew about the multiple audio tracks and allowed me to change the gain and sum the ones i want in the final mix. any chance of this feature being implemented any time soon? :)

**Comment by mifi** [comment]
There is a function Tools -> Merge files that can merge multiple files. Have you tried that? Note that you can not do any editing on the merged files, only merge them.
As for changing gain, it is a lossy operation and will not be implemented I think

**Comment by Lightningblade** [comment]
I think he means (or atleast thats what i wan't) that if you have a mp4 with multiple audio tracks inside the one file, that you can mix those together to only one track so that most players will play both tracks instead of just the primary.

**Comment by mifi** [comment]
This is not a lossless operation and requires encoding. Will not be prioritized in losslesscut.
