### ISSUE TITLE
LosslessCut 3.46.2 Gets an FFMPEG Error

### ISSUE THREAD

**Issue by dagunny** [mifi/lossless-cut#1304]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut and **Known issues / Troubleshooting**
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Linux

### Steps to reproduce

Install on Fedora 36 Cinnamon Dist.
Double Click on LosslessCut Icon
This error pops up
×
LosslessCut is installation is broken
Command failed with EACCES: /opt/LosslessCut/resources/ffmpeg -hide_banner -f lavfi -i nullsrc=s=256x256:d=1 -f null - spawn /opt/LosslessCut/resources/ffmpeg EACCES

![Screenshot from 2022-09-06 11-31-06](https://user-images.githubusercontent.com/73240474/188677446-0020a219-7c58-4bf1-95ac-7d02acd3bd99.png)

I have a duplicate machine running Fedora 36 and no issues. Both are up to date with Fedora 36 and RPMFusion libs. The failing machine has an NVidia 710 card. The good machine is an Intel video onboard. The failing file seems to be app.asar but it may be calling something else. I have both new and an older version on the failing machine (/opt/oldLosslessCut and /opt/LosslessCut).  The 3.39 version works fine. I have copied the older 3.39 FFMpeg resource files to the new (3.42) to test and the older app.apar works OK but states new update available, even with the 3.42 FFMpeg files.

Cited included text as per problem report
No error occurred.

{
  "state": {
    "filePath": "",
    "externalFilesMeta": {},
    "mainStreams": [],
    "copyStreamIdsByFile": {},
    "cutSegments": [
      {}
    ],
    "mainFileFormatData": {},
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "separate"
  },
  "platform": "linux",
  "version": "3.46.2"
}

### Expected behavior

It would open without an error as it does on other machines I have.

### Actual behavior

![Screenshot from 2022-09-06 11-31-06](https://user-images.githubusercontent.com/73240474/188677689-c6a197ab-ec20-425b-a9b4-ddbc030d2c46.png)

**Comment by dagunny** [comment]
I fixed it. I had to make the /LosslessCut folder chmod -R 775 and it allowed it to run. I tested by running as root in the /opt/LosslessCut folder and it worked with --no-sandbox. From the desktop it got the error as the user so I changed the launcher to sudo /opt/LosslessCut/losslesscut --no-sandbox and it worked so I deduced it was a permission problem. Learn something new every day.

**Comment by mifi** [comment]
oh great. i hope issues like this will be fixed in newer versions of electron #714
