### ISSUE TITLE
Lossless Cut Failure to Open Properly

### ISSUE THREAD

**Issue by CtrlAltDel1** [mifi/lossless-cut#1305]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut and **Known issues / Troubleshooting**
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Linux

### Steps to reproduce

Hello Mifi and thanks for taking the time to check this out.  Using Linux Mint 21, the latest version of the Lossless Cut Appimage/x64 doesn't work properly.  After marking "Allow Executing File As Program" and attempting to open by clicking on icon, only a white screen appears for a few seconds and disappears. 

![Screenshot from 2022-09-07 22-27-34](https://user-images.githubusercontent.com/77008917/189027681-12e474d0-ce8e-452b-987d-799915ce09ee.png)

Opening the file from terminal gives this error:

`CLI arguments { _: [] }
Current version 3.46.2
Newest version 3.46.2
[247788:0907/201336.758320:FATAL:gpu_data_manager_impl_private.cc(1034)] The display compositor is frequently crashing. Goodbye.
Trace/breakpoint trap (core dumped)
`

### Expected behavior

It opens normally.

### Actual behavior

It doesn't function properly.

**Comment by mifi** [comment]
dup #1025
