### ISSUE TITLE
Trim output adding one second to exported video before "out start" position

### ISSUE THREAD

**Issue by 93dogs** [mifi/lossless-cut#131]
Hi - and thanks for the great application.
I'm trying to do a simple trim and export of a small .mp4 - 
regardless of where I set the "out start" point, the exported output is adding one second before that point to the export, even though the video time display display accurately reflects the actual trim point I'm setting...in other words when i set the in trim point display to 00.11.34.813 the exported video begins at 00.11.33.813.
The "out trim point" is reflected accurately.
I'm guessing that video should be able to be trimmed at the precise points that define it...
What am I doing wrong?
Thanks so much.

**Comment by TehPlayer14** [comment]
You must have it set as cut to nearest key frame instead of normal you can change it here 
![obraz](https://user-images.githubusercontent.com/7756773/53191954-7bbd7780-360d-11e9-9abc-683b01eb149e.png)

**Comment by 93dogs** [comment]
Thanks so much

I should have figured that out ;O

maybe mifi adding an explanation of that cut mode button to the "typical workflow" section  of the read me...instead of in the "known issues" would be good.

an excellent, useful app!

**Comment by kenzojungle** [comment]
I have the same issue. When I chose Normal Cut instead of Keyframe Cut (as per provided solution), the out start point is correct but my trim output has audio and video out of sync!

**Comment by mifi** [comment]
Closing this, see explanation in #126
