### ISSUE TITLE
Speed up footage when merging video files, shorter merged time than total time of components

### ISSUE THREAD

**Issue by OriginalUserName2000** [mifi/lossless-cut#1315]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut and **Known issues / Troubleshooting**
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 11

### Steps to reproduce

I have a couple video files, all 30 FPS, all without any audio attached to them, and I select all of them, drag them into lossless cut, and I select to merge them.

### Expected behavior

The merged file should be one large video file consisting of all the content I put in (The clips total about a little over 2 hours)

### Actual behavior

The merged file has some segments sped up drastically and as such is shorter than the sum of the parts I put in. Sometimes it also just lingers on a starting frame of one of the files for a long time. The final product is about an hour and a half, losing 30 minutes.

### Share log

there is no crash, it does successfully complete the operation, its just not the intended product.

**Comment by mifi** [comment]
Try to enable the  "Check compatibility" flag in the merge dialog. It probably shows some differences between the files.

See also #455

closing this due to no response
