### ISSUE TITLE
Add file to save previous settings 

### ISSUE THREAD

**Issue by TehPlayer14** [mifi/lossless-cut#132]
Add simple .INI text file so program remember last options you used like instead of having to changing constantly from default to another option

**Comment by mifi** [comment]
I plan on implementing this when i have time. #72

**Comment by ofersadan85** [comment]
Adding my vote for this, having to set everything up each time isn't that time consuming (not many options) but it is annoying (just a nitpick, the program is wonderful)

**Comment by mifi** [comment]
Closing this. Put an upvote on #149 if you want this implemented
