### ISSUE TITLE
Install in Broken - maybe ffmpeg is missing

### ISSUE THREAD

**Issue by ajl11998800** [mifi/lossless-cut#1321]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut and **Known issues / Troubleshooting**
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Linux

### Steps to reproduce

Hello,

i installed LosslessCut-linux-armv7l.tar.bz2 on an RPI 3B.

when i start ist with ./losslesscut this
![IMG_0691](https://user-images.githubusercontent.com/11679017/191712069-25c1a562-012b-4c54-b8b3-19b6bc6e4c9a.jpg)
pops up.

in the Folder .../resources/ is no ffmpeg in there. Maybe this is the Problem? 

### Expected behavior

How can i fix this?

### Actual behavior

Or did i somethin in the installation wrong?

**Comment by mifi** [comment]
hi. unfortunately the arm package doesn't have ffmpeg arm included so you need to use an external ffmpeg (see Settings).
