### ISSUE TITLE
Error while Exporting File

### ISSUE THREAD

**Issue by ajl11998800** [mifi/lossless-cut#1323]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut and **Known issues / Troubleshooting**
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Linux

### Steps to reproduce

I tried to cut a file as same as i do on ubuntu.
On the RPI i got a problem report.

### Expected behavior

The plan is only to cut the file, nothing to change

### Actual behavior

it dosn´t work on the RPI with Raspbian

### Share log

Error: Command failed with exit code 1: /usr/bin/ffmpeg -hide_banner -i /home/pi/Videos/Staffel 6/Paw.Patrol.S06E05.Welpen retten das Melonen-Festival;06 Welpen retten eine Kuh.mp4 -t 664.78836 -map 0:0 -c:0 copy -map 0:1 -c:1 copy -map_metadata 0 -movflags use_metadata_tags -default_mode infer_no_subs -ignore_unknown -f mp4 -y /home/pi/Videos/Paw.Patrol.S06E05.Welpen retten das Melonen-Festival;06 Welpen retten eine Kuh-00.00.00.000-00.11.04.788.mp4
Unrecognized option 'default_mode'.
Error splitting the argument list: Option not found
    at makeError (/home/pi/Install/LosslessCut-linux-armv7l/resources/app.asar/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/pi/Install/LosslessCut-linux-armv7l/resources/app.asar/node_modules/execa/index.js:118:26)
    at async file:///home/pi/Install/LosslessCut-linux-armv7l/resources/app.asar/build/static/js/main.f18f3ad4.js:2:307402
    at async file:///home/pi/Install/LosslessCut-linux-armv7l/resources/app.asar/build/static/js/main.f18f3ad4.js:2:308170
    at async file:///home/pi/Install/LosslessCut-linux-armv7l/resources/app.asar/build/static/js/main.f18f3ad4.js:2:2382031

{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "filePath": "/home/pi/Videos/Staffel 6/Paw.Patrol.S06E05.Welpen retten das Melonen-Festival;06 Welpen retten eine Kuh.mp4",
    "fileFormat": "mp4",
    "externalFilesMeta": {},
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_time_base": "1001/48000",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 720,
        "height": 404,
        "coded_width": 720,
        "coded_height": 416,
        "has_b_frames": 2,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "180:101",
        "pix_fmt": "yuv420p",
        "level": 42,
        "chroma_location": "left",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "24000/1001",
        "avg_frame_rate": "24000/1001",
        "time_base": "1/24000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 32053021,
        "duration": "1335.542542",
        "bit_rate": "440552",
        "bits_per_raw_sample": "8",
        "nb_frames": "32021",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "VideoHandler"
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_time_base": "1/48000",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/48000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 64138320,
        "duration": "1336.215000",
        "bit_rate": "91186",
        "max_bit_rate": "91186",
        "nb_frames": "62638",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "SoundHandler"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "/home/pi/Videos/Staffel 6/Paw.Patrol.S06E05.Welpen retten das Melonen-Festival;06 Welpen retten eine Kuh.mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {
        "end": 664.788355
      }
    ],
    "mainFileFormatData": {
      "filename": "/home/pi/Videos/Staffel 6/Paw.Patrol.S06E05.Welpen retten das Melonen-Festival;06 Welpen retten eine Kuh.mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "1336.258000",
      "size": "89954798",
      "bit_rate": "538547",
      "probe_score": 100,
      "tags": {
        "major_brand": "isom",
        "minor_version": "512",
        "compatible_brands": "isomiso2avc1mp41",
        "encoder": "Lavf58.30.100"
      }
    },
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "separate"
  },
  "platform": "linux",
  "version": "3.46.2"
}

**Comment by mifi** [comment]
I think you’re running an old version of ffmpeg

**Comment by ajl11998800** [comment]
`ffmpeg version 4.1.9-0+deb10u1+rpt1 Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 8 (Raspbian 8.3.0-6+rpi1)
configuration: --prefix=/usr --extra-version=0+deb10u1+rpt1 --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --libdir=/usr/lib/arm-linux-gnueabihf --cpu=arm1176jzf-s --arch=arm
libavutil      56. 22.100 / 56. 22.100
libavcodec     58. 35.100 / 58. 35.100
libavformat    58. 20.100 / 58. 20.100
libavdevice    58.  5.100 / 58.  5.100
libavfilter     7. 40.101 /  7. 40.101
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  3.100 /  5.  3.100
libswresample   3.  3.100 /  3.  3.100
libpostproc    55.  3.100 / 55.  3.100
`
This ist the version i can install - sudo apt-get install ffmpeg.

Did you testing losslesscut on a rpi32bit? 
I tried many to bekome the newest ffmpeg, but nothing will work for me.

**Comment by mifi** [comment]
see https://ffmpeg.org/download.html
