### ISSUE TITLE
Save which segments are selected/unselected in .llc file

### ISSUE THREAD

**Issue by shodanx2** [mifi/lossless-cut#1329]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut to see if the feature already exists
- [x] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

The first step in my process is to place many cut points in the right places. 
Then I unselect the bad segments.
Unfortunately, when I re-open losslesscut, it forgets which segments were selected/unselected.
I will try to use labels to work around this, however, saving the selected status would be a great improvement to streamline the cutting room process !

thanks for your great work !

**Comment by mifi** [comment]
I think this has been requested by someone before so I'll keep this as a useful feature request.

**Comment by mifi** [comment]
i put this in #371 - closing this issue

**Comment by mifi** [comment]
next version will have this
