### ISSUE TITLE
no video(black screen) with gopro mp4 4K 50fps

### ISSUE THREAD

**Issue by cricri33** [mifi/lossless-cut#133]
hi, no video shown on the screen with a 50fps video. 
thanks for the issue your soft is very usefull !

C:\Program Files (x86)\LosslessCut-win32-x64\resources\app.asar\renderer.js:880 Version 2.1.0
C:\Program Files (x86)\LosslessCut-win32-x64\resources\app.asar\renderer.js:303 Load {filePath: "C:\Partage\20190227 Barbade Gopro\GX010923.MP4", html5FriendlyPath: undefined}
C:\Program Files (x86)\LosslessCut-win32-x64\resources\app.asar\ffmpeg.js:213 getFormat C:\Partage\20190227 Barbade Gopro\GX010923.MP4
C:\Program Files (x86)\LosslessCut-win32-x64\resources\app.asar\ffmpeg.js:218 formats mov,mp4,m4a,3gp,3g2,mj2
C:\Program Files (x86)\LosslessCut-win32-x64\resources\app.asar\ffmpeg.js:224 fileType detected format {}

**Comment by mifi** [comment]
Hi. Is the codec H264? This is not yet supported natively. See #88

**Comment by sm0kie420** [comment]
Hi I am loving your program, but is there any way to watch HEVC/265 files?  You say natively.  So is there a way to manually add the codec or something, or a plugin?  Thank you!  Also a way to delete the segments automatically after merger would be nice too.

**Comment by killaz47** [comment]
> Hi. Is the codec H265? This is not yet supported natively. See #88
hevc support for chronium
https://github.com/henrypp/chromium/blob/master/hevc_support_new.md

**Comment by mifi** [comment]
There is a way to cut h265 by converting to html5 friendly codec first. See main readme. Closing this because can continue discussion in #88
