### ISSUE TITLE
If LossLess Cut is not running in the background opened video does not show up in it 

### ISSUE THREAD

**Issue by avatar-lavventura** [mifi/lossless-cut#1330]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut and **Known issues / Troubleshooting**
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

MacOS 12

### Steps to reproduce

I am using LosslessCut Version 3.46.2 (3.46.2).

Right click on the video and do `Open With >` select `LossLess Cut`.

If the `LossLess Cut` does not running in the background the selected video does not show up on it, I see the DROP FILE(S) view.

When I re-do the same operation again it shows up in the `LossLess Cut`.

### Expected behavior

Should video open in LossLess Cut right away even it does not run in the background, it was like that on previous version.

### Actual behavior

Following screen shows up:

<img width="783" alt="image" src="https://user-images.githubusercontent.com/18537398/192758940-eb8fa702-2414-44d2-8fd6-0e9745eb17b3.png">

**Comment by mifi** [comment]
Hi. I think this is the same issue that I already fixed in the commit https://github.com/mifi/lossless-cut/commit/6724a8b82ef432322f6aa8c7f82da87609febc0e

However I have not yet released a new version with that fix - coming soon!
