### ISSUE TITLE
SRT to cut ?

### ISSUE THREAD

**Issue by Michaelwhite34** [mifi/lossless-cut#1332]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

This maybe useful for people who want to generate dataset for TTS.

**Comment by Michaelwhite34** [comment]
Or create a system to add points to timeline and choice to snap to them.This way it may be less laggy (video usually contains thousands of srt lines)

**Comment by mifi** [comment]
can you elaborate what you mean by "SRT to cut"?

**Comment by Michaelwhite34** [comment]
> can you elaborate what you mean by "SRT to cut"?

For example the srt file 
                                      00:01:00-00:02:00
                                      00:03:00-00:04:00
Then lossless cut creates 2 clips in timeline  
                                      00:01:00-00:02:00
                                      00:03:00-00:04:00

**Comment by mifi** [comment]
Ah, so you want to import an SRT file so that the titles in the SRT become segments with names?

**Comment by Michaelwhite34** [comment]
> Ah, so you want to import an SRT file so that the titles in the SRT become segments with names?

Yeah, but It seems that lossless cut slows quite a bit from 100 segments.

**Comment by mifi** [comment]
I'm collecting all import/export format requests in one issue #1340 to keep issue count down - closing this
