### ISSUE TITLE
Split audio files by silent parts

### ISSUE THREAD

**Issue by mifi** [mifi/lossless-cut#1334]
### Discussed in https://github.com/mifi/lossless-cut/discussions/1333

<div type='discussions-op-text'>

<sup>Originally posted by **Marek-Moehling** October  5, 2022</sup>
Namely mp4...</div>

Conceptually similar to #623

**Comment by mifi** [comment]
this will be avail in the next version

<img width="506" alt="Screenshot 2022-12-28 at 23 52 01" src="https://user-images.githubusercontent.com/402547/209838600-ab5213b2-dc07-41bd-b552-59cdb8c1e593.png">

**Comment by CodeOptimist** [comment]
I gave this a shot but couldn't export; something I'm doing wrong?

![image](https://user-images.githubusercontent.com/52485/209946151-735fdadc-9e15-4d20-836c-db438773525e.png)
![image](https://user-images.githubusercontent.com/52485/209946969-f3eca4d5-825a-4c74-86be-29249b6fff30.png)

**Comment by mifi** [comment]
@CodeOptimist not sure why you are getting overlapping segments. Maybe something wrong with ffmpeg's `silencedetect` filter. Not sure why these segments would be overlapping.

Or could it be due to rounding error happening here? https://github.com/mifi/lossless-cut/commit/60bf1a5c5f9cf0985a770a1db9cca64834a0e452#diff-ee2bd8e80992a2bf1f38f4feeaddc6dbbd67b721e7067d73e0bf1f2491de2db2R600

Do you have a file that reproduces the problem or could you do some more experimenting to see which segments are overlapping and what does the output from ffmpeg look like?

I will implement a "combine overlapping segments" function from the menu that can be used to remedy this.

**Comment by CodeOptimist** [comment]
Your menu function works. 😉 Thank you!
I will definitely send you a file if I reproduce it in one that isn't absurdly large. I also realize I could poke around at this myself and probably figure it out, but you know how it is, on a side-project of a side-project of a side-project 😅, about to overflow the stack. When I come across a small-ish test file, or if I poke at the code myself, I'll update you.

**Comment by mifi** [comment]
ok, i'll close this but can reopen if we have some reproduceable case

**Comment by AhmedThahir** [comment]
I really appreciate you guys implementing this. There's another open-source python package called auto-editor, which implements silent cutting using a Python CLI.

However, it does not support lossless cutting. There is a mode to export the cuts as a json, and I would like help with implementing lossless cutting.

Can you help with this issue: https://github.com/WyattBlue/auto-editor/issues/400
