### ISSUE TITLE
Export each track as individual files *except*

### ISSUE THREAD

**Issue by Linnshet** [mifi/lossless-cut#1335]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

![image](https://user-images.githubusercontent.com/52015410/194759496-e7e0a085-f0c1-4f08-a637-c7aed7bccc6c.png)
The "Export each track as individual files" should consider user-disabled tracks. I'm trying to export audio streams into separate tracks to circumvent a bug in my editor, but I either have to export them all as one file, or wait forever for LLC to export my video track first.

**Comment by mifi** [comment]
thanks, have now implemented this
