### ISSUE TITLE
When I export the split files of a file in 4:3 AR, the aspect ratio have changed to 16:9

### ISSUE THREAD

**Issue by naoj77** [mifi/lossless-cut#1336]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Hi, and first of all, thanks for this amazing app!!!

When I export the split files of a file in 4:3 AR, the aspect ratio have changed to 16:9

I'm trying in a windows 10 computer

thanks

**Comment by mifi** [comment]
This seems like a Problem with a particular file. please [provide the requested info](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

**Comment by mifi** [comment]
closing due to no response
