### ISSUE TITLE
A way to merge all selected audio tracks

### ISSUE THREAD

**Issue by Libror** [mifi/lossless-cut#1337]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Would be an amazing way for me to merge the game audio and voice audio track from my nvidia clips into one audio track!

**Comment by mifi** [comment]
you want to mix multiple tracks into one? see https://github.com/mifi/lossless-cut#troubleshooting--faq

**Comment by Libror** [comment]
Oh I understand! Thanks for the answer! I am hoping for a feature packed future!
