### ISSUE TITLE
Subtitles not retained when merging

### ISSUE THREAD

**Issue by tarmacalastair** [mifi/lossless-cut#134]
Hi,

I'm trying to cut bits of TV programmes at the start and end of my recordings made with Mythtv and also strip out adverts in the middle. My files are in ts format (UK broadcast TV).

Using the same file both times:

1. A single cut to remove bits at the beginning and end - works brilliantly, keeping my video, audio and subtitle tracks.
2. Splitting the files into several sections and then using losslesscut to merge them - the resulting file appears fine but unfortunately the subtitle track is missing completely. There are several intermediate files produced for the individual sections. These contain the susbtitles but they are lost when trying to merge to reconstruct the entire TV programme.

Many thanks for your help.

Output from Developer Tools:

Merging files Object to /home/family/Downloads/Endeavour - S4 E1.ts-cut-merged-1551873921101.ts
/home/family/LosslessCut-linux-x64/resources/app.asar/ffmpeg.js:157 ffmpeg -f concat -safe 0 -protocol_whitelist file,pipe -i - -c copy -map_metadata 0 -y /home/family/Downloads/Endeavour - S4 E1.ts-cut-merged-1551873921101.ts
/home/family/LosslessCut-linux-x64/resources/app.asar/ffmpeg.js:162 file '/home/family/Downloads/Endeavour - S4 E1.ts-00.03.27.401-00.18.30.925.ts'
file '/home/family/Downloads/Endeavour - S4 E1.ts-00.22.47.635-00.35.40.739.ts'
file '/home/family/Downloads/Endeavour - S4 E1.ts-00.39.59.164-00.53.40.552.ts'
file '/home/family/Downloads/Endeavour - S4 E1.ts-00.57.58.262-01.09.13.451.ts'
file '/home/family/Downloads/Endeavour - S4 E1.ts-01.13.29.591-01.26.15.608.ts'
file '/home/family/Downloads/Endeavour - S4 E1.ts-01.30.31.480-01.43.22.457.ts'
file '/home/family/Downloads/Endeavour - S4 E1.ts-01.47.39.589-01.58.52.611.ts'
/home/family/LosslessCut-linux-x64/resources/app.asar/ffmpeg.js:170

**Comment by tarmacalastair** [comment]
Just looking through the log file and noticed that for the creation of the intermediate files these options are included:
_-acodec copy -vcodec copy -scodec copy -map 0_

However, in the final command for merging the cut files together these options are missing.
I have tried using ffmpeg manually, following https://trac.ffmpeg.org/wiki/Concatenate and added my 2 filenames to a list file (_joinfiles.txt_). I then manually issued:

1. ffmpeg -f concat -safe 0 -i /home/family/joinfiles.txt -c copy joined.ts (instructions from above wiki)
2. ffmpeg -f concat -safe 0 -i /home/family/joinfiles.txt -map 0 -c copy joined.ts (adding **-map 0**)

Using line 1 above, I got a file like with the merging from your program, ie video and audio are great but subtitles are missing.
Using line 2 above, the resulting merged file is even better and includes the subtitles!

I wonder if you could amend the program to include this option when you have a spare moment please? It would be a great help to those of us with really bad hearing.
Many thanks

**Comment by mifi** [comment]
Hi. I'm thinking that when cutting and merging files, doesn't that make the subtitles useless? because subtitles have start/end times, right? and when cutting out portions of the video, these times will not longer be correct, am i right?

**Comment by tarmacalastair** [comment]
Hi,
Thanks for having a look at this, much appreciated. You've built a great piece of software.

I'm not an expert on video files at all but in UK broadcast TV, I believe that the subtitles are transmitted as a stream in the same way as the video and audio streams. So, when you toggle the subtitles on, they appear to be embedded in the picture. This is different to a video where you can also download a SRT subtitle file which contains a timestamp alongside each line of text. With SRT files I've noticed that I often have to use a +/- offset in e.g. Kodi to get the subtitles correct whereas with a video with a subtitle stream this does not happen.
Also, in the test I did above, where I ran the second command, the output video did combine perfectly with the subtitles working correctly.
I'm sorry that I don't have the programming skills to try and make and test a change for you but if you would like me to test any code then please let me know.
Thanks.

**Comment by mifi** [comment]
Ok I see. I don't know how these embedded subtitles work, but I agree that it makes sense to include all streams (-map 0) when merging, however I don't know if it has any implications, possibly causing issues for some files

**Comment by tarmacalastair** [comment]
Thanks. I hope you find this is something that you could implement. Please note that the intermediate files do contain the subtitles (also if you just trim the start and end of the file then it does contain subtitles). It's only when you try to merge the files into one that the subtitles are lost.
Cheers.

**Comment by tarmacalastair** [comment]
Hi again. Any more news on this? I'd love to be able to trim down my recorded TV programmes but as someone who relies so much on subtitles I have found no easy way to do this without losing the subtitles.
As you can see from the above tests, ffmpeg can be made to include the DVB subtitle stream but it just needs an extra option to be added to lossless-cut.
Hoping you can help, many thanks.

**Comment by wapsi** [comment]
@tarmacalastair I fixed this by adding -map 0 parameter in ffmpeg concat command in src/ffmpeg.js. Then DVB subtitles retained in final / merged output file.

I created a pull request into master branch: https://github.com/mifi/lossless-cut/pull/227

**Comment by wapsi** [comment]
> Hi. I'm thinking that when cutting and merging files, doesn't that make the subtitles useless? because subtitles have start/end times, right? and when cutting out portions of the video, these times will not longer be correct, am i right?

DVB subtitles are completely separate stream in .ts/.mkv file (typically they are transparent bitmap files which are displayed over the video stream) and FFmpeg handles then just fine. I tested with couple of HD DVB recordings and by adding the -map 0 parameter in concat command: subtitles were handled correctly, even if I had multiple cuts and final merged file: subtitle timing etc. are 100% working in the final file.

**Comment by tarmacalastair** [comment]
Hi @wapsi ,
Sorry it's taken me so long to read this but thanks so much for fixing!

I'm quite new to github but managed to get it working by following the instructions at https://github.com/mifi/lossless-cut#development-building--running, but replacing the 

> git clone https://github.com/mifi/lossless-cut.git line 

with

> git clone https://github.com/wapsi/lossless-cut.git

I was then able to run it (on Ubuntu 18.04, (16.04 too old)) and the resulting file was great, with my DVB subtitles intact.

Brilliant! Thank you for your help.

Is it easy to build an Appimage myself or do I just need to wait for @mifi to incorporate this change when he has time?

All the best...

**Comment by mifi** [comment]
I have added -map 0 now. Only if all streams is selected in the UI before merging.

**Comment by tarmacalastair** [comment]
Thank you, much appreciated
