### ISSUE TITLE
Error "Failed to open file. Unexpected end of JSON input" on Windows with filenames containing blanks (??) or under some other weird condition

### ISSUE THREAD

**Issue by JD777777777** [mifi/lossless-cut#1342]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut and **Known issues / Troubleshooting**
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

Load file containing blanks in filename on Windows 10.

EDIT: 
So far, this seems to happen only the first time you use the app and open a nonconforming filename.
It happened while opening a video file using a new app version for the first time.
After I changed the file name to something simple, everything worked.
Then I changed it back to the original and opening it still worked?!?!?
Weird.

### Expected behavior

File opens.

### Actual behavior

Error Message:
"Failed to open file
Unexpected end of JSON input"

### Share log

main.ff7aecec.js:2 loadMedia O:\I AM SOME FILENAME WITH BLANKS.mp4 undefined undefined
main.ff7aecec.js:2 state reset
main.ff7aecec.js:2 ffprobe -of json -show_chapters -show_format -show_entries stream -i 'O:\I AM SOME FILENAME WITH BLANKS' -hide_banner
main.ff7aecec.js:2 userOpenFiles SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at zb (main.ff7aecec.js:2)
    at async file:/C:/Program%20Files/Lossless%20Cut/resources/app.asar/build/static/js/main.ff7aecec.js:2
    at async file:/C:/Program%20Files/Lossless%20Cut/resources/app.asar/build/static/js/main.ff7aecec.js:2
    at async file:/C:/Program%20Files/Lossless%20Cut/resources/app.asar/build/static/js/main.ff7aecec.js:2
(anonymous) @ main.ff7aecec.js:2
main.ff7aecec.js:2 handleError Failed to open file SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at zb (main.ff7aecec.js:2)
    at async file:/C:/Program%20Files/Lossless%20Cut/resources/app.asar/build/static/js/main.ff7aecec.js:2
    at async file:/C:/Program%20Files/Lossless%20Cut/resources/app.asar/build/static/js/main.ff7aecec.js:2
    at async file:/C:/Program%20Files/Lossless%20Cut/resources/app.asar/build/static/js/main.ff7aecec.js:2
M_ @ main.ff7aecec.js:2

**Comment by mifi** [comment]
Maybe your file had some special whitespace or invisible characters like newline `\n`, carriage return `\r`, tab `	 `, non breaking space `  ` or a myriad of other whitespace chars: https://en.wikipedia.org/wiki/Whitespace_character#Unicode

 maybe you can try to reproduce the problem with one of those. I will try also to reproduce on macos.

> Please use "..." instead of '...' for quoting filenames on Windows, otherwise sh*t happens.

There is no quoting at all, because losslesscut doesn't use a shell, it executes the command directly with its arguments with [child_process.spawn](https://nodejs.org/api/child_process.html#child_processspawncommand-args-options)

**Comment by JD777777777** [comment]
I tried using all characters from the first table in the video filename (well, those that Windows let me use, ASCII 9 to 13 seem generally forbidden), but couldn't reproduce the behavior from yesterday.

It seems some other quirk of Windows produced the faulty behavior.

What got me to suspect the blanks was the output of ffprobe when trying your debug output literally, i.e. with the single quotes, and the fact that the problem disappeared after renaming the file to something short and simple.

Since everything seems to be OK now, I think this should be closed.

My only suggestion would be to somehow forward the 'ffprobe' error message for further debugging just in case anything like this ever comes up again.
(If this is even possible when using the "child_process.spawn" method -- I am not at all familiar with Node.js or the inner workings of ffprobe.)
