### ISSUE TITLE
Split segment in n segments to for example respect twitter 140 seconds limit

### ISSUE THREAD

**Issue by Azureit** [mifi/lossless-cut#1344]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

I will like to open a mp4 video with lossless-cut and set the video start and end, and the resulting segment be split in n segments to respect for example the twitter 140 seconds limit.

**Comment by mifi** [comment]
can't you use the "create fixed duration segments" functionality for this?
