### ISSUE TITLE
A queue for mass exporting of different projects

### ISSUE THREAD

**Issue by Tasos500** [mifi/lossless-cut#1345]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

It would be very handy to have the option of adding projects ready to export into a queue, in order to make multiple projects in a single session, without having to wait for each one to finish before working on the next one, and export them all at the same time, similar to how Adobe Media Encoder works.

This should also similarly allow the ability to rearrange or delete export-ready projects in the queue at any point, and show progress both in total, and per project, while exporting, e.g. "1 of 10, 54.30%"

For ease of use, the "Add to queue" button could appear from behind the Export button when opening the Export menu, so that any changes to the export settings will be applied on a per project basis.

**Comment by KenhCuaDaoLeMinh** [comment]
Agree with you. The app should have something like a "export queue" instead of press export for every single file to save time and effort.

**Comment by mifi** [comment]
> This should also similarly allow the ability to rearrange or delete export-ready projects in the queue at any point

I believe this is already implemented (we already have an editable batch list)

> For ease of use, the "Add to queue" button could appear from behind the Export button when opening the Export menu, so that any changes to the export settings will be applied on a per project basis.

I think this would make it a much harder feature to implement. I think the first version should just have a function to export all files in the batch list using current settings (without showing the export dialog)

I will close this and add your suggestion to #89
