### ISSUE TITLE
merge problem

### ISSUE THREAD

**Issue by CHDKBL** [mifi/lossless-cut#1346]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut and **Known issues / Troubleshooting**
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

When I merge two videos with the same encoding, p2 can be merged in front of p1, but p1 cannot be merged in front of p2, and strange audio appears at their connection. this p1 and p2 come from the losslesscut spilt by different videos.

### Expected behavior

two video merge together

### Actual behavior

Cannot be merge

**Comment by mifi** [comment]
do you see any warning if you check compatibility of the files in the merge dialog?
