### ISSUE TITLE
Multiple simulatenous audio track playback?

### ISSUE THREAD

**Issue by ghost** [mifi/lossless-cut#135]
This is more of a suggestion than an issue however would it be possible to make the program playback multiple audio tracks simultaneously? Say for example if I am cutting a game play video with one track for game sound and one for microphone sound I would be able to hear both at the same time and know where to cut.

Thanks for making this program.

**Comment by mifi** [comment]
I'm not sure but I don't think that is possible with the html5 video player. needs some more research

**Comment by mifi** [comment]
closing in favor of #256
