### ISSUE TITLE
Hello! Can you provide a function to trim the video in the top, bottom...

### ISSUE THREAD

**Issue by zhouxinghong** [mifi/lossless-cut#1350]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Hello! Can you provide a function to trim the video in the top, bottom, left and right 4 directions, because in many cases it is necessary to trim off the excess parts of the video in the top, bottom, left and right 4 directions. I don't seem to have this feature at the moment. This is available in many paid video editing software.

您好！您能不能提供一個對視頻上下左右4個方向修剪視頻的功能，因為在很多時候需要修剪掉視頻上下左右4個方向多余的部分。。。目前好像沒有這個功能。這在很多付費的視頻編輯軟件中都有提供。。。

**Comment by mifi** [comment]
Please read the FAQ: https://github.com/mifi/lossless-cut/blob/master/issues.md#faq
