### ISSUE TITLE
Remember compatibility option for joining files

### ISSUE THREAD

**Issue by rieje** [mifi/lossless-cut#1354]
- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

I use the merging/concatenating feature a lot and a simple feature request would be to remember whether the compatibility option was checked and re-use this option instead of checking the box to do a check when this joining window pops up every time. If previous checked, check for comparability immediately. I would prefer checking compatibility as default (not sure how sensible this is for other people's cases), but remembering the option fulfills all usecases.

**Comment by snakecase** [comment]
I would like to add that this feature could actually be a bug of not saving merge options settings between sessions. For example, the settings below get reset on program exit though it looks like they are supposed to be kept between runs.

![LosslessCut_2022-12-10_19-44-22](https://user-images.githubusercontent.com/4579891/206861056-4d293c39-589e-4778-bcf8-7c53a7294bd9.jpg)

**Comment by mifi** [comment]
I agree this makes sense to remember, just haven't had time to implement yet

**Comment by mifi** [comment]
I added this to #371 - closing this issue
