### ISSUE TITLE
Hotkey binding for renaming currently selected segment

### ISSUE THREAD

**Issue by Wiethoofd** [mifi/lossless-cut#1355]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

From some looking through the shift+/ hotkey menu there does not seem to be a keybind for the action to rename a segment without manually clicking the 🏷️icon below your list of segments.

Adding an option to bind it and potentially setting it to a default (F2) could optimize workflow for creating and naming segments.

**Comment by mifi** [comment]
Use the enter key. maybe it should have been configurable too

**Comment by mifi** [comment]
actually it **is** configurable:

<img width="508" alt="Screenshot 2023-01-06 at 23 35 57" src="https://user-images.githubusercontent.com/402547/211044930-36d11472-4167-4a44-9cf7-2ff94c61ce5a.png">
