### ISSUE TITLE
Cut files unable to open with Sony Vegas

### ISSUE THREAD

**Issue by Tonyjvc** [mifi/lossless-cut#136]
Hi,

I have been trimming some videos with this amazing program but when I try to open the trimmed videos with Sony Vegas to edit them, Sony Vegas detect these videos as corrupted.

Could you please advise any solution for this issue?

Thank you in advance.

**Comment by tazzydemon** [comment]
My guess, since I cannot open my gopro cuts in a windows viewer and yet they work in VLC and Magix is to use the suggestion here: https://github.com/mifi/lossless-cut/issues/121#issuecomment-460084786
And toggle the button kc to nc

Ironic since Vegas is owned by Magix. But I was using fastcut.

**Comment by mifi** [comment]
still an issue?

**Comment by mifi** [comment]
closing due to lack of response
