### ISSUE TITLE
flatpak version doesn't show all user folders

### ISSUE THREAD

**Issue by RafaelLinux** [mifi/lossless-cut#1362]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Linux

### Steps to reproduce

Install losslesscut from Discover (Plasma apps store) as flatpak version.

### Expected behavior

To show ALL non hidden folders from user

### Actual behavior

Only some user folders are showed (this doesn't happen with AppImage version)

![imagen](https://user-images.githubusercontent.com/13048959/200548738-451e1e12-f776-415a-ba29-9aafece26295.png)

**Comment by mifi** [comment]
Maybe some permissions are needed. Anyways flatpak version of losslesscut is not being maintained by me, please file an issue here instead: https://github.com/flathub/no.mifi.losslesscut/
see also #218
