### ISSUE TITLE
Integrate pngquant when exporting to PNG

### ISSUE THREAD

**Issue by eduardomozart** [mifi/lossless-cut#1365]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

It would be great if image captured from video could be optimized by pngquant after being exported. JPEG makes the captured image loose quality, and PNG files are so big, so compressing them using pngquant would make a file with a great size and quality.

**Comment by mifi** [comment]
next version will now allow setting a custom jpeg quality parameter. as for png, maybe we can use https://github.com/psych0der/pngquantjs

**Comment by Freso** [comment]
I personally use PNG to save/export lossless screenshots, but [`pngquant`](https://github.com/kornelski/pngquant) is specifically for lossy compression of PNGs. It may be “invisibly” lossy, but it’s lossy none‐the‐less. [`optipng`](https://optipng.sourceforge.net/) (or the [`oxipng`](https://lib.rs/crates/oxipng) fork) seems like a better option to interface with… but I usually just run `optipng` myself.

If you decide to incorporate `pngquant` please make it clear that using that will result in a lossy screenshot.

**Comment by mifi** [comment]
TBH now that we can adjust jpeg quality in losslesscut, I'm not sure what's the advantage of pngquant lossy png vs jpeg with 100% or so quality

**Comment by eduardomozart** [comment]
JPEG has a larger file size than PNG relative to it's quality. Lossless Cut doesn't seem to optimize the PNG it produces and they have a higher size than they could without loosing visible quality. Using optipng would allow better quality screenshots with lower file size and pratically no noticeable quality loss.

**Comment by mifi** [comment]
I've added the suggestion here: #1908
