### ISSUE TITLE
System language doesn't being automatically detected when running macOS

### ISSUE THREAD

**Issue by eduardomozart** [mifi/lossless-cut#1366]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

MacOS 12

### Steps to reproduce

Installing the program through Brew.

### Expected behavior

The program should open in "português do Brasil" (my OS language) when the language autodetection is set.

### Actual behavior

Instead, it's opening in English.

**Comment by mifi** [comment]
Language detection is intentionally disabled because I don't know the quality of the different languages, so better to default to english.
