### ISSUE TITLE
Player freezes

### ISSUE THREAD

**Issue by pdopchev** [mifi/lossless-cut#137]
Hi guys,

Started to use the program and love it since it is so fast and doesn't do any encoding to the file, but after I did a few videos, it stopped working. Cannot play the file any more or set Mark In/Out! If I press "E" it export the whole file...

This is not h.256 as it was recorder with a Sony A7iii

This is from the console:
{filePath: "/Users/Petar/Movies/C0017.MP4", html5FriendlyPath: undefined}
filePath:"/Users/Petar/Movies/C0017.MP4"
html5FriendlyPath:undefined
__proto__:Object

**Comment by mifi** [comment]
Maybe u can share a file that encounters this problem. Restarting the application helps,right?

**Comment by pdopchev** [comment]
It’s working great now, don’t have the issue any more!

Petar
