### ISSUE TITLE
When Merging and Cutting MP4 files Subtitles get lost.

### ISSUE THREAD

**Issue by McEilif** [mifi/lossless-cut#1371]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

I wrote you a detailed email on mifi@ya####.no with 21 Screendumps included.

I have never been logged in here in Github before, so I have no idea if this will be public or an internal message... Please check Email and comment on that, post it if you like. Thanks!

### Expected behavior

Cutted MP4 merged with other Cutted MP4 should still show subtitle track1 (Geodata from DJI-Drone)
![dump01-original_mp4_sbt1(engelsk)](https://user-images.githubusercontent.com/118133964/201542502-56b78a0e-7294-4116-b944-da09133565be.jpg)

### Actual behavior

Cutting 3 Streams unfortunately isn't possible to Merge in one session as before. So first hat to merge 3 streams - Subtitles still works, but merged file has renamed Subtitle Name and added another Track with Chapter Names.

When I now CUT and "Export/Merge" Subtitles are lost. See screendumps
![dump16_subtitletrack2](https://user-images.githubusercontent.com/118133964/201542400-759b780a-b255-45f6-8431-65e1104f349d.jpg)
![dump15-2subtitletracks](https://user-images.githubusercontent.com/118133964/201542424-b7bf827d-a3a7-4d35-9757-586a22c8055f.jpg)
![2 - Tracknumber and Lenght changed for Subtitles](https://user-images.githubusercontent.com/118133964/201542478-dc522145-f7d1-4c72-83e6-77cf0393d2cd.png)

### Share log

It doesn't crash, but changes the Subtitle Tracks. Can it have something to do with a missing option in the Track-List?
![dump12-Tracktype-Subtitle-missing](https://user-images.githubusercontent.com/118133964/201542542-c4cfdce5-7df5-40d3-9a93-8a5c1b5ca360.jpg)

But again - I emailed you Mikael - there are 21 Screendumps I made Stepwise... Love your program - Oh btw: I had this problem from first time I used LossLessCut - it is not just the latest Version!

**Comment by mifi** [comment]
i don't remember, was this resolved?

**Comment by jtognazzi** [comment]
I have similar issue with subtitle.
After cuting an MP4 file, the resulting MP4 still has subtitle track metadata, but the text does not appear on the video (VLC, gnome video player)

If I try to extract just the subtitle track to a file I have an error:
```
Failed to extract track Error: Command failed with exit code 1: /snap/losslesscut/118/resources/ffmpeg -hide_banner -i /Downloads/my video.mp4 -map 0:4 -c copy -f matroska -y /Downloads/my video-stream-4-subtitle-mov_text.mks
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Downloads/my video.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42isomiso2iso5dashavc1dby1mp41
  Duration: 01:40:08.02, start: 0.000000, bitrate: 5317 kb/s
  Stream #0:0[0x1](fra): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 4456 kb/s, 50 fps, 50 tbr, 1k tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](fra): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 126 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](fra): Audio: eac3 (ec-3 / 0x332D6365), 48000 Hz, 5.1(side), fltp, 256 kb/s
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
    Side data:
      audio service type: main
  Stream #0:3[0x4](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 126 kb/s
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
  Stream #0:4[0x5](fra): Subtitle: mov_text (tx3g / 0x67337874), 0 kb/s (default)
    Metadata:
      handler_name    : SubtitleHandler
[matroska @ 0x7422840] Subtitle codec 94213 is not supported.
Could not write header for output file #0 (incorrect codec parameters ?): Function not implemented
Error initializing output stream 0:0 -- 
```

Is there a bug with the subtitle export, or am I missing something ?
I'll try to make proper report if I find the time.

**Comment by mifi** [comment]
@jtognazzi your issue is unrelated to this issue, but I have now fixed your issue, thanks!
