### ISSUE TITLE
Video/Audio randomly freezes when LosslessCut running in background and a game is running in foreground

### ISSUE THREAD

**Issue by SignpostMarv** [mifi/lossless-cut#1373]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 11

### Steps to reproduce

1) Load up LosslessCut on secondary monitor
2) Load up UnrealEngine 4-based game on primary monitor
3) Set LosslessCut away playing
4) Go play game

### Expected behavior

no interruption in playback of video file

### Actual behavior

video playback / audio playback randomly freezes

**Comment by SignpostMarv** [comment]
Issue appears to be resolved somewhat by using `--disable-gpu`, but as this is a different issue to #781, I thought it prudent to post the issue in case there was something that could be done with electron to make it play nice.

In retrospect, same issue also appears to be observed in Twitch Studio, but isn't apparent in OBS so guessing this is electron-specific.

**Comment by SignpostMarv** [comment]
@mifi problem was caused by the hardware-accelerated gpu scheduler, enabled by default in windows 11, available on some versions of windows 10 (disabled by default).

hoping there's something in electron/chromium to say "don't deprioritise" ?

**Comment by SignpostMarv** [comment]
@mifi p.s. I suppose you could technically close this as no fix needed, but on the off-chance there's something one can do at the electron level.... 🤷‍♂️

**Comment by mifi** [comment]
seems like a bug in windows or electron yea. not sure what i can do about it, so let's close. new electron version of llc coming soon
