### ISSUE TITLE
Split Time not Accurate ( it is -2 Seconds on all clips ? )

### ISSUE THREAD

**Issue by salehawal** [mifi/lossless-cut#1374]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Linux

### Steps to reproduce

split a video to more than on part

### Expected behavior

to split the video in the given start/finish time for each part "exactly"

### Actual behavior

it split the video starting from (-2) second from marked starting point for each part

**Comment by mifi** [comment]
> * [x]  Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
> *
