### ISSUE TITLE
Aout SONY XAVC HS 4K is not supported

### ISSUE THREAD

**Issue by hcllmsx** [mifi/lossless-cut#1375]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 11

### Steps to reproduce

![Snipaste_2022-11-22_21-52-46](https://user-images.githubusercontent.com/63240764/203351489-db74cd38-1fa3-47a0-bb04-e3609b024029.png)

[The test video is here](https://drive.google.com/file/d/11yaeBDqAVMCM9bxGsPUCh3GYObi0EH07/view)

Hello, this is the SLOG3 video I shot with SONY camera. The XAVC HS 4K file format is selected. 
Although the display is not supported, I tested that it can be trimmed. 
However, when I import the cropped video to DaVinci Resolve, the first four or five frames are black. 
When I import to Adobe Premiere Pro, there is no problem. 
Therefore, I don't know whether the black screen is caused by LosslessCut or DaVinci Resolve. 
In addition, LosslessCut reminded me that this video file is not supported, and there is also a problem. Can this be fixed? 
thank you!

### Expected behavior

The first 4 or 5 frames of the cut video are black after being imported to DaVinci Resolve.

### Actual behavior

In fact, it can be cut, so it is not supported without prompting. It just has some problems after cutting.

**Comment by mifi** [comment]
Hi
Thanks for sharing the file. You can try to set "Shift timestamps (avoid_negative_ts)" to `auto`. For me that caused the black frames in the beginning to disappear

**Comment by hcllmsx** [comment]
Thank you. I just tried. There are no black frames.

**Comment by mifi** [comment]
great. in the next versios you will not get "file not natively supported" error for hevc anymore

**Comment by hcllmsx** [comment]
By the way, the video taken by my camera is in MP4 format, such as the video file I sent to you. Why are MP4 files displayed in MOV format after they are placed in LosslessCut? After cutting the MP4 file, the MOV file is generated. Has this problem been fixed? Sorry, my English is not very good. I wonder if I have made it clear, So I cut a picture.
![QQ截图20221123170831](https://user-images.githubusercontent.com/63240764/203508708-a6c53d28-7053-4b84-9c57-2d8619c73048.png)

**Comment by mifi** [comment]
for some files ffmpeg is unable to export as mp4 and must use MOV. XAVC is one of those

**Comment by hcllmsx** [comment]
All right, thank you

**Comment by hcllmsx** [comment]
Hello, now the updated version does not have any error prompts, very good. However, I found that after importing the video (SONY XAVC HS 4K), it cannot be previewed. Is this a new bug?

https://user-images.githubusercontent.com/63240764/204128440-982db97a-d353-4ae6-8130-c007db33b4a1.mp4

**Comment by mifi** [comment]
Hi. this is probably related to this issue: #88
Can you try what I suggested here and report back? https://github.com/mifi/lossless-cut/issues/88#issuecomment-1368188991
