### ISSUE TITLE
Detect existing html5ified

### ISSUE THREAD

**Issue by hugoideler** [mifi/lossless-cut#138]
Thanks for this very nice tool!

It would be nice if LosslessCut would detect and load an existing '-html5ified.mp4' file that has been generated in a previous run. For example, when having multiple H.265 files and you switch between files and decide to create a cut at a later moment.

**Comment by mifi** [comment]
Yea, that would be nice, I'll look into it when I have some time

**Comment by janosh** [comment]
Could there be a setting for disabling writing those `*-html5ified-dummy.mp4` files automatically? I don't use them and they clutter my working directories.

**Comment by anonimuos** [comment]
Yes please I would like to request this too. What is the purpose of html5ified-dummy files? I would like to not have them generated automatically.

**Comment by mifi** [comment]
Unfortunately they are needed to play back certain formats/codecs. They could be written to a temp directory also, but we never know how much space the user has there, so that's why I'm writing them to the output directory.

**Comment by janosh** [comment]
I see. Thanks for explaining!
