### ISSUE TITLE
Always getting "Unable to move file to trash"

### ISSUE THREAD

**Issue by mikeyaworski** [mifi/lossless-cut#1381]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

Using the [beta version of the app](https://github.com/mifi/lossless-cut/releases/tag/v3.48.2), I get the "Unable to move file to trash. Do you want to permanently delete it?" every time I try to delete any file (using the D shortcut)

Here is a screenshot of the file info, though it might not be that helpful. Its encoding is H264

![image](https://user-images.githubusercontent.com/10966214/203700967-3360530e-5365-4dbe-a73e-d0515bc28605.png)

### Expected behavior

File should be deleted

### Actual behavior

I get the "Unable to move file to trash. Do you want to permanently delete it?" every time I try to delete any file (using the D shortcut)

![image](https://user-images.githubusercontent.com/10966214/203700398-e14c8603-4c08-401d-9fc5-82452591b455.png)

This is the console after making that attempt

![image](https://user-images.githubusercontent.com/10966214/203700721-c31d0cf2-dc29-4b04-9c3d-c9091cdb3bef.png)

It happens regardless of which checkboxes I select in the delete prompt.
![image](https://user-images.githubusercontent.com/10966214/203701222-26e88f19-2081-4710-a147-d52ddff5200e.png)

If I leave them all checked, then I'll still get the "Unable to move file to trash modal", but after pressing "Permanently delete", it gives me the following error:

> Error: ENOENT: no such file or directory, unlink <my-file-name>-proj.llc'

However, if I only select the "Trash original source" file, then it will permanently delete the source file as expect.

In general, the app is unable to move the source file to my recycle bin, and only sometimes permanently delete the source file.

### Share log

![image](https://user-images.githubusercontent.com/10966214/203701090-eed36308-fafb-45ba-9aaa-fc5f1c7d1b9d.png)

**Comment by mifi** [comment]
thx for reporting. seems like a bug in electron: https://github.com/electron/electron/issues/29598

I will probably work around it by not calling trash function from renderer process

**Comment by Rubens10010** [comment]
What is the state of this? I noticed also that deleting a file will effectively remove the file from the system, it's not even at the recycle bin where it should be.

**Comment by mifi** [comment]
it's a bug in the newest beta version. you should be able to downgrade to the previous version and it should go away. if not, then please provide more information about the issue
