### ISSUE TITLE
could you make a flatpak for lossless-cut?

### ISSUE THREAD

**Issue by ghost** [mifi/lossless-cut#139]
Hi, I really appreciate your work , is a very good application

could you make a flatpak for lossless-cut?
in this way, users can install the application in any linux distribution

please.
thank you.
http://flatpak.org/

**Comment by mifi** [comment]
Gonna have to look into
http://docs.flatpak.org/en/latest/electron.html

**Comment by mifi** [comment]
Closing in favor of #218
