### ISSUE TITLE
Please add the files into a folder for next releases - Windows

### ISSUE THREAD

**Issue by spirulin** [mifi/lossless-cut#1390]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

A small request. Please put the files in a folder. When directly unzipping it creates a mess with files all over the place.

**Comment by mifi** [comment]
you mean the files in the 7z package? can't 7z extract all files to a folder? tbh I'm not sure how to do this because `electron-builder` handles all the building and packaging and I can't find an option for it

**Comment by spirulin** [comment]
Sure it can but for someone getting it for the first time and directly extracting it creates a mess, especially if you have other files in the extracted place. Not a big deal but would be nice if possible to fix this. :)
