### ISSUE TITLE
Losslet cut can't export MP4 from a Sony (A6300) camera

### ISSUE THREAD

**Issue by echidna555** [mifi/lossless-cut#1391]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

the program won't export Mp4 from a MP4 file from a Sony camera. "Unable to export this file"
exporting as mkv and mov is working BUT Adobe Premiere can't read the mkv and with mov only the audio is imported in Premiere.

Note that with the MP4s from my Nikon camera and Mavic everything works fine.

### Expected behavior

export as MP4 which can be used in Premiere.

### Actual behavior

see above

### Share log

Error: Command failed with exit code 1: C:\Users\MANFRE~1\AppData\Local\Temp\1c2S8Wbw7TFP9wOtcHcsranqDZJ\resources\node_modules\ffmpeg-static\ffmpeg.exe -hide_banner -i H:\Videos Hauptordner H\2022-06+07 Slowenien-Kroatien-Österreich\Manfred Sony Videos\C0008-M.MP4 -t 13.28659 -avoid_negative_ts make_zero -c copy -map 0:0 -map 0:1 -map_metadata 0 -movflags use_metadata_tags -ignore_unknown -f mp4 -y H:\Videos Hauptordner H\2022-06+07 Slowenien-Kroatien-Österreich\Manfred Sony Videos\C0008-M-00.00.00.000-00.00.13.286.MP4 [mov,mp4,m4a,3gp,3g2,mj2 @ 00000276bcb2ab40] st: 0 edit list: 1 Missing key frame while searching for timestamp: 1000 [mov,mp4,m4a,3gp,3g2,mj2 @ 00000276bcb2ab40] st: 0 edit list 1 Cannot find an index entry before timestamp: 1000. Guessed Channel Layout for Input Stream #0.1 : stereo Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'H:\Videos Hauptordner H\2022-06+07 Slowenien-Kroatien-Österreich\Manfred Sony Videos\C0008-M.MP4': Metadata: major_brand : XAVC minor_version : 16785407 compatible_brands: XAVCmp42iso2 creation_time : 2022-06-11T09:47:52.000000Z Duration: 00:00:23.52, start: 0.000000, bitrate: 53979 kb/s Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709/bt709/iec61966-2-4), 3840x2160 [SAR 1:1 DAR 16:9], 52235 kb/s, 25 fps, 25 tbr, 25k tbn, 50 tbc (default) Metadata: creation_time : 2022-06-11T09:47:52.000000Z handler_name : Video Media Handler encoder : AVC Coding Stream #0:1(und): Audio: pcm_s16be (twos / 0x736F7774), 48000 Hz, stereo, s16, 1536 kb/s (default) Metadata: creation_time : 2022-06-11T09:47:52.000000Z handler_name : Sound Media Handler Stream #0:2(und): Data: none (rtmd / 0x646D7472), 204 kb/s (default) Metadata: creation_time : 2022-06-11T09:47:52.000000Z handler_name : Timed Metadata Media Handler timecode : 06:07:22:06 [mp4 @ 00000276bcb4c680] Could not find tag for codec pcm_s16be in stream #1, codec not currently supported in container Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument Stream mapping: Stream #0:0 -> #0:0 (copy) Stream #0:1 -> #0:1 (copy) Last message repeated 1 times at makeError (C:\Users\MANFRE~1\AppData\Local\Temp\1c2S8Wbw7TFP9wOtcHcsranqDZJ\resources\app.asar\node_modules\execa\lib\error.js:58:11) at handlePromise (C:\Users\MANFRE~1\AppData\Local\Temp\1c2S8Wbw7TFP9wOtcHcsranqDZJ\resources\app.asar\node_modules\execa\index.js:114:26) at async _ (file:///C:/Users/MANFRE~1/AppData/Local/Temp/1c2S8Wbw7TFP9wOtcHcsranqDZJ/resources/app.asar/build/static/js/main.437c0011.chunk.js:1:4342) at async L (file:///C:/Users/MANFRE~1/AppData/Local/Temp/1c2S8Wbw7TFP9wOtcHcsranqDZJ/resources/app.asar/build/static/js/main.437c0011.chunk.js:1:5024) at async file:///C:/Users/MANFRE~1/AppData/Local/Temp/1c2S8Wbw7TFP9wOtcHcsranqDZJ/resources/app.asar/build/static/js/main.437c0011.chunk.js:1:127583 { "err": { "killed": false, "failed": true, "timedOut": false, "isCanceled": false, "exitCode": 1 }, "state": { "filePath": "H:\\Videos Hauptordner H\\2022-06+07 Slowenien-Kroatien-Österreich\\Manfred Sony Videos\\C0008-M.MP4", "fileFormat": "mp4", "externalStreamFiles": [], "mainStreams": [ { "index": 0, "codec_name": "h264", "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10", "profile": "High", "codec_type": "video", "codec_time_base": "1/50", "codec_tag_string": "avc1", "codec_tag": "0x31637661", "width": 3840, "height": 2160, "coded_width": 3840, "coded_height": 2160, "has_b_frames": 1, "sample_aspect_ratio": "1:1", "display_aspect_ratio": "16:9", "pix_fmt": "yuv420p", "level": 51, "color_range": "tv", "color_space": "bt709", "color_transfer": "iec61966-2-4", "color_primaries": "bt709", "chroma_location": "left", "refs": 1, "is_avc": "true", "nal_length_size": "4", "r_frame_rate": "25/1", "avg_frame_rate": "25/1", "time_base": "1/25000", "start_pts": 2000, "start_time": "0.080000", "duration_ts": 588000, "duration": "23.520000", "bit_rate": "52235271", "bits_per_raw_sample": "8", "nb_frames": "588", "disposition": { "default": 1, "dub": 0, "original": 0, "comment": 0, "lyrics": 0, "karaoke": 0, "forced": 0, "hearing_impaired": 0, "visual_impaired": 0, "clean_effects": 0, "attached_pic": 0, "timed_thumbnails": 0 }, "tags": { "creation_time": "2022-06-11T09:47:52.000000Z", "language": "und", "handler_name": "Video Media Handler", "encoder": "AVC Coding" } }, { "index": 1, "codec_name": "pcm_s16be", "codec_long_name": "PCM signed 16-bit big-endian", "codec_type": "audio", "codec_time_base": "1/48000", "codec_tag_string": "twos", "codec_tag": "0x736f7774", "sample_fmt": "s16", "sample_rate": "48000", "channels": 2, "bits_per_sample": 16, "r_frame_rate": "0/0", "avg_frame_rate": "0/0", "time_base": "1/48000", "start_pts": 0, "start_time": "0.000000", "duration_ts": 1128960, "duration": "23.520000", "bit_rate": "1536000", "nb_frames": "1128960", "disposition": { "default": 1, "dub": 0, "original": 0, "comment": 0, "lyrics": 0, "karaoke": 0, "forced": 0, "hearing_impaired": 0, "visual_impaired": 0, "clean_effects": 0, "attached_pic": 0, "timed_thumbnails": 0 }, "tags": { "creation_time": "2022-06-11T09:47:52.000000Z", "language": "und", "handler_name": "Sound Media Handler" } }, { "index": 2, "codec_type": "data", "codec_tag_string": "rtmd", "codec_tag": "0x646d7472", "r_frame_rate": "0/0", "avg_frame_rate": "0/0", "time_base": "1/25000", "start_pts": 0, "start_time": "0.000000", "duration_ts": 588000, "duration": "23.520000", "bit_rate": "204800", "nb_frames": "588", "disposition": { "default": 1, "dub": 0, "original": 0, "comment": 0, "lyrics": 0, "karaoke": 0, "forced": 0, "hearing_impaired": 0, "visual_impaired": 0, "clean_effects": 0, "attached_pic": 0, "timed_thumbnails": 0 }, "tags": { "creation_time": "2022-06-11T09:47:52.000000Z", "language": "und", "handler_name": "Timed Metadata Media Handler", "timecode": "06:07:22:06" } } ], "copyStreamIdsByFile": { "H:\\Videos Hauptordner H\\2022-06+07 Slowenien-Kroatien-Österreich\\Manfred Sony Videos\\C0008-M.MP4": { "0": true, "1": true, "2": false } }, "cutSegments": [ { "end": 13.286586 } ], "fileFormatData": { "filename": "H:\\Videos Hauptordner H\\2022-06+07 Slowenien-Kroatien-Österreich\\Manfred Sony Videos\\C0008-M.MP4", "nb_streams": 3, "nb_programs": 0, "format_name": "mov,mp4,m4a,3gp,3g2,mj2", "format_long_name": "QuickTime / MOV", "start_time": "0.000000", "duration": "23.520000", "size": "158699566", "bit_rate": "53979444", "probe_score": 100, "tags": { "major_brand": "XAVC", "minor_version": "16785407", "compatible_brands": "XAVCmp42iso2", "creation_time": "2022-06-11T09:47:52.000000Z" } }, "rotation": 360, "shortestFlag": false } }

**Comment by mifi** [comment]
unfortunately ffmpeg cannot export `pcm_s16be` audio in mp4 so it must use MOV.
Does audio also not work in other players like quicktime or vlc?
If you can share a short file that reproduces the problem I can look into it. you can email it to me if private

**Comment by echidna555** [comment]
Hi,the exported MOV files play ok on Mediaplayers. The problem is that Adobe Premiere cannot handle them. When I import to Premiere there is only the Audiotrack, no Videotrackkind regardsManfred

    Am Montag, 12. Dezember 2022 um 11:59:54 MEZ hat Mikael Finstad ***@***.***> Folgendes geschrieben:  
 
 


unfortunately ffmpeg cannot export pcm_s16be audio in mp4 so it must use MOV.
Does audio also not work in other players like quicktime or vlc?
If you can share a short file that reproduces the problem I can look into it. you can email it to me if private

**Comment by mifi** [comment]
I think it could be related to #1075

see also f3738fab9185eb0993fa95ca95a3d9fb0b0d0dd9

what happens if you select MOV output from losslesscut but you rename the file name to .mp4?

**Comment by echidna555** [comment]
Hi, thank you ! MOV renaming to MP4 worked. I had tried that renaming for mkv but that did not work and I did not try the same MOV.

    Am Mittwoch, 14. Dezember 2022 um 06:18:21 MEZ hat Mikael Finstad ***@***.***> Folgendes geschrieben:  
 
 


I think it could be related to #1075

see also f3738fa

what happens if you select MOV output from losslesscut but you rename the exported file name to .mp4?

**Comment by mifi** [comment]
i think this can be closed
