### ISSUE TITLE
Error while cuting an MKV video file in Windows 10

### ISSUE THREAD

**Issue by sergiopjf** [mifi/lossless-cut#14]
E:\Downloads\LosslessCut-win32-x64\resources\app.asar\ffmpeg.js:18 Error: spawn undefined ENOENT
    at notFoundError (E:\Downloads\LosslessCut-win32-x64\resources\app.asar\node_modules\cross-spawn\lib\enoent.js:11)
    at verifyENOENT (E:\Downloads\LosslessCut-win32-x64\resources\app.asar\node_modules\cross-spawn\lib\enoent.js:46)
    at ChildProcess.cp.emit (E:\Downloads\LosslessCut-win32-x64\resources\app.asar\node_modules\cross-spawn\lib\enoent.js:33)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215)

**Comment by mifi** [comment]
Can you open developer tools using CTRL+SHIFT+I or F12 before triggering the error, and include the output from the Console?
Alternatively, is it possible for you to share a sample video that's not working?

**Comment by sergiopjf** [comment]
I can not share the video, it's too big (200MB).

Output from the Console:

C:\Users\srmp\Desktop\LosslessCut-win32-x64\resources\app.asar\renderer.js:81 Load C:\Users\srmp\Desktop\video.mkv
C:\Users\srmp\Desktop\LosslessCut-win32-x64\resources\app.asar\ffmpeg.js:61 getFormat C:\Users\srmp\Desktop\video.mkv
C:\Users\srmp\Desktop\LosslessCut-win32-x64\resources\app.asar\ffmpeg.js:69 formats matroska,webm
C:\Users\srmp\Desktop\LosslessCut-win32-x64\resources\app.asar\ffmpeg.js:45 Cutting from 107.085721 to 149.593918
C:\Users\srmp\Desktop\LosslessCut-win32-x64\resources\app.asar\ffmpeg.js:49 ffmpeg -i C:\Users\srmp\Desktop\video.mkv -y -vcodec copy -acodec copy -ss 107.085721 -t 42.508196999999996 -f webm C:\Users\srmp\Desktop\video.mkv-00.01.47.085-00.02.29.593..mkv
C:\Users\srmp\Desktop\LosslessCut-win32-x64\resources\app.asar\ffmpeg.js:18 Error: spawn undefined ENOENT
    at notFoundError (C:\Users\srmp\Desktop\LosslessCut-win32-x64\resources\app.asar\node_modules\cross-spawn\lib\enoent.…:11)
    at verifyENOENT (C:\Users\srmp\Desktop\LosslessCut-win32-x64\resources\app.asar\node_modules\cross-spawn\lib\enoent.…:46)
    at ChildProcess.cp.emit (C:\Users\srmp\Desktop\LosslessCut-win32-x64\resources\app.asar\node_modules\cross-spawn\lib\enoent.…:33)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215)

**Comment by mifi** [comment]
Can you open CMD and run:
C:\Users\srmp\Desktop\LosslessCut-win32-x64\resources\app.asar.unpacked\ffmpeg.exe -i C:\Users\srmp\Desktop\video.mkv -y -vcodec copy -acodec copy -ss 107.085721 -t 42.508196999999996 -f webm C:\Users\srmp\Desktop\video.mkv-00.01.47.085-00.02.29.593..mkv

...And show the output?

I will add this ffmpeg output to javascript console in a later release 📝
Also I noticed that the extension has two dots "..mkv", I will fix that too in the next release.

**Comment by sergiopjf** [comment]
C:\Users\srmp>C:\Users\srmp\Desktop\LosslessCut-win32-x64\resources\app.asar.unpacked\ffmpeg\ffmpeg.exe -i C:\Users\srmp\Desktop\video.mkv -y -vcodec copy -acodec copy -ss 107.085721 -t 42.508196999999996 -f webm C:\Users\srmp\Desktop\video.mkv-00.01.47.085-00.02.29.593..mkv
ffmpeg version 3.1.5 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.4.0 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-libebur128 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 28.100 / 55. 28.100
  libavcodec     57. 48.101 / 57. 48.101
  libavformat    57. 41.100 / 57. 41.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 47.100 /  6. 47.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
Input #0, matroska,webm, from 'C:\Users\srmp\Desktop\video.mkv':
  Metadata:
    encoder         : libebml v1.3.3 + libmatroska v1.4.4
    creation_time   : 2016-11-07 04:12:43
  Duration: 00:57:18.42, start: 0.000000, bitrate: 783 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(tv, bt709/unknown/unknown), 720x402, SAR 1:1 DAR 120:67, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp (default)
[webm @ 00000000006f7040] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
    Last message repeated 1 times
Output #0, webm, to 'C:\Users\srmp\Desktop\video.mkv-00.01.47.085-00.02.29.593..mkv':
  Metadata:
    encoder         : Lavf57.41.100
    Stream #0:0: Video: h264, yuv420p(tv, bt709/unknown/unknown), 720x402 [SAR 1:1 DAR 120:67], q=2-31, 23.98 fps, 23.98 tbr, 1k tbn, 1k tbc (default)
    Stream #0:1: Audio: aac (LC), 48000 Hz, stereo (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[webm @ 00000000006f7040] Only VP8 or VP9 video and Vorbis or Opus audio and WebVTT subtitles are supported for WebM.
av_interleaved_write_frame(): Invalid argument
Error writing trailer of C:\Users\srmp\Desktop\video.mkv-00.01.47.085-00.02.29.593..mkv: Invalid argumentframe=    1 fps=0.0 q=-1.0 Lsize=       0kB time=00:00:01.07 bitrate=   3.1kbits/s speed=  13x
video:35kB audio:14kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

**Comment by mifi** [comment]
Thanks.
I assume you are running the latest version of LosslessCut.
The format of your video has been detected as being WebM (despite the extension being mkv.)

It seems FFMPEG doesn't want to put H264 video with AAC audio into a WebM file. As far as I understand that is outside the spec of the WebM format (which only supports VP8 or VP9 video.)
Where did you get this file? As of now I can only conclude that the file is unsupported.
I guess an option would be to implement the ability to select a custom output format like matroska.

**Comment by sergiopjf** [comment]
Torrent for download of sample video attached.
[video.zip](https://github.com/mifi/lossless-cut/files/604373/video.zip)

**Comment by mifi** [comment]
I have investigated and found out that the library that I'm using to detect file type detects mistakenly detects this file as webm.
https://github.com/sindresorhus/file-type

**Comment by mifi** [comment]
Fixed in 21898711dcdda8d2124c6bd5dbc57bead96616e6 and in 1.3.0
