### ISSUE TITLE
win32-64 downloaded exe file will not install-say missing node.dll

### ISSUE THREAD

**Issue by biggere** [mifi/lossless-cut#140]
Won't install because says missing node.dll.  However, the file node.dll is listed as being present.  Apparently something is the program is not searching for the file.

I am just an intermediate Windows user--not a programmer, although I did do a little Fortran programming 56 years ago.

Just trying to find a simple free video cutter that will allow multiple cuts in the SAME file.  Like "Free Video Editor" but without the watermark.

Your program seems like what I am desiring--if I can just get it installed.

Thanks for your help.

**Comment by Hrxn** [comment]
Not sure...

I've downloaded and extracted this into a new directory:
https://github.com/mifi/lossless-cut/releases/download/v2.1.0/LosslessCut-win32-x64.zip

Seems to work fine here.

**Comment by mifi** [comment]
Could this be anti-virus related?

**Comment by guymanley** [comment]
This happened to me once. It gives this error when the .exe file isn't being opened from the install folder that was extracted in the download. This happened to me when I copied the exe to my desktop instead of making a shortcut of the exe from the install folder.

**Comment by mifi** [comment]
Repopen if this is a problem still
