### ISSUE TITLE
LLC does not handle video files from Lumix S5 properly

### ISSUE THREAD

**Issue by JPA92160** [mifi/lossless-cut#1406]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

try to split a .MOV file, keeping the mov format the generated file seems to be correct but no image is visible (black screen), the audio is OK. The only workaround I've found is to choose .mkv output but unfortunately Matroska files are not really supported by Vegas Pro. 

### Expected behavior

see first paragraph

### Actual behavior

see first paragraph

**Comment by mifi** [comment]
Could you provide more of the requested info? See the «problem with a particular» file template

**Comment by JPA92160** [comment]
Hi mifi, I didn't choose so "problem with a particular file" template because this issue happens whatever the format of the file selected and I can't attach a file because of the size limitation (which by the way doesn't make sense for a video oriented software). Hereunder a link where you can download a sample files :

**Comment by JPA92160** [comment]
grosfi.ch/qGVAZisVeQu](https://www.grosfichiers.com/qGVAZisVeQu)

**Comment by JPA92160** [comment]
Closed by error, sorry

**Comment by mifi** [comment]
Thanks for sharing. Seems like the same problem as #280 - closing this
a workaround for you is to go into Settings and enable the ffmpeg experimental flag. that should fix it

**Comment by JPA92160** [comment]
Thanks a lot it works fine !
