### ISSUE TITLE
automatically cut silence

### ISSUE THREAD

**Issue by markifi** [mifi/lossless-cut#1408]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

to automatically detect when the audio is under a certain level, add 500 milliseconds of padding and mark to cut there. i know it wouldn't be perfect as this only cuts on keyframes, but it would probably still be a valuable addition, especially if you'd still have the option to further manually edit what this function marks to be cut. i don't believe this to be a feature previously considered, but i might be searching wrong. i tried "cut silence", "jumpcut", and some other variations along those lines. (including these for easier search in the future)

there's a bunch of proprietary software for this but apart from carykh's jumpcutter i don't see any open source ones. (carykh's malfunctions with any file above 15 gigabytes, although this might be user error)

**Comment by mifi** [comment]
Isn't this a duplicate of #1334 ?

**Comment by markifi** [comment]
sorry i didn't see that those ones. it kind of is a duplicate, except not split by silence, but removing the silent part entirely. that way you can take the time to write what you want to say, say it, and have the long meandering silence in between two lines automatically thrown out of the footage and have a video that flows normally and not waste the time of the viewer, all with almost zero effort in editing. the commercial programs for this would be timebolt and recut, but those are aimed at people who actually want to re-render their videos. a waste of time and processing power in my opinion, but i digress.

i'll close this now, thanks mifi.

**Comment by mifi** [comment]
Ah yes, I will probably implement it as a «detect silence». Similar to the detect black scenes. That way the silent parts will become segments, and you can cut them out
