### ISSUE TITLE
can't output the files suddenly, it is possible for the same video before

### ISSUE THREAD

**Issue by syayys** [mifi/lossless-cut#1409]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

Error: Command failed with exit code 1: C:\Users\Dell\Downloads\Compressed\losslesscut 3.48.2 (beta!) Latest\resources\ffmpeg.exe -hide_banner -ss 235.63442 -i E:\下载\浮图缘\E03.mp4 -t 47.56602 -avoid_negative_ts make_zero -map 0:0 -c:0 copy -map 0:1 -c:1 copy -map_metadata 0 -movflags +faststart -default_mode infer_no_subs -ignore_unknown -f mp4 -y E:\下载\浮图缘\ E03-2 【曾黎】夜 | 换完衣服回来 发火听汇报 急匆匆离开.mp4
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'E:\下载\浮图缘\E03.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    date            : 2022-12-27T20:34:07.2229262+08:00
    encoder         : Lavf58.32.104
  Duration: 00:46:28.35, start: 0.000000, bitrate: 1820 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x800, 1622 kb/s, 25 fps, 25 tbr, 90k tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 191 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
E:\下载\浮图缘\ E03-2 【曾黎】夜 | 换完衣服回来 发火听汇报 急匆匆离开.mp4: Invalid argument
    at makeError (C:\Users\Dell\Downloads\Compressed\losslesscut 3.48.2 (beta!) Latest\resources\app.asar\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\Dell\Downloads\Compressed\losslesscut 3.48.2 (beta!) Latest\resources\app.asar\node_modules\execa\index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///C:/Users/Dell/Downloads/Compressed/losslesscut%203.48.2%20(beta!)%20Latest/resources/app.asar/build/static/js/main.019d3772.js:2:311242
    at async file:///C:/Users/Dell/Downloads/Compressed/losslesscut%203.48.2%20(beta!)%20Latest/resources/app.asar/build/static/js/main.019d3772.js:2:312108
    at async file:///C:/Users/Dell/Downloads/Compressed/losslesscut%203.48.2%20(beta!)%20Latest/resources/app.asar/build/static/js/main.019d3772.js:2:2353839

{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "filePath": "E:\\下载\\浮图缘\\E03.mp4",
    "fileFormat": "mp4",
    "externalFilesMeta": {},
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 1920,
        "height": 800,
        "coded_width": 1920,
        "coded_height": 800,
        "closed_captions": 0,
        "film_grain": 0,
        "has_b_frames": 2,
        "pix_fmt": "yuv420p",
        "level": 40,
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "field_order": "progressive",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "id": "0x1",
        "r_frame_rate": "25/1",
        "avg_frame_rate": "25/1",
        "time_base": "1/90000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 250945200,
        "duration": "2788.280000",
        "bit_rate": "1622644",
        "bits_per_raw_sample": "8",
        "nb_frames": "69707",
        "extradata_size": 45,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "VideoHandler",
          "vendor_id": "[0][0][0][0]"
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "id": "0x2",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/48000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 133840896,
        "duration": "2788.352000",
        "bit_rate": "191978",
        "nb_frames": "130704",
        "extradata_size": 2,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "SoundHandler",
          "vendor_id": "[0][0][0][0]"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "E:\\下载\\浮图缘\\E03.mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {
        "start": 98.489984,
        "end": 204.535645
      },
      {
        "start": 235.634418,
        "end": 283.200438
      },
      {
        "start": 606.459752,
        "end": 795.294911
      },
      {
        "start": 873.313049,
        "end": 1066.697413
      },
      {
        "start": 1151.291702,
        "end": 1152.914821
      },
      {
        "start": 1284.730172,
        "end": 1472.011758
      },
      {
        "start": 1824.629073,
        "end": 1827.989166
      },
      {
        "start": 2492.771141,
        "end": 2497.50888
      }
    ],
    "mainFileFormatData": {
      "filename": "E:\\下载\\浮图缘\\E03.mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "2788.352000",
      "size": "634588804",
      "bit_rate": "1820684",
      "probe_score": 100,
      "tags": {
        "major_brand": "isom",
        "minor_version": "512",
        "compatible_brands": "isomiso2avc1mp41",
        "date": "2022-12-27T20:34:07.2229262+08:00",
        "encoder": "Lavf58.32.104"
      }
    },
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "separate",
    "outSegTemplate": " ${FILENAME}-${SEG_NUM} ${SEG_LABEL}${EXT}"
  },
  "platform": "win32",
  "version": "3.48.2"
}

### Expected behavior

 output all the pieces

### Actual behavior

can't output all the videos, just output one piece

### Share log

ok

**Comment by mifi** [comment]
Can you try to rename your input and output path to latin characters only and see if it works?

**Comment by syayys** [comment]
> Can you try to rename your input and output path to latin characters only and see if it works?

thanks for your answer, i haven't meet the same mistake before, i tried the past version again, and failed , but this time i can output at most twelve cuts, however i wanted it to output 14 cuts. the process just can work to 66%

**Comment by syayys** [comment]
> Can you try to rename your input and output path to latin characters only and see if it works?

i cancel all the labels of cuts, and it works. however i can output the cuts with labels in the past,sadly

**Comment by syayys** [comment]
> Can you try to rename your input and output path to latin characters only and see if it works?

sorry, i think i found the reason, it doesn't work just because the lable includes " |  "

**Comment by mifi** [comment]
Ok thanks for reporting back. I will improve the code so that it gives a warning if some label has `|` in it.
