### ISSUE TITLE
Disabling Animation

### ISSUE THREAD

**Issue by vuslatx** [mifi/lossless-cut#1410]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Hi.

I hate animations in general. I always disable all windows animations, after install windows and android.

I would be very happy if there was a disable feature for Lossless Cut. Example is below. There is also that case in opening to settings.

https://user-images.githubusercontent.com/65629417/210106845-69e346e9-9ccd-4689-841b-a6c4b21b71fe.mp4

Thanks.

**Comment by mifi** [comment]
I think we need to use something like this: https://www.framer.com/docs/guide-accessibility/
However we are still on an old version of framer motion v1 that does not support this, so need to upgrade to v8 (probbaly a lot of breaking changes)

related: #880

**Comment by mifi** [comment]
now losslesscut will follow the operating system's "reduced motion" preference
