### ISSUE TITLE
batch export all segments from all opened files

### ISSUE THREAD

**Issue by neuronflow** [mifi/lossless-cut#1411]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description
<img width="1536" alt="Screenshot 2023-01-01 at 02 30 37" src="https://user-images.githubusercontent.com/7048826/210158815-70684f68-598d-469e-97da-189a2b46ab86.png">

I have multiple files opened; in each file, I tagged a couple of sequences. Now I want to batch-export everything at once.

If I only do timepoint cutting, the overhead is acceptable as it is only a few seconds per file, but with reencoding, this becomes very painful.

This might be related to this feature request:
https://github.com/mifi/lossless-cut/issues/89

**Comment by mifi** [comment]
Not sure how this is different from #89 "mass export button"

> but with reencoding, this becomes very painful.

What do you mean by re-encoding? Smart cut?

**Comment by neuronflow** [comment]
Yes, smart cut or saving with another codec in general.
