### ISSUE TITLE
Preview screen error

### ISSUE THREAD

**Issue by miku1958** [mifi/lossless-cut#1412]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

1. make a record video with different tools(Mumu enmulator, GeForce Experience)
2. try edit it with LLC

### Expected behavior

preview screen is normal

### Actual behavior

preview screen has error, out put video is normal
![image](https://user-images.githubusercontent.com/24806909/210196040-57361e26-a805-482c-919b-d61dc0e325fb.png)

the preview screen become noraml when I try to output the file
![image](https://user-images.githubusercontent.com/24806909/210196062-db9ec4dc-51bc-4d83-bf7c-041c39eb8f14.png)

**Comment by mifi** [comment]
Hi. Where is the error? can you share a sample file?

**Comment by miku1958** [comment]
Can you see the screenshot? The preview imge should be like this:
<img width="646" alt="image" src="https://user-images.githubusercontent.com/24806909/210250603-0f429218-671d-4739-9a7c-80264ab91910.png">

**Comment by miku1958** [comment]
I am not sure why, I some different video and their preview are all broken.

**Comment by mifi** [comment]
can you provide more info about your file? See questions here https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml

does it work on a different computer? or a different file?

**Comment by miku1958** [comment]
The previews of the different files are broken.

**Comment by raidiuss** [comment]
I'm having this same issue, i open a video with lossless cut and it has that weird flickery dark blue and red glitch in the preview. i had to go all the way back to version 3.44.0 and download the exe just to get a working version.

**Comment by mifi** [comment]
does it happen on a different computer? what's your OS?

**Comment by miku1958** [comment]
I don't have another computer. Windows 10 19045.2486

**Comment by mifi** [comment]
what about other type of file? h264, h265, something else?

**Comment by miku1958** [comment]
I tried h264, h265, h264 with HDR, they all have the same issues.

**Comment by mifi** [comment]
so it only happens with HDR files? what about non-hdr files?

**Comment by mifi** [comment]
oops sorrry i misread. so it happens with all files you drag into losslesscut....

**Comment by miku1958** [comment]
Yes, all files

**Comment by mifi** [comment]
what if you click File -> Convert to supported format -> Fastest: Low playback speed (no audio)
same problem?

**Comment by miku1958** [comment]
let me try with latest beta.

**Comment by miku1958** [comment]
It shows:
File not natively supported. Preview may have no audio or low quality. The final export will however be lossless with audio. You may convert it from the menu for a better preview with audio.

Then the preview become normal.

**Comment by mifi** [comment]
What happens if you open Chrome browser and then drag-drop one of the vidoe files into chrome? same problem?

**Comment by miku1958** [comment]
nothing happen when I drag media file to Chrome.

**Comment by miku1958** [comment]
![image](https://user-images.githubusercontent.com/24806909/212535402-c8609b65-af22-4789-b6bc-9bf7bf16db81.png)
It looks normal

**Comment by mifi** [comment]
very strange. new version of losslesscut coming out soon. hopefully it will resolve the problem..

**Comment by miku1958** [comment]
I try to make a record about how it looks like in lossless-cut, but I found that if I wait long enough, the preview becomes normal afterwards, but at this point the preview lags very badly. 

Then I turn off "Auto convert to supported format" but no help, the preview still error when opening and becomes normal but laggy after wait for a while.

**Comment by mifi** [comment]
Lagging preview is a know problem with «convert to supported format». Hope to improve it in the future

**Comment by HurricAngel** [comment]
I ran into the same issue and it has last for several versions now. I discovered that if you rename/remove libEGL.dll and libGLESv2.dll the preview will go back to normal. Not sure what exactly does those two files do so I made a folder and put them there in case I need them to have losslesscut work properly.

**Comment by puppysnuff** [comment]
> I ran into the same issue and it has lasted for several versions now. I discovered that if you rename/remove libEGL.dll and libGLESv2.dll the preview will go back to normal. Not sure what exactly does those two files do so I made a folder and put them there in case I need them to have losslesscut work properly.

This worked for me as well.

Windows 11 editing an MP4 file
![image](https://github.com/mifi/lossless-cut/assets/48777436/e8e29991-6d31-4fbd-a599-e48e2ad18fe7)
