### ISSUE TITLE
Volume button issue when the file is long and time line is zoomed out  

### ISSUE THREAD

**Issue by xcodelight** [mifi/lossless-cut#1416]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 11

### Steps to reproduce

When the following 3 conditions are true, the volume button issue occurs
1.File is longer
2."Show waveform" button is enabled
3."Zoom" is less (1x or 2x)

Its hard to explain. I have uploaded the video 
https://user-images.githubusercontent.com/120263284/211193671-26fa3a24-c0f1-4638-9e4c-42b479d005b5.mp4

### Expected behavior

Volume control should be working when mouse clicked.

### Actual behavior

Volume control button does not work when mouse clicked.

**Comment by mifi** [comment]
thanks for reporting!
