### ISSUE TITLE
Display Progress in Taskbar

### ISSUE THREAD

**Issue by amibeamer** [mifi/lossless-cut#1417]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Can you add that the Progress is displayed in the Taskbar?
like Shotcut..  :-)

**Comment by mifi** [comment]
that's a great idea. implemented:
<img width="305" alt="Screenshot 2023-01-09 at 12 36 22" src="https://user-images.githubusercontent.com/402547/211241857-a671a061-ea52-498d-8662-8dc95d2c871a.png">
