### ISSUE TITLE
Please ask permission before phoning home

### ISSUE THREAD

**Issue by older-pack** [mifi/lossless-cut#1418]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

When I launched the Linux appimage for the first time it phoned home to these domains:

```
api.github.com
redirector.gvt1.com
losslesscut.mifi.no
```

Would it be possible to ask the user's permission first?

I think the `redirector.gvt1.com` domain might be linked to a spell check dictionary service in Electron.
I guess that service probably isn't used by LosslessCut and could be disabled like it was [here in bitwarden](https://github.com/bitwarden/desktop/issues/1215)

Thanks for LosslessCut. Very cool app.

**Comment by mifi** [comment]
Hi!
These endpoints are used for showing some dynamic content as well as checking for updates. It's definitely possible, but definitely not my highest priority to implement. Can leave this request open though.
See also #457 #1055

**Comment by older-pack** [comment]
Hi,
Thanks for replying.

I know I'm not going to change your mind but here are some thoughts.

I dislike big tech spying on users.
And that's why I love open source software.

I think the 'dynamic content' is an unnecessary taint on an otherwise great app.
I don't belie you're harvesting user data like big tech, but even getting a user's IP address (without permission) is too much data for me.

I've no objection to you hard coding messages about your other apps and services and/or the Ukrainian flag.
I just don't like the 'dynamic' part without asking.

Do your messages really have to be dynamic?
Could you not change them in each new updated version of LosslessCut?

As for updates, it was always traditional to ask the user if they wanted to check for them.

Thanks for listening and being open about it and for leaving the issue open.

Great app.

**Comment by mifi** [comment]
I think a lot of apps these days make some kind of network requests automatically. Heck some even require logging in to a service before using. In an ideal world, yea, all apps would be strictly offline, until the user needs something online. Hopefully in the future, all popular operating systems will automatically start asking dialog popups like `Do you want to allow app XX to access the internet?` once an app tries to make a network request, kind of like how many OS's (like macos) now will not allow apps to access a user's files without the user confirming a popup dialog. Until then, I'm not sure, but I will keep this request in mind. Would a CLI flag to disable all network traffic be a good alternative? It would be the easiest to implement.

**Comment by mifi** [comment]
next version will allow turning off auto updates

**Comment by older-pack** [comment]
> In an ideal world, yea, all apps would be strictly offline, until the user needs something online.

That ideal world was circa 2005... I remember it well. Those were the days. :wink: :grinning:

>  Would a CLI flag to disable all network traffic be a good alternative?

Anything would be better than nothing.
Thanks again.

**Comment by Jookia** [comment]
You can revoke the network permission using Flatseal

**Comment by mifi** [comment]
next version will have a flag `--disable-networking` that will disable update check and other networking. will close this for now then

**Comment by older-pack** [comment]
@Jookia Thanks. Never heard of Flatseal before. Looks very useful.

@mifi Thanks for listening and making the changes.
