### ISSUE TITLE
Cutting a few seconds before the starting cut

### ISSUE THREAD

**Issue by MdsCool** [mifi/lossless-cut#142]
Hey, I'm trying to cut a video but when I put the starting cut and ending cut, yeah that's normal, but when it's exported it has like 5 seconds from before the starting cut. I try to put the starting cut 5 seconds ahead then to see if it'll do it again but no, it just starts from the original 5 seconds before point from before. What's going on here?

**Comment by kenzojungle** [comment]
I think is the answer is here:

https://github.com/mifi/lossless-cut/issues/131

However, when I chose Normal Cut instead of Keyframe Cut then my trim output has audio and video out of sync. Maybe you won't have the same issue.

**Comment by MdsCool** [comment]
> I think is the answer is here:
> 
> #131
> 
> However, when I chose Normal Cut instead of Keyframe Cut then my trim output has audio and video out of sync. Maybe you won't have the same issue.

Even with that other option the same thing happens. Maybe it's because of a setting in OBS or something?

**Comment by mifi** [comment]
Problem is that you cannot cut between keyframes, it's a technical limitation of modern video codecs. So it will choose the nearest keyframe (which ahppens to be 5 sec before your cut point). In the future we could implement a smart cut that re-encodes (lossy) the part between the cutpoint and next keyframe. See #126 
I think I can close this, if I'm wrong please reopen
