### ISSUE TITLE
AppImages require FUSE to run.

### ISSUE THREAD

**Issue by lamyergeier** [mifi/lossless-cut#1421]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Linux

### Steps to reproduce

Downlaod Latest Appimage from Github on Ubuntu 22.10 (wayland)

```
$ ./LosslessCut-linux-x86_64.AppImage 
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
```

### Expected behavior

-

### Actual behavior

-

### Share log

-

**Comment by mifi** [comment]
related? https://github.com/balena-io/etcher/issues/1490

**Comment by lamyergeier** [comment]
Solved by: sudo apt install fuse
