### ISSUE TITLE
Export FLAC audio file as AAC from mp4 video

### ISSUE THREAD

**Issue by MarleVVLL** [mifi/lossless-cut#1426]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Dear beloved developer(s),

it would be an excellent addition if FLAC could be exported to AAC (.mov or .mp4). I currently receive errors when trying to export.

Best,

**Comment by mifi** [comment]
Hi. Unfortunately that is not possible to do without re-encoding. But there are many other tools out there that can re-encode audio
