### ISSUE TITLE
Cut GoPro files together with telemetry

### ISSUE THREAD

**Issue by lukegluke** [mifi/lossless-cut#1428]
Nowdays [gyroflow ](https://github.com/gyroflow/gyroflow) becomes the mainstream tool for video stabilization using gyroscope data. It would be nice if [lossless-cut](https://github.com/mifi/lossless-cut) could cut GoPro video files together with telemetry, by parsing GPMF data. I'm not going deep into it, but it looks there are several open-source solutions/libraries for this format: https://community.gopro.com/s/question/0D53b00008BtEHHCA3/gopro-telemetry-resources-software

**Comment by mifi** [comment]
thanks for your suggestion. I created a super-issue for this kind of stuff: #1438 - closing this
