### ISSUE TITLE
Click-drag seeking stops working if your cursor moves off the bar.

### ISSUE THREAD

**Issue by Delerium** [mifi/lossless-cut#1432]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

click the time bar and drag it to seek position, then move the cursor up or down off of the bar.

### Expected behavior

The previous version would still continue seeking according to the cursors horizontal position and ignored the vertical position, which is what is preferred.  Not sure why this behavior changed, but when you have your eyes on the video, it's easy for the cursor to drift up or down as you seek without realizing it, and it's distracting to have to keep looking back at the bar to adjust the cursor back.

### Actual behavior

Video stops seeking and pauses at the spot the mouse leaves the bar.

**Comment by mifi** [comment]
Ah yes, I hoped that nobody would notice :P
I had to rewrite some code and remove an unmaintained lib react-hammerjs https://github.com/mifi/lossless-cut/commit/123c3a3402f2894a39d308ee3362d93524fe2959

Note sure how to restore the previous behavior but I agree that would be optimal

**Comment by Delerium** [comment]
Always hate it when a library gets abandoned.  Wish you good luck on finding a solution. Thanks for trying though.

**Comment by mifi** [comment]
Did implement a workaround, will be out in the next version

**Comment by Delerium** [comment]
Hey, just got the new version and noticed it was fixed, so I came back to say thanks!  Works great!
