### ISSUE TITLE
Cut at the nearest audio (key-) frame instead of the next one

### ISSUE THREAD

**Issue by DreckSoft** [mifi/lossless-cut#1433]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

I'm using LosslessCut to cut AC3/EAC3 files to sync audio. Those are using 32ms frames at 48k sampling rate. If I cut 0.000-2.568 the closest cut would be 2.560 seconds, so an 8ms difference. LosslessCut however produces a file with 2.592s, leaving a 24ms difference. This adds up over various cuts. So the cuts should be made on the closest keyframe. This will usually result in a +- 0ms result over various cuts. 

As an alternate option to solve this a setting "snap to xx ms" would be helpful. So one can only enter a multiple of xx ms as cut points.

**Comment by mifi** [comment]
Is this keyframe cut or normal cut mode? Not sure how to control this, and not sure how exactly ffmpeg deals with keyframes when seeking in audio. See #1216

**Comment by DreckSoft** [comment]
In Keyframe cut mode. According to the description it should be the nearest key frame but it is always the next.
