### ISSUE TITLE
Program doesn't respect the exact moments I want to cut. It insists on including some seconds before my desired starting point

### ISSUE THREAD

**Issue by Yolakalemowa** [mifi/lossless-cut#1434]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

I tried this with several videos and it refuses to respect my authoritah :)

let's say I ask to cut and export only second 10 to 20, after I export it I find that it starts from second 5 to 20 not from 10. 

I tried to search for a similar issue here but coudln't find so I'm sorry if it is open already plz point me to it.

to reproduce:
I drag drop a video
press the "start segment at current time" on my desired start time, and same with end time (but so far the cases I tried I let it finish till the end I didn't need to cut before the end)
I press export
the video will start earlier than my desired start time.

### Expected behavior

It should respect my specifically assigned start segment time.

### Actual behavior

It moves a few seconds before that.

**Comment by kibbblz** [comment]
I've spoke about this in the past with the dev. Forgot what he said but I think at the moment can't be fixed? I also have this problem and I've just made myself remember whenever I select a frame that it's gonna save the frame before that. The out frame is fine though.

**Comment by mifi** [comment]
please see https://github.com/mifi/lossless-cut/blob/master/issues.md#cutting-times-are-not-accurate
