### ISSUE TITLE
Cutting MOV doesn't work with version 2.10

### ISSUE THREAD

**Issue by cometchaserde** [mifi/lossless-cut#144]
If you have an issue with cutting a particular file, or an unexpected bug or crash, please open developer tools after starting LosslessCut and before doing the failing operation. Then share the output from the javascript console.

If you have an issue cutting a particular file, please also share the file, if possible. Also please try to cut it with the ffmpeg command line directly.

How to open developer tools:
- Windows: <kbd>F12</kbd> or <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>
- Mac: <kbd>Cmd</kbd>+<kbd>Opt</kbd>+<kbd>I</kbd>

**Comment by cometchaserde** [comment]
Cutting MOV doesn't work with version 2.10. the old 2.01 works fine.

I used ffmpeg command line: ffmpeg -i 20190406_132008.MOV -ss 00:00:00  -t 00:00:10 -c copy out.mov
and it works fine.
Errormessage:
Whoops! ffmpeg was unable to cut this video. It may be of an unknown format or codec combination

[-1554826474520.log](https://github.com/mifi/lossless-cut/files/3059996/-1554826474520.log)

System: Debian Stable 64bit
FFMpeg:
ffmpeg version 3.2.12-1~deb9u1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516

**Comment by plncrzy** [comment]
I get the same error with dashcam video files saying, "Whoops! ffmpeg was unable to cut this video. It may be of an unknown format or codec combination". 

For me, I get the same error on 2.10 and 2.00

I attached the log file and here is a link to a sample video file:
https://drive.google.com/drive/folders/10vqrDOJFRhFA8-CS3YXOUx1_ozm4ZqoC?usp=sharing
Let me know if you have trouble downloading the video file.

Potplayer says it is MPEG-4 format with a QuickTime profile. The codec is AVC. 1080P 30fps. YUV color space, PCM audio.

[log 5-5-19 MOV version 2.10.txt](https://github.com/mifi/lossless-cut/files/3146050/log.5-5-19.MOV.version.2.10.txt)

FFmpeg version 4.1 
LosslessCut - win32-x64 v2.10
Windows 10 1809 x64

**Comment by cometchaserde** [comment]
The sample video looks fine and I can play it. Cutting with 2.10 doesn't work. Same error message.



System: Debian Stable 64bit
FFMpeg:
ffmpeg version 3.2.12-1~deb9u1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516

**Comment by mifi** [comment]
Have you tried to toggle "all" to "ps"?

**Comment by mifi** [comment]
It seems that ffmpeg doesn't like to put PCM audio into mp4 files. And somehow it identifies these files as MP4 instead of MOV

**Comment by plncrzy** [comment]
Great thoughts. I agree. I tried toggling "all" to "ps" with no luck. However, toggling on the delete audio button "da" allows it to cut just fine. So, it must not like PCM audio. 

Thanks! For now I have an option if I don't need the audio.

**Comment by cometchaserde** [comment]
Hi,
here is a sample video
https://c.1und1.de/@520261252337899338/rjH06m3lQ2CZlHx5WTUDcA

It works if I set it to "delete audio". Other chances e.g. "all" to "ps" or "kc" to "nc" doesn't work.

**Comment by mifi** [comment]
Thanks for sample. I confirm it's a bug and it seems to be fixed in newest `file-type` version, so I have upgraded that. It will be included in the next version of losslesscut
