### ISSUE TITLE
File name missing from App Window 

### ISSUE THREAD

**Issue by ilaw138** [mifi/lossless-cut#1440]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

MacOS 12

### Steps to reproduce

Just upgrade to ARM64 V 3.49.0 on MacBook Air M1 and the window title no longer includes the name of the file that has been opened it only shows "LosslessCut". Am using Mac OS Ventura 13.2.

On 3.36.0 on a late 2012 Mac Mini on Mojave 10.14.6 it shows the app name and the file name in the format "LosslessCut - <filename>".

Thanks,

Ian Law

### Expected behavior

App Window Title used to show "Lossless Cut - <filename>".

### Actual behavior

App Window just shows "Lossless Cut".

### Share log

No error occurred.

{
  "state": {
    "filePath": "/Users/ianlaw/Movies/n0020-n0029/Source ƒ/Encode_V1129_1080P_29.mp4",
    "fileFormat": "mp4",
    "externalFilesMeta": {},
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "id": "0x1",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/3000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 10440768,
        "duration": "3480.256000",
        "bit_rate": "189374",
        "nb_frames": "163137",
        "extradata_size": 2,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "eng",
          "handler_name": "\fSoundHandler",
          "vendor_id": "[0][0][0][0]"
        }
      },
      {
        "index": 1,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "Constrained Baseline",
        "codec_type": "video",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1080,
        "closed_captions": 0,
        "film_grain": 0,
        "has_b_frames": 0,
        "pix_fmt": "yuv420p",
        "level": 40,
        "chroma_location": "left",
        "field_order": "progressive",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "id": "0x2",
        "r_frame_rate": "25/1",
        "avg_frame_rate": "2175100/87003",
        "time_base": "1/25",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 87003,
        "duration": "3480.120000",
        "bit_rate": "9650402",
        "bits_per_raw_sample": "8",
        "nb_frames": "87004",
        "extradata_size": 41,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "eng",
          "handler_name": "\fVideoHandler",
          "vendor_id": "[0][0][0][0]"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "/Users/ianlaw/Movies/n0020-n0029/Source ƒ/Encode_V1129_1080P_29.mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {
        "start": 53.039355,
        "end": 3447.000415
      }
    ],
    "mainFileFormatData": {
      "filename": "/Users/ianlaw/Movies/n0020-n0029/Source ƒ/Encode_V1129_1080P_29.mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "3480.256000",
      "size": "4283261523",
      "bit_rate": "9845853",
      "probe_score": 100,
      "tags": {
        "major_brand": "isom",
        "minor_version": "512",
        "compatible_brands": "qt  "
      }
    },
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "merge",
    "outSegTemplate": "${FILENAME}-${CUT_FROM}-${CUT_TO}${SEG_SUFFIX}${EXT}"
  },
  "platform": "darwin",
  "version": "3.49.0"
}

**Comment by mifi** [comment]
fixed in 5f8107de98acff4bc77d132b6c145e379f2c3354 see also #1435
