### ISSUE TITLE
Cut and merge this file and the output video is unseekable

### ISSUE THREAD

**Issue by Silver-Fang** [mifi/lossless-cut#1442]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with a different kind of file to confirm that the problem is related to just this file.
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Steps to reproduce

Export+merge:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/33191697/215630304-7393afed-e291-4e80-82b5-8678986a376f.png">
Play the merged video with windows default player.

### Expected behavior

The output video should be playable and seekable.

### Actual behavior

I couldn't seek to a specific time position. And the full time length is wrong. It can play from the start but if I try to seek to the middle position:
<img width="903" alt="image" src="https://user-images.githubusercontent.com/33191697/215631606-b824af95-ee3c-47a4-af9e-24a9d1e89183.png">

### Provide an error report

No error occurred.

{
  "state": {
    "filePath": "C:\\Users\\vhtmf\\Videos\\民@[人人资源网：www.rrzyw.cn]异志.mp4",
    "fileFormat": "mp4",
    "externalFilesMeta": {},
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "hevc",
        "codec_long_name": "H.265 / HEVC (High Efficiency Video Coding)",
        "profile": "Main",
        "codec_type": "video",
        "codec_tag_string": "hev1",
        "codec_tag": "0x31766568",
        "width": 3840,
        "height": 1608,
        "coded_width": 3840,
        "coded_height": 1608,
        "closed_captions": 0,
        "film_grain": 0,
        "has_b_frames": 2,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "160:67",
        "pix_fmt": "yuv420p",
        "level": 150,
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "refs": 1,
        "id": "0x1",
        "r_frame_rate": "24/1",
        "avg_frame_rate": "24/1",
        "time_base": "1/90000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 626940000,
        "duration": "6966.000000",
        "bit_rate": "4362966",
        "nb_frames": "167184",
        "extradata_size": 115,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "VideoHandler",
          "vendor_id": "[0][0][0][0]"
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "44100",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "id": "0x2",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/44100",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 307204096,
        "duration": "6966.079274",
        "bit_rate": "189588",
        "nb_frames": "300004",
        "extradata_size": 2,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "SoundHandler",
          "vendor_id": "[0][0][0][0]"
        }
      },
      {
        "index": 2,
        "codec_name": "png",
        "codec_long_name": "PNG (Portable Network Graphics) image",
        "codec_type": "video",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "width": 1309,
        "height": 334,
        "coded_width": 1309,
        "coded_height": 334,
        "closed_captions": 0,
        "film_grain": 0,
        "has_b_frames": 0,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "1309:334",
        "pix_fmt": "rgba",
        "level": -99,
        "color_range": "pc",
        "refs": 1,
        "id": "0x0",
        "r_frame_rate": "90000/1",
        "avg_frame_rate": "0/0",
        "time_base": "1/90000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 626947200,
        "duration": "6966.080000",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 1,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        }
      }
    ],
    "copyStreamIdsByFile": {
      "C:\\Users\\vhtmf\\Videos\\民@[人人资源网：www.rrzyw.cn]异志.mp4": {
        "0": true,
        "1": true,
        "2": true
      }
    },
    "cutSegments": [
      {
        "start": 50,
        "end": 80
      },
      {
        "start": 150,
        "end": 240
      },
      {
        "start": 1910,
        "end": 2160
      },
      {
        "start": 3620,
        "end": 3720
      },
      {
        "start": 4700,
        "end": 4770
      },
      {
        "start": 5180,
        "end": 5210
      },
      {
        "start": 5290,
        "end": 5470
      },
      {
        "start": 5600,
        "end": 5700
      },
      {
        "start": 5800,
        "end": 5850
      },
      {
        "start": 6000,
        "end": 6050
      },
      {
        "start": 6060,
        "end": 6130
      },
      {
        "start": 6140,
        "end": 6200
      },
      {
        "start": 6220,
        "end": 6450
      },
      {
        "start": 6540,
        "end": 6630
      }
    ],
    "mainFileFormatData": {
      "filename": "C:\\Users\\vhtmf\\Videos\\民@[人人资源网：www.rrzyw.cn]异志.mp4",
      "nb_streams": 3,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "6966.080000",
      "size": "3969838120",
      "bit_rate": "4559049",
      "probe_score": 100,
      "tags": {
        "major_brand": "isom",
        "minor_version": "512",
        "compatible_brands": "isomiso2mp41",
        "encoder": "Lavf58.29.100",
        "comment": "www.mp4ba.cc"
      }
    },
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "merge",
    "outSegTemplate": "${FILENAME}-${CUT_FROM}-${CUT_TO}${SEG_SUFFIX}${EXT}"
  },
  "platform": "win32",
  "version": "3.49.0"
}

### Share the file

https://1drv.ms/u/s!Ao_ojVC-AjiXgaFNWFSL_KMjm0Op4A?e=fkMbpd

**Comment by mifi** [comment]
How did you solve the problem?

**Comment by Silver-Fang** [comment]
> How did you solve the problem?

I have not solved it. I'll open a new issue with a better reproduction.
