### ISSUE TITLE
This video clip does not play properly after merging

### ISSUE THREAD

**Issue by Silver-Fang** [mifi/lossless-cut#1444]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with a different kind of file to confirm that the problem is related to just this file.
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Steps to reproduce

Export+merge:
<img width="606" alt="image" src="https://user-images.githubusercontent.com/33191697/215674083-cd3500f8-5f0e-4c4b-ab6d-36be4358c03d.png">
Play the merged video with the Windows default player.

### Expected behavior

The output video should play normally from beginning to end, and can jump to any time position.

### Actual behavior

Only the first segment is normal. Subsequent segments either don't play properly or can't jump.

### Provide an error report

No error occurred.

{
  "state": {
    "filePath": "D:\\OneDrive - 翁悸会\\共享\\复现\\1分钟.mp4",
    "fileFormat": "mp4",
    "externalFilesMeta": {},
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "hevc",
        "codec_long_name": "H.265 / HEVC (High Efficiency Video Coding)",
        "profile": "Main",
        "codec_type": "video",
        "codec_tag_string": "hev1",
        "codec_tag": "0x31766568",
        "width": 3840,
        "height": 1608,
        "coded_width": 3840,
        "coded_height": 1608,
        "closed_captions": 0,
        "film_grain": 0,
        "has_b_frames": 2,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "160:67",
        "pix_fmt": "yuv420p",
        "level": 150,
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "refs": 1,
        "id": "0x1",
        "r_frame_rate": "24/1",
        "avg_frame_rate": "24/1",
        "time_base": "1/90000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 5407500,
        "duration": "60.083333",
        "bit_rate": "6731963",
        "nb_frames": "1442",
        "extradata_size": 115,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "VideoHandler",
          "vendor_id": "[0][0][0][0]"
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "44100",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "id": "0x2",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/44100",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 2646016,
        "duration": "60.000363",
        "bit_rate": "189639",
        "nb_frames": "2584",
        "extradata_size": 2,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "SoundHandler",
          "vendor_id": "[0][0][0][0]"
        }
      },
      {
        "index": 2,
        "codec_name": "png",
        "codec_long_name": "PNG (Portable Network Graphics) image",
        "codec_type": "video",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "width": 1309,
        "height": 334,
        "coded_width": 1309,
        "coded_height": 334,
        "closed_captions": 0,
        "film_grain": 0,
        "has_b_frames": 0,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "1309:334",
        "pix_fmt": "rgba",
        "level": -99,
        "color_range": "pc",
        "refs": 1,
        "id": "0x0",
        "r_frame_rate": "90000/1",
        "avg_frame_rate": "0/0",
        "time_base": "1/90000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 5415030,
        "duration": "60.167000",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 1,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        }
      }
    ],
    "copyStreamIdsByFile": {
      "D:\\OneDrive - 翁悸会\\共享\\复现\\1分钟.mp4": {
        "0": true,
        "1": true,
        "2": true
      }
    },
    "cutSegments": [
      {
        "end": 10
      },
      {
        "start": 20,
        "end": 30
      },
      {
        "start": 40,
        "end": 50
      }
    ],
    "mainFileFormatData": {
      "filename": "D:\\OneDrive - 翁悸会\\共享\\复现\\1分钟.mp4",
      "nb_streams": 3,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "60.167000",
      "size": "52063648",
      "bit_rate": "6922551",
      "probe_score": 100,
      "tags": {
        "major_brand": "isom",
        "minor_version": "512",
        "compatible_brands": "isomiso2mp41",
        "encoder": "Lavf59.27.100",
        "comment": "www.mp4ba.cc"
      }
    },
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "merge",
    "outSegTemplate": "${FILENAME}-${CUT_FROM}-${CUT_TO}${SEG_SUFFIX}${EXT}"
  },
  "platform": "win32",
  "version": "3.49.0"
}

### Share the file

https://1drv.ms/u/s!Ao_ojVC-AjiXgaUnxn_CjuLh8ijh9A?e=1Le0Vr

**Comment by mifi** [comment]
Hi. thanks for sharing the file. I managed to reproduce the problem. Can you try to set Shift timestamps (avoid_negative_ts) to "auto"?

**Comment by Silver-Fang** [comment]
> Hi. thanks for sharing the file. I managed to reproduce the problem. Can you try to set Shift timestamps (avoid_negative_ts) to "auto"?
> 
> Another thing you can try is to disable the 3rd PNG track

Nice, 【Shift timestamps (avoid_negative_ts) to "auto" 】solves this issue

**Comment by mifi** [comment]
Cool! I have improved the troubleshooting docs
