### ISSUE TITLE
Translation has been registered but not translated

### ISSUE THREAD

**Issue by maboroshin** [mifi/lossless-cut#1456]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

1. Set Language to something other than English.
2. See: Menu - Tools - Keyboard & mouse shortcuts

### Expected behavior

Displayed in the selected language.

### Actual behavior

"Keyboard & mouse shortcuts" in menu remains in English.
"Keyboard & mouse shortcuts" is translated in the settings panel opened from here.

**Comment by mifi** [comment]
I'm not sure what is the problem. Do you mean that there is a string that has not been translated to all languages? You can go and translate here: https://hosted.weblate.org/projects/losslesscut/losslesscut/

**Comment by maboroshin** [comment]
@mifi 
"Steps to reproduce" are not difficult.

Strings translated in Weblate are still in English in the app menu. And this string is used in two places. One is translated. It is possible that something bad is happening with the replace() function.

KeyboardShortcuts.jsx:
```title={t('Keyboard & mouse shortcuts')}```

menu.js: ***remains in English***
```label: i18n.t('Keyboard & mouse shortcuts'.replace(/&/g, '&&'))```

**Comment by mifi** [comment]
ahh gotcha. thanks for reporting.

I see the problem. replace should be moved outside i18n.t(), like this:

```
i18n.t('Keyboard & mouse shortcuts').replace(/&/g, '&&')
```

if we don't escape `&`, then Electron will not show it (I think `&` has a special meaning in electron):

<img width="356" alt="Screenshot 2023-02-06 at 14 25 55" src="https://user-images.githubusercontent.com/402547/216898547-32245002-7e64-4036-a24f-9927eb9e12ab.png">

I think I need to do this for all menu items...

**Comment by maboroshin** [comment]
@mifi Thanks.

Other strings are in the local language. There are no places that remain in English.

For example, in other projects, It should rewrite "&" to "&amp;amp;" to see the translation string.

The cause is not clear to me. However, I considered the possibility that the "&" changed to a different string.
