### ISSUE TITLE
Split file have wrong length info

### ISSUE THREAD

**Issue by kkeonline** [mifi/lossless-cut#146]
Splitting some MP4 file format, all the split output files showing the same length as original file
This happen only with some mp4 file, and after merge all split file into one the length is multiple by split part.
Original file length = 1hr
Split part#1 length 15sec (system info show 1hr)
Split part#2 length 5min (system show 1hr)
Split part#3 length 2min (system show 1hr)
Merge file length (7:15) (system show 3hr)

I try the same mp4 file with mp4spltter from mp4tool it work the correct job, the split file show correct length in player, however the mp4splitter interface is very suck.

![2019-04-23_100947](https://user-images.githubusercontent.com/30925725/56551438-9cc12b00-65b2-11e9-9db2-f27fa46b3525.png)

**Comment by kkeonline** [comment]
After switching from All stream to Primary stream the length is correct now.

attached picture showing wrong length info (split with all stream option)
![2019-04-23_105255](https://user-images.githubusercontent.com/30925725/56558878-3a742480-65ca-11e9-9794-3b85934f1e0c.png)

**Comment by DGrv** [comment]
It seems that the issue #121 is also solved by this.
In v2.0.0 the 'Keyframe cut mode is now default'. I am wondering what is the goal of the default option 'all' (set output streams: Current include (and cut) all streams. Personally I would prefer the 'ps'as default. Or is it possible to have a config file where the user can decide which option to use at startup ?

**Comment by mifi** [comment]
I though that it would make sense to include all streams by default, and not remove any data unless necessary. But if it causes a lot of issues I can be open for changing that. There is an issue for implementing settings saving, but I have not yet implemented that.

**Comment by mifi** [comment]
The code is now changed to only include audio, video and subtitle streams by default (can be overridden.) I think the problem here was that some files contain proprietary binary streams that ffmpeg cannot cut, thus when including those they would stay the same length as before cutting, causing the video to also stay the same length. I've tested with gopro 6/7 and now it seems to work with both keyframe cut and normal cut. Reopen if still issue
