### ISSUE TITLE
Usability request

### ISSUE THREAD

**Issue by gruianovac** [mifi/lossless-cut#1460]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

have click and drag selection method for segments 
have a delete option in edit 
Export feature should not always prompt the popup / confirmation. 
rremove animations
remove transparency
make smaller font

**Comment by mifi** [comment]
> - [x] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

https://github.com/mifi/lossless-cut/issues?q=is%3Aissue+is%3Aopen+drag
