### ISSUE TITLE
Suggest the option of set by default the Tracks you normal use. 

### ISSUE THREAD

**Issue by lorduncan** [mifi/lossless-cut#1465]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Suggest the option of be able to save what tracks you normal use by default. 
Normal is video and audio, could be nice to be able to set that we need also the Gyro data from a gopro file without change it every time.

I really love this software! I can´t stop recommending it!
1.000 times THANKS!

**Comment by mifi** [comment]
Thanks. I added it here #371 - closing this to keep issue count down
