### ISSUE TITLE
Titlebar does not change to input video's name. 

### ISSUE THREAD

**Issue by psultan** [mifi/lossless-cut#1466]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

File>Open

### Expected behavior

Titlebar should update to the name of the video file. 

### Actual behavior

Titlebar just says: LoselessCut.
![lossless](https://user-images.githubusercontent.com/1406954/217956998-8d4d86e4-3d22-468f-aba8-17f20e7fa215.JPG)

### Share log

index.jsx:14 Version 3.49.0
ffmpeg.js:65 ffmpeg -hide_banner -f lavfi -i 'nullsrc=s=256x256:d=1' -f null -
DevTools failed to load source map: Could not parse content for file:///D:/Dropbox/Media/Software/PC/Appz/video/LosslessCut-win-x64/resources/app.asar/build/main.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///D:/Dropbox/Media/Software/PC/Appz/video/LosslessCut-win-x64/resources/app.asar/build/signals.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///D:/Dropbox/Media/Software/PC/Appz/video/LosslessCut-win-x64/resources/app.asar/build/core.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///D:/Dropbox/Media/Software/PC/Appz/video/LosslessCut-win-x64/resources/app.asar/build/realtime.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///D:/Dropbox/Media/Software/PC/Appz/video/LosslessCut-win-x64/resources/app.asar/build/cue.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///D:/Dropbox/Media/Software/PC/Appz/video/LosslessCut-win-x64/resources/app.asar/build/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///D:/Dropbox/Media/Software/PC/Appz/video/LosslessCut-win-x64/resources/app.asar/build/node.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///D:/Dropbox/Media/Software/PC/Appz/video/LosslessCut-win-x64/resources/app.asar/build/utf8.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///D:/Dropbox/Media/Software/PC/Appz/video/LosslessCut-win-x64/resources/app.asar/build/match.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///D:/Dropbox/Media/Software/PC/Appz/video/LosslessCut-win-x64/resources/app.asar/build/unicode.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///D:/Dropbox/Media/Software/PC/Appz/video/LosslessCut-win-x64/resources/app.asar/build/mbcs.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///D:/Dropbox/Media/Software/PC/Appz/video/LosslessCut-win-x64/resources/app.asar/build/sbcs.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///D:/Dropbox/Media/Software/PC/Appz/video/LosslessCut-win-x64/resources/app.asar/build/iso2022.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///D:/Dropbox/Media/Software/PC/Appz/video/LosslessCut-win-x64/resources/app.asar/build/command.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///D:/Dropbox/Media/Software/PC/Appz/video/LosslessCut-win-x64/resources/app.asar/build/cuesheet.js.map: Unexpected end of JSON input

App.jsx:1969 userOpenFiles
App.jsx:1970 C:\Users\Paul\Desktop\some_movie.webm
App.jsx:1545 loadMedia C:\Users\Paul\Desktop\some_movie.webm undefined undefined
App.jsx:1549 state reset
ffmpeg.js:50 ffprobe -of json -show_chapters -show_format -show_entries stream -i 'C:\Users\Paul\Desktop\some_movie.webm' -hide_banner
App.jsx:659 onDurationChange 40.477
ffmpeg.js:50 ffprobe -v error -read_intervals '0%30' -show_packets -select_streams 0 -show_entries 'packet=pts_time,flags' -of json 'C:\Users\Paul\Desktop\some_movie.webm'

**Comment by mifi** [comment]
> * [x]  Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)

> index.jsx:14 Version 3.49.0

I'm pretty sure this was fixed in 3.50.0 #1435

**Comment by psultan** [comment]
Confirmed Fixed.
