### ISSUE TITLE
Direct export of the merged file

### ISSUE THREAD

**Issue by songyin1412** [mifi/lossless-cut#1472]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

When the video is cut into multiple clips and exported and merged into a single clip, is there a way to achieve a direct export to a single merged file？

**Comment by mifi** [comment]
if you mean no temporary files per clip, then no, this has been suggested before #963 #1360 but seems to be not possible to do.
