### ISSUE TITLE
failed to change app language

### ISSUE THREAD

**Issue by taozi1996** [mifi/lossless-cut#1473]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

![GIF 2023-02-17 08-29-12](https://user-images.githubusercontent.com/31797996/219518850-82279e62-8139-400c-8d86-2f2c0537e01e.gif)

### Expected behavior

I want to change to non-English language.

### Actual behavior

It doesn't work.I failed to change any non-English language.

**Comment by taozi1996** [comment]
And v3.51.0 starts slower than the previous version

**Comment by mifi** [comment]
Thanks for reporting. will fix this bug.

> And v3.51.0 starts slower than the previous version

It starts up slower than 3.50.0? for me there is no noticable difference 🤔 the only things i can think about is [upgrading electron](https://github.com/mifi/lossless-cut/commit/cebb532656243ccef8274d14630f2e1324e83d63) and upgrading to vite - but i'm not sure why those would cause slower startup. if anything, the v51 app size is smaller than v50. How much slower? do you have any screencast?
