### ISSUE TITLE
Update the flatpak version

### ISSUE THREAD

**Issue by CodeCubeNeo** [mifi/lossless-cut#1477]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Linux

### Steps to reproduce

na

### Expected behavior

na

### Actual behavior

na

**Comment by mifi** [comment]
flatpak is not maintained by me: https://github.com/flathub/no.mifi.losslesscut/issues
