### ISSUE TITLE
Keyboard Shortcut for joining segments

### ISSUE THREAD

**Issue by hulleyrob** [mifi/lossless-cut#1478]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

I find myself wanting to join segments often, I cannot find a shortcut for this so my idea is 2 shortcuts.

1. Join current segment (selected) with the segment to the LEFT.
2. Join current segment (selected) with the segment to the RIGHT.

Would this be a useful feature for anyone else?

To make this more clear what I am doing is using the detect scene change feature and then joining some segments that belong to either the longer left or right segment.

Related to this workflow it would be useful if clear all segments was in the tools menu with detect scene changes etc OR that the menu that has been run becomes UNDO scene changes to make it easier when trying to find a good value for said function.

Thanks
Rob

**Comment by mifi** [comment]
I added now a keyboard action for the menu item "combine overlapping segments".

But reading your request again, I think what you want is something different, am I right? You don't want to join overlapping segment, but you want to selectively join neighbouring segments? as in neighbouring in time, not neighbours in order (1,2,3)?

maybe that could be implemented in a more flexible way by using the existing "select segments" functionaliuty, then another function and shortcut for "join all selected segments". Then I think we would need keyboard shortcuts also for these actions:
- "select current segment"
- "deselect current segment"

**Comment by hulleyrob** [comment]
A picture here may help.

<img width="222" alt="image" src="https://user-images.githubusercontent.com/17217514/219851287-c2fc43f5-e20f-42f3-a9e1-169e271c8e63.png">

Now from searching through with CMD+Right Arrow I know that 12 and 13 should actually be the same segment that I want to export.

My idea is CMD + ] if on segment 12 will join it with segment 13 to make a longer segment 12.

If I was in segment 13 and press CMD + [ it would effectively do the same thing but join the previous segment in this case.

Are the overlapping segments you mentioned the lighter parts either side of segment 12? I had not even realised there may be such a thing.
