### ISSUE TITLE
Error msg after update to 3.51 or 3.52 but v3.50 opens correctly

### ISSUE THREAD

**Issue by git29jet** [mifi/lossless-cut#1479]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 7

### Steps to reproduce

Current version 3.50 opens correctly.
Error occurs when updating to v 3.52 [and 3.51 before] and trying to open lossless cut.exe
error msg:
LosslessCut.exe - Entry Point Not Found The procedure entry point GetPackageFamilyName could not be located in the dynamic link library KERNEL32.dll. 

Current program location = C:\Users\Dale\AppData\Roaming
and consists of 2 folders:
LosslessCut
Lossless Cut-win-x64

### Expected behavior

see above

### Actual behavior

see above

### Share log

program does not open

**Comment by mifi** [comment]
see https://github.com/mifi/lossless-cut/discussions/1476 - i will add a note about this in the release notes

**Comment by git29jet** [comment]
Thanks for the quick reply.
For many reasons it is not feasible for me to upgrade to win10/11 so I will remain with losslesscut v3.50.
Nevertheless, I completely understand your reasons for updating electron version and abandoning win7/8.
dj
________________________________
