### ISSUE TITLE
Cannot map stream #0:6 - unsupported type.

### ISSUE THREAD

**Issue by endmarsfr** [mifi/lossless-cut#148]
Hello, 
I tried to cut/merge at ts stream with dvb subtitle.
ffmpeg returned :

```
Cannot map stream #0:6 - unsupported type.
If you want unsupported types ignored instead of failing, please use the -ignore_unknown option
If you want them copied, please use -copy_unknown
```
I tried on command line to execute with -copy_unknown, it worked.
when i run npm run watch and npm start, but i wasn't able to build an app

i've changed, 

`
 const ffmpegArgs = [
    '-f', 'concat', '-safe', '0', '-protocol_whitelist', 'file,pipe', '-i', '-',
    '-c', 'copy', **'-copy_unknown',**
    **'-map',  '0',**
    '-map_metadata', '0',
    '-y', outPath,
  ];
  
  
  const inputCutArgs = keyframeCut ? [
    ...cutFromArgs,
    '-i', filePath,
    ...cutToArgs,
    '-avoid_negative_ts', 'make_zero',
    **'-copy_unknown',**
  ] : [
    '-i', filePath,
    ...cutFromArgs,
    ...cutToArgs,
  ];`

Could you please add "-copy_unknown" for cut and merge inside lossless cut app   ? 

I tried unsuccessfully to build a dist for mac osx or windows.
I had an error when I used `npm run package:darwin_x64` 

`CANNOT RUN WITH NODE 12.1.0
Electron Packager requires Node 4.0 or above.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lossless-cut@2.1.0 package-single: `npm run copy-ffmpeg && electron-packager dist LosslessCut --out=package --asar.unpackDir=ffmpeg --overwrite --platform=${PLATFORM} --arch=${ARCH} --icon=icon-dist/${ICON} --app-copyright='Copyright (c) 2017 Mikael Finstad' --win32metadata.CompanyName=mifi --win32metadata.FileDescription=LosslessCut --win32metadata.OriginalFilename=LosslessCut.exe --win32metadata.ProductName=LosslessCut --win32metadata.InternalName=LosslessCut`
npm ERR! Exit status 1`

finally, I had succeeded to build !!!
I had to comment, linux ffmpeg in download (file not found).
I had to replace ARCH, PLATFORM and ICON variable by their value (I don't know why).
But finally I had the APP :) and it works

```
/Users/...../Downloads/lossless-cut/dist/renderer.js:272 stderr: ffmpeg version 4.1.3 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple LLVM version 10.0.1 (clang-1001.0.46.4)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.1.3_1 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags='-I/Library/Java/JavaVirtualMachines/adoptopenjdk-11.0.2.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-11.0.2.jdk/Contents/Home/include/darwin' --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-videotoolbox --disable-libjack --disable-indev=jack --enable-libaom --enable-libsoxr
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[h264 @ 0x7fee9d018200] SPS unavailable in decode_picture_timing
[h264 @ 0x7fee9d018200] non-existing PPS 0 referenced
[h264 @ 0x7fee9d018200] SPS unavailable in decode_picture_timing
[h264 @ 0x7fee9d018200] non-existing PPS 0 referenced
[h264 @ 0x7fee9d018200] decode_slice_header error
[h264 @ 0x7fee9d018200] no frame!
[h264 @ 0x7fee9d018200] SPS unavailable in decode_picture_timing
[h264 @ 0x7fee9d018200] non-existing PPS 0 referenced
[h264 @ 0x7fee9d018200] SPS unavailable in decode_picture_timing
[h264 @ 0x7fee9d018200] non-existing PPS 0 referenced
[h264 @ 0x7fee9d018200] decode_slice_header error
[h264 @ 0x7fee9d018200] no frame!
[h264 @ 0x7fee9d018200] mmco: unref short failure
    Last message repeated 1 times
[mpegts @ 0x7fee9d000000] start time for stream 5 is not set in estimate_timings_from_pts
[mpegts @ 0x7fee9d000000] PES packet size mismatch
    Last message repeated 1 times
[mpegts @ 0x7fee9d000000] Could not find codec parameters for stream 6 (Unknown: none ([5][0][0][0] / 0x0005)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mpegts @ 0x7fee9d000000] Could not find codec parameters for stream 7 (Unknown: none ([11][0][0][0] / 0x000B)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mpegts, from '/Users/..../Downloads/000.ts':
  Duration: 01:55:14.17, start: 44808.552300, bitrate: 4739 kb/s
  Program 1025 
    Metadata:
      service_name    : M6
      service_provider: Multi4
    Stream #0:0[0x78]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1[0x82](fra): Audio: eac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 192 kb/s
    Stream #0:2[0x83](fra): Audio: eac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 96 kb/s (visual impaired) (descriptions)
    Stream #0:3[0x84](qaa): Audio: eac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 128 kb/s
    Stream #0:4[0x8c](fra): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006) (hearing impaired)
    Stream #0:5[0x8d](fra): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006)
    Stream #0:6[0xaa]: Unknown: none ([5][0][0][0] / 0x0005)
    Stream #0:7[0xab]: Unknown: none ([11][0][0][0] / 0x000B)
  Program 1026 
    Metadata:
      service_name    : W9
      service_provider: Multi4
  Program 1031 
    Metadata:
      service_name    : Arte
      service_provider: Multi4
  Program 1045 
    Metadata:
      service_name    : France 5
      service_provider: Multi4
  Program 1046 
    Metadata:
      service_name    : 6ter
      service_provider: Multi4
Cannot map stream #0:6 - unsupported type.
If you want unsupported types ignored instead of failing, please use the -ignore_unknown option
If you want them copied, please use -copy_unknown
Cannot map stream #0:6 - unsupported type.
```

**Comment by endmarsfr** [comment]
here is the patched ffmpeg.js
[patched-ffmpeg.js.txt](https://github.com/mifi/lossless-cut/files/3145644/patched-ffmpeg.js.txt)

**Comment by mifi** [comment]
Hi. I'm not sure if I want to hardcode these options. I'm not sure which consequences it will have. I'm thinking maybe we could let the user edit the parameters before running the command as a workaround for this.

**Comment by endmarsfr** [comment]
Thank a lot, i agree with that.

You've done a great job!

But, please, not forget this issue too : [https://github.com/mifi/lossless-cut/issues/134](url)
it is about subtitles not merged

I am waiting for the next versions and i hope, you could easily make the cutting frame accurate with reencoding between keyframes

best regards

**Comment by mifi** [comment]
I decided to go with -ignore_unknown, because I'm thinking that when cutting a file it doesn't make sense to include streams that cannot be cut. I may be wrong, but it solves the issues. See #170

**Comment by mifi** [comment]
We can reopen this if many people think this is wrong
