### ISSUE TITLE
Auto name the llc file with ${video file name}.llc when export project to the llc

### ISSUE THREAD

**Issue by tzraeq** [mifi/lossless-cut#1480]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Now, the software will name the llc file with ${timestamp}.llc when export project to the llc，but I have a lot of video files in the same folder, so I have to type in a name related to the video file name.
Would you please name the llc file with ${video file name}.${ext}.llc when I export project to the llc ?
Thank you !

**Comment by mifi** [comment]
thanks! have implemented this change
