### ISSUE TITLE
Allow ignore first the first 2 args when not starting in dev mode

### ISSUE THREAD

**Issue by skbeh** [mifi/lossless-cut#1481]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

The current implementation:
https://github.com/mifi/lossless-cut/blob/9725d73613a1a9ea10dbcbe2bf1f5edca46726d9/public/electron.js#L143
only allows starting from electron command line in dev mode, otherwise the `The media you tried to open does not exist` error dialog will be thrown.
It would be better if it can automatically detect the arguments or we can add a environmental variable that allows specifying whether to ignore the second argument.

**Comment by mifi** [comment]
Not sure I understand. When the app is packaged, are you not able to run it from the command line?

for me it works on macos:
```
LosslessCut.app/Contents/MacOS/LosslessCut ~/myvideo.mp4 
```

it opens the file successfully on launch. which OS are you on?

**Comment by skbeh** [comment]
@mifi I want to start it via the packed asar file, not the launcher.

**Comment by mifi** [comment]
Oh ok. out of curiosity, why do you want to do that? maybe we can have an env variable

**Comment by skbeh** [comment]
Because I does not want multiple electric installation.

**Comment by mifi** [comment]
ok fair enough. do you want to submit a PR?
