### ISSUE TITLE
Smart cut cannot be disabled for full video, prevents adding additional audio tracks to video

### ISSUE THREAD

**Issue by cosborn4** [mifi/lossless-cut#1483]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

In the following steps, I wish to replace the audio track of an MP4 file with a separate MP3 audio track. The file will not need to be cut, just exported with the new audio track.

1. Open new instance of LosslessCut
2. Drag any MP4 file into the program. There should be only one segment in the timeline bar which equal in length to your entire MP4 file, like this:
![image](https://user-images.githubusercontent.com/65191629/219908788-c789f2f2-73b9-47bb-b2d5-fa058a08f097.png)
3. In the tracks menu, click "Include more tracks from other file"
4. Locate, select, and open an MP3 track
5. In the tracks menu, discard the MP4 file's audio and keep the new MP3 audio, like so:
![image](https://user-images.githubusercontent.com/65191629/219908740-583fd30b-39ab-4a6a-beef-1825d597cc47.png)
6. As stated before we are going to keep the entire length of the track and won't need to cut it. But to reproduce the bug we will temporarily shorten the segment.
7. On the timeline bar, set the cursor/playhead in a bit from the end of the track
8. Click "end current segment at current time". The timeline should now look like this: ![image](https://user-images.githubusercontent.com/65191629/219908424-899a6845-12f7-4350-a32b-7ad4c0b1e5fd.png)
9. Make sure export options are shown when exporting
10. Click Export
11. Since the segment has been shortened, we have the option to change the cut type. In the export options menu, turn on smart cut.
![image](https://user-images.githubusercontent.com/65191629/219909159-4b7a734a-d1ed-4d50-a059-9df1c86cd9eb.png)
12. Exit the export options and set the segment to the entire length of the file again:
![image](https://user-images.githubusercontent.com/65191629/219908788-c789f2f2-73b9-47bb-b2d5-fa058a08f097.png)
13. Click export again, keeping the same options as before. This time you will not see options to change the cut type, since we are no longer performing a cut operation.
14. Export the file
15. Play the exported file. It does not have any audio!

### Expected behavior

The video should export with the new audio track, since we are not cutting the track and just exporting it at full length.

### Actual behavior

The video is exported without audio even when exporting the full track. Smart cut is presumably still "shadow-enabled" and prevents the new audio track from being added to the video.

**Comment by mifi** [comment]
got a little logic issue there. thanks for reporting 👍
