### ISSUE TITLE
m3u8 HLS Livestream / VOD Support

### ISSUE THREAD

**Issue by gdomod** [mifi/lossless-cut#1486]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Please add the Feature to cut Livestreams or hosted VODs based on HLS Stream.

**Comment by mifi** [comment]
I think having an option to download a HLS stream could be possible. Then after downloading is complete (or canceled), Losslesscut could allow cutting the downloaded file. As for cutting *while* it's streaming, that I think is not possible to implement without a full rewrite of losslesscut
