### ISSUE TITLE
Autostart/autoplay the Video

### ISSUE THREAD

**Issue by amibeamer** [mifi/lossless-cut#1488]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Can you imlement that the video can Autostart? Maybe selectable via button or Preferences.

**Comment by mifi** [comment]
What’s the use case for this feature?

This has been discussed here: there has mostly been opposition:
- https://github.com/mifi/lossless-cut/issues/89#issuecomment-1224827022
- https://github.com/mifi/lossless-cut/issues/89#issuecomment-1224878485

But if you have a good reason can leave this open to see if it’s something more people want.
