### ISSUE TITLE
V 3.52.0 load some Videos slower than the older version

### ISSUE THREAD

**Issue by amibeamer** [mifi/lossless-cut#1489]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

V 3.52.0 load some Videos slower than the older version: 
Mediacodec :
Format                                   : MPEG-4
Format-Profil                            : Base Media
Codec-ID                                 : isom (isom/iso2/avc1/mp41)
Dateigröße                               : 940 MiB
Dauer                                    : 45 min 59s
Gesamte Bitrate                          : 2 857 kb/s
Kodierungs-Datum                         : UTC 2021-02-08 20:53:33
Tagging-Datum                            : UTC 2021-02-08 20:53:33
Kodierendes Programm                     : Lavf59.27.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format-Profil                            : High@L3.1
Format-Einstellungen                     : CABAC / 5 Ref Frames
Format-Einstellungen für CABAC           : Ja
Format-Einstellungen für RefFrames       : 5 frames
Codec-ID                                 : avc1
Codec-ID/Info                            : Advanced Video Coding
Dauer                                    : 45 min 59s
Source duration                          : 45 min 59s
Bitrate                                  : 2 607 kb/s
maximale Bitrate                         : 2 720 kb/s
Breite                                   : 720 Pixel
Höhe                                     : 406 Pixel
Bildseitenverhältnis                     : 16:9
Modus der Bildwiederholungsrate          : konstant
Bildwiederholungsrate                    : 29,970 (30000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scantyp                                  : progressiv
Bits/(Pixel*Frame)                       : 0.298
Stream-Größe                             : 857 MiB (91%)
Source stream size                       : 895 MiB (95%)
verwendete Encoder-Bibliothek            : x264 core 157 r2969 d4099dd
Kodierungseinstellungen                  : cabac=1 / ref=5 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=8 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-2 / threads=13 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=300 / keyint_min=29 / scenecut=40 / intra_refresh=0 / rc_lookahead=50 / rc=crf / mbtree=1 / crf=19.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Kodierungs-Datum                         : UTC 2021-02-08 20:53:33
Tagging-Datum                            : UTC 2021-02-08 20:53:33
mdhd_Duration                            : 2759190
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec-ID                                 : mp4a-40-2
Dauer                                    : 45 min 59s
Source duration                          : 45 min 59s
Bitraten-Modus                           : konstant
Bitrate                                  : 128 kb/s
Kanäle                                   : 2 Kanäle
Channel layout                           : L R
Samplingrate                             : 48,0 kHz
Bildwiederholungsrate                    : 46,875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream-Größe                             : 42,2 MiB (4%)
Source stream size                       : 42,2 MiB (4%)
Default                                  : Ja
Alternate group                          : 1
Kodierungs-Datum                         : UTC 2021-02-08 20:53:33
Tagging-Datum                            : UTC 2021-02-08 20:53:33

### Expected behavior

Normal Loading time

### Actual behavior

Loading slow

**Comment by mifi** [comment]
Hi. Which version is faster? How much faster? What do you see while loading? What line do you see in the devtools while lit’s loading?
