### ISSUE TITLE
Remember settings

### ISSUE THREAD

**Issue by mifi** [mifi/lossless-cut#149]
This has been requested many times, to remember certain settings between app launches. I'm not 100% sure if it's really that good to do, because you might forget that you had enabled an option and it will go on forever with that option without you being aware. Anyhow here are the settings that have been requested to be remembered. Put an upvote if you want this implemented

- Default output directory
- Keyframe cut / Normal cut
- Include all streams / primary streams

**Comment by mifi** [comment]
I'm thinking about using one of these:
https://github.com/sindresorhus/electron-store
https://github.com/nathanbuchar/electron-settings
https://github.com/electron-userland/electron-json-storage

**Comment by sindresorhus** [comment]
Happy to answer any questions if you decide to go with `electron-store`.

**Comment by mifi** [comment]
Thanks, Sindre. Yea I'll probably use `electron-store`, cus usually your modules are pretty rad

**Comment by mifi** [comment]
Now implemented using `electron-store`. Following settings:
```
    captureFormat
    customOutDir
    keyframeCut
    autoMerge
    timecodeShowFrames
    invertCutSegments
    autoExportExtraStreams
    askBeforeClose
    muted
```
