### ISSUE TITLE
Can't manually input start/end time segments

### ISSUE THREAD

**Issue by facelessvoice** [mifi/lossless-cut#1491]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

- Download and unzip the latest version 3.52.0
- Open the executable
- Import by dragging any video file
- Click on the manual start time segment input
- Start typing any frametime i.e 00:00:40.100
- Then type the end frametime 00:00:50.100

### Expected behavior

While manually typing these inputs the segment would resize/form automatically as you type (it does on my old version 3.46.2)

### Actual behavior

The input text becomes red font and i can't continue further.

### Share log

[-1677361915303.log](https://github.com/mifi/lossless-cut/files/10832399/-1677361915303.log)

**Comment by mifi** [comment]
thanks for reporting. have now fixed this bug
