### ISSUE TITLE
Shortcut for centering timeline view to playhead

### ISSUE THREAD

**Issue by Sermuns** [mifi/lossless-cut#1492]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

It would be very useful to press a keyboard shortcut so that the timeline pans to where the playhead is in the middle of the screen. This effect can **roughly** be achieved by tapping **z** twice, but then the zoom level changes. Thank you very much!

**Comment by mifi** [comment]
I added your suggestion here: #254 - closing this
