### ISSUE TITLE
Unable to launch multiple instances of the program

### ISSUE THREAD

**Issue by Modems2000** [mifi/lossless-cut#1494]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 11

### Steps to reproduce

Hallo

I'm sorry, I don't speak English, I use translation software.

Unable to launch multiple instances of the program.

No error occurred.

{
  "state": {
    "ffmpegExperimental": true,
    "preserveMovData": false,
    "movFastStart": true,
    "preserveMetadataOnMerge": false,
    "filePath": "G:\\Denis\\Hippocrate\\Hippocrate - S01x04 (E004) - BDrip.mkv",
    "fileFormat": "matroska",
    "externalFilesMeta": {},
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "width": 720,
        "height": 406,
        "coded_width": 720,
        "coded_height": 406,
        "closed_captions": 0,
        "film_grain": 0,
        "has_b_frames": 2,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "360:203",
        "pix_fmt": "yuv420p",
        "level": 41,
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "field_order": "progressive",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "25/1",
        "avg_frame_rate": "25/1",
        "time_base": "1/1000",
        "start_pts": 21,
        "start_time": "0.021000",
        "bits_per_raw_sample": "8",
        "extradata_size": 47,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "BPS-eng": "999721",
          "DURATION-eng": "00:54:56.520000000",
          "NUMBER_OF_FRAMES-eng": "82413",
          "NUMBER_OF_BYTES-eng": "411950176",
          "_STATISTICS_WRITING_APP-eng": "mkvmerge v25.0.0 ('Prog Noir') 64-bit",
          "_STATISTICS_WRITING_DATE_UTC-eng": "2021-04-12 10:37:27",
          "_STATISTICS_TAGS-eng": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/1000",
        "start_pts": 0,
        "start_time": "0.000000",
        "extradata_size": 5,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "fre",
          "title": "French",
          "BPS-eng": "160198",
          "DURATION-eng": "00:54:56.533000000",
          "NUMBER_OF_FRAMES-eng": "154525",
          "NUMBER_OF_BYTES-eng": "66012499",
          "_STATISTICS_WRITING_APP-eng": "mkvmerge v25.0.0 ('Prog Noir') 64-bit",
          "_STATISTICS_WRITING_DATE_UTC-eng": "2021-04-12 10:37:27",
          "_STATISTICS_TAGS-eng": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "G:\\Denis\\Hippocrate\\Hippocrate - S01x04 (E004) - BDrip.mkv": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {}
    ],
    "mainFileFormatData": {
      "filename": "G:\\Denis\\Hippocrate\\Hippocrate - S01x04 (E004) - BDrip.mkv",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "matroska,webm",
      "format_long_name": "Matroska / WebM",
      "start_time": "0.000000",
      "duration": "3296.541000",
      "size": "478891985",
      "bit_rate": "1162168",
      "probe_score": 100,
      "tags": {
        "creation_time": "2021-04-12T10:37:27.000000Z",
        "ENCODER": "Lavf58.29.100"
      }
    },
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "merge",
    "outSegTemplate": "${FILENAME}-${CUT_FROM}-${CUT_TO}${SEG_SUFFIX}${EXT}"
  },
  "platform": "win32",
  "version": "3.52.0"
}

Thanks a lot

Modems2000

### Expected behavior

I'm not sure what I'm sending is done right.

### Actual behavior

 I'm not sure what I'm sending is done right.

### Share log

 I'm not sure what I'm sending is done right.

**Comment by mifi** [comment]
Hi. See This page: https://github.com/mifi/lossless-cut/blob/master/cli.md#multiple-instances-experimental

Next version of LosslessCut will have a setting to configure whether to allow multiple instances https://github.com/mifi/lossless-cut/commit/86f451539a28464cedf16f0b0abf787a2b9b56fd

**Comment by Modems2000** [comment]
Thank you and I apologize for disturbing you.
________________________________
De : Mikael Finstad ***@***.***>
Envoyé : 4 mars 2023 03:50
À : mifi/lossless-cut ***@***.***>
Cc : Modems2000 ***@***.***>; Author ***@***.***>
Objet : Re: [mifi/lossless-cut] Unable to launch multiple instances of the program (Issue #1494)


Closed #1494<https://github.com/mifi/lossless-cut/issues/1494> as completed.

**Comment by TroyB9** [comment]
> Next version of LosslessCut will have a setting to configure whether to allow multiple instances [86f4515](https://github.com/mifi/lossless-cut/commit/86f451539a28464cedf16f0b0abf787a2b9b56fd)

Thanks for adding this option, a huge timesaver to run multiple versions at the same time!
