### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by bovirus** [mifi/lossless-cut#1495]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

@mifi 

Translation Issues

![image](https://user-images.githubusercontent.com/1262554/222497000-38c844c0-7f59-454d-b7ce-7fb68f869d4c.png)

![image](https://user-images.githubusercontent.com/1262554/222497047-89ab2e54-e081-4183-894e-bb52a680241e.png)

![image](https://user-images.githubusercontent.com/1262554/222497097-3c4359c2-f8b2-4dd1-98ae-2c5d5735c9ba.png)

### Expected behavior

To add resource in language files

### Actual behavior

The strings are untranslated

**Comment by mifi** [comment]
Thanks for reporting these issues.

1. "App language", I chose to not translate, because I want to make it easy to find the language selector if someone starts up losslesscut in an unknown language.
2. ok, fixed
3. I don't know how to fix this. It's provided by electron or the operating system

**Comment by bovirus** [comment]
@mifi 

The "Open" window - File type is provdied by develop system or Windows OS.
But in my acse is italian and should be in Italian then probably is created by your develop system.

**Comment by mifi** [comment]
> But in my acse is italian and should be in Italian then probably is created by your develop system.

I don't know why that's happening. I cannot find the text "All Files" anywhere in my code.

> How can tranbslate "Shift" in "Maiusc" (in Italian)?

try now


> In Settings window there are many strings that are in interrogative form that for me could be better and clear in affermative form.
> The interrogative form in Settings is not usual.

I agree.

**Comment by bovirus** [comment]
@mifi 

Italian tarnslation updated (100% tarnslated).

About Open>File type window what kind of developping system are you using?
What's the command that you are using to ask Open window?

**Comment by mifi** [comment]
https://www.electronjs.org/docs/latest/api/dialog#dialogshowopendialogbrowserwindow-options

not sure how to accept "all files" with a FileFilter in electron

**Comment by bovirus** [comment]
@mifi

can customize the strings "All Files" in

  filters: [
    { name: 'All Files', extensions: ['*'] }

**Comment by bovirus** [comment]
@mifi 

Please leave it open until you will fix the issues about File type..

**Comment by mifi** [comment]
it's fixed already

**Comment by bovirus** [comment]
@mifi 

Soprry I didn't see the note about teh fix.,
No need to add the relative string "All Files (*.xxx)" to weblate?
