### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by bovirus** [mifi/lossless-cut#1498]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Hi.

![image](https://user-images.githubusercontent.com/1262554/222951874-3e990a07-bd78-4043-999e-2996f5f82e6b.png)

Please check redbox.
In Italian is period flow is different.
Is "string" and after image.
In weblate I can only translate the string but not the position befroe the image.
Please modify the string to include also the marker of the image (as you see for string about cue point above). ex
 <x></x> to show advanced view 

![image](https://user-images.githubusercontent.com/1262554/222951966-37047a16-f9ca-4e93-a7be-225ed6415761.png)

Could you please increase the window width?
How can add a forced new line in the text?
I should sue special character (like /n or other)?
I already added in italian language a simple newline (CR) in the text but seems that are not recognzied as newline.

Thanks.

**Comment by bovirus** [comment]
@mifi

Could you please fix the string issue revising current string?

**Comment by bovirus** [comment]
@mifi 

See below. Please modify in weblate strings as

<z></x> to show advanced view

(add <x></x> where x is the code for the image).

 Do you know if is it possible to use as newline in html text code like <br> or \r\n or &#13;&#10;  ?

**Comment by mifi** [comment]
> @mifi
> 
> See below. Please modify in weblate strings as
> 
> to show advanced view
> 
> (add where x is the code for the image).
> 
> Do you know if is it possible to use as newline in html text code like or \r\n or ?

No, it could be possible to allow HTML like `<br />` inside translations but I don't like that idea, due to security reasons for instance

**Comment by bovirus** [comment]
@mifi 

OK.
Please complete the string as explained for show advanced view.

**Comment by bovirus** [comment]
@mifi 

Could you please revise teh string in weblate?

Thanks.

**Comment by bovirus** [comment]
@mifi 

String modified.

The width of the informative window seems unchanged.

**Comment by mifi** [comment]
you created a separate issue about that #1504
