### ISSUE TITLE
Settings windows - Strings in interrogative form

### ISSUE THREAD

**Issue by bovirus** [mifi/lossless-cut#1499]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

@mifi 

Please check screenshot of po file of italian tarnslation.

![image](https://user-images.githubusercontent.com/1262554/222953886-450c1d50-015d-4d8f-bc72-b90a7f90c084.png)

There are some mismatch about use of "?" and probably most of them regarding strings in Setting window.
As I explained for me string in interrogative form are not usal in this context.
Please check if you can change it in affermarive form.
Thanks.

**Comment by mifi** [comment]
What strings would you use instead of the current strings, for example?

**Comment by bovirus** [comment]
@mifi

Example

Cleanup file?
Cleanup file

Cleanup file after extraction?
Make cleanup file after extraction

Ask about what to do when opening a new file when another file is already open?
Action when opening a new file when another file is already open

etc.

**Comment by bovirus** [comment]
@mifi 

No news?
