### ISSUE TITLE
Invert Selection for Unselected Segments

### ISSUE THREAD

**Issue by Ryjjjj45** [mifi/lossless-cut#1503]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Is it possible to add a function and a keyboard shortcut to allow user to invert selection to select all the unselected segments and unselect all the selected segments currently? 

It should be easier for user to export segments for different purposes so that user does not need to re-select the segments for other pupose one-by-one.

**Comment by mifi** [comment]
By selected segments you mean toggling the segments in the right side panel, correct?

**Comment by Ryjjjj45** [comment]
> By selected segments you mean toggling the segments in the right side panel, correct?

Yes. Because it's difficult to re-select the unselected part one-by-one. And it's also hard to find. I might miss several segments sometimes.

**Comment by mifi** [comment]
now implemented, thanks
