### ISSUE TITLE
Hope to support the export of more audio formats in the next update

### ISSUE THREAD

**Issue by patricksun2807** [mifi/lossless-cut#1508]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Hope to support the export of more audio formats,such as FLAC and PCM in the next update

**Comment by patricksun2807** [comment]
Hope to support the export of more audio formats,such as FLAC and PCM in the next update while exporting video in MP4 format

**Comment by mifi** [comment]
FLAC and PCM is already supported. If not, please provide some more info about the problem.

**Comment by patricksun2807** [comment]
Yes, but when I want to export the video in MP4 format FLAC and PCM are not supported. Hope to support FLAC and PCM in MP4 exporting soon. TKS!

**Comment by mifi** [comment]
Why do you want to put FLAC in MP4? I think it's not possible to do that (it violates the spec - and probably no players will be able to play it back)

**Comment by patricksun2807** [comment]
But the original video is MP4 with FLAC audio in it, and Potplayer supportMP4 with FLAC audio.
And one more thing, when play video in HEVC or H265 code, the audio is silence, and this will not help us exporting more accurate videos. Hope can fix this bug in the future
