### ISSUE TITLE
no sound during playback

### ISSUE THREAD

**Issue by killaz47** [mifi/lossless-cut#151]
after (under duress, for another video editor) installing lav filters there's NO SOUND in losslesscut (only) during playback of any media file. "convert to friendly codec(slow), dleteing lavfilters, using windows restor point dated a few days before installing the lav filters, cleaning windows registry, installing ffmpeg manually, etc. didn't do anything.what is causing the issue and how it can be fixed?

**Comment by mifi** [comment]
I have no idea what lavfilters is. Is there same issue if you try to play the file in google chrome?

**Comment by killaz47** [comment]
> 
> 
> I have no idea what lavfilters is. Is there same issue if you try to play the file in google chrome?

lav filters [](https://www.videohelp.com/software/LAV-Filters) are vital component for subtitle edit and a component of k-lite codek pack. tried losslesscut 2.2.0, still no sound during playback. any thoughts?

**Comment by mifi** [comment]
I have no idea what this issue is. Only thing i can think of is trying a different computer

**Comment by killaz47** [comment]
> I have no idea what this issue is. Only thing i can think of is trying a different computer

Already done, nothing changed. Can there be made a choice which decoding software to be used by losslesscut (LAV, or any other, instead of ffmpeg), or a different player perhaps?

**Comment by mifi** [comment]
Unfortunately I'm not going to be able to replace the decoder/encoder inside losslesscut, so closing this
