### ISSUE TITLE
Notification if job is done (like VidCoder)

### ISSUE THREAD

**Issue by LeChatNoir666** [mifi/lossless-cut#1510]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

It would be nice to get an notification if a job is completed, like in VidCoder.
VidCoder have sound and also Windows notification.

It could also be done with "Things to do after all jobs are completed" to play a sound with an Powershell script as workaround like described here for Handbrake:

https://www.admin-enclave.com/computer/windows/how-to-generate-a-notifications-once-handbreak-finished-its-current-work

Would be really cool to get notified if a job is completed! :)

**Comment by mifi** [comment]
I think something like this:

https://www.electronjs.org/docs/latest/tutorial/notifications

**Comment by LeChatNoir666** [comment]
Oh yes...
Looks like an nice solution. :)
I remember now, LLC is build in an browser (btw.: awesome idea! :) ) and some sites or plugins have notifications... 
Is it hard to implement?

**Comment by mifi** [comment]
not too hard I think, but there are some quirks around when the app is allowed by the OS to send notifications and not.

**Comment by mifi** [comment]
kind of related #1511

**Comment by mifi** [comment]
have implemented this, but sound i'm not so sure about. if more people ask for it then maybe, but for now, no custom sound.
