### ISSUE TITLE
One frame inaccuracy when trimming MP4 file

### ISSUE THREAD

**Issue by MiMoHo** [mifi/lossless-cut#1513]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

MacOS 12

### Steps to reproduce

Using LosslessCut v3.53.0 arm64 on macOS 12.6.3, I was able to reproduce an issue with any MP4 H.264 file and it has nothing to do with Smart Cut as it happens in legacy keyframe cut mode as well.

### Expected behavior

When trimming a H.264 1080p 25fps MP4 file, I noticed that the first and end frame in the export file is one frame inaccurate although I would expect to cut the clip right at the frame I visually see in the program.

### Actual behavior

There is one frame added in the output file to the in and out marker I set in the program. Therefore, I assume the visual frame indication to be wrong.

**Comment by mifi** [comment]
When you say one frame inaccurate, you mean relative to what's shown in LosslessCut's video view, right? If so, I believe it could be the same issue as #1487

**Comment by MiMoHo** [comment]
> When you say one frame inaccurate, you mean relative to what's shown in LosslessCut's video view, right? If so, I believe it could be the same issue as #1487

Yes, that's what I mean @mifi
