### ISSUE TITLE
Lossless Cut being extremely slow

### ISSUE THREAD

**Issue by infypooh** [mifi/lossless-cut#1517]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

MacOS 10

### Steps to reproduce

Recently when I open a clip/video (past 2 days) it is taking like 40 seconds to open the application, than an additional 20 seconds to load the video I opened.  Than sometimes when I go through to trim/just watch the clip the entire application slows down and freezes.  I have a 2 pc setup and on my gaming pc I also have lossless cut and I have zero issues opening the app and everything is almost instant.

### Expected behavior

files open almost instantly and does not slow down.

### Actual behavior

lossless is behaving extremely slow

**Comment by mifi** [comment]
which version are you running? did you try with the previous version?

**Comment by infypooh** [comment]
I actually accidentally figured it out this morning.  One of the steps to
fix was to disable your security software which I did do. But for whatever
reason an old security software that my subscription had expired too was
still running and that software was what ended up causing it to not work
properly!

**Comment by mifi** [comment]
What does «your security software» mean?

**Comment by mifi** [comment]
closing this for now

**Comment by mifi** [comment]
> Seeing this with on my machine:

- is it the same with older versions of llc?
- if you open losslesscut, how long does it take to launch?
- if you drag drop a video into a running losslesscut, does it takes 20 sec until it loads?
- does it slow down while you use it or just when launching / opening files?

**Comment by gabriel-r** [comment]
My bad 🙈
I got the x86 version, the arm64 version is nice and snappy.
Never mind, and thanks!
