### ISSUE TITLE
Problem Cutting and Merging

### ISSUE THREAD

**Issue by AlexUCeli** [mifi/lossless-cut#1518]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Linux

### Steps to reproduce

After make de cut, the i got an error

### Expected behavior

Cut and Merge

### Actual behavior

Error window

### Share log

Error: Command failed with exit code 1: /app/lossless-cut/resources/ffmpeg -hide_banner -f concat -safe 0 -protocol_whitelist file,pipe -i - -map 0:0 -c:0 copy -disposition:0 default -map 0:1 -c:1 copy -disposition:1 default -movflags +faststart -default_mode infer_no_subs -ignore_unknown -f mp4 -y /root/Vídeos/USA_college/WSR-cut-merged-1679643153168.mp4
[fd @ 0x55fbfe1a16c0] Protocol 'fd' not on whitelist 'file,pipe'!
fd:: Invalid argument
    at makeError (/app/lossless-cut/resources/app/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/app/lossless-cut/resources/app/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "ffmpegExperimental": false,
    "preserveMovData": false,
    "movFastStart": true,
    "preserveMetadataOnMerge": false,
    "filePath": "/root/Vídeos/USA_college/WSR.mp4",
    "fileFormat": "mp4",
    "externalFilesMeta": {},
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 1254,
        "height": 720,
        "coded_width": 1254,
        "coded_height": 720,
        "closed_captions": 0,
        "film_grain": 0,
        "has_b_frames": 1,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "209:120",
        "pix_fmt": "yuv420p",
        "level": 31,
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "field_order": "progressive",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "id": "0x1",
        "r_frame_rate": "30/1",
        "avg_frame_rate": "1669391661/55646333",
        "time_base": "1/15360",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 562457549,
        "duration": "36618.330013",
        "bit_rate": "1463459",
        "bits_per_raw_sample": "8",
        "nb_frames": "1098551",
        "extradata_size": 44,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "ISO Media file produced by Google Inc.",
          "vendor_id": "[0][0][0][0]"
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "44100",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "initial_padding": 0,
        "id": "0x2",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/44100",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 1614870528,
        "duration": "36618.379320",
        "bit_rate": "127999",
        "nb_frames": "1577022",
        "extradata_size": 16,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "eng",
          "handler_name": "ISO Media file produced by Google Inc.",
          "vendor_id": "[0][0][0][0]"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "/root/Vídeos/USA_college/WSR.mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {
        "start": 3459.356841,
        "end": 3628.756841
      },
      {
        "start": 3763.356841,
        "end": 3813.356841
      },
      {
        "start": 4703.32985,
        "end": 5135.52985
      },
      {
        "start": 26525.452933,
        "end": 27000.782674
      },
      {
        "start": 27117.982668,
        "end": 27193.782665
      },
      {
        "start": 27267.982663,
        "end": 28153.182663
      },
      {
        "start": 28412.582663,
        "end": 29056.382663
      },
      {
        "start": 29789.782663,
        "end": 30004.382663
      },
      {
        "start": 32269.386409000002,
        "end": 32314.386409
      }
    ],
    "mainFileFormatData": {
      "filename": "/root/Vídeos/USA_college/WSR.mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "36618.379320",
      "size": "7328003645",
      "bit_rate": "1600945",
      "probe_score": 100,
      "tags": {
        "major_brand": "isom",
        "minor_version": "512",
        "compatible_brands": "isomiso2avc1mp41",
        "encoder": "Lavf58.29.100"
      }
    },
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "merge",
    "outSegTemplate": "${FILENAME}-${CUT_FROM}-${CUT_TO}${SEG_SUFFIX}${EXT}"
  },
  "platform": "linux",
  "version": "3.52.0"
}

**Comment by UrsusLvovich** [comment]
I am also having this problem. The program cuts all the segments into separate files, but when it starts the merge, immediately fails with the same error message. Tried exporting as mp4, mov, and mkv

**Comment by UrsusLvovich** [comment]
I just downloaded OpenShot, was able to drag all the segments into the program, add them in sequence and export as a single file. That way worked

**Comment by mifi** [comment]
Are you all on linux? i think ffmpeg might have changed something. Does it work if you select an older version of ffmpeg? (External)

**Comment by pixeldin** [comment]
try to add **fd** to this option, like `-protocol_whitelist 'file,pipe,fd'`

**Comment by mifi** [comment]
ok i added `fd` to the option

**Comment by AlexUCeli** [comment]
> Are you all on linux? i think ffmpeg might have changed something. Does it work if you select an older version of ffmpeg? (External)

Yes, I work with Rocky Linux 8

**Comment by AlexUCeli** [comment]
Finally I remove all the losslesscut, and reinstall and works fine again...!!!

**Comment by mifi** [comment]
🧐🧐🧐 that’s odd
