### ISSUE TITLE
Exporting and merging generates larger files than the original

### ISSUE THREAD

**Issue by Avila-Diego** [mifi/lossless-cut#1519]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

MacOS 13

### Steps to reproduce

I have a video that I recorded with OBS, the original video format is "mkv", I have tried with the "mp4" that results from doing the conversion in OBS and with the "mp4" from using the "convert to a compatible format" function.

The original video is 18:21 minutes long.

I generate 169 segments and expert them, with the default characteristics (I have tried other configurations but the problem repeats itself). 

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/6963761/227633865-a002c6a2-17d3-4f19-85d3-17fd02d77e56.png">

I export the segments separately or generate the files individually.

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/6963761/227634037-8976ef92-9644-4b3c-86fd-be706b44e64a.png">

The video and audio encoding is:

<img width="680" alt="image" src="https://user-images.githubusercontent.com/6963761/227637608-a5897c1d-e835-4162-bb4b-e9f48d8733c1.png">

### Expected behavior

I want to get a single video or the videos separately with only the selected sections.

### Actual behavior

I get very large videos, even when combined they generate files larger than 5 GB.

### Share log

This is the final execution code:
ffmpeg -hide_banner -ss '1077.66665' -i '/Users/aviladiego/Movies/Videos/3.1.1 Introdución dplyr y filter.mp4' -t '3.56335' -avoid_negative_ts make_zero -map '0:0' '-c:0' copy '-tag:0' hvc1 -map '0:1' '-c:1' copy -map_metadata 0 -default_mode infer_no_subs -ignore_unknown -f mp4 -y '/Users/aviladiego/Movies/Videos/3.1.1 Introdución dplyr y filter-00.17.57.667-00.18.01.230-seg168.mp4'

**Comment by mifi** [comment]
Hi. What’s the keyframe interval? Are you cutting segments shorter than keyframe intervals? If so, it could result in longer output durations.

**Comment by mifi** [comment]
So it seems that the "cut-from" argument is being ignored. Do you have a short OSB recording that you can share that can reproduce this problem?

**Comment by Avila-Diego** [comment]
Sure, here I share a link to a video

https://drive.google.com/file/d/16RzaDkTugUlvVpi1SR8DFeQxKlO7VMGe/view?usp=sharing

**Comment by mifi** [comment]
Thanks. Unfortunately this file seems to be corrupted, as it doesn't play back correctly in players like VLC.
Do you have an original OBS file that plays back correctly, but when you cut it in losslesscut it gives the behaviour that you described:
> If I have a 20 minute file and I have two cuts, from minute 4 to 5 and from 15 to 18. I have as individual clips from minute 0 to 5 and from 0 to 18.

**Comment by Avila-Diego** [comment]
Sorry. The error probably occurred while uploading the file. I have shared a folder with two files ([link](https://drive.google.com/drive/folders/16RQzCMcamAF6bSq-aoKEYFioSFkC-G7u?usp=sharing)).   

I am testing on Windows and MAC (with M1 chip) with the same result.

**Comment by mifi** [comment]
Thanks for sharing. Unfortunately both of these files also are not playable for me in any player on macos like IINA or VLC, so I think there's something wrong with the files, maybe a bug in OBS?
