### ISSUE TITLE
failed to extract all streams

### ISSUE THREAD

**Issue by killaz47** [mifi/lossless-cut#152]
"failed to extract all streams" losslesscut error that happens with most of the .mkv files in losslesscut

1)the ,mkv file that it had failed to extract:

 cutted sample: https://nofile.io/f/pyhRDYbeb86/Star.Trek.2009.720p.(sample+file).mkv

 screenshot http://tinypic.com/view.php?pic=tw5g&s=9

sample mediainfo report:https://gofile.io/?c=Sd1tka
losslesscut console log before extraction https://gofile.io/?c=GT0TDG
console log after extraction attempt (failed to extract all streams) https://gofile.io/?c=CarBMq
2)the ,mkv file that it has extratced succesfully:

cutted sample: https://nofile.io/f/CHdjfXhEqEG/Serenity+(sample+file).2019.BDRip.720p.mkv

screenshot:http://tinypic.com/view.php?pic=25z4k1e&s=9

sample mediainfo report:https://gofile.io/?c=97Tnhi

**Comment by mifi** [comment]
Can you try 2.2.0?

**Comment by killaz47** [comment]
> 
> 
> Can you try 2.2.0?

it does work now although extraction takes very long time. would be appreciated if extraction would be fixed to the original streams file extensions (.ac3 audio tracks, srt subtitle)

**Comment by mifi** [comment]
Yea, then we need to have a mapping between all codecs and which formats (extensions) that support these codecs. I don't know where to find such a mapping which is also correct for ffmpeg.
