### ISSUE TITLE
Posibility to change display aspect ratio?

### ISSUE THREAD

**Issue by Jessegao2020** [mifi/lossless-cut#1527]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

I'm running the latest version 3.53.0 on Windows 10.

**Issue:** 
MPEG-4 Part 2 encoded videos + adding "rotation" will not display properly on Windows Photos App: Only the video container rotated, leaving the video content itself not rotated. Result is, creating a big blank black area where the container is not filled with video content. I see this when I change portrait video to landscape or vice versa.

Potplayer and VLC can both recognize the "rotation" info under "display matrix" tag. I know Windows Photos is not a popular app to view videos (its name already revealed that). But when it comes to checking different videos from a large video quantity, Windows Photos loads much faster than the mentioned two. Flipping throught videos's speed is just like fliping through photos.

**My Test Result:**
H.264 codec + “rotaion” from “display matrix” works together perfectly
MPEG-4 part 2 + changing aspect ratio also works good

I guess adding either "change codec" or "change aspect ratio" feature will dramatically slow down lossless cut's process speed? thus is against its original built purpose.

So is there a easy solution to solve this delima? Thank you for your time to respond..

**Comment by mifi** [comment]
changing codec requires a re-encode. This is something I'll consider implementing but not yet: #372

changing rotation or aspect ratio losslesscut so that it works in Windows Photos, I don't know how to do unfortunately. So I'll close this unless someone can find some technical way to do it
