### ISSUE TITLE
segment export name error

### ISSUE THREAD

**Issue by renmu123** [mifi/lossless-cut#1528]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 11

### Steps to reproduce

1. create a segment
2. named as chinese like "小王子"
3. export as single file

![image](https://user-images.githubusercontent.com/26896790/228595890-62c7d4fc-eb7c-494f-bc83-6ab78fdb325a.png)
![image](https://user-images.githubusercontent.com/26896790/228596000-e5c5a31c-cb28-4cd3-9cc3-11e7650c15b1.png)
![image](https://user-images.githubusercontent.com/26896790/228596680-0ac1776c-38fe-4879-b287-5da803943038.png)

### Expected behavior

The file name should be `录制-27183290-20230329-194628-213-游戏时间-02.42.51.648-02.57.00.432-小王子.mp4`

### Actual behavior

The file name is `录制-27183290-20230329-194628-213-游戏时间-02.42.51.648-02.57.00.432-___.mp4`

**Comment by mifi** [comment]
Try to click the "sanitize" button in the output dialog

**Comment by mifi** [comment]
See https://github.com/mifi/lossless-cut/issues/889#issuecomment-950335497
