### ISSUE TITLE
Add Title tag readout to the Tracks Screen

### ISSUE THREAD

**Issue by DmitriyYukhanov** [mifi/lossless-cut#1530]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Hey @mifi

Could it be a good idea to add the `'title'` column on the Tracks Screen? It would make it easier to distinguish tracks from each other when a video has many tracks with different translations for the same language, like this one:

![image](https://user-images.githubusercontent.com/883587/229136852-3f492e98-2821-44d5-916b-11e100ad2e0f.png)

Possibly should be discussed at #482, but creating a separate issue for now.

**Comment by mifi** [comment]
Hi. Not sure what's a "title". Where does does it come from?

**Comment by DmitriyYukhanov** [comment]
Hi @mifi I mean this one:
![image](https://user-images.githubusercontent.com/883587/229498765-f6d82d43-15df-4b18-9f36-a55bc42ac7c7.png)

**Comment by mifi** [comment]
Do you know any (small) example file that has this tag?

**Comment by DmitriyYukhanov** [comment]
Actually, it wasn't easy to find something small with multiple audio tracks where the title would be filled on public since this is something I do usually see in bigger files with multiple dubs.

Still, I found the Pixar intro which has an audio track with the title tag filled, here is an under-15-megs cut of it:
[Pixar-logo-cut.zip](https://github.com/mifi/lossless-cut/files/11141595/Pixar-logo-cut.zip)

I've also realized this can be something rarely filled and wouldn't worth it to always occupy space for this tag in Tracks Screen table as in most cases it can be empty.

Instead, it might be nice to show a title column on the Tracks Screen if at least 1 track has this tag filled.

Please let me know what do you think. While I'm not proficient with JS, I'd still be happy to participate and try crafting it in PR.

**Comment by DmitriyYukhanov** [comment]
Amazing, thank you 🧡
