### ISSUE TITLE
KERNEL32.dll 

### ISSUE THREAD

**Issue by Electorn** [mifi/lossless-cut#1531]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 7

### Steps to reproduce

On Click LosslessCut EXE fails to open the Program with this message. "The Procedure entry point GetPackageFamilyName could not be located in the dynamic link library KERNEL32.dll"  I'm attempting to run LosslessCut Version 3.52.0 on a Windows 7 64 bit machine. 

### Expected behavior

The Losslesscut.EXE File should execute and open the Program

### Actual behavior

On Click LosslessCut EXE fails with this message. "The Procedure entry point GetPackageFamilyName could not be located in the dynamic link library KERNEL32.dll"  I'm running Windows 7 64 bit.  I have verified that KERNEL32.dll is in this Windows Directory on this machine.  I even tried to copy and paste the Kernel32.dll in the same directory as Losslesscut of course that didn't work.

Side note: I am also running Losslesscut on a Windows 10 machine. That Installation also had an issue because of a missing ffmpeg.dll.  After 3 Downloads the missing ffmpeg.dll showed up and it all works. 

Thanks for the help

**Comment by mifi** [comment]
> - [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)


https://github.com/mifi/lossless-cut/search?q=KERNEL32.dll&type=issues

**Comment by cyberhardt** [comment]
the last windows 7 compatible version is 3.50.0, you're having issues with kernel32 bc the electron version the newer releases use has dropped support for windows 7
