### ISSUE TITLE
Feature Request: Add a setting to opt-in to a custom directory for project files.

### ISSUE THREAD

**Issue by YousufSSyed** [mifi/lossless-cut#1536]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

I edit videos in my Downloads folder where a bunch of other files are too and I don't want project files to be there. Perhaps you could add a button under "Tools" called "Project directory settings" and show a menu letting the user choose between have it in the same folder as the videos or in a custom one.

**Comment by mifi** [comment]
hi. how's this different from the setting "Store project file (.llc) in the working directory or next to loaded media file | Store in working directory"?

**Comment by mifi** [comment]
It increases complexity so I'm not sure about this yet, but I can leave it open to see if it's a popular feature request

**Comment by YousufSSyed** [comment]
How does it increase complexity? Is it more than just a matter of having the file in a different directory for reading and writing? I don't know much about them.

**Comment by mattack1** [comment]
I use LosslessCut to cut one or two sections out of a file (e.g. musical performances on SNL or a talk show).  I wish I could save exported files in the same as the input file but save the project and any other files in /tmp (so they go away by themselves).. or not save them at all (but without a prompt each time I try to quit or close).

So I understand/agree with the request.

**Comment by mifi** [comment]
@mattack1 I think you can already turn off project file saving. Other generated files can be auto-deleted when you close the file. (Press D)

**Comment by YousufSSyed** [comment]
@mifi How do u do that? This gave me an idea for this discussion post: [Should LosslessCut have a repo wiki?](https://github.com/mifi/lossless-cut/discussions/1542)

**Comment by mifi** [comment]
https://github.com/mifi/lossless-cut/blob/f62fe6d941c3b7680c309a224caacb0dde686e32/src/components/Settings.jsx#L124

**Comment by YousufSSyed** [comment]
Alright, I guess I'll wait for tomorrow's night build.

**Comment by mifi** [comment]
no that setting has been there for years

**Comment by YousufSSyed** [comment]
Oh I didn't see it there the first time lol.

**Comment by mifi** [comment]
closing in favor of #2115
