### ISSUE TITLE
Linux: 3.54.0 "About" help menu entry does nothing (does not open window)

### ISSUE THREAD

**Issue by slrslr** [mifi/lossless-cut#1537]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Linux

### Steps to reproduce

Hello, on Linux Debian + KDE I have latest AppImage 3.54.0
When i click Help menu and then "About" menu entry, nothing happen. Other entries in same menu opens, like problem report above it.

Anyone else with same issue?

### Expected behavior

should open

### Actual behavior

does not open

### Share log

/.config/LosslessCut/app.log does not add any entry during operation.
Dev. console either, but shows:
```
index-2c6483e9.js:308 Version 3.54.0
index-2c6483e9.js:169 ffmpeg -hide_banner -f lavfi -i 'nullsrc=s=256x256:d=1' -f null -
DevTools failed to load source map: Could not parse content for file:///tmp/.mount_LossleBE3upN/resources/app.asar/node_modules/cue-parser/lib/cue.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///tmp/.mount_LossleBE3upN/resources/app.asar/node_modules/cue-parser/lib/command.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///tmp/.mount_LossleBE3upN/resources/app.asar/node_modules/cue-parser/lib/cuesheet.js.map: Unexpected end of JSON input
```

**Comment by mifi** [comment]
hi. does it work on the previous version?

**Comment by slrslr** [comment]
> hi. does it work on the previous version?

Yes, previous (3.53) works, current not. Previous shows different translation of the menu item: Verze (non-english), current non working one shows: About

**Comment by mifi** [comment]
seems to be a bug in electron: https://github.com/electron/electron/issues/23847

I created a PR to fix it there https://github.com/electron/electron/pull/37828

**Comment by mifi** [comment]
I think this should be fixed now in the latest release. can reopen if not

**Comment by slrslr** [comment]
Thank you for the new release and improvements.
I have just downloaded 3.56.0 AppImage and it started showing the window now, yet the version figure is missing in it:
![image](https://github.com/mifi/lossless-cut/assets/6596726/8f9e9c3a-8999-4e62-b2a3-1eeeca654e0b)

last lines of the `tail -n 300 $HOME/.config/LosslessCut/app.log`
```
info: Waiting for app to become ready
info: CLI arguments { _: [] }
info: Current version 3.56.0
info: Newest version 3.56.0
```

Dev. console shows:
```
index-3c673242.js:299 Version 3.56.0
DevTools failed to load source map: Could not load content for file:///tmp/.mount_Losslesf0mXG/resources/app.asar/node_modules/cue-parser/lib/cue.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///tmp/.mount_Losslesf0mXG/resources/app.asar/node_modules/cue-parser/lib/command.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///tmp/.mount_Losslesf0mXG/resources/app.asar/node_modules/cue-parser/lib/cuesheet.js.map: Unexpected end of JSON input

```

**Comment by mifi** [comment]
This is a shortcoming in electron. Once they fix it, then it will also be resolved here in losslesscut. see https://github.com/electron/electron/issues/18918
