### ISSUE TITLE
classify output container format

### ISSUE THREAD

**Issue by taozi1996** [mifi/lossless-cut#1539]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

![屏幕截图 2023-04-05 125912](https://user-images.githubusercontent.com/31797996/229985330-f1a2754e-0a77-47c4-bc77-86fb4775692e.png)

Losslesscut has already common formats which is great. I would like to have a more detailed classification.
Commmon video formats : mp4 mkv webm  .etc
Commmon audio formats : mp3 flac aac ac3 .etc
Commmon subtitle formats : ass srt sup webvtt .etc

Sometimes I just want to export subtitle files.It's difficult for me to find a suitable subtitle format.

**Comment by mifi** [comment]
Hi.
I like your idea, but the problem is that many formats can contain both video/audio or only one of those. For example matroska can be used for video or for audio only. Also your audio classification is not entirely correct:

> Commmon audio formats : mp3 flac aac ac3 .etc

only mp3 and flac are commonly used format.  `aac` is not a format, `ac3` I believe is not a very common format, normally you'd put it into something like  a mov or m4a format.

But I agree we can have a subtitle category.

**Comment by taozi1996** [comment]
> Hi. I like your idea, but the problem is that many formats can contain both video/audio or only one of those. For example matroska can be used for video or for audio only. Also your audio classification is not entirely correct:
> 
> > Commmon audio formats : mp3 flac aac ac3 .etc
> 
> only mp3 and flac are commonly used format. `aac` is not a format, `ac3` I believe is not a very common format, normally you'd put it into something like a mov or m4a format.
> 
> But I agree we can have a subtitle category.

Yes.,a subtitle category!
