### ISSUE TITLE
Suggestion: add 'HELP>ABOUT'

### ISSUE THREAD

**Issue by KevinYork** [mifi/lossless-cut#154]
add 'HELP>ABOUT'

**Comment by mifi** [comment]
Why do we need this? currently there is a More Info link to the website under help

**Comment by KevinYork** [comment]
I certainly can’t justify ‘need this…’.

But…

1)      It’s a standard [or at least a Windows standard] and easy to do.

2)      Doesn’t the ‘More Info’ link give you information on your current release 
[rather than the version the user is currently running]?

**Comment by guymanley** [comment]
[rather than the version the user is currently running] True and the only way I know what version I am running in to delete and reinstall the version that I intend to use.

**Comment by pedzed** [comment]
> Why do we need this? currently there is a More Info link to the website under help

First of all, I never click on external links in my menu bars. If I accidentally do, I quit right away with frustration that my browser gets triggered. It's an anti-pattern (or whatever it is called). Please, don't do this.

Secondly, for error reporting it is important to mention the app version when creating issues. By getting a dialog box when clicking on `Help > About`, the app version can be showed, including information about dependencies and perhaps some useless but nice credits of contributors.

Debugging errors and understanding (GitHub) issues across different versions would become a lot easier in the long run, especially for issues that are old and become irrelevant.

**Comment by mifi** [comment]
At least on Mac you can currently see the running version by pressing "About LosslessCut". Does it not work on windows? I have not tested so much on windows.

**Comment by KevinYork** [comment]
Not in Windows.

**Comment by mifi** [comment]
Ok I added on windows and linux too now #161. will be in next release
