### ISSUE TITLE
A problem about  output keeping  tracks

### ISSUE THREAD

**Issue by taozi1996** [mifi/lossless-cut#1540]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 11

### Steps to reproduce

v3.53.0
![3 53 0](https://user-images.githubusercontent.com/31797996/229992026-91945892-c44a-43bb-9841-2a40d9d891f4.gif)
v3.54.0

![GIF 2023-4-5 14-02-33](https://user-images.githubusercontent.com/31797996/229994404-61517c2d-e2b7-45b6-9e96-5c543fd80d42.gif)

### Expected behavior

Automatically pop up a track selection page like v3.53.0

### Actual behavior

In v3.54.0, clicking on "keeping tracks" will not automatically pop up  the track selection page.

**Comment by mifi** [comment]
thanks for reporting. that's a bug

**Comment by taozi1996** [comment]
v3.55.2
After selecting the track on the export page and closing the track page， I need to click Export again to display the export options page.

The export options page cannot always be displayed at the bottom.

**Comment by mifi** [comment]
Ah, maybe that could be changed yes. Could change the order so that tracks screen is on top. But then if someone is on the tracks screen and presses E (export), then the export dialog will not be visible 🤔

**Comment by taozi1996** [comment]
> Ah, maybe that could be changed yes. Could change the order so that tracks screen is on top. But then if someone is on the tracks screen and presses E (export), then the export dialog will not be visible 🤔

v3.53.0 is normal, but it has been disabled since v3.54.0
