### ISSUE TITLE
Option toggle "Show informational notifications" defunct

### ISSUE THREAD

**Issue by xbyte99** [mifi/lossless-cut#1541]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

Settings > Prompts and dialogs > Show informational notifications > click on the enable/disable slider button.

### Expected behavior

As it is not a grayed out/disabled button it is expected to react to clicks, thus enabling or disabling informational notifications

There's no further explanation to this option but I would assume (and hope), that the "Export is done" dialog window would not be shown after a successful export. In my case, as I'm often cutting dozens of videos after another, it's kind of annoying having to click the "close" button of this dialog when drag&drop a new file to the main window.

### Actual behavior

There's no change, no reaction to a click, it stays enabled.

**Comment by mifi** [comment]
right. that's a bug. thanks!

**Comment by VL4DST3R** [comment]
Came here to report the same issue, using the latest 3.54.0 i can't seem to be able to change it, the switch again not working like OP said. Please tell me we're not stuck with that useless "export is done" blocking popup at the end?

**Comment by mifi** [comment]
you're stuck with it until the next version comes out. or you could go here and find the latest build: https://github.com/mifi/lossless-cut/actions/runs/5679153798

**Comment by VL4DST3R** [comment]
I was literally checking the commit version and couldn't figure out why it was newer than latest build XD Thanks.

**Comment by mifi** [comment]
https://github.com/mifi/lossless-cut/blob/3b53051e3d57760d6f16d8b9dd19b54de378e84b/src/components/Settings.jsx#L289

**Comment by mifi** [comment]
i don't understand, why do you need to add it in config.json? doesn't the toggle button work on the latest build?

**Comment by VL4DST3R** [comment]
I couldn't install the latest-latest build (3.55.0)- the version you linked me above would not open at all, spawning 3 processes with 0 activity. No errors in event viewer, no notifications, nothing. I eventually reverted to the "official" latest 3.54 and was trying to manually set that in the config.json to achieve the same result

**Comment by mifi** [comment]
yes there was an issue with the latest github actions artifact, should be fixed now
