### ISSUE TITLE
LoselessCut 3.54 - About string untranslated

### ISSUE THREAD

**Issue by bovirus** [mifi/lossless-cut#1544]
@mifi 

### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 11

### Steps to reproduce

Using Italian GUI the string "About" in "Help" menu is untranslated.

Note: in Weblate the Italian language is localized at 100%.

![image](https://user-images.githubusercontent.com/1262554/230093533-ec345bc7-f3ea-4b2e-ad43-ec5e854ed9ca.png)

### Expected behavior

Show untranslated

### Actual behavior

The strings should be show in Italian.

**Comment by bovirus** [comment]
@mifi 

How fix it?

**Comment by mifi** [comment]
I fixed it in the code: https://github.com/mifi/lossless-cut/commit/f477b74918279a6dbe900188309ba10e2b84b35f

the translation will be back in the next version

**Comment by bovirus** [comment]
@mifi 

Thanks.
I will check in next temporary build.
Please check other issues that I opened today.
