### ISSUE TITLE
无法打开程序

### ISSUE THREAD

**Issue by a3659950** [mifi/lossless-cut#1545]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

MacOS 13

### Steps to reproduce

双击程序，打不开，提示无法定位程序输入点getpackagefamilyname于动态链接库kernel32.dll

### Expected behavior

双击程序，打不开，提示无法定位程序输入点getpackagefamilyname于动态链接库kernel32.dll

### Actual behavior

双击程序，打不开，提示无法定位程序输入点getpackagefamilyname于动态链接库kernel32.dll

### Share log

双击程序，打不开，提示无法定位程序输入点getpackagefamilyname于动态链接库kernel32.dll

**Comment by mifi** [comment]
> - [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

https://github.com/mifi/lossless-cut/search?q=KERNEL32.dll&type=issues
