### ISSUE TITLE
Can't export Subtitle, it's a 0 size file

### ISSUE THREAD

**Issue by shruru** [mifi/lossless-cut#1547]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476) **I am not using Windows 8.1 or older**

### Operating System

MacOS 13

### Steps to reproduce

I got a mp4 embedded subtitle .VTT file which I choice to export it as a single file. however it didn't work out.  I tried every options in LosslessCut, no luck...please help. 

I am using the latest version of it. MacOS 13. Thank you.

### Expected behavior

Export a .vTT file 

### Actual behavior

a file within 0 file size.

**Comment by mifi** [comment]
could you provide some more info? like what does it mean "didn't work out"
