### ISSUE TITLE
Suggestion: drop WINDOW>CLOSE; add FILE>CLOSE [i.e. close current files. Do NOT exit]

### ISSUE THREAD

**Issue by KevinYork** [mifi/lossless-cut#155]
You currently have:
- FILE>OPEN
- FILE>EXIT
- WINDOW>CLOSE (which appears to be the same as FILE>EXIT)

To be like other Windows apps; I think you should have:
- FILE>OPEN
- FILE>CLOSE
- FILE>EXIT

**Comment by KevinYork** [comment]
...just wondering what you thought about this suggestion...
1) renaming a couple menus.
2) add FILE>CLOSE [i.e. close current files. Do NOT exit]
obviously, #2 was the real point of this suggestion.

[I was trying to make it easier to edit multiple videos.
    ...I didn't think about it during my original post; but I guess that would also mean adding:
    3) FILE>SAVE  PROJECT
    4) FILE>OPEN PROJECT
]

**Comment by mifi** [comment]
Have now implemented close file
Open/save project has to come in a future release. there are other issues covering this.
