### ISSUE TITLE
The video rotate function does not work, I selected rotate, but the exported video is still not rotated.

### ISSUE THREAD

**Issue by Gjx031720** [mifi/lossless-cut#1552]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476) **I am not using Windows 8.1 or older**

### Operating System

MacOS 13

### Steps to reproduce

The video rotate function does not work, I selected rotate, but the exported video is still not rotated.

### Expected behavior

The video should rotate, but the exported video does not rotate.

### Actual behavior

视频和原来的视频一样，并没有旋转。

**Comment by mifi** [comment]
please use this issue template instead: https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml
