### ISSUE TITLE
Is it possible to choose to rotate the video while merging the video?

### ISSUE THREAD

**Issue by Gjx031720** [mifi/lossless-cut#1553]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Some videos need to be rotated when merging it, but you need to select rotate and then merge, if you can set the rotation of the video while merging, it will be faster

**Comment by mifi** [comment]
I think what you can do instead is:

1. select files to merge
2. merge the files
3. open merged output file
4. select rotation
5. export

It will only be a few clicks, so I think it should be ok?
