### ISSUE TITLE
Batch extracting of (part of) all tracks

### ISSUE THREAD

**Issue by lapineige** [mifi/lossless-cut#1554]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Hello,

Thank you for this very handy software.

# Feature proposal

I would like to be able to batch extract tracks, in particular only video or only audio tracks if possible

## Possible implementation

As a proposal, one way to implement this would be to add on top of the file list a new button (with the extract icon for instance) that would batch extract all tracks.
Alternatively, it could show a drop-down/menu to extract only video/audio/subtitles tracks.

# Current situation

Currently the fastest way to do that is to open a list of file, select *and open* the first one, extract all track using a custom shortcut, select and open the next one, and so on.
And then remove all unwanted tracks if you want only audio/video.

That can be a bit painful and quite long depending on the number of files.

**Comment by mifi** [comment]
Hi. Thanks for your suggestion. I think this is a two part feature:
- [ ] being able to extract only certain tracks by the click of a button
- [ ] being able to do this in batch with all files in the list

I think for the first point, I can change the Export each track as a separate file to only export the enabled tracks, becasuse there are already buttons for selecting all video tracks / all audio tracks

**Comment by mifi** [comment]
added your suggestion here #868 as it would be probably implemented as part of a bigger batch feature. closing this to keep issue count down, thanks!

**Comment by mifi** [comment]
For now maybe you can ask chatgpt to write a bash script to do it for you :)

**Comment by lapineige** [comment]
:rofl:
Not going to happen :smile:

> because there are already buttons for selecting all video tracks / all audio tracks

I didn't know that, thank you.

**Comment by m1nuzz** [comment]
> For now maybe you can ask chatgpt to write a bash script to do it for you :)

I asked ChatGPT to create a batch script with an option to select how many of the last minutes to keep for trimming. I created a fork and uploaded it there with ffmpeg; I hope it helps someone.
https://github.com/m1nuzz/batch-lossless-cut

**Comment by Dragodraki** [comment]
I'd like to say, I would ask for an implementation in LosslessCut of extracting all separated tracks as batch job too. To separate them is a common way to prepare any audio/video optimization and with having about 75-100 single files doing that for every would be too much effort.

Maybe the dev could add this feature to LosslessCut (extract all tracks for multiple files as batch job)?
