### ISSUE TITLE
ATSC 3.0 Recordings from Channels DVR have no sound

### ISSUE THREAD

**Issue by sdschramm** [mifi/lossless-cut#1555]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476) **I am not using Windows 8.1 or older**

### Operating System

MacOS 12

### Steps to reproduce

1. Make a recording of an ATSC 3.0 channel via the Channels DVR app. 
2. Import recording (.MPG) into Lossless Cut
3. Only video plays, no sound. Try converting to a compatible format. Still no sound. 

### Expected behavior

Video has sound

### Actual behavior

Video has no sound

**Comment by mifi** [comment]
Please use the other issue template, as this seems to be an issue with a particular file
