### ISSUE TITLE
transition improvement

### ISSUE THREAD

**Issue by randomguyxoxo** [mifi/lossless-cut#1562]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

is it possible to have transition like fade in (black) / fade out during merging of two clips

https://user-images.githubusercontent.com/130574897/231481367-317b8bd5-df3c-428b-b7b2-4964ca23a8d4.mp4

**Comment by mifi** [comment]
> - [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
