### ISSUE TITLE
The tracks selection dialog on Export page does not display/appear on foreground but on background

### ISSUE THREAD

**Issue by slrslr** [mifi/lossless-cut#1566]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Linux

### Steps to reproduce

On Linux (have Debian with KDE) AppImage [3.54.0](https://github.com/mifi/lossless-cut/releases/tag/v3.54.0) when i drag and drop some video file, click "Export", click the number of tracks (in order to try to disable one), the track selection dialog appear on background, is not visible. To see it, i have to close export dialog.

### Expected behavior

It would be handy if i can still customize tracks from export page and track selection (or any other in future) dialogs being on foreground. I think that in previous version it worked.

### Actual behavior

Tracks selection dialog does not appear on Export page. Is on background.

**Comment by mifi** [comment]
dup #1540
