### ISSUE TITLE
suggestion:take all the best from the related projects

### ISSUE THREAD

**Issue by killaz47** [mifi/lossless-cut#157]
there's a choice needs to be added in losslesscut: which decoding/encoding software to be used by losslesscut (https://github.com/Nevcairiel/LAVFilters, or any other, instead of the current built-in ffmpeg (https://alternativeto.net/software/ffmpeg/)), or a different player perhaps (f.e. other html5 player, Windows Media Player HTML5 Extension for Chrome, mplayer kmplayer, vlc, mpc)
this (but not limited to) open-source ffmpeg-related software could help to improve losslesscut (as being described above):
https://alternativeto.net/software/vidcutter/

this is a suggestion that comes from the [https://github.com/mifi/lossless-cut/issues/151](url) issue that can't be fixed on the user side.

**Comment by mifi** [comment]
Needs to be something that is very stable, without bugs, supports alot of codecs , and integrates easily with Electron. I'm not aware of any project that does this. HTML5 video player is all of the above except it does not support alot of codecs.

**Comment by killaz47** [comment]
then perhaps this one should be used as html5 player, [https://www.radiantmediaplayer.com/](url) [https://www.radiantmediaplayer.com/guides/working-with-electron.html](url) as the problem that has been told a few months before (no audio during playback in losslesscut player) remains including the 2,3.0

**Comment by killaz47** [comment]
mostly nothing is for free these days

**Comment by mifi** [comment]
I think more things than ever before are free in the software industry these days. Everything that lossless cut is based on is free and open source. It's a great time to be a developer :)

**Comment by killaz47** [comment]
this one https://electronjs.org/apps/phreshplayer looks promising, except that it says that there's no .ac3 support.

**Comment by mifi** [comment]
Does it support other codecs or formats like h265?

**Comment by mifi** [comment]
not much actionable here, closing this
