### ISSUE TITLE
Move file on editless export

### ISSUE THREAD

**Issue by Valvify** [mifi/lossless-cut#1575]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Sometimes, when processing files in a batch, I want to export an entire video file without making any cuts or other edits. However, pressing the export button on these videos still goes through the whole 'export' process and takes time.

Would it be possible to simply move the file to the working directory if such an export is done?

**Comment by mifi** [comment]
Why do you want to simply move the file? I think you could use other tools like windows explorer for this?

**Comment by Valvify** [comment]
Oh I know that XD.

I mean that if someone doesn’t make any cuts, edits, or other changes to a
file in a batch list, the program currently spends a lot of time “cutting”
the entire file even when no changes were made.

Yes it would be faster to open the file explorer and move the file over
manually, but it would be *even* faster if the program detected that no
edits were made and just move the file over itself. It sort of hurts my
workflow of cutting many videos when I have to use the file explorer to
move a video that I don’t wish to make any changes to.

**Comment by mifi** [comment]
I think some people would want to run their files thru ffmpeg even without any cuts or edits, in case the files were recorded in a non-standard way, has some issue or they cannot play back on some players, then running it thru ffmpeg will sometimes «fix» the files.

**Comment by Valvify** [comment]
Ah, that makes sense :)
