### ISSUE TITLE
Open Dialog shows boxes instead of text

### ISSUE THREAD

**Issue by Drest** [mifi/lossless-cut#1578]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Linux

### Steps to reproduce

Running latest Snap version on Linux fedora 6.2.9-200.fc37.x86_64

File menu > Open

### Expected behavior

Dialog should show text

### Actual behavior

Open Dialog shows boxes instead of text (like when a font is missing)
![Screenshot from 2023-04-20 15-27-51](https://user-images.githubusercontent.com/16182304/233478116-0227b9b7-5e0b-40a4-81e8-10c0b8a176b4.png)

Also, attempting to drag and drop a video onto the main window has no effect.

Files open just fine from the dialog and the app works great. I just can't see which file I'm opening.

### Share log

"Send problem report" text:
```
No error occurred.

{
  "state": {
    "filePath": "",
    "externalFilesMeta": {},
    "mainStreams": [],
    "copyStreamIdsByFile": {},
    "cutSegments": [
      {}
    ],
    "mainFileFormatData": {},
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "separate"
  },
  "platform": "linux",
  "version": "3.49.0"
}
```

Dev Console output:
```
Version 3.49.0
ffmpeg.js:65 ffmpeg -hide_banner -f lavfi -i 'nullsrc=s=256x256:d=1' -f null -
DevTools failed to load source map: Could not parse content for file:///snap/losslesscut/114/resources/app.asar/node_modules/cue-parser/lib/cue.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///snap/losslesscut/114/resources/app.asar/node_modules/cue-parser/lib/command.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///snap/losslesscut/114/resources/app.asar/node_modules/cue-parser/lib/cuesheet.js.map: Unexpected end of JSON input
﻿
```

**Comment by mifi** [comment]
Maybe youre missing some fonts? Does it happen with other apps like chromium also?

**Comment by dericke** [comment]
I had the same problem and was able to fix it (at least for now) by following the steps [here](https://askubuntu.com/a/1228809), replacing `chromium` with `losslesscut`.

**Comment by mifi** [comment]
Not much I can do about this, as it's most likely a linux/electron issue. feel free to suggest fix if you find one.
