### ISSUE TITLE
If I cut in nc mode, the first few seconds of the video will get stuck.

### ISSUE THREAD

**Issue by ZonSamuel** [mifi/lossless-cut#158]
![无标题](https://user-images.githubusercontent.com/17244763/57797933-1eeddb00-777e-11e9-9419-ddfa1524d578.png)

**Comment by ZonSamuel** [comment]
I try to ffmpeg.exe  
ffmpeg.exe -i "a.mp4" -ss 00:00:01.890 -t 10.610 -c copy  "b.mp4"
Same problem.

**Comment by mifi** [comment]
This is a limitation with ffmpeg
