### ISSUE TITLE
SmartCut : not frame accurate from TS file

### ISSUE THREAD

**Issue by AlexBelz** [mifi/lossless-cut#1585]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

Hello,
inthe context of a TS file workflow, with Frame Accurate Preview = "Slow (no audio)" , 
I can see that export (whatever TS or mp4) do not start/cut on the proper frame, even if "smart cut" is activated. 

- It contains some pictures before the Input cutting point.
- Worse, the first seconds of the file lag at playout using VLC.
- Even worse, during these lagging seconds I can see that pictures are mixed.
- For instance, if I have in TS frames ... **AD1;AD2**:Intro1;Intro2;Intro3;Intro4...,  after export i get starting frames  ... **AD1**;Intro2;**AD2**;Intro3;Intro4...

See attached screen capture of the mp4 export : we can clearly see the picture mess-up : 
Advert thumbnail (orange guy) inside the movie (yellow thumbnails).
![BadSmartCutExport](https://user-images.githubusercontent.com/55029991/234498175-379775c6-4682-462a-b54f-47c7ee55fa8c.JPG)

### Expected behavior

Pictures should not be inverted/messed-up. 

### Actual behavior

Pictures are inverted/messed-up.

**Comment by mifi** [comment]
does it work if you first try to remux from ts to mp4, then use smart cut on the mp4 file?

**Comment by AlexBelz** [comment]
Hi @mifi, 
I've tried , using LossLessCut to convert (rewrap) the *.TS into a *.mp4, and then only do the Frame Accurate (Smart Cut) edition, to trim the start/end of the movie.
The swapped pictures have disappeared, great !!
Unfortunately, the starting/ending picture do not correspond to what I asked on the GUI.
(starting and ending pictures are wrong by approximatively + 2 pictures late).

Do you need the source TS file and the start/ending cuting point , so that you can investigate ?

**Comment by mifi** [comment]
hi

> (starting and ending pictures are wrong by approximatively + 2 pictures late).

you mean it's off by 2 frames only? If so, this is a known issue that I haven't been able to solve yet. see #126 and #1216

**Comment by AlexBelz** [comment]
Hello @mifi, yes, only 2 frames off.

**Comment by mifi** [comment]
Ok, like I mentioned, it is a known problem, and I don't know how to solve it yet. I will close this issue because it seems to be the same as the other mentioned issues. I will add a point about it in #1216 and #126
