### ISSUE TITLE
Is there the way to found out the missing frames on the timeline easy and quickly

### ISSUE THREAD

**Issue by BoscoFZ** [mifi/lossless-cut#1587]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Sometime i edit a video recording from the livestream. Some of them will be missing some frames because the signal not always OK when recording. Ex: The current frame time is 00:35:05.020 then click the next key icon the frame time will be 00:35:05.520 this is OK then click the next key icon again the frame time will jump to 00:36:00.020 because the frame from 00:35:05.520 to 00:36:00.020 can't record (this is what i am talking about the missing frame)  . Can you help me the way to found out the missing frames on the timeline easy and quickly to cut. Thank you so much.

**Comment by mifi** [comment]
Hi. If your file is corrupted and is missing frames, then I don't know how to seek to a frame that does not exist.

**Comment by BoscoFZ** [comment]
I see. Thank you for your support
