### ISSUE TITLE
Smart cropping (experimental) causes videos to lose quality (not before)

### ISSUE THREAD

**Issue by WILLIANWILLOFC** [mifi/lossless-cut#1592]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 11

### Steps to reproduce

o erro é com o recurso "Corte inteligente (experimental)" antes das ultimas versões ele cortava mas não arruinava a resolução do video, nas ultimas versões do aplicativo quando esta opção é ativada o vídeo após a edição fica com "ruidos" a resolução cai e fica parecendo um video de baixa resolução... (Antes isso não acontecia) fora esse problema o aplicativo está funcionando muito bem no windows 11...

### Expected behavior

que o video após a edição saia na mesma resolução (como acontecia antes)

### Actual behavior

o video perde qualidade de resolução...

**Comment by mifi** [comment]
> the error is with the feature "Smart cut (experimental)" before the latest versions it cut but did not ruin the resolution of the video, in the latest versions of the application when this option is activated the video after editing is "noisy" the resolution drops and it looks like a low resolution video... (Before this did not happen) apart from this problem the application is working very well in windows 11...

**Comment by mifi** [comment]
please use this instead: https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml
