### ISSUE TITLE
Can't Convert MPV or MP4 to MOV, HEVC, H.264, and others.

### ISSUE THREAD

**Issue by quinnnuge** [mifi/lossless-cut#1593]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with a different kind of file to confirm that the problem is related to just this file.
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Steps to reproduce

Try opening an MPV or MP4 file in Lossless Cut and convert it to MOV, HEVC, H.264, and other similar formats. Lossless Cut will give an error message and say to try a different file and file type but nothing has been working when using different files or file formats. The two formats I tried were MP4 and MPV. I tried this with multiple different files and nothing has been working. The files are recorded from OBS using the NVIDIA NVENC AV1 encoder and are outputted to MPV.

### Expected behavior

Lossless Cut should convert the MPV or MP4 files to MOV, HEVC, or H.264 and create a new file in the folder.

### Actual behavior

Lossless Cut gives an error message stating 

Unable to export this file
Try one of the following before exporting again:
Select a different output Format (matroska and mp4 support most codecs)
Disable unnecessary Tracks
Try both Normal cut and Keyframe cut
Set a different Working directory
Try with a Different file
See Help menu
If nothing helps, you can send an Error report

### Provide an error report

Error: Command failed with exit code 1: C:\Program Files\LosslessCut-win-x64\resources\ffmpeg.exe -hide_banner -i C:\Users\Quinn\Videos\OBS\Actually the Final Cut.mkv -map 0:0 -c:0 copy -map 0:1 -c:1 copy -map_metadata 0 -movflags +faststart -default_mode infer_no_subs -ignore_unknown -f mov -y C:\Users\Quinn\Videos\OBS\Actually the Final Cut-00.00.00.000-00.03.02.484.mov
[libaom-av1 @ 000001ab30090780] 3.5.0-242-g6ed0c7a32
Input #0, matroska,webm, from 'C:\Users\Quinn\Videos\OBS\Actually the Final Cut.mkv':
  Metadata:
    ENCODER         : Lavf59.27.100
  Duration: 00:03:02.48, start: 0.000000, bitrate: 1586 kb/s
  Stream #0:0: Video: av1 (Main), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 60 fps, 60 tbr, 1k tbn
    Metadata:
      DURATION        : 00:03:02.484000000
  Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp
    Metadata:
      title           : Track1
      DURATION        : 00:03:02.464000000
[mov @ 000001ab324306c0] av1 only supported in MP4 and AVIF.
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:1 -- 
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
    Last message repeated 1 times
    at makeError (C:\Program Files\LosslessCut-win-x64\resources\app.asar\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Program Files\LosslessCut-win-x64\resources\app.asar\node_modules\execa\index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "ffmpegExperimental": false,
    "preserveMovData": false,
    "movFastStart": true,
    "preserveMetadataOnMerge": false,
    "filePath": "C:\\Users\\Quinn\\Videos\\OBS\\Actually the Final Cut.mkv",
    "fileFormat": "mov",
    "externalFilesMeta": {},
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "av1",
        "codec_long_name": "Alliance for Open Media AV1",
        "profile": "Main",
        "codec_type": "video",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1080,
        "closed_captions": 0,
        "film_grain": 0,
        "has_b_frames": 0,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 9,
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "refs": 1,
        "r_frame_rate": "60/1",
        "avg_frame_rate": "60/1",
        "time_base": "1/1000",
        "start_pts": 0,
        "start_time": "0.000000",
        "extradata_size": 20,
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "DURATION": "00:03:02.484000000"
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/1000",
        "start_pts": 0,
        "start_time": "0.000000",
        "extradata_size": 5,
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "title": "Track1",
          "DURATION": "00:03:02.464000000"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "C:\\Users\\Quinn\\Videos\\OBS\\Actually the Final Cut.mkv": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {}
    ],
    "mainFileFormatData": {
      "filename": "C:\\Users\\Quinn\\Videos\\OBS\\Actually the Final Cut.mkv",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "matroska,webm",
      "format_long_name": "Matroska / WebM",
      "start_time": "0.000000",
      "duration": "182.484000",
      "size": "36180308",
      "bit_rate": "1586125",
      "probe_score": 100,
      "tags": {
        "ENCODER": "Lavf59.27.100"
      }
    },
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "separate",
    "outSegTemplate": "${FILENAME}-${CUT_FROM}-${CUT_TO}${SEG_SUFFIX}${EXT}"
  },
  "platform": "win32",
  "version": "3.54.0"
}

### Share log

DevTools failed to load source map: Could not parse content for file:///C:/Program%20Files/LosslessCut-win-x64/resources/app.asar/vite-dist/main.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Program%20Files/LosslessCut-win-x64/resources/app.asar/vite-dist/signals.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Program%20Files/LosslessCut-win-x64/resources/app.asar/vite-dist/core.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Program%20Files/LosslessCut-win-x64/resources/app.asar/vite-dist/realtime.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Program%20Files/LosslessCut-win-x64/resources/app.asar/vite-dist/cue.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Program%20Files/LosslessCut-win-x64/resources/app.asar/vite-dist/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Program%20Files/LosslessCut-win-x64/resources/app.asar/vite-dist/node.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Program%20Files/LosslessCut-win-x64/resources/app.asar/vite-dist/utf8.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Program%20Files/LosslessCut-win-x64/resources/app.asar/vite-dist/match.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Program%20Files/LosslessCut-win-x64/resources/app.asar/vite-dist/unicode.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Program%20Files/LosslessCut-win-x64/resources/app.asar/vite-dist/mbcs.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Program%20Files/LosslessCut-win-x64/resources/app.asar/vite-dist/sbcs.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Program%20Files/LosslessCut-win-x64/resources/app.asar/vite-dist/iso2022.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Program%20Files/LosslessCut-win-x64/resources/app.asar/vite-dist/command.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Program%20Files/LosslessCut-win-x64/resources/app.asar/vite-dist/cuesheet.js.map: Unexpected end of JSON input

**Comment by mifi** [comment]
hi. can you try to select MP4 as output format? or Matroska? It seems like MOV doesn't support your AV1 codec.

**Comment by quinnnuge** [comment]
It will let me do MP4 and MPV (matroska) but nothing else. Sorry for not
clarifying that in my issue report. I appreciate your quick response and I
love your application.

**Comment by mifi** [comment]
Great! Unfortunately there's nothing I can do about this, because it seems that MOV does not support AV1 (either it's a technical impossibility or ffmpeg does not support that). So you'll have to use a format like mp4 or matroska.
