### ISSUE TITLE
REQUEST: full convert to friendly codec

### ISSUE THREAD

**Issue by kmatzdorf7** [mifi/lossless-cut#160]
Per issue #94 , the idea behind "convert to friendly codec" seems to be to create a smaller 'preview' file with no audio and fixed small resolution, which is a great feature.  However, it would also be useful to have a full convert feature.  That is, convert the file to a friendly codec while also preserving the audio and the original resolution.  The resulting files could be played/edited by a wider variety of tools, without losing resolution and audio.  Maybe have "full convert to friendly codec (very slow)" or something like that.

**Comment by mifi** [comment]
What is the use case for this?

**Comment by kmatzdorf7** [comment]
In order to play and edit video clips with older tools that do not support newer codecs.  For example, QuickTime Pro.

**Comment by mifi** [comment]
Ahh, so you mean create a huge file with H264 lossless quality like `-crf 0`?

**Comment by mifi** [comment]
This one is now implemented.
