### ISSUE TITLE
Can't export the significant part of a YT PM4

### ISSUE THREAD

**Issue by bianchifan** [mifi/lossless-cut#1604]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Linux

### Steps to reproduce

Open a YT file: "Orianthi  'First Time Blues' The Token Lounge  February 9, 2023_Full-HD.mp4"
Determine thelast  keyframe of the significant part (no black screen)
Try to export

### Expected behavior

export the main part

### Actual behavior

"...cannot export...."

then the screen below
![Bildschirmfoto vom 2023-05-17 23-32-24](https://github.com/mifi/lossless-cut/assets/17491743/29a11433-d5fb-4c5f-a9b2-b638ebd93e86)

### Share log

Error: Command failed with exit code 1: /opt/LosslessCut-linux-x64/resources/ffmpeg -hide_banner -i /run/user/1000/gvfs/mtp:host=SAMSUNG_SAMSUNG_Android_R52N40GZSZM/Interner Speicher/Video/Orianthi  'First Time Blues' The Token Lounge  February 9, 2023_Full-HD.mp4 -t 400.40000 -map 0:0 -c:0 copy -map 0:1 -c:1 copy -map_metadata 0 -movflags +faststart -default_mode infer_no_subs -ignore_unknown -f mp4 -y /run/user/1000/gvfs/mtp:host=SAMSUNG_SAMSUNG_Android_R52N40GZSZM/Interner Speicher/Video/Orianthi  'First Time Blues' The Token Lounge  February 9, 2023_Full-HD-00.00.00.000-00.06.40.400-seg1.mp4
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/run/user/1000/gvfs/mtp:host=SAMSUNG_SAMSUNG_Android_R52N40GZSZM/Interner Speicher/Video/Orianthi  'First Time Blues' The Token Lounge  February 9, 2023_Full-HD.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.35.101
  Duration: 00:09:54.52, start: 0.000000, bitrate: 2446 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 2310 kb/s, 29.97 fps, 29.97 tbr, 30k tbn (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
      vendor_id       : [0][0][0][0]
/run/user/1000/gvfs/mtp:host=SAMSUNG_SAMSUNG_Android_R52N40GZSZM/Interner Speicher/Video/Orianthi  'First Time Blues' The Token Lounge  February 9, 2023_Full-HD-00.00.00.000-00.06.40.400-seg1.mp4: Operation not supported
    at makeError (/opt/LosslessCut-linux-x64/resources/app.asar/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/opt/LosslessCut-linux-x64/resources/app.asar/node_modules/execa/index.js:118:26)
    at async file:///opt/LosslessCut-linux-x64/resources/app.asar/build/static/js/main.f18f3ad4.js:2:307402
    at async file:///opt/LosslessCut-linux-x64/resources/app.asar/build/static/js/main.f18f3ad4.js:2:309155
    at async file:///opt/LosslessCut-linux-x64/resources/app.asar/build/static/js/main.f18f3ad4.js:2:2382031

{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "filePath": "/run/user/1000/gvfs/mtp:host=SAMSUNG_SAMSUNG_Android_R52N40GZSZM/Interner Speicher/Video/Orianthi  'First Time Blues' The Token Lounge  February 9, 2023_Full-HD.mp4",
    "fileFormat": "mp4",
    "externalFilesMeta": {},
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1080,
        "closed_captions": 0,
        "film_grain": 0,
        "has_b_frames": 1,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 40,
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "field_order": "progressive",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "id": "0x1",
        "r_frame_rate": "30000/1001",
        "avg_frame_rate": "30000/1001",
        "time_base": "1/30000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 17833816,
        "duration": "594.460533",
        "bit_rate": "2310792",
        "bits_per_raw_sample": "8",
        "nb_frames": "17816",
        "extradata_size": 44,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "ISO Media file produced by Google Inc.",
          "vendor_id": "[0][0][0][0]"
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "44100",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "id": "0x2",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/44100",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 26218496,
        "duration": "594.523719",
        "bit_rate": "127999",
        "nb_frames": "25604",
        "extradata_size": 16,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "eng",
          "handler_name": "ISO Media file produced by Google Inc.",
          "vendor_id": "[0][0][0][0]"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "/run/user/1000/gvfs/mtp:host=SAMSUNG_SAMSUNG_Android_R52N40GZSZM/Interner Speicher/Video/Orianthi  'First Time Blues' The Token Lounge  February 9, 2023_Full-HD.mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {
        "end": 400.4
      },
      {
        "start": 400.4
      }
    ],
    "mainFileFormatData": {
      "filename": "/run/user/1000/gvfs/mtp:host=SAMSUNG_SAMSUNG_Android_R52N40GZSZM/Interner Speicher/Video/Orianthi  'First Time Blues' The Token Lounge  February 9, 2023_Full-HD.mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "594.524000",
      "size": "181798785",
      "bit_rate": "2446310",
      "probe_score": 100,
      "tags": {
        "major_brand": "isom",
        "minor_version": "512",
        "compatible_brands": "isomiso2avc1mp41",
        "encoder": "Lavf58.35.101"
      }
    },
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "separate"
  },
  "platform": "linux",
  "version": "3.46.2"
}

**Comment by mifi** [comment]
hmm, the error message from ffmpeg seems to be "Operation not supported". can't find much on google on that message. Could you try with ffmpeg 6 and see if it helps?
