### ISSUE TITLE
Video quality gets degraded when "smart cutting" (experimental)

### ISSUE THREAD

**Issue by WILLIANWILLOFC** [mifi/lossless-cut#1606]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with a different kind of file to confirm that the problem is related to just this file.
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Steps to reproduce

after choosing the cut segments in the video and activating the "smart cut" option and exporting the video, the video comes out of losslesscut in low resolution, that is: the .mp4 video loses resolution after being edited.

### Expected behavior

the expected behavior would be that the video after export remained at the same resolution / without losing resolution.

### Actual behavior

with the "smart cut" option activated on export, the video comes out of lossllesscut in low resolution, that is: the .mp4 video loses resolution after export...

### Provide an error report

don't need bug report because the problem is in video resolution after export.

**Comment by mifi** [comment]
What's the input resolution? what's the output resolution? does this happen with all kinds of files?

**Comment by WILLIANWILLOFC** [comment]
> Qual é a resolução de entrada? Qual é a resolução de saída? Isso acontece com todos os tipos de arquivos?

happens at any resolution. in the highest resolution videos like 4K it is almost imperceptible... até agora só testei com arquivos .mp4

**Comment by WILLIANWILLOFC** [comment]
> Qual é a resolução de entrada? Qual é a resolução de saída? Isso acontece com todos os tipos de arquivos?

I'll try to explain better: for example: if I edit and export a video whose input is (1280x720) with the smart cut option enabled, the video is exported in resolution (1280x720) but the image quality of the exported video is lower compared to the original video.

**Comment by mifi** [comment]
Ah, ok, so the resolution doesn't change, but the quality changes.

There has been some discussion around this in #126 - in particular check: https://github.com/mifi/lossless-cut/issues/126#issuecomment-1347909058

**Comment by xiaxiaxiaojie** [comment]
您好，请问在用智能剪辑模式剪辑视频的时候，视频质量会下降是指从剪辑点到下一个关键帧的视频部分会下降，还是整个视频的质量都会受到影响呀？

**Comment by xiaxiaxiaojie** [comment]
Hello, when editing a video in smart editing mode, will the video quality decrease? Does it mean that the part of the video from the editing point to the next key frame will decrease, or will the quality of the entire video be affected?

**Comment by mifi** [comment]
hi. that is correct. only the part of the video from the editing point to the next key frame will decrease. the rest of the video will not be encoded.
