### ISSUE TITLE
[Request] Please add version number to release

### ISSUE THREAD

**Issue by b2gcoder** [mifi/lossless-cut#161]
Thank you for producing a great utility!  Would it be possible to add an About Screen under 'Help' with a version number?

**Comment by mifi** [comment]
You can see thee version under "About", is it not enough?

**Comment by EvWoN** [comment]
> 
> 
> You can see thee version under "About", is it not enough?

There is no "About" anywhere in the UI (afaik). Traditionally it is placed in the "Help" menu bar item.
![Screenshot_59](https://user-images.githubusercontent.com/28621760/60757808-2d10e880-9fc4-11e9-9138-5b70f4c25a4a.png)

👍

**Comment by mifi** [comment]
Yes i just found out that the About menu was only shown on Mac. Have now added it to win/linux also in the next version
