### ISSUE TITLE
Feature Request: Seek controls in line with most media players

### ISSUE THREAD

**Issue by Delerium** [mifi/lossless-cut#1611]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Is there any chance we can get media controls that are closer in line with media players such as SMPlayer, media player classic, etc?
Example from SMPlayer:
Customizable fixed seek times:
![image](https://github.com/mifi/lossless-cut/assets/3868689/c6788ec7-1486-44ef-b42a-aa8f6dc4e69b)
With keyboard shortcuts configurable for each one:
![image](https://github.com/mifi/lossless-cut/assets/3868689/b0e7a2cc-0020-49c0-bd39-dcf2ed2b0622)

Explanation why:
The way it works now in LosslessCut, you have two keyboard options to seek, normal and by 1% of timeline.  Normal is fine for the left and right arrows to do small movements, but when you are working with videos that could range from 5 minutes to 6 hours, 1% is such a HUGE change that it has become useless to me.  That means my only source of control is the small seek, which doesn't help much to traverse a 6 hour video.  

That leaves seek acceleration, which is way too hard to control due to not having a "top speed" so without watching the timeline, you have no clue how fast you are going, and end up skipping most of the video because your eyes are glued to the actual video not the timeline.

The basics of it is that when I am seeking through a video to cut up, I would use each seek distance for different purposes... 1 minute to traverse a large video quickly and consistently regardless of total video length. 5 second to traverse points between the 1 minute marks to find the general area I want to cut, and 1 second to get in the exact position I want to cut. 
(edited title to reflect that this is a feature request not a bug. lol)

**Comment by mifi** [comment]
gotcha. I think it could be solved by allowing an additional set of keys that can be bound to additional customisable intervals (currently there's just one - default 1 sec, customisable). i'm closing this to keep issue count down but im referring to your issue here: https://github.com/mifi/lossless-cut/issues/604#issuecomment-1585811890

**Comment by mifi** [comment]
next version will have 3 total customisable seek speeds
