### ISSUE TITLE
Clicking inactive item in the list of segments in right sidebar cause activation, not moving to segment position on timeline

### ISSUE THREAD

**Issue by slrslr** [mifi/lossless-cut#1612]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Linux

### Steps to reproduce

Hello, on Linux Debian + KDE I have latest AppImage [3.54.0](https://github.com/mifi/lossless-cut/releases/tag/v3.54.0)
When i have multiple segments in the video, i right click for example 3rd one and click menu entry to select only this segment. Then after i am finished with the segment (i exported it), i wanted to move to one of the following (currently inactive) segments by double clicking it in the right sidebar of segment list, it activate the segment instead of moving the cursor to the right time on the timeline of this selected segment. To do it i need to double click again. Why not making it the way that single double click activates and also moves cursor to right place on timeline?

I expect that most people does not know about doubleclick action to cause activate/deactivate, i am personally using doubleclick on segment to move playback cursor to proper position, and it does not work (have to do double click two times).

### Expected behavior

Mouse double click action should jump to right place on the timeline so i can use jump to start/end of the segment buttons to fix the cut points.

### Actual behavior

Mouse double click action just activates inactive segment.

**Comment by mifi** [comment]
I agree that this is not a desirable behavior. will change it so that it doesn't just activate inactive segment
