### ISSUE TITLE
Can't open files on external drive

### ISSUE THREAD

**Issue by dsgiigh** [mifi/lossless-cut#1613]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Linux

### Steps to reproduce

It is not possible to open a file on an external mounted disk drive, either by opening from the menu or dragging the file into the application. I always get permission errors.

### Expected behavior

It should open the files.

### Actual behavior

Files do not open. When trying to open from the file/open menu, popup says "Could not read the contents of <disk name> / Error opening directory <name>: Permission denied"
![Screenshot from 2023-06-03 13-24-38](https://github.com/mifi/lossless-cut/assets/804184/f1be62de-2aca-4bd8-8b64-f272db803c04)

When dragging a file onto the application, error is "You do not have permission to access this file"
![Screenshot from 2023-06-03 13-29-11](https://github.com/mifi/lossless-cut/assets/804184/a8e93a18-a2a7-4718-9e37-61d6c0e12cb4)

This only occurs with files from external drives.

### Share log

index.jsx:14 Version 3.49.0
ffmpeg.js:65 ffmpeg -hide_banner -f lavfi -i 'nullsrc=s=256x256:d=1' -f null -
App.jsx:1969 userOpenFiles
App.jsx:1970 /home/dan/Downloads/video1538431929 (1) (1).mov
App.jsx:1545 loadMedia /home/dan/Downloads/video1538431929 (1) (1).mov /home/dan/Videos/cut undefined
App.jsx:1549 state reset
ffmpeg.js:50 ffprobe -of json -show_chapters -show_format -show_entries stream -i '/home/dan/Downloads/video1538431929 (1) (1).mov' -hide_banner
App.jsx:659 onDurationChange 238.026667
ffmpeg.js:50 ffprobe -v error -read_intervals '0%30' -show_packets -select_streams 0 -show_entries 'packet=pts_time,flags' -of json '/home/dan/Downloads/video1538431929 (1) (1).mov'
App.jsx:1969 userOpenFiles
App.jsx:1970 /media/dan/bbcru/bgat/FLb/eightball.mp4
DevTools failed to load source map: Could not parse content for file:///snap/losslesscut/114/resources/app.asar/node_modules/cue-parser/lib/cue.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///snap/losslesscut/114/resources/app.asar/node_modules/cue-parser/lib/command.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///snap/losslesscut/114/resources/app.asar/node_modules/cue-parser/lib/cuesheet.js.map: Unexpected end of JSON input
App.jsx:1969 userOpenFiles
App.jsx:1970 /home/dan/Dropbox/Mapping exercise.mp4
App.jsx:1545 loadMedia /home/dan/Dropbox/Mapping exercise.mp4 /home/dan/Videos/cut undefined
App.jsx:1549 state reset
ffmpeg.js:50 ffprobe -of json -show_chapters -show_format -show_entries stream -i '/home/dan/Dropbox/Mapping exercise.mp4' -hide_banner
App.jsx:659 onDurationChange 354.951995
ffmpeg.js:50 ffprobe -v error -read_intervals '0%30' -show_packets -select_streams 0 -show_entries 'packet=pts_time,flags' -of json '/home/dan/Dropbox/Mapping exercise.mp4'
App.jsx:1969 userOpenFiles
App.jsx:1970 /media/dan/bbcru/Mapping exercise.mp4

No error occurred.

{
  "state": {
    "filePath": "",
    "externalFilesMeta": {},
    "mainStreams": [],
    "copyStreamIdsByFile": {},
    "cutSegments": [
      {}
    ],
    "mainFileFormatData": [],
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "separate",
    "outSegTemplate": "${FILENAME}-${CUT_FROM}-${CUT_TO}${SEG_SUFFIX}${EXT}"
  },
  "platform": "linux",
  "version": "3.49.0"
}

**Comment by mifi** [comment]
I think see #937 - maybe in particular https://github.com/mifi/lossless-cut/issues/937#issuecomment-1046063665

**Comment by mifi** [comment]
i don't think there's anything actionable here for me
