### ISSUE TITLE
Option to disable auto filling Potplayer bookmarks (.Pbf) like in version 3.43.0?

### ISSUE THREAD

**Issue by snwefly** [mifi/lossless-cut#1619]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Same Pbf when imported to different versions of lossless-cut

3.43.0
![image](https://github.com/mifi/lossless-cut/assets/88805679/81174905-e976-4d33-ad27-4c2faf46e62c)

3.54.0

![image](https://github.com/mifi/lossless-cut/assets/88805679/57d6e854-4746-4689-b9d2-4dcd27e8e6fb)

New versions of lossless-cut always fills the gap and looks messy due to that, is there any way to disable it on the newer versions?

Thanks

**Comment by mifi** [comment]
this has been discussed here: #993 - unfortunately i didn't have time to prioritise yet
