### ISSUE TITLE
Video and audio drifting when importing into video editor

### ISSUE THREAD

**Issue by Libroru** [mifi/lossless-cut#1622]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 11

### Steps to reproduce

We exported a 1h timeline to mp4 with keyframe cut enabled.

### Expected behavior

No audio drift at all.

### Actual behavior

Audio is drifting when importing into video editor (like Vegas, Davinci) but is fine in VLC.

I already commented on this on another issue but figured I might want to open another one.

**Comment by mifi** [comment]
You have this problem with all kinds of files, right?
