### ISSUE TITLE
Export Screen: "disable thumbnail track" improvements

### ISSUE THREAD

**Issue by Mrnofish** [mifi/lossless-cut#1628]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Whenever a thumbnail track is present, LosslessCut emits a warning in the Export Dialog.

### 1. One-click disable thumbnail track

To disable the thumbnail track, it is necessary to click on the Tracks link, then on the Track itself, then close the Track Dialog and go back to the Export screen.

However, since LosslessCut knows which one is the thumbnail track, it could disable it by itself if prompted.

1. There could be a button in the Export screen that disables the thumbnail track.
2. And a switch to automatically disable that track whenever it is present.

### 2. Improve the warning logic

I've noticed that when the export only contains one segment, or LosslessCut is asked to separate multiple segments, rather than merge, it is NOT necessary to remove the thumbnail track.

This happens systematically, at least with the formats I usually work with, so the application could only emit the warning and/or remove the track automatically, when the user requests an operation that is actually affected, and not the others.

**Comment by mifi** [comment]
> ### 1. One-click disable thumbnail track

This makes sense, at least a hotkey button.

> ### 2. Improve the warning logic

what you're saying is that removing the thumbnail track is **only** necessary when merging/concatenating?

**Comment by Mrnofish** [comment]
That is, in my experience and with all the caveats from my previous post, what happens.

I cannot vouch for all the scenarios under the sun, though, so it would seem smart to include some sort of failsafe so that the unsuspecting user doesn't get stuck.

**Comment by mifi** [comment]
have now implemented a new "Keep or discard thumbnail tracks" action that can be bound to keyboard a shortcut (works the same as the existing "Keep or discard audio tracks")
