### ISSUE TITLE
Sequenced file cutting

### ISSUE THREAD

**Issue by t3dotgg** [mifi/lossless-cut#1629]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

This is a somewhat weird usecase and I'm fully expecting the response to be "lul we're not doing this", but here goes...

Many cameras and recording methods will "segment" recordings at a given cap. My new camera breaks files up when they hit 200gb. To apply my markers as cuts, my workflow is now:
1. Drag the chunked videos (usually just 2) to LosslessCut
2. Hit "merge" (which takes...awhile)
3. re-open LosslessCut with merged file
4. Finally apply my cuts and re-transcode again

I haven't looked too much into how the cuts are applied under the hood, but my (admittedly ancient) ffmpeg knowledge leads me to believe it's possible to do this in one pass 😅

**Comment by mifi** [comment]
Not sure exactly what you need. Do you want to merge and cut files in the same operation instead of two operations, in order to speed up the workflow? If so, that sounds more like NLE functionality which is not possible in losslesscut as of now (see #976)

**Comment by t3dotgg** [comment]
> ...merge and cut in same operation?

Yes that's what I meant. Fits under the greater NLE issue, will close this.
