### ISSUE TITLE
"Whoops! ffmpeg was unable to cut this video." Error

### ISSUE THREAD

**Issue by mosawake** [mifi/lossless-cut#163]
Hello! Today I encountered this error while trying to cut a file. File is too large to share so I'll copy/post the console.

"Whoops! ffmpeg was unable to cut this video. It may be of an unknown format or codec combination"

>/Applications/LosslessCut.app/Contents/Resources/app.asar/renderer.js:880 Version 2.2.0
/Applications/LosslessCut.app/Contents/Resources/app.asar/renderer.js:303 Load {filePath: "/Users/mla/Documents/Files/Anime/Cu…it chap)/ReCH(1920x1080 x264 ALAC 10bit chap).mp4", html5FriendlyPath: undefined}
/Applications/LosslessCut.app/Contents/Resources/app.asar/ffmpeg.js:215 getFormat /Users/mla/Documents/Files/Anime/RCH/ReCH(1920x1080 x264 ALAC 10bit chap).mp4
/Applications/LosslessCut.app/Contents/Resources/app.asar/ffmpeg.js:220 formats mov,mp4,m4a,3gp,3g2,mj2
/Applications/LosslessCut.app/Contents/Resources/app.asar/ffmpeg.js:226 fileType detected format {"ext":"mp4","mime":"video/mp4"}
/Applications/LosslessCut.app/Contents/Resources/app.asar/ffmpeg.js:61 Cutting from 380.795197 to 456.954237
/Applications/LosslessCut.app/Contents/Resources/app.asar/ffmpeg.js:74 ffmpeg -ss 380.795197 -i /Users/mla/Documents/Files/Anime/RCH/ReCH(1920x1080 x264 ALAC 10bit chap).mp4 -t 76.15904 -avoid_negative_ts make_zero -acodec copy -vcodec copy -scodec copy -map 0 -map_metadata 0 -f mp4 -y /Users/mla/Documents/Files/Anime/RCH/ReCH(1920x1080 x264 ALAC 10bit chap).mp4-00.06.20.795-00.07.36.954.mp4
/Applications/LosslessCut.app/Contents/Resources/app.asar/renderer.js:271 stdout: 
App.cutClick @ /Applications/LosslessCut.app/Contents/Resources/app.asar/renderer.js:271
_tickCallback @ internal/process/next_tick.js:188
async function (async)
App.cutClick @ /Applications/LosslessCut.app/Contents/Resources/app.asar/renderer.js:218
da @ /Applications/LosslessCut.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:14
ka @ /Applications/LosslessCut.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:15
la @ /Applications/LosslessCut.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:15
xa @ /Applications/LosslessCut.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:17
Ba @ /Applications/LosslessCut.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:18
za @ /Applications/LosslessCut.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:18
Ea @ /Applications/LosslessCut.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:21
Gd @ /Applications/LosslessCut.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:84
Th @ /Applications/LosslessCut.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:231
Ob @ /Applications/LosslessCut.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:39
Jd @ /Applications/LosslessCut.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:86
Wh @ /Applications/LosslessCut.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:231
Id @ /Applications/LosslessCut.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:85
/Applications/LosslessCut.app/Contents/Resources/app.asar/renderer.js:272 stderr: ffmpeg version 4.1.3-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple LLVM version 10.0.1 (clang-1001.0.46.3)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/mla/Documents/Files/Anime/RCH/ReCH(1920x1080 x264 ALAC 10bit chap).mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41isomM4A 
    creation_time   : 2014-02-14T07:44:18.000000Z
    encoder         : qaac 2.22, CoreAudioToolbox 7.9.8.3, Apple Lossless Encoder
  Duration: 00:44:56.03, start: 0.000000, bitrate: 10447 kb/s
    Chapter #0:0: start 0.000000, end 18.485000
    Metadata:
      title           : Chapter 1
    Chapter #0:1: start 18.485000, end 97.697000
    Metadata:
      title           : Chapter 2
    Chapter #0:2: start 97.697000, end 192.458000
    Metadata:
      title           : Chapter 3
    Chapter #0:3: start 192.458000, end 274.540000
    Metadata:
      title           : Chapter 4
    Chapter #0:4: start 274.540000, end 335.635000
    Metadata:
      title           : Chapter 5
    Chapter #0:5: start 335.635000, end 410.977000
    Metadata:
      title           : Chapter 6
    Chapter #0:6: start 410.977000, end 427.760000
    Metadata:
      title           : Chapter 7
    Chapter #0:7: start 427.760000, end 447.880000
    Metadata:
      title           : Chapter 8
    Chapter #0:8: start 447.880000, end 570.236000
    Metadata:
      title           : Chapter 9
    Chapter #0:9: start 570.236000, end 675.007000
    Metadata:
      title           : Chapter 10
    Chapter #0:10: start 675.007000, end 742.575000
    Metadata:
      title           : Chapter 11
    Chapter #0:11: start 742.575000, end 842.174000
    Metadata:
      title           : Chapter 12
    Chapter #0:12: start 842.174000, end 858.591000
    Metadata:
      title           : Chapter 13
    Chapter #0:13: start 858.591000, end 937.236000
    Metadata:
      title           : Chapter 14
    Chapter #0:14: start 937.236000, end 1160.959000
    Metadata:
      title           : Chapter 15
    Chapter #0:15: start 1160.959000, end 1415.013000
    Metadata:
      title           : Chapter 16
    Chapter #0:16: start 1415.013000, end 1437.035000
    Metadata:
      title           : Chapter 17
    Chapter #0:17: start 1437.035000, end 1510.475000
    Metadata:
      title           : Chapter 18
    Chapter #0:18: start 1510.475000, end 1672.470000
    Metadata:
      title           : Chapter 19
    Chapter #0:19: start 1672.470000, end 1762.594000
    Metadata:
      title           : Chapter 20
    Chapter #0:20: start 1762.594000, end 1805.970000
    Metadata:
      title           : Chapter 21
    Chapter #0:21: start 1805.970000, end 1859.657000
    Metadata:
      title           : Chapter 22
    Chapter #0:22: start 1859.657000, end 1877.976000
    Metadata:
      title           : Chapter 23
    Chapter #0:23: start 1877.976000, end 1890.655000
    Metadata:
      title           : Chapter 24
    Chapter #0:24: start 1890.655000, end 1939.337000
    Metadata:
      title           : Chapter 25
    Chapter #0:25: start 1939.337000, end 1997.328000
    Metadata:
      title           : Chapter 26
    Chapter #0:26: start 1997.328000, end 2083.081000
    Metadata:
      title           : Chapter 27
    Chapter #0:27: start 2083.081000, end 2159.390000
    Metadata:
      title           : Chapter 28
    Chapter #0:28: start 2159.390000, end 2234.799000
    Metadata:
      title           : Chapter 29
    Chapter #0:29: start 2234.799000, end 2250.381000
    Metadata:
      title           : Chapter 30
    Chapter #0:30: start 2250.381000, end 2306.637000
    Metadata:
      title           : Chapter 31
    Chapter #0:31: start 2306.637000, end 2315.313000
    Metadata:
      title           : Chapter 32
    Chapter #0:32: start 2315.313000, end 2321.919000
    Metadata:
      title           : Chapter 33
    Chapter #0:33: start 2321.919000, end 2332.229000
    Metadata:
      title           : Chapter 34
    Chapter #0:34: start 2332.229000, end 2391.689000
    Metadata:
      title           : Chapter 35
    Chapter #0:35: start 2391.689000, end 2441.038000
    Metadata:
      title           : Chapter 36
    Chapter #0:36: start 2441.038000, end 2494.024000
    Metadata:
      title           : Chapter 37
    Chapter #0:37: start 2494.024000, end 2563.494000
    Metadata:
      title           : Chapter 38
    Chapter #0:38: start 2563.494000, end 2571.902000
    Metadata:
      title           : Chapter 39
    Chapter #0:39: start 2571.902000, end 2667.998000
    Metadata:
      title           : Chapter 40
    Chapter #0:40: start 2667.998000, end 2695.983333
    Metadata:
      title           : Chapter 41
    Stream #0:0(und): Video: h264 (High 10) (avc1 / 0x31637661), yuv420p10le(tv), 1920x1080, 8938 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      creation_time   : 2014-02-14T07:44:18.000000Z
      handler_name    : Encoded by Alkasa
      encoder         : AVC Coding
    Stream #0:1(jpn): Audio: alac (alac / 0x63616C61), 48000 Hz, stereo, s32p (24 bit), 1505 kb/s (default)
    Metadata:
      creation_time   : 2014-02-14T07:44:18.000000Z
    Stream #0:2(und): Data: bin_data (tx3g / 0x67337874), 0 kb/s
    Metadata:
      creation_time   : 2014-02-14T07:44:18.000000Z
      handler_name    : L-SMASH Text Media Handler
[mp4 @ 0x7fdae4004000] Could not find tag for codec alac in stream #1, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
  Stream #0:2 -> #0:2 (copy)
    Last message repeated 1 times

**Comment by pedzed** [comment]
I can confirm for Windows 10 64-bit using LosslessCut 2.2.0.

Note that I have install FFMPEG manually in the past:
```
$ ffmpeg -version
ffmpeg version 4.1.3 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 8.3.1 (GCC) 20190414
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
libavutil      56. 22.100 / 56. 22.100
libavcodec     58. 35.100 / 58. 35.100
libavformat    58. 20.100 / 58. 20.100
libavdevice    58.  5.100 / 58.  5.100
libavfilter     7. 40.101 /  7. 40.101
libswscale      5.  3.100 /  5.  3.100
libswresample   3.  3.100 /  3.  3.100
libpostproc    55.  3.100 / 55.  3.100
```

**Comment by VL4DST3R** [comment]
Same here, previous version works fine with said file.

**Comment by jraby** [comment]
Same here on 2.2.0.
These files used to work (and still work) with v1.14.

```
stderr: ffmpeg version 4.1.3-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5b4f4c0] st: 0 edit list: 1 Missing key frame while searching for timestamp: 3003
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5b4f4c0] st: 0 edit list 1 Cannot find an index entry before timestamp: 3003.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5b4f4c0] Referenced QT chapter track not found
Guessed Channel Layout for Input Stream #0.1 : stereo
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/jean/Pictures/P5250370.MOV':
  Metadata:
    major_brand     : qt  
    minor_version   : 537986816
    compatible_brands: qt  
    creation_time   : 2019-05-25T09:57:58.000000Z
  Duration: 00:00:58.56, start: 0.000000, bitrate: 29900 kb/s
    Stream #0:0(jpn): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, smpte170m), 1920x1080 [SAR 1:1 DAR 16:9], 28278 kb/s, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc (default)
    Metadata:
      creation_time   : 2019-05-25T09:57:58.000000Z
      timecode        : 10:46:33;20
    Stream #0:1(jpn): Audio: pcm_s16le (sowt / 0x74776F73), 48000 Hz, stereo, s16, 1536 kb/s (default)
    Metadata:
      creation_time   : 2019-05-25T09:57:58.000000Z
      timecode        : 10:46:33;20
    Stream #0:2(jpn): Data: none (tmcd / 0x64636D74), 0 kb/s (default)
    Metadata:
      creation_time   : 2019-05-25T09:57:58.000000Z
      timecode        : 10:46:33;20
[mp4 @ 0x5b56640] Could not find tag for codec pcm_s16le in stream #1, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
```

**Comment by mifi** [comment]
So it works in 2.2.0? or only in master? I thought that commit was included in 2.2.0

**Comment by mifi** [comment]
Ahh you're right, i commited that AFTER the release. will release a 2.3.0

**Comment by jraby** [comment]
Thanks for the new release.
Sorry for the confusion, I edited my message after I posted it initially and the result wasn't really clear.

**Comment by mifi** [comment]
Does it work in 2.3.0?

**Comment by ArnulfKoch** [comment]
I have the same problem with 2.3.0 with 100 Mbit mp4 files from the Sony A6400.
VLC says the Codec is: H264 - MPEG-4 AVC (part 10) (avc1)
Resolution: 3840x2160
Framerate: 25

**Comment by TechManiacHD** [comment]
I am having the same issue on v2.3.0
Sony FDR-AX700 4k/30p 100Mbps

<img width="667" alt="Screenshot_1" src="https://user-images.githubusercontent.com/24764145/61499568-a85c9c00-a9bf-11e9-91ab-26074d0074af.png">

**Comment by cykl** [comment]
Doesn't work in 2.3.0

```
ffmpeg   -ss 2 -i /xxx/GOPR0883.MP4  -t 3 -avoid_negative_ts make_zero -acodec copy -vcodec copy -scodec copy  -map 0   -map_metadata 0 -ignore_unknown  -write_tmcd 0 -f mp4 -y /xxx/GOPR0883.MP4.1
ffmpeg version 4.1.4 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9 (GCC)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' --extra-ldflags='-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld ' --extra-cflags=' ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-fontconfig --enable-frei0r --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libcdio --enable-libdrm --enable-indev=jack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmp3lame --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzvbi --enable-avfilter --enable-avresample --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-libmfx --enable-runtime-cpudetect
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55885ca60c80] unsupported color_parameter_type aclc
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/xxx/GOPR0883.MP4':
  Metadata:
    major_brand     : avc1
    minor_version   : 0
    compatible_brands: avc1isom
    creation_time   : 2014-03-20T22:25:45.000000Z
    firmware        : HD3.20.01.09
  Duration: 00:00:13.98, start: 0.000000, bitrate: 15637 kb/s
    Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuvj420p(pc), 1280x720 [SAR 1:1 DAR 16:9], 15214 kb/s, 50 fps, 50 tbr, 50k tbn, 100 tbc (default)
    Metadata:
      creation_time   : 2014-03-20T22:25:45.000000Z
      handler_name    :  Ambarella AVC
      encoder         : Ambarella AVC encoder
      timecode        : 22:25:45:00
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2014-03-20T22:25:45.000000Z
      handler_name    :  Ambarella AAC
      timecode        : 22:25:45:00
    Stream #0:2(eng): Data: none (tmcd / 0x64636D74), 0 kb/s (default)
    Metadata:
      creation_time   : 2014-03-20T22:25:45.000000Z
      timecode        : 22:25:45:00
[mp4 @ 0x55885ca75000] Could not find tag for codec none in stream #2, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
  Stream #0:2 -> #0:2 (copy)
    Last message repeated 1 times
```

Replacing `-f mp4` by `-f mov`, as @jraby suggested, worked for me too.

**Comment by mifi** [comment]
I have implemented in the latest version an option to choose output format.
See also https://github.com/mifi/lossless-cut/issues/173
