### ISSUE TITLE
Export Ignores Deleted Segments

### ISSUE THREAD

**Issue by hockinsk** [mifi/lossless-cut#1632]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 11

### Steps to reproduce

Slice to create Segment. Delete Segment. Export. Play in media player, but deleted segment still plays

### Expected behavior

The deleted segment showing the trashcan shouldn't be part of the exported playback.

### Actual behavior

Deleted segment is still included playback

### Share log

![image](https://github.com/mifi/lossless-cut/assets/1609513/70be9bda-7e86-40d1-ae22-e001716cf719)

**Comment by mifi** [comment]
> * [x]  Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)

https://github.com/mifi/lossless-cut/blob/master/issues.md#cutting-times-are-not-accurate

**Comment by hockinsk** [comment]
Apologies, I've been using for a year or so and must have been lucky that this never happened before. Thanks for reply, amazing software btw!
