### ISSUE TITLE
Edited language metadata tags are ignored

### ISSUE THREAD

**Issue by hjschmidt99** [mifi/lossless-cut#1635]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

I use a video (mp4) with one or more audio tracks
Edit metadata tags for an audio track
Change the language tag as desired (from deu to eng in my case)
Close the Edit-Track-Dialog with "Done"
The track list still shows the original language deu
Same on the exported file

### Expected behavior

The edited language tag should be applied an used

### Actual behavior

The edited language tag is ignored

**Comment by mifi** [comment]
I tried the same thing just now, changed from eng to deu. Although the track list in losslesscut shows `eng`, when exporting, and then reopening the exported file, it has correctly changed to `deu`. Is it possible to share a  file that reproduces this behavior?

**Comment by hjschmidt99** [comment]
Here are 16 sec of a movie that won't take the metadata change:

https://github.com/mifi/lossless-cut/assets/81195606/ad4b8f9b-6d4d-4f0c-a84e-87517c753027

Many thanks for providing LosslessCut and your quick response here ...

**Comment by mifi** [comment]
thanks . i tried with your file and it works for me:
<img width="870" alt="Screenshot 2023-06-29 at 12 46 53" src="https://github.com/mifi/lossless-cut/assets/402547/5e763c2f-e708-4eb5-9fb1-bd66511c0626">

maybe you forgot to click the green check icon before exporting:

<img width="470" alt="Screenshot 2023-06-29 at 12 47 32" src="https://github.com/mifi/lossless-cut/assets/402547/b095d5d8-fa64-4f48-ae81-9bf07bfa7d47">

**Comment by hjschmidt99** [comment]
Thanx, my mistake...
