### ISSUE TITLE
merged file can't properly play

### ISSUE THREAD

**Issue by python152** [mifi/lossless-cut#164]
latest released version. the cutting and merging seems fine without errors (mkv).
the segments itself are also fine, but the merged file can't properly play back: it got stuck during the the transition from one to another.  I have tried both 'nc' and 'kc' - don't seem to make a difference. Are there any suggestions? I am not sure what additional debug info can be provided.

**Comment by mifi** [comment]
Need some more info about the file you are trying to cut. maybe u can share it?

**Comment by mifi** [comment]
Can you try again with newest version of losslesscut ? reopen if still issue
