### ISSUE TITLE
Crash when open video

### ISSUE THREAD

**Issue by SplitGemini** [mifi/lossless-cut#1641]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

File menu -> Open -> Select video file -> Lossless cut crashes

### Expected behavior

Not crash.

### Actual behavior

File menu -> Open -> Select video file -> Lossless cut crashes
It doesn't happen every time, the frequency is about 10%, it feels like it happens randomly, nothing special

### Share log

No error occurred.

{
  "state": {
    "ffmpegExperimental": false,
    "preserveMovData": false,
    "movFastStart": true,
    "preserveMetadataOnMerge": false,
    "filePath": "I:\\stream\\part-001.mp4",
    "fileFormat": "mp4",
    "externalFilesMeta": {},
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1080,
        "closed_captions": 0,
        "film_grain": 0,
        "has_b_frames": 1,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 42,
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "field_order": "progressive",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "id": "0x1",
        "r_frame_rate": "60/1",
        "avg_frame_rate": "60/1",
        "time_base": "1/15360",
        "start_pts": 492,
        "start_time": "0.032031",
        "duration_ts": 55295985,
        "duration": "3599.999023",
        "bit_rate": "6018386",
        "bits_per_raw_sample": "8",
        "nb_frames": "216000",
        "extradata_size": 54,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "VideoHandler",
          "vendor_id": "[0][0][0][0]"
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "44100",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "id": "0x2",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/44100",
        "start_pts": 750,
        "start_time": "0.017007",
        "duration_ts": 158759912,
        "duration": "3599.998005",
        "bit_rate": "310485",
        "nb_frames": "155039",
        "extradata_size": 5,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "SoundHandler",
          "vendor_id": "[0][0][0][0]"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "I:\\stream\\part-001.mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {}
    ],
    "mainFileFormatData": {
      "filename": "I:\\stream\\part-001.mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.017007",
      "duration": "3600.032000",
      "size": "2854872918",
      "bit_rate": "6344105",
      "probe_score": 100,
      "tags": {
        "major_brand": "isom",
        "minor_version": "512",
        "compatible_brands": "isomiso2avc1mp41",
        "encoder": "Lavf59.27.100"
      }
    },
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "merge",
    "outSegTemplate": "${FILENAME}-${CUT_FROM}-${CUT_TO}${SEG_LABEL}${EXT}"
  },
  "platform": "win32",
  "version": "3.54.0"
}

**Comment by mifi** [comment]
what do you mean by "crashes"?

**Comment by SplitGemini** [comment]
> what do you mean by "crashes"?

The window is closed immediately after I click the "Open" button.Without prompting I went back to my desktop.

**Comment by SplitGemini** [comment]
Mostly occur when disk is busy.

**Comment by SplitGemini** [comment]
cmdline error print
```
[1112:0715/175300.778:ERROR:cache_util_win.cc(20)] Unable to move the cache: �ܾ����ʡ� (0x5)
[1112:0715/175300.779:ERROR:cache_util_win.cc(20)] Unable to move the cache: �ܾ����ʡ� (0x5)
[1112:0715/175300.809:ERROR:disk_cache.cc(205)] Unable to create cache
[1112:0715/175300.824:ERROR:gpu_disk_cache.cc(673)] Gpu Cache Creation failed: -2
[1112:0715/175300.824:ERROR:disk_cache.cc(205)] Unable to create cache
[1112:0715/175300.825:ERROR:gpu_disk_cache.cc(673)] Gpu Cache Creation failed: -2
[14884:0715/175307.242:ERROR:cache_util_win.cc(20)] Unable to move the cache: �ܾ����ʡ� (0x5)
[14884:0715/175307.244:ERROR:disk_cache.cc(205)] Unable to create cache
[16764:0715/175500.794:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is
```

**Comment by SplitGemini** [comment]
It is most likely caused by multiple instances, **do not use multiple instances**.

https://github.com/electron/electron/issues/2157

**Comment by SplitGemini** [comment]
I need the ability to export in the background so I can move on to the next job while exporting

**Comment by mifi** [comment]
that's an interesting observation, thanks for reporting. I will update the docs to make sure to reflect the fact that it's not really supported

**Comment by SplitGemini** [comment]
> It is most likely caused by multiple instances, **do not use multiple instances**.
> 
> [electron/electron#2157](https://github.com/electron/electron/issues/2157)

Update: It is not caused by this reason, it is opening the video again on top of the already opened video (showing You opened a new file. What do you want to do?), there is a probability that it will crash, but I manually close it first, and then open the video , it won't

**Comment by mifi** [comment]
you mean open the same video that you already opened?
- by file->Open or drag-drop? 
- what did you answer to `You opened a new file. What do you want to do?` does it crash after you answer that?
- does it happen with other files too?

**Comment by SplitGemini** [comment]
* by file->Open
* 
When ![image](https://github.com/mifi/lossless-cut/assets/34861918/8fb0ccbc-a13a-41dc-82c9-fab68b598011) showed, it crashes before I can press the button
* Yes, not limited to the same file

**Comment by mifi** [comment]
1. does the same happen if you drag-drop instead of file->open?
2. how long does it take until it crashes, after the dialog has been shown?
3. are you 100% sure you are not running another instance of losslesscut in the background?
4. do you see any error message or log printed at the exact time when it crashes?

**Comment by SplitGemini** [comment]
After I deleted the file in `%appdata%\LosslessCut\GPUCache`, it can't be reproduced now, and I will reply when this happens again.

**Comment by mifi** [comment]
ok, feel free to reopen with reproducible steps. closing for now
