### ISSUE TITLE
Batch edit default audio track

### ISSUE THREAD

**Issue by Ninko85** [mifi/lossless-cut#1644]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Hi,
I have many files where I just want to change the default audio track.
It would be nice to be able to change the default audio track and have that applied to all imported files.

Thanks

**Comment by mifi** [comment]
Hi. I think this is a job for ffmpeg. Shouldn't be too hard with some simple bash scripting. It's the first time I've heard this feature request, so I think it's kind of niche and not probably something that will be implemented in LosslessCut unless requested by more people, so I'm closing this for now. Thanks!
