### ISSUE TITLE
Tracks Selection is covered by Export options 

### ISSUE THREAD

**Issue by KirinRyuuri** [mifi/lossless-cut#1645]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 11

### Steps to reproduce

I try to cut a video with 3 tracks, and I just need 2 tracks
so I :
1. edit this video
2. press [ Export ] button
3. press [ Keeping in 3 tracks ] text to the right of [ Input has 3 tracks ]
4. The **tracks selection panel** is not on the top, it's under the **Export options panel**

### Expected behavior

4. The **tracks selection panel** is on the top, I can select which track I need, just like 3.45.0.0 ( old version )

### Actual behavior

4. I can't see the **tracks selection panel** unless I turn off the **Export options panel**

**Comment by mifi** [comment]
already fixed. will be out in the next version #1566
