### ISSUE TITLE
Wrong version in Linux 64bit dist

### ISSUE THREAD

**Issue by Suor** [mifi/lossless-cut#165]
I am downloading this - https://github.com/mifi/lossless-cut/releases/download/v2.2.0/LosslessCut-linux-x64.zip and it has `2.0.9` in version.

**Comment by mifi** [comment]
Same problem in 2.3.0?

**Comment by FabioBeneditto** [comment]
Version file says v2.0.18

**Comment by mifi** [comment]
Ohh! This is not the version of LosslessCut, this is the version of Electron. I don't know why it creates that file, but it shouldn't be a big problem. I will add app version in the help menu.
