### ISSUE TITLE
Avoid re-rendering sections

### ISSUE THREAD

**Issue by jtagcat** [mifi/lossless-cut#1655]
I've noticed I re-render my projects progressively multiple times. This means I press Export, then add a cut, and Export again. With 2-digit hour projects, It feels dumb to re-render all sections again.

LosslessCut is mostly stateless. The most reasonable way I see is to check for existing filenames before overwriting + adding a default-off 'overwrite' option. In theory, this could expand to rendering pervious sections when a new section cut start is placed.

Another improvement for my specific workflow:  I can continue editing after pressing Export, but the icon stays somewhat in the way. How about minimizing the rendering icon to the top bar after a few seconds?

**Comment by mifi** [comment]
related: https://github.com/mifi/lossless-cut/issues/916  https://github.com/mifi/lossless-cut/commit/9161278e54ac32aa7205249bcadd44b1206e3374

**Comment by jtagcat** [comment]
`enableOverwriteOutput: false` results in nothing being done and an error, even if a new section is added before.

**Comment by mifi** [comment]
yep, i understand what you want is to have a mode where existing files will be left as-is but new files will be written, while exporting, right?
