### ISSUE TITLE
Error dialog self-closes

### ISSUE THREAD

**Issue by LorenPechtel** [mifi/lossless-cut#1658]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

Merge damaged files

### Expected behavior

A while back I complained about it **silently** failing on some files.  This was soon fixed, upon completion it gives a warning about the file size not being as expected.  Unfortunately, this shows up on the merge complete notice--which soon self-closes.  That means if you're not paying attention to it you won't see the error--come back to it and there's absolutely no difference between merge successful and merge unsuccessful.

If there's a warning leave the box open!

### Actual behavior

See expected behavior.

### Share log

Not relevant

**Comment by mifi** [comment]
that's a good point, the only problem is that some people might not want a modal to block their whole flow just because of a warning. so need to find a way to still show it as a toast, but not auto-close it after x seconds.

**Comment by mifi** [comment]
ok will remove the timer in the toast if there are warnings

**Comment by LorenPechtel** [comment]
I'd sure prefer my flow blocked rather than miss an almost certain failure warning.
