### ISSUE TITLE
Doesn't work on Ubuntu 19.04

### ISSUE THREAD

**Issue by Suor** [mifi/lossless-cut#166]
```bash
$ lsb_release -a
LSB Version:	core-10.2019031300ubuntu1-noarch:security-10.2019031300ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
$ ./LosslessCut 
./LosslessCut: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```

**Comment by sharipovmarat** [comment]
+ same problem on clean Ubuntu 18.04

**Comment by mifi** [comment]
Thanks for researching. Hopefully this will be fixed in electron or ubuntu in the future

**Comment by mifi** [comment]
I heard some reports it may be working now, so we can close this?

**Comment by cesar-santos** [comment]
Great tool, @mifi !!! It is really simple to perform what you need to, good job (y)
Regarding this dependency, would it be possible to suggest a fix to user? I've though of some different ways:
- on "npm install", execute a script to look for libgconf-2-4 on user's system. If not there, install it;
- on Release versions, I've thought on two possibilities:
-- alert the user this lib is missing, and ask him/her to install it;
-- look for the library, and if missing, install it;
-- include this library on the final package.

Pardon me not providing solutions, but I'm not Electron-savvy... but in case you have ideas on how to implement it, any suggestions you can give of sources to study it or where to look at it, I'll be glad to send a Pull Request.

Thanks,
Cesar.

**Comment by mifi** [comment]
Is it the same problem with 2.5.0?

**Comment by mifi** [comment]
reopen if still an issue
