### ISSUE TITLE
"Set file modification date/time of output files to" does not work on Win11

### ISSUE THREAD

**Issue by moggaz** [mifi/lossless-cut#1661]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 11

### Steps to reproduce

Take two or more files, try to merge.

I always use version 3.37.0 because it was the last version where you could still quickly merge files.
Every version after that has to do 6.000.000 steps to merge.
But now that I'm using Windows 11, I noticed that it uses the current time and date when merging even though I set something different. Unfortunately, this does not work even with the current version 3.54.0. 

Unfortunately, a quick (2 click, I now need to hit a tiny little symbol....) merge is then also no longer possible :(

### Expected behavior

DateTime is now

### Actual behavior

DateTime must be datetime of files

**Comment by mifi** [comment]
Maybe a hotkey would make it easier to merge?

Are you saying you want output file to have modified date set to current clock time?

**Comment by moggaz** [comment]
When I set Windows11 (I think it is default) that when I merge two files it should take the date of the files and not the current date, but it takes the current date. Tested under Windows 10 in a Vm, it works. In Windows 11 it does not.
Hotkey I can try, I did not know yet, thanks.

**Comment by mifi** [comment]
Do you see any error message like `Failed to set output file modified time` pop up in the developer tools log? Unfortunately I don't have windows 11 avail right now so it's hard to look into this issue, but I'm planning on making a github actions windows vm for testing

**Comment by moggaz** [comment]
I do not understand all this but I attached a picture. the source file is from 14.07, today I merge them and although I did not set it in the options, today's date is taken and not that of the source files.

![merge](https://github.com/mifi/lossless-cut/assets/86011609/8e59e42f-7c2f-4fbd-a16a-f6d0a0ef426c)

**Comment by moggaz** [comment]
hey, were you able to readjust and fix the error?

**Comment by mifi** [comment]
no, i haven't been able to reproduce the problem, and it works on other platforms

**Comment by moggaz** [comment]
will you fix the error promptly ? otherwise I have to look for a better program that goes with the times (windows 11)...

**Comment by mifi** [comment]
it's not so trivial for me to setup a windows 11 vm under apple mac silicon m2, but once i do i will look into it. there's no other way for me to fix this issue without the help of others

**Comment by mifi** [comment]
it's probably not related to ffmpeg.
This is the code that does the job of transferring timestamps:

https://github.com/mifi/lossless-cut/blob/9c633cbbdf51a8f9ba8eaf5b816f7d25dceb5832/src/util.js#L95

not sure why it doesn't work for you on win11. I've never heard this issue reported by anyone else.

**Comment by mifi** [comment]
if you know how to run node.js code, you could try to run this code on a file and see if it works.

**Comment by mifi** [comment]
or provide log output from the developer console in losslesscut (more info: https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&projects=&template=file-issue.yml)

**Comment by moggaz** [comment]
it doesn't seem to work like that, but I've only known node for 2 minutes.
Can you tell me what must be in the js file when I want to read the file 1.mp4?

![grafik](https://github.com/mifi/lossless-cut/assets/86011609/3644f114-893f-47d8-a0ff-517de2e4cfde)

**Comment by moggaz** [comment]
anyone here who can help the programmer with this problem ?

**Comment by mifi** [comment]
Ok I've finally managed to install Windows 11 developer preview in a VM on my macbook m2, and when cutting I see that "Modified date" does indeed get correctly set when exporting/merging, see screenshot:

<img width="395" alt="Screenshot 2023-08-17 at 20 31 04" src="https://github.com/mifi/lossless-cut/assets/402547/7edeb530-424d-4280-ba01-4ae428c2ea1d">

looking at your screenshot however, I can see "Erstelldatum". I believe in english it translates to "created date", so you are not talking about modified date, but "created date". I believe that's not possible to set "created date" of a file in windows, so I'm closing this.
