### ISSUE TITLE
merge

### ISSUE THREAD

**Issue by shwang92** [mifi/lossless-cut#1668]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 11

### Steps to reproduce

after i use motion blur (teknoblur) individually to a video file it is fine. however, once i merge it. it cuts off after 2 secs after the clip OR if i edit it, it wont replay. but i can play it back on windows media. 

### Expected behavior

it should just replay fine

### Actual behavior

the full video will not play after i edit by cutting or merging after i using a motion blur

**Comment by mifi** [comment]
what is motion blur? I think you might be on the wrong project's github. this is losslesscut

**Comment by shwang92** [comment]
It just won’t replay correctly on lossless cut after I edit it whether it’s just cutting or merging two videos On Jul 26, 2023, at 4:47 PM, Mikael Finstad ***@***.***> wrote:﻿
what is motion blur? I think you might be on the wrong project's github. this is losslesscut

**Comment by mifi** [comment]
unfortunately there's not enough info here for me to help. maybe try this instead https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&projects=&template=file-issue.yml
