### ISSUE TITLE
"Lossless keyframe," rather than "Nearest keyframe"

### ISSUE THREAD

**Issue by Rehaan13** [mifi/lossless-cut#167]
Awesome program, thanks!

Rather than jumping to the nearest keyframe (which means the selected segment might LOSE out on a few frames/second of footage), could you:

1) Select the nearest EARLIER keyframe for the IN point
2) Select the nearest LATER keyframe for the OUT point

This would prevent users from losing out on an important bit of footage when chopping up their files in LosslessCut.

Better to have an extra few seconds than a few seconds less!

**Comment by Rehaan13** [comment]
Adding to this idea...

Have the option to buffer cuts with "X" number of additional frames / seconds.

Eg. If i'm using this software to cut up raw clips before taking them into Premiere for an edit, I'd like some additional lead-in / out for transitions, leeway, etc.

If i could set an options like "Save an additional ____ seconds before & after each selected clip" - that would be amazing.

**Comment by mifi** [comment]
I agree! Have not yet implemented parsing of keyframes because it turns out to be a bit slow operation. But we could like you say work around it by adding a few sec before/after cut. Just need to determine how many sec..

**Comment by Rehaan13** [comment]
> Just need to determine how many sec..

I think users use your program for many different reasons. Some want exact cuts, while others want to just trim a few gigabytes off their raw video, and then import the result into an editing program.

I think having "Settings" in the program with options like these (eg. closest keyframe outside the selection vs add X seconds buffer) would be a good start, and way for the future to cater to many use-cases.

**Comment by mifi** [comment]
After some experimentation it seems that the current behavior when using "keyframe cut", is indeed that it will jump to the nearest keframe **before** the desired cutpoint, so you will not lose anything.
The newest version now shows keyframes on the timeline and lets you zoom in. so you can experiment with cutting near keyframes.

**Comment by mifi** [comment]
See #330
