### ISSUE TITLE
Autoreload on file changed

### ISSUE THREAD

**Issue by johannesCmayer** [mifi/lossless-cut#1674]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

I am having the use case that I concatenate to the current MKV video file that LosslessCut is displaying. I would like it that LosslessCut automatically updates and shows the newly recorded video content. Basically, I record a mkv file using OBS and then use ffmpeg to append the recorded file to the file that is currently open in LosslessCut.

Right now I need to kill  LosslessCut and then reopen it for it to recognize the change. 

If it would be much easier to just have a hotkey to do this, this would be nice too. The main disadvantage right now is that I always lose settings such as playback speed and playback position. Restarting LosslessCut also takes a few moments, which is a bit annoying.

**Comment by mifi** [comment]
So if you close the file (ctrl+w) and reopen it, it doesn't recognise the changes to the file?

**Comment by johannesCmayer** [comment]
This has also the disadvantage of losing the playback position and the playback speed setting. Also, it is even slower than my terminal script of killing LosslessCut completely. Because now I need to close the file and then drag the file again into the LosslessCut window.

Another related thing that might be nice is if the lossless card could open, display and edit files that are being appended to, like mpv. I can record some video in OBS and at the same time play back the file using mpv. And then I would normally pause OBS and then use MPV to preview what I have recorded so far.

**Comment by mifi** [comment]
I managed to find a way to reload the file from disk on command, but it's a bit difficult to detect when this happens in a cross-platform way. And I'm afraid it's going to cause unexpected problems if we auto-reload. As a first version I can make a custom keyboard shortcut to reload the file. Then it will reload the file with its new duration and preserve playback position.

**Comment by johannesCmayer** [comment]
Nice, thank you. I did not expect this be fixed so fast, or at all actually. I will try in the next release, as the current nightly doesn't start for me.
