### ISSUE TITLE
Show both time and frame count in timecode

### ISSUE THREAD

**Issue by mgunyho** [mifi/lossless-cut#1677]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Currently, it is possible to choose one of the following options for the timestamp shown on the timeline: frame count, milliseconds with decimal fraction, or milliseconds with frame fraction. This can be chosen by changing the "in timecode show" under settings.

I would like another option: millisecond fractions *and* frames. So the timeline would display something like `00:00:08.989 (539)`. I would like to see both the millisecond and frame information at the same time.

As a sidenote, I think this setting should be a drop-down menu instead of a toggle, since it has more than two options. It can be hard to tell when I've cycled through all possibilities. Also, "in timecode show" is a bit of a confusing name, it should IMO be called "Timecode format" or "Show time on timeline as".

**Comment by mifi** [comment]
i think it makes sense to always show timecode *and* total frame numbers in the timeline

**Comment by mgunyho** [comment]
Cool, thanks! Does this mean that the ["in timecode show: frame counts" option](https://github.com/mifi/lossless-cut/blob/master/src/components/Settings.jsx#L52) is redundant?

**Comment by mifi** [comment]
No, because that option still controls other places like segment list, output file names etc
