### ISSUE TITLE
Automatically start NEW cut segment after a segment is selected (Auto + after I O)

### ISSUE THREAD

**Issue by Rehaan13** [mifi/lossless-cut#168]
For a really smooth and fast workflow, I'd love to just use the I and O (segment start & segment end) keys to mark out multiple segments in one shot.

What tends to currently happen is that i forget to hit C+ (new segment) and as a result not only do i not start a new segment, but i also end up botching up the earlier selected segment once i hit "I" again.

**Would be great if:**

There was an "auto new segment" option, which meant that any "O" followed by an "I" would actually be automatically registered as a "C+ I"

Thanks

**Comment by mifi** [comment]
implemented in newest
