### ISSUE TITLE
Merging two .mp4 files results in a file the same duration as the first file.

### ISSUE THREAD

**Issue by Monkeor** [mifi/lossless-cut#1680]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

I have 2 .mp4 files, one 3.67gb and one 2.90gb, which I'm trying to merge. I import them and hit merge, but the software gives me this error showing that the output file is much shorter than the sum of the two input files.
![image](https://github.com/mifi/lossless-cut/assets/46661228/5bc45895-4ba2-403c-98ef-9f7f94abb547)

I tried disabling all tracks except for the video tracks (though it seemed like going to disable the audio track of the second clip re-enabled the audio track of the first clip and vice-versa?), I tried every setting of avoid_negative_ts in the export settings, and I've tried exporting both videos and merging those instead. Nothing has worked.

### Expected behavior

The two files should merge into one single file instead of not doing that.

### Actual behavior

Final file is just a copy of the first file with the same duration.

**Comment by mifi** [comment]
that's odd. how does your merge options look like? also, can you provide some more info? see https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&projects=&template=file-issue.yml

**Comment by Monkeor** [comment]
I just tried exporting each half separately through LosslessCut after disabling the audio tracks (the only track that the files had other than the video) and trying to merge those, but the same error occurs.

These are my merge options:
![image](https://github.com/mifi/lossless-cut/assets/46661228/8bd412c9-abb9-4407-a7a9-9d5e7a7ccb0a)

This is the error report from Help->Report and Error:
```
No error occurred.

{
  "state": {
    "ffmpegExperimental": false,
    "preserveMovData": false,
    "movFastStart": true,
    "preserveMetadataOnMerge": false,
    "filePath": "",
    "externalFilesMeta": {},
    "mainStreams": [],
    "copyStreamIdsByFile": {},
    "cutSegments": [
      {}
    ],
    "mainFileFormatData": {},
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "separate",
    "outSegTemplate": "${FILENAME}-${CUT_FROM}-${CUT_TO}${SEG_SUFFIX}${EXT}"
  },
  "platform": "win32",
  "version": "3.54.0"
}
```

This is the log from the Javascript console:
![image](https://github.com/mifi/lossless-cut/assets/46661228/7c795ce8-b604-4619-a5f4-49923d63d68e)

This is a GDrive link to the two files I'm trying to merge:
https://drive.google.com/drive/folders/1gmDQ3h_8pcpRmVF93MtXhuQ6FhZZBtMS?usp=sharing

I hope this covers everything you're looking for, but if not, let me know.

**Comment by Monkeor** [comment]
![image](https://github.com/mifi/lossless-cut/assets/46661228/a1948dde-4d36-4404-af04-1f463243819c)
I tried running the command through Losslesscut's console, but it doesn't seem to work. How exactly do I run this command to merge the files myself?

**Comment by mifi** [comment]
You have to install ffmpeg and run it from  cmd

**Comment by Monkeor** [comment]
![image](https://github.com/mifi/lossless-cut/assets/46661228/058ed4ef-dff4-4fe5-b813-1037b08d1143)
I hate to come back with what might be an unrelated issue, but the `protocol_whitelist` flag doesn't seem to be working for `fd` and I don't know why. The full command I'm running is:
`echo -e "file 'file:G:\Shadowplay recordings\Devil May Cry 5\DMD Guns Only\TEST.mp4'\nfile 'file:G:\Shadowplay recordings\Devil May Cry 5\DMD Guns Only\TEST2.mp4'" | ffmpeg -hide_banner -f concat -auto_convert 0 -safe 0 -protocol_whitelist 'file,pipe,fd' -i - -map 0 -c copy -f mp4 -y 'MERGED.mp4'`
It doesn't seem to make a difference whether I try the same thing on the two files exported from LosslessCut with the audio channels removed either.
![image](https://github.com/mifi/lossless-cut/assets/46661228/239773d9-0436-43b4-a7a0-43663ccbfaaf)

**Comment by Monkeor** [comment]
Thank you, this worked for me. You've been a huge help.

**Comment by mifi** [comment]
nice! for future reference: in latest llc version people can add `h264_mp4toannexb` in the "tracks" panel
