### ISSUE TITLE
TimeCode error

### ISSUE THREAD

**Issue by ymjung58** [mifi/lossless-cut#1682]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

In the case of 120 frame video, the time code is displayed as 00:00:00:00, so it seems that it is not recognized.

**Comment by mifi** [comment]
Not sure what you mean by that. care to elaborate? maybe with some screenshots

**Comment by ymjung58** [comment]
![timecode_1](https://github.com/mifi/lossless-cut/assets/125270626/fca879ab-7de0-4a01-a544-9bbdeda0af40)
