### ISSUE TITLE
Splitting a video file into multiple video files by size

### ISSUE THREAD

**Issue by sks2012** [mifi/lossless-cut#1683]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Hello! 
Split video file into several by size, please add!
The ability to split huge video files into several 2GB files is very much missed!

**Comment by mifi** [comment]
> [x] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists

> ## Features

> Divide timeline into segments with length L or into N segments or even randomized segments!

**Comment by sks2012** [comment]
> > [x] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
> 
> > ## Features
> 
> > Divide timeline into segments with length L or into N segments or even randomized segments!
I couldn't find this function in the program.
Could you please tell me where it is?

**Comment by sks2012** [comment]
And yes. There is no SIZE function!

**Comment by sks2012** [comment]
> > [x] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
> 
> > ## Features
> 
> > Divide timeline into segments with length L or into N segments or even randomized segments!

And yes. There is no SIZE function!
