### ISSUE TITLE
Trimming VIRB360 video loses the projection information

### ISSUE THREAD

**Issue by brisset** [mifi/lossless-cut#169]
Hi,
I am looking for a lean and mean video cutter which does not reencode video, and came accross this project which looks promising. However when trying to trim a video shot on VIRB360 (360 video) it somehow loses the projection information, and the trimmed video is not displayed correctly.
Looking at the codec information in VLC I see that the projection information has been lost. Is there any way to preserve it? Attached 2 screenshots: codec information of original file, and codec information of trimmed file.
Thanks!
![VIRB_original_codec_info](https://user-images.githubusercontent.com/5457181/58833694-e4c37b00-8651-11e9-8b26-8d836459fc0d.JPG)

![VIRB_trimmed_codec_info](https://user-images.githubusercontent.com/5457181/58833714-ee4ce300-8651-11e9-9db5-95dc74b624be.JPG)

**Comment by brisset** [comment]
Looks like this may be the reason: 
https://stackoverflow.com/questions/44760588/preserving-side-data-information-for-360-video-transcoding-using-ffmpeg
Unfortunately it is not so easy to add a switch to the generated command line nor is there any options to set for ffmpeg invocation so I can't test it

**Comment by mifi** [comment]
Now inside the help screen you can see a log of the last ffmpeg commands so you can copy and paste

**Comment by mifi** [comment]
https://github.com/google/spatial-media/tree/master/spatialmedia

**Comment by mifi** [comment]
Have you tried this?

https://stackoverflow.com/a/48147865/6519037

**Comment by mifi** [comment]
I found a solution to this:

Go to Settings and enable the `Experimental flag` checkbox. Then 360 data should be included.

**Comment by dhilt** [comment]
@mifi I successfully split my 360-video into several 360-pieces with "Experimental flag" set to true, but I can't join that pieces into a new single source. The result is not 360. Looks like it loses some meta-data or something else when doing merge. How can I merge some 360-videos into one 360-piece?

**Comment by mifi** [comment]
@dhilt did you try to enable the "Preserve original metadata when merging? (slow)" option? And I think "Preserve all MP4/MOV metadata" needs to be disabled

**Comment by mifi** [comment]
I think this is somewhat related to #853

**Comment by mifi** [comment]
So to summarise where the issue currently stands at:
With experimental flag and preserve metadata on a **non-merge** (`-map_metadata 0`) it does copy 360 side data

```
Output #0, mp4, to '360-out.mp4':
...
  Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(tv, smpte170m), 5760x2880, q=2-31, 177436 kb/s, 25 fps, 25 tbr, 25k tbn, 25k tbc (default)
    Metadata:
      creation_time   : 2021-09-08T15:48:50.000000Z
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
    Side data:
      stereo3d: 2D
      spherical: equirectangular (0.000000/0.000000/0.000000)
```

However if merging (concat), it does not copy the side data, even when explicitly specifying the metadata for "global" and "streams":

```bash
ffmpeg -f concat -safe 0 -protocol_whitelist file,pipe -i 360.txt -i 360.mp4 -strict experimental -c copy -map 0 -map_metadata:g 1:g -map_metadata:s 1:s -strict experimental -y 360-out.mp4
```

```
Output #0, mp4, to '360-out.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 2021-09-08T15:48:50.000000Z
    encoder         : Lavf58.76.100
  Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(tv, smpte170m), 5760x2880, q=2-31, 177436 kb/s, 25 fps, 25 tbr, 25k tbn, 25k tbc
    Metadata:
      creation_time   : 2021-09-08T15:48:50.000000Z
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 130 kb/s
    Metadata:
      creation_time   : 2021-09-08T15:48:50.000000Z
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
```

**Comment by mifi** [comment]
Ok I found that ffmpeg currently doesn't support it when concatenating files:

https://stackoverflow.com/questions/61701335/how-do-i-preserve-side-data-when-concatenating-files-in-ffmpeg

BUT I found that exiftool seems to support it, so I'm considering adding it to losslesscut:
https://stackoverflow.com/a/71038003/6519037

**Comment by dhilt** [comment]
That's great! BTW I did merge with [google spatialmedia](https://github.com/google/spatial-media).

**Comment by mifi** [comment]
Will track in #1027, so I'll close this
