### ISSUE TITLE
Disabling overwrite doesn't behave as expected if a subsequent export adds more segments

### ISSUE THREAD

**Issue by SignpostMarv** [mifi/lossless-cut#1690]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 11

### Steps to reproduce

1) Disable overwriting
2) Create a session with less than 100 segments (this may also work with less than 10 segments, have not tested)
3) Export
4) Add more segments to bump it over the number padding length (i.e. less than 100 pads to two digits, 100 or more pads to 3 digits)
5) Export

### Expected behavior

presence of 01-foo.mp4 should be treated as presence of 001-foo.mp4

### Actual behavior

001-foo.mp4 through 099-foo.mp4 will be created alongside 01-foo.mp4 through 99-foo.mp4

**Comment by mifi** [comment]
I think the only way to solve this is to allow the user to choose how many zeroes to pad the number with, right?

**Comment by SignpostMarv** [comment]
> I think the only way to solve this is to allow the user to choose how many zeroes to pad the number with, right?

Either that, or run a file existence check for 1 up / 1 down orders of magnitude's worth of padding?

Having a setting that I can set and forget for the _minimum_ padding length would be good though 👍
