### ISSUE TITLE
Exporting segments as webp image files doesn't work as expected.

### ISSUE THREAD

**Issue by Helspank** [mifi/lossless-cut#1693]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Linux

### Steps to reproduce

0. Select "webp" as "Snapshot capture format" in the Settings.
1. Open a file
2. Create a couple of segments.
4. Right click on a segment -> Extract frames as image files
5. Select any option and confirm.

### Expected behavior

The frames should be extracted in the working directory in the selected format.

### Actual behavior

A single animated webp file is exported instead of a series of webp images.

### Share log

The Developer Tools don't say anything in particular, but the command line says this:

`
ffmpeg -hide_banner -f lavfi -i 'nullsrc=s=256x256:d=1' -f null -
ffprobe -of json -show_chapters -show_format -show_entries stream -i '/mnt/ext/Coffee_Run_Blender_Studio.webm' -hide_banner
ffprobe -v error -read_intervals '0%30' -show_packets -select_streams 0 -show_entries 'packet=pts_time,flags' -of json '/mnt/ext/Coffee_Run_Blender_Studio.webm'
ffprobe -v error -read_intervals '0%50.2912765625' -show_packets -select_streams 0 -show_entries 'packet=pts_time,flags' -of json '/mnt/ext/Coffee_Run_Blender_Studio.webm'
ffprobe -v error -read_intervals '0%51.291275999999996' -show_packets -select_streams 0 -show_entries 'packet=pts_time,flags' -of json '/mnt/ext/Coffee_Run_Blender_Studio.webm'
ffprobe -v error -read_intervals '50.39576875%110.39576875' -show_packets -select_streams 0 -show_entries 'packet=pts_time,flags' -of json '/mnt/ext/Coffee_Run_Blender_Studio.webm'
ffprobe -v error -read_intervals '51.395768000000004%111.395768' -show_packets -select_streams 0 -show_entries 'packet=pts_time,flags' -of json '/mnt/ext/Coffee_Run_Blender_Studio.webm'
ffmpeg -ss '80.39576875' -i '/mnt/ext/Coffee_Run_Blender_Studio.webm' -t '0.9999992500000019' '-q:v' 7 -vsync 0 -y '/home/Pictures/Coffee_Run_Blender_Studio-%02d.webp'
Failed to parse ffmpeg progress line: Invalid time from ffmpeg progress -577014:32:22.77
Failed to parse ffmpeg progress line: Invalid time from ffmpeg progress -577014:32:22.77
Failed to parse ffmpeg progress line: Invalid time from ffmpeg progress -577014:32:22.77
Failed to parse ffmpeg progress line: Invalid time from ffmpeg progress -577014:32:22.77
[etc, this line is repeated several times]
`

**Comment by mifi** [comment]
related: https://stackoverflow.com/questions/62345064/unable-to-extract-frames-in-webp-from-webm-video
