### ISSUE TITLE
Bug in setting the modification date/time of output files

### ISSUE THREAD

**Issue by maboroshin** [mifi/lossless-cut#1695]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

Select the following in the settings : "Source file's time minus segment end cut time"

The modification date of the new file is not negative. The values are the result of addition.

### Expected behavior

I don't know.

1. If the text is correct, it will be negative.
2. If the calculations are correct, the text will be corrected. : "Source file's time plus segment end cut time"

### Actual behavior

The explanation is that it is negative, but it is additive.

**Comment by mifi** [comment]
I have these settings:
<img width="319" alt="Screenshot 2023-09-05 at 23 41 46" src="https://github.com/mifi/lossless-cut/assets/402547/c0532718-7bad-4726-b072-a414f8278cc2">

Then I cut segment end about one hour away from the end of a file:
<img width="505" alt="Screenshot 2023-09-05 at 23 42 03" src="https://github.com/mifi/lossless-cut/assets/402547/bcea58ce-ef87-4d14-afb3-fb6f88ac7782">

to me it looks like the time has been subtracted:
- before:  19:18
- after: 18:23

or am i misunderstanding?

**Comment by maboroshin** [comment]
I got the same result as you. I forget which file, Sorry. So I will close this issue.
