### ISSUE TITLE
v 3.5.6 AppImage not working; disappearing interface and inoperable menu items

### ISSUE THREAD

**Issue by slipperybeluga** [mifi/lossless-cut#1697]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Linux

### Steps to reproduce

Run AppImage. I am using Ubuntu 22.04.3 LTS

### Expected behavior

Ability to access File menu items

### Actual behavior

When I first load this version of lossless-cut, I have a splash screen or background that says DROP FILE(S) and has a picture of a flower, etc. This disappears within about 3 seconds, taking the bottom menu/interface (play button, cut, etc) with it. During the brief period that it is visible, I can access the menu items as normal. However, once it's gone, nothing happens when I click File menu options such as Open, Settings, and the Import options and I am missing the main user interface at the bottom of the window. Help menu options work and I was able to Toggle Developer Tools.

This is my first time using lossless-cut so I grabbed the older AppImage version, 3.5.4, and it works without any issue. 

### Share log

I get this output in the terminal after running the AppImage for lossless-cut 3.5.6:

```
ffmpeg -hide_banner -f lavfi -i 'nullsrc=s=256x256:d=1' -f null -
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94361)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at click (/tmp/.mount_Lossleyp27BH/resources/app.asar/vite-dist/menu.js:23:36)
    at MenuItem.click (node:electron/js2c/browser_init:2:30958)
    at Menu._executeCommand (node:electron/js2c/browser_init:2:36354)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94361)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at click (/tmp/.mount_Lossleyp27BH/resources/app.asar/vite-dist/menu.js:23:36)
    at MenuItem.click (node:electron/js2c/browser_init:2:30958)
    at Menu._executeCommand (node:electron/js2c/browser_init:2:36354)
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94361)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at click (/tmp/.mount_Lossleyp27BH/resources/app.asar/vite-dist/menu.js:23:36)
    at MenuItem.click (node:electron/js2c/browser_init:2:30958)
    at Menu._executeCommand (node:electron/js2c/browser_init:2:36354)
```

Here is the output of the JS console:
```

index-3c673242.js:299 Version 3.56.0
DevTools failed to load source map: Could not load content for file:///tmp/.mount_LosslewNVNtu/resources/app.asar/node_modules/cue-parser/lib/cue.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///tmp/.mount_LosslewNVNtu/resources/app.asar/node_modules/cue-parser/lib/command.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///tmp/.mount_LosslewNVNtu/resources/app.asar/node_modules/cue-parser/lib/cuesheet.js.map: Unexpected end of JSON input

```

**Comment by mifi** [comment]
does it  work on another computer and does it work with non-AppImage install? for example https://github.com/mifi/lossless-cut/releases/download/v3.56.0/LosslessCut-linux-x64.tar.bz2

**Comment by bwprog** [comment]
I have the same issue with the AppImage. I'm also using the previous version as a workaround for now.

OpenSuse Tumbleweed w/ Pacman Mesa/Codecs on X11 with AMD GPU Zen3+.

Issue seems to be affecting every app that upgraded to Electron 26/26.1. Not all Linux configurations are affected, but here are several threads of people discussing the issue with other apps.
Webcord: https://github.com/SpacingBat3/WebCord/issues/452
Armcord: https://github.com/ArmCord/ArmCord/issues/454
Electron: https://github.com/electron/electron/issues/39515

In the Electron thread they seem to have isolated the issue to Chromium 116 which also causes me the same blank screen issue unless I pass "--disable-gpu". Unfortunately that does not work for any of the updated Electron apps. Thankfully, it is easy to stay on older AppImages until a fix (Electron 25/27) is implemented.

**Comment by slipperybeluga** [comment]
> does it work on another computer and does it work with non-AppImage install? for example https://github.com/mifi/lossless-cut/releases/download/v3.56.0/LosslessCut-linux-x64.tar.bz2

Same issue on other PCs. But I am running the same version of Ubuntu on all of my non-headless PCs.

Also same issue running the binary directly from the linux-x64.tar.bz2. 

Sounds like it's a known Electron issue per @bwprog post. I am happy with using the older version in the meantime.

**Comment by mysteryx93** [comment]
On Arch-based Linux, having the same issue installing it from `Chaotic-AUR`

**Comment by sblatnick** [comment]
I can confirm that I see the same behavior on my Debian box using v3.5.6.  Clicking anywhere seems unresponsive.  The menu is available, but doesn't seemingly do anything when I select Settings.

If I extract the tar.bz2 one iinstead, I get an error with:
`Error: Render frame was disposed before WebFrameMain could be accessed`

**Comment by mifi** [comment]
Hopefully electron will fix this issue soon. In the meantime I hope you can use older version of losslesscut

**Comment by AndKe** [comment]
same issue here - joining in :)

**Comment by nany3003** [comment]
same issue here

**Comment by ipisdagat** [comment]
Reporting the same issue as well, using PCLinuxOS.

**Comment by sppmg** [comment]
Not sure same issue for me.

Directly execute appimage:

```
$ ./LosslessCut-linux-x86_64_v3.56.AppImage
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
ffmpeg -hide_banner -f lavfi -i 'nullsrc=s=256x256:d=1' -f null -
ffprobe -of json -show_chapters -show_format -show_entries stream -i '/run/shm/vid.mp4' -hide_banner
```

With firejail (noprofile)
```
$ firejail --noprofile --appimage --private=${HOME}/****/firejail/lossless-cut /mnt/******/LosslessCut-linux-x86_64_v3.56.AppImage --no-sandbox
Parent pid 267809, child pid 267810

** Warning: dropping all Linux capabilities and setting NO_NEW_PRIVS prctl **

Mounting appimage type 2
Warning: NVIDIA card detected, nogroups command ignored
Warning: NVIDIA card detected, nogroups command ignored
Warning: NVIDIA card detected, nogroups command ignored
Child process initialized in 49.89 ms
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
ffmpeg -hide_banner -f lavfi -i 'nullsrc=s=256x256:d=1' -f null -
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
```
Using Debian 12, but it's work fine at Debian 11 (same verison with firejail).

**Comment by bwprog** [comment]
I can confirm the new 3.58 appimage solves this issue for me. 

I think the bump to Electron 27 fixed it, as I confirmed I still have the issue with the older 3.56 (Electron 26).

Thanks again for this useful software.

**Comment by slipperybeluga** [comment]
**Version 3.58.0 AppImage working.**

Closing issue, thanks!
