### ISSUE TITLE
Exported file timestamps are crazy wrong

### ISSUE THREAD

**Issue by mrobe** [mifi/lossless-cut#1699]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

MacOS 12

### Steps to reproduce

Open a file, set in and out points, then export.

### Expected behavior

The creation and modification times of the exported file should be sensible.

### Actual behavior

Creation time is 01/01/2001, and modification time is -23 hours from now.

### Share log

N/A

**Comment by mifi** [comment]
creation time I don't know why it's set to 01/01/2001. losslesscut doesn't update that value. Modification date is set based on the source file's modification date. Try to set "Set file modification date/time of output files to:" to "current time" under settings.
