### ISSUE TITLE
Convert to supported format strips audio

### ISSUE THREAD

**Issue by dreamflasher** [mifi/lossless-cut#1706]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with a different kind of file to confirm that the problem is related to just this file.
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Steps to reproduce

1. Download an AVI or HQ file from onlinetvrecorder.com, eg. https://www.onlinetvrecorder.com/v2/help/samples
2. Open with losslesscut
3. Observe "Convert to supported format"

### Expected behavior

Have a preview with sound and correct aspect ratio.

### Actual behavior

Missing sound (and wrong aspect ratio), as previously observed here: https://github.com/mifi/lossless-cut/issues/94

### Provide an error report

```
No error occurred.

{
  "state": {
    "ffmpegExperimental": false,
    "preserveMovData": true,
    "movFastStart": true,
    "preserveMetadataOnMerge": true,
    "filePath": "E:\\Downloads\\TEST_10.10.10_10-10_test_1_TVOON_DE.mpg.HQ.avi",
    "fileFormat": "avi",
    "externalFilesMeta": {},
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "Main",
        "codec_type": "video",
        "codec_tag_string": "H264",
        "codec_tag": "0x34363248",
        "width": 720,
        "height": 576,
        "coded_width": 720,
        "coded_height": 576,
        "closed_captions": 0,
        "film_grain": 0,
        "has_b_frames": 1,
        "sample_aspect_ratio": "64:45",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 30,
        "chroma_location": "left",
        "field_order": "progressive",
        "refs": 1,
        "is_avc": "false",
        "nal_length_size": "0",
        "r_frame_rate": "25/1",
        "avg_frame_rate": "25/1",
        "time_base": "1/25",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 1462,
        "duration": "58.480000",
        "bit_rate": "7346070",
        "bits_per_raw_sample": "8",
        "nb_frames": "1462",
        "extradata_size": 40,
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        }
      },
      {
        "index": 1,
        "codec_name": "mp3",
        "codec_long_name": "MP3 (MPEG audio layer 3)",
        "codec_type": "audio",
        "codec_tag_string": "U[0][0][0]",
        "codec_tag": "0x0055",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "initial_padding": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "3/125",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 2439,
        "duration": "58.536000",
        "bit_rate": "192000",
        "nb_frames": "2439",
        "extradata_size": 12,
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        }
      }
    ],
    "copyStreamIdsByFile": {
      "E:\\Downloads\\TEST_10.10.10_10-10_test_1_TVOON_DE.mpg.HQ.avi": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {}
    ],
    "mainFileFormatData": {
      "filename": "E:\\Downloads\\TEST_10.10.10_10-10_test_1_TVOON_DE.mpg.HQ.avi",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "avi",
      "format_long_name": "AVI (Audio Video Interleaved)",
      "start_time": "0.000000",
      "duration": "58.536000",
      "size": "55172274",
      "bit_rate": "7540286",
      "probe_score": 100,
      "tags": {
        "software": "Lavf52.44.0"
      }
    },
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "separate",
    "outSegTemplate": "${FILENAME}-${CUT_FROM}-${CUT_TO}${SEG_SUFFIX}${EXT}"
  },
  "platform": "win32",
  "version": "3.56.0"
}
```

### Share the file

https://static.onlinetvrecorder.com/TEST_10.10.10_10-10_test_1_TVOON_DE.mpg.avi

**Comment by dreamflasher** [comment]
I am happy to change the container format before opening with losslesscut, but I can't find any settings that work:

`ffmpeg -fflags +genpts -i TEST_10.10.10_10-10_test_1_TVOON_DE.mpg.HQ.avi-c:v copy -c:a copy TEST_10.10.10_10-10_test_1_TVOON_DE.mpg.HQ.mkv`

`ffmpeg -fflags +genpts -i TEST_10.10.10_10-10_test_1_TVOON_DE.mpg.HQ.avi -c:v copy -c:a copy TEST_10.10.10_10-10_test_1_TVOON_DE.mpg.HQ.mp4`

**Comment by dreamflasher** [comment]
Ah I figured this is an ongoing issue, related issues:
https://github.com/mifi/lossless-cut/issues/445

And there is `File → Convert to supported format`, and some of them work.
I am not happy with the video quality though (either the quality is low or it has the wrong aspect ratio), are there some better players out there that support the creation of cutting marks to be imported into losslesscut? 
I couldn't find any plugins for VLC.

**Comment by mifi** [comment]
what if you run this? still low quality?
<img width="196" alt="Screenshot 2023-09-07 at 22 08 28" src="https://github.com/mifi/lossless-cut/assets/402547/9b70918c-5c48-4406-bd40-de904d607209">

**Comment by dreamflasher** [comment]
Ah the last option is the best! Indeed I missed that one, would be great if one could set that option as default forever (not only until the next restart). 
But yeah, that option has decent quality+sound+aspect ratio, so issue solved for me, thank you!
