### ISSUE TITLE
HTML5 Player Engine alternative

### ISSUE THREAD

**Issue by alsab200** [mifi/lossless-cut#1709]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

How you been Mikael? Long time no see..

As you know there are some codec issues, your HTML5 player don't support some codecs natively.

**.TS files** are one of them..  (TV Broadcasts are this file type and most importantly can be played simultaneously while recording)

Can we solve this codec issue? if you give us an alternative player option?..

E.g. **MPV player** I believe "can" play those codecs.. (created from **MPlayer**)

I have seen some programs offering 2-3 player options like MPV, VLC etc.  Is this possible for you?
I'll get to more detail later, if necessary.
Thank you.

**Comment by mifi** [comment]
Hi. See #88
