### ISSUE TITLE
I think the timecode is wrong

### ISSUE THREAD

**Issue by ymjung58** [mifi/lossless-cut#1711]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

![timecode_1](https://github.com/mifi/lossless-cut/assets/125270626/01c94c65-1f62-4da1-9603-c0eb0d0438db)

### Expected behavior

normal display

### Actual behavior

normal display

**Comment by mifi** [comment]
that's because your cursor is at the beginning of your timeline (00:00:00). If you move your timeline cursor to the right, it should show a different time

**Comment by ymjung58** [comment]
Thanks for your reply.
My intentions were not conveyed accurately.
In the case of 119.88 frame video, the time code is not displayed as the shooting time.
  Please check by referring to the image.
Thanks to LosslessCut, I am receiving a lot of help in managing my videos.
Thank you very much.

-----Original Message-----

**Comment by mifi** [comment]
do you get a popup when opening the file asking about importing its timecode? is it possible to share a video file that has such a timecode?

**Comment by mifi** [comment]
unfortuately i cannot see this video file. you can email to me if private: https://mifi.no/

**Comment by ymjung58** [comment]
Thank you
What are you saying?
Does this mean you can't see this email?
Please tell me again exactly how to send the video.

-----Original Message-----

**Comment by mifi** [comment]
I cant see your attachment. Maybe you can send to mikael@yankee.no

**Comment by mifi** [comment]
I didn't recieve any email so closing this
