### ISSUE TITLE
Losslessly speed up / slow down

### ISSUE THREAD

**Issue by mifi** [mifi/lossless-cut#1712]
### Discussed in https://github.com/mifi/lossless-cut/discussions/1710

<div type='discussions-op-text'>

<sup>Originally posted by **MangerzArt** September 16, 2023</sup>
ffmpeg -itsscale 0.1 -i 0.mp4 -c copy -an 0.mkv
Its it possible? or maybe i can add the comand somewhere</div>

**Comment by AhmedThahir** [comment]
Could you redirect me to the docs on how to use this? I couldn't find it.

**Comment by mifi** [comment]
hi. you can click on the FPS in the lower left to change speed

**Comment by rofrol** [comment]
to speedup 16x, I use this command ` ffmpeg -i input.mp4 -filter:v "setpts=PTS/16" -an output.mp4`. I do not want to increase fps.

**Comment by mifi** [comment]
@rofrol that is not a lossless command, and will cause a full re-encode

**Comment by jdilla59** [comment]
> hi. you can click on the FPS in the lower left to change speed

Thank you Google Gemini for helping me easily find what I wanted to ask about Lossless Cut Speed Adjustment.....
