### ISSUE TITLE
Avoid intermediate files when possible

### ISSUE THREAD

**Issue by r3a1d3a1** [mifi/lossless-cut#1713]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

As mentioned at the end of this [answer](https://superuser.com/a/1644282/158220), it's possible to merge sections of a video without creating multiple videos of subsections. This would increase the operation speed and minimize wear and tear on SSD. I understand that it's not suitable for all options, but when it's possible, why not utilize it?

**Comment by mifi** [comment]
closing in favor of #963 - thanks!

**Comment by mifi** [comment]
> Terribly sorry I didn't find that issue myself.

no worries! it was closed after all

> One more interesting thing I noticed that's not totally relevant to this issue but hard to search: MKV->MKV gets glitchy at stitch points even if subsections (extracted via current method) are glitch-free (cut on keyframes). But MKV->MP4 w/o any re-encoding works perfectly. Maybe add a warning of sorts for MKV to suggest switching destination container to MP4 for example.

You mean cut+merge to MKV is glitchy but cut+merge to mp4 works? do you see this behaviour in many different files/codecs or only files from a certain camera or app?

**Comment by mifi** [comment]
That's very interesting! I will add it to troubleshooting docs
