### ISSUE TITLE
Non-English (Cyrillic) segments labels are lost in exported file names

### ISSUE THREAD

**Issue by onivan** [mifi/lossless-cut#1716]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Linux

### Steps to reproduce

Name the segment with Ukrainian letters, for inst. Україна. On an export the Ukrainian symbols are lost and replaced with underscore symbols _

### Expected behavior

The exported file name should keep non-English symbols used in segments labels. 

### Actual behavior

In the exported file name the non-English symbols used in segments labels are lost and replaced with  _ symbols

**Comment by mifi** [comment]
> * [x]  Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting]

https://github.com/mifi/lossless-cut/blob/master/issues.md#output-file-name-is-missing-characters

doesn't help?

**Comment by onivan** [comment]
Oops! I missed that paragraph! 
But! Although turning off sanitizing recovers Cyrillic letters in filenames from segments labels it also keeps potentially problematic symbols like ? \ / : etc. It will work as workaround. 
Would be better if the sanitizing functionality and non-English letters be non-dependent items.

**Comment by mifi** [comment]
Actually, keeping special symbols like `/` or `\` is a feature, as it allows users to label their segments like directory structures, which allows them to export a folder hierarchy from their segments.

Also I believe some file systems don't support Cyrillic letters, that's why those are being "sanitized" away by default. If someone wants them included, then they can turn off sanitizing.

I agree this could probably be improved, but not sure what's the best way, see #889

**Comment by onivan** [comment]
I agree with the suggestion of [psychob](https://github.com/psychob) to make _3 options: ASCII (which is what we currently got as sanitize), Sanitize (which is what i propose), and no sanitize._ 
The Cyrillic as filenames is widely used by many countries and is included in utf8 so if the filesystem supports utf it would support Cyrillic as well I guess. This is not the critical issue for me as I use the application once a week to split a stream into few parts and have no problem using the current workaround turning of the sanitize option.

**Comment by mifi** [comment]
alright, I think this issue can be closed in favor of the other issue
