### ISSUE TITLE
continue #1714 it can not open

### ISSUE THREAD

**Issue by snoopytl** [mifi/lossless-cut#1718]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

You ignored the version. I mentioned that only in version 3.43 can two segments be displayed correctly, which is also the result I wanted. All versions after version 3.43 cannot meet my requirements.please ues version 3.43 to test ,you will know my meaning
![image](https://github.com/mifi/lossless-cut/assets/29892766/32d8902a-0ddf-4578-a5a4-aa8626818d8b)

**Comment by mifi** [comment]
why did you open a new issue?

**Comment by snoopytl** [comment]
my browser can not open the old issue，i can‘t reply，when i click the  #1714
![image](https://github.com/mifi/lossless-cut/assets/29892766/33563a9e-501e-4d8c-8efc-e89a5bb4f1c2)

**Comment by mifi** [comment]
wow ok, maybe you need to get a new browser 😅

**Comment by snoopytl** [comment]
It may be due to something operating on your Mac, my Edge and other Chrome kernels are unable to open # 1714 properly, while others are fine,
To answer your previous question, I expect the result in version 3.56 to be the same as in version 3.43, displaying 2 clips directly without me having to manually adjust it

**Comment by mifi** [comment]
> It may be due to something operating on your Mac, my Edge and other Chrome kernels are unable to open # 1714 properly

something on my Mac is breaking this page https://github.com/mifi/lossless-cut/issues/1714 for you? 🤔

> It may be due to something operating on your Mac, my Edge and other Chrome kernels are unable to open # 1714 properly, while others are fine, To answer your previous question, I expect the result in version 3.56 to be the same as in version 3.43, displaying 2 clips directly without me having to manually adjust it

so you expect it to look like this:

<img width="782" alt="Screenshot 2023-09-19 at 15 31 31" src="https://github.com/mifi/lossless-cut/assets/402547/daabc878-1417-402c-9a05-75ae97a58162">

with each segment being one frame long?

**Comment by snoopytl** [comment]
i excpect like this,just 2 clips,If it is difficult to achieve, I will continue to use 3.43 and keep the latest version coexisting with 3.43
![image](https://github.com/mifi/lossless-cut/assets/29892766/79837110-c30b-4e24-a3e5-6151b5880008)

**Comment by mifi** [comment]
Ok, I'll close this in favor of existing issue #993, as I believe it's the same thing
