### ISSUE TITLE
Detecting of silent scenes doesn't work

### ISSUE THREAD

**Issue by Nedrozak** [mifi/lossless-cut#1721]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

1. Install 3.56.0
2. Load a mp4 file
3. Use the option "Detect silent scenes"
4. Use any time which should give results
5. Wait for detection to be completed
6. Observe the lack of any detected segments

### Expected behavior

There should be detected segments.

### Actual behavior

There are no detected segments.

### Share log

index-3c673242.js:218 silentScenes []
index-3c673242.js:160 handleError Failed to detect silent scenes Error: No valid segments found
    at index-3c673242.js:218:14654
    at index-3c673242.js:218:15115
    at async index-3c673242.js:218:16098
    at async EventEmitter.<anonymous> (index-3c673242.js:299:7317)
ea @ index-3c673242.js:160
(anonymous) @ index-3c673242.js:218
await in (anonymous) (async)
(anonymous) @ index-3c673242.js:218
await in (anonymous) (async)
(anonymous) @ index-3c673242.js:299
emit @ node:events:513
onMessage @ node:electron/js2c/renderer_init:2

**Comment by mifi** [comment]
I believe this has been fixed already in #1705 - could you try with the nightly build?
