### ISSUE TITLE
make it easier to determine parameters to use for scene/black detect

### ISSUE THREAD

**Issue by hulleyrob** [mifi/lossless-cut#1724]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

So ive just come back to using this after a while away. It seems ive forgotten what settings I used to detect scenes in videos I wanted to cut.

It came to me that being able to analyse the current frame so that it would give me the numbers to put into Detect Black Scene etc on the frames im interested in would be a very useful feature so that I can work out what values would capture all the frames I want to cut on.

Easy to do?

**Comment by mifi** [comment]
not sure exactly how that would work? i mean the parameters are customisable because they will affect the number of segments to create

**Comment by hulleyrob** [comment]
Sorry I probably wasnt very clear.

In the case of detect black scene for example it would be good if on a given Frame I could press a button and calculate what values would be needed trigger for that scene.

Is there anyway to see what the ffmpeg values are for a given frame?

**Comment by mifi** [comment]
for blackdetect, reading https://ffmpeg.org/ffmpeg-filters.html#blackdetect

there are some formulae:

`Set the threshold for considering a picture "black". Express the minimum value for the ratio`:

```
picture_black_ratio_th = nb_black_pixels / nb_pixels
```

`threshold for considering a pixel "black"` is a bit more complicated:

```
pixel_black_th = luma_minimum_value + pixel_black_th * luma_range_size
```

not sure how to get the correct values for both of these parameters from a single frame.

**Comment by hulleyrob** [comment]
Although I do believe this is a valid improvement I feel I should mention that my struggles were due to a bug in a previous version that have since disappeared after updating. It didnt matter what settings I used I could not split the videos however after an update the old settings I was using worked fine.

**Comment by mifi** [comment]
oh ok. I guess we can close this then. if someone has any ideas on how to finish the above formulae, then we can re-open, but if not, I'm not sure how to do this
