### ISSUE TITLE
希望${SEG_LABEL}能支持中文

### ISSUE THREAD

**Issue by eshao2018** [mifi/lossless-cut#1728]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

使用${SEG_LABEL}变量导出对文件重命名，英文正常显示，中文全部输出——————

**Comment by mifi** [comment]
> [x] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists

https://github.com/mifi/lossless-cut/blob/master/issues.md#output-file-name-is-missing-characters

**Comment by eshao2018** [comment]
e界家族很好的一个交流分享、交友寻找快乐论坛。

**Comment by eshao2018** [comment]
感谢已解决

**Comment by CroMarmot** [comment]
> > [x] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
> 
> https://github.com/mifi/lossless-cut/blob/master/issues.md#output-file-name-is-missing-characters

url hash is out of date

https://github.com/mifi/lossless-cut/blob/master/issues.md#output-file-name-is-missing-characters-chinese-accents-etc

**Comment by eshao2018** [comment]
e界家族很好的一个交流分享、交友寻找快乐论坛。
