### ISSUE TITLE
Gray screen seconds after launching

### ISSUE THREAD

**Issue by FlareFlo** [mifi/lossless-cut#1731]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Linux

### Steps to reproduce

Occurs both on [the latest AUR package](https://aur.archlinux.org/packages/losslesscut-bin) and [the most recent nightly build](https://github.com/mifi/lossless-cut/actions/runs/6349973124).
Losslesscut worked well for me before, though i cannot recall exactly when it broke as i haven't used it for about a week, with several system-updates in-between.

1. Run losslesscut with video file as argument
2. Start video-preview playback, jump to any part of the timeline or wait for around two seconds (no user input)
3. Webview crashes/hangs with grey screen

### Expected behavior

The program operates normally.

### Actual behavior

The program hangs after about two seconds of playback, turning to a grey screen and the web view becomes unresponsive.

https://github.com/mifi/lossless-cut/assets/78537307/458509f7-b163-4379-9203-2ed3b1b677ca
(Log of attached run below)

### Share log

```
libva error: vaGetDriverNames() failed with unknown libva error
ffmpeg -hide_banner -f lavfi -i 'nullsrc=s=256x256:d=1' -f null -
ffprobe -of json -show_chapters -show_format -show_entries stream -i '/home/flareflo/Videos/Replay_2023-09-29_16-05-50.mp4' -hide_banner
ffprobe -v error -read_intervals '0%30' -show_packets -select_streams 0 -show_entries 'packet=pts_time,flags' -of json '/home/flareflo/Videos/Replay_2023-09-29_16-05-50.mp4'
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94361)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at click (/usr/share/losslesscut/resources/app.asar/vite-dist/menu.js:30:36)
    at MenuItem.click (node:electron/js2c/browser_init:2:30958)
    at Menu._executeCommand (node:electron/js2c/browser_init:2:36354)
```

**Comment by mifi** [comment]
This seems to be an electron/linux related issue. Not much I can do, see https://github.com/electron/electron/issues/30902

**Comment by FlareFlo** [comment]
Thanks for the research. According to the linked issue, electron27 no longer has this issue, so i will wait for its release.
