### ISSUE TITLE
Add support for rescaling audio to fit video timestamps in video files with variable frame rate to support AWS MediaConvert

### ISSUE THREAD

**Issue by haakonnessjoen** [mifi/lossless-cut#1733]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

We have issues with some recordings from a LiveU stream. They seem to be regarded as "variable frame rate", even though they are supposed to be one framerate. But I guess they use this to handle if the stream cuts out entirely or something.

Anyways, the clips play fine in any video player, at the start and at the end of the clip. But if we convert the video to HLS using AWS MediaConvert (Amazon web services), the resulting HLS might have increasingly big audio sync issues at the end of the video. This seems to be because AWS MediaConvert doesn't properly scale the input audio presentation time to the video presentation time like most players.

The fix, is to run the mp4 file through ffmpeg with the following flags: `-c:v copy -af aresample=async=1`, so basically that it reencodes the audio, and does tiny adjustments to make sure the audio is following the speed of the video, so that the resulting audio track is exactly the same length as the video track, I imagine.

It would be nice if we could have a "resample audio for audio sync issues" flag in losslesscut. **I realize that this feature would not be lossless**, and what the name of the project is, but could it just be behind some "I understand that this feature is not lossless" modal dialog maybe, or something?

**Comment by mifi** [comment]
This is the first time I've heard this request, but I've added it as a point here #372 - but I have to close this issue for maintenance purposes
