### ISSUE TITLE
No video image on playback, seek — nada

### ISSUE THREAD

**Issue by mrobe** [mifi/lossless-cut#1736]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

MacOS 12

### Steps to reproduce

I open a nothing-special MKV file.

I can't see any video at all. Nothing. Audio works. Some mediainfo for the video.

Format                                   : MPEG Video
Format version                           : Version 2
Format profile                           : Main@High
Format settings                          : CustomMatrix / BVOP
Format settings, BVOP                    : Yes
Format settings, Matrix                  : Custom
Format settings, GOP                     : Variable
Format settings, picture structure       : Frame
Codec ID                                 : V_MPEG2
Codec ID/Info                            : MPEG 1 or 2 Video
Duration                                 : 1 h 23 min
Bit rate mode                            : Variable
Bit rate                                 : 7 909 kb/s
Width                                    : 1 440 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 26.223 FPS
Original frame rate                      : 29.970 (30000/1001) FPS
Standard                                 : Component
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Interlaced
Scan type, store method                  : Separated fields (2 fields per block)
Scan order                               : Top Field First
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.194
Time code of first frame                 : 20:30:51;02
Time code source                         : Group of pictures header
GOP, Open/Closed                         : Open
Stream size                              : 4.98 GiB

 

### Expected behavior

Video should be visible on seek and playback.

### Actual behavior

I can't see any video at all. Nothing.

I can open a TS format version of the same file, and the video works (aspect ratio is squashed, but it's visible), but TS support in LosslessCut is limited (can't seek to key frames), so I convert to MKV with MKVToolNix v. 76. 

### Share log

State reset
index-3c673242.js:298 userOpenFiles
index-3c673242.js:298 /Volumes/OMV-Storage/On'na gokuakuchō.mkv
index-3c673242.js:298 loadMedia /Volumes/OMV-Storage/On'na gokuakuchō.mkv undefined undefined
index-3c673242.js:298 State reset
index-3c673242.js:298 onDurationChange 5024.903

**Comment by mifi** [comment]
does it work if you file -> convert to supported format?

**Comment by mrobe** [comment]
I thought(?) MKV is already supported. What I mean is: MKV files don't show any video.

If I try opening a TS file, LosslessCut automatically begins "Converting to supported format...". After that's finished, I can see the video and play it, but the buttons to seek to keyframes are non-functional, and the image is squashed.

**Comment by mifi** [comment]
> I thought(?) MKV is already supported. What I mean is: MKV files don't show any video.

MKV is supported but [MKV is just a container format](https://github.com/mifi/lossless-cut/blob/master/issues.md#primer--noob-guide-video--audio-formats--codecs). Your file seems to have 
the video *codec* `MPEG Video 2`, which is a quite old codec and not natively supported in losslesscut, so it means you have to convert it to a supported format for the preview/playback to work. Note that the cut/export will still be lossless. See also https://github.com/mifi/lossless-cut#supported-formats and

**Comment by mrobe** [comment]
Oic... I tried one of them and it works.

Is there a warning shown somewhere that the actual codec is unsupported?

Actually, it tried `ffmpeg -decoders` and it lists MPEG-2 video.

Does LosslessCut use a different library for playback?

**Comment by mifi** [comment]
[losslesscut uses chromium for playback](https://github.com/mifi/lossless-cut#supported-formats)

**Comment by mifi** [comment]
there should be awarning but maybe it's not showing for your file, for some reason.if you can share a file that has this problem then i could look into it

**Comment by mrobe** [comment]
OK, this file is too large to share, but let me see if there's a way to cut it down with ffmpeg.

**Comment by mrobe** [comment]
I've trimmed a two-second piece of the file, here:

https://www.sendspace.com/file/fm2l0h

Also, this is an unrelated question, but is there a way to selectively mute a portion of the audio track, losslessly?

I have some films with a loud and very brief 'click' at the beginning, probably from a scratch or blemish on the original (optical) audio track. I'm wondering if there is a way to get rid of these.

thanks for your help !

**Comment by mifi** [comment]
thanks for sharing. It seems your file has codec `mpeg2video`, which chromium video player will just play the audio and show a black video for some reason. I will add it here: https://github.com/mifi/lossless-cut/blob/1cf88d966c3d05e590c15af94c15e34d6cd7985a/src/util/streams.js#L277

> Also, this is an unrelated question, but is there a way to selectively mute a portion of the audio track, losslessly?

#495

**Comment by mrobe** [comment]
Thanks. I'll try the next version of LosslessCut and see how it handles this kind of codec.

And thanks for the pointer to that other topic about muting audio.

I looked on the Net, and some ppl point out that it's possible with the ffmpeg -af option, e.g.:

`ffmpeg -i video.mp4 -af "volume=enable='between(t,5,10)':volume=0, volume=enable='between(t,15,20)':volume=0" ...`

However, I don't know if(?) this is a lossless operation.

Any idea?

If so, I could just do it from the command line.

**Comment by mifi** [comment]
`-af` operations are not lossless so you have to re-rencode
