### ISSUE TITLE
Failed to parse ffmpeg progress line: Cannot destructure property 'start' of 'matchLineTokens(...)' as it is undefined.

### ISSUE THREAD

**Issue by chriad** [mifi/lossless-cut#1739]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Linux

### Steps to reproduce

Install via snap:

snap install losslesscut --channel=edge

Tools > Detect silent scenes
Run silencedetect with default arguments

### Expected behavior

Silences are detected.

### Actual behavior

Silences are not detected.

The following error occurs:

`Failed to parse ffmpeg progress line: Cannot destructure property 'start' of 'matchLineTokens(...)' as it is undefined.`

Silences are detected correctly when running the corresponding ffmpeg command in bash.

This problem does not occur with the stable version by the way.

**Comment by chriad** [comment]
I think its a duplicate #1721

**Comment by chriad** [comment]
Maybe I closed too early. I cannot test it with the latest build (Build/Release #750) since the GUI does not work.

**Comment by mifi** [comment]
I believe this is fixed, can reopen if not
