### ISSUE TITLE
Unable to start on Manjaro Sway - No such interface org.freedesktop.portal.FileChooser

### ISSUE THREAD

**Issue by xeruf** [mifi/lossless-cut#1741]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Linux - Arch with Wayland

### Steps to reproduce

Start from any of the AUR packages or latest from source.

### Expected behavior

It works.

### Actual behavior

I get this in the logs:

    [1] [55847:1014/190016.002545:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”

Window looks like this:
![image](https://github.com/mifi/lossless-cut/assets/13354331/849ee067-6380-4e29-800c-6d5110393304)

Navigation bar works, but clicking something like `File>Open` does nothing and shows this in the logs:

```sh
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94361)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at click (/tmp/.mount_losslevAJ42F/resources/app.asar/vite-dist/menu.js:23:36)
    at MenuItem.click (node:electron/js2c/browser_init:2:30958)
    at Menu._executeCommand (node:electron/js2c/browser_init:2:36354)
```

**Comment by mifi** [comment]
Unfortunately I cannot help you with linux distro specific issues. You'll have to google a solution https://www.google.com/search?q=No+such+interface+org.freedesktop.portal.FileChooser
