### ISSUE TITLE
Audio Playback with .ts (Stransportstreams) Files

### ISSUE THREAD

**Issue by e-x-t-r-a-c-o-o-l** [mifi/lossless-cut#1746]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

When Editing A File that is of Type Transportstream (e.g. .ts) the Sound is not heard. For me it is not clear why this is not possible, since normally the Audio Content is of Type AC3 (2.0 or 5.1) or of MPEG Audio (mpeg 1 or mpeg 2 codec).

When I open A File of the above type, the Dialogue shows someting like "Converting to compatible Format" and after a whle the file is shown in the timeline. A .mkv with size 0 is created in the same folder like the file.

The Video is displayed, but sound is not heard. It is most of the time difficult to cut the file accurately without sound. I must open the same file on VLC Player and search for the exact cutting point, then find the same point in lossless-cut. This makes it difficult and slow to work.

To say: the cutting points remain accurate at the end when using keyframes (accurate mode is not working well)

I have used satellite streams (dvb-s) and cable tv stream (dvb-c) of misc types, SD, HD 720p and FHD 1080P content. I have tried Videos with MPEG2 Audio only and with AC-3 TYPE only, and Mixed Audio Content (AC-3 and MPEG-2 Multicodec/Tracks/Languages). 

I have tested on several machines usng AMD or Intel Processors from first to latest Processor Gnerations, Intel or Nvidia Cards, 4GB to 32GB RAM. There was always enough Harddisk Capacity Remaining to creat or Output the Files.

My Question is: Why isn't it possible to hear sound, at least MPEG2 or a usable converted track to MP4 Audio to facilitate setting cutting points? Why is no Audio Track converted?

This Issue exists since the first version until now (3.58.0)

Thanks for looking at the Issue. 

You may contact me also through the github User E-Mail. 

Best regards
e-x-t-r-a-c-o-o-l

**Comment by mifi** [comment]
it's not clear to me what happens when you click file -> convert to supported format. If you do `Slow: Low quality encode`, do you still not get any audio? or `Fastest: Low playback speed`
