### ISSUE TITLE
Version 3.58 Cannot display file audio waveforms

### ISSUE THREAD

**Issue by hqhbaby** [mifi/lossless-cut#1749]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

Version 3.58 Cannot display file audio waveforms
![QQ截图20231018173135](https://github.com/mifi/lossless-cut/assets/95172664/f0381990-dd53-49d6-9474-dc3656481d41)

### Expected behavior

waveforms

### Actual behavior

waveforms

**Comment by mifi** [comment]
works for me. you need to:
<img width="214" alt="Screenshot 2023-10-19 at 16 12 36" src="https://github.com/mifi/lossless-cut/assets/402547/f6abc0e0-a281-48ed-8c37-83929667eba2">
