### ISSUE TITLE
Can you provide new features or extensions

### ISSUE THREAD

**Issue by hqhbaby** [mifi/lossless-cut#1750]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Can you provide new features or extensions to enhance the display of the file by editing the waveform of the audio and provide a clear display as shown in the picture?
![QQ截图20231018173349](https://github.com/mifi/lossless-cut/assets/95172664/7b56234c-6da5-4fea-b2fa-7a5ada24d963)

**Comment by mifi** [comment]
not sure what you mean by this?
there is already a small and full screen waveform in losslesscut:
<img width="382" alt="Screenshot 2023-10-19 at 16 13 02" src="https://github.com/mifi/lossless-cut/assets/402547/6777c9b5-f21a-4a4f-a42a-daa0efff6f8f">
