### ISSUE TITLE
[feature request] option "play this segment only"

### ISSUE THREAD

**Issue by rrrcabral** [mifi/lossless-cut#1753]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

It would be nice to have the "play this segment only" option when right clicking on one of the segments in the sidebar to check if it is cut correctly, without this it is difficult to know if the end was cut in the right place (at another time, after you have already configured it), because the player continues running without pausing when it reaches the end of the segment, and you only depend on its visuals to guess if it is cut correctly.

**Comment by mifi** [comment]
I believe there's already a hotkey to do this. Are you saying the hotkey is not convenient enough and you want a menu item instead?

**Comment by rrrcabral** [comment]
menu, to appear when you right-click on the segment

**Comment by mifi** [comment]
check they keyboard shortcuts page: `togglePlayOnlyCurrentSegment` or `toggleLoopOnlyCurrentSegment`
