### ISSUE TITLE
Seek by audio frames

### ISSUE THREAD

**Issue by QuartzSTQ** [mifi/lossless-cut#1754]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Currently if you try opening a file with just audio it seeks by 0.033 ms, which is definitely not the length of an MP3 frame for example (1152s/44.1kHz=~26 ms), and you also can't visualise where audio frames are positioned.

**Comment by mifi** [comment]
Do you happen to know how to calculate mp3 sample size of a file using for example ffprobe? Not sure if it makes sense to seek by audio frames, especially for certain formats like .wav, because there's 44k samples every second so I don't know what would be the need to seek by such a small amount

**Comment by QuartzSTQ** [comment]
MP3 frames are always 1152 samples, no matter what sample rate or bit rate. Other codecs are different. It would be pointless to implement for uncompressed codecs, slightly less so for losslessly-compressed codecs, since there you can just re-encode. But for splitting lossy audio this would be great since I could directly visualize where my cutting points are as opposed to using an external editor to guess and also having to figure out time differerences between them as well. Of course, for some codecs this is unnecesary anyway, for example [m4acut](https://github.com/nu774/m4acut) can add gapless playback tags so exact-sample splitting is possible (as long as your player supports them as well). So I suppose being able to visualize exact samples would also be good, considering the decoder time difference problem that I mentioned.
But if there's no way to do this using ffprobe then I guess it's impossible for now.

**Comment by mifi** [comment]
Ok I will hardcode frame size of 1152 and base the FPS and "short step" off that value for mp3. for aac it seems the frame size is 1024 so I will do similarily for that https://stackoverflow.com/questions/59173435/aac-packet-size
