### ISSUE TITLE
改进预览播放 Improve preview playback：Dynamic preview 动态预览

### ISSUE THREAD

**Issue by jkqxl** [mifi/lossless-cut#1756]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

已有的讨论（https://github.com/mifi/lossless-cut/issues/1584#issue-1682613228），但并没有完成想要功能（There has been discussion, but the desired function has not been completed）

现有的功能：循环当前段的开始和结束（toggleLoopStartEndOnlyCurrentSegment）

![Snipaste_2023-10-22_12-36-03](https://github.com/mifi/lossless-cut/assets/72729140/8e733a83-ae04-4c6b-a6b7-e89fa2f52e5c)

想要的功能：循环当前段的结束、下一片段的开始（toggle Loop End Only Current Segment and toggle Loop Start Only nextSegment）（Each Loop the end of the current segment and the beginning of the next segment）

![Snipaste_2023-10-22_12-44-32](https://github.com/mifi/lossless-cut/assets/72729140/4b9ea2b1-9087-4d54-bc36-773ead24d37b)

目的，通过动态预览，以确认剪辑结果是否符合预期。（Purpose, through dynamic preview, to confirm whether the clip result is as expected.）
静态查看，在很多时候的结果并不能让人满意，需要重新修正。（Static viewing, in many cases the results are not satisfactory and need to be corrected）

**Comment by mifi** [comment]
Hi! Im not sure exactly what you’re asking for improving here.

**Comment by jkqxl** [comment]
> 你好！我不确定您在这里要求改进什么。

希望可以预览，不同片段视频之间的过渡（Hope to be able to preview, the transition between different clips of video）

**Comment by jkqxl** [comment]
> Hi! Im not sure exactly what you’re asking for improving here.

![Snipaste_2023-10-27_11-27-27](https://github.com/mifi/lossless-cut/assets/72729140/80fef76c-712c-46a4-8b84-aef6ce3e9174)

![Snipaste_2023-10-27_11-29-57](https://github.com/mifi/lossless-cut/assets/72729140/4ee6db30-f69e-43bf-823b-854ce7dccfa0)

**Comment by mifi** [comment]
If I understand you correctly, what you want is something like this #1887

**Comment by jkqxl** [comment]
> If I understand you correctly, what you want is something like this #1887

![Snipaste_2024-10-09_11-21-11](https://github.com/user-attachments/assets/be235da2-e498-4e2e-b2c7-deca58cd892a)

Loop playback（A similar feature）
default Sequential fragments：1 --> 2
change Sequential fragments：3 --> 4

Check whether the content of the transition scene can meet expectations
