### ISSUE TITLE
timestamp / filename when saving

### ISSUE THREAD

**Issue by imel6** [mifi/lossless-cut#1757]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

the option for name of file is set to "Source file's time plus segment start cut time'.  If I export data with more than one segment then the filename is always the same and overrides the existing file although it does not contain the same start point.

### Expected behavior

different filenames

### Actual behavior

always the same filename

### Share log

No error occurred.

{
  "state": {
    "ffmpegExperimental": false,
    "preserveMovData": true,
    "movFastStart": true,
    "preserveMetadataOnMerge": false,
    "filePath": "H:\\downloads\\2023-10-22 12-32-02 Kittyy.mp4",
    "fileFormat": "mp4",
    "externalFilesMeta": {},
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1080,
        "closed_captions": 0,
        "film_grain": 0,
        "has_b_frames": 1,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 40,
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "field_order": "progressive",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "id": "0x1",
        "r_frame_rate": "30/1",
        "avg_frame_rate": "30/1",
        "time_base": "1/15360",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 377619968,
        "duration": "24584.633333",
        "bit_rate": "5981642",
        "bits_per_raw_sample": "8",
        "nb_frames": "737539",
        "extradata_size": 58,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "VideoHandler",
          "vendor_id": "[0][0][0][0]"
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "44100",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "initial_padding": 0,
        "id": "0x2",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/44100",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 1084179456,
        "duration": "24584.568163",
        "bit_rate": "63899",
        "nb_frames": "1058769",
        "extradata_size": 5,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "SoundHandler",
          "vendor_id": "[0][0][0][0]"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "H:\\downloads\\2023-10-22 12-32-02 Kittyy.mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {
        "start": 5793.614351453351,
        "end": 6065.455494043539
      },
      {
        "start": 8647.946348650312,
        "end": 8834.837134181065
      }
    ],
    "mainFileFormatData": {
      "filename": "H:\\downloads\\2023-10-22 12-32-02 Kittyy.mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "24584.633333",
      "size": "18609195504",
      "bit_rate": "6055553",
      "probe_score": 100,
      "tags": {
        "major_brand": "isom",
        "minor_version": "512",
        "compatible_brands": "isomiso2avc1mp41",
        "encoder": "Lavf60.3.100"
      }
    },
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "merge",
    "outSegTemplate": "${FILENAME}-${CUT_FROM}-${CUT_TO}${SEG_SUFFIX}${EXT}"
  },
  "platform": "win32",
  "version": "3.58.0"
}

**Comment by mifi** [comment]
Not sure I understand. Could you explain with some screenshots maybe?

**Comment by imel6** [comment]
![Export1](https://github.com/mifi/lossless-cut/assets/148804129/a00b7d6c-301f-47db-a371-3b5a2ff4b0fb)
![Export2](https://github.com/mifi/lossless-cut/assets/148804129/a8743ef2-2e03-4eaf-852d-eeb726250f65)

I hope my upload of 2 screenshot is well. You see the parts of the moves start at diffent time, but the filename created is the same.

**Comment by imel6** [comment]
I wanted write "movies"
