### ISSUE TITLE
Undo-ing does not work as expected

### ISSUE THREAD

**Issue by szoper** [mifi/lossless-cut#176]
When I mess with an existing segment (already have a start and an end and press "mark in" again) I have no way to revert my change. Pressing Undo have completely no effect, no matter the file.

Expected behaviour:
Revert last action and have a segment like it was before.

**Comment by RileyMShea** [comment]
I would also greatly appreciate an in/out command history.

Currently I set an in/out for a segment, then forget to hit '+' for new segment-in and end up clobbering my in-point  for the previous segment.

Or I think that I have a segment selected that I don't and accidentally change the wrong segment's in/out point.

A command history to track in/out creation/deletion/changes along with a undo/redo shortcut would be wonderful.
#enhancement

**Comment by mifi** [comment]
Yea, this multi segment feature is quite new and I have not implemented any undo for it. But since I am using React, it should be quite simple to use a reducer for all these actions instead of state, so they can be easily undone with the press of a button.

**Comment by mifi** [comment]
this is now impelemented
