### ISSUE TITLE
In LLC 3.58 clicking 'Show file' after export crashes Finder 

### ISSUE THREAD

**Issue by danmeek** [mifi/lossless-cut#1762]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

MacOS 13

### Steps to reproduce

I'm running MacOS Ventura 13.4 and LossLessCut 3.58. Since I updated from 3.56, I noticed that when my export is done and I click the 'Show' button, Finder crashes hard. I've done all the obvious things like restarting the device and de- and re-installing 3.58 but the problem persists. When I went back to 3.56 the problem went away again.

**Steps to reproduce**

1. Open LLC 3.58
2. Open a video file
3. Edit the file
4. Hit export
5. When the export complete notice appears, click 'Show'
6. *sirens in the distance*

### Expected behavior

Clicking 'Show' in 3.56 opens a Finder window (or foregrounds one with the folder in question) and highlights the first of the exported files.

### Actual behavior

Finder crashes and I have to relaunch it.

### Share log

index-3ee52d33.js:299 Version 3.58.0
index-3ee52d33.js:298 userOpenFiles
index-3ee52d33.js:298 /Users/daniel/Downloads/completely benign movie file.mp4
index-3ee52d33.js:298 loadMedia /Users/daniel/Downloads/completely benign movie file.mp4 undefined undefined
index-3ee52d33.js:298 State reset
index-3ee52d33.js:298 Loading EDL file llc /Users/daniel/Downloads/completely benign movie file-proj.llc undefined
index-3ee52d33.js:298 onDurationChange 46.902993
index-3ee52d33.js:298 outSegTemplateOrDefault ${FILENAME}-${CUT_FROM}-${CUT_TO}${SEG_SUFFIX}${EXT}
index-3ee52d33.js:167 customTagsByFile {}
index-3ee52d33.js:167 paramsByStreamId Map(0) {size: 0}
index-3ee52d33.js:167 Cutting from start to 23.50764533439745
index-3ee52d33.js:160 STDERR:
index-3ee52d33.js:160 Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/daniel/Downloads/completely benign movie file.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : Project 8
    date            : 2023-10-24
    encoder         : Lavf60.5.100
  Duration: 00:00:46.90, start: 0.000000, bitrate: 1432 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 720x1080 [SAR 1:1 DAR 2:3], 1295 kb/s, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc60.11.100 libx264
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Output #0, mp4, to '/Users/daniel/Downloads/completely benign movie file-00.00.00.000-00.00.23.508-seg1.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : Project 8
    date            : 2023-10-24
    encoder         : Lavf60.3.100
  Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 720x1080 [SAR 1:1 DAR 2:3], q=2-31, 1295 kb/s, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc60.11.100 libx264
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=    0 fps=0.0 q=-1.0 size=       0kB time=-00:00:00.06 bitrate=  -0.0kbits/s speed=N/A    
[mp4 @ 0x1338056f0] Starting second pass: moving the moov atom to the beginning of the file
frame=  708 fps=0.0 q=-1.0 Lsize=    4250kB time=00:00:23.50 bitrate=1481.6kbits/s speed=1.33e+03x    
video:3856kB audio:369kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.612256%
index-3ee52d33.js:167 Cutting from 24.007645 to end
index-3ee52d33.js:160 STDERR:
index-3ee52d33.js:160 Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/daniel/Downloads/completely benign movie file.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : Project 8
    date            : 2023-10-24
    encoder         : Lavf60.5.100
  Duration: 00:00:46.90, start: 0.000000, bitrate: 1432 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 720x1080 [SAR 1:1 DAR 2:3], 1295 kb/s, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc60.11.100 libx264
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Output #0, mp4, to '/Users/daniel/Downloads/completely benign movie file-00.00.24.008-00.00.46.903-seg2.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : Project 8
    date            : 2023-10-24
    encoder         : Lavf60.3.100
  Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 720x1080 [SAR 1:1 DAR 2:3], q=2-31, 1295 kb/s, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc60.11.100 libx264
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=    0 fps=0.0 q=-1.0 size=       0kB time=-00:00:00.16 bitrate=  -0.0kbits/s speed=N/A    
[mp4 @ 0x127605770] Starting second pass: moving the moov atom to the beginning of the file
frame=  689 fps=0.0 q=-1.0 Lsize=    3892kB time=00:00:22.87 bitrate=1394.0kbits/s speed=1.56e+03x    
video:3507kB audio:360kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.649409%

**Comment by mifi** [comment]
Wow I was wondering if it’s just me. Probably a bug in Finder triggered by electron’s showItemInFolder

https://github.com/mifi/lossless-cut/blob/308bb2b36bf369e6fb61d40c39ac946ffb20d898/src/dialogs/index.jsx#L569

 Will do some googling

**Comment by rd-sf** [comment]
Same bug.  M2Pro  MacOS 14.0

**Comment by mifi** [comment]
found the electron bug: https://github.com/electron/electron/issues/38540#issuecomment-1788904863

**Comment by danmeek** [comment]
Amazing detective work! Is that something the LLC creators can fix
themselves?

**Comment by mifi** [comment]
Well i am the llc creator. I think I will wait a bit and see if it gets fixed in electron. If not, then I have to find some kind of workaround, or downgrade electron.

**Comment by danmeek** [comment]
Oh pardon me! I hadn't realised. I'm a huge fan of your work and grateful
for your efforts.

**Comment by xinplus99** [comment]
Hi, same issue with LLC 3.58.0 on my M1 Macbook Air. 
If I click Show File, Finder will be frozen for about 45-60 sec. But I can still use LLC while Finder is frozen. 
However after export completes, if I click Close instead of Show File, Finder is all good. 
Hope it can be fixed in next update. Thx
