### ISSUE TITLE
Multiple Labels for the same segment

### ISSUE THREAD

**Issue by s2xnetx** [mifi/lossless-cut#1766]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Please allow multiple labels for one segment, that could be used separately in export file names. ~5 labels would be enough for me. Could be edited in the Label editor, and used in export like ${SEG_LABEL1}, ${SEG_LABEL2} and so on.

I know that segment tags could solve my problem, but the segment tag editor needs more time to edit my segments. (also segment tags menu does not have a keyboard shortcut)

Thank you

**Comment by mifi** [comment]
can't you use segment tags?

**Comment by s2xnetx** [comment]
Can, but is difficult to edit the pure json. It would be nice to have a simplified tag editor with 2 textboxes fore each name, value pairs to skip the editing of the direct json.
