### ISSUE TITLE
A mismatch was detected in at least one file 

### ISSUE THREAD

**Issue by konte466** [mifi/lossless-cut#1769]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

So i'm trying to merge the videos but everytime this issue pops up "A mismatch was detected in at least one file . You may proceed, but the resulting file not be playable." and i thought it might be a file problem so i checked with randoms videos and it's same issue 

### Expected behavior

Video should have merged like it used to

### Actual behavior

Instead the video is not merging 
![image](https://github.com/mifi/lossless-cut/assets/150100146/492f21bf-4313-49d9-882b-843a762789d3)

**Comment by mifi** [comment]
You need to click on the exclamation mark

**Comment by konte466** [comment]
![image](https://github.com/mifi/lossless-cut/assets/150100146/03e4c2ae-9a77-41b6-820f-f5fd140341a2)
Well i did and iam getting this mssg everytime and in every single video iam trying to merge

**Comment by konte466** [comment]
I am not sure what happened but i was able to merge the videos 1 or 2month ago but now it's seems like impossible with any video bcz this mssgs pops up and when i procced with the merge the video either gets broken or stops working..
Sorry for the bad english

**Comment by mifi** [comment]
As can be seen from the dialog, the files you are trying to merge have different fps and width/height. Thus merging them losslessly can be problematic. It’s hard to say why they are different without knowing anything about where they come from or any info about them.

**Comment by konte466** [comment]
Sir but this wasn't a issue 2 months ago even i  downloaded a video from youtube then tried to split it and then tried to merge it and iam still facing the same issue i don't know why

**Comment by konte466** [comment]
Is there anyway to fix this?

**Comment by mifi** [comment]
i don't know how to look into this because i don't know anything about the files you're trying to merge

**Comment by KaKi87** [comment]
Hi,
I'm experiencing the same issue, what to do ?
I can share the original files through the platform of your choice.
Thank you
