### ISSUE TITLE
Cutting video problem (beginning part becomes black)

### ISSUE THREAD

**Issue by qazxswedcrtg** [mifi/lossless-cut#177]
I have cut several 360 videos by losslesscut and never had problem until now.

This is cutted video
https://drive.google.com/open?id=1njJvtt6jhn52bb2bi6KOIynL-xst_2--

Originally, the video was longer but I cut beginning of the video several times which never helped.

Beginning of video becomes black like this for a few second.
![Screenshot_2019-06-27-04-18-43](https://user-images.githubusercontent.com/52266400/60228863-575ff900-9894-11e9-890e-eafc72c62092.png)

It supposed to be like this;
![Screenshot_2019-06-27-04-18-51](https://user-images.githubusercontent.com/52266400/60228912-7c546c00-9894-11e9-8e49-1753beff0348.png)

I updated losslesscut and other files which has about same file size have no problem.

**Comment by qazxswedcrtg** [comment]
Actually, it does not become black by PC but it becomes slow and unsmooth. It becomes black by phone (LG G4).

**Comment by duncand0nuts** [comment]
Hi.  I had a similar issue, where the start of my cut videos were black.  I toggled the "kc" cut option to "nc" (normal cut) at the bottom of the window and that fixed it for me - maybe try that and see if it works?

**Comment by mifi** [comment]
Alot has changed now in newest version. Reopen if this is still a problem
