### ISSUE TITLE
Split tool does not cut at the specified time

### ISSUE THREAD

**Issue by rhyshanan** [mifi/lossless-cut#1770]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Hi,

has this issue been fixed yet?

When I use the split tool in Lossless Cut ... it does not split at the exact time specified ... its offset slightly

**FFMPEG is able to perform this split function ... and perform it with lossless quality ... on a video file**

Can lossless cut not do this also?

**Comment by mifi** [comment]
what do you mean by split tool?

do you mean https://github.com/mifi/lossless-cut/blob/master/issues.md#cutting-times-are-not-accurate ?

> **FFMPEG is able to perform this split function ... and perform it with lossless quality ... on a video file**

can you elaborate?

**Comment by rhyshanan** [comment]
Yes,
In LosslessCut
I import a video that is .... 5:00 (minutes length)

I use the tool, split segments at cursor .... at positions ... 2:02 and 3:16

now I have 3 segments ... I untick segment 2 ...and press button export+merge ... to export segment 1 and 3 only
the exported video file ... does not have the cuts at ... 2:02 and 3:16both cuts are slightly off




If I perform the same function in FFMPEG
ffmpeg -ss 00:00:00 -i "in.mkv" -to 00:25:55 -c copy out0.mkv
ffmpeg -ss 00:25:56 -i "in.mkv" -to 00:38:20 -c copy out1.mkv

the video exports with the cuts in the exact locations specified ... with lossless quality





Has this issue been resolved in LosslessCut?
I am using version 3.58.0.0



Sent from Yahoo Mail on Android 
 
  On Wed, 8 Nov 2023 at 15:33, Mikael ***@***.***> wrote:   


what do you mean by split tool?

do you mean https://github.com/mifi/lossless-cut/blob/master/issues.md#cutting-times-are-not-accurate ?


FFMPEG is able to perform this split function ... and perform it with lossless quality ... on a video file


can you elaborate?

**Comment by mifi** [comment]
Where did you get the time 00:25:55 from? I thought you were trying to cut 02:02?

**Comment by rhyshanan** [comment]
the 02:02 was only an example number
the actual file I am testing on ... is the ... 00:25:55

however ...I have already run ... LosslessCut split segments at cursor ... tool on the actual test file ... 00:25:55 ... location many times, and its never a precise cut
    On Thursday, 9 November 2023 at 07:33:17 pm NZDT, Mikael Finstad ***@***.***> wrote:  
 
 


Where did you get the time 00:25:55 from? I thought you were trying to cut 02:02?

**Comment by mifi** [comment]
Could you provide the ffmpeg commands coming from losslesscut (see the menu) for the same cuts you did from the command line?

**Comment by rhyshanan** [comment]
menu > tools > Last FFMPEG commands?I dont know how to use this feature.


I am using FFMPEG outside of LosslessCut(Version: 6.0-essentials_build-www.gyan.dev)



I have attached an example video of the problem as it happens
LosslessCut - cut feature.mp4

| 
| 
|  | 
LosslessCut - cut feature.mp4


 |

 |

 |




EXAMPLE VIDEO
there is an image ... placed between two black flickers ... i would like to delete this image ...but cannot ... because LosslessCut is not able to isolate the 2 cuts properly

I can provide another video ... proving that FFMPEG ... does not have this same problem ... it is able to perform this cut accurately.


Can you please confirm that this problem exists, as you mentioned beforedo you mean lossless-cut/issues.md at master · mifi/lossless-cut ?

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
lossless-cut/issues.md at master · mifi/lossless-cut

The swiss army knife of lossless video/audio editing - mifi/lossless-cut
 |

 |

 |





    On Thursday, 9 November 2023 at 07:55:31 pm NZDT, Mikael Finstad ***@***.***> wrote:  
 
 


Could you provide the ffmpeg commands coming from losslesscut (see the menu) for the same cuts you did from the command line?

**Comment by rhyshanan** [comment]
heres a higher resolution of the example video

LosslessCut - cut feature (higher resolution).mkv

| 
| 
|  | 
LosslessCut - cut feature (higher resolution).mkv


 |

 |

 |




    On Thursday, 9 November 2023 at 08:42:44 pm NZDT, Rhys Hanan ***@***.***> wrote:  
 
  menu > tools > Last FFMPEG commands?I dont know how to use this feature.


I am using FFMPEG outside of LosslessCut(Version: 6.0-essentials_build-www.gyan.dev)



I have attached an example video of the problem as it happens
LosslessCut - cut feature.mp4

| 
| 
|  | 
LosslessCut - cut feature.mp4


 |

 |

 |




EXAMPLE VIDEO
there is an image ... placed between two black flickers ... i would like to delete this image ...but cannot ... because LosslessCut is not able to isolate the 2 cuts properly

I can provide another video ... proving that FFMPEG ... does not have this same problem ... it is able to perform this cut accurately.


Can you please confirm that this problem exists, as you mentioned beforedo you mean lossless-cut/issues.md at master · mifi/lossless-cut ?

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
lossless-cut/issues.md at master · mifi/lossless-cut

The swiss army knife of lossless video/audio editing - mifi/lossless-cut
 |

 |

 |





    On Thursday, 9 November 2023 at 07:55:31 pm NZDT, Mikael Finstad ***@***.***> wrote:  
 
 


Could you provide the ffmpeg commands coming from losslesscut (see the menu) for the same cuts you did from the command line?

**Comment by mifi** [comment]
yes Last FFMPEG commands. Do your cut/export operation then open that page and copy the ffmpeg command and paste it here.

I cannot see any of your attachments. I think because youre using email.

**Comment by rhyshanan** [comment]
ffmpeg -hide_banner -ss '1556.46408' -i 'C:\Users\User\Desktop\gameplay\.published\sniper\Tunnel Flanks\Battlefield 3 - Operation Metro - Round 5 (Tunnel Flank).mkv' -avoid_negative_ts make_zero -map '0:0' '-c:0' copy -map '0:1' '-c:1' copy -map_metadata 0 -movflags '+faststart' -default_mode infer_no_subs -ignore_unknown -f matroska -y 'C:\Users\User\Desktop\gameplay\.published\sniper\Tunnel Flanks\Battlefield 3 - Operation Metro - Round 5 (Tunnel Flank)-00.25.56.464-00.38.20.424-seg2.mkv'
 ffmpeg -hide_banner -i 'C:\Users\User\Desktop\gameplay\.published\sniper\Tunnel Flanks\Battlefield 3 - Operation Metro - Round 5 (Tunnel Flank).mkv' -t '1555.40849' -map '0:0' '-c:0' copy -map '0:1' '-c:1' copy -map_metadata 0 -movflags '+faststart' -default_mode infer_no_subs -ignore_unknown -f matroska -y 'C:\Users\User\Desktop\gameplay\.published\sniper\Tunnel Flanks\Battlefield 3 - Operation Metro - Round 5 (Tunnel Flank)-00.00.00.000-00.25.55.408-seg1.mkv'
 echo -e "file 'file:C:\Users\User\Desktop\gameplay\.published\sniper\Tunnel Flanks\Battlefield 3 - Operation Metro - Round 5 (Tunnel Flank)-00.00.00.000-00.25.55.408-seg1.mkv'\nfile 'file:C:\Users\User\Desktop\gameplay\.published\sniper\Tunnel Flanks\Battlefield 3 - Operation Metro - Round 5 (Tunnel Flank)-00.25.56.464-00.38.20.424-seg2.mkv'" | ffmpeg -hide_banner -f concat -safe 0 -protocol_whitelist 'file,pipe,fd' -i - -map '0:0' '-c:0' copy '-disposition:0' default -map '0:1' '-c:1' copy '-disposition:1' default -movflags '+faststart' -default_mode infer_no_subs -ignore_unknown -f matroska -y 'C:\Users\User\Desktop\gameplay\.published\sniper\Tunnel Flanks\Battlefield 3 - Operation Metro - Round 5 (Tunnel Flank)-cut-merged-1699516941386.mkv'


VS


FFMPEG
ffmpeg -ss 00:00:00 -i "C:\Users\User\Desktop\gameplay\.published\sniper\Tunnel Flanks\Battlefield 3 - Operation Metro - Round 5 (Tunnel Flank).mkv" -to 00:25:55 -c copy out0.mkv
ffmpeg -ss 00:25:56 -i "C:\Users\User\Desktop\gameplay\.published\sniper\Tunnel Flanks\Battlefield 3 - Operation Metro - Round 5 (Tunnel Flank).mkv" -to 00:38:20 -c copy out1.mkv

I then merge these 2 files ... using LosslessCut (merge feature)
and get an accurate cut result

    On Thursday, 9 November 2023 at 08:48:44 pm NZDT, Mikael Finstad ***@***.***> wrote:  
 
 


yes Last FFMPEG commands. Do your cut/export operation then open that page and copy the ffmpeg command and paste it here.

I cannot see any of your attachments. I think because youre using email.

**Comment by mifi** [comment]
It seems you are not cutting at the exact same times in your ffmpeg command vs in losslesscut: 00.25.55.408
What happens if you use the exact same time stamp in ffmpeg as in losslesscut?

**Comment by rhyshanan** [comment]
I have done as you suggested
I first tried this, and it gave an error
FFMPEG
ffmpeg -ss 00:00:00:000 -i "in.mkv" -to 00:25:55:408 -c copy out0.mkv
ffmpeg -ss 00:25:56:464 -i "in.mkv" -to 00:38:20:000 -c copy out1.mkv

so I changed the colon to a decimal point (00:25:55.408)


FFMPEG
ffmpeg -ss 00:00:00.000 -i "in.mkv" -to 00:25:55.408 -c copy out0.mkv
ffmpeg -ss 00:25:56.464 -i "in.mkv" -to 00:38:20.000 -c copy out1.mkv


now both exported videos from FFMPEG and LosslessCut ... look the same ... but they are both failing


    On Thursday, 9 November 2023 at 11:50:24 pm NZDT, Mikael Finstad ***@***.***> wrote:  
 
 


It seems you are not cutting at the exact same times in your ffmpeg command vs in losslesscut: 00.25.55.408
What happens if you use the exact same time stamp in ffmpeg as in losslesscut?

**Comment by mifi** [comment]
I assume by «they are both failing» you mean the cutpoints are off?
If so, what happens if you use the same split time that you used in ffmpeg (00:25:55) also in losslesscut?

**Comment by rhyshanan** [comment]
is there a way i can enter those exact numbers?
LosslessCut ... exports its cuts to a degree of like 2 seconds or more difference ... offset from the originally placed cut
in this example ... we're only talking about a 0.5
    On Friday, 10 November 2023 at 12:37:34 am NZDT, Mikael Finstad ***@***.***> wrote:  
 
 


I assume by «they are both failing» you mean the cutpoints are off?
If so, what happens if you use the same split time that you used in ffmpeg (00:25:55) also in losslesscut?

**Comment by mifi** [comment]
> LosslessCut ... exports its cuts to a degree of like 2 seconds or more difference ... offset from the originally placed cut in this example ... we're only talking about a 0.5

cuts are only possible on keyframes, see:

- [x] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists


> is there a way i can enter those exact numbers?

<img width="292" alt="Screenshot 2023-11-10 at 10 31 13" src="https://github.com/mifi/lossless-cut/assets/402547/562d7b9f-3af0-4773-9e77-0cfebaa3fe68">

**Comment by mifi** [comment]
closing this because it's working as expected. can reopen if there's concrete evidence that ffmpeg cli and losslesscut ffmpeg commands cut things differently
