### ISSUE TITLE
Support importing cutlist format

### ISSUE THREAD

**Issue by dreamflasher** [mifi/lossless-cut#1771]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

http://cutlist.at provides a large amount of user-provided "cut lists" for TV recordings of https://onlinetvrecorder.com – the format they use is "cutlist", specified here:

http://cutlist.at/faq/cutlist.html

Would be awesome if you would support this! Thank you for your amazing work!

**Comment by mifi** [comment]
Seems like a very niche format, I have never heard of it, and I cannot even find much about it on google (and no wikipedia article). I'm not going to spend any time on this unless it becomes a popular request, but if someone wants to make a PR to support it, I'm open to that. thanks!

**Comment by dreamflasher** [comment]
@mifi I'd be down for implementing it. Do you already have some way of reading ini files? I'd like to use this: https://github.com/shangerxin/config-ini – which could be used as a dependency or copied. What do you think?

**Comment by mifi** [comment]
could we use this one instead? https://github.com/npm/ini

**Comment by LOK-Soft** [comment]
I just created a PR to import cutlist file format... I did not use an library to parse the ini file but a (quite simple) custom JS
