### ISSUE TITLE
Application Flashback

### ISSUE THREAD

**Issue by wzgrx** [mifi/lossless-cut#1773]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 11

### Steps to reproduce

After downloading and decompressing the latest LosslessCut win x64
I copied the folder to "D:\Soft\LosslessCut-win-x64\LosslessCut.exe" and opened the exe file. The program cannot be opened and flashing back, but "D:\Desktop\Windows\LosslessCut-win-x64" can be opened. 
That's why. I don't want to put the program on the desktop

### Expected behavior

No flashing, can be opened

### Actual behavior

Application Flashback

**Comment by mifi** [comment]
so it works when running losslesscut from c:/ but not from d:/ ?

**Comment by wzgrx** [comment]
> so it works when running losslesscut from c:/ but not from d:/ ?

yes

**Comment by wzgrx** [comment]
> "D:\Soft\LosslessCut-win-x64\LosslessCut.exe"

"D:\Soft\LosslessCut-win-x64\LosslessCut.exe" cannot work
"D:\LosslessCut-win-x64\LosslessCut.exe" can work
It's strange， Is it a problem with soft？

**Comment by mifi** [comment]
honestly i have no idea. I'm thinking it could be something with your antivirus or security setup or permissions on your files. maybe you can try to run losslesscut from the command line and see if you get any error, and share it here. if not, I don't know what to do about this issue because i don't have windows to test on

**Comment by wzgrx** [comment]
> honestly i have no idea. I'm thinking it could be something with your antivirus or security setup or permissions on your files. maybe you can try to run losslesscut from the command line and see if you get any error, and share it here. if not, I don't know what to do about this issue because i don't have windows to test on

Okay, thank you for your reply. I'll try another method
