### ISSUE TITLE
Cannot continue exporting when exporting more than 100 fragments

### ISSUE THREAD

**Issue by XiHua0522** [mifi/lossless-cut#1775]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

I want to divide a video into many small segments and export them as MP4 format

### Expected behavior

Videos should be exported with 120 or more

### Actual behavior

Stop exporting and report an error when exporting 100 pieces

### Share log

![image](https://github.com/mifi/lossless-cut/assets/98436743/a14c76c3-c2a9-43d8-910b-9dec563dad7b)

error report：
Error: Command failed with exit code 1: D:\LosslessCut-win-x64\resources\ffmpeg.exe -hide_banner -f concat -safe 0 -protocol_whitelist file,pipe,fd -i - -map 0:0 -c:0 copy -disposition:0 default -map 0:1 -c:1 copy -disposition:1 default -movflags +faststart -default_mode infer_no_subs -ignore_unknown -video_track_timescale 60 -f mp4 -y D:\Desktop\淘宝短视频\CDUJB 内外牙组合\竖\CDUJB内外牙 组合 竖101.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001c5bc63b600] Auto-inserting h264_mp4toannexb bitstream filter
Input #0, concat, from 'fd:':
  Duration: N/A, start: 0.000000, bitrate: 24086 kb/s
  Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1080x1440 [SAR 1:1 DAR 3:4], 24086 kb/s, 60 fps, 60 tbr, 60 tbn
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc60.3.100 libx264
Stream map '0:1' matches no streams.
To ignore this, add a trailing '?' to the map.
    at makeError (D:\LosslessCut-win-x64\resources\app.asar\node_modules\execa\lib\error.js:60:11)
    at handlePromise (D:\LosslessCut-win-x64\resources\app.asar\node_modules\execa\index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "ffmpegExperimental": false,
    "preserveMovData": false,
    "movFastStart": true,
    "preserveMetadataOnMerge": false,
    "filePath": "D:\\Desktop\\CDUJB内外牙 组合 竖.mp4",
    "fileFormat": "mp4",
    "externalFilesMeta": {},
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "Main",
        "codec_type": "video",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 1080,
        "height": 1440,
        "coded_width": 1080,
        "coded_height": 1440,
        "closed_captions": 0,
        "film_grain": 0,
        "has_b_frames": 1,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "3:4",
        "pix_fmt": "yuv420p",
        "level": 42,
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "field_order": "progressive",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "id": "0x1",
        "r_frame_rate": "60/1",
        "avg_frame_rate": "93599/1560",
        "time_base": "1/60",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 93600,
        "duration": "1560.000000",
        "bit_rate": "14524944",
        "bits_per_raw_sample": "8",
        "nb_frames": "93599",
        "extradata_size": 55,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "creation_time": "2023-11-11T11:14:18.000000Z",
          "language": "und",
          "handler_name": "VideoHandler",
          "vendor_id": "[0][0][0][0]"
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "44100",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "initial_padding": 0,
        "id": "0x2",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/44100",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 68796529,
        "duration": "1560.011995",
        "bit_rate": "195721",
        "nb_frames": "67185",
        "extradata_size": 5,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "creation_time": "2023-11-11T11:14:18.000000Z",
          "language": "und",
          "handler_name": "SoundHandler",
          "vendor_id": "[0][0][0][0]"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "D:\\Desktop\\CDUJB内外牙 组合 竖.mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {
        "start": 0,
        "end": 13
      },
      {
        "start": 13,
        "end": 26
      },
      {
        "start": 26,
        "end": 39
      },
      {
        "start": 39,
        "end": 52
      },
      {
        "start": 52,
        "end": 65
      },
      {
        "start": 65,
        "end": 78
      },
      {
        "start": 78,
        "end": 91
      },
      {
        "start": 91,
        "end": 104
      },
      {
        "start": 104,
        "end": 117
      },
      {
        "start": 117,
        "end": 130
      },
      {
        "start": 130,
        "end": 143
      },
      {
        "start": 143,
        "end": 156
      },
      {
        "start": 156,
        "end": 169
      },
      {
        "start": 169,
        "end": 182
      },
      {
        "start": 182,
        "end": 195
      },
      {
        "start": 195,
        "end": 208
      },
      {
        "start": 208,
        "end": 221
      },
      {
        "start": 221,
        "end": 234
      },
      {
        "start": 234,
        "end": 247
      },
      {
        "start": 247,
        "end": 260
      },
      {
        "start": 260,
        "end": 273
      },
      {
        "start": 273,
        "end": 286
      },
      {
        "start": 286,
        "end": 299
      },
      {
        "start": 299,
        "end": 312
      },
      {
        "start": 312,
        "end": 325
      },
      {
        "start": 325,
        "end": 338
      },
      {
        "start": 338,
        "end": 351
      },
      {
        "start": 351,
        "end": 364
      },
      {
        "start": 364,
        "end": 377
      },
      {
        "start": 377,
        "end": 390
      },
      {
        "start": 390,
        "end": 403
      },
      {
        "start": 403,
        "end": 416
      },
      {
        "start": 416,
        "end": 429
      },
      {
        "start": 429,
        "end": 442
      },
      {
        "start": 442,
        "end": 455
      },
      {
        "start": 455,
        "end": 468
      },
      {
        "start": 468,
        "end": 481
      },
      {
        "start": 481,
        "end": 494
      },
      {
        "start": 494,
        "end": 507
      },
      {
        "start": 507,
        "end": 520
      },
      {
        "start": 520,
        "end": 533
      },
      {
        "start": 533,
        "end": 546
      },
      {
        "start": 546,
        "end": 559
      },
      {
        "start": 559,
        "end": 572
      },
      {
        "start": 572,
        "end": 585
      },
      {
        "start": 585,
        "end": 598
      },
      {
        "start": 598,
        "end": 611
      },
      {
        "start": 611,
        "end": 624
      },
      {
        "start": 624,
        "end": 637
      },
      {
        "start": 637,
        "end": 650
      },
      {
        "start": 650,
        "end": 663
      },
      {
        "start": 663,
        "end": 676
      },
      {
        "start": 676,
        "end": 689
      },
      {
        "start": 689,
        "end": 702
      },
      {
        "start": 702,
        "end": 715
      },
      {
        "start": 715,
        "end": 728
      },
      {
        "start": 728,
        "end": 741
      },
      {
        "start": 741,
        "end": 754
      },
      {
        "start": 754,
        "end": 767
      },
      {
        "start": 767,
        "end": 780
      },
      {
        "start": 780,
        "end": 793
      },
      {
        "start": 793,
        "end": 806
      },
      {
        "start": 806,
        "end": 819
      },
      {
        "start": 819,
        "end": 832
      },
      {
        "start": 832,
        "end": 845
      },
      {
        "start": 845,
        "end": 858
      },
      {
        "start": 858,
        "end": 871
      },
      {
        "start": 871,
        "end": 884
      },
      {
        "start": 884,
        "end": 897
      },
      {
        "start": 897,
        "end": 910
      },
      {
        "start": 910,
        "end": 923
      },
      {
        "start": 923,
        "end": 936
      },
      {
        "start": 936,
        "end": 949
      },
      {
        "start": 949,
        "end": 962
      },
      {
        "start": 962,
        "end": 975
      },
      {
        "start": 975,
        "end": 988
      },
      {
        "start": 988,
        "end": 1001
      },
      {
        "start": 1001,
        "end": 1014
      },
      {
        "start": 1014,
        "end": 1027
      },
      {
        "start": 1027,
        "end": 1040
      },
      {
        "start": 1040,
        "end": 1053
      },
      {
        "start": 1053,
        "end": 1066
      },
      {
        "start": 1066,
        "end": 1079
      },
      {
        "start": 1079,
        "end": 1092
      },
      {
        "start": 1092,
        "end": 1105
      },
      {
        "start": 1105,
        "end": 1118
      },
      {
        "start": 1118,
        "end": 1131
      },
      {
        "start": 1131,
        "end": 1144
      },
      {
        "start": 1144,
        "end": 1157
      },
      {
        "start": 1157,
        "end": 1170
      },
      {
        "start": 1170,
        "end": 1183
      },
      {
        "start": 1183,
        "end": 1196
      },
      {
        "start": 1196,
        "end": 1209
      },
      {
        "start": 1209,
        "end": 1222
      },
      {
        "start": 1222,
        "end": 1235
      },
      {
        "start": 1235,
        "end": 1248
      },
      {
        "start": 1248,
        "end": 1261
      },
      {
        "start": 1261,
        "end": 1274
      },
      {
        "start": 1274,
        "end": 1287
      },
      {
        "start": 1287,
        "end": 1300
      },
      {
        "start": 1300,
        "end": 1313
      },
      {
        "start": 1313,
        "end": 1326
      },
      {
        "start": 1326,
        "end": 1339
      },
      {
        "start": 1339,
        "end": 1352
      },
      {
        "start": 1352,
        "end": 1365
      },
      {
        "start": 1365,
        "end": 1378
      },
      {
        "start": 1378,
        "end": 1391
      },
      {
        "start": 1391,
        "end": 1404
      },
      {
        "start": 1404,
        "end": 1417
      },
      {
        "start": 1417,
        "end": 1430
      },
      {
        "start": 1430,
        "end": 1443
      },
      {
        "start": 1443,
        "end": 1456
      },
      {
        "start": 1456,
        "end": 1469
      },
      {
        "start": 1469,
        "end": 1482
      },
      {
        "start": 1482,
        "end": 1495
      },
      {
        "start": 1495,
        "end": 1508
      },
      {
        "start": 1508,
        "end": 1521
      },
      {
        "start": 1521,
        "end": 1534
      },
      {
        "start": 1534,
        "end": 1547
      },
      {
        "start": 1547,
        "end": 1560
      }
    ],
    "mainFileFormatData": {
      "filename": "D:\\Desktop\\CDUJB内外牙 组合 竖.mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "1560.011995",
      "size": "2872183851",
      "bit_rate": "14729034",
      "probe_score": 100,
      "tags": {
        "major_brand": "isom",
        "minor_version": "512",
        "compatible_brands": "isomiso2avc1mp41",
        "creation_time": "2023-11-11T11:14:18.000000Z",
        "Hw": "1",
        "bitrate": "18000000",
        "maxrate": "0",
        "te_is_reencode": "1",
        "encoder": "Lavf58.76.100"
      }
    },
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "separate",
    "outSegTemplate": "${FILENAME}${SEG_NUM}${EXT}"
  },
  "platform": "win32",
  "version": "3.58.0"
}

**Comment by mifi** [comment]
hi. how did you solve this problem?
