### ISSUE TITLE
How to compile from source code?

### ISSUE THREAD

**Issue by artenax** [mifi/lossless-cut#1778]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Provide instructions, please. I have Ubuntu 22.04. I would like to recompile the program and increase the bitrate, it is too low, poor quality.

![lossless-cut](https://github.com/mifi/lossless-cut/assets/107228652/c0ce1a5e-a485-48d3-973c-93860d1b3d03)

**Comment by mifi** [comment]
Are you talking about smart cut bit rate?

https://github.com/mifi/lossless-cut/blob/master/.github/workflows/build.yml

**Comment by artenax** [comment]
> build.yml

What should I do with this file? Will GitHub build it?

> Are you talking about smart cut bit rate?

Yes.

**Comment by mifi** [comment]
> What should I do with this file? Will GitHub build it?

yes you can either use github actions in your fork, or you can translate/run commands from that file locally on your computer

> > Are you talking about smart cut bit rate?
> 
> Yes.

I already increased bitrate by 20%, but maybe that was not enough: https://github.com/mifi/lossless-cut/commit/c01f0cf4b2787dfa6b4dc152c032b999c5d7ccf9

see also existing discussions here: https://github.com/mifi/lossless-cut/issues/126#issuecomment-1623727817

What does `bit_rate` and `max_bit_rate` metadata say on the file you're trying to smart cut?

**Comment by artenax** [comment]
I installed nodejs 18.18.2
`sudo npm install -g yarn`

```
git clone https://github.com/mifi/lossless-cut
cd lossless-cut
git checkout abacff91a40e83002a7560cab481e372386141b3
```

In lossless-cut/src/smartcut.js
changed:
`videoBitrate = Math.floor(videoBitrate * 1.2)`
to:
`videoBitrate = Math.floor(videoBitrate * 20)`

```
yarn install
yarn build
yarn download-ffmpeg-linux-x64
yarn start
```

The program starts slowly, I encountered a packaging problem.
Now everything is fine, bitrate is normal.

I had two video files:
1. WebM VP9 from YouTube.
2. MKV H.264 encoded by me with crf 18.

On both of them only multiplier 20 is good.

**Comment by artenax** [comment]
I don't know how to use GitHub Actions, never tried it.

**Comment by mifi** [comment]
Can you share info about your file? Multiplier 20 seems quite extreme. I wonder why such a multiplier is necesaary

**Comment by mifi** [comment]
Do your files by any chance have bit rate «N/A» for the video track?

**Comment by mifi** [comment]
I think there’s a bug in the code that estimates bitrate when bit_rate is N/A. It estimates bit rate from size/duration, but that is bytes/sec, ffmpeg -b expects bits, so we need to multiply by 8 here: https://github.com/mifi/lossless-cut/blob/c01f0cf4b2787dfa6b4dc152c032b999c5d7ccf9/src/smartcut.js#L46

this also explains your high multiplier and also some people who complained about low quality some times

**Comment by mifi** [comment]
you can try new nightly build tomorrow if you like

**Comment by artenax** [comment]
> Can you share info about your file?

The file is regular, downloaded from YouTube https://www.youtube.com/watch?v=RtFocW6gi5c with yt-dlp, streams 247+251, mux in ffmpeg 6.0. WebM (VP9 720p + Opus). I don't have much traffic left, please download it yourself.

```
General
Format                                   : WebM
Format version                           : Version 4
File size                                : 182 MiB
Duration                                 : 28 min 40 s
Overall bit rate                         : 889 kb/s
Writing application                      : Lavf60.3.100
Writing library                          : Lavf60.3.100

Video
ID                                       : 1
Format                                   : VP9
Codec ID                                 : V_VP9
Duration                                 : 28 min 40 s
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Color space                              : YUV
Language                                 : English
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio
ID                                       : 2
Format                                   : Opus
Codec ID                                 : A_OPUS
Duration                                 : 28 min 40 s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Bit depth                                : 32 bits
Compression mode                         : Lossy
Language                                 : English
Default                                  : Yes
Forced                                   : No
```

> Do your files by any chance have bit rate «N/A» for the video track?

How can I check this?
The MediaInfo utility does not really show either the video bitrate or the audio bitrate. Only the total. Since everywhere is VBR, and info tags ffmpeg does not insert. However, even repackaging in MKVToolnix didn't help. MKVToolnix inserted info tags (track statistic tags) and MediaInfo utility showed bitrate, but only MediaInfo.

> I think there’s a bug in the code that estimates bitrate when bit_rate is N/A. It estimates bit rate from size/duration, but that is bytes/sec, ffmpeg -b expects bits, so we need to multiply by 8 here

LosslessCut selects a bitrate 3 times lower. I checked.

> you can try new nightly build tomorrow if you like

I could try. But I also like to choose the bitrate myself in my build.

**Comment by artenax** [comment]
I tried the [nightly build](https://github.com/mifi/lossless-cut/actions/runs/6875712546). It's much better now. The bitrate is higher by a factor of x1.07 ... x1.37. This was clearly a bit/byte problem, which you fixed. Thanks.
![lossless-cut](https://github.com/mifi/lossless-cut/assets/107228652/437279e3-8ebd-488d-a6a1-1456881680ad)
I'd like the bitrate even higher, of course. Because I'm still seeing some artifacts.
YouTube uses VP9 more efficiently, probably with a hardware encoder.

**Comment by artenax** [comment]
The nightly builds have an expiration date and require a github account, so I've [re-uploaded](https://github.com/artenax/lossless-cut/releases) them. They may be useful for those who don't have a github account.

**Comment by mifi** [comment]
cool. note that nightly builds will eventually turn into an actual release
