### ISSUE TITLE
Enhancement request: Make cutting framerate-agnostic (replace -t by -frames)  

### ISSUE THREAD

**Issue by MirkoArnold1** [mifi/lossless-cut#178]
Frame rate information in the video files are not always reliable. For a number of videos I wanted to cut, this resulted in the cut segments being far too long. In the generated ffmpeg commands, the start is defined by frame number, but the end by duration in seconds (which will go wrong if the frame rate of the file is not correctly reported).
Using the `-frame` option and provide the duration as number of frames instead of `-t` and duration in seconds, the length of the video will always match what is marked in the GUI.

**Comment by mifi** [comment]
I don't understand. The start -ss uses seconds, not frame number, right?

**Comment by MirkoArnold1** [comment]
Sorry, I don't remember now but somehow I assumed you start cutting using a frame number.
So it seems the -ss option manages to get to the right start position, but somehow the -t option ended up creating a video that was much too long. The frame rate that ffmpeg reported of the input video was not matching the framerate it was played back on video players (that is probably a rare case)

Since the start position is correct, maybe the -to option would work more reliably than the -t option

I'm afraid after this long time I don't have the videos with this issue anymore, so cannot provide one to replicate the issue. Feel free to close this and I'll report again if I find the issue again.

Thanks for this great tool!

**Comment by mifi** [comment]
Ok cool.
