### ISSUE TITLE
Interface freezing

### ISSUE THREAD

**Issue by eleius** [mifi/lossless-cut#1781]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Linux

### Steps to reproduce

Since version 3.52.0, when I start the appimage or its aur package on Arch Linux, LosslessCut displays a gray window ([screenshot](https://i.imgur.com/6WXKCdB.png)) and freezes for about 30 seconds, then starts normally.

I can't find any errors in the log. The last working version (no gray window, no delays) was 3.50.0.

With the latest version I also noticed empty menu items and freezing randomly (not 100% reproducible), for example after opening the Settings menu and scrolling with the sidebar. It's like there's some kind of issue with drawing the interface (maybe the qt libraries used in Arch? I have qt5 5.15.11 and qt6 6.6.0 installed)

### Expected behavior

There should be no delay/freezing

### Actual behavior

It freezes for a while

**Comment by mifi** [comment]
unfortuantely there's not much I can do about this, because it's most likely an issue with electron or linux. I don't have any specific code for linux in losslesscut so I don't see why it shouldn't work there. Closing because I don't have any actionable. I can only recommend trying other binary than appimage, or trying another linux based OS and see if the issue gets resolved. also try the latest nightly build of losslesscut and see if it helps.

**Comment by eleius** [comment]
It seems the issues reported above were caused by using the integrated amd graphics. When I switched to nvidia, the issues disappeared.
