### ISSUE TITLE
Custom paths for exports can result in invalid files in Windows

### ISSUE THREAD

**Issue by t3dotgg** [mifi/lossless-cut#1790]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

Hey y'all! Had a few issues where certain characters sneak into path names and break things badly in Windows. Biggest causes are spaces at end of file names and "..."

![image](https://github.com/mifi/lossless-cut/assets/6751787/3e0b8243-4851-44a7-a0b8-46e38644e83a)

### Expected behavior

File paths should be valid

### Actual behavior

File paths are invalid and break windows

**Comment by mifi** [comment]
Hi! This is with "No sanitize" right? (in the output file name template export settings):
<img width="469" alt="Screenshot 2023-12-02 at 00 17 16" src="https://github.com/mifi/lossless-cut/assets/402547/1ca83972-72da-480f-a315-fec364c545d1">

I think we could indeed still add some sanitazion even for the "no sanitize" mode. Do you have any concrete examples of file names that failed? I see that your screenshot has a file named `09 - End_of_Prime_reacts_to_is` - but I cannot see any `..` or trailing space there. And I cannot find any documentation saying the file names on windows cannot contain `..` or trailing space.

what does the output look like in the "preview" button dialog?

**Comment by mifi** [comment]
I have now changed logic when sanitize is on:

- disallow both forward and backward slashes on windows
- disallow file name ending with a space or a dot
