### ISSUE TITLE
Option to never show "Cleanup Files"

### ISSUE THREAD

**Issue by Rookiehome55** [mifi/lossless-cut#1797]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Wonderful app. After getting used to the features and configuring the different options I would like to suggest a checkbox in the Cleanup files screen to always confirm. This way I can immediately continue with my next to be clipped movie.

With my best regards

**Comment by Rookiehome55** [comment]
Hello, thanks for your reply I did not expect to hear from you this quick.

I did check that checkbox but it still requires to acknowledge the popup screen after every cut.

I see in your print that you have disabled the button, "Show this dialog every time". Where in my settings this was/is enabled.


After turning off the "show this dialog..." the original file is no longer deleted, a message box appears with

![Clipboard-1](https://github.com/mifi/lossless-cut/assets/152540668/1c429989-ec78-42a4-891d-c47c99f970ac)

That does not happen when I enable both "show this dialog every time" AND "Do all of this automagically......" in that case the original file is properly deleted.

I am a very happy user of this app, previously I used a different app that was sooo much slower cutting a 2160p video (reducing size to about 30 min) is now done in 10 seconds or less.
Thanks for your effords.

With my best regards
HBA

**Comment by Rookiehome55** [comment]
Sorry newbie on github closed the item but would still like you opinion on found issue.

**Comment by mifi** [comment]
which version of losslesscut are you running? related #272

**Comment by mifi** [comment]
will now retry deleting a few times, hopefully that fixes it

**Comment by Rookiehome55** [comment]
In response to your question which version do I use.
Version 3.58.0.0
I will check for an update and try again.
Regards
HBA

**Comment by Rookiehome55** [comment]
No update found, response with "Show this dialog every time" is still the original file is no longer deleted. with the described error message. When enabling the "Show this....." the original file is correctly removed bur requires one additional click to close the cleanup files. 
HBA

**Comment by mifi** [comment]
There isn’t any release but you can try nightly build
