### ISSUE TITLE
empty portion-accurate time

### ISSUE THREAD

**Issue by pcpsp0810csw** [mifi/lossless-cut#1799]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Keyframe cut mode
Accurate time but could leave an empty portion at the beginning of the video. Equiv to:
ffmpeg -i -ss ...

I just want accurate time but don't want extra empt portion（10s）
Please provide an option to improve

**Comment by mifi** [comment]
not enough information for me to help you here unfortunately. maybe try https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&projects=&template=file-issue.yml instead
