### ISSUE TITLE
Windows 10 .JS error

### ISSUE THREAD

**Issue by Ambush80** [mifi/lossless-cut#18]
hi there

        I am trying to run lossless cut on win 10 pro x64, no matter what video i load i get the same response after a few seconds, please find a screenshot attached, be happy if you could let me know how to fix it or make an update for your app tnx !
![2017 01 02-19 33](https://cloud.githubusercontent.com/assets/11506188/21595226/7c13c942-d123-11e6-8879-1c763f2ab4ff.png)

**Comment by mifi** [comment]
Hi.
Have you tried with completely different files? Like big bucks bunny or something similar.

Also could you run this on the command line using the included ffprobe.exe:
/path/to/LosslessCut/resources/app.asar.unpacked/ffprobe.exe -of json -show_format -i /path/to/your/file.mp4
And post what it prints out.

**Comment by Ambush80** [comment]
thanks for your response, i actually managed to get to the bottom of the problem, comodo antivirus has quite an aggressive sandbox and it was sandboxing a few of the files, which gave the resulting error when lossless cut was run, might be worth adding a recomendation to check antivirus etc is not blocking files in event of error etc, apart from that, it is running brilliantly now, good job !

**Comment by mifi** [comment]
Thanks, i added to readme.
