### ISSUE TITLE
Feedback: on Linux (Ubuntu 18.04.2 LTS) it works!

### ISSUE THREAD

**Issue by firepol** [mifi/lossless-cut#180]
Awesome program!

In the readme I read that Linux is untested, so I want to give you my feedback, as I just tested it.

In Ubuntu it worked like a charm. Here some details about the versions I'm using.

Ubuntu: 18.04.2 LTS
Nodejs: v10.16.0
npm: 6.10.1

So I think you can update the readme and remove that "untested" part which can scare Linux users for no reason ;)

**Comment by spiralofhope** [comment]
Or maybe change the untested text into a link to this ticket.  ;)

**Comment by mifi** [comment]
Ok thanks for testing! There are some other reports about some linux versions not working so I cannot completely guarantee that it works everywhere.
