### ISSUE TITLE
There should be a transparency effect in transitions between parts

### ISSUE THREAD

**Issue by ghost** [mifi/lossless-cut#1801]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [x] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Hello. First of all, thank you very much for the efforts you put into the software.

This is really the only software I use for video editing.

But I don't know if it was me who couldn't find it, but; It would be great if there was a setting to add a transparent transition between sections when you separate certain sections from a video.

Or there is, but I couldn't find it.

Can you help me?

Thank you again.

**Comment by mifi** [comment]
hi. not sure what you mean by transparent transition, but if you mean fade-in/out, then:

> - [x] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists

**Comment by annikinstarkiller** [comment]
> MERHABA. şeffaf geçişle ne kastettiğinizden emin değilim, ancak solma/kapanmayı kastediyorsanız, o zaman:
> 
> > * [x] Özelliğin zaten mevcut olup olmadığını görmek için [belgeleri](https://github.com/mifi/lossless-cut) ve [SSS, Bilinen sorunlar, Sorun Giderme belgelerini](https://github.com/mifi/lossless-cut/blob/master/issues.md) okuyun.

https://www.youtube.com/watch?v=NnDUmv2-Hzk (1.06 - 1.13)

For example, we divide a video into 2 parts, right? We combine the 2 videos we divided and watch them, but when transitioning from part 1 to part 2, I want the first part to fade away slowly, but it passes directly.

**Comment by annikinstarkiller** [comment]
> inanıyorum@mifi[SSS'deki](https://github.com/mifi/lossless-cut/blob/master/issues.md) ilk soruya atıfta bulunuyordu :
> 
> > LosslessCut... video klipler arasında solma/geçiş yapabilir mi?
> > Hayır, bunların hepsi kayıplı işlemlerdir (yani dosyayı yeniden kodlamanız gerekir), ancak gelecekte bu tür özellikleri uygulamaya başlayabilirim. #372

I don't quite understand, I'm sorry. It's been 3 years, has he added it yet?
