### ISSUE TITLE
Inverted merge file

### ISSUE THREAD

**Issue by kohehedit** [mifi/lossless-cut#1805]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

1) split a video into A and B
2) invert video A (upside down) into C
3) merge C and B into video D
4) now video D has C and INVERTED-B !!!!  (the expected result of D would be C and B)

### Expected behavior

the expected result of D would be C and B

### Actual behavior

D has C and INVERTED-B !!!!  

### Share log

No error occurred.

{
  "state": {
    "ffmpegExperimental": false,
    "preserveMovData": false,
    "movFastStart": true,
    "preserveMetadataOnMerge": false,
    "filePath": "D:\\＃＃Portable\\＃S\\Xferred\\B.mp4",
    "fileFormat": "mp4",
    "externalFilesMeta": {},
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 960,
        "height": 544,
        "coded_width": 960,
        "coded_height": 544,
        "closed_captions": 0,
        "film_grain": 0,
        "has_b_frames": 2,
        "sample_aspect_ratio": "136:135",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 31,
        "chroma_location": "left",
        "field_order": "progressive",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "id": "0x1",
        "r_frame_rate": "25/1",
        "avg_frame_rate": "25/1",
        "time_base": "1/12800",
        "start_pts": 1203,
        "start_time": "0.093984",
        "duration_ts": 52081152,
        "duration": "4068.840000",
        "bit_rate": "1655958",
        "bits_per_raw_sample": "8",
        "nb_frames": "101721",
        "extradata_size": 45,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "VideoHandler",
          "vendor_id": "[0][0][0][0]"
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "44100",
        "channels": 1,
        "channel_layout": "mono",
        "bits_per_sample": 0,
        "initial_padding": 0,
        "id": "0x2",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/44100",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 179437001,
        "duration": "4068.866236",
        "bit_rate": "69383",
        "nb_frames": "175228",
        "extradata_size": 5,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "SoundHandler",
          "vendor_id": "[0][0][0][0]"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "D:\\＃＃Portable\\＃S\\Xferred\\B.mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {}
    ],
    "mainFileFormatData": {
      "filename": "D:\\＃＃Portable\\＃S\\Xferred\\B.mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "4068.933984",
      "size": "882083046",
      "bit_rate": "1734278",
      "probe_score": 100,
      "tags": {
        "minor_version": "512",
        "major_brand": "isom",
        "compatible_brands": "isomiso2avc1mp41",
        "copyright": "firehood",
        "encoder": "Lavf58.36.100"
      }
    },
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "merge",
    "outSegTemplate": "${FILENAME}-${CUT_FROM}-${CUT_TO}${SEG_SUFFIX}${EXT}"
  },
  "platform": "win32",
  "version": "3.58.0"
}

**Comment by mifi** [comment]
I'm not sure what you mean by "invert video upside down":

> * invert video A (upside down) into C

**Comment by kohehedit** [comment]
I meant the video has rotated 180 degree ... upside down ...
1. split an original video into Video-A and Video-B
2. rotate video-A (using LosslessCut function at lower right corner, left of camera icon) into video-C
3. merge Video-C and Video-B into video-D (using LosslessCut function)
4. now video-D has Video-C and the-180-degree-rotated-Video-B !!!! (the expected result of video-D would be Video-C and Video-B merged)

**Comment by kohehedit** [comment]
I meant the video has rotated 180 degree ... upside down ...

Steps to duplicate the problem :
* split an original video into Video-A and Video-B
* rotate video-A (using LosslessCut function at lower right corner, left of camera icon) into video-C
* merge Video-C and Video-B into video-D (using LosslessCut function)
* now video-D has Video-C and the-180-degree-rotated-Video-B !!!! (the expected result of video-D would be Video-C and Video-B merged)
On Tue 05 Dec 2023 1:41:23 PM, Mikael Finstad ***@***.***> wrote:
I'm not sure what you mean by "invert video upside down":
* invert video A (upside down) into C

**Comment by mifi** [comment]
Ahh right. This is because a video’s rotation is just some metadata stored in a file. One file can only have a single rotation across the whole file, so if you have two files and you rotate only one file and merge them, then the rotation needs to be the same when they merge.

In other words: merging two files with different rotation metadata is an impossibility.
