### ISSUE TITLE
Officially-listed snap version is a year out of date

### ISSUE THREAD

**Issue by MMachado05** [mifi/lossless-cut#1806]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

The snap version of this application, which is the Linux version linked to on the [official website](https://mifi.no/losslesscut/), is running version 3.49.0. I am aware that the AppImage is newer, but it's not listed as an option on the website, so I assumed that the Snap is the recommended package format. Clearly this is not the case. The website should either be updated to link to an AppImage download, or the snap should be kept up-to-date with official releases.

**Comment by mifi** [comment]
thanks for the reminder. I have bump the version.

**Comment by MMachado05** [comment]
Thanks! Will there be a check implemented in the dev cycle to ensure all officially-listed formats are kept up to date from here on out? At least those that aren't just downloads (i.e. snap, flatpak if applicable)
