### ISSUE TITLE
Re-encode flac files in order to preserve duration

### ISSUE THREAD

**Issue by mifi** [mifi/lossless-cut#1809]
When trimming flac files using `copy` the duration doesn't get updated and remains as the original. Only happens with flac audio files. This is a bug in ffmpeg that seems will not be fixed. So we could workaround it by re-encoding flac (because it is lossless even when encoding, even though slower)

_Originally posted by @hazerflac7 in https://github.com/mifi/lossless-cut/discussions/1320_

**Comment by sahiljr-111** [comment]
This can be done by converting them to a different format and then back to FLAC.
1. convert the FLAC file to a .wav  -> `ffmpeg -i original.flac -c:a pcm_s24le intermediate.wav`
2. trim the file ->` ffmpeg -ss start_time -i intermediate.wav -to end_time -c:a pcm_s24le trimmed_intermediate.wav`
3. convert trimmed file to FLAC -> `ffmpeg -i trimmed_intermediate.wav -c:a flac final_trimmed.flac`

**Comment by Freso** [comment]
Those specific commands would drop any metadata from the FLAC though, though I guess there are ways to add that back.

Is there an upstream (ffmpeg) issue/ticket for this?

**Comment by mifi** [comment]
I've found these:
- https://trac.ffmpeg.org/ticket/10287
- https://trac.ffmpeg.org/ticket/4905

**Comment by sahiljr-111** [comment]
@Freso you can use additional options to copy the metadata from the original FLAC file to the final trimmed FLAC file

**Comment by Gevaarlijk** [comment]
I've found an app called Audacity that cuts flacs the way it should without messing up the times.

**Comment by mifi** [comment]
losslesscut can also do it now, if you want you can test it in the latest nightly build: https://github.com/mifi/lossless-cut/actions/runs/10585664608
