### ISSUE TITLE
[Feature Request] "Play selected segments"

### ISSUE THREAD

**Issue by fourteen-1** [mifi/lossless-cut#1815]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Ability to select multiple created segments and play them continually in order. Pretty self-explanatory.

**Comment by mifi** [comment]
Isn't this already a feature?

<img width="512" alt="Screenshot 2023-12-11 at 18 05 42" src="https://github.com/mifi/lossless-cut/assets/402547/518106e8-38e4-4f2c-8edc-91130a9f1bae">
