### ISSUE TITLE
load all keyframes on file open/import (ideally via multi-threading)

### ISSUE THREAD

**Issue by cy-gh** [mifi/lossless-cut#1818]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

There are various issues (#1018, #1311) regarding keyframes, and to me it seems the underlying problem is that LC runs ffprobe very conservatively only for the vicinity of cursor position and in single-thread, which can be seen in console & process explorer. An option like "load/derive all keyframes on open" (ideally via multi-threading) is missing. Even when "detect all scene changes" is run, there are a lot of missing keyframes, which can be easily seen in zoomed in timeline.

Multi-threading would speed up the initial keyframe derivation immensely; my CPU has 24 HT cores but every couple seconds LC waits for ffprobe on a single core running under full load, while other cores are idling.

**Comment by mifi** [comment]
I believe this is the same as #563
