### ISSUE TITLE
Some videos flicker when dropped into lossless cut

### ISSUE THREAD

**Issue by emacs-elements** [mifi/lossless-cut#1819]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Linux

### Steps to reproduce

Drag and drop an mp4 file into losslesscut.

### Expected behavior

Video should play smoothly.

### Actual behavior

The video flickers although it plays. I have tested this out on both flathub and appimage versions.

### Share log

N/A

**Comment by mifi** [comment]
what does flicker mean? rapid sporadic frames of white pixels? have you tried on a different computer and with a different file?

**Comment by emacs-elements** [comment]
I cannot replicate the problem on another OS. I am therefore closing this issue. Thank you for responding.
