### ISSUE TITLE
Update macOS Icon to Big Sur Style

### ISSUE THREAD

**Issue by reales** [mifi/lossless-cut#1820]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

I'd like to request an update of the macOS icon to the Big Sur style for better consistency with the latest macOS releases. I'm attaching an icon file to facilitate the task.

<img width="128" alt="icon" src="https://github.com/mifi/lossless-cut/assets/13709183/c9fcadd1-daa9-49a3-9616-cb577b3c1c9b">

[icon.zip](https://github.com/mifi/lossless-cut/files/13730781/icon.zip)

**Comment by mifi** [comment]
Not sure if simply wrapping the logo inside a rounded square is the best way. Ideally I think the [original svg](https://github.com/mifi/lossless-cut/blob/master/src/icon.svg) should be modified so that the whole blue background (now round) is exapnded to a rounded square.

**Comment by reales** [comment]
I get your point. Something like this?

![icon](https://github.com/mifi/lossless-cut/assets/13709183/a79fa30b-1aeb-4068-940a-121befb7256c)

[icon.zip](https://github.com/mifi/lossless-cut/files/13737746/icon.zip)

**Comment by mifi** [comment]
exactly! although the SVG looks a bit blurry, I think it has a rasterized image inside:

<img width="418" alt="Screenshot 2023-12-21 at 16 11 00" src="https://github.com/mifi/lossless-cut/assets/402547/e6c07565-2dec-463c-851d-994dd08ac731">

would be nice to have this in pure vector svg for max quality

**Comment by reales** [comment]
I'm using the raster layer for the shadow and the iOS corner radius, which can be tricky to copy in vector tool apps, at least in my experience 🙂 Since the icons are going to be bitmaps, I don't see it being a problem. I've included a new SVG file with 400 DPI raster images. You shouldn't really notice it with the usual icon sizes.

[icon.svg.zip](https://github.com/mifi/lossless-cut/files/13738946/icon.svg.zip)

**Comment by mifi** [comment]
I made one based on this template: https://gist.github.com/thecodewarrior/56b2aeee751fc23c4945c8c232b37c81

Then I just deleted everything except the rounded rect, copied the color and added drop-shadow filter and copy pasted the original svg markup ontop of it:

![icon-mac](https://github.com/mifi/lossless-cut/assets/402547/3da1d49d-088e-4b25-9c18-92a0022a8c66)

the problem now is that I'm a total svg noob so i dunno how to extend the lines of that darker colored shadow "ray" 😄

**Comment by mifi** [comment]
i tried to ask chatgpt and github copilot to do it but they failed:

![gpt](https://github.com/mifi/lossless-cut/assets/402547/dbe9bc13-8e43-42b6-9554-0012187eefb7)

**Comment by reales** [comment]
Thanks for the template, it will solve the iOS radius issue. The colored shadow can be easily created with a vector tool, but Affinity Designer doesn't support shadows. I'll check if it can be done through a text editor.

**Comment by reales** [comment]
This is completely vectorized. The only thing missing now is the shadow.

![icon](https://github.com/mifi/lossless-cut/assets/13709183/b6838b21-2155-4e68-9e2b-6daa25c5b1bc)

[icon.svg.zip](https://github.com/mifi/lossless-cut/files/13740373/icon.svg.zip)

**Comment by reales** [comment]
Drop shadow filter applied. It's now entirely vector-based. You can easily adjust the parameters to your liking using a text editor.

![icon_filter_shadow](https://github.com/mifi/lossless-cut/assets/13709183/5304f088-10f1-4ef9-b23c-0b4be14e63a5)

[icon.svg.zip](https://github.com/mifi/lossless-cut/files/13741660/icon.svg.zip)

**Comment by mifi** [comment]
thank your very much! cec54056a6514f217f884a1c4bd44c873397be41
