### ISSUE TITLE
"Unsupported file" error when opening a read only file...

### ISSUE THREAD

**Issue by wielandjeff** [mifi/lossless-cut#1822]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

I have dozens of read only mp4's on my network share (Unraid server). They all play fine, no errors/corruption. However, when I drag any of them to LosslessCut (3.58.0.0) I get a "Unsupported file" error and the following console output...

"
index-3ee52d33.js:298 userOpenFiles
index-3ee52d33.js:298 //Movies\test.mp4
index-3ee52d33.js:298 State reset
index-3ee52d33.js:299 userOpenFiles Error: Unsupported file: Command failed with exit code 1: C:\Apps\LosslessCut-win-x64\resources\ffprobe.exe -of json -show_chapters -show_format -show_entries stream -i //Movies\test.mp4 -hide_banner
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001bf20287dc0] moov atom not found
//Movies\test.mp4: Invalid data found when processing input
"

If I copy the exact same file to my local drive (no longer read only), LosslessCut can open/edit it just fine.

I'm slowly researching the "moov atom", but like I said, the videos all play fine, so the files themselves are not broken/corrupt. 

### Expected behavior

LosslessCut should open the file, read only or not.

### Actual behavior

LosslessCut can't open files on a read only network share.

### Share log

"
index-3ee52d33.js:298 userOpenFiles
index-3ee52d33.js:298 //Movies\test.mp4
index-3ee52d33.js:298 State reset
index-3ee52d33.js:299 userOpenFiles Error: Unsupported file: Command failed with exit code 1: C:\Apps\LosslessCut-win-x64\resources\ffprobe.exe -of json -show_chapters -show_format -show_entries stream -i //Movies\test.mp4 -hide_banner
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001bf20287dc0] moov atom not found
//Movies\test.mp4: Invalid data found when processing input
"

**Comment by mifi** [comment]
hmm, seems something might be wrong with the path. it tries to open `\Movies\test.mp4`. AFAIK on windows a path cannot start with a single slash and it needs to include the drive. what's the actual path to the file? does the same happen if you do file->open?

**Comment by wielandjeff** [comment]
*the network path got formatted when posting above, it is indeed actually "\\Movies\test.mp4"

**Comment by mifi** [comment]
hmm that's odd. does the same happen if you mount the share as a drive, e.g. `K:\` (`net use k: \\Movies`)?

I wonder if we need to use `file:\\` as [seen here](https://trac.ffmpeg.org/ticket/9166). any chance you could see if this works from the command line?

```bash
C:\Apps\LosslessCut-win-x64\resources\ffprobe.exe -of json -show_chapters -show_format -show_entries stream -i file:\\Movies\test.mp4 -hide_banner
```

**Comment by wielandjeff** [comment]
Ran the above ffprobe from command line, getting the same error...

"
{
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001c8a5e7dd80] moov atom not found
file:\\Movies\test.mp4: Invalid data found when processing input

}
"

Interestingly enough, if I drag the exact same "test.mp4" into Lossless Cut from a different read/write share (same Unraid server), then export a clip, then put the clip back onto the read only share, now everything works! The "test_clip.mp4" (which presumably has been "fixed" when it passed through Lossless Cut) will open JUST FINE in Lossless Cut (even though it's back on the read only share).

So I think what's going on is - Lossless Cut (and/or ffmpeg) is detecting something 'wrong' with the "moov atom" (whatever the heck that is), and is trying to repair/monkey with the file (which it can't, since it's read only), so it freaks out and throws the "Unsupported file" popup.

There must be a way to load/edit a video without needing write permissions to the original file... And like I said, this isn't an issue with just one 'bad' file, this is EVERY mp4 on the read only share (tons of different videos/sources).

**Comment by mifi** [comment]
Hmm. I highly doubt that ffprobe tries to write to the file. Ffprobe is a program that is meant to just read data from media files. I guess you could verify this by creating a readonly file on c:/ and try to open that and aee if it’s the same error.
What might be happening is maybe it cannot seek the file? Maybe the file system is not seekable? I know ffprobe needs to seek back and forth to look for the moov atom. Either that or it simply cannot read from the file, but it throws this confusing error message.

**Comment by wielandjeff** [comment]
All the files play fine (and are seekable), directly off the read only network share. Tested several different media players.

The thing that confuses me the most - I just ran another test with a random mp4 video file. If I try to load it into Lossless Cut directly off the read only share, I get "Unsupported file".

However, if I pull the file down to my local machine, not only does it load in just fine, but if I export a clip, then send the clip back to the read only share, everything magically starts working. I can now load the new clip DIRECTLY into Lossless Cut (straight off the read only share), just as you would expect, no problems.

So it's like when exporting a clip, Lossless Cut modified the file format somehow and now it's more 'readable'? But why do the original files (which don't seem to be corrupt in any way) load in fine as long as they aren't on this read only share? All the mp4s on my other read/write share load in just fine, so I don't think it's a problem with my network/Unraid server...

**Comment by mifi** [comment]
I cannot explain this unfortunately. I don't have any way to reproduce this problem.

**Comment by mifi** [comment]
can you try again with the latest version?

**Comment by eebambe** [comment]
I am having a similar issue where LLC won't open files anymore saying "Unsupported file" and I did not used to have this problem even after trying with the latest version

**Comment by eebambe** [comment]
are you asking if i'm still having the same issue if I try using LLC with a file that's on my network drive?

**Comment by mifi** [comment]
> are you asking if i'm still having the same issue if I try using LLC with a file that's on my network drive?

yes im wondering how to reproduce your problem and more details about your system, files, and which file types it happens with, and since which version you started getting this error message. (and are you not getting the error for older versions with the exact same files? if so which version did it start to appear?)

**Comment by mifi** [comment]
closing due to lack of response
