### ISSUE TITLE
Get an error when starting the program "Cannot read properties of undefined (reading 'replace')"

### ISSUE THREAD

**Issue by acceleratorlastorder** [mifi/lossless-cut#1823]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

Download the LosslessCut-win-x64.7z unpack it, and double click on the LosslessCut.exe

### Expected behavior

Being able to drop in or click on open file to start a project

### Actual behavior

Error on start
![image](https://github.com/mifi/lossless-cut/assets/22743445/c34e639c-9b17-4fab-9b12-409ba72e5102)

### Share log

TypeError: Cannot read properties of undefined (reading 'replace')
    at xe (file:///C:/LosslessCut-win-x64/resources/app.asar/vite-dist/assets/index-18074aaf.js:167:13763)
    at R.U._bindMultiple (file:///C:/LosslessCut-win-x64/resources/app.asar/vite-dist/assets/index-18074aaf.js:167:14141)
    at R.bind (file:///C:/LosslessCut-win-x64/resources/app.asar/vite-dist/assets/index-18074aaf.js:167:14306)
    at file:///C:/LosslessCut-win-x64/resources/app.asar/vite-dist/assets/index-18074aaf.js:167:15681
    at Array.forEach (<anonymous>)
    at file:///C:/LosslessCut-win-x64/resources/app.asar/vite-dist/assets/index-18074aaf.js:167:15649
    at jv (file:///C:/LosslessCut-win-x64/resources/app.asar/vite-dist/assets/index-18074aaf.js:40:24283)
    at Dd (file:///C:/LosslessCut-win-x64/resources/app.asar/vite-dist/assets/index-18074aaf.js:40:42406)
    at file:///C:/LosslessCut-win-x64/resources/app.asar/vite-dist/assets/index-18074aaf.js:40:40723
    at $ (file:///C:/LosslessCut-win-x64/resources/app.asar/vite-dist/assets/index-18074aaf.js:25:1658)

{
  "err": {},
  "platform": "win32",
  "version": "3.59.0"
}

I hope this can help !

Best regards.

**Comment by mifi** [comment]
oops I found the issue. will release a new version with a fix

**Comment by mifi** [comment]
after upgrading you need to delete your configuration file `config.json` inside LosslessCut folder inside your `%APPDATA%`. See [how to find APPDATA](https://www.freecodecamp.org/news/appdata-where-to-find-the-appdata-folder-in-windows-10/)

**Comment by mifi** [comment]
alternatively you can fix it before upgrading by editing `config.json` and find `"key": "f"` and replace it with `"keys": "f"` (note the added `s`)

**Comment by mifi** [comment]
fixed in 5d8fd422a565adaa90dbacc07346e5dce8650af0

**Comment by Hrxn** [comment]
@mifi I'm still on LosslessCut 3.58.0 at the moment, yet wanted to make the changes you suggested in your last comment, and my `config.json` does not have any `"key":` JSON values, instead it looks like this:

```json
..
	"keyBindings": [
		{
			"keys": "plus",
			"action": "addSegment"
		},
		{
			"keys": "space",
			"action": "togglePlayResetSpeed"
		},
		{
			"keys": "k",
			"action": "togglePlayNoResetSpeed"
		},
..
```

How come? Or was this only the default association to this one very specific keybind?

**Comment by mifi** [comment]
You only need to make the change if you upgraded to 59.0

**Comment by Hrxn** [comment]
Got it, thanks!

**Comment by acceleratorlastorder** [comment]
Thanks a lot and good job!
