### ISSUE TITLE
Change smart cut AV1 encoder to libsvtav1

### ISSUE THREAD

**Issue by BuyMyMojo** [mifi/lossless-cut#1825]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

By default just using `av1` as the encoder in ffmpeg will use the aomav1 encoder which is extraordinarily slow, detecting when the content is is av1 and smart cut is enabled the encoder should be set to `libsvtav1` for a substantially improved experince

**Comment by mifi** [comment]
I've added the suggestion to #126 OP - closing this to keep issue count down

**Comment by mifi** [comment]
next nightly build will use libsvtav1
