### ISSUE TITLE
Feature to highlight export size

### ISSUE THREAD

**Issue by Rytoxz** [mifi/lossless-cut#1827]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

I use this program to trim clips for Discord where my file size limit is 50 MB. Using keyframe cut, I frequently have to reduce keyframes on clips to get under the file size amount. Is it possible from a technical standpoint to offer a feature where file size is shown before exporting so that I could know - or is this not possible?

**Comment by mifi** [comment]
It would be possible to estimate the output size by multiplying input size by the duration of the exported cut, but it will not be accurate at all. Not sure if that would be helpful for keeping the size below 50mb though

**Comment by mifi** [comment]
closing for now
