### ISSUE TITLE
RENEWED DEMO how to ADD COVER ART in youtube

### ISSUE THREAD

**Issue by McEilif** [mifi/lossless-cut#1828]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Hi - is there any chance that you can make a renewed video for youtube how to add Cover Art. The youtube video from 2021 is not working for the new UI.

I have found the metakey "attached_pic", but I must do something wrong as the videos doesn't change "Look" in Windows...

(My aim is to get an optical overview of files in my folders IF i have turned on thumbs in my windows 10.)

![Burgen - Monumente der Macht - Maurenfestung Gibralfaro (Thumb)](https://github.com/mifi/lossless-cut/assets/118133964/0ff10283-a165-4378-9c78-e6bcbbeee1e1)

[Screendump Sequence Complete.zip](https://github.com/mifi/lossless-cut/files/13760317/Screendump.Sequence.Complete.zip)

![LossLessCut - Add Cover Art (Something is missing)-00 00 02 000](https://github.com/mifi/lossless-cut/assets/118133964/46472cdb-b51d-497c-a6af-b2d206e4a013)
![LossLessCut - Add Cover Art (Something is missing)-00 01 10 000](https://github.com/mifi/lossless-cut/assets/118133964/858a9074-64c3-443a-b953-110a65b4b4fc)

![LossLessCut - Add Cover Art (Something is missing)-00 00 30 000](https://github.com/mifi/lossless-cut/assets/118133964/3db839e3-de88-43bd-996d-74a1cb9a33b9)

**Comment by mifi** [comment]
does this problem happen with all files? Also I noticed you enabled the "bin_data" track, does it make a difference? I just tried this and for me it works (MacOS Finder shows the thumbnail correctly in the exported file). Maybe try a different jpeg file or different mp4 file and see if it makes a difference. and check inside VLC whether VLC can see the thumbnail

**Comment by McEilif** [comment]
I don't know why it has bin_data track on some and on some not - I guess that has to do with source of the video, fx, my Panasonic BD-recorder, Mobile phone, Drone, GoPro-camera aso. But it does no difference no.

I kinda thought it would be best to make a dump from the original file, so the dump had same proportions - and did it from VLC and from LosslessCut - no difference either - at least in windows 10 - I am installing a PC with Linux now, trying that out later - I tell you what happens. Happy new year!

**Comment by mifi** [comment]
unfortunately i cannot reproduce this problem, so there's nothing actionable here for me. maybe try again with the latest version
