### ISSUE TITLE
Segment tag editor enhancement

### ISSUE THREAD

**Issue by s2xnetx** [mifi/lossless-cut#1829]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

https://github.com/mifi/lossless-cut/issues/1766 this enhancement is great thank you, and I still have ideas :)

- Ability to define default metadata in program level (which will available for any opened video). Like "Place", "Weather", "Person". And this can be extended with new metas in any segment. Maybe default value for these elements should be available.
- Keyboard shortcut for opening Segment tags for the active segment.
- If you click add meta and enter data and wont click on the edit button, when clicking again to add meta it wont save the previously entered meta.

**Comment by mifi** [comment]
> * Ability to define default metadata in program level (which will available for any opened video). Like "Place", "Weather", "Person". And this can be extended with new metas in any segment. Maybe default value for these elements should be available.

see #427

> * Keyboard shortcut for opening Segment tags for the active segment.

good idea

> * If you click add meta and enter data and wont click on the edit button, when clicking again to add meta it wont save the previously entered meta.

ok fixed

**Comment by s2xnetx** [comment]
#427 is not what i mean. My new idea was the ability to create metas without opening a video, like "Place", "Person", "Weather". After that when you open any video these metas are there by default when you open segment tag editor. So this way you dont need to enter your default meta names for every segment. You only need to enter data for them.

You can add additional metas beside the defaults like currently (like "Daytime").

Also you should be able to fill defaults for your predefined metas, like "Place":"Outdoor", then every segments get those prefilled metas and datas, and you can edit them for your segments.

**Comment by mifi** [comment]
Ok I will add it to that issue
