### ISSUE TITLE
[Feature Request] Add version info to about dialog

### ISSUE THREAD

**Issue by Perkolator** [mifi/lossless-cut#1830]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

With linux AppImage, this is what is shown in the about dialog:

![image](https://github.com/mifi/lossless-cut/assets/53913724/cd20e651-8c62-44f2-8ba6-adcf19c3dac3)

Please add a version number to this dialog. Thank you.

**Comment by mifi** [comment]
duplicate #1537
