### ISSUE TITLE
SHA256 checksums for the release files

### ISSUE THREAD

**Issue by Perkolator** [mifi/lossless-cut#1831]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Please add SHA256 checksums for the release files. Either as a downloadable text file with all the checksums for all the files of a release, or as text in the notes of a github release. EDIT: or both. Thanks!

**Comment by mifi** [comment]
there is already a latest-mac.yml and latest-linux.yml with checksums. latest-win.yml seems to be missing but this is due to a bug in electron builder. I don't have time to workaround this now but I'm sure PR is welcome at electron-builder repo. See #621

**Comment by Perkolator** [comment]
> there is already a latest-mac.yml and latest-linux.yml with checksums.

Nope. The `sha512: AOBpKvMgxmcdCslaOz5WjN+Ey9OquXXJvc8tSow8QG2NPwFcfBBeNjo/freP2a+FABzTbAVBge3I1+0Z74GBrw==` that's (twice) in the `latest-linux.yml` file is not a SHA512 hash.

I get `00e0692af320c6671d0ac95a3b3e568cdf84cbd3aab975c9bdcf2d4a8c3c406d8d3f015c7c105e363a3f7eb78fd9af85001cd36c054181edc8d7ed19ef8181af` as the real SHA512 for `LosslessCut-linux-x86_64.AppImage` file.

**Comment by mifi** [comment]
hmm, maybe there are more bugs in electron-builder then if all the checksums are wrong. I don't know how to fix this unfortunately. The problem is that I don't know how to easily add additional files to the github release in [action-electron-builder](https://github.com/samuelmeuli/action-electron-builder). But if you know how to do that easily, a PR is welcome!
