### ISSUE TITLE
Editing TS files Front cut point is stuck

### ISSUE THREAD

**Issue by lbcake** [mifi/lossless-cut#1833]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

Editing TS files

### Expected behavior

Video should play smoothly.

### Actual behavior

Front cut point is stuck

### Share log

N/A

**Comment by mifi** [comment]
Does it happen with all ts files?

**Comment by lbcake** [comment]
> Does it happen with all ts files?

YES, Edited clips  Almost all。

**Comment by mifi** [comment]
I just tested with a TS file and it works for me. you can try a different. maybe also see https://github.com/mifi/lossless-cut/blob/master/issues.md#common--known-issues--troubleshooting

**Comment by mifi** [comment]
your share doesn't work:

<img width="345" alt="Screenshot 2023-12-31 at 11 46 27" src="https://github.com/mifi/lossless-cut/assets/402547/21df9238-eae7-4033-aed2-3573f4f05264">

**Comment by lbcake** [comment]
> your share doesn't work:
> 
> <img alt="Screenshot 2023-12-31 at 11 46 27" width="345" src="https://private-user-images.githubusercontent.com/402547/293489052-21df9238-eae7-4033-aed2-3573f4f05264.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwODIxOTUsIm5iZiI6MTcwNDA4MTg5NSwicGF0aCI6Ii80MDI1NDcvMjkzNDg5MDUyLTIxZGY5MjM4LWVhZTctNDAzMy1hZWQyLTM1NzNmNGYwNTI2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMVQwNDA0NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NzJkYTY2Y2E2MmYzZWE3MDQxNzU5MDFlYjc5ZjhlNGM3YmJhZjFjYTJkNjRlOWJhNzQ0MjY1NDJkYWMzOTIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ALIwO14_6Y0tD5qYmvW8IKurKwH3BI46I3uKEz7rmxk">



oh. this

https://drive.google.com/file/d/1Yk57Nr40pyuoGDuinBz1GSFZKhz3gTr2/view?usp=drive_link

**Comment by mifi** [comment]
remuxing to mp4 before cutting works for me: https://github.com/mifi/lossless-cut/blob/master/issues.md#mpeg-ts--mts

**Comment by lbcake** [comment]
> remuxing to mp4 before cutting works for me: https://github.com/mifi/lossless-cut/blob/master/issues.md#mpeg-ts--mts


yes. i konw

If TS cutting could optimize the cutting points, that would be great.     Only for TS

**Comment by mifi** [comment]
see #1839
