### ISSUE TITLE
Video & Audio Out-Of-Sync Suggestion To Fix

### ISSUE THREAD

**Issue by Github-Username-is-not-available** [mifi/lossless-cut#1837]
Hi everyone,

I've seen this issue mentioned as a (currently unresolved) bug already, so I'm going to try to come at this from a different angle. I have an mp4 video file I'm trying to snip down, but can't due to the video & audio being out-of-sync in LosslessCut (both in playback, & the outputted file). This is despite the file playing in-sync in video players, & playing in-sync in other video editors (in VideoPad it works in-sync).

Like I said, if this issue really can't be fixed, could you offer a feature whereby the audio & video may be shifted, compressed, or expanded in order to synchronise them together. Or perhaps implement a detection system to automatically sync them.

I've been stuck with not being able to find any way around this issue for months now, & would be very appreciative if someone can offer a solution for this. PS I'm using the latest version (v3.59.1.0).

Thank you,
Richard

**Comment by mifi** [comment]
Hi. There is a feature to speed up / slow down you media, if you click on the fps. Does that help?

**Comment by Github-Username-is-not-available** [comment]
Hi, thanks for the response mifi. I've tried the FPS setting, as you suggested. Although it changes the speed of overall playback, it doesn't bring into sync the video & audio. (I need a way of seperating the audio & video, it seems.) Thank you

**Comment by mifi** [comment]
thanks for sharing. this video clip is also out of sync when I play it back here in Chrome. So there's probably something wrong with the file. If what you need is to shift the audio track back/forward, that is not yet possible, but the feature request is described in this issue: #216 - I'm closing this issue as a duplicate then.

**Comment by Github-Username-is-not-available** [comment]
OK, thanks for having a look at my situation anyway. Happy New Year mate

**Comment by Github-Username-is-not-available** [comment]
To give a little more information, these videos are from old family VHS video cassettes. They have been converted using "Elgato Video Capture" which has helped me get the videos into digital computer format (.mp4 files).

However, some of these converted videos only play in VLC without issue. If I try to play the videos in (PC) Quicktime, some of the videos (including the one I'm having trouble with above) show the error message:

"Error -2002: a bad public movie atom was found in the movie.......(name of video)........."

So, I think this has something to do with my problem. The video conversion hardware has kind of corrupted (some of) the files. To be clear, they'll play back in VLC, fully synchronised BEFORE editing, but DURING or AFTER editing in a video editor, they don't play in sync.

Despite this, I still believe it would be worth you creating a video/audio syncing feature to overcome this, if possible. But anyway, I hope this info helps you to diagnose the problem. Thanks mate! Cheers,
-Richard

**Comment by mifi** [comment]
oh ithought the problem was that the source files were out of sync. i thought the file you shared was a source file. I assume it's not easy for you to share a source file, but if you can provide more technical info about the files, that would be helpful: https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&projects=&template=file-issue.yml

**Comment by Github-Username-is-not-available** [comment]
Hi MiFi,
I'm not sure what you mean by "source file". The videos are mp4 files which were created using this: https://www.amazon.co.uk/Elgato-Video-Capture-Digitise-iPad/dp/B00293CDG0

This means I can have all my old family videos from VHS cassettes (from the 1980's / 1990's) on my computer now.

The videos are recorded as .mp4 files, & they are otherwise untampered with. No other modification by me. Just the mp4 files

At the weekend, when I have more time, I'll see what I can do to provide you with more info, & fill out your attached form. I'll try to make a little video explaining too. Thanks for your help so far! Appreciated

**Comment by mifi** [comment]
basically I need to know whether the file you shared video.audio.out.of.sync.brief.example.mp4 is before or after being processed by losslesscut. and if this file is from after processing by losslesscut, was the audio in sync before processing with losslesscut?

**Comment by Github-Username-is-not-available** [comment]
Hi MiFi, I hope this helps to clarify which files were in-sync, & which ones were out-of-sync, & also clarify the "before", "during", & "after" stages.
Hopefully the links will work for you to view my video.
Thank you!

Video is 4:25 minutes long.
00:00 - 00:30 = short intro
00:30 - 01:51 = My situation regarding video Playback - BEFORE USING LOSSLESS-CUT.
01:51 - 03:40 = Video playback inside of LosslessCut - DURING USING LOSSLESS-CUT.
03:40 - 04:25 = Video playback post-processing - AFTER OUTPUT OF LOSSLESS-CUT.
https://drive.google.com/file/d/1Vl8XInQwk_NWVB-IXeAT5VXksuPdyXCi/view?usp=sharing
https://drive.google.com/file/d/1Vl8XInQwk_NWVB-IXeAT5VXksuPdyXCi/view?usp=drive_link

**Comment by mifi** [comment]
thanks for sharing. well i hope once #216 gets implemented, you can use that to synchronize your out-of-sync files.

**Comment by Github-Username-is-not-available** [comment]
> thanks for sharing. well i hope once #216 gets implemented, you can use that to synchronize your out-of-sync files.

Cool, thanks a lot for having a look at my situation mate! And thanks for Lossless-Cut - it's a great programme!
