### ISSUE TITLE
.m4a drag and drop is broken and right click 'open with' doesnt show lossless cut

### ISSUE THREAD

**Issue by RustoMCSpit** [mifi/lossless-cut#1841]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Linux

### Steps to reproduce

drag and drop .m4a or rigjt click and then open with (losslesscut doesnt show)

### Expected behavior

.

### Actual behavior

.

### Share log

linux mint lts cinnamon jammy jellyfish

**Comment by mifi** [comment]
I cannot reproduce this. not enough information to help

**Comment by RustoMCSpit** [comment]
> I cannot reproduce this. not enough information to help

Try to drag and drop a .m4a file on Linux Mint and it will fail, what more info needs to be provided?

**Comment by RustoMCSpit** [comment]
> Try to drag and drop a .m4a file on Linux Mint and it will fail, what more info needs to be provided?

Or a .mp3

**Comment by mifi** [comment]
what about an mp4?

**Comment by mifi** [comment]
what about other linux OS

**Comment by RustoMCSpit** [comment]
> and what is a "fail"?

The media you tried to open does not exist

**Comment by RustoMCSpit** [comment]
> what about other linux OS

no idea

**Comment by RustoMCSpit** [comment]
regardless this is core functionality broken, please re-open

**Comment by mifi** [comment]
the problem is that i cannot reproduce it, and you provided minimal information. please see https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&projects=&template=bug.yml

and nobody else reported this issue so it leads me to believe it's a problem on mint only or your computer only

**Comment by RustoMCSpit** [comment]
> the problem is that i cannot reproduce it, and you provided minimal information. please see https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&projects=&template=bug.yml
> 
> and nobody else reported this issue so it leads me to believe it's a problem on mint only or your computer only

i can do a screen recording show it happen if you want
