### ISSUE TITLE
Video previews play in 20 FPS

### ISSUE THREAD

**Issue by dongerlel** [mifi/lossless-cut#1851]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 11

### Steps to reproduce

![image](https://github.com/mifi/lossless-cut/assets/12804761/621c110e-48db-4546-8595-a95662eb8f53)

set this in nvidia control panel

### Expected behavior

it should not play in 20 fps

### Actual behavior

it plays in 20 fps even tho it's not in the background

**Comment by mifi** [comment]
sorry I don't know how to fix that. losslesscut is a cross platform app built on [electron](https://www.electronjs.org/)

**Comment by dongerlel** [comment]
@mifi
is there an older version which is not build on electron?

**Comment by mifi** [comment]
> is there an older version which is not build on electron?

no

> Do people behind electron know about this issue?

you can ask them
