### ISSUE TITLE
Let LC cut at NOT-key-frames - auto-calculate first key (B) frame?

### ISSUE THREAD

**Issue by pstein** [mifi/lossless-cut#1855]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

In general I appreciate LC very much. But one feature needs an improvement:

Occasionally I want to cut sections in the mid of a *.mp4 video at NON-key-frames (not at key frames).

Steps currently:
I navigate to the next key frame after the planned cut start position, 
then click frame backward icon until my target cut start position is reached
and mark in LC the start position simple frame
and finally export the video section interval.

Unfortunately LC exports it with/including the video stuff left (=before) the cut point until the previous key frame.
I wonder whether this couldn't be done more precisely.
LC could take the previous key-B-frame, then add the next simple "I" frames on top of it and finally insert the current cumulated "B" frame as new key frame at the first position. of the exported video interval.

Can this feature be added in the next release?

Thank you

**Comment by mifi** [comment]
Unfortunately I have no idea how to implement what you suggested using the ffmpeg CLI. But suggestions are welcome. See also #1216
