### ISSUE TITLE
Smoother "playback" when moving through timeline

### ISSUE THREAD

**Issue by vertigo220** [mifi/lossless-cut#1860]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

When scrolling forward/backward along the timeline, there's a slight lag/delay, so the video doesn't change smoothly/quickly as you scroll. When moving by frame, it's even worse, as the image doesn't change until you stop. Ideally, it should change quickly as you're scrolling or going forward/backward by frame, always showing the frame you're on, without any lag. As an example, Avidemux does this very well (as do VidCutter and PotPlayer, though both do far better forward than backward, and I only mention them to point out that it's more common than not that these functions are more smooth than in LC). Not sure if it's a lack of hardware acceleration or optimization, but it would be far easier to use if this were improved.

**Comment by mifi** [comment]
are you getting a warning "file not natively supported" when opening the file in losslesscut?

**Comment by vertigo220** [comment]
It does it with AVC files, both ones encoded in 264 and ripped from discs. If I advance forward/backward slowly, it works fine, but if I do so even somewhat quickly, it will only change the displayed frame every so often, every few to several frames depending on how quickly I do it. If I hold down the key, it doesn't change until I release it. Whereas in PotPlayer, even if I hold it down, it advances frame-by-frame very quickly (with audio, even), and while it doesn't work so well in reverse (holding it down works mostly the same way, though even then it will periodically change), I can press it repeatedly very quickly and it will work. And that's even with x265. And Avidemux works very well forwards and backwards. So it's clearly possible, and my system is capable of it, so it would be nice if LC could be made to do so as well.

**Comment by mifi** [comment]
what if you try to open the video file in google chrome and seek, do you see similar behaviour? im asking because losslesscut uses chrome's html5 video player, so it's at the mercy of its implementation

**Comment by vertigo220** [comment]
Can't even get chrome to play them, just keeps "downloading" them.

**Comment by mifi** [comment]
If you can provide a report from the help menu (report an error) then it’s easier to help.

**Comment by vertigo220** [comment]
No error occurred.

{
  "state": {
    "ffmpegExperimental": false,
    "preserveMovData": false,
    "movFastStart": true,
    "preserveMetadataOnMerge": false,
    "filePath": ".mkv",
    "fileFormat": "matroska",
    "externalFilesMeta": {},
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1080,
        "closed_captions": 0,
        "film_grain": 0,
        "has_b_frames": 4,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 41,
        "chroma_location": "left",
        "field_order": "progressive",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "24000/1001",
        "avg_frame_rate": "24000/1001",
        "time_base": "1/1000",
        "start_pts": 84,
        "start_time": "0.084000",
        "bits_per_raw_sample": "8",
        "extradata_size": 130,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "eng",
          "BPS-eng": "34641184",
          "DURATION-eng": "00:25:17.656000000",
          "NUMBER_OF_FRAMES-eng": "36380",
          "NUMBER_OF_BYTES-eng": "6571675272",
          "_STATISTICS_WRITING_APP-eng": "mkvmerge v47.0.0 ('Black Flag') 64-bit",
          "_STATISTICS_WRITING_DATE_UTC-eng": "2020-06-21 00:45:33",
          "_STATISTICS_TAGS-eng": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
        }
      },
      {
        "index": 1,
        "codec_name": "dts",
        "codec_long_name": "DCA (DTS Coherent Acoustics)",
        "profile": "DTS-HD MA",
        "codec_type": "audio",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "sample_fmt": "s32p",
        "sample_rate": "48000",
        "channels": 6,
        "channel_layout": "5.1(side)",
        "bits_per_sample": 0,
        "initial_padding": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/1000",
        "start_pts": 92,
        "start_time": "0.092000",
        "bits_per_raw_sample": "24",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "fre",
          "BPS-eng": "4039139",
          "DURATION-eng": "00:25:17.572000000",
          "NUMBER_OF_FRAMES-eng": "142240",
          "NUMBER_OF_BYTES-eng": "766210700",
          "_STATISTICS_WRITING_APP-eng": "mkvmerge v47.0.0 ('Black Flag') 64-bit",
          "_STATISTICS_WRITING_DATE_UTC-eng": "2020-06-21 00:45:33",
          "_STATISTICS_TAGS-eng": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
        }
      },
      {
        "index": 2,
        "codec_name": "hdmv_pgs_subtitle",
        "codec_long_name": "HDMV Presentation Graphic Stream subtitles",
        "codec_type": "subtitle",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/1000",
        "start_pts": 84,
        "start_time": "0.084000",
        "duration_ts": 1517664,
        "duration": "1517.664000",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 1,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "eng",
          "title": "Foreign Language (Forced)",
          "BPS-eng": "26197",
          "DURATION-eng": "00:23:20.121000000",
          "NUMBER_OF_FRAMES-eng": "420",
          "NUMBER_OF_BYTES-eng": "4584938",
          "_STATISTICS_WRITING_APP-eng": "mkvmerge v47.0.0 ('Black Flag') 64-bit",
          "_STATISTICS_WRITING_DATE_UTC-eng": "2020-06-21 00:45:33",
          "_STATISTICS_TAGS-eng": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
        }
      }
    ],
    "copyStreamIdsByFile": {
      ".mkv": {
        "0": true,
        "1": true,
        "2": true
      }
    },
    "cutSegments": [
      {}
    ],
    "mainFileFormatData": {
      "filename": ".mkv",
      "nb_streams": 3,
      "nb_programs": 0,
      "format_name": "matroska,webm",
      "format_long_name": "Matroska / WebM",
      "start_time": "0.084000",
      "duration": "1517.664000",
      "size": "7340896653",
      "bit_rate": "38695767",
      "probe_score": 100,
      "tags": {
        "encoder": "libebml v1.3.10 + libmatroska v1.5.2",
        "creation_time": "2020-06-21T00:45:33.000000Z"
      }
    },
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "separate",
    "outSegTemplate": "${FILENAME}-${CUT_FROM}-${CUT_TO}${SEG_SUFFIX}${EXT}"
  },
  "platform": "win32",
  "version": "3.59.1"
}

**Comment by mifi** [comment]
You could try to File -> Convert to supported format -> "Fast: Full quality remux, likely to fail" or "Fast: Remux video, encode audio (fails if unsupported video codec)"

**Comment by vertigo220** [comment]
Neither of those options made a difference, which isn't surprising since it was already a supported format. I'd also be very hesitant to use them since I wouldn't want to spend a bunch of time doing edits only to have it fail or, worse, have something not work right and not realize it and get a corrupted output file.

**Comment by mifi** [comment]
The fact that chrome tried to download it lead me to believe it’s not natively supported. However if you say that it’s supported, then I don’t know anything that can be done to improve this, because we’re at the mercy of chromium html5 player.
