### ISSUE TITLE
 want to set the default playback speed of the video to be edited. 

### ISSUE THREAD

**Issue by fanz010** [mifi/lossless-cut#1865]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

 want to set the default playback speed of the video to be edited.

I want to default to 1600 times

I want a shortcut key that I can change to any speed at once

When I go back to the normal speed, it's inconvenient to use the shortcut key several times until the maximum playback speed.

**Comment by fanz010** [comment]
I thought I did it.
I think I checked the log.

Determines the playback speed of lossless cuts when a file is imported.
I want to be up to 1600 times faster when  road it.

From standard playback speed, one shortcut key operation
I want to switch to 1600 times the maximum speed.

Would you consider it?

**Comment by mifi** [comment]
i don't know what you mean by this unfortunately. 1600 times what?

**Comment by fanz010** [comment]
I'm sorry I couldn't explain it well because I was not good at English

1
  When the new file is read for the first time, I want to set the
playback speed at the time of video editing to 1600 %

1600 % is 16x speed, right?

2
After returning the playback speed to normal
I want to make it 16 times faster with a single hot key.

200 400 800 1600 Up to maximum playback speed
I have to enter a hot key four times

I want to change to any above playback speed in one operation.

2024-01-23 16:03 GMT+09:00, Mikael Finstad ***@***.***>:

**Comment by fanz010** [comment]
To give you a better understanding of how it works, we have created a
video in MP4 format.
https://streamable.com/onbrd4

2024-01-24 2:53 GMT+09:00, 1 s ***@***.***>:

**Comment by mifi** [comment]
thanks. I will add your suggestion to #254 and close this to keep issue count down
