### ISSUE TITLE
I want a mode to change the order of segments As it stands

### ISSUE THREAD

**Issue by fanz010** [mifi/lossless-cut#1866]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

I want a mode to change the order of segments
As it stands, there is only a difficult edit list on the right side.

In full-screen segment edit mode
While viewing still images of the start and end points of a segment, drag, etc.
Intuitively, I want to sort.

I want it to be big on the screen including letters.
When the mouse cursor is placed on the start and end images, it should be enlarged to a reasonable size to make it easier to see.

**Comment by fanz010** [comment]
I think I checked the log.

It's inconvenient because I can't intuitively rearrange segments.
The segment number input replacement function is very difficult to use.

Could you create a new segment order editing mode?

Would you consider it?

**Comment by mifi** [comment]
You can drag drop segments using your mouse in the right segment panel. please open discussion instead of issue for these kinds of questions
