### ISSUE TITLE
 I want you to implement a seeker preview  Implement a seeker preview like MPC-HC  I want to set the desired preview image magnification.

### ISSUE THREAD

**Issue by fanz010** [mifi/lossless-cut#1867]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

I want you to implement a seeker preview

Implement a seeker preview like MPC-HC

I want to set the desired preview image magnification.

**Comment by fanz010** [comment]
There's a thumbnail function, but apart from that,
I think it would be useful if this software has a seek preview function.

**Comment by mifi** [comment]
Can you elaborate how it works? maybe some screenshots or screencast?

**Comment by fanz010** [comment]
MPC-HC is a well-known video playback software

To give you a better understanding of how it works, we have created a
video in MP4 format.
https://streamable.com/1r9cel
Thumbnails are useful to some extent, but
Please consider implementing it!

2024-01-23 15:47 GMT+09:00, Mikael Finstad ***@***.***>:

**Comment by mifi** [comment]
See "Thumbnails" under #483
