### ISSUE TITLE
Need more instructions , fulls examples how to use Loseless cut with the "TERMINAL"

### ISSUE THREAD

**Issue by APISeeker** [mifi/lossless-cut#1878]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

I would like, please, full examples with fully written lines to use on windows, on how to perform different tasks with LoselessCut using the terminal please.

**Comment by mifi** [comment]
It’s experimental. Feel free to submit a pr
