### ISSUE TITLE
mac os preview not playing video after cut

### ISSUE THREAD

**Issue by skywinder** [mifi/lossless-cut#1879]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with a different kind of file to confirm that the problem is related to just this file.
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [x] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Steps to reproduce

I've cut and exported a piece from a video shot on a DJI FPV drone. This issue only occurs with files from this drone; all other files work fine.

### Expected behavior

When I press space on my Mac for a preview, I expect to see a window open with the video playing. 

### Actual behavior

Instead, I see only a static preview image.

Attached is a screenshot with the data of the tracks and export details, as well as a short video showing how it looks with the original media and the cut versions.

### Provide an error report

![CleanShot 2024-01-30 at 18 52 30@2x](https://github.com/mifi/lossless-cut/assets/3356474/d549ce48-6e4d-4f94-8ced-d2d980b6fbac)
![Screenshot 2024-01-30 at 18 52 25](https://github.com/mifi/lossless-cut/assets/3356474/033edcd4-8c9b-4b6c-a076-2a0d8c32081f)

https://github.com/mifi/lossless-cut/assets/3356474/ddb387ed-e56b-4f69-8fb8-c22749d0b234

**Comment by mifi** [comment]
Hi. does it play back in Quicktime? Have you tried suggestions from FAQ/troubleshooting? in particular see if it helps to change output format to mov as well as disable the avc track. it's a bit hard to say what's causing this exactly without having a sample file to test

**Comment by mifi** [comment]
possible workarounds:
- disabling the 2nd (avc1) track
- avoid_negative_ts
- "Keyframe cut" vs "Normal cut"

**Comment by skywinder** [comment]
Yay! 
> Disabling the 2nd (avc1) track

helped! I don't know why it was breaking the preview, but now everything is good. Thanks. I believe I don't need that lower bitwrate & resilution track anyway!
