### ISSUE TITLE
Audio getting a little unsynchronized after cut

### ISSUE THREAD

**Issue by Undercover0007** [mifi/lossless-cut#1880]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 11

### Steps to reproduce

I open mp4 file, make a trim (cut from the beginning and from the end), click export and the audio is getting a little unsynchronized   (delayed) with video.

### Expected behavior

Audio shouldn't get unsynchronized after cut and export.

### Actual behavior

The audio is getting unsynchronized.
I search similar issue report but didn't find.

**Comment by mifi** [comment]
does this happen to all files you try? if not, please use this instead: https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&projects=&template=file-issue.yml

**Comment by Undercover0007** [comment]
I have to close the case, because I cannot replicate it at the moment and now I am confused. Maybe there was a mistake at my side. If I meet the issue again and I will be convinced LosslessCut is the culprit I will reopen the case. Thank you for your response anyway. I can only suggest by this occasion, as it was also suggested by some users in the past, is to add a functionality to shift audio track. Yes, I know the workaround by extracting, trimming and importing :)

**Comment by mifi** [comment]
#216
