### ISSUE TITLE
Allow rebinding of "Pan Timeline" shortcut

### ISSUE THREAD

**Issue by jackb-4824** [mifi/lossless-cut#1883]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

The ability to have hardware left & right scroll wheels doesn't seem to be supported by Windows, so with the current version it's seemingly impossible to pan the timeline.

It would be great if this can be (any of the following...)
- rebound to the keyboard in some way
- CTRL + Dragging on the timeline (This is behavior from kdenlive)

Other issues:
- Zooming with the scroll wheel is done with CTRL+MSWHEELUP/MSWHEELDOWN, but the Shortcuts menu says it's MSWHEELUP/MSWHEELDOWN. The option to unbind this would be appreciated.
- Seeking with the scroll wheel **has no entry** in the Shortcuts menu, but is bound to MSWHEELUP/MSWHEELDOWN.

**Comment by mifi** [comment]
Not sure I understand. You’re saying that left/right scroll wheel is not supported by the windows operating system? Then how can losslesscut support it if the operating system doesn’t?

The shortcuts dialog only supports binding keyboard shortcuts. Non keyboard actions (like mouse/wheel) are hardcoded and cannot be customised.

**Comment by mifi** [comment]
see also #1884

**Comment by mifi** [comment]
closing due to lack of response
