### ISSUE TITLE
Label all segments at once

### ISSUE THREAD

**Issue by Vipp0** [mifi/lossless-cut#1888]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

I am using Losslesscut to split large video files into smaller ones using the detect black scenes function, the operation is successful but at this point I have to rename all the segments and to do this I have to label each segment one at a time.

It would be useful, in my opinion, to have a function that allows (as with the "Text chapters/Youtube" function) to rename all the segments simply with a copy-paste (or import) from a text file, where each line corresponds to a segment.

**Comment by mifi** [comment]
not sure why you have to rename all the segments, e.g. what is the use case for that, but you could edit the `.llc` JSON5 file for the video and replace the `name` property for each segment. There are many existing tools out there for batch working on json files

**Comment by Vipp0** [comment]
Just to explain my particular case.

I have several long videos of mixed commercials that I need to split into individual videos, so for each video (one for each commercial), thanks to the detect black scenes feature, I can easily (with some minor adjustments) create the various segments of the individual commercial, at this point I have to rename each segment with the name of the related commercial (a different name for each segment) and it is getting to this point that I would like a method to rename all the segments at once so that I don't have to rename 30 or 60 segments each time one at a time, for this I was thinking of a screen like the one like "Text chapters/Youtube" that allows you to do what I need but without making cuts but only to rename the segments.

**Comment by mifi** [comment]
Still not sure why you need to import the segment names from a text file. If the segments all need to have different names, manually inputted by you, then why can't you just
1. Press <kbd>enter</kbd> to open the label current segment dialog
2. enter the segment name
3. Press <kbd>enter</kbd> to save the segment name
4. press <kbd>down arrow</kbd> to go to the next segment
5. repeat 1.

..other than losing a few keystrokes (you could skip step 1 and 4)

**Comment by Vipp0** [comment]
Basically to save time, I currently manually label each segment, I thought there might be a way to enter all the segment names with one click :D

Let's take an example with 60 segment names that I already have in a text file, the operation to do would be:

1. Import segment names
2. select the file with the names (or paste the names into the screen that pops up)

and that's it, just to save time :D

**Comment by mifi** [comment]
Ok sure, but where do you get your list of segment names from? You type them manually or they come from somewhere?

**Comment by Vipp0** [comment]
OK now I see your point

Short answer:
I already have a list of segment names to copy

Long answer:
These videos come from YouTube, the author in the video description enters the names of the individual commercials in the classic YouTube format 

00:00 name 1
00:30 name 2
00:43 name 3
Etc.

So I could use the Text chapters/Youtube function but the problem that comes up is that YouTube's seconds format is not accurate because the milliseconds are missing, so the division is not accurate on the black screen (and it's not a keyframe problem)
So what I do is use the detect black scenes function, invert segment selection and then proceed to rename the individual segments.
However, having the list ready would save a lot of time and if the function ignored the time written at the beginning (00:00, 00:30, 00:43 etc.) it would be even better 
Sorry for the long answer, I hope I have explained my case better, thanks for your help

**Comment by mifi** [comment]
Ok, I see! Isn't there a chance that the "black scenes" function will detect slightly different segments than the Youtube chapters, thereby voiding the youtube chapters invalid? Anyways I think this use case is very niche so I don't think I will prioritise implementing this unless many people ask for it. As mentioned, a workaround is to edit the `.llc` file or use some assistive tool to do that. maybe even chatGPT could do it, so I'm going to close this for now. thanks!
