### ISSUE TITLE
When merging mp3 files and creating chapters, these have the wrong position

### ISSUE THREAD

**Issue by reaseno** [mifi/lossless-cut#1891]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

Merge mp3 files and "Create chapters from merged segments". You can then see where the chapter markers have been placed.

### Expected behavior

The chapters should be in the right places according to the length of the mp3 files.

### Actual behavior

In my example, the first mp3 had a length of 3:07, but the chapter was set to position 2:40.

Pocket Casts is the app in Android that had problems. In contrary, the chapters were correct in SMPlayer.

I was able to fix the problem in Pocket Casts by using foobar2000 and "Fix VBR MP3 header". I'm not sure why it worked since it wasn't a VBR mp3. Also, now I don't know which program is making mistakes here.

**Comment by mifi** [comment]
I justed tested merging 2 mp3 files and it looks correct to me. there's not enough information here to help you. I think this is a problem with a particular set of files so you should try this instead: https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&projects=&template=file-issue.yml

**Comment by reaseno** [comment]
How did you check the correctness?

**Comment by mifi** [comment]
i opened the file in QuickLook in Finder on MacOS and it showed two chapters with the correct length
