### ISSUE TITLE
Can't run from network drive.

### ISSUE THREAD

**Issue by devanteweary** [mifi/lossless-cut#1893]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

1) Download the latest version of Lossless Cut: v3.59.1.0
2) Copy the folder to my SMB network drive hosted on a local Unraid server.
3) Launch the app.

### Expected behavior

App should launch normally.

### Actual behavior

Lossless Cut window opens momentarily, showing the titlebar and a white screen as the window.  
Then about 2 seconds later, it closes on its own.

### Share log from developer tools

I can't get to the javascript console due to the window closing immediately.

![nyann](https://github.com/mifi/lossless-cut/assets/29805497/07e3a0c2-2ee6-4ca0-8f0b-8667fdb551d9)

**Comment by mifi** [comment]
you can try to start it from the command line and see if there's any error message. if not, then I don't know how to solve this, and I can only recommend making sure that all files are writeable/executable, or just not running losslesscut from a network drive but instead copying it to c:.

**Comment by devanteweary** [comment]
> you can try to start it from the command line and see if there's any error message. if not, then I don't know how to solve this, and I can only recommend making sure that all files are writeable/executable, or just not running losslesscut from a network drive but instead copying it to c:.

Thank you for answering!!!!

OK I ran it in Powershell and got this...

![image](https://github.com/mifi/lossless-cut/assets/29805497/1e70a618-aefc-4c2c-89a0-26d8523d10e7)

But from my local PC it work.
Hopefully this helps!

**Comment by mifi** [comment]
this may be helpful for you: https://github.com/Automattic/simplenote-electron/issues/3096
