### ISSUE TITLE
Lossless masking?

### ISSUE THREAD

**Issue by dcdom2** [mifi/lossless-cut#1895]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Here is my case: I want to remove the image part of a video, but keep the audio. Normal cutting wouldn't do.

VirtualDub (the original) had a feature called masking where if you mask frames 101-150, the video appears to "hang" on frame 100 for that duration until it resumes with frame 151. This was lossless in the sense: 1-100 untouched + 101-150 replaced with the 100 keyframe (I think) as long as the specified duration in the same video parameters + 151-end untouched, then all were losslessly merged.

I think this will be an awesome addition to LosslessCut and in the same spirit of "cutting".

Thank you

**Comment by mifi** [comment]
Hi. I believe this is technically similar to #1268 - I've added your suggestion there, and will close this

**Comment by dcdom2** [comment]
Thanks.

I just want to add: I am not sure if the frame is actually repeated during the masked segment or that is just a quirk of the media player (if I jump forward within the masked segment (e.g. to frame 130), the player changes to the first unmasked frame (151) for the duration (130-150) then continues to play normally (151-end)) . So, the issue might not exactly be frame manipulation. Could I ask you to try it in VirtualDub (doesn't work in VirtualDub 2) to be sure how it is done? Thanks.

**Comment by mifi** [comment]
not sure how to test that. maybe you can do it and then load the video into losslesscut and see if there are many keyframes in a short period of time

**Comment by dcdom2** [comment]
It seems that *all* the masked frames are replaced with what VirtualDub calls D frames or "A **drop or null frame**, which repeats the previous frame".

Here is the output of VirtualDub: 

[1min.zip](https://github.com/mifi/lossless-cut/files/14322973/1min.zip)


### Steps to reproduce:
- Download https://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4 (62 MB)
- Open in LosslessCut. Cut from 0 to 1 minute. save as 1min.mp4
- Load 1min.mp4 into VirtualDub. From the toolbar menu, select Video --> Direct stream copy
- Mark from second 5 to second 20 using the buttons at the bottom
- Edit --> Mask selected frames
- Ctrl+D (to clear selection)
- File --> Save as AVI ...
- Close 1min.mp4, open 1min.avi in VirtualDub
- Check frames between second 5 to second 20. All D frames.

**Comment by dcdom2** [comment]
Hi,

1. I have to go through many hoops of muxing, extracting and remerging **with each video** to get it to work in VirtualDub. I would really love it if you are able to give this some attention.
2. I think it shouldn't be categorized as key frame manipulation (#1268) in light of [the post above](#issuecomment-1951350905)

Thank you again

**Comment by mifi** [comment]
1. i don’t know how to achieve null frames with ffmpeg
2. Ok, I’ll rename that issue to make it more generic
