### ISSUE TITLE
Trimmed file choppy / not playing properly

### ISSUE THREAD

**Issue by eranekao** [mifi/lossless-cut#190]
I've only encountered this issue with some of the videos that were taken with a friend's iPhone. I doesn't happen systematically on every one of those files, but when it happens to one, it's always reproducible on that one, there is no way to cut it without this happening.

I have uploaded the original file, the resulting trimmed file as well as the developer tools log here:

https://1drv.ms/u/s!AiQni5AItzu5hrRVIsQ2RlPt_n3D0w?e=l73yI5

I also included screenshot of my system information.

Thanks,

**Comment by eranekao** [comment]
Any input on this or possible solutions?

**Comment by mifi** [comment]
Hi. Can you try to toggle `all` to `ps`, or `kc` to `nc` or both

**Comment by eranekao** [comment]
Both of these options solved the issue, either ticked individually or together, thank you!
