### ISSUE TITLE
App no longer runs from a UNC path

### ISSUE THREAD

**Issue by shawnwright** [mifi/lossless-cut#1903]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 11

### Steps to reproduce

Unzip to and run from a UNC path

### Expected behavior

Normal app function (used to work)

### Actual behavior

At work my "my documents" directory is virtual/roaming and actually lives on a windows UNC path, and that's where I keep my "portable" applications so I can run them from whatever computer I'm on at the time at the office. For years I've run lossless cut that way but recently that stopped working. The splash screen will come up, and then it would go away but the application would never come up. However, the application still shows in task manager after running it, so SOMEthing is running, but you never get a GUI, I then have to kill that task. I've had to change to having it on a lettered drive instead. I realize this is probably a low probability use case and understand this may therefore be a low priority fix, if at all. Just thought I'd raise awareness since it worked not so long ago.

**Comment by mifi** [comment]
Hi. Could it be the same issue as #1893 ?

**Comment by shawnwright** [comment]
Yes, sorry, that's the behavior I see as well. I did search first, but just for "UNC".

**Comment by mifi** [comment]
Ahh, in that case I don’t know how to solve it because it’s a bug upstream in Electron, so i’ll close this. See the issues i linked in the other issue. You could try to run losslesscut with the `--no-sandbox` argument.
