### ISSUE TITLE
120 fps video stutters in playback window

### ISSUE THREAD

**Issue by Rytoxz** [mifi/lossless-cut#1904]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 11

### Steps to reproduce

Open a 120 fps video in lossless cut (such as below) and frame pacing is poor with stuttering in the playback window. This does not happen with 60 fps clips. The new NVIDIA app (https://www.nvidia.com/en-us/geforce/news/nvidia-app-beta-download/) allows for recording at 120 fps. 

https://github.com/mifi/lossless-cut/assets/134399545/db385614-7da0-4ed9-9008-df85b1d89e6e

### Expected behavior

The clip should playback smoothly like a 60 fps clip.

### Actual behavior

The clip plays back in a desynced manner with stuttering.

120 fps playback: 

https://github.com/mifi/lossless-cut/assets/134399545/b6cffabc-81f7-474b-997f-282179129e1e

60 fps playback: 

https://github.com/mifi/lossless-cut/assets/134399545/265bfeba-ad23-449e-bc71-2479457cb223

**Comment by mifi** [comment]
could u share more info about the file? https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&projects=&template=1-file-issue.yml

**Comment by mifi** [comment]
or is it happening with all files? e.g. normal h264 files too

**Comment by mifi** [comment]
Could you try to play the video in Chrome also and see if it’s the same?

**Comment by mifi** [comment]
That's strange. for me it plays smoothly at 120fps. i'm on m2 macbook air. which other devices did you test it on? do you see high cpu usage?

**Comment by mifi** [comment]
interesting. so did all apps have global fps lock applied or only losslesscut? it's probably a bug in electron/windows/nvidia combination, and I have no idea how to fix it. maybe related: #922
