### ISSUE TITLE
Add audio source channel switching preview

### ISSUE THREAD

**Issue by dams92210** [mifi/lossless-cut#1905]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

When playing a multitrack audio video (MP4, TS, MKV, ...) there is no way to hear different audio track than the main one.
In avidemux selecting the audio track permits to hear it and it is really usefull when you want to check for example the audio track of simultaneous audio track.
Would be great to add the feature of selecting the audio track you want to hear in the preview pane.
I have developped myself a tool based of Nwjs/ffmpeg to slice and export videos cuts but yours is far away from mine ;-)
![Capture d'écran 2024-02-23 113544](https://github.com/mifi/lossless-cut/assets/3910999/93ecaf76-c0f1-49dc-9f76-978667f28915)

Thanks for this great tool, you did an amazing job.

**Comment by mifi** [comment]
hi. this was already implemented in 6fddf72a2dabbc74e635909f56238877936a64d6 - you can try the nightly build if you want
