### ISSUE TITLE
Implement JPGXL or AVIF format options for video snapshots

### ISSUE THREAD

**Issue by Apposite245** [mifi/lossless-cut#1907]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

With HDR becoming more and more prevalent due to the increase in support from modern smartphones as well as HDR film and tv releases, having a way to capture accurate stills from HDR content would be greatly appreciated.

It seems that ffmpeg already supports JPGXL using libjxl.

**Comment by mifi** [comment]
added your suggestion here: #1907
