### ISSUE TITLE
[Request] Flatpak/snap or other installable linux release!

### ISSUE THREAD

**Issue by carverhaines** [mifi/lossless-cut#191]
I would love to see this as an installable file on linux (snap, flatpack etc)!

**Comment by mifi** [comment]
Is AppImage good enough? I could add snap but I think it seems to require me to sign up to snapcraft?

**Comment by carverhaines** [comment]
Awesome, I see the appimage.

**Comment by mifi** [comment]
With new build system it was now easy to add also snap, see 2.6.2
