### ISSUE TITLE
Waveform appears seemingly at random

### ISSUE THREAD

**Issue by xrstf** [mifi/lossless-cut#1912]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

1. Open a video file (mkv with x265 in my case)
2. Click "Show waveform". A bar like this appears as expected:

![2024-03-03 09_46_57-New Issue · mifi_lossless-cut — Mozilla Firefox](https://github.com/mifi/lossless-cut/assets/127499/031d347f-6ad1-4c4c-b86f-5335f5a377f4)

3. Zoom in (either via mousewheel or the zoom buttons in the status bar)

### Expected behavior

At some zoom level, the audio waveform should appear consistently.

### Actual behavior

When zooming in, the bar for the waveform just disappears entirely. I can zoom in and out an in and move back and forth and only when losslesscut feels like it, will it seemingly at random actually show the waveform again.

https://github.com/mifi/lossless-cut/assets/127499/c089dbc0-b77d-4ef4-b0d3-0a8b7b15b730

Is this maybe losslesscut still loading? Or what could be the reason I have to wait / click around randomly? Would there be a chance to include a loading indicator on the waveform bar to let me know that/if something is going to happen?

Sometimes when clicking around, the entire waveform bar just disappears and I get errors like

![2024-03-03 09_57_53-LosslessCut - S05E10 - New Ground mkv](https://github.com/mifi/lossless-cut/assets/127499/39e9d7eb-f6ca-431e-8b3a-ec09bfaa89e4)

but I guess those errors are from me clicking around _fast_.

**Comment by mifi** [comment]
i couldn't reproduce it right now, but there could be a bug there yes

**Comment by xrstf** [comment]
My video files are ~1.5GB per file, stored on an internal HDD. Video is x265 and the audio streams are DTS / Vorbis.

**Comment by shalex28** [comment]
Would like to add: There is no  waveform shown for my file of around 100MB in TS Format. But waves  do appear  for this my file exported in MP4 or Matroska.

**Comment by shalex28** [comment]
p.s. zooming had no effect

**Comment by mifi** [comment]
can you try the nightly build?

**Comment by shalex28** [comment]
1. no there are only 2 tracks - one for video one for audio
![tracks](https://github.com/mifi/lossless-cut/assets/167364190/8103f895-8f90-4657-a5bb-3b8499055f6c)

**Comment by shalex28** [comment]
2. yes I tried https://github.com/mifi/lossless-cut/actions/runs/8859012902 and the result was that the wave panel  without waveform. 
![after](https://github.com/mifi/lossless-cut/assets/167364190/0dec2e6e-87ae-4d32-b354-4563b90df407)

**Comment by shalex28** [comment]
before applying the build there was no wave panel at all
![before](https://github.com/mifi/lossless-cut/assets/167364190/9535d089-c0a4-4c46-8fd6-f72a5e3ab25f)

**Comment by shalex28** [comment]
I want to thank you anyway for the great software! I finished my small family video with help of it!

**Comment by mifi** [comment]
alright. probably a bug in ffmpeg. unfortunately i cannot reproduce the problem with a TS file (waveform works for me)

**Comment by mifi** [comment]
is this still a problem with the latest version?

**Comment by mifi** [comment]
closing due to lack of response

**Comment by andimik** [comment]
I have the same impression that the waveform appears and disappears randomly. I'm using Linux Mint (based on Ubuntu 24.04) with appImage 3.62

My use case it radio recording from DAB+, so no big files (50 MB each).

![grafik](https://github.com/user-attachments/assets/2d3d10a7-7064-4aaf-bf62-bbc8ebb871ef)

There is even a grey block, which comes from the waveform.

![grafik](https://github.com/user-attachments/assets/f821ee6a-ff83-45cf-96fe-5d60ab28f3d9)

And it will not show from left edge to the right end ...

![grafik](https://github.com/user-attachments/assets/25215a18-22fe-44ff-b7d5-a7c29170f43f)

**Comment by mifi** [comment]
> I have the same impression that the waveform appears and disappears randomly. I'm using Linux Mint (based on Ubuntu 24.04) with appImage 3.62

try latest version. maybe you can share a file and steps that that reproduces the problem. it's not obvious from your screenshots how you get this grey box to show up

> And it will not show from left edge to the right end ...

this is expected. it will only render a window around the current time

**Comment by shalex28** [comment]
> is this still a problem with the latest version?

hello and merry Christmas) Sorry for not answering you. I have just seen your comment because of not loging here for a long time. Right now I am doing  another family video congrat for the new year. So I logged in here to update and download the last nightly and saw your comment. As you wanted I checked out my old file with the problem from above. The answer is no, there is no wave form. I also tried the slowest high quality encode , but there was no effect

**Comment by shalex28** [comment]
full screen waveform 1xzoom
![full screen waveform 1xzoom](https://github.com/user-attachments/assets/7fb1b6f3-f788-4f90-beb4-efc8c36040ff)

**Comment by shalex28** [comment]
full screen waveform 9xzoom

![full screen waveform 9xzoom](https://github.com/user-attachments/assets/cae0affa-57a7-4d3f-a9ef-21f92b0fb58e)

**Comment by mifi** [comment]
that's strage. it works for me with mpeg ts files. what if you first remux it to a mov or mp4 file (select output format mov, then export, then re-open the exported file), do you then get any waveform?

**Comment by shalex28** [comment]
> that's strage. it works for me with mpeg ts files. what if you first remux it to a mov or mp4 file (select output format mov, then export, then re-open the exported file), do you then get any waveform?

yes I get - I wrote it above https://github.com/mifi/lossless-cut/issues/1912#issuecomment-2062451092
I  also took  another mp4 file with working wave form, converted ot then to mpeg ts format and the wave disappeared as shown above https://github.com/mifi/lossless-cut/issues/1912#issuecomment-2564400811. Then I converted it back to mp4 and the wave came back again :)

**Comment by shalex28** [comment]
the same story happens with the files from other sources like recorded with  pc, smartphone  ... or  videos from youtube like the next one downloaded as mp4 with working wave and then converted to mpeg ts with no wave any more

![Image](https://github.com/user-attachments/assets/7bfe8851-bfac-4a27-80cb-4154e20f4fdc)

**Comment by mifi** [comment]
Ok, I don't know how to fix this, it's probably an issue in ffmpeg because LosslessCut doesn't call ffmpeg differently for mpegts vs other formats to get the waveform.

**Comment by shalex28** [comment]
yeh maybe, I have just let you know)
