### ISSUE TITLE
Add option to display subtitle by default when creating MP4 file

### ISSUE THREAD

**Issue by RedRabbit88** [mifi/lossless-cut#1913]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

I'm not sure if this is possible, or if there is a limitation with the MP4 container, but I am trying to convert from MKV to an MP4 container - with SRT subtitles - but would like the subtitles to display by default.

When playing back the resultant video in VLC, videos created by LosslessCut (both MKV and MP4) retain the subtitles, but only MKV plays them by default (so MP4 files require the subs to be enabled manually).

Is it possible to flag subtitles to show by default with created MP4 files?  Many thanks for any insight.

**Comment by mifi** [comment]
you mean a flag telling the player to activate the subtitle by default, without the user having to maunally do so?

Have you tried the "disposition" in the track panel? `default` or `forced`

relevant:
- https://stackoverflow.com/a/40711500/6519037
- https://superuser.com/a/1512887/658247
- https://stackoverflow.com/questions/73772765/how-to-force-by-default-subtitles-ffmpeg

**Comment by RedRabbit88** [comment]
Yes, that's exactly what I mean.  I _have_ tried setting 'disposition' to both `default` and `forced` - neither show the subs by default (but can be activated manually by the user).  With MKVs, this works precisely as expected / desired - just not MP4s, from what I can see.

**Comment by mifi** [comment]
hmm, i just tried to add a subtitle to an mp4 file and set the disposition to "default", and for me it automatically enables teh subtitle when i use finder preview, quicktime player or IINA, but not in VLC. leads me to believe it's a problem with VLC. as far as I can see from my research, `disposition` is the right thing to use, so I don't know how else to solve this, so I'm closing until some new information comes up.
