### ISSUE TITLE
Playback is extremely slow and stuttery

### ISSUE THREAD

**Issue by Pinkchup** [mifi/lossless-cut#1915]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [ ] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [x] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

I have no idea how to reproduce the problem. When I first installed LosslessCut, everything worked perfectly fine, but after a few months it suddenly started doing this. I hadn't done any major changes to my computer when this problem first occured, and after a few months it continues to persist even if I install older or newest versions.

### Expected behavior

The playback of the video should be at normal speed and the program shouldn't stutter.

### Actual behavior

When a video is played, it plays very slow and when it's too much for the program, it stops momentarily before doing the same stutter loop again.

https://github.com/mifi/lossless-cut/assets/138224519/2e87c8b4-ca83-4272-8efa-da30588b253c

**Comment by mifi** [comment]
seems awfully related to #1904

**Comment by Pinkchup** [comment]
> seems awfully related to #1904

unfortunately, i always record in 60 fps, so the problem isn't related. I tried limiting the FPS of lossless cut in NVIDIA control panel, but it had no effect

**Comment by mifi** [comment]
does the same happen with all kinds of video files (e.g. from other sources)? and did you try on a different computer? what about if you open the video file in google chrome? I have a feeling that it's related to some issue specific to nvidia graphics driver..

**Comment by Pinkchup** [comment]
> does the same happen with all kinds of video files (e.g. from other sources)? and did you try on a different computer? what about if you open the video file in google chrome? I have a feeling that it's related to some issue specific to nvidia graphics driver..

the behaviour is still the same no matter what the video source is (downloaded, recorded, etc.). Tried it on my old laptop and it worked perfectly fine. I dont use google chrome but any video works fine on opera gx

**Comment by mifi** [comment]
ok. unfortunately i'm going to have to call this a bug in chromium or windows or nvidia drivers (or probably a combination), so there's not much I can do there.

**Comment by Pinkchup** [comment]
thank you for all the help, really unfortunate i cant get it to work

**Comment by Pinkchup** [comment]
I have finally come up with a potential solution to my problem. I was randomly playing around with the windows properties for LosslessCut, and tried to run the program as admin, disabling fullscreen optimizations, etc. Also reinstalled the program just in case there was an update that could fix my problem.

Nothing worked UNTIL I ran my program in compatibility mode for Windows Vista (Service Pack 2). It's one of the windows versions that makes the program run perfectly smooth again, like it's supposed to be.

![image_2024-04-16_015320817](https://github.com/mifi/lossless-cut/assets/138224519/9c51f5b2-af5b-4927-8054-eccb780e5ab6)

Genuinely dunno why this worked but it did. 
(Side note: tested other windows versions, and only all the Vista ones work.)

**Comment by mifi** [comment]
wow that's very strange, because losslesscut(electron) doesn't even run on windows vista

**Comment by tazztone** [comment]
this fixed it for me. windows vista service pack 2 WAY TO GO in 2024!! :D

**Comment by Tarec** [comment]
I have the same issue. Happens since I switched to a newer monitor and started recording at 1440p@60 instead of 1080p@60 with nvidia shadowplay, but it stutters even when playing previously recorded videos at 1080p, so it might be more about the display output rather than the input format or the bitrate. My main display is set 120Hz, while the previous one, which was only 60Hz, is still connected as a secondary display. Also, Vista SP2 compatibility mode works like a charm - the GPU usage is about 30-35%, whereas without compatibility enabled it fluctuates heavily between 1-3% and 100%.
My spec is 5800X3D, GTX970 and 64GB of RAM memory.

**Comment by tazztone** [comment]
maybe there is a way for the player engine not to be detected by the systems as being "in the background" to avoid disabling "Background Application Max Frame Rate" ?

**Comment by mifi** [comment]
I have no idea how the system detects a video as being in the background unless the window is indeed minimized or covered(behind) another window

**Comment by semplar2007** [comment]
> maybe there is a way for the player engine not to be detected by the systems as being "in the background" to avoid having to disable "Background Application Max Frame Rate" ?

worked for me, thanks!

**Comment by MRZ-OW** [comment]
> I have finally come up with a potential solution to my problem. I was randomly playing around with the windows properties for LosslessCut, and tried to run the program as admin, disabling fullscreen optimizations, etc. Also reinstalled the program just in case there was an update that could fix my problem.
> 
> Nothing worked UNTIL I ran my program in compatibility mode for Windows Vista (Service Pack 2). It's one of the windows versions that makes the program run perfectly smooth again, like it's supposed to be.
> 
> ![image_2024-04-16_015320817](https://github.com/mifi/lossless-cut/assets/138224519/9c51f5b2-af5b-4927-8054-eccb780e5ab6)
> 
> Genuinely dunno why this worked but it did. (Side note: tested other windows versions, and only all the Vista ones work.)

Wow. THANKS! My viewer was just black and occasionally flickering in and out of color, sometimes even positioning the video out of the frame, until I did this!! It is flawless again. Sometimes you find solutions in places you really don't expect :D

**Comment by tazztone** [comment]
playback is quite ok when the window is small.  but beginns to stutter heavily in fullscreen. on 5900x ans 3090 that shouldn't be

Apr 29, 2025 16:27:09 MRZ-OW ***@***.***>:

**Comment by Fabled-Stranger** [comment]
This has also solved my issue on versions 3.63 & 3.64, thanks!

**Comment by ozi337** [comment]
> I have finally come up with a potential solution to my problem. I was randomly playing around with the windows properties for LosslessCut, and tried to run the program as admin, disabling fullscreen optimizations, etc. Also reinstalled the program just in case there was an update that could fix my problem.
> 
> Nothing worked UNTIL I ran my program in compatibility mode for Windows Vista (Service Pack 2). It's one of the windows versions that makes the program run perfectly smooth again, like it's supposed to be.
> 
> ![image_2024-04-16_015320817](https://github.com/mifi/lossless-cut/assets/138224519/9c51f5b2-af5b-4927-8054-eccb780e5ab6)
> 
> Genuinely dunno why this worked but it did. (Side note: tested other windows versions, and only all the Vista ones work.)

Windows 10
Nvidia 2080ti
i7 9900K

All files I edited (60 & 120fps AVC codec mp4 files) had the issue 

+ similar to OP's (slowdowns)
+ also mainly blacked out image with flickers of coloured frames

**FIXED** by setting compatibility mode = Windows Vista SP 2
