### ISSUE TITLE
default Working directory 

### ISSUE THREAD

**Issue by viohug** [mifi/lossless-cut#1918]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

HI, I set a special working directory because I needed to do it, but then wanted to go back to the default (same directory than the files you're working on) but I couldn't find how to do it.

greets.

**Comment by mifi** [comment]
click the X next to the working dir in the upper right

<img width="152" alt="Screenshot 2024-03-14 at 16 07 28" src="https://github.com/mifi/lossless-cut/assets/402547/ae8cbc1f-f369-4b4b-8108-99667abb74b3">

**Comment by viohug** [comment]
My gaah... I was checking settings, advanced settings... it was right there in the main window.
I guess now you'll add an option under settings too :D

Ok. Thanks.
