### ISSUE TITLE
scene detection with assigned shortcut doesn't work but from the toolbar it's working

### ISSUE THREAD

**Issue by piimah** [mifi/lossless-cut#1919]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

assign a shortcut to scene detection.
then try to use it.
i am getting an error every time i use a shortcut to detect scenes.
from the regular toolbar it's working without problems.

i hope someone can fix it:)

you guys are awesome💪🏽

### Expected behavior

normal scene detection witbout any errors

### Actual behavior

error. if needed i can take a screenshot.

### Share log from developer tools

na

**Comment by mifi** [comment]
what's the error you're getting? i just tried it but it works for me. also what do you set the `minChange` parameter to?
