### ISSUE TITLE
Audio is messed up after cut

### ISSUE THREAD

**Issue by duclepham** [mifi/lossless-cut#1924]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 11

### Steps to reproduce

I cut a small portion out of a big video. However, when playing the output file in VLC, every 2-3 seconds or so the audio will be muted. 

### Expected behavior

Audio should be exactly like the original video.

### Actual behavior

Eevery 2-3 seconds or so the audio will be muted. 

### Share log from developer tools

No error occurred.

{
  "state": {
    "ffmpegExperimental": false,
    "preserveMovData": false,
    "movFastStart": true,
    "preserveMetadataOnMerge": false,
    "filePath": "D:\\NKR DB\\SCSL\\SCSL Final Final.mp4",
    "fileFormat": "mp4",
    "externalFilesMeta": {},
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "initial_padding": 0,
        "id": "0x1",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/48000",
        "start_pts": 96,
        "start_time": "0.002000",
        "duration_ts": 194838208,
        "duration": "4059.129333",
        "bit_rate": "159956",
        "nb_frames": "190272",
        "extradata_size": 2,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "creation_time": "2024-03-13T06:13:06.000000Z",
          "language": "eng",
          "handler_name": "SoundHandler",
          "vendor_id": "[0][0][0][0]"
        }
      },
      {
        "index": 1,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1080,
        "closed_captions": 0,
        "film_grain": 0,
        "has_b_frames": 16,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 42,
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "field_order": "progressive",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "id": "0x2",
        "r_frame_rate": "60/1",
        "avg_frame_rate": "1114249955/18650704",
        "time_base": "1/1000000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 4059166655,
        "duration": "4059.166655",
        "bit_rate": "7994258",
        "bits_per_raw_sample": "8",
        "nb_frames": "242507",
        "extradata_size": 58,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "creation_time": "2024-03-13T06:13:06.000000Z",
          "language": "eng",
          "handler_name": "VideoHandler",
          "vendor_id": "[0][0][0][0]"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "D:\\NKR DB\\SCSL\\SCSL Final Final.mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {
        "start": 1353.414445,
        "end": 1828.719197
      }
    ],
    "mainFileFormatData": {
      "filename": "D:\\NKR DB\\SCSL\\SCSL Final Final.mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "4059.166655",
      "size": "4144594043",
      "bit_rate": "8168364",
      "probe_score": 100,
      "tags": {
        "major_brand": "isom",
        "minor_version": "0",
        "compatible_brands": "mp41avc1",
        "creation_time": "2024-03-13T06:13:06.000000Z",
        "playback_requirements": "QuickTime 6.0 or greater",
        "playback_requirements-eng": "QuickTime 6.0 or greater",
        "encoder": "vlc 3.0.20 stream output",
        "encoder-eng": "vlc 3.0.20 stream output"
      }
    },
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "separate",
    "outSegTemplate": "Final 1 V2${EXT}"
  },
  "platform": "win32",
  "version": "3.59.1"
}

**Comment by mifi** [comment]
Hmm, I've never heard of this problem. does it happen also if you simply export the whole thing unmodified from losslesscut without any cuts at all?

**Comment by mifi** [comment]
closing due to lack of response
