### ISSUE TITLE
 apply automatically  "Open selected file" action after Export / Delete action

### ISSUE THREAD

**Issue by skywinder** [mifi/lossless-cut#1926]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Great to have feature: I have to press `Enter` each time to choose the next video. Since I have to process thousands of them, I would be happy to save this single click. It could be an option in the settings as well. If you like the idea, I can check the code; probably, I can help with it.

![CleanShot 2024-03-17 at 17 16 40@2x](https://github.com/mifi/lossless-cut/assets/3356474/0b6140f6-512b-4e30-89cb-18de71fa4266)

**Comment by mifi** [comment]
next version will have new bindable actions to achieve batch next/previous+open in one action:
- Open previous file `batchOpenPreviousFile`
- Open next `filebatchOpenNextFile`

**Comment by skywinder** [comment]
Wow, that's fast! Looking forward for next release to try! Thank you!
