### ISSUE TITLE
M2TS video file is not accepted

### ISSUE THREAD

**Issue by KatieBelli** [mifi/lossless-cut#1928]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with a different kind of file to confirm that the problem is related to just this file.
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Steps to reproduce

Import a m2ts video file into Lossless Cut GUI.

### Expected behavior

It should load the video file like any other video file so you can edit and export it like usual.

### Actual behavior

It suggests that I should convert it to another format and it doesn't play the video.

Errors:
"File not natively supported. Preview may have no audio or low quality. The final export will however be lossless with audio. You may convert it from the menu for a better preview with audio."

"Unable to playback this file. Try to convert to supported format from the menu."

### Provide an error report

No error occurred.

{
  "state": {
    "ffmpegExperimental": false,
    "preserveMovData": false,
    "movFastStart": false,
    "preserveMetadataOnMerge": false,
    "filePath": "[.........................]",
    "fileFormat": "mpegts",
    "externalFilesMeta": {},
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "vc1",
        "codec_long_name": "SMPTE VC-1",
        "profile": "Advanced",
        "codec_type": "video",
        "codec_tag_string": "VC-1",
        "codec_tag": "0x312d4356",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1080,
        "closed_captions": 0,
        "film_grain": 0,
        "has_b_frames": 1,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 3,
        "chroma_location": "left",
        "field_order": "progressive",
        "refs": 1,
        "id": "0x1011",
        "r_frame_rate": "24000/1001",
        "avg_frame_rate": "24000/1001",
        "time_base": "1/90000",
        "start_pts": 54000000,
        "start_time": "600.000000",
        "duration_ts": 1153486083,
        "duration": "12816.512033",
        "extradata_size": 33,
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        }
      },
      {
        "index": 1,
        "codec_name": "dts",
        "codec_long_name": "DCA (DTS Coherent Acoustics)",
        "profile": "DTS-HD HRA",
        "codec_type": "audio",
        "codec_tag_string": "[133][0][0][0]",
        "codec_tag": "0x0085",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 6,
        "channel_layout": "5.1(side)",
        "bits_per_sample": 0,
        "initial_padding": 0,
        "id": "0x1100",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/90000",
        "start_pts": 54000000,
        "start_time": "600.000000",
        "duration_ts": 1153485120,
        "duration": "12816.501333",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        }
      },
      {
        "index": 2,
        "codec_name": "dts",
        "codec_long_name": "DCA (DTS Coherent Acoustics)",
        "profile": "DTS-HD HRA",
        "codec_type": "audio",
        "codec_tag_string": "[133][0][0][0]",
        "codec_tag": "0x0085",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 6,
        "channel_layout": "5.1(side)",
        "bits_per_sample": 0,
        "initial_padding": 0,
        "id": "0x1101",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/90000",
        "start_pts": 54000000,
        "start_time": "600.000000",
        "duration_ts": 1153485120,
        "duration": "12816.501333",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        }
      },
      {
        "index": 3,
        "codec_name": "ac3",
        "codec_long_name": "ATSC A/52A (AC-3)",
        "codec_type": "audio",
        "codec_tag_string": "AC-3",
        "codec_tag": "0x332d4341",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "initial_padding": 0,
        "id": "0x1102",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/90000",
        "start_pts": 54000000,
        "start_time": "600.000000",
        "duration_ts": 1153486080,
        "duration": "12816.512000",
        "bit_rate": "224000",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        }
      },
      {
        "index": 4,
        "codec_name": "ac3",
        "codec_long_name": "ATSC A/52A (AC-3)",
        "codec_type": "audio",
        "codec_tag_string": "AC-3",
        "codec_tag": "0x332d4341",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "initial_padding": 0,
        "id": "0x1103",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/90000",
        "start_pts": 54000000,
        "start_time": "600.000000",
        "duration_ts": 1153486080,
        "duration": "12816.512000",
        "bit_rate": "224000",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        }
      },
      {
        "index": 5,
        "codec_name": "hdmv_pgs_subtitle",
        "codec_long_name": "HDMV Presentation Graphic Stream subtitles",
        "codec_type": "subtitle",
        "codec_tag_string": "[144][0][0][0]",
        "codec_tag": "0x0090",
        "id": "0x1200",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/90000",
        "start_pts": 54000000,
        "start_time": "600.000000",
        "duration_ts": 1153486083,
        "duration": "12816.512033",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        }
      },
      {
        "index": 6,
        "codec_name": "hdmv_pgs_subtitle",
        "codec_long_name": "HDMV Presentation Graphic Stream subtitles",
        "codec_type": "subtitle",
        "codec_tag_string": "[144][0][0][0]",
        "codec_tag": "0x0090",
        "width": 1920,
        "height": 1080,
        "id": "0x1201",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/90000",
        "start_pts": 54000000,
        "start_time": "600.000000",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        }
      },
      {
        "index": 7,
        "codec_name": "hdmv_pgs_subtitle",
        "codec_long_name": "HDMV Presentation Graphic Stream subtitles",
        "codec_type": "subtitle",
        "codec_tag_string": "[144][0][0][0]",
        "codec_tag": "0x0090",
        "id": "0x1202",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/90000",
        "start_pts": 54000000,
        "start_time": "600.000000",
        "duration_ts": 1153486083,
        "duration": "12816.512033",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        }
      }
    ],
    "copyStreamIdsByFile": {
      "[.........................]": {
        "0": true,
        "1": true,
        "2": true,
        "3": true,
        "4": true,
        "5": true,
        "6": true,
        "7": true
      }
    },
    "cutSegments": [
      {}
    ],
    "mainFileFormatData": {
      "filename": "[.........................]",
      "nb_streams": 8,
      "nb_programs": 1,
      "format_name": "mpegts",
      "format_long_name": "MPEG-TS (MPEG-2 Transport Stream)",
      "start_time": "600.000000",
      "duration": "12816.512033",
      "size": "36559220736",
      "bit_rate": "22820075",
      "probe_score": 50
    },
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "separate",
    "outSegTemplate": "${FILENAME}-${CUT_FROM}-${CUT_TO}${SEG_SUFFIX}${EXT}"
  },
  "platform": "win32",
  "version": "3.59.1"
}

**Comment by mifi** [comment]
where did you get this file from? seems to have a quite old codec SMPTE VC-1 (Microsoft WMV) https://en.wikipedia.org/wiki/VC-1

I tested the file [Test_1440x576_WVC1_6Mbps.wmv](https://samples.mplayerhq.hu/V-codecs/WVC1/Test_1440x576_WVC1_6Mbps.wmv) from https://samples.mplayerhq.hu/V-codecs/WVC1/ and it works for me. Does it work if you convert it to a supported format first? select for example output format matroska. see also faq: https://github.com/mifi/lossless-cut/blob/master/issues.md

**Comment by mifi** [comment]
closing due to lack of response
