### ISSUE TITLE
Unexpected char in digit field for scene detection window (from pressing keyboard shortcut)

### ISSUE THREAD

**Issue by skywinder** [mifi/lossless-cut#1936]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

MacOS 13

### Steps to reproduce

- set (or use predefined shortcut for scene detection) any char. like `B` or `Shift + B`
- acrivate it in the video

### Expected behavior

open window with predefined digit

### Actual behavior

open window with digit + char from key shortcut (look at screenshots)

![CleanShot 2024-03-24 at 22 11 00@2x](https://github.com/mifi/lossless-cut/assets/3356474/161b80ec-4333-48db-8d0e-40d5e8957c66)
![CleanShot 2024-03-24 at 22 05 21@2x](https://github.com/mifi/lossless-cut/assets/3356474/df40e8d3-0352-4464-92d0-2ee9027f84bb)

**Comment by mifi** [comment]
already fixed in 96baa9a93197bcb1ce9c8afad8f69096cf93d3a8
