### ISSUE TITLE
Keep only specifed track for batch videos

### ISSUE THREAD

**Issue by skywinder** [mifi/lossless-cut#1937]
### Description

In additions to https://github.com/mifi/lossless-cut/issues/1879 (to fix issue with autoplay option of DJI files, I need to keep only the first track. So now, I have to do it manually for each track by clicking the track selection. It would be great to set this as the default for batch videos.

![CleanShot 2024-03-25 at 21 11 29@2x](https://github.com/mifi/lossless-cut/assets/3356474/5fb60620-e13a-4d76-bec4-67e8360e2579)
![CleanShot 2024-03-25 at 21 11 49@2x](https://github.com/mifi/lossless-cut/assets/3356474/5225230d-2339-4d25-bb72-9d306d35f757)

**Comment by skywinder** [comment]
btw, I also have related question: i tried to find shortcut for that and found this 2 actions, that looks that do the same. what the differences between 
`toggleStreamsSelector` and `showStreamsSelector`?


![CleanShot 2024-03-25 at 22 31 56@2x](https://github.com/mifi/lossless-cut/assets/3356474/64a955c6-16f3-4ea5-823e-7d3239c8c485)

**Comment by mifi** [comment]
> In additions to #1879 (to fix issue with autoplay option of DJI files, I need to keep only the first track. So now, I have to do it manually for each track by clicking the track selection. It would be great to set this as the default for batch videos.

Not sure about making it default, but it is tracked in this issue #371 "Enabled Tracks".

There is already a toggle button (and keyboard action) for disabling/enabling all audio tracks. I think a similar keyboard action for "toggle video tracks" could help for your use case. I've added the suggestion here: https://github.com/mifi/lossless-cut/issues/254#issuecomment-1996881797

> btw, I also have related question: i tried to find shortcut for that and found this 2 actions, that looks that do the same. what the differences between `toggleStreamsSelector` and `showStreamsSelector`?

one is toggle on/off, other is turn on (regardless of current state), as can be seen in the code:

- https://github.com/search?q=repo%3Amifi%2Flossless-cut%20showStreamsSelector&type=code
- https://github.com/mifi/lossless-cut/blob/191f0c71bd8d03a78ddec1cd3e839f5f871fe058/src/renderer/src/App.tsx#L1714

**Comment by mifi** [comment]
closing this issue because your concerns are being tracked in the other issues
