### ISSUE TITLE
universal install package does not work

### ISSUE THREAD

**Issue by tcz305** [mifi/lossless-cut#1938]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

MacOS 13

### Steps to reproduce

The seperate app in dmg files work fine.
Using the universal package installer the app will not open.
Crash report is attached.

### Expected behavior

app should open

### Actual behavior

crashes on startup 

### Share log from developer tools

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: 23CD48BC-12C2-4F86-89C2-A81971FCDBAE
CrashReporter Key:   F5BF08E0-A78B-ABB2-444F-79C6AE114DB6
Hardware Model:      iMac18,2
Process:             LosslessCut [13428]
Path:                /Applications/LosslessCut.app/Contents/MacOS/LosslessCut
Identifier:          no.mifi.losslesscut-mac
Version:             3.60.0 (3.60.0)
Code Type:           X86-64 (Native)
Role:                Default
Parent Process:      launchd [1]
Coalition:           no.mifi.losslesscut-mac [5415]

Date/Time:           2024-03-25 22:18:04.0925 -0400
Launch Time:         2024-03-25 22:18:04.0618 -0400
OS Version:          macOS 13.6.1 (22G313)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGKILL (Code Signature Invalid))
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: CODESIGNING 1 Taskgated Invalid Signature

Triggered by Thread:  0

Thread 0 Crashed:
0   ???                           	       0x11a5bb070 _dyld_start + 0
1                                 	       0x10ea46000 ???

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ff7b14b9bc8
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x000000011a5bb070  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000 
Trap Number:     0

Binary Images:
       0x11a5b6000 -        0x11a651fff ??? (*) <3df96f32-b9c9-3566-a6b7-4daebc6d6563> ???
       0x10ea46000 -        0x10ea47fff  (*) <4c4c4414-5555-3144-a14f-ae3644a5dc58> ???

Error Formulating Crash Report:
dyld_process_snapshot_get_shared_cache failed

EOF

-----------
Full Report
-----------

{"app_name":"LosslessCut","timestamp":"2024-03-25 22:18:04.00 -0400","app_version":"3.60.0","slice_uuid":"4c4c4414-5555-3144-a14f-ae3644a5dc58","build_version":"3.60.0","platform":0,"bundleID":"no.mifi.losslesscut-mac","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.6.1 (22G313)","roots_installed":0,"name":"LosslessCut","incident_id":"23CD48BC-12C2-4F86-89C2-A81971FCDBAE"}
{
  "uptime" : 40000,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iMac18,2",
  "coalitionID" : 5415,
  "osVersion" : {
    "train" : "macOS 13.6.1",
    "build" : "22G313",
    "releaseType" : "User"
  },
  "captureTime" : "2024-03-25 22:18:04.0925 -0400",
  "incident" : "23CD48BC-12C2-4F86-89C2-A81971FCDBAE",
  "pid" : 13428,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-03-25 22:18:04.0618 -0400",
  "procStartAbsTime" : 40740158344104,
  "procExitAbsTime" : 40740188623085,
  "procName" : "LosslessCut",
  "procPath" : "\/Applications\/LosslessCut.app\/Contents\/MacOS\/LosslessCut",
  "bundleInfo" : {"CFBundleShortVersionString":"3.60.0","CFBundleVersion":"3.60.0","CFBundleIdentifier":"no.mifi.losslesscut-mac"},
  "storeInfo" : {"deviceIdentifierForVendor":"1CAA9CB6-3FD9-5556-AE58-1A41FF5FEF4B","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "no.mifi.losslesscut-mac",
  "crashReporterKey" : "F5BF08E0-A78B-ABB2-444F-79C6AE114DB6",
  "codeSigningID" : "",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 16777216,
  "codeSigningValidationCategory" : 0,
  "codeSigningTrustLevel" : 0,
  "wakeTime" : 33051,
  "sleepWakeUUID" : "76D7A5BA-7B78-4D6A-B818-A3F2A0BABD73",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGKILL (Code Signature Invalid)"},
  "termination" : {"flags":66,"code":1,"namespace":"CODESIGNING","indicator":"Taskgated Invalid Signature"},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":365152,"threadState":{"r13":{"value":0},"rax":{"value":0},"rflags":{"value":512},"cpu":{"value":0},"r14":{"value":0},"rsi":{"value":0},"r8":{"value":0},"cr2":{"value":0},"rdx":{"value":0},"r10":{"value":0},"r9":{"value":0},"r15":{"value":0},"rbx":{"value":0},"trap":{"value":0},"err":{"value":0},"r11":{"value":0},"rip":{"value":4737183856,"matchesCrashFrame":1},"rbp":{"value":0},"rsp":{"value":140701808171976},"r12":{"value":0},"rcx":{"value":0},"flavor":"x86_THREAD_STATE","rdi":{"value":0}},"frames":[{"imageOffset":20592,"symbol":"_dyld_start","symbolLocation":0,"imageIndex":0},{"imageOffset":0,"imageIndex":1}]}],
  "usedImages" : [
  {
    "size" : 638976,
    "arch" : "x86_64",
    "source" : "P",
    "base" : 4737163264,
    "uuid" : "3df96f32-b9c9-3566-a6b7-4daebc6d6563"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4540620800,
    "size" : 8192,
    "uuid" : "4c4c4414-5555-3144-a14f-ae3644a5dc58",
    "name" : ""
  }
],
  "vmSummary" : "ReadOnly portion of Libraries: Total=988K resident=0K(0%) swapped_out_or_unallocated=988K(100%)\nWritable regions: Total=8192K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8192K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                          4K        1 \n__DATA                              20K        2 \n__DATA_CONST                        36K        2 \n__DATA_DIRTY                        16K        1 \n__LINKEDIT                         368K        4 \n__TEXT                             632K        2 \nshared memory                        4K        1 \n===========                     =======  ======= \nTOTAL                             65.1M       15 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "4b658d28912592c55a6ca4934adceb76ff94ca33",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "61675b89201f677a9a4cbd65",
      "factorPackIds" : {
        "HEALTH_FEATURE_AVAILABILITY" : "65a855f5f087695cfac03d1f"
      },
      "deploymentId" : 240000095
    },
    {
      "rolloutId" : "6425c75e4327780c10cc4252",
      "factorPackIds" : {
        "SIRI_HOME_AUTOMATION_INTENT_SELECTION_CACHE" : "642600a457e7664b1698eb32"
      },
      "deploymentId" : 240000004
    }
  ],
  "experiments" : [

  ]
},
  "reportNotes" : [
  "dyld_process_snapshot_get_shared_cache failed"
]
}

Model: iMac18,2, BootROM 522.0.0.0.0, 4 processors, Quad-Core Intel Core i5, 3.4 GHz, 8 GB, SMC 2.40f1
Graphics: Radeon Pro 560, Radeon Pro 560, PCIe, 4 GB
Display: iMac, 4096 x 2304 Retina, Main, MirrorOff, Online
Memory Module: BANK 0/DIMM0, 4 GB, DDR4 SO-DIMM, 2400 MHz, 0x802C, 0x344154463531323634485A2D3247334532202020
Memory Module: BANK 1/DIMM0, 4 GB, DDR4 SO-DIMM, 2400 MHz, 0x802C, 0x344154463531323634485A2D3247334532202020
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x16E), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1772.1)
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: APPLE HDD HTS541010A9E632, 1 TB
USB Device: USB30Bus
USB Device: Bluetooth USB Host Controller
USB Device: FaceTime HD Camera (Built-in)
Thunderbolt Bus: iMac, Apple Inc., 41.5

**Comment by mifi** [comment]
the pkg file is for App Store distrubution only and does not work. use the dmg instead.
