### ISSUE TITLE
Merge cut export fade to black or fade to next clip

### ISSUE THREAD

**Issue by s2xnetx** [mifi/lossless-cut#1944]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

It would be great when we export cuts and merge them to be able to add a fade from and to black for the clips (via setting a timer for fades). Or add a fade to the next clip via setting a timer (i know this would be more difficult). But I would be happy with the fade to black solution.

**Comment by mifi** [comment]
> - [x] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists

**Comment by The-Gaymer** [comment]
> > * [x]  [mifi](https://github.com/mifi)
closed this as [completed][on Apr 3, 2024]

Hello mifi, thanks for your hardwork, and sorry for duplicate.
You Said this topic is closes as it completed, but i can't find this feature anywhere in app, can you help me find it please ? 
Thanks 😁

**Comment by mifi** [comment]
hi, i meant to close as duplicate of #372 - it has not been implemented.
