### ISSUE TITLE
Auto merge segments orders

### ISSUE THREAD

**Issue by HugoHeneault** [mifi/lossless-cut#195]
Awesome tool! I have to say: thank you! 🎉 

That being said, I've been surprised because with multi-segments exports they are ordered by segment creation time.

I would expect the segments to be ordered by their timing in the original file. 

Example:

I create a segment from 0'30 to 0'40 then I remember I made a nice shot from 0'10 to 0'20. 
In the merged export, the 0'30 segment appears before the 0'10. 🤔 

A toggle might be cool! But I think we should keep the original order :)

Cheers!

**Comment by mifi** [comment]
Ahh yes I would call this a bug.

**Comment by mifi** [comment]
fixed. will be released in newest version

**Comment by snakecase** [comment]
Still an issue. I suggest adding a button which automatically renumbers segments by the order of appearance on the timeline because it can still be valuable to rearrange segments differently for artistic reasons. And thank you for such a great tool!

**Comment by mifi** [comment]
In the nwest version now there is a menu item to sort segments by time Tools -> segments
