### ISSUE TITLE
different configuration support for different copys of Losslesscut

### ISSUE THREAD

**Issue by kulkatt** [mifi/lossless-cut#1956]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

I use different configuration for many situations, modifying settings every time is very inconvenient.
maybe the configuration files could be saved in the same folder as lossless-cut.exe so different configurations is possible.
thanks you.

**Comment by mifi** [comment]
LosslessCut should already (on windows) pick up a `config.json` if it exists in the same folder as the .exe file, see #645

What you're asking for is a way to specify the config file from the command line, right? e.g.
```bash
LosslessCut.exe --config config1.json
```
or
```bash
LosslessCut.exe --config config2.json
```

**Comment by kulkatt** [comment]
> LosslessCut.exe --config config1.json

thank you for your response, I just tested.
seems the config file with version3.59.1.0 on my win10 is C:\Users\[username]\AppData\Roaming\LosslessCut\config.json
specify the full path, like --config LosslessCut.exe c:/config1.json, not working

**Comment by mifi** [comment]
> > LosslessCut.exe --config config1.json
> 
> thank you for your response, I just tested. seems the config file with version3.59.1.0 on my win10 is C:\Users[username]\AppData\Roaming\LosslessCut\config.json specify the full path, like --config LosslessCut.exe c:/config1.json, not working

that's because losslesscut doesn't support that yet.

**Comment by mifi** [comment]
next version will have a new cli arg `--config-dir`
