### ISSUE TITLE
Improving fast seek behavior ?

### ISSUE THREAD

**Issue by Mrnofish** [mifi/lossless-cut#1957]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Currently losslesscut employs an acceleration technique when a seek button is kept pressed.

This is an exceedingly annoying behavior whenever I'm scanning for specific events in a long video, such as highlights in a match: I need to stop pressing the seek button repeatedly, otherwise the seek point will start skipping forward in bigger increments, jumping over shorter action sequences entirely.

One way to ameloriate this issue would be a way to disable skip acceleration.

Another could be having a way to scan a video automatically at high speed, without having to keep the skip button pressed.

What do you think?

**Comment by mifi** [comment]
"Timeline keyboard seek acceleration" under settings.

**Comment by Mrnofish** [comment]
Sorry, I did look for a preference but obviously I must've missed that slider.

That said, even after disabling acceleration, I'm still forced to release the FFWD button every now and then, otherwise the preview stops updating regularly.

It seems to work fine for a while after the button is first pressed, however, after some time, the jumps become quite big.

This seems to happen mostly with longer videos, roughly 2 hours.

I can fast seek a video with MPC-HC or VLC from a mechanical drive with no issue, but LosslessCut exhibits this problem even when the same file is copied to an SSD.

It gets worse if I increase the keyboard skip value. Setting it to 5 or 10 seconds causes the preview to stop completely after the first frame update.

Dropping it to 0.8 improves the situation.

BTW the sliders are quite inconvenient to operate: there's a wide range compared to the screen representation, and making accurate changes is hard.

If I click on the slider handle, I can make exactly one change with the keyboard: subsequent key presses are fed to the main window instead of the slider control.

**Comment by mifi** [comment]
> That said, even after disabling acceleration, I'm still forced to release the FFWD button every now and then, otherwise the preview stops updating regularly.

I believe it's the same as #1881

> BTW the sliders are quite inconvenient to operate: the range is very wide compared to its screen representation, making accurate changes is hard.

the next version will include a more precise slider (currently in nightly build) ca7a9d3eebfb990cca2955e20e77739faa9da018

**Comment by Mrnofish** [comment]
I've subscribed to the other issue and will report there after the changes mentioned here and there have made it to the public.

Thank you for the help!
