### ISSUE TITLE
Can't support drag & drop for M4A files?

### ISSUE THREAD

**Issue by g33khubber** [mifi/lossless-cut#1958]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

thought it'd be a pretty popular audio format, but turns out it's not supported? I'm on the very latest version, portable from Github.

**Comment by mifi** [comment]
please use this instead https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&projects=&template=1-file-issue.yml

**Comment by mifi** [comment]
really? I just tried this file and it works for me: https://samples.ffmpeg.org/A-codecs/AAC/8_Channel_ID.m4a can you confirm that it fails for you? what's the error you're getting?

**Comment by g33khubber** [comment]
Ok - I noticed it can't be dragged & dropped onto the UI, but I can
manually open it via Ctrl+O.

**Comment by mifi** [comment]
so the problem has nothing to do with m4a files in particular? this problem exists for all files? also which OS are you on?

**Comment by mifi** [comment]
i can't explain that. if you rename the m4a file to mp4, does it work then?

**Comment by g33khubber** [comment]
just tried - It doesn't.

**Comment by g33khubber** [comment]
Apologies - just realized now the drag & drop doesn't work with other file
formats too. 😅
