### ISSUE TITLE
Copy and Paste Segment Tags

### ISSUE THREAD

**Issue by s2xnetx** [mifi/lossless-cut#1964]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

It would be awesome to be able to copy all the segment tags from one segment and paste them to another segment.

**Comment by mifi** [comment]
coming in next version (and nightly build)

**Comment by s2xnetx** [comment]
Very nice. Thank you. It would be great to add the copy and paste functions to the segment context menu too, to be able to use it without opening the tag editor.

**Comment by mifi** [comment]
sounds like a quite niche use case which could be achieved by other means (scripting/modifying the `.llc` files), but i might implement it if requested by more people
