### ISSUE TITLE
Audio Loss When Exporting

### ISSUE THREAD

**Issue by pepino21** [mifi/lossless-cut#1967]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 11

### Steps to reproduce

I import a file to change its container (An example is changing a webm file to mp4), but all of a sudden these past two weeks the audio doesn't seem to stay with the exported file.

### Expected behavior

Final exported result with audio.

### Actual behavior

Final Exported result without audio.

### Share log from developer tools

No unexpected bug crash.

**Comment by mifi** [comment]
does this happen with all kinds of video files?

**Comment by mifi** [comment]
closing due to no response
