### ISSUE TITLE
Repeated frames at each joined segment or chapter in continuous video

### ISSUE THREAD

**Issue by dellyspice69** [mifi/lossless-cut#1973]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

This applies to version 3.59.1.0. When using the "merge cuts" feature on a MP4 video file, there are repeated frames at each new segment, even when the cuts are (only) at key frames, these are clearly visible when viewing the final (joined) video. This happens when there is no gap between segments, i.e. when the time code at the end of the previous segment is the same as the start of the next segment. It is difficult to tell if there are any repeated frames where there is a gap between (joined) segments, i.e. when the time code at the start of a new segment is not the same as the end of a previous segment. The repeated frames occur regardless of whether or not chapters are created in the merged video, so even a merged video without chapters has the visible repeated frames at the join points. Of course, there is no reason to have a join in a continuous video except to insert a chapter point but this information is provided for purposes of diagnosis.

### Expected behavior

When joining cuts at key frames, I would expect a smooth transition from one segment/chapter to the next so that there is no indication of a join (as per the original video), where there is no time gap between each segment/chapter.

### Actual behavior

There are repeated frames at each join point in a continuous video which are clearly visible when viewing the joined video, this happens regardless of whether chapters are being inserted into the output video. Changing the "avoid_negative_ts" from "auto" to "make_zero", the recommended options, makes no difference. Deselecting "Keyframe cut mode" solves the problem of the repeated frames but creates a worse problem by having still frames in the video instead which are even more obvious during playback of the output video.

**Comment by mifi** [comment]
out of curiosity did you try to disable all tracks except video and see if the same happens?

**Comment by mifi** [comment]
closing due to no response
