### ISSUE TITLE
GPU encoding to VP9 codec

### ISSUE THREAD

**Issue by sks2012** [mifi/lossless-cut#1974]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

https://developer.chrome.com/blog/vp9-webrtc?hl=ru
Please add the ability to encode in vp9 using GPU, by WebRTC.

**Comment by mifi** [comment]
> - [x] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists

#372

**Comment by sks2012** [comment]
I, uh, I don't get it.
Is there already GPU-accelerated encoding in VP9?
