### ISSUE TITLE
Custom folder paths for exports on Windows

### ISSUE THREAD

**Issue by t3dotgg** [mifi/lossless-cut#1979]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

I cut an issue about bad folder directories being created on Windows awhile ago https://github.com/mifi/lossless-cut/issues/1790

Just set up a new PC and updated to latest Lossless-Cut. Didn't realize I wouldn't be able to export to per-segment directories anymore :(

Ideally I'd still be able to use (dynamic) folder names on Windows. If not, I think a better error here would be nice.

Also thought that turning off sanitization should let me do this still :(

<img width="693" alt="image" src="https://github.com/mifi/lossless-cut/assets/6751787/df06f375-dd22-4425-a411-33052a1b689d">

**Comment by mifi** [comment]
Hmm, I just tested on windows 11 and I'm not getting this error on 3.59.1 when including a slash, and it's correctly creating the `clips` directory for me.

What I'm suspecting is that one of your segments' `SEG_LABEL` variable contains disallowed characters. If you click on Preview button, what do you see as "resulting file names"? on windows, when sanitize is "off", the following characters are not allowed: `'<', '>', ':', '"', '|', '?', '*'`

https://github.com/mifi/lossless-cut/blob/9ea438052f05d019e4594d4fd978b15b83862e1a/src/renderer/src/util/outputNameTemplate.ts#L34

> I think a better error here would be nice.

I will improve the error message to specify exactly which characters are invalid.

**Comment by mifi** [comment]
error message is improved. can reopen if you can reproduce the problem
