### ISSUE TITLE
XFade between cuts

### ISSUE THREAD

**Issue by federicotortora** [mifi/lossless-cut#1983]
basically the request is to add the possibility to make the ffmpeg command execute also https://trac.ffmpeg.org/wiki/Xfade while merging segments. I'm now doing that by copying last ffmpeg command(s) from the menu and execute it in terminal after changing the command where it's needed

**Comment by mifi** [comment]
> - [x] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists

> Can LosslessCut crop, resize, stretch, mirror, overlay text/images, watermark, blur, redact, re-encode, create GIF, slideshow, burn subtitles, color grading, fade/transition between video clips, fade/combine/mix/merge audio tracks or change audio volume?
