### ISSUE TITLE
docker version would be nice

### ISSUE THREAD

**Issue by sacsbrainz** [mifi/lossless-cut#1985]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

for flexibility 
would be nice to `docker compose up -d` and you have the app running

**Comment by mifi** [comment]
> - [x] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists

https://github.com/search?q=repo%3Amifi%2Flossless-cut%20docker&type=code

#1086

**Comment by Verkhovskyi** [comment]
> [#1086](https://github.com/mifi/lossless-cut/issues/1086)

Looks like mentioned Docker build is abandoned a long time ago. I've used it a lot in Docker forming my Plex library. It would be really nice to have official container. Though I understand it may not be worth the effort. Thank you for your work!

**Comment by mifi** [comment]
I'm totally open to linking to docker file maintained by someone else, or if it's just a single docker file, i can host it here in this repo to. But my knowledge about docker is lacking. And I don't have time to provide support on keeping docker up-to-date as electron gets upgraded etc, so someone else would have to do that.
