### ISSUE TITLE
[Request] Import csv file with timers and names

### ISSUE THREAD

**Issue by DarkWiss** [mifi/lossless-cut#199]
Hi, I love your tool and it's simplicity to use.
It would be great to be able to import a file (csv or else) with timers, and for the software to automatically put it on the timeline. 
It would be awsome for reviewing video logging and cutting them without any video editing software.
Also, the ability to name each cut made and putting it in the filename for easier tracking after cutting them.

Regards,
(I hope I was understandable in my proposal).

**Comment by mifi** [comment]
auto and manual export/import of timestamps from CSV is now implemented in newest version along with many other new features!

**Comment by DarkWiss** [comment]
Awesome, thanks for your work.
The csv formating is ( start time,end time,title) right? The timestamps are in seconds?

I'll try it in my workflow and keep you posted.

**Comment by mifi** [comment]
Yes, you can try to export a csv and you see the format. I'll add documentation in readme
