### ISSUE TITLE
[Feature] Add playback-speed control and segment operations (delay/offset)

### ISSUE THREAD

**Issue by marcosilva85** [mifi/lossless-cut#1992]
### Description

Hi, this is a suggestion for 3 small features to improve the workflow of those who of us who do segment definitions during playback and who would like to have it done in one-sitting (one-playback).

1. Could we quickly adjust the playback-speed (1.5x, 2x, 3x... ) like most software tools in the video domain have, with hotkey and maybe in with a 1-click switch icon between speeds on the UI?

2. We sadly cannot directly edit any of the times in the segments list itself (right-panel) and would be great if we could add/subtract offset (some seconds) to duration, starting or ending points of segment(s).

3. It would be great if we could "Select only segments that were defined during video playback", then do the operations above, as these are often the ones in need of re-adjustments, which would help the workflow which I describe bellow.

A user story / my context: I heavily use a workflow where I do a full video-playback and do the segmentation as a blueprint of what I'd like to keep, then I do a second pass to readjust all starting points to start some seconds earlier.

These new minor additions would allow me to avoid doing the full second pass on all segments to re-adjust properly the ones which are missing the right start of the "action". As I define them during playback I usually miss some seconds until I realize "something happened" that I want to keep and setting the point, however, having this, I could just choose "select only the segments defined during playback" and "add offset to start of segment: -3 seconds" and finalize it in a one-sitting workflow.

**Comment by mifi** [comment]
> * Could we quickly adjust the playback-speed (1.5x, 2x, 3x... ) like most software tools in the video domain have, with hotkey and maybe in with a 1-click switch icon between speeds on the UI?

J, K and L keyboard shortcuts


> * We sadly cannot directly edit any of the times in the segments list itself (right-panel) and would be great if we could add/subtract offset (some seconds) to duration, starting or ending points of segment(s).

This can be achieved by either
1. use checkboxes in the lower right of a sgment in the segment list to select the desired segment only. Then Segments menu (application menu) -> Shift all segments on timeline, or
2. type a new time into the start/end time to the left/right of the Play button at the bottom


> 3\. It would be great if we could "Select only segments that were defined during video playback", then do the operations above, as these are often the ones in need of re-adjustments, which would help the workflow which I describe bellow.

as described above, you can use checkboxes in the lower right of a segment in the segment list to select which segments you want to affect, then run any operations on them

**Comment by marcosilva85** [comment]
My bad, was not aware of such menu's, and indeed, they all works. Thank you! Closing.
