### ISSUE TITLE
[3.61] [Win10/64] "Keyboard & Mouse Shortcuts" Help Item no longer works

### ISSUE THREAD

**Issue by Mrnofish** [mifi/lossless-cut#1996]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

1. Open LosslessCut
2. Open the Help Menu
3. Select "Keyboard & Mouse Shortcuts"

### Expected behavior

A list of shortcuts used to open in previous versions.

### Actual behavior

Nothing happens, seemingly.

### Share log from developer tools

The Dev Tools Console has no further information.

**Comment by mifi** [comment]
that was a bug. thanks for reporting
