### ISSUE TITLE
[Feature Request] Filter segments by length

### ISSUE THREAD

**Issue by markmillerdev** [mifi/lossless-cut#1999]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

A LosslessCut use case is to remove very short scene-change segments, as from a video chat recording when people may say a single word or otherwise makes a noise that causes the focus to move to them and then back to the main speaker.  After running Detect Scene Change, it would be useful to have a way to select segments that are, for example, shorter than 2 seconds (or any user-defined length), which would then allow the user to delete those in bulk.

**Comment by mifi** [comment]
will implement

**Comment by attaboyBrad** [comment]
Was this ever implemented? I can't seem to find the feature documented anywhere if so, and I'd love to have this feature as well.

**Comment by mifi** [comment]
Yes you can select by JS expression
