### ISSUE TITLE
Not opening videos

### ISSUE THREAD

**Issue by robotwerks** [mifi/lossless-cut#2]
I'm running into an issue where Lossless Cut will not open videos at all. I have tried confirming the FFMPEG path, tried different formats,etc. Is there a definitive list of what media works and what doesn't?

**Comment by mifi** [comment]
Hi.
There isn't a definitive list yet. I just made this for my own use and decided to share it :)
The video player itself is html5 video player in Electron, so it should comply with Chromium's supported formats/codecs:
https://www.chromium.org/audio-video

What kind of format/codec are you trying?
I guess I should add a check to see if the format is supported or not when opening a file. It would also be possible to (losslessly) re-format the video using ffmpeg before opening it.

**Comment by mifi** [comment]
With 1.2 it now supports more formats.
