### ISSUE TITLE
Request: hear sound

### ISSUE THREAD

**Issue by vitorgalvao** [mifi/lossless-cut#20]
One thing I really like about other video editors when cutting is that when transversing the file they still play a fraction of the sound at the moment of movement. This is particularly useful when trying to cut a piece of video where the audio also matters, as you can have a better sense of when the important part actually starts (or end).

For a precise cutter like LosslessCut, where no reencoding happens, that would be extremely welcome.

**Comment by mifi** [comment]
LosslessCut is using the HTML5 video player. I cannot think of a simple way to solve this right now. But suggestions for solving this are welcome!
It will currently play sound if you have it in play mode while seeking though...
