### ISSUE TITLE
Allow Export / Import / Saving of clip segment projects

### ISSUE THREAD

**Issue by pkamb** [mifi/lossless-cut#200]
Please allow app state to be recreated for a particular video file and the cuts you have made.

This could be as simple as exporting/importing a json file containing the different cuts and timestamps.

Yesterday I made a 12-segment cut in a video via LosslessCut. Today I opened my Mac and for whatever reason the app had quit. I have no way to recreated the clips without a ton of manual work.

This would also be very helpful for recreating issues in the app. Send the original video + the text file containing the cuts.

**Comment by mifi** [comment]
I understand that this is frustrating. Could implement something like this.

**Comment by mifi** [comment]
#181
