### ISSUE TITLE
[FEATURE] Be able to change the segments suffix name from " -segXXX" to anything else.

### ISSUE THREAD

**Issue by masterofobzene** [mifi/lossless-cut#2000]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

The automatic " -seg001" suffix on files are triggering bugs in playlists that take "-" character as a special character. We need a way to input a custom suffix when this causes trouble OR you need to remove the "-" character from the automatic suffix.

The bug can be experienced on certain situations of many files in a m3u playlist using MPV.

Since I consider that adding a custom suffix would be handy even for other needs, I ask to add this feature in a future version.

**Comment by mifi** [comment]
hmm, so is the problem the leading space character in ` -segXX` or is the problem the dash `-` ? I cannot reproduce the leading space problem. when i try to export it gives me `input-seg01.mp4` (when I use `${FILENAME}-${SEG_SUFFIX}${EXT}`).

what does your output file name template look like in the export confirm dialog?

if you want to remove the `-segXX` and provide your own suffix, then simply change the template to something like:
```
${FILENAME}_mysuffix${SEG_NUM}${EXT}
```

that will give you `input_mysuffix01.mp4`

**Comment by mifi** [comment]
in the Export options dialog click on the output file names:

<img width="676" alt="Screenshot 2024-05-19 at 23 33 28" src="https://github.com/mifi/lossless-cut/assets/402547/d6b91b37-0f64-45ce-94d8-5bf51b8fd26c">
