### ISSUE TITLE
File Open

### ISSUE THREAD

**Issue by networkproblemsolver** [mifi/lossless-cut#2001]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

I just upgraded to the latest version and the FILE OPEN now tries to open a FOLDER and will not let me "just choose a file."

How can I change this back to the way it was before -- allowing me to select ONE file (or several files) instead of CHOOSE FOLDER?

Thx!

**Comment by outlyer-net** [comment]
See https://github.com/mifi/lossless-cut/discussions/1995
