### ISSUE TITLE
Find video clips with subtitles

### ISSUE THREAD

**Issue by github55666** [mifi/lossless-cut#2002]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Hi,Can the software add a function to find corresponding video segments through subtitles on the "Segments to export:" function? Thank you.
![image](https://github.com/mifi/lossless-cut/assets/140618709/13ca9bb3-5fd9-494a-abdd-78824a05e8a4)

**Comment by mifi** [comment]
next version will have a new feature: create segments from subtitles (tracks panel, then track menu). I hope that will solve your use case
