### ISSUE TITLE
Focus the segment nearest to the playback cursor (keyboard behaviour)

### ISSUE THREAD

**Issue by marcosilva85** [mifi/lossless-cut#2004]
### Steps to reproduce

A minor issue I still have in Losslesscut : 
I navigate forward/backwards with the keyboard in the timeline, however, landing on a segment does not make it focused, so whatever cuts I try to make don't apply to it, instead they apply on the last one, somehow.
- if however I use the mouse to do the same and click in the timeline on a segment, it properly focus it so the operations I do apply to it.

### Expected behavior

- is there a way to add "Focus the segment nearest to the playback cursor" ? Should focus when manually navigating or when pausing playback on a certain timeline point.

**Comment by mifi** [comment]
Next version will have a new keyboard action `Focus segment at cursor`
