### ISSUE TITLE
New releases

### ISSUE THREAD

**Issue by dreamflasher** [mifi/lossless-cut#2006]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Thank you for your great work! There hasn't been a release in about half a year, and there are a bunch of features I'd like to use. I know I can build head or use one of the nightlies, but it would be very convenient to have a new release maybe monthly, which is known to be stable? Thank you for considering.

[EDIT] I didn't notice that there is a pre-release from 5 days ago, as it's not shown on the main page. Then I am looking forward to the new release soon – but a minor release from time to time would be fantastic :)

**Comment by mifi** [comment]
Hi. There's no fixed release schedule unfortunately. The pre-release was initially a release but it had some serious bugs so I had to degrade it to pre-release. a new version is coming soon. until then you can use nightly builds. If you would like a new build every month you could use nightly builds, they are fairly stable most of the time.
