### ISSUE TITLE
2.4.0 bug with output format

### ISSUE THREAD

**Issue by tommisaltiola** [mifi/lossless-cut#201]
Hello

I have an issue with the latest Lossless Cut release 2.4.0

I use Sony a7R II which outputs 4K S-Log2 in .mp4 format and H.264 codec. When I try to cut the videos lossless cut is saying that:

Whoops! ffmpeg was unable to cut this video. Try each of the following thing before attempting to cut again:
1. Selevt different output format
2. toggle the button "all" to "ps"

When I start Lossless Cut the output format is mp4, which is the case with my files. However when I manually change it to .MOV (Which is not the case with the files I load to Lossless Cut, or with the files that it exports out, they are still mp4) , which I have to do every time manually, it cuts it without error.

Could you add maybe a toggle setting for the output format so that I wouldn’t have to manually change the format every time I load a new video to it Lossless Cut? Or even better, make it work with .mp4 files if the setting is on mp4..

You say you have added “Allow user to select output format to workaround certain issues like #173”
Maybe there is something that mixes things up?

Meanwhile Im stuck in the previous version 2.3.0 of Lossless Cut - it still works perfectly

**Comment by mifi** [comment]
Is the problem that in 2.4.0 it detects the file as mp4, and in 2.3.0 it detects it as mov?

**Comment by mifi** [comment]
Try again with v3, reopen if still an issue
