### ISSUE TITLE
Perform batch cutting of files for a fixed time of minutes and seconds from the list

### ISSUE THREAD

**Issue by DruidCtba** [mifi/lossless-cut#2011]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Hey buddy Mifi, first off, I'd like to congratulate you on your excellent work.

So, I've got a bit of an issue right now that should be pretty simple to solve. I can do it manually like your losslesscut, which is splitting MP4 files to a fixed time, but doing it for dozens or hundreds of files is quite a chore.

I see you already have the option to read batches of files in your program, so I don't see much difficulty in implementing a command to do this automatically, as they suggested here, while I have a little coffee :).

The idea here is to have an option where you input the time for splitting the files, for example: 00:04:59.000, and it allows exporting all the files from the list in segments all at once. You don't even need to implement a file selection, that's even better, if not, just take all the loaded files from the list, a button that says <EXPORT ALL>.

Thanks a lot for your attention :P.

Best regards,

Druid®.

P.S. I just saw in the MENU, the tools option, and yes, this option doesn't exist, but the opposite does, which would be MERGE, please consider implementing this feature, batch resources are a lifesaver.

**Comment by mifi** [comment]
Hi. I believe your request is the same as #868

In that case, see the example workaround. you can fill in the start time `TIME_TO_CUT_FROM=299` (4*60 + 59)

**Comment by DruidCtba** [comment]
But I didn't quite get it, is the bash script going to split a file, for example, of 9 minutes and 19 seconds, into two files, one of 4 minutes and 59 seconds, and the other of 4 minutes and 20 seconds, is that it?

I didn't quite get it because I have two variables: TIME_TO_CUT_FROM and TIME_TO_CUT_TO.

If I have, for example, a 14-minute file, will this bash script split this file into three files: the first one of 299 seconds, the second one of 299 seconds, and the third one of 242 seconds, which together give 14 minutes or 840 seconds?

Thanks for responding.

Druid®.

**Comment by mifi** [comment]
No. A split is basically just the same as two cut operations. If you want to split, you would have to run the ffmpeg operation twice inside the for-loop.

e.g. u have a file 60 seconds long and you want to split it into two parts at the 20 second mark you would typically:
1. make an ffmpeg cut from 0 to 20
2. make an ffmpeg cut from 20 to 60

**Comment by DruidCtba** [comment]
Hey buddy @mifi, I think what wasn't understood here is the issue that some people might face, like me:

I have a folder with one, none, or several MP4 files of varying sizes, I don't know, and the program will have to handle this. So, in the case of your program LOSSLESSCUT, it has the option to load these MP4 video files from this folder. Currently, if I tell it to split an MP4 file into equal parts of 299 seconds, it does it perfectly. What's missing is for it to loop, to read one by one, all the files from the list and split them into equal parts of 299 seconds. That's all, just to AUTOMATE A PROCESS that already exists in your program, but in batch.

Yes, I know that others have requested different ways, some need to cut an initial part in seconds or minutes, and also a final part in seconds or minutes of MP4 files in batch. It's called AUTOMATING A PROCESS, that's what computing is for, to make the laborious task easier than having to do it one by one.

And yes, I tried using the CHAT-GPT4o for this, and it failed miserably, it gets completely lost in the ffmpeg library, if you've tried it, you'll see how exhausting it is. I did it in C#, Windows Prompt Script, and it got worse with each interaction with me.

Oh yes, I tried the BlackBox Plugin for VS Code, and believe it or not, it got lost in the same way, it was freezing, didn't know how to form a loop with ffmpeg; anyway, I appreciate your attention. I just hope that in the future you implement automation of processes in LOOSLESSCUT for the mentioned cases and future requests. I understand that this improves and creates a competitive edge for your product, even though it's open source, it can also be commercialized.

Best regards,

Druid®.

**Comment by mifi** [comment]
Ok, so I think I understand now, you have a folder with X number of mp4 files, and for each of these files you want to split into an unknown number of output files, each 299 seconds long. (how many files it will produce depends on the length of each input file), e.g. `number_of_output_files=length_of_input_file_in_seconds/299`.

The problem with these batch features is that there are many people who want many different kinds of batch features like this, but each feature doesn't have much in common and must be implemented separately, and tested/maintained in the future. Therefore I need to prioritise the most popular features.

Implementing the batch feature that you're asking for is not trivial and we cannot be simply be added to existing functionality.

Anyways I've added your request to #868 and will close this to keep issues down. I might implement it if many people ask for it. thanks!

**Comment by mifi** [comment]
oh and just for fun I did ask chatGTP:

> write a bash script that takes a folder of mp4 files, then for each file, split it into an (unknown) number of files, each file of an equal length of 299 seconds.

here is what it gave me:

```bash
#!/bin/bash

# Check if directory is supplied as an argument
if [ -z "$1" ]; then
  echo "Usage: $0 <directory>"
  exit 1
fi

DIRECTORY=$1

# Check if the supplied argument is a directory
if [ ! -d "$DIRECTORY" ]; then
  echo "Error: $DIRECTORY is not a directory"
  exit 1
fi

# Iterate over each MP4 file in the directory
for FILE in "$DIRECTORY"/*.mp4; do
  # Check if there are no mp4 files in the directory
  if [ ! -e "$FILE" ]; then
    echo "No mp4 files found in the directory."
    exit 1
  fi

  # Get the base name of the file (without path and extension)
  BASENAME=$(basename "$FILE" .mp4)
  
  # Use ffmpeg to split the file into 299 second segments
  ffmpeg -i "$FILE" -c copy -map 0 -segment_time 299 -f segment -reset_timestamps 1 "${DIRECTORY}/${BASENAME}_part%03d.mp4"
done

echo "Splitting completed."
```

I haven't tested it but I believe it should work

**Comment by DruidCtba** [comment]
Sure buddy mifi, maybe some other time, well, as for the bash, it only works in dreams, forget it, GPT-3.5 still has a lot to learn, maybe in GPT-100 they'll get the model right.

Best regards,

Druid®.

**Comment by mifi** [comment]
Out of curousity I just tested the script, and interestingly it **does** actually work for me. It successfully split a folder full of videos into ~299sec files

**Comment by DruidCtba** [comment]
Good friend @mifi, unfortunately, I don't use LINUX, I use Windows Pro 11 23H2, and when using GPT-4o to convert your BASH LINUX file to BAT WINDOWS, it gave several errors, so if it worked for you, miserably it failed to convert BASH to BAT.

Regards.

Druid®.

**Comment by DruidCtba** [comment]
My last attempt now, yesterday in bed I thought, what if I give a flowchart to the GPT-3.5, will it then perform the requested task? Well, it performed better than just text, although I included not only the flowchart in PDF, but the previous description, it seems it interpreted it better. But what amazed me is that even though I put 299 seconds, which is 4 minutes and 59 seconds, it created the first files with 5 minutes and 4 seconds, and I can't tell why it follows this logic from the beginning of this whole process in C#. Anyway, using 298 seconds it splits the first files into 4 minutes and 58 seconds, could it be a limitation of ffmpeg, to be able to split accurately and not leave any frame to correctly join the files? Anyway, although the world is not perfect, things aren't either, but I insist, if your program LOSSLESSCUT already performs a correct unit operation, well, just put this operation in a loop and you automate the batch process, and as a Delphi programmer I don't see so many problems in this, but it's up to you, the program is yours, even so I appreciate all your attention to me, I like your program, but specifically for what I need, it still doesn't do it in batch. 

Regards, 

Druid®. 

P.S. My struggle in all of this is that a site that converts for free, MP4 from English to Brazilian Portuguese, requires the files to be exactly less than 5 minutes, so I really needed to get these 140 files from a Tableau course, and perform this operation, because I hate reading subtitles, I completely lose focus on the image, and let's face it, in the course itself it says: 80% of what the brain assimilates is image and the other 20% are all other forms of communication, and the site is caption.ai (but I'm having a problem there too, it loses sync between translated audio and video, and in the end about 5 to 9 seconds before the audio ends, a problem that is hard to resolve, as the support from the paid site is very weak).

**Comment by mifi** [comment]
The reason why the resulting files are not exactly 299 seconds, is most likely because of keyframes. Lossless cutting cannot happen outside keyframes, you can read more about it in losslesscut FAQ. this is a limitation in ffmpeg (and video codecs), and you will see the same happen if you try to cut in losslesscut - the output will not be exactly 299 seconds long even if you cut it to 299. Unfortunately there's no easy fix for this, other than re-encoding the video in order to get exact cuts (but that takes a long time).

**Comment by DruidCtba** [comment]
Exato amigo @mifi, acho que ainda lembro do tal GOP do MPEG, deve ser isto, mesmo para AVC e outros codecs, então SIM, eu entendo perfeitamente, mas ai surge uma dúvida: o LOSSLESSCUT está fazendo isto, ele corta onde eu determino 4 minutos e 59 segundos, então isto não seria correto certo? Bem, eu entendo muito pouco sobre isto, entendo tanto quanto BASH do LINUX, ou os comandos do ffmpeg, mas na REAL, fazendo o que fiz acima resolve meu CASO, só espero que o SITE CAPITONS.AI resolva o problema de ASSINCRONIA da DUBLAGEM.

Att.

Druid®.

![LosslessCUT](https://github.com/mifi/lossless-cut/assets/49574472/84faa901-0c37-4813-a0f7-5ef819316ad4)
