### ISSUE TITLE
Cannot properly Smartcut mkv files encoded with Nvidia NVENC HEVC codec

### ISSUE THREAD

**Issue by zwei7** [mifi/lossless-cut#2013]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with a different kind of file to confirm that the problem is related to just this file.
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Steps to reproduce

Smart cut for my HEVC files don't work, I know you said that only some HEVC don't work, but I would like it to work please. Thank you so much for makin this kick ass program!

1. Use MSI GTX 1080 Armor as the video card
2. Record a video using OBS studio 30.1.2

OBS Studio Settings pane settings
Recording Path: Desktop
Recording Format: MKV
Video Encoder: NVIDIA NVENC HEVC
Rate Control: CQP
CQ Level: 20
Keyframe Intereval: 0 s
Preset: P7: Slowest (Best Quality)
Tuning: High Quality
Multipass Mode: Two Passes (Quarter Resolution)
Prodile: main10
Look Ahead: Checkmark on
Psycho Visual Tuning: Checkmark on
GPU: 0
Max B-Frames

OBS Studio Advanced pane :
Renderer: Direct3D 11
Color Format: NV12 (8 bit, 4:2:0, 2 planes)
Color Space: sRGB
Color Range: Full
SDR White Level: 300 nits
HDR Nominal Peak: 1000 nits

3. Place video in Lossless Cut, says it is an unsupported format and it performs a fast conversion
4. Perform a frame accurate cut, I created 7 segments/cuts
5. Play back the cut files

### Expected behavior

Video files should play correctly

### Actual behavior

Used VLC and MPC-BE
Video plays incorrectly, audio is fine
Video moves correctly for 1 second or less, then freezes while audio continues playing
Seeking to different parts of the video does not work either as it still displays frozen video frame, audio seeks fine

### Provide an error report

No error report since Lossless cut thinks it did a perfect job.
File is 19.0 GB

In Mediaplayer Classic Black edition these are the file properties of the 19 GB file:
Video
ID                             : 1
Format                         : HEVC
Format/Info                    : High Efficiency Video Coding
Format profile                 : Main 10@L5.1@Main
Codec ID                       : V_MPEGH/ISO/HEVC
Duration                       : 1 h 37 min
Width                          : 3 840 pixels
Height                         : 2 160 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Constant
Frame rate                     : 60.000 FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Default                        : No
Forced                         : No
Color range                    : Full
Color primaries                : BT.709
colour_primaries_Original      : BT.709
Transfer characteristics       : sRGB/sYCC
transfer_characteristics_Origi : sRGB/sYCC
Matrix coefficients            : BT.709
matrix_coefficients_Original   : BT.709

Audio
ID                             : 2
Format                         : AAC LC
Format/Info                    : Advanced Audio Codec Low Complexity
Codec ID                       : A_AAC-2
Duration                       : 1 h 37 min
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 48.0 kHz
Frame rate                     : 46.875 FPS (1024 SPF)
Compression mode               : Lossy
Title                          : Track1
Default                        : No
Forced                         : No

**Comment by mifi** [comment]
Thanks for your data points. Smart cut is still experimental but it is being tracked in #126
