### ISSUE TITLE
I recommend adding a few common features

### ISSUE THREAD

**Issue by MrDesignLGC** [mifi/lossless-cut#202]
Hello, I am a loyal user of this software. In the long-term use process, I have the following suggestions, hoping to help you improve this software:

1. Pay for more formats, such as AVI and RMVB formats

2. It is suggested to add a particularly important function: supporting frame-by-frame movement of pointers to facilitate accurate editing. Although the current version has this function, it is not very useful, and the key points only move a frame several times.

3. Supporting subtitle editing, because many videos do not have subtitles, after each edit, subtitles need to be edited separately.

**Comment by mifi** [comment]
Closing in favor of #250  #156 #88
