### ISSUE TITLE
Batch extract thumbnails from chapter marks

### ISSUE THREAD

**Issue by JustALooker666** [mifi/lossless-cut#2033]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Hello,

Not sure if this has already been suggested but I'd like to extract thumbnails for every chapter mark.
lossless-cut can split a video by chapter marks and even export chapter timecodes but you can extract only 1 chapter frame to image and/or extract every n-th frame etc which I don't find really useful.

**Comment by mifi** [comment]
Hi. I think you can:
1. bind the keyboard action "Extract frames from selected segments as image files"
2. then press they bound keyboard button
3. then select "Capture exactly one image every nth second", then enter a large number like 999999

**Comment by mifi** [comment]
closing due to lack of response

**Comment by JustALooker666** [comment]
Belated sorry for late reply.
I've tried binding a hotkey and it works... in theory.
In practice, in takes minutes to extract just the first 3 chapter marks to image frames.
Is there a faster way to extract frames using a losslesscut+ffmpeg command?

**Comment by mifi** [comment]
you mean the ffmpeg operation is slow, or it involves a lot of manual labour by you and therefore is slow?

**Comment by JustALooker666** [comment]
No manual labour at all.  It's just ffmpeg that is terribly slow. "Extracting frames 0.0 %"
Also, it seems to me that it just extracts frames with timestamps instead of chapter names.
e.g filename-00.00.00.000.jpg instead of filename-Chapter01.jpg

**Comment by mifi** [comment]
I think in the upcoming version you achieve what you what. In the next version, there's a new feature "markers". these are segments that have no length (no end time set), so they are effectively bookmarks. you create these markers by just adding new segments without setting their end time. then you can use the function "extract frames from selected segments as image files" and it will create 1 screenshot for every marker you have.

you can test this with the latest nightly build if you'd like.

**Comment by JustALooker666** [comment]
In other words, I have to clear all segments (chapters) and then create markers.
If I have to create segments/markers manually, I'd rather manually take 1 screenshot for every segment instead.
Is there an option to convert start time for every segment to marker or import chapters as markers when you add a video?

BTW, even if you label a marker, losslesscut export the frames with timecodes only.

**Comment by mifi** [comment]
If you import chapters when opening a file as segments, you can right click in the segment list, then "Edit segments by expression", then "Convert segments to markers". Then you should be able to extract each chapter (marker) as an image.

**Comment by JustALooker666** [comment]
Big thanks! Extracting markers to images is 1000x faster now.
