### ISSUE TITLE
Direct Jump to a Specific Moment in the Video

### ISSUE THREAD

**Issue by vayo28** [mifi/lossless-cut#2037]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

I would like the application to have a feature that allows users to jump directly to a specific minute in the video by pressing the corresponding numbers on the keyboard. This would significantly improve the efficiency and usability of the application, especially for those who need to edit or review long videos.

Feature Details:

Entering the Desired Minute:
Users can enter the desired minute by pressing the numbers on their keyboard. For example, to go to minute 14, the user simply presses "1" followed by "4".

Automatic Jump:
Upon entering the number, the application will automatically take the user to the corresponding minute of the video. This eliminates the need to manually scroll through the video timeline.

In the basic mode, it would be much faster than searching with the cursor. The advanced mode has something similar, but the numbers 00.00.00.00 are not auto-completed and going through each number is a bit slow.

Thank you for the work and the application, and sorry if something like this has already been suggested.

**Comment by mifi** [comment]
I think something similar already exists:
1. Press <kbd>g</kbd> (seek to timecode)
2. Press <kbd>1</kbd> and <kbd>4</kbd>
3. Press Enter
It will now jump to 14 seconds.

if you want to jump to 14 minutes instead type 14:00

**Comment by vayo28** [comment]
> I think something similar already exists:
> 
> 1. Press g (seek to timecode)
> 2. Press 1 and 4
> 3. Press Enter
> 
> It will now jump to 14 seconds.
> 
> if you want to jump to 14 minutes instead type 14:00

I've seen it, but I mentioned in the post that it takes longer because you have to type 00 : 014 : 00. That is, it doesn't have quick completion, and if you don't put the : and the 00, it doesn't work.

**Comment by mifi** [comment]
which version are you on? simply typing `14` works for me. I don't have to type and `:00`

**Comment by vayo28** [comment]
> which version are you on? simply typing `14` works for me. I don't have to type and `:00`

Yes, I saw, and you don't have to put the 00 that way, but you do need the : 
For example, to enter the time 5:12, the fastest way would be to type 0512 without the :
I know it's a small detail, but when you cut a lot of videos, it makes a difference having to move your hand to the :
Obviously, this is a suggestion. Thanks for the program it's really good 👍
