### ISSUE TITLE
Export project - Duration

### ISSUE THREAD

**Issue by reinierrr** [mifi/lossless-cut#2040]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

MacOS 12

### Steps to reproduce

I'm trying to 'Export project' with timestamps + duration, trying to find it under File > Export Project.

### Expected behavior

I'm expecting to be able to export timestamps and duration for each segment visible in the segments sidebar.

### Actual behavior

I only succeed in exporting the segments Start time and End time timestamps by choosing File > Export Project > Timestamps.

**Comment by mifi** [comment]
Are you saying that you want "start time" & "duration" of each segment in the exported file (instead of segment "start time", "end time")? what do you need this for ?

**Comment by reinierrr** [comment]
Correct, looking back at my report I see now that that was unclear. 

I'm not able to export segments where the first frame of the exported video corresponds with what I'm seeing when I play the segment in the LosslessCut GUI. After reading up on "Keyframe cut mode" I learned that it's not possible to achieve this. When exporting with "Keyframe cut mode" the exported clip starts too early, when exporting with "Keyframe cut mode" disabled it starts with a few black frames. 

After reading up I understand why this is the case (and therefor unavoidable). Am I correct or misunderstanding?

When I manually export the clip through terminal using ffmpeg while I use Start time (HH:MM:SS.MS) for -ss and Duration (HH:MM:SS.MS) for -t I get exactly the segment as I see in the LossletCut GUI. 

So this is what I would need it for: to be able to export those values, write a Bash script to export all these segments and loop through the exported values to export the segments starting with the correct first frame...

**Comment by reinierrr** [comment]
You are right, thanks for your reply and proposed solution
