### ISSUE TITLE
Add commands and entry to losslesscut version ffmpeg

### ISSUE THREAD

**Issue by e4ya** [mifi/lossless-cut#2044]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

If the ffmpeg command is generated using Last ffmpeg commands on the command line
Using the ffmpeg command line installed by yourself on your computer, errors will be reported, including but not limited to
Invalid duration for option ss: '474.95000'
Error opening input files: Invalid argument
The problem centers on timestamps, and native ffmpeg doesn't seem to support timestamps like 474.95000, 0:07:54.950
I have tried to use the losslesscut CLI command-line tool, but repeated attempts have not been successful and I have not found a way to use ffmpeg with losslesscut
The successful workaround was to change my output to a timestamp in cvs format, but that required one more step
The solution I'm thinking of right now is to enter the ffmpeg execution of losslesscut, but I can't, and want to add the ffmpeg method into losslesscut
I'd appreciate it if it worked out

The ffmpeg command I exported is as follows:
ffmpeg-hide_banner -ss '474.95000' -i'm :\Desktop\GBC\01.mkv' -t '3.07000' -avoid_negative_ts make_zero-map '0:0' '-c:0' copy -map '0:1' '-c:1' copy -map '0:2' '-c:2' copy -map '0:3' '-c:3' copy -map '0:4' '-c:4' copy -map '0:5'  '-c:5' copy -map '0:6' '-c:6' copy -map '0:7' '-c:7' copy -map '0:8' '-c:8' copy -map '0:9' '-c:9' copy -map '0:10'  '-c:10' copy -map '0:11' '-c:11' copy -map_metadata 0 -movflags use_metadata_tags -movflags '+faststart' -default_mode  infer_no_subs-ignore_unknown -f matroska-y 'E:\Desktop\GBC\output\01-00.07.54.950-00.07.58.020.mkv'

**Comment by mifi** [comment]
Hi. Not sure exactly what you are asking for. A new feature?

**Comment by e4ya** [comment]
Maybe there is a translation problem, there is a problem with the timestamp of the ffmpeg command generated by losslesscut, the native ffmpeg cannot be executed, and I want to add a way to enter the ffmpeg called by losslesscut

**Comment by mifi** [comment]
you can change the ffmpeg command used by losslesscut to a custom one by going into settings and then selecting "Select custom FFmpeg directory"
