### ISSUE TITLE
Markup cannot be added in languages other than English

### ISSUE THREAD

**Issue by e4ya** [mifi/lossless-cut#2046]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

I don't want to say

### Steps to reproduce

Just use the labelCurrentSegment function to add a language other than English to the fragment
![image](https://github.com/mifi/lossless-cut/assets/87714554/1a775109-d42f-4a10-91c5-75e480230293)

### Expected behavior

Comments in other languages are displayed normally

### Actual behavior

Languages other than English will not be displayed properly; this length will be underlined, and the output will also be underlined
![image](https://github.com/mifi/lossless-cut/assets/87714554/27a7dd79-fdee-4a15-aa94-b19bac34db57)
![image](https://github.com/mifi/lossless-cut/assets/87714554/9ad22bd9-fb4f-4448-8fb0-5eee218ac7fd)

**Comment by mifi** [comment]
<img width="664" alt="Screenshot 2024-06-20 at 23 32 13" src="https://github.com/mifi/lossless-cut/assets/402547/e56ffd5b-550d-457b-9363-023ba352dca3">

turn off "Sanitise file names"

**Comment by e4ya** [comment]
Thank you very much!
