### ISSUE TITLE
Desktop notification for completion

### ISSUE THREAD

**Issue by enoryw** [mifi/lossless-cut#2048]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Feature request: option for desktop notification on completion, e.g. `notify-send` when video finishes processing. Currently, there's only notification shown on the window but when going through videos to process, it would be nice to be notified of completion and not have to check periodically manually.

Also, currently notification on the application window disappears after a brief period of time so when I come back to an already processed video, there's no indication that a video is successfully processed (I assume if there's an error it would also be shown and disappear after a period of time in the same way) so the user can't know if it was successful if the message disappears automatically. The message shouldn't disappear until there's user action.

**Comment by mifi** [comment]
> Feature request: option for desktop notification on completion, e.g. `notify-send` when video finishes processing. Currently, there's only notification shown on the window but when going through videos to process, it would be nice to be notified of completion and not have to check periodically manually.

I believe this is #1510

> Also, currently notification on the application window disappears after a brief period of time so when I come back to an already processed video, there's no indication that a video is successfully processed (I assume if there's an error it would also be shown and disappear after a period of time in the same way) so the user can't know if it was successful if the message disappears automatically. The message shouldn't disappear until there's user action.

I will change it so it doesn't auto disappear

**Comment by mifi** [comment]
closing as duplicate
