### ISSUE TITLE
Add move-to-next-key-frame, move-to-previous-key-frame controls

### ISSUE THREAD

**Issue by mrmsbarnes** [mifi/lossless-cut#205]
Even when choosing 'normal cut' (nc) over 'key frame cut' (kc), lossless-cut still cuts at key frames using blank video for fill in to the normal-cut frame.  These controls would let users choose the best key frame for editing without incurring blank frames.

**Comment by danielsbrewer** [comment]
That would be nice.

**Comment by mifi** [comment]
#41
