### ISSUE TITLE
Prompt file overwrite when extracting audio track

### ISSUE THREAD

**Issue by haminhtrifree** [mifi/lossless-cut#2053]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Right now when you extract an audio track from a video file, it will overwrite the file in the same folder if the file name is the same. The program should prompt the user to overwrite in the same way as the full file Export feature does.

**Comment by mifi** [comment]
I've created a seaprate issue including this suggestion as well as other similar overwrite situations, closing this

**Comment by mifi** [comment]
#2054
