### ISSUE TITLE
Please re-add portable .exe file as release form

### ISSUE THREAD

**Issue by Dragodraki** [mifi/lossless-cut#2055]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

The windows portable form of your app as EXE was simply the best option. I read your note about known issues. Probably you removed the exe due to file size and NSIS bad reputation on VirusTotal for portable apps. But please consider to add them again. The ZIP instead includes so many dependencies the most people neither need to use nor want to see.
The PortableAppZ is no solution since it only extracts loose files again and does not run it like a real portable app does.

**Comment by mifi** [comment]
you mean you want the self-extracting exe back? if so, the reasons for its removal are discussed here: https://github.com/mifi/lossless-cut/issues/1072#issuecomment-1066026323
