### ISSUE TITLE
Go to timecode always moves playhead to beginning of file

### ISSUE THREAD

**Issue by keith555** [mifi/lossless-cut#2057]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 11

### Steps to reproduce

Set _Autoload timecode from file as an offset in the timeline_ on
Set _in timecode show_ to  Frame fractions
Load a file containing timecode
Press G to open the go to timecode window
Enter the timecode of some point in the file

### Expected behavior

The playhead moves to the entered timecode

![losslessCutTimecodeBug](https://github.com/mifi/lossless-cut/assets/1978986/560c1e12-e3f6-4983-abcd-53c2b249a197)

### Actual behavior

The playhead moves to the beginning of the file

**Comment by mifi** [comment]
> Set _in timecode show_ to Frame fractions

does the issue happen regardless of this setting, or *only* when set to "Frame fractions"?

**Comment by mifi** [comment]
are you sure the playhead moves to the beginning of the file? for me if I load a 30 second video and set Tools->Set custom start time offset to `01:00:00.00` and then press <kbd>g</kbd> and enter 01:00:00.00 it seeks to the end of the file.

**Comment by mifi** [comment]
closing due to lack of response
