### ISSUE TITLE
JS expressions function not working for me.

### ISSUE THREAD

**Issue by sportniik** [mifi/lossless-cut#2059]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

I used " segment.duration < 5 "

### Expected behavior

All segments with duration less than 5 sec should be selected (as I understand).

### Actual behavior

Nothing is selected, although I have few segments with less than 5 sec. The JS expression window does not close when I click "OK".

**Comment by mifi** [comment]
this is the nightly build, right? do you see any error message in developer tools javascript console? it works for me on macos but it could be an issue on windows. I saw this error message in an unrelated issue #2070 - and i have a feeling it's related:

> index.html:1 Refused to execute script from 'file:///D:/Downloads/LosslessCut-win-x64%20(1)/resources/app.asar/out/renderer/assets/evalWorker-2659dcda.ts' because its MIME type ('video/vnd.dlna.mpeg-tts') is not executable.

**Comment by mifi** [comment]
I've managed to reproduce the problem on windows and I think I've found the issue https://github.com/vitejs/vite/issues/11823

**Comment by mifi** [comment]
Yes i purposefully made it so that if it's matching **all** segments, then it will not actually select anything, because that would not be very useful.
