### ISSUE TITLE
black glitches ?

### ISSUE THREAD

**Issue by goobiefoof** [mifi/lossless-cut#206]
For few day when i open video in LosslessCut i have some black glitches on screen
Example: https://i.imgur.com/POE3d9i.png  https://i.imgur.com/H19iExD.png   (On the left is video and right same video opened in Loslesscut)
but when cut video they look normal

It's happend few day ago ,before this  i didnt seen any black glitches. 
Even video which i was cutting few days ago was normal now when i open file again in Loslesscut its black glitched...

**Comment by mifi** [comment]
Looks like an issue with your graphics card or some driver issue. try opening in chrome and see if it's the same issue

**Comment by mifi** [comment]
reopen if still an issue
