### ISSUE TITLE
Changing the defult audio track

### ISSUE THREAD

**Issue by vahid9** [mifi/lossless-cut#2066]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

With this nice program, I could not change the default audio track and I had to use **MKVToolNix** to do that. It would be nice to add this simple feature so that we do not need to use two applications, and losslesscut would suffice all needs.
Thanks for your attention.

**Comment by mifi** [comment]
so when you tried to change the default audio track in the tracks panel, it did not get changed? could you explain exactly what you did step by step?

**Comment by vahid9** [comment]
> so when you tried to change the default audio track in the tracks panel, it did not get changed? could you explain exactly what you did step by step?

Hi,
Thank you for your response. Actually, the only way I know of to do that in losslesscut is to remove previous audio track so that new audio track becoes default audio in all players, otherwise it always keep the previous audio track a default as I checked in in different video players. If there is any method that one can change the default audio track inside losslesscut without need to remove other audio tracks, please let me know.

**Comment by mifi** [comment]
> If there is any method that one can change the default audio track inside losslesscut without need to remove other audio tracks, please let me know.

yes, you can set "disposition" to "default" on the "tracks" screen

<img width="107" alt="Screenshot 2024-08-05 at 23 44 33" src="https://github.com/user-attachments/assets/d497f214-7634-4ad5-9efb-a10a37f11500">

**Comment by mifi** [comment]
closing due to lack of respnose

**Comment by dmitri-fm** [comment]
I also had this issue multiple times. It often happens when the video contains more than 2 audio tracks.
@mifi the whole thing with this "disposition" in the tool is very confusing. Starting with the fact that you can select multiple tracks as "default", while only 1 track can have such flag.

> > If there is any method that one can change the default audio track inside losslesscut without need to remove other audio tracks, please let me know.
> 
> yes, you can set "disposition" to "default" on the "tracks" screen
> 
> <img alt="Screenshot 2024-08-05 at 23 44 33" width="107" src="https://private-user-images.githubusercontent.com/402547/355248169-d497f214-7634-4ad5-9efb-a10a37f11500.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDcwMjAsIm5iZiI6MTcyODMwNjcyMCwicGF0aCI6Ii80MDI1NDcvMzU1MjQ4MTY5LWQ0OTdmMjE0LTc2MzQtNGFkNS05ZWZiLWExMGEzN2YxMTUwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QxMzEyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTFkM2UxNTEzNmQwZDlhNzU1MzBiOTFiOGE0YjllODIwNGJkODQwZTkwNDNlOGNmYWMzODEzMDU2OTkyYmVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cLrACC54aWHJZ_TEnEUCiu5r7AYpwqwIdXg9_groqyk">

@mifi from your screen, we see that multiple tracks have "default" status. But is this allowed by video format?

**Comment by mifi** [comment]
i'm not sure, depends on how it's implemented in ffmpeg
