### ISSUE TITLE
ffmpeg error code 3199971767

### ISSUE THREAD

**Issue by networkproblemsolver** [mifi/lossless-cut#2068]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with a different kind of file to confirm that the problem is related to just this file.
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Steps to reproduce

open video.mp4, select last 33% of file to cut, click export twice, get error code 3199971767
![2024-07-09-20-05-06_01](https://github.com/mifi/lossless-cut/assets/7603955/ea227548-9956-4bbe-83d0-7fa10a482e44)

### Expected behavior

All other files export without error

### Actual behavior

Export fails

### Provide an error report

2024-07-09T10:24:37.609Z info: Initializing config store
2024-07-09T10:24:37.824Z info: Waiting for app to become ready
2024-07-09T10:24:37.834Z info: CLI arguments { _: [] }
2024-07-09T10:24:39.233Z info: Current version 3.61.1
2024-07-09T10:24:39.234Z info: Newest version 3.61.1
ffprobe -of json -show_chapters -show_format -show_entries stream -i 'C:\FFOutput\video.mp4' -hide_banner
ffmpeg -hide_banner -loglevel error -ss 0 -noautorotate -i 'C:\FFOutput\video.mp4' -map '0:0' -vcodec mjpeg '-frames:v' 1 -f image2pipe -ffprobe -v error -read_intervals '0%30' -show_packets -select_streams 0 -show_entries 'packet=pts_time,flags' -of json 'C:\FFOutput\video.mp4'
ffmpeg -hide_banner -loglevel error -ss 0 -noautorotate -i 'C:\FFOutput\video.mp4' -map '0:0' -vcodec mjpeg '-frames:v' 1 -f image2pipe -ffmpeg -hide_banner -loglevel error -ss '8695.856536' -noautorotate -i 'C:\FFOutput\video.mp4' -map '0:0' -vcodec mjpeg '-frames:v' 1 -f image2pipe -ffprobe -v error -read_intervals '8665.85653690037%8725.85653690037' -show_packets -select_streams 0 -show_entries 'packet=pts_time,flags' -of json 'C:\FFOutput\video.mp4'
2024-07-09T10:25:27.347Z info: Starting preview process { videoStreamIndex: 0, audioStreamIndex: 1, seekTo: 8695.85653690037 }
2024-07-09T10:25:44.157Z info: Aborting preview process { videoStreamIndex: 0, audioStreamIndex: 1, seekTo: 8695.85653690037 }
ffmpeg -hide_banner -loglevel error -ss '8712.536644' -noautorotate -i 'C:\FFOutput\video.mp4' -map '0:0' -vcodec mjpeg '-frames:v' 1 -f image2pipe -ffmpeg -hide_banner -loglevel error -ss '8712.628133' -noautorotate -i 'C:\FFOutput\video.mp4'
ffmpeg -hide_banner -loglevel error -ss '8712.628133' -noautorotate -i 'C:\FFOutput\video.mp4' -map '0:0' -vcodec mjpeg '-frames:v' 1 -f image2pipe -ffmpeg -hide_banner -loglevel error -ss '8710.167667' -noautorotate -i 'C:\FFOutput\video.mp4'
ffmpeg -hide_banner -loglevel error -ss '8710.167667' -noautorotate -i 'C:\FFOutput\video.mp4' -map '0:0' -vcodec mjpeg '-frames:v' 1 -f image2pipe -ffmpeg -hide_banner -loglevel error -ss '8705.167667' -noautorotate -i 'C:\FFOutput\video.mp4'
Failed to parse ffmpeg progress line: Invalid time from ffmpeg progress -577014:32:22.77

**Comment by rrrcabral** [comment]
me too have this "hide banner" error when open the program, and when open a file. after udate the program. in windows 11.

**Comment by rrrcabral** [comment]
returning to version 3.61.0 corrected the error to me.

**Comment by mifi** [comment]
sounds like a bug in ffmpeg if it exits with code 3199971767. not much I can do in losslesscut.

**Comment by mifi** [comment]
@rrrcabral do you also have exits code 3199971767 in the error message?

**Comment by mifi** [comment]
closing: nothing actionable here
