### ISSUE TITLE
Generates an insane amount of registry keys at installation

### ISSUE THREAD

**Issue by FrisoDB** [mifi/lossless-cut#2069]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 11

### Steps to reproduce

Opening PS as admin I did the following:

PS C:\Users\friso> choco install lossless-cut
which was followed by a very long return message
it seems to be creating an insane amount of hkey/registry keys
this technically works in chocolatey but is very unpleasant.
wingetui cannot even handle this gigantic flood of messages/lines and just botches the installation.

### Expected behavior

a way shorter installation message

### Actual behavior

installing takes a long time with many lines being printed

**Comment by mifi** [comment]
which registry keys are you talking about specifically?
unfortunately i don't publish losslesscut in `choco`, am not affiliated with them, and i don't know how to fix this.

**Comment by Yolakalemowa** [comment]
shit... it's happening to me too :( 

![image](https://github.com/user-attachments/assets/6e3acc18-b35b-4586-9fbd-29752e0e9104)

had to abort it but it did a LOT and I have no idea what.

**Comment by mifi** [comment]
It's probably due to file type associations https://github.com/mifi/lossless-cut/blob/69f600a0c082772fd10018399ac7db1c51e22a3a/package.json#L319

**Comment by Yolakalemowa** [comment]
> It's probably due to file type associations
> 
> https://github.com/mifi/lossless-cut/blob/69f600a0c082772fd10018399ac7db1c51e22a3a/package.json#L319

so it's a problem on my end? or the chocolatey package

**Comment by mifi** [comment]
I dont k ow about chocolatey because i dont publish there. You could try the github download and see if it’s the same

**Comment by FrisoDB** [comment]
The chocolatey script downloads the 7z archive directly from this github repo, but somehow it also adds chocolateyinstall.ps1 .  In this extra script paths and registry keys are arranged, including a big loop over many file extensions/types.
