### ISSUE TITLE
"Unsupported file" Error message since update 3.61.1

### ISSUE THREAD

**Issue by Bastian007** [mifi/lossless-cut#2070]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 11

### Steps to reproduce

Opening any *.mp4 file, independent of used codec, ends with "Unsupported file" message.

### Expected behavior

Opening mp4 files as with earlier versions

### Actual behavior

Mp4 file not opned, error message

### Share log from developer tools

`Version 3.61.1
index.html:1 Refused to execute script from 'file:///D:/Downloads/LosslessCut-win-x64%20(1)/resources/app.asar/out/renderer/assets/evalWorker-2659dcda.ts' because its MIME type ('video/vnd.dlna.mpeg-tts') is not executable.
App.tsx:1900 userOpenFiles
App.tsx:1901 D:\Downloads\testfile.mp4
App.tsx:781 State reset
App.tsx:2016 userOpenFiles Error: Unsupported file: Command failed with exit code 1: D:\Downloads\LosslessCut-win-x64 (2)\ffprobe.exe -of json -show_chapters -show_format -show_entries stream -i D:\Downloads\testfile.mp4 -hide_banner
Das System kann den angegebenen Pfad nicht finden.

    at readFileMeta (file:///D:/Downloads/LosslessCut-win-x64%20(1)/resources/app.asar/out/renderer/assets/index-381ab70a.js:56017:27)
    at async file:///D:/Downloads/LosslessCut-win-x64%20(1)/resources/app.asar/out/renderer/assets/index-381ab70a.js:132906:24
    at async file:///D:/Downloads/LosslessCut-win-x64%20(1)/resources/app.asar/out/renderer/assets/index-381ab70a.js:133003:5
    at async file:///D:/Downloads/LosslessCut-win-x64%20(1)/resources/app.asar/out/renderer/assets/index-381ab70a.js:133319:7
(anonymous) @ App.tsx:2016`

**Comment by mifi** [comment]
> Opening any *.mp4 file, independent of used codec, ends with "Unsupported file" message.

do you open the file with File->Open or drag-drop?

> Opening mp4 files as with earlier versions

does it work with 3.61.0 or [3.59.1](https://github.com/mifi/lossless-cut/releases/tag/v3.59.1) ?

**Comment by mifi** [comment]
also what if you try the latest version now?

**Comment by Bastian007** [comment]
Thanks for coming back!

Just downloaded 3.62:
With all methods (open dialog, drag & drop) I got _Unsupported file_ Error.
Log file:
```
2024-08-08T05:50:03.867Z info: Initializing config store
2024-08-08T05:50:03.955Z info: Waiting for app to become ready
2024-08-08T05:50:03.978Z info: CLI arguments { _: [] }
2024-08-08T05:50:04.218Z error: Failed to check github version connect EACCES 140.82.121.6:443
2024-08-08T05:50:14.639Z info: ffprobe -of json -show_chapters -show_format -show_entries stream -i 'D:\Downloads\videofile.mp4' -hide_banner
```

Same for 3.59.1. 
But then I was suddenly able to change Custom FFmpeg directory back to status "Using built-in ffmpeg" which was somehow before not possible once you have set a custom folder (even if it was the lossless-cut folder.
Not it is working again, I can import mp4 files! :-) Thanks!

**Comment by mifi** [comment]
I will improve the startup check so that it will check for a working ffmpeg and warn if not, thanks.

**Comment by Cranbaerry** [comment]
This issue still persists in 3.64.0

**Comment by mifi** [comment]
can you provide steps how to reproduce as well as information about your system? if it happens only with one file(type), see https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&projects=&template=1-file-issue.yml
