### ISSUE TITLE
Export Naming Strings Issue

### ISSUE THREAD

**Issue by discgrace** [mifi/lossless-cut#2073]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

MacOS 13

### Steps to reproduce

Exporting, trying to name clip files using SEG_NUM_INT (or SEG_NUM_INT+xx)

### Expected behavior

should be naming clips from the number set onwards: SEG_NUM_INT+33 should produce clips titled 34 and onwards

### Actual behavior

"There is an error in the file name template: SEG_NUM_INT is not defined"

**Comment by discgrace** [comment]
@mifi Every time I try to use SEG_NUM_INT (or SEG_NUM_INT+xx), it comes up with "There is an error in the file name template: SEG_NUM_INT is not defined"
I used to use lossless cut a lot and had a naming string that would essentially start my clip names at the number +1 that my last clip ended at. EG, I would export say 20-30 clips from a video, numbered 1-30, and then the next video, I would do another batch of clips, and they would be named from 31 onwards
If I use ${SEG_NUM} the sequence is: 1, 2, 3, etc. if I use ${SEG_NUM-1} the sequence becomes 0, 1, 2, etc. however if I use ${SEG_NUM+1} the sequence becomes 11, 21, 31 etc, which honestly makes no sense to me, because I'd expect it to be 2, 3, 4 etc
please help!

**Comment by discgrace** [comment]
Update* I have gone back to when I last used lossless cut, and it seems the [3.39.0](https://github.com/mifi/lossless-cut/releases/tag/v3.39.0) release, actually had the feature exactly as I mentioned it, where ${SEG_NUM+1} would increase the clip name by 1, so clips 1-3 resulting names would be 2, 3, 4
Just gonna use this release until a solution comes up

**Comment by mifi** [comment]
> it seems the [3.39.0](https://github.com/mifi/lossless-cut/releases/tag/v3.39.0) release, actually had the feature exactly as I mentioned it, where ${SEG_NUM+1}

I believe that was an undocumented feature that was removed in later versions.

Actually this was implemented in #1846 - `SEG_NUM_INT` is now the way to make what you're asking for, however I haven't made a new release which has support for that yet (even though the readme documents it). If you want to try it you can use the latest nightly build until I release a new official version update.
