### ISSUE TITLE
timecode error

### ISSUE THREAD

**Issue by ymjung58** [mifi/lossless-cut#2075]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 11

### Steps to reproduce

<img width="800" alt="error" src="https://github.com/user-attachments/assets/f72952c3-6f82-40e8-872e-e402f519974c">
timecode not read

### Expected behavior

timecode  read

### Actual behavior

metadata error

### Share log from developer tools

<img width="800" alt="error" src="https://github.com/user-attachments/assets/d156af7f-ebe5-4d5a-b827-1a11b88ad9ee">

**Comment by mifi** [comment]
are you sure that DS9_9127 has a timecode? can you more technical info about the file that you don't think has a timecode?

**Comment by ymjung58** [comment]
definitely have it
![DS9_9127](https://github.com/user-attachments/assets/2b32e968-1362-4bae-81f6-aaa20be64f82)

**Comment by ymjung58** [comment]
대용량 첨부 1개 693MB

DS9_9127.MOV 726975994 ~ 2024/09/05
기한이 있는 파일은 30일 보관 / 100회 다운로드 가능



There is definitely

-----Original Message-----

**Comment by mifi** [comment]
alright! so probably there is some limitation in the ffprobe or losslesscut that extracts the timecode. unfortunately it's hard to fix without having a sample file that can reproduce the problem, or more technical info (like an ffprobe output of such a file).

If you can run this command from your command line and give me the output, then that would be helpful:
```bash
ffprobe.exe -of json -show_chapters -show_format -show_entries stream -i c:\path\to\DS9_9127.MOV -hide_banner
```

**Comment by mifi** [comment]
closing due to lack of response
