### ISSUE TITLE
Add an entry for importing subtitle timestamp files to achieve the purpose of automatic batch segmentation of videos

### ISSUE THREAD

**Issue by howsy-520** [mifi/lossless-cut#2076]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Import timestamp files to perform batch segmentation

**Comment by mifi** [comment]
closing due to lack of response
