### ISSUE TITLE
Audio time units

### ISSUE THREAD

**Issue by Haikel-G** [mifi/lossless-cut#2079]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Hey,

Can you add a feature that allows allows to display audio time units which is more precise than the video timecode. Similar to feature on Premiere pro.

Thanks in advance;

![1-1-psd](https://github.com/user-attachments/assets/c7886330-f7a8-4019-9b10-8ce4c072fecf)

**Comment by mifi** [comment]
how does premiere pro show audio time units exactly?

**Comment by Haikel-G** [comment]
This way ! 

![image](https://github.com/user-attachments/assets/e0e47859-f2ec-4c88-9e46-17843c685bb3)

**Comment by mifi** [comment]
hmm, if you in losslesscut settings change "In timecode show" to "Millisecond fractions", it shows moer accurate timestamps, is that what you want? example:

<img width="191" alt="Screenshot 2024-08-06 at 22 23 47" src="https://github.com/user-attachments/assets/7884954e-b00d-4696-bb43-5593e575f45f">

**Comment by mifi** [comment]
if not, why do you need more precise timecode than 1/1000sec? losslesscut cannot cut very accurately anyhow, and it's not possible to seek by less than 1/30 of a sec with the keyboard

**Comment by mifi** [comment]
closing due to no response
