### ISSUE TITLE
Programmatically moving time cursor through HTTP API

### ISSUE THREAD

**Issue by VinayValsaraj-at** [mifi/lossless-cut#2087]
### Description

Hi! I'm looking to programmatically move to a certain timestamp. It seems that this is possible through the keyboard shortcut goToTimecode to open the modal, but still requires application input for the timestamp. There is no way to pass in a timestamp to the keyboard shortcut.

It seems that this has been requested and closed here: https://github.com/mifi/lossless-cut/issues/1204 , but not implemented. 

It feels as though on top of skipping frame/playing/etc., being able to definitively provide a timestamp would supercharge automating LosslessCut programmatically.

Let me know if you need more details.
`e.g. curl -X POST http://localhost:8080/api/shortcuts/goToTimecode --data '{"timestamp": "0:57"}'`

**Comment by mifi** [comment]
now implemented (you can try next nightly). example:

```
curl -X POST http://localhost:8080/api/action/goToTimecodeDirect --json '{"time": "09:11"}'
```
