### ISSUE TITLE
Export/import preferences (with keyboard shortcuts)

### ISSUE THREAD

**Issue by Das2020** [mifi/lossless-cut#2088]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Export/import preferences (with keyboard shortcuts)

**Comment by mifi** [comment]
what do you mean by that exactly?

**Comment by Das2020** [comment]
I mean, after changing keyboard shortcuts, it would be great to have an option to export these shortcuts and import them on another machine. This would save a lot of time and effort compared to manually making the tweaks on each new machine.
Best regards

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mifi** [comment]
oh, right. I don't think I will create a dedicated "export/import settings" feature, but you should be able to relatively easily copy the config file from one machine to the other yourself. The config file is stored in electron's [`appData` folder](https://www.electronjs.org/docs/latest/api/app#appgetpathname), and is called `config.json`. See also https://github.com/mifi/lossless-cut/blob/master/issues.md#faq

**Comment by Das2020** [comment]
Okay, that would work. Hats off to you for this incredible software btw, it's truly the best
________________________________
