### ISSUE TITLE
Version 2.0.18 showing up in 2.4.0

### ISSUE THREAD

**Issue by arkazmi** [mifi/lossless-cut#209]
Hi Mikael, very nice software.
One minor issue: I downloaded the 2.4.0 version (for Linux & windows), but the VERSION file in both says 2.0.18. Is the version file not updated, or main engine is of 2.0.18? Plz verify/rectify. Thanks. Ali

**Comment by mifi** [comment]
Hey. Sorry for the confusion. This is electron version that somehow gets put into a VERSION file. Can you try newest 1.5.0? I think it should not contain this file anymore.
