### ISSUE TITLE
Hello Is there a possibility of a new feature appearing in your later stage? For example, automatic editing, adding variable speed, picture in picture, scanning, stickers, and filters to videos

### ISSUE THREAD

**Issue by hqylss111** [mifi/lossless-cut#2091]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Hello
Is there a possibility of a new feature appearing in your later stage? For example, automatic editing, adding variable speed, picture in picture, scanning, stickers, and filters to videos

**Comment by mifi** [comment]
hi. not sure what you mean by automatic editing, but it sounds like the things you are requesting are lossy operations that cannot be supported losslessly. see https://github.com/mifi/lossless-cut/blob/master/issues.md#faq
