### ISSUE TITLE
Segments Functions ignore deleted parts

### ISSUE THREAD

**Issue by jarrard** [mifi/lossless-cut#2098]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

I couldn't find any request or way to resolve this.

BUT I like to segment my videos up, but sometimes I must remove some parts using the split function.  Unfortunately Losslesscut doesn't allow any way to setup tasks, you must export the trimmed video then reload losslesscut to do the segments function or it will include deleted/cut parts of the video otherwise.

It be nice if there was a way to tell it to hide/ignore cut parts or even compact down already done work (in memory) so you can then see the result and apply new TASKS to the YET TO BE EXPORTED workload.  

I don't know if I've explained well what I mean, basically it be a workflow history and a compact/complete segment tasks function without the export, all done inside losslesscut as a means to do more work on video before export.

Does this make sense what I'm asking?  

If someone has a SIMPLE alternative to lossless-cut tool that does ALL the above then let me know.  I don't want to be doing any of this cut/trim/segment generate workload in a complicated video editing suite.

**Comment by mifi** [comment]
I believe you're asking about non linear editing functionality #976 - I believe Avidemux can do it, although I haven't tested it myself extensively
