### ISSUE TITLE
Clarification on “tiny seek”

### ISSUE THREAD

**Issue by vitorgalvao** [mifi/lossless-cut#21]
`Tiny seek` does not advance/go back frame by frame, but rather a few frames at a time. Is it because since the cuts are done without reencoding, tiny seek jumps between keyframes, ignoring b-frames and the like in the process?

**Comment by mifi** [comment]
`Tiny seek` is just a small time value, because the video player which is being used (HTML5 video) does not support seeking by frames, but instead by time. It will seek 1/60 sec. I have clearified in readme. Is that ok?

**Comment by vitorgalvao** [comment]
Yes, thank you for the clarification.

Would like to see seeking by frames in the future, but I understand why it isn’t possible now.
