### ISSUE TITLE
Random failure to drop the file into a LC on Debian Linux+KDE, AppImage

### ISSUE THREAD

**Issue by slrslr** [mifi/lossless-cut#2107]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

On a Debian 11 + KDE I am seeing randomly not working file drop action into a LC interface. It may not necessarily be the issue of the LC, but my desktop environment (DE).

For example successfully completed export dialogue(window), **sometimes prevents dropping any file (nothing happen)** into a LosslessCut 3.62.0 window. This often happen when i launch a LC and quickly drop a file to it, sometimes maybe I need to wait couple of seconds and sometimes i suspect that i have to drop into certain area of a LC interface).
Pre-export/Settings/Tracks windows worked OK, only post-export one had that "issue". 

It is not reproducible, yet **my drag & drop looks like**: Export in LC, switch to a Dolphin file manager to open exported file, drag next file from a Dolphin file manager, move it to a taskbar LC icon, once LC is focused, move to a LC window and immediately drop it (done quickly with minimum waiting - it can play role) on the "Export finished" confirmation window (or outside of it). **It actually opens a kind of "Save" file dialog and a new session of the LC! On second attempt it asks to insert the file normally and do not open other session.**

**Comment by mifi** [comment]
could it be related to https://github.com/mifi/lossless-cut/discussions/1675#discussioncomment-10303204 ?

**Comment by slrslr** [comment]
> could it be related to...

I am not using Flatpak as that user, but AppImage on Linux Debian with KDE 5.20.5 (framework 5.78.0, qt 5.15.2)

This does not show anything:
![image](https://github.com/user-attachments/assets/114cebbe-5c7c-457e-a240-ceacf0c330e3)

```
$ echo $XDG_SESSION_TYPE
x11
$ env | grep -i wayland
nothing
```

This drag & drop issue is not a big problem, maybe it will befixed once I will move from oldstable to a stable with newer KDE.

**Comment by mifi** [comment]
Yea I haven't noticed this problem so I think it's definitely an OS issue with the drag-drop feature. There are so many different linux flavours and desktop managers, window managers, windowing systems etc so I cannot possibly provide debugging support for all of them, so I have to close this for now.

**Comment by slrslr** [comment]
Some other apps like a [Session messenger](https://getsession.org) desktop app shows a rectangle when the app becomes ready to accept the file dropped on it. The rectangle does not always show up immediately (maybe some Linux xorg lag), but when it shows up (maybe with a couple second delay), then it can mean that there is a higher change the app is ready to accept the dropped file.

**Comment by mifi** [comment]
I will show a visual indicator on the `dragover` event
