### ISSUE TITLE
New version doesn't show the current playback speed percentage anymore

### ISSUE THREAD

**Issue by Rocket3192** [mifi/lossless-cut#2109]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

When using the shortcut to speed up or slow down the video (I personnaly set it to ctrl + => / <= ) the playback speed percentage isn't displayed as it used to be in the previous version

We need to see that value as the video begins to play poorly when you're higher than 1200% (in my case), so in order to put the highest playable speed and still keep it below that personal playable limit we need to know that value :)

### Expected behavior

Playback speed percentage should be displayed as it was before the update

### Actual behavior

Doesn't display the playback speed anymore

**Comment by Rocket3192** [comment]
Okay after watching the settings and testing some of them I figure with the new version you need to turn on "Show informational in-app notification" for the percentage to show up

**Comment by mifi** [comment]
I will change it so that the playback rate will instead always show in the bottom left (next to the speedometer/fps)
