### ISSUE TITLE
Metadata delete does not work in 3.62.0

### ISSUE THREAD

**Issue by Fubaxiusz** [mifi/lossless-cut#2113]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

Get some MKV video with track metadata (anything will do, title or language).
Click on the trash icon to label metadata for deletion.
Export file.
Open new file and see that metadata entry was not removed.

### Expected behavior

Metadata entry labeled for deletion disappears in exported file.
Also metadata entry gets a UI flag indication that it will be deleted.

### Actual behavior

Data entry persists and there's no UI feedback of what's going on.

**Comment by mifi** [comment]
did it work in 3.61?

**Comment by Fubaxiusz** [comment]
No, it did not. I also tested 3.59.1 without success. It's weird because I remember successfully deleting metadata tags at one point but don't remember which version of LC was it.

**Comment by mifi** [comment]
I don't think there ever was any way to remove metadata. It's not trivial to implement because ffmpeg doesn't have any argument to remove a specific metadata. **however** what you can do is to set the metadata to an empty string, and it will effectively reset it to the default value.

**Comment by mifi** [comment]
alright cool! i will close this but can reopen if it turns out that there's something wrong with setting metadata to empty string
