### ISSUE TITLE
Merge cuts with fade transition

### ISSUE THREAD

**Issue by akalankavinda** [mifi/lossless-cut#2114]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

I know that the transitions are lossy operations.
but this logic came into my mind while i was thinking about it.

Can we do the following logic to implement fade transition ?

====PART-A====|--------PART-B--------|====PART-C====

lets consider a scenario of joining PART-A with PART-C and we need to add a transition of 2 seconds

1. In the background, we cut the PART-A into two parts as follows
---> 1) 00:00 to T-1 (T= total length of PART-A in seconds) <--- lets label this as **PART-A1**
---> 2) T-1 to T   <--- lets label this as **LS-A**

2. In the background, we cut the PART-C into two parts as follows
---> 1) 00:00 to 00:01 <--- lets label this as **FS-C**
---> 2) 00:01 to T (T= total length of PART-C in seconds)  <--- lets label this as **PART-C1**

so now we have last second from PART-A (LS-A), and first second from PART-C (FS-C) as two video files

3. we create a fade transition by combining LS-A and FS-C using a **LOSSY** operation and save it as a separate video file and lets labels it as **T-AC**

4. now we can execute the **LOSSLESS** merge operation with combining the above video segments which can hopefully result a fade transition as follows

====PART-A1====|=T-AC=|====PART-C1====

I am not technically aware of the feasibility of this logic, 
just thought it might be a good solution to implement fade transition between clips.

Please let me know what you think about this..
If it is feasible, it will be a very useful feature to everyone using this software.

Finally, thank you very much for implementing this software. 
It has been very helpful to me.

**Comment by mifi** [comment]
Hi. Similar features have been suggested in #1044 #1983 #1944

I agree your suggested implementation sounds like the correct way to do it. It's currently of out of the scope of what LosslessCut supports, but I've added your feature here for reference so will close this issue: #372

**Comment by dmitri-fm** [comment]
@InTheWorks-ca
Your solution worked for me.
But I used loseless-cut for cutting and merging, and ffmpeg only for cross-fading.
When you cut in loseless-cut, you can directly see the duration and frames count in the program.
Also when merging, it will show you if there are compatibility problems between video files.
