### ISSUE TITLE
When merging videos the last 5-10 mins after cut off

### ISSUE THREAD

**Issue by CloudStrife911** [mifi/lossless-cut#2118]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

Have a long MP4 video file approximately 55 mins long, have multiple cuts removing sections in the video, export using merge, and it cuts off the last handful of minutes. 

When exported seperately the last clip shows the full length, but when merged it cuts off the end.

I had this happen with another file that I though was a fluke, but now it has happened with another. 

### Expected behavior

Should have the full length of the ending clip.

### Actual behavior

Missing the last handful of minutes from the last clip.

**Comment by mifi** [comment]
did you try the troubleshooting suggestions? https://github.com/mifi/lossless-cut/blob/master/issues.md#common--known-issues--troubleshooting especially things like disabling all tracks except 1 video + 1 audio

**Comment by CloudStrife911** [comment]
I looked through everything but didn't see anything that fit my exact issue. It is possible I just missed it entirely though.

I was able to work around it by exporting the segments and merging them in another program.

**Comment by mifi** [comment]
Ok, then I'm not sure how to help, because this could happen due to a lot of reasons. if you want me to look into it then you can file a new "Problem with a particular file": https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&projects=&template=1-file-issue.yml
