### ISSUE TITLE
All your assets are down

### ISSUE THREAD

**Issue by Redsandro** [mifi/lossless-cut#212]
I've been trying to download this, but your assets are down.

I keep getting unresolved hostnames on downloads, such as `github-production-release-asset-2e65be.s3.amazonaws.com`

I cannot compile it from source either, because the amazon hosted dependencies are down.

I don't like to download from some random website crawling with ads. Is there a recommended mirror for your compiled binaries?

> # Intermittent DNS Resolution Errors
> We are investigating reports of occasional DNS resolution errors with Route 53 and our external DNS providers. We are actively working towards resolution.
>
> Amazon AWS

**Comment by Redsandro** [comment]
### Update

You're not the only one. I tweeted just in case this one is not on the radar yet.

https://twitter.com/Redsandro/status/1186800774472486912

**Comment by mifi** [comment]
Yea it seems S3 is partly down right now. I will not do anything about this because i trust amazon will be able to fix their errors. and not being able to download losslesscut for a few hours per year is acceptable so i'm not gonna make a mirror.

**Comment by Redsandro** [comment]
Sorry, I meant to close this ticket with my followup comment.
