### ISSUE TITLE
When cutting a video based on scene detection or time specification, the frames at the seams of the video are missing. We would appreciate it if you could improve the process to split these seam frames without any loss.

### ISSUE THREAD

**Issue by hachi515** [mifi/lossless-cut#2121]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 11

### Steps to reproduce

When cutting a video based on scene detection or time specification, the frames at the seams of the video are missing. We would appreciate it if you could improve the process to split these seam frames without any loss.

### Expected behavior

The same as above.

### Actual behavior

The same as above.

**Comment by mifi** [comment]
Hi. Is this different from https://github.com/mifi/lossless-cut/blob/master/issues.md#cutting-times-are-not-accurate ?

**Comment by hachi515** [comment]
Thank you for your message. Yes, I believe the issue described in the article is similar to what we are experiencing. We changed the avoid_negative_ts setting, but it seems that about 5 to 6 frames are still missing. Additionally, some of the exported videos are partially corrupted (we tried changing the output format, but it didn’t resolve the issue).

**Comment by mifi** [comment]
It's a technical limitation of lossless cutting that you cannot always cut at the exact times that you wish to.

If you're getting corrupted output, it could be a bug in ffmpeg that gets triggered with your particular type of file. We can only hope it gets fixed in the future. You're not specifying whether you're doing cut/export to multiple files or cut+merge into one file, but I assume it's the latter. Unfortunately there's not much to do other than trying different output settings, different cut time or waiting for improvements in FFmpeg.
