### ISSUE TITLE
Getting Wrong Start Poing even After Selecting Correct timestamp

### ISSUE THREAD

**Issue by iamLazyCode** [mifi/lossless-cut#2126]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 11

### Steps to reproduce

i selected a start point but even then it starts few seconds before when i actually intend it to start

as in this screenshot u can see that at this time frame i have a different scene `from where i actually wanted to cut` 

![image](https://github.com/user-attachments/assets/daab2681-804a-4c94-914a-4e45ad52dcae)

### Expected behavior

Should start from exact same point not from few seconds before

### Actual behavior

but when i export the video it started from here , which is few seconds before

![image](https://github.com/user-attachments/assets/4e50a8b0-9224-4cf5-8b9a-0c4e878f0907)

**Comment by mifi** [comment]
> - [x]  Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
