### ISSUE TITLE
doesnt run on manjaro

### ISSUE THREAD

**Issue by dddeveloperrr** [mifi/lossless-cut#213]
hello
cant run lossless cut on manjaro 18.1.0
when double click on LosslessCut icon, it does nothing

**Comment by dddeveloperrr** [comment]
Please release a snap version, thanks

**Comment by mifi** [comment]
Can you try newest AppImage 2.5.0?

**Comment by dddeveloperrr** [comment]
I dont use Appimage
Could you please release a snap version? 
It would make it VERY easy to install and use via snap store

**Comment by mifi** [comment]
see 2.6.2, added snap binary

**Comment by dddeveloperrr** [comment]
@mifi Thank you
snap binary is fine, but it would be better to upload it to snap store 
thanks anyway

**Comment by mifi** [comment]
Ok i created an issue for this #218
