### ISSUE TITLE
file lengths are incorrect after cutting. 

### ISSUE THREAD

**Issue by Gevaarlijk** [mifi/lossless-cut#2131]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] This problem happens with all kinds of files that I try. For problem only with a particular file or type, [use this other form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&projects=&template=1-file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

Cut a flac

### Expected behavior

When i cut a flac of 6 minutes into 3 segments of 2 minutes the resulting files should be reported as being 2 minutes long by other software, like media players. 

### Actual behavior

When i cut a flac of 6 minutes into 3 segments of 2 minutes the resulting files are all reported as being 6 minutes long by other software, like mediplayers

**Comment by mifi** [comment]
this is a known issue and a bug in ffmpeg with flac files #1809 - will be fixed in the next version
