### ISSUE TITLE
GPMD tracks should be included automatically when exporting from GoPro cameras

### ISSUE THREAD

**Issue by racer-coder** [mifi/lossless-cut#2134]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Losslesscut currently only copies the video and audio tracks from GoPro MP4 files.  This is called out at:
https://github.com/mifi/lossless-cut/blob/master/issues.md

> When exporting, LosslessCut may be unable to process certain proprietary tracks. For example tmcd, fdsc and gpmd added by GoPro. These can however be losslessly exported to separate files if you want to keep this data for later.

However it turns out that the ffmpeg used by losslesscut actually CAN handle GPMD streams.  I think it still cannot handle TMCD or FDSC.  I have been using it to do exactly this, and it's annoying to have to remember to always add back the GPMD stream.

Can you make it include GPMD by default, or at least have a system option to include it for any new operation?

This is basically reopening #1428 (though I'm looking at exporting segments, not combining; I use mp4-merge to combine programmatically) which is a sub feature of #1438 .

**Comment by mifi** [comment]
how can ffmpeg do this?

**Comment by racer-coder** [comment]
I understand how it can handle GPMD, but then not why it has a problem with TMCD and FDSC.

GPMD is pretty straightforward - there are individual atomic chunks of data, roughly one per second.  Each one can be decoded independently of any other.  The MP4 file format then says where the chunks are and what time period they cover.  So to cut up a file with them it's only necessary to include the chunks for the user time selection.  No knowledge of the encoding of the GPMD is necessary.

I'm not sure why the same approach isn't used for TMCD or FDSC (or if that would even work) but when selecting those tracks I got an error for unhandled codec.

Oh huh: https://patchwork.ffmpeg.org/project/ffmpeg/patch/20170721083019.3174-1-u@pkh.me/#14185
Maybe TMCD is handled just fine, but it's FDSC that isn't handled.
`
@@ -2077,6 +2089,8 @@  static int mov_write_stsd_tag(AVFormatContext *s, AVIOContext *pb, MOVMuxContext
         mov_write_rtp_tag(pb, track);
     else if (track->par->codec_tag == MKTAG('t','m','c','d'))
         mov_write_tmcd_tag(pb, track);
+    else if (track->par->codec_tag == MKTAG('g','p','m','d'))
+        mov_write_gpmd_tag(pb, track);
     return update_size(pb, pos);
 }
`

**Comment by racer-coder** [comment]
FWIW I just tried a test export, and it seems TMCD and FDSC do NOT work with lossless-cut:
video + audio + GPMD = OK
video + audio + TMCD + GPMD = error
video + audio + GPMD + FDSC = error
video + audio + TMCD = error
video + audio + FDSC = error

I'm not sure why, since FFMpeg does have support for TMCD.  I did run across this post; it's a long read, and a bit specific to trying to get GoPro's editing software to recognize the resulting MP4, but maybe it'll have some helpful information?
https://coderunner.io/how-to-compress-gopro-movies-and-keep-metadata/
I don't like how he tries to handle the SOS/FDSC stream though, seems a bit hacky.

**Comment by mifi** [comment]
Ah, ok. So what you'd like is for GPMD track to be enabled by default in losslesscut in the track list?

**Comment by mifi** [comment]
I just tested a gopro file with a `tmcd` track and i can confirm that if i enable the track it fails.

```
[mp4 @ 0x120e07050] Could not find tag for codec none in stream #2, codec not currently supported in container
[out#0/mp4 @ 0x6000039000c0] Could not write header (incorrect codec parameters ?): Invalid argument
```

However if I leave it as disabled, and then export without it, and open the output file, the `tmcd` track is still there! so it seems that it gets copied automatically regardless.
