### ISSUE TITLE
Add 'losslesscut' Topic of repo to improve search visibility on GitHub

### ISSUE THREAD

**Issue by toboil-features** [mifi/lossless-cut#2137]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Title describes the improvement, so yeah.

The current situation :(

| lossless-cut | losslesscut (to improve it here) |
| --- | --- |
| ![lossless-cut](https://github.com/user-attachments/assets/7cd8261e-2014-464c-b56e-46cb35ae04e1) | ![losslesscut](https://github.com/user-attachments/assets/2a653e7c-ece7-4728-89e4-b023ed956e33) |

**Comment by mifi** [comment]
thanks, i have now added the `losslesscut` topic
