### ISSUE TITLE
Addition to 'About program' page

### ISSUE THREAD

**Issue by toboil-features** [mifi/lossless-cut#2142]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

The current layout is fine, but I think I want it to be that specific to avoid headaches later, if they'll occur.

I wish the next strings to be added:
```
Commit: 0499100
Electron 31.6.0
```

![About page](https://github.com/user-attachments/assets/c910c5ca-1766-41e1-89f6-677c9738f25e)

**Comment by mifi** [comment]
not sure what's the best way to include this info. i can agree that electron version is somewhat useful. commit id i'm not so sure because every release has a version tag which can easily be tracked back to commit id here on github

**Comment by toboil-features** [comment]
You mean order? I think it should be like:
```
https://github.com/mifi/lossless-cut
Electron 31.6.0
Commit: 0499100
Copyright © 2016-{Current-Year} Mikael Finstad
```

**Comment by mifi** [comment]
no i mean how to technically fetch the info without too much hacky scripting

**Comment by jnt0rrente** [comment]
if releases are automated with github actions, it is straightforward

**Comment by mifi** [comment]
I think commit should not really be needed, becase you can easily find the commit id by using this URL and the version:

```
https://github.com/mifi/lossless-cut/releases/tag/vx.y.z
```

example: https://github.com/mifi/lossless-cut/releases/tag/v3.62.0

I've added the other info. Can reopen in the future if it becomes a popular demand but i'll close this for now
