### ISSUE TITLE
Option to disable the "Export is done" window or move status to main window

### ISSUE THREAD

**Issue by mprophoto** [mifi/lossless-cut#2146]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

It would be nice to have the option to disable the "Export is done" window or move the status/activitiy to the main window to eliminate the need to close the window manually which is a bit annoying especially when working batches.

Thank you!

**Comment by mifi** [comment]
you can go to settings and disable the "Show informational in-app notifications" setting
