### ISSUE TITLE
adjust volume of audio track

### ISSUE THREAD

**Issue by KevinYork** [mifi/lossless-cut#2149]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Adjust volume of the audio track.    [I realize that is a lossy op; but...]

I am suggesting:
```
Changing the volume of an audio track:
	ffmpeg -i input.mp4 -af "volume=0.5" -c:v copy output.mp4
	ffmpeg -i input.mp3 -af "volume=3dB" -c:v copy output.mp3
```

**Comment by mifi** [comment]
> - [x]  Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists

#372
