### ISSUE TITLE
Playback rate indicator on main window

### ISSUE THREAD

**Issue by PhilippeBruno** [mifi/lossless-cut#2153]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

When playback rate is different from 100%, it would be nice to have an indicator on the main window displaying the rate.

**Comment by mifi** [comment]
already fixed in 016f4ce1b79cb10d90bfb39dc5af1db15ebf88b4 #2109
