### ISSUE TITLE
Make 'Segments to chapters' only export the segments

### ISSUE THREAD

**Issue by andrewdbond** [mifi/lossless-cut#2157]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Goal: Create segments in a video and export only those segments as chapters.

However, at present it appears the app exports the entire video, including parts of the video not included in any segment, and adds chapter markers to the uncut video. Personally this functionality was unexpected for me and I was unclear if this was intended behavior or a bug, but in searching github I found the text "[Segments to chapters mode is active, this means that the file will not be cut. Instead chapters will be created from the segments.](https://github.com/mifi/lossless-cut/blob/f3d2a93db320206691065c4745bc9301b17027d4/src/renderer/src/components/ExportConfirm.tsx#L245)" that appears as an alert tooltip on the export screen.

My proposal is to change the (default?) behavior so that only segments are exported, like the default 'Export mode', with chapter markers then applied to those segments. If someone wanted the whole video exported, they could add segment(s) for the whole video.

(If the existing functionality is preferred to be kept, I guess it could be clearer if the timeline no longer showed the trash can icon over non-segment areas, as those areas aren't actually trashed.)

I guess the workaround to export only the segments as chapters would be to first trim/export the originial video, then open the trimmed video and add the chapter segments and re-export, although my preference would be my proposal above. 😄

Regardless, thank you so much for your work on this app!

**Comment by mifi** [comment]
hi

I think this change would complicate the code a lot because it would no longer be a pure "export with chapters", but it will be a mixture of the two, so I don't think it's worth implementing. Your workaround seems to be the way to do it.

> (If the existing functionality is preferred to be kept, I guess it could be clearer if the timeline no longer showed the trash can icon over non-segment areas, as those areas aren't actually trashed.)

agree. will remove those trash icons when in that mode. thanks!

**Comment by andrewdbond** [comment]
I think the current text is "Segments to chapters" - if the existing functionality is kept, perhaps it should be renamed to "Non-segments + segments to chapters" or similar?

**Comment by mifi** [comment]
I think that name will be a bit too long

**Comment by cagrey** [comment]
...but it USED to work the desired way (export ONLY the selected segments) for ever - at least to my previous downloaded version (~3.59.2 I think, maybe 3.56.n), without that orange "!". Now I am sorry that I've deleted that version after updating to 3.62, without checking the results first :(
Could you please go back to that (only selected segments)? It doesn't make much sense to me either to
1. export all the segments, selected or not (what I did NOT select is NOT a segment to me); or
2. squash all the selected segments into one after export.
I (used to) make segments out of my various videos, and then use them in new combinations - always worked well until recently :(

**Comment by mifi** [comment]
Hi @cagrey, I'm not sure exactly what you mean. do you mean that in version 3.95.2 or 3.56.n, when choosing "Segments to chapters" mode, losslesscut would first cut out all the segments, then merge them into one file, and then export the resulting file with chapters (from the segments)? I believe "Segments to chapters" has never worked like that, and always worked how it works right now. If that's not true, could you find the exact version where it worked differently [from here](https://github.com/mifi/lossless-cut/releases) and then show a screencast of how you used it or explain in a detailed way?

**Comment by cagrey** [comment]
Hmmm.... looks like I (and perhaps andrewdbond above too) confused myself while changing to a new version + also switching to the "Segments to chapters" mode instead of "Merge cuts". "Merge cuts" does what I (and andrewdbond?) want (in both new and old versions, 3.56.0 in my case), deleting the non-selected parts and merging the selected ones as chapters. Perhaps the wording is a bit confusing...
Sorry for wasting your time :(
