### ISSUE TITLE
"Capture every single frame as an image" progress percentage broken.

### ISSUE THREAD

**Issue by Whirblewind** [mifi/lossless-cut#2161]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] This problem happens with all kinds of files that I try. For problem only with a particular file or type, [use this other form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&projects=&template=1-file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

3.62.0
Open video file (I drag and drop) (mp4, mkv, webms, multiple codecs featured including avc and vp9; your standard youtube containers/codecs)
Right click segment
Extract frames as image files
Capture every single frame as an image
Confirm prompt about thousands of images

### Expected behavior

The percentage beneath the text "Extracting frames..." should increment small amounts coinciding with a division of frames extracted ending at completion with 100%.

### Actual behavior

Whatever measurement the percentage progress is actually using seems broken so it increments at what seems like a progressively larger number instead of the fraction of a percent it's supposed to, so a video of 3:30~ length and 5k~ frames can end up well over 20000% by the end. 
![losslesscut frames](https://github.com/user-attachments/assets/dd622f4c-6c28-4157-8397-eac6b7a77499)

Before this week, I had been using 3.54.0, which I believe is only a month or two off from when the feature was added last year, and in that version the percentage works just fine. Doesn't narrow it down for you much, but hopefully it can still breadcrumb you to the problem in some way.

Conventionally cutting a segment and exporting, or exporting an untouched file to a different container are two other use cases I've done recently and the progress seems fine there.

**Comment by mifi** [comment]
I tried the same but for me the progress seems normal. Does it happen with all kinds of files? Is it possible to share a file that reproduces the problem?
