### ISSUE TITLE
Can you add the number of video loops or set the total duration of the video in the place where the video is merged in the tool? 能不能在合并的地方添加循环次数或者设置总时长

### ISSUE THREAD

**Issue by Brzeskot** [mifi/lossless-cut#2162]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

能不能在工具处 合并视频的地方添加视频循环次数或者设置视频总时长

**Comment by mifi** [comment]
#976 976
