### ISSUE TITLE
[Feature request/Bug report] Improve exporting progress percentage

### ISSUE THREAD

**Issue by dmitri-fm** [mifi/lossless-cut#2163]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [x] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

The progress goes well until the end (98% or 99% depending on file size) and then it always stuck for some time (also depends on file size I guess).

Example: 2 mins from 0% to 98%, and then another 2 mins to reach 100%.

Anything can be done about this?

**Comment by mifi** [comment]
Is it export single segment? Does it happrn with all kinds of files? If not, is there anything characterizing the files it happens with?

**Comment by vergol** [comment]
It happens when exporting 1 hour video with one more audio track added (mp3). So original video/audio was not changed.
I only noticed that it takes less time when the file is smaller.

**Comment by mifi** [comment]
exactly how do you reproduce the problem? See https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&projects=&template=2-bug.yml
