### ISSUE TITLE
Please don't drop Windows 32-bit support

### ISSUE THREAD

**Issue by txr660** [mifi/lossless-cut#217]
Please continue building the 32-bit package for Windows .
I started using Lossless-cut only last year and I have been using it a lot since .
Thanks

**Comment by mifi** [comment]
im not quite sure how to easily do that with the newest build system based on electron builder. Need to include the correct ffmpeg binary depending on whether build is 32/64bit. if someone has some easy solution please shout out.

**Comment by mifi** [comment]
Now we can easily add 32 bit win support again, but I'm not sure how many people want that

**Comment by mifi** [comment]
I tried to implement 32 bit in the branch

It seems to work, and it generates two builds. And for ffprobe it includes the right 64/32 bit version, but ffmpeg-static which now downloads only the version for the current arch only, it won't let me select which one to be included in the electron-builder.
See https://github.com/eugeneware/ffmpeg-static/issues/35

I'm thinking maybe creating a new npm module that works like ffmpeg-static used to work before.

**Comment by mifi** [comment]
I'm going to close this. Unfortunately I will probably never prioritize this
