### ISSUE TITLE
Don't copy chapters into split export files

### ISSUE THREAD

**Issue by yuchenshi** [mifi/lossless-cut#2176]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

I like how Lossless-Cut imports embedded MP4 chapters from the source file automatically, but when I try to export the segments as individual files, I'm surprised to find out that chapter markers are copied into each file.

This feature request is about *not* copying the chapter markers (or at least having an option for skipping those) and my rationale follows.

Due to the inexact nature of cutting, the resulting chapters are quite misleading in most of the cases. For example, when the source file contains Chapter 1-5, the resulting file `chapter4.mp4` will usually end up having:

1. A few seconds at the start of the video, marked as "Chapter 3"
2. The actual intended contents of Chapter 4, marked as such
3. [Sometimes] 1-2 seconds at the end of the video, marked as "Chapter 5"

I'm not asking to remove the extra seconds and I understand that they're due to key frames seeking. The extra seconds themselves don't bother me, but I find the 1-2 bogus chapters annoying in video players. For example, they show up in VLC timeline and enables chapter seeking. (If one were to modify the segment start/end, the embedded chapters may be even more confusing since they are stuck to the original video.)

----

Diving into the implementation, I did a bit research and found that adding `-map_chapters -1` to the ffmpeg command line worked just fine and removed the chapters for me. I believe the fact that chapters are copied in the first place is due to `-map_metadata` implying chapters as well, so appending `-map_chapters -1` that negates that. This of course only matters for split imports and "Chapters only" mode shouldn't be changed.

The problem is that I still need to run Lossless Cut export and wait for all the segments to be written, and then go to the menu logs, copy the commands and add the flag to them one by one, and then finally run those again to overwrite the files. I've searched the menus, options, and issue list but haven't found a way to add custom flags to ffmpeg. The only thing I can think of is to use the Developer Tools to modify the command line on a break point, which quickly becomes tedious for each segment. (I've also searched the issues for `map_chapters` but couldn't find any similar issue. I've also searched for `map_metadata` and I understand it's needed for copying over other metadata and I think copying chapters is just probably an unintended consequence. I believe I've done my due diligence but let me know if I've missed anything.)

Let me know if this sounds reasonable and I'm happy to send PRs and/or dive into more discussions.

**Comment by yuchenshi** [comment]
I also just want to say thank you so much for this project. Lossless Cut has helped me countless times with my video editing and the project is still amazing despite this small issue. I've sponsored but it's not a bounty for this issue or anything like that -- no pressure at all.

**Comment by mifi** [comment]
i've added a button to disable chapters output, thanks!

**Comment by mifi** [comment]
under "Export options". you can enable this dialog in the bottom right:
<img width="26" alt="Screenshot 2024-10-20 at 20 33 33" src="https://github.com/user-attachments/assets/f302edf8-57af-47a7-a28f-d536201950e0">

**Comment by TarkusLV** [comment]
Yes, I have that button enabled, but I see no option to disable chapters on export.

**Comment by mifi** [comment]
are you running v3.63.0? it's called "preserve chapters"

<img width="669" alt="Screenshot 2024-10-20 at 21 34 24" src="https://github.com/user-attachments/assets/00fe4022-aced-4a77-9885-c8b1d0a7df81">

**Comment by TarkusLV** [comment]
Yeah, I don't have that option.
![Screenshot (20)](https://github.com/user-attachments/assets/42d4e15a-9bfc-4cd0-a8fd-b6cfa77b8f61)

**Comment by mifi** [comment]
oops that's a bug. seems I only enabled that option for MOV/MP4 files, will fix. as a workaround you can open a mov/mp4 file, then change the setting, then open your file again

**Comment by TarkusLV** [comment]
Thank you!
