### ISSUE TITLE
timestamp obscures timeline

### ISSUE THREAD

**Issue by exekutive** [mifi/lossless-cut#2177]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

the playback cursor timestamp obscures the timeline. Especially annoying that you can't see segment labels. A better place for it might be in the lower toolbar.

**Comment by mifi** [comment]
I think what I can do is to make it almost completely invisible when hovering the mouse over it

**Comment by exekutive** [comment]
but then you won't see the timestamp when legitimately seeking the position directly under the timestamp. I think it needs to be somewhere else.

**Comment by mifi** [comment]
you can still easily:

1. seek using keyboard
2. seek by dragging the mouse, but move the mouse out of the way of the timestamp (vertically) to make it appear again

**Comment by exekutive** [comment]
1. kb isn't as fast as mouse
2. no. just no. I want to see the entire timeline all of the time, not just when I put my mouse there. Superimposing the timestamp there just looks cluttered , out of place, and completely unnecessary. There is enough room in the UI for its own place. It belongs in the toolbar just like the in/out times. Right below the play button would be ideal.

**Comment by mifi** [comment]
the problem is that there are also many other icons down there so it's not obvious how to place it
placing it off-center would look weird:

<img width="725" alt="Screenshot 2024-10-06 at 23 42 54" src="https://github.com/user-attachments/assets/3df46000-b583-4e45-af50-01a75b9f6d0d">

**Comment by exekutive** [comment]
absolutely nothing wrong with this
<img width="725" alt="373981981-3df46000-b583-4e45-af50-01a75b9f6d0d" src="https://github.com/user-attachments/assets/914bc068-e868-4ceb-a161-1fac7dfd6e38">


Usually my toolbar is wide open like this anyway


<img width="1362" alt="Screenshot 2024-10-13 at 16 40 03" src="https://github.com/user-attachments/assets/0c1e7486-7437-46d9-9481-5ab921c12f1a">

**Comment by mifi** [comment]
might look into it, but it's not obvious to me how to center a single item in a css flexbox, while having the rest flow to the right/left

**Comment by exekutive** [comment]
It doesn't have to be centered. Left justified is OK. integrated into the control bar is OK too.
