### ISSUE TITLE
New input automatically overwrites the previous number(timeline)

### ISSUE THREAD

**Issue by UserKKy** [mifi/lossless-cut#2178]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

https://github.com/user-attachments/assets/bfdec730-d1d0-45c8-95ae-bc0d853738ae

There's no need to delete the previous number; new inputs overwrite it automatically

please update

**Comment by mifi** [comment]
duplicate #1694
