### ISSUE TITLE
Convert between subtitle format

### ISSUE THREAD

**Issue by hisel-sabermetrics** [mifi/lossless-cut#2179]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Please add auto conversion between subtitle format.
It very annoy having to use a text editor whenever I have an .srt file instead of .vtt file for a webm video.

**Comment by mifi** [comment]
Not sure exactly what you want? You want a menu option like this:
- choose input file (.srt/.vtt)
- choose output format (.vtt/.srt)
- choose output file path
- subtitle will be converted

If so, then I think there are probably other tools that already let you do this?

**Comment by mifi** [comment]
can you provide clear concise steps to reproduce the error?
