### ISSUE TITLE
Publish to new services

### ISSUE THREAD

**Issue by mifi** [mifi/lossless-cut#218]
- [x] Snap store
- [ ] Bintray
- [ ] Flatpak (not supported by Electron natively, http://docs.flatpak.org/en/latest/electron.html)
- [x] Sign for Mac OS (notarize) 
- [x] Mac App Store (https://github.com/electron/electron/issues/20027)
- [x] Windows store

**Comment by o-l-a-v** [comment]
For Microaoft Store, finance EV cert by either:

* Foundraise EV cert before publishing. If enough interest and money = Publish.
* Make app from MS store paid/ not free.

**Comment by mifi** [comment]
Actually when looking now, I cannot find any information anymore about EV certificates being required. I find only a [one time fee of 19$](https://docs.microsoft.com/en-us/windows/uwp/publish/account-types-locations-and-fees), which is something I'm ok with.

However it seems to be not so easy to set up something like this because it seems that it needs a lot of manual steps: https://medium.com/@sangamrajpara/publishing-electron-app-to-windows-store-3cadeed26a32
I'm currently using Mac and I want to run this on Github Actions (CI) automatically on git tag. Because manually booting up a windows and going through a lot of manual release steps for every release is something that will cause me to not bother releasing new versions to window store in the future. Currently releasing happens automatically on every git tag.

I'm also a bit scared that the bundled ffmpeg.exe might cause issues with their AppX format (just a hunch.)

If anyone is interested in trying to help setting this up automatically, I'm happy to assist.

**Comment by mifi** [comment]
It seems that code signing requires either an EV or Code Signing certificate. Both which cost at least 200$ usd / year:

- https://www.electron.build/code-signing
- https://www.electronjs.org/docs/tutorial/windows-store-guide

**Comment by reitzig** [comment]
What's preventing publishing on snapcraft.io? Do you need assistance?

**Comment by mifi** [comment]
I added a bounty for the microsoft signing here: https://issuehunt.io/r/mifi/lossless-cut/issues/240

**Comment by mifi** [comment]
@reitzig Can you test if it's working?

[![Get it from the Snap Store](https://snapcraft.io/static/images/badges/en/snap-store-white.svg)](https://snapcraft.io/losslesscut)

**Comment by mifi** [comment]
After a lot of hassle I have now manged to publish to Mac App Store and Microsoft Store.

**Comment by reitzig** [comment]
@mifi Cool, thanks! I was able to install lossless with `sudo snap install --edge losslesscut` and the app started.

`edge` is for something like nightly builds, so it's the most frequent and unreliable kind of release. If you want to publish "real" releases, those should go to `stable`. See also: https://snapcraft.io/docs/channels#heading--risk-levels

**Comment by mifi** [comment]
Ok I promoted to stable

**Comment by ThracianKnight1907** [comment]
Hello! Has Lossless Cut been published on flathub officially? I see a package [listed](https://flathub.org/apps/details/no.mifi.losslesscut) and it appears up to date

**Comment by FMuro** [comment]
Hey, thanks for this piece of software! Really useful to avoid using ffmpeg in the command line. The Ubuntu snap package reports a newer version. I check it's in the edge channel. Is anything preventing you from pushing it to stable? If you need testing, or whatever, please let me know how I can help.

**Comment by mifi** [comment]
@ThracianKnight1907 it's not publishedd by me officially, but @muelli has been working on the integration, and I have been assisting him.
See here for his source code:
https://github.com/flathub/no.mifi.losslesscut

**Comment by mifi** [comment]
@FMuro nothing preventing me, it's just that it is another manual step for me, and I don't really test the app on Linux before I release. I bumped it now. If anyone wants to assist the testing and bumping to stable, I'm happy to invite a collaborator to do this.

I bumped now to 3.22.3

**Comment by edmundlaugasson** [comment]
Looks like [Flatpak version of LosslessCut](https://flathub.org/apps/details/no.mifi.losslesscut) is outdated :(
Also I ask kindly to add Flatpak button with appropriate link to [download section at main page](https://github.com/mifi/lossless-cut#download).

**Comment by muelli** [comment]
can you file a bug [here](https://github.com/flathub/no.mifi.losslesscut/), please? :)
I remember there were some issues around downloads that were required at install-time. Maybe these issues have disappeared now and I can give it a spin again. In any case, the other repo is the better place to track this issue.

**Comment by edmundlaugasson** [comment]
> can you file a bug [here](https://github.com/flathub/no.mifi.losslesscut/), please? :)

[Done.](https://github.com/flathub/no.mifi.losslesscut/issues/7)

> I remember there were some issues around downloads that were required at install-time. Maybe these issues have disappeared now and I can give it a spin again. In any case, the other repo is the better place to track this issue.

This has to be tested. Using currently AppImage version, which works fine. As soon as Flatpak will be updated, plan to install it. Using Linux Mint different versions.

**Comment by mifi** [comment]
Closing as I'm not going to work on this, but create a new issue if anyone want to work on a publish to a new service
