### ISSUE TITLE
Block the Alt key from activating the software's menu bar

### ISSUE THREAD

**Issue by ponyscma** [mifi/lossless-cut#2180]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Alt+I and Alt+O are the most commonly used shortcuts, but frequently pressing the ALT key often mistakenly activates the menu bar, and this happens quite often.

![3116943](https://github.com/user-attachments/assets/a38d22b7-af9a-4c74-b4fb-9b620c5b3cf6)

**Comment by mifi** [comment]
a bit tricky to do in electron:

**Comment by ponyscma** [comment]
> 在电子中有点棘手： [electron/electron#34211](https://github.com/electron/electron/issues/34211)

I have changed the Alt+Left and Alt+Right key combinations to separate Left and Right keys.

**Comment by mifi** [comment]
In the next version I will prevent <kbd>alt</kbd> default action when the user has bound alt in any of the LosslessCut keybindings

**Comment by Simon818** [comment]
As a keyboard-only user who has bound some keyboard shortcuts to alt+letter combinations, i'm now locked out of the menu bar. Is there an alternative keystroke?

**Comment by mifi** [comment]
I think you can unbind the alt key from all keyboars shortcuts and it will restore default behavior

**Comment by Simon818** [comment]
That requires I actually get into the keyboard shortcuts page, which requires opening up the menu.

**Comment by mifi** [comment]
No, you should be able to use the keyboard shortcut to open the keyboard shortcuts page

**Comment by mifi** [comment]
Or you can edit the config file using a text editor and remove all «alt» keyboard shortcuts

**Comment by Simon818** [comment]
Ahh, good suggestions--I had forgotten there was a shortcut to open shortcuts. Thanks.

I do think this change is a really big accessibility issue though. I use A LOT of software and have never in my life seen any of it block the alt key from opening the menu bar. For an app that has excellent keyboard shortcut support, this seems like an odd decision. I can unbind every key that uses alt, but there are only so many modifier keys and that just means I have to get creative when assigning new shortcuts. It's also a really high barrier to entry for any screen reader user, as there are several alt-key shortcuts by default. I'd like to be able to recommend this app to my friends without disclaimering it with "You have to use this command to open keyboard shortcuts and delete al the ones with "alt" or you won't be able to accses the menu." The alt key doesn't open the menu bar unless you press it and let go of it, and if you do that by accident, you just escape out of the menu and carry on with your day.

**Comment by mifi** [comment]
I see your concern. Maybe we should by default not bind any keys to Alt, so that the alt key works as a menu activator. Then those people who don’t need the alt menu activator can bind the alt key to to whichever losslesscut keyboard shortcuts they want

**Comment by mifi** [comment]
Unfortunately I don't know the best way to implement that.
The <kbd>alt</kbd> key `keydown` event is being intercepted and prevented here: https://github.com/mifi/lossless-cut/commit/898eefcadcca3b771a679d0275377804dfa0449b#diff-a9d1f8b421da343d1839cd3d03a144a079ed3863384f0fab015c96f7898a28abR2331
Maybe it could be solved by using `keyup` instead and check if any action was triggered and prevent it only in that case. But I'm on macOS which doesn't seem to have this alt key behavior, so it's not trivial for me to test this.

**Comment by mifi** [comment]
I've now tried to implement it correctly but it's untested because i don't have a windows computer here now. If someone wants to test it, then please do with the latest nightly build: https://mifi.no/llc/nightly/
