### ISSUE TITLE
Cut segment from video is longer than it's supposed to be

### ISSUE THREAD

**Issue by Tomahawk27x** [mifi/lossless-cut#2184]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] This problem happens with all kinds of files that I try. For problem only with a particular file or type, [use this other form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&projects=&template=1-file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

Just trying to cut the video no matter from where can cause this issue. This video is recorded with OBS Replay Buffer, doesn't happen with Shadowplay recordings/replays. I suck at explaining but I hope the video below clears it up. This is done with the very latest version of Lossless Cut.

https://github.com/user-attachments/assets/747bf5c8-bd43-4269-bb50-cb75c7d3f215

### Expected behavior

I expect for the video to have the same duration, the same segment as the one in the cutter.

### Actual behavior

The part that was cut is supposedly longer making it not cut how I want it to be.
![image](https://github.com/user-attachments/assets/0e95d599-58f2-4ffa-876e-ff448e460c1d)
![image](https://github.com/user-attachments/assets/f0107d05-8a37-4ae4-ab08-f2af8b5c3196) the result after exporting

**Comment by Tomahawk27x** [comment]
![image](https://github.com/user-attachments/assets/8026148c-2122-4254-b471-615b175106e6)
If it helps with anything, these are my OBS settings that I used for the replay.

**Comment by Tomahawk27x** [comment]
Another thing with cutting OBS videos, seeking is laggier (doesn't flick, but lags), with shadowplay recordings it's more convenient cause it's easier to seek to a specific part from where you can cut a video.

**Comment by mifi** [comment]
> - [x]  Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)

https://github.com/mifi/lossless-cut/blob/master/issues.md#cutting-times-are-not-accurate

**Comment by Tomahawk27x** [comment]
Fuck, my mistake.
