### ISSUE TITLE
Additional keyboard navigation feature request: larger jump on up and down keys

### ISSUE THREAD

**Issue by danielsbrewer** [mifi/lossless-cut#219]
Thanks for a great program. I use it to cut adverts out of TV that I have recorded.  I've come from MPEGstreamclip which doesn't seem to work with HD mpeg4s. One thing I miss is the ability to make a larger jump using the up and down arrow keys. I'm not sure on the time of the jump but I would suggest 10 seconds.

**Comment by mifi** [comment]
See #254
