### ISSUE TITLE
Linux: chrome-sandbox needs to be owned by root and mode 4755

### ISSUE THREAD

**Issue by darealshinji** [mifi/lossless-cut#2192]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [x] This problem happens with all kinds of files that I try. For problem only with a particular file or type, [use this other form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&projects=&template=1-file-issue.yml)

### Operating System

Linux

### Steps to reproduce

I've tried to run the release version AppImage giving me this error message:
```
$ ./LosslessCut-linux-x86_64.AppImage 
[23654:1011/135636.786306:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_Losslel83AVZ/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
```

Same with the nightly build:
```
$ ./losslesscut 
[25492:1011/140520.953106:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/djcj/Downloads/Linux/dist/LosslessCut-linux-x64/chrome-sandbox is owned by root and has mode 4755.
```

### Expected behavior

I've expected the program to start.

### Actual behavior

Program doesn't start.

Setting the correct bits makes the program start as expected:
``` sh
chown root chrome-sandbox
chmod 04755 chrome-sandbox
```

Or I start the AppImage with `--no-sandbox`, that works too.

### Share log from developer tools

n/a

**Comment by mifi** [comment]
> - [x]  Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

https://github.com/search?q=repo%3Amifi%2Flossless-cut+chrome-sandbox+is+owned+by+root+and+has+mode&type=issues

**Comment by darealshinji** [comment]
The AppImage uses an AppRun script to launch the losslesscut binary. The option `--no-sandbox` could be added to the shell script.

**Comment by mifi** [comment]
Unfortunately I don't know how to do that
