### ISSUE TITLE
Speed-up or Slow-down buttons do not trigger informational pop-up

### ISSUE THREAD

**Issue by padiix** [mifi/lossless-cut#2193]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] This problem happens with all kinds of files that I try. For problem only with a particular file or type, [use this other form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&projects=&template=1-file-issue.yml)

### Operating System

Windows 11

### Steps to reproduce

1. Update from [3.62.0](https://github.com/mifi/lossless-cut/releases/tag/v3.62.0) to [3.63.0](https://github.com/mifi/lossless-cut/releases/tag/v3.63.0)
2. Open up a video file
3. Speed-up/Slow-down the video using the `J` or `L` keys

### Expected behavior

There should be an informational pop-up about the amount of speed-up or slow-down

### Actual behavior

There is no pop-up.
I kind of got used to it...

**Comment by mifi** [comment]
it is now shown in the lower left:
<img width="51" alt="Screenshot 2024-10-12 at 22 16 02" src="https://github.com/user-attachments/assets/5f415084-5b7e-4839-9dfd-0bf27d82aab0">
