### ISSUE TITLE
Mac OS X (other OS-es not tried yet) "not supported" when playing a file with the # in filename

### ISSUE THREAD

**Issue by jpluimers** [mifi/lossless-cut#22]
When a video has a `#` in the filename, you get a "ERR_FILE_NOT_FOUND" error with a console log entry like this:

```
/Users/jeroenp/tmp/1.0004-0014-Nathans%20Popquiz%20-%20Aflevering%20#69-4B7jYjVBPrw.mp4:1 GET file:///Users/jeroenp/tmp/1.0004-0014-Nathans%20Popquiz%20-%20Aflevering%20 net::ERR_FILE_NOT_FOUND
```

When playing you then get this error message:

```
This video format is not supported, maybe you can re-format the file first using ffmpeg
```

After renaming `1.0004-0014-Nathans Popquiz - Aflevering #69-4B7jYjVBPrw.mp4` to `1.0004-0014-Nathans Popquiz - Aflevering 69-4B7jYjVBPrw.mp4` it loads fine.

Two things:

1. Please correct the error message
2. If possible make loading files having `#` in them possible

My guess is that 1. is easy, but 2. might be difficult if it's not a URL encoding issue.

**Comment by mifi** [comment]
See #8
