### ISSUE TITLE
In Windows 10, in version 2.6.2. "delete source file" never finishes, get stuck at 99%

### ISSUE THREAD

**Issue by ajpeters19** [mifi/lossless-cut#220]
If you have an issue with cutting a particular file, or an unexpected bug or crash, please open developer tools after starting LosslessCut and before doing the failing operation. Then share the output from the javascript console.

If you have an issue cutting a particular file, please also share the file, if possible. Also please try to cut it with the ffmpeg command line directly.

How to open developer tools:
- Windows: <kbd>F12</kbd> or <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>
- Mac: <kbd>Cmd</kbd>+<kbd>Opt</kbd>+<kbd>I</kbd>

**Comment by mifi** [comment]
Please do as instructed

**Comment by ajpeters19** [comment]
Sorry, I am traveling for a few weeks.  Before I left I deleted 2.6.2 and went back to an earlier version that worked.  If you can't duplicate my problem then maybe it has something to do with my specific computer setup.

On Nov 13, 2019, at 5:22 AM, Mikael Finstad <notifications@github.com> wrote:

﻿

Please do as instructed

**Comment by Symbai** [comment]
I noticed the same. It only happens if the source file cannot be deleted, for example because it's still used in another process. In this case LosslessCut stuck at 99% deletion. Happened in recent version.

**Comment by mifi** [comment]
#228
