### ISSUE TITLE
Merge Fails With Long Filenames

### ISSUE THREAD

**Issue by networkproblemsolver** [mifi/lossless-cut#2200]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] This problem happens with all kinds of files that I try. For problem only with a particular file or type, [use this other form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&projects=&template=1-file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

Hi, first I want to say WOW I LOVE LOSSLESS CUT!!!  : )

And, I think I've found a bug...

If you have 3 files with the following names:

- File-123a Now is the time Now is the time Now is the time Now is the time Now is the time Now is the time Now is the time Now is the time Now is the time Now is the time Now is the time Now●is the time Now is the time Now is the time Now Now.ts
- File-123b Now is the time Now is the time Now is the time Now is the time Now is the time Now is the time Now is the time Now is the time Now is the time Now is the time Now is the time Now●is the time Now is the time Now is the time Now Now.ts
- File-123c Now is the time Now is the time Now is the time Now is the time Now is the time Now is the time Now is the time Now is the time Now is the time Now is the time Now is the time Now●is the time Now is the time Now is the time Now Now.ts

And try to CONCAT/MERGE... it fails... but if you rename them to:

- File-123a.ts
- File-123b.ts
- File-123c.ts

They MERGE just fine.

Thx!!

### Expected behavior

Should merge.

### Actual behavior

Fails to merge.

### Share log from developer tools

n/a

**Comment by mifi** [comment]
Hi! which error do you get?

**Comment by networkproblemsolver** [comment]
"Unable to merge files" (I have attached screenshots and the "report" from the app)
![Error-File-1-Load](https://github.com/user-attachments/assets/ce47e9de-3d41-43f4-a1c5-df8d0524597f)
![Error-File-2-Merge](https://github.com/user-attachments/assets/4b1895b3-9c74-4ccb-a476-cfe63458aa92)
![Error-File-3-Fail](https://github.com/user-attachments/assets/47636cf7-fbb3-421d-aaa6-5385bb1a56c4)
[Error-File-4-The-Report.txt](https://github.com/user-attachments/files/17462245/Error-File-4-The-Report.txt)

**Comment by mifi** [comment]
I think the problem might be the "●" character. did you try without it?

**Comment by mifi** [comment]
I also get an error on MacOS if too long name. I will show a warning if the file name is too long
