### ISSUE TITLE
HDR (BT.2020) video playback support

### ISSUE THREAD

**Issue by qupig** [mifi/lossless-cut#2203]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

I really like your project, it works great, thank you for all your work.

In fact, I even use it as a player rather than an editing tool many times, because with frame seeking and common shortcut key support, it is very convenient to use it to play videos.

When I tried to use it to play HDR videos, I found that it didn't seem to support HDR rendering (i.e. still output in SDR). Since `chromium` supports some online HDR video playback, I thought it was possible, but maybe it would take some work to turn it on.

This isn't an urgent and required feature, but it would be nice to support it, and maybe look into the issue when you or anyone has some time. I will also try to learn more, but after all I am not a professional in this area.

Some attempts I've made:
- HDR (BT.2020) `mkv` format video
- HDR (BT.2020) `webm` from YouTube

I've noticed that sometimes it jumps back and forth between an overexposed (almost white) high-brightness picture and a dark SDR picture, I'm not sure if it's trying to render in HDR and failing or using the incorrect brightness mapping?

I used an Apple MacBook Pro (with Apple Silicon) for testing, which has a built-in XDR display that many people are familiar with.

**Comment by mifi** [comment]
Hi! I also tried with HDR files (macbook m2), and for me I think it does support those, I see that when I open the files, the brightness looks different, and my screen sometimes adjusts its brightness. also when looking at overlays, the drop shadow gets a bit funky in that the HDR image seems too bright:

<img width="494" alt="Screenshot 2024-10-22 at 15 20 28" src="https://github.com/user-attachments/assets/828bd348-dc2d-49ff-ab6f-44524d4485e9">

Not sure how you're expecting it to play back vs how it's actually playing?
