### ISSUE TITLE
Cannot see OSD when changing playback speed in v3.63.0

### ISSUE THREAD

**Issue by defencedog** [mifi/lossless-cut#2205]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] This problem happens with all kinds of files that I try. For problem only with a particular file or type, [use this other form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&projects=&template=1-file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

Increase / decrease playback speed ...no overlay indication

### Expected behavior

Previous release had OSD

### Actual behavior

Playback speed decrease / increase without user knowing what it is

**Comment by mifi** [comment]
#2193
