### ISSUE TITLE
Added re-encoding function

### ISSUE THREAD

**Issue by Leroy-X** [mifi/lossless-cut#2208]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

I hope to add the re-encoding function to reduce the size of high-bitrate videos.

I saw the option to convert to a supported format in the file menu, but the default output is mkv, without more advanced options such as format, crf, etc.

I know it's awkward to suggest this feature in Lossless Cut.😂
But I really look forward to this feature to reduce the installation of other converters on my computer.

**Comment by mifi** [comment]
> - [x]  Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists

> Can LosslessCut crop, resize, stretch, mirror/flip, overlay text/images, watermark, blur, redact, re-encode, create GIF, slideshow, burn subtitles, color grading, fade/transition between video clips, fade/combine/mix/merge audio tracks or change audio volume?
> No, these are all lossy operations (meaning you have to re-encode the file), but in the future I may start to implement such features. https://github.com/mifi/lossless-cut/issues/372. See also https://github.com/mifi/lossless-cut/issues/643.
