### ISSUE TITLE
Help on this issue please?

### ISSUE THREAD

**Issue by heyoitscelo** [mifi/lossless-cut#2211]
Help on this issue, please?

I want to export the edits as .mov or .mp4 files, although they are being exported as text files. 
I apologize about the music, I didn't realize OBS was capturing it.

As you can see in the video, the clip gets edited and comes out as a text file, and I don't know why. I also don't understand anything about coding, to be honest.

Video for reference:
https://github.com/user-attachments/assets/b13c7c0c-a68a-4de3-818a-fca7f75707eb

https://github.com/user-attachments/assets/a1bfa87e-bc04-46e3-a2a0-870605d441bd

_Originally posted by @heyoitscelo in https://github.com/mifi/lossless-cut/discussions/2194#discussioncomment-10941104_

**Comment by mifi** [comment]
Hi. You need to include an extension in "Output file name" in the Export options. e.g. `${EXT}` or `.mp4`

**Comment by heyoitscelo** [comment]
brother, I showed it in the video, I tried choosing the mp4 option. It doesn't allow me to export the option. I can't even get into export mode. It just exports a text file even if I chose mp4

**Comment by mifi** [comment]
click the bottom right icon to enable the export options

<img width="30" alt="Screenshot 2024-10-29 at 14 10 49" src="https://github.com/user-attachments/assets/6e41780f-9297-4321-9477-05f0681438d0">

**Comment by heyoitscelo** [comment]
Brother, I've checked almost every setting. It still shows export mode as unavailable, and when I export the file, it's exporting as a failed file.

Here is another example:

What is the next thing I can try?

https://github.com/user-attachments/assets/ab78e3e6-0fd5-4722-b50d-e2cf7fa43945

ow you a video

**Comment by mifi** [comment]
![IMG_8615](https://github.com/user-attachments/assets/052661d8-d20f-40b5-8e18-07ada13d11fd)

**Comment by heyoitscelo** [comment]
sorry man but this doesn't mean anything to me, and it also help change the file type to the desired time.

Yes. I changed the output file name to "test", and the file that is coming from the app, isn't a usable file.

How can I get the damn file to cut as an MP4 or a MOV file?

**Comment by mifi** [comment]
> Hi. You need to include an extension in "Output file name" in the Export options. e.g. `${EXT}` or `.mp4`

You need to do this.
Set the output name to:

test${EXT}

**Comment by heyoitscelo** [comment]
OH WOW! MY MAN!!!

I reset the name and let it do its thing, thank you so much! I legit could not figure it out for the life of me hahaha. Cheers 👋🏽
