### ISSUE TITLE
Shift embedded timecodes by segment cut offset

### ISSUE THREAD

**Issue by monofish** [mifi/lossless-cut#2213]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] This problem happens with all kinds of files that I try. For problem only with a particular file or type, [use this other form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&projects=&template=1-file-issue.yml)

### Operating System

Other (please specify)

### Steps to reproduce

**OS:** macOS Sequoia 15.0.1 (24A348) / Apple Silicon M2 Max
**Software Version:** LosslessCut 3.63.0

Split 1 video file with time code track (QuickTime TC / SMPTE timecode) into 4 segments.

### Expected behavior

The time codes of all 4 segments should shifted by the start time of each segment. (not sure if it is a bug or a feature request)

### Actual behavior

The time codes of first frame of all 4 segments remains the same as the source video. The time codes of last frame is the time code of first frame plus the durations of each segment.

**Comment by mifi** [comment]
I would expect ffmpeg to automatically adjust timecodes when cutting, but I guess it's not implemented there, so I'm not sure how to best fix this. I've added this request here #506 - closing this issue to keep issues count down
