### ISSUE TITLE
Version number inclusion in release file

### ISSUE THREAD

**Issue by jay-ramani** [mifi/lossless-cut#2216]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Including version number in the released files will help track which version is getting installed offline, or if it requires an upgrade. Currently, the release file name is without this inclusion.

For example, name it LosslessCut-win-x64-v3.6.36.0.7z, as opposed to LosslessCut-win-x64.7z.

**Comment by mifi** [comment]
I wouldn't know how to make these links then (to the latest release binaries):

<img width="642" alt="Screenshot 2024-10-22 at 22 04 35" src="https://github.com/user-attachments/assets/125bb723-5dd6-411c-8fa3-6cc8ca1bf365">

if you have any idea, feel free to PR

**Comment by mifi** [comment]
Oh I thought you meant the *file name* of the release files. what do you mean by version number in the release file?

**Comment by mifi** [comment]
I closed the issue because I don't know how to implement it, and therefore I'm not going to work on it. If someone else knows how, then I'm open to discussing it

**Comment by jay-ramani** [comment]
> Oh I thought you meant the _file name_ of the release files. what do you mean by version number in the release file?

Yup, I meant the file name of the release file, as in the original message
> For example, name it LosslessCut-win-x64-v3.6.36.0.7z, as opposed to LosslessCut-win-x64.7z

> I closed the issue because I don't know how to implement it, and therefore I'm not going to work on it. If someone else knows how, then I'm open to discussing it
Alright. I hope someone can figure a way to implement this.

Thanks for the quick response, and cheers.
