### ISSUE TITLE
MacOS+NAS Crash while cutting the file

### ISSUE THREAD

**Issue by brunoyork** [mifi/lossless-cut#2217]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with a different kind of file to confirm that the problem is related to just this file.
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Steps to reproduce

MacOS 15.0.1
Synology NAS

While processing the file on the NAS, it will totally stuck at any point of the process, like 1.5%, 8%, 20.3%...The Losslesscut crashes, and the Finder on Mac stucks as well. 

It works perfectly before 15.0.1, i'm not sure if it's the Mac's bug or what. 

### Expected behavior

normal

### Actual behavior

crash

### Provide an error report

NA

**Comment by mifi** [comment]
If Finder is also crashing, then it sounds like a bug in MacOS. Not much I can do about it unfortunately, because LosslessCut is built on Electron, so I'm not in control of low-level stuff.
