### ISSUE TITLE
Change a video's default aspect ratio

### ISSUE THREAD

**Issue by JayNyqvist** [mifi/lossless-cut#2218]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Would be great to be able to change a video's default aspect ratio, as many times videos come with screwed up in that regard. Happens a lot with videos that were supposed to play in 4:3, but are stretched to 16:9, for example. It seems ffmpeg can do this without reenconding, should be an easy and very useful feature. Thanx for this outstanding piece of software!

**Comment by mifi** [comment]
#493
