### ISSUE TITLE
cut mode "nearest key frame cut" produces same length and file size video

### ISSUE THREAD

**Issue by llDataSciencell** [mifi/lossless-cut#222]
Dear developer,

"nearest key frame cut" doesn't working well on MacOS.
The output file is almost same file size and it could't extract selected segment of movie .

 I downloaded latest dmg file and ran it.
The file format of the movie is MOV .

"Cut mode normal cut" working well.

Anyway, normal cut working well so thank you so much for developing such a good product.

**Comment by llDataSciencell** [comment]
I also tried npm version from source code but the situation is same.

**Comment by mifi** [comment]
I think in v3 this should be fixed. can you test?

**Comment by mifi** [comment]
I think this is same as #146
