### ISSUE TITLE
Could not call remote method getFfCommandLine

### ISSUE THREAD

**Issue by olafhering** [mifi/lossless-cut#2220]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with a different kind of file to confirm that the problem is related to just this file.
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Steps to reproduce

Create some video with Pixel 7a.
````
rm -rf ~/.config/LosslessCut
~/Downloads/LosslessCut-linux-x64/losslesscut
# Tools/Toggle Developer Tools
# File/Open -> /Tmpfs/some.mp4
````

### Expected behavior

Show the video.

### Actual behavior

Error popup: "Failed to open file"

### Provide an error report

````json
No error occurred.

{
  "err": false,
  "state": {
    "ffmpegExperimental": false,
    "preserveMovData": false,
    "movFastStart": true,
    "preserveMetadataOnMerge": false,
    "externalFilesMeta": {},
    "mainStreams": [],
    "copyStreamIdsByFile": {},
    "cutSegments": [
      {}
    ],
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "separate",
    "preserveMetadata": "default",
    "preserveChapters": true
  },
  "platform": "linux",
  "version": "3.63.0"
}
````

### Share log from developer tools

[ffprobe-1.txt](https://github.com/user-attachments/files/17520489/ffprobe-1.txt)

[ffprobe-2.txt](https://github.com/user-attachments/files/17520490/ffprobe-2.txt)

[console.txt](https://github.com/user-attachments/files/17520492/console.txt)

**Comment by mifi** [comment]
see https://github.com/mifi/lossless-cut/releases/tag/v3.63.0 #2197
