### ISSUE TITLE
[Request]: An easy way to reorder clips to be joined several times.

### ISSUE THREAD

**Issue by tnilzon** [mifi/lossless-cut#223]
Would like to see an easy way to reorder video clips to be joined before saving the result. Not only the first time that the clips are selected for import (as it is now), but the possibility to preview the result of the joined clips, and then be able to change the clips order if the result is not what was intended, and once again preview the result (and save it if it looks good). As I understand, the clips order can only be edited the first time they are added into Lossless-cut.

Grate if this option could be included, thanks!

**Comment by mifi** [comment]
Reordering is now implemented. Preview I have to think about how to implement. not so trivial. #253

**Comment by tnilzon** [comment]
Great, thanks!
