### ISSUE TITLE
Merger failure

### ISSUE THREAD

**Issue by mreasonlin** [mifi/lossless-cut#2231]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] This problem happens with all kinds of files that I try. For problem only with a particular file or type, [use this other form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&projects=&template=1-file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

Why does it always happen when you merge files, but with other things like pr, it's fine.
![屏幕截图 2024-10-31 210056](https://github.com/user-attachments/assets/26eb9a30-768e-4b87-9964-4306ed1172e5)

### Expected behavior

Merger failure

### Actual behavior

Merger failure

**Comment by mifi** [comment]
Unfortunately it's hard for me to help you with such little information. maybe try again with a different kind of file and then:

> * [x]  This problem happens with all kinds of files that I try. For problem only with a particular file or type, [use this other form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&projects=&template=1-file-issue.yml)
