### ISSUE TITLE
Problem:When ffmpeg-assisted playback is enabled, the inner subtitles cannot be previewed

### ISSUE THREAD

**Issue by taozi1996** [mifi/lossless-cut#2234]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

before
![屏幕截图 2024-11-02 003459](https://github.com/user-attachments/assets/2f3b6daa-1ed9-420e-80ec-0b2870b6bd1c)

after
![屏幕截图 2024-11-02 003551](https://github.com/user-attachments/assets/7a08ead2-c119-4c1c-aef2-31ff0938b292)

**Comment by mifi** [comment]
#250
