### ISSUE TITLE
[Feature Request] Preserve Audio (Only) Beyond Ending Keyframe

### ISSUE THREAD

**Issue by Ionwerks** [mifi/lossless-cut#2238]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Great program, working unbelievably well for my use case (cutting recaps/previews from the beginning and end of tv shows).

One thing that I would find incredibly useful is (at its simplest) a slider that allowed the preservation of 0-5 seconds of audio after the last segment.

It's a common dramatic device to fade the video to black, in which the last note of the audio sustains. To not have the audio cut off I frequently end up getting the next video keyframe (typically the first image after the black). Current workaround is to export twice and then mux the longer audio with the shorter video.

Of course this could be implemented with greater complexity, giving every segment a separate audio sustain, but for my purposes at least, a single slider, affecting just the last segment would I think be 'relatively simple' and return the greatest benefit for the least work.

As said, I have a workaround, but this would be the Cat's Pyjamas.

Thank you for the app.

**Comment by mifi** [comment]
Hi and thatnks for your suggestion. TBH I think it's such a niche feature and it's not trivial to implement, so I'm probably not going to be able to prioritise it any time soon. I've added your request to #255 which is a bit similar, but I'm going to close this
