### ISSUE TITLE
Feature request: show segment time

### ISSUE THREAD

**Issue by firepol** [mifi/lossless-cut#224]
Hi,

I'd like to see segment times, e.g. if I cut a video of 50 seconds in 2 parts, after 10 seconds, I'd like to see "10s" in the first segment, and "40s" in the second.

Now I have to export my segments and play them to see their duration, which is not very efficient.

This should be trivial, because it's a simple detraction, maybe less trivial to display the value on the segment, maybe (just an idea) you could display the duration on mouse over the segment?

**Comment by mifi** [comment]
Have now added as a tooltip.
