### ISSUE TITLE
Don't store window state in config file

### ISSUE THREAD

**Issue by danielwerg** [mifi/lossless-cut#2240]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

I manage my dotfiles with git and lossless-cut's config changing after every use because I will definitely resize it at least once while using:

```diff
"windowBounds": {
-        "x": 2567,
-        "y": 745,
-        "width": 1266,
-        "height": 688
+        "x": 4383,
+        "y": 42,
+        "width": 730,
+        "height": 1391
},
```

`windowBounds` should be stored in separate file and preferably in correct system dir (`~/.local/state/lossless-cut` on linux for example)

Also I don't know what would happen if `x` and `y` is bigger then device's monitor, if I were to pull this config from my laptop with a smaller resolution screen.

**Comment by mifi** [comment]
Hmm, I think you could then argue that many other things (that change frequently) should also not be stored in the config file, like volume, output directory etc. But I don't think the added complexity of having two separate storage files outweighs the need for a less-frequently changing config file. And some people might want to customise all these things from a custom config file (see [cli](https://github.com/mifi/lossless-cut/blob/master/cli.md)). I could be open for having a config setting for completely disabling storing of window bounds though.

> Also I don't know what would happen if `x` and `y` is bigger then device's monitor, if I were to pull this config from my laptop with a smaller resolution screen.

I think window managers will usually force-resize the window to fit the screen (at least MacOS does this in my experience).

**Comment by danielwerg** [comment]
> I could be open for having a config setting for completely disabling storing of window bounds though.

good middle ground!

> ...store an additional config file in a completely different location

Well my argument is that it is not a "config" but rather a "state"

**Comment by mifi** [comment]
@Rytoxz  I think that would be #2396
