### ISSUE TITLE
LosslessCut-linux-x64.tar.bz2 is shipped without the program's icon.svg

### ISSUE THREAD

**Issue by AnthillSudoku** [mifi/lossless-cut#2249]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

LosslessCut icon is available at [icon.svg](https://github.com/mifi/lossless-cut/raw/refs/heads/master/src/renderer/src/icon.svg), but `LosslessCut-linux-x64.tar.bz2`at [releases](https://github.com/mifi/lossless-cut/releases) does not include it.

It would be nice to have it inside the bz2 file, so users can easily make a *.desktop launcher with the icon

Thanks for the app

**Comment by mifi** [comment]
how would users easily make a .desktop launcher with the icon? can't they just download it here from github?

**Comment by mifi** [comment]
The icon should already be included here:
https://github.com/mifi/lossless-cut/blob/e819bce57ed9b6af1f7b8c044a8c3d9741edd959/package.json#L432

I don’t know how else to expose it.

**Comment by mifi** [comment]
Oh, could be a bug in electron builder then, or a misconfiguration. Is it the same with appimage/snap?

**Comment by mifi** [comment]
as i've alreeady set icon to `icon-build/app-512.png`, for linux (see above) I don't know what else to do.
the icon is being auto generated at build time: https://github.com/mifi/lossless-cut/blob/e819bce57ed9b6af1f7b8c044a8c3d9741edd959/script/icon-gen.mts#L17
