### ISSUE TITLE
Trying to import mp4 from Panasonic GH5 

### ISSUE THREAD

**Issue by andreasseiler** [mifi/lossless-cut#2251]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with a different kind of file to confirm that the problem is related to just this file.
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Steps to reproduce

Record a mp4 file with Panasonic GH5 and try to import it into LossLessCut. It gives the error -> This file contains an audio track that FFmpeg is unable to mux into the MP4 format, so MOV has been auto-selected as the default output format. -> If I select mp4 manually, I get the following error -> At least one codec is not supported by the selected output file format. Try another output format or try to disable one or more tracks. Even if I select MOV I get a warning -> 

Export finished with a warning
Please test the output file in your desired player/editor before you delete the source file.
If output does not look right, see the Help menu.
Unprocessable streams were exported as separate files.
Cutpoints may be inaccurate.
There is a known problem with this file type, and the output might not be playable. You can work around this problem by enabling the "Experimental flag" under Settings.

-> I don't find an experimental flag, except "run multiple instances of losslesscut" which does not change anything.

### Expected behavior

I should be able to use the same export format as my import format was.

### Actual behavior

It converts it to MOV instead of MP4.

### Provide an error report

No error occurred.

{
  "err": false,
  "state": {
    "ffmpegExperimental": false,
    "preserveMovData": false,
    "movFastStart": true,
    "preserveMetadataOnMerge": false,
    "filePath": "/media/rw/BAK/skatebox_ad/P1144521.MP4",
    "fileFormat": "mov",
    "externalFilesMeta": {},
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High 4:2:2 Intra",
        "codec_type": "video",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1080,
        "closed_captions": 0,
        "film_grain": 0,
        "has_b_frames": 0,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv422p10le",
        "level": 42,
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "field_order": "progressive",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "id": "0x1",
        "r_frame_rate": "60000/1001",
        "avg_frame_rate": "60000/1001",
        "time_base": "1/180000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 6756750,
        "duration": "37.537500",
        "bit_rate": "199989162",
        "bits_per_raw_sample": "10",
        "nb_frames": "2250",
        "extradata_size": 108,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "creation_time": "2024-11-24T15:58:25.000000Z",
          "language": "und",
          "vendor_id": "[0][0][0][0]",
          "timecode": "12:31:05;48"
        }
      },
      {
        "index": 1,
        "codec_name": "pcm_s16be",
        "codec_long_name": "PCM signed 16-bit big-endian",
        "codec_type": "audio",
        "codec_tag_string": "twos",
        "codec_tag": "0x736f7774",
        "sample_fmt": "s16",
        "sample_rate": "48000",
        "channels": 2,
        "bits_per_sample": 16,
        "initial_padding": 0,
        "id": "0x2",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/48000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 1801800,
        "duration": "37.537500",
        "bit_rate": "1536000",
        "nb_frames": "1801800",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "creation_time": "2024-11-24T15:58:25.000000Z",
          "language": "und",
          "vendor_id": "pana",
          "timecode": "12:31:05;48"
        }
      },
      {
        "index": 2,
        "codec_type": "data",
        "codec_tag_string": "tmcd",
        "codec_tag": "0x64636d74",
        "id": "0x3",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "180000/3003",
        "time_base": "1/180000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 6756750,
        "duration": "37.537500",
        "bit_rate": "1918",
        "nb_frames": "2250",
        "extradata_size": 18,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "creation_time": "2024-11-24T15:58:25.000000Z",
          "language": "und",
          "timecode": "12:31:05;48"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "/media/rw/BAK/skatebox_ad/P1144521.MP4": {
        "0": true,
        "1": true,
        "2": false
      }
    },
    "cutSegments": [
      {
        "start": 20.339954242928457,
        "end": 24.440027
      }
    ],
    "mainFileFormatData": {
      "filename": "/media/rw/BAK/skatebox_ad/P1144521.MP4",
      "nb_streams": 3,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "37.537500",
      "size": "956350770",
      "bit_rate": "203817679",
      "probe_score": 100,
      "tags": {
        "major_brand": "mp42",
        "minor_version": "1",
        "compatible_brands": "mp42avc1",
        "creation_time": "2024-11-24T15:58:25.000000Z"
      }
    },
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "separate",
    "outSegTemplate": "${FILENAME}-${CUT_FROM}-${CUT_TO}${SEG_SUFFIX}${EXT}",
    "preserveMetadata": "default",
    "preserveChapters": true
  },
  "platform": "linux",
  "version": "3.64.0"
}

### Share log from developer tools

There is no error output in the console

**Comment by mifi** [comment]
> H5 and try to import it into LossLessCut. It gives the error -> This file contains an audio track that FFmpeg is unable to mux into the MP4 format, so MOV has been auto-selected as the default output format. -> If I select mp4 manually, I get the following error -> At least one codec is not supported by the selected output file format. Try another output format or try to disable one or more tracks. Even if I select MOV I get a warning ->

not possible. see https://github.com/mifi/lossless-cut/blob/master/issues.md#mp4mov-issues

**Comment by andreasseiler** [comment]
@mifi Thanks for the information and the quick response! But sad to hear ;)
