### ISSUE TITLE
When I switch to light theme (via the "sun" icon toggle in the lower left), the waveform is barely visible (white on almost-white).

### ISSUE THREAD

**Issue by dreirund** [mifi/lossless-cut#2262]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] This problem happens with all kinds of files that I try. For problem only with a particular file or type, [use this other form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&projects=&template=1-file-issue.yml)

### Operating System

Linux

### Steps to reproduce

* Build it on my system, Artix GNU/Linux (rolling release), from git according to [this recipe](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=losslesscut-git).
* Start it.
* Load an audio file.
* Switch to advanced view.
* Toggle the "sun icon" for light theme.
* Observe that the waveform is barely visible (white on almost white):

---

![image](https://github.com/user-attachments/assets/5f9469db-83d6-43d0-832c-7cc25640a92c)

---

### Expected behavior

Waveform switches to black colour then.

### Actual behavior

Waveform stays white, on an almost-white background.

**Comment by dreirund** [comment]
> you need to restart the app

Then the user should be notified about it with a message.

Looks very unconvenient to have a toggle in the toolbar and a need to
restart when pressing a toggle in the toolbar.

**Comment by mifi** [comment]
ideally there's no need to restart the app at all. but i didn't have time to implement that
