### ISSUE TITLE
Edit - Concatenate 2 files

### ISSUE THREAD

**Issue by JoopiJansen** [mifi/lossless-cut#2269]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

sometimes I want to paste 2 scenes from different files together. Now I have to first cut one scene then the other and then merge them together. My idea is to do this in one go.
I think that is not so difficult to implement. The procedure I have in mind is as follows:
You load the first file, then you drop the 2nd file and then in addition to the current options you should get a 5th option "place the file after the current file". 
You then can select the desired scenes/segments and export them in one go with "Merge cuts"
What do you think?

**Comment by mifi** [comment]
what you're asking sounds like a NLE. unfortunately it's not easy to implement, see #976
