### ISSUE TITLE
In Windows 10, in version 2.6.2. "delete source file" never finishes, get stuck at 99%

### ISSUE THREAD

**Issue by embryonicmadness** [mifi/lossless-cut#228]
I am having this same problem. Any way around this? I tried 2.6.0 and also got this issue

**Comment by SakuraKoi** [comment]
same here

**Comment by embryonicmadness** [comment]
2.4.0 is the only version that seems to delete the source files without it freezing

**Comment by Nitro-N** [comment]
try to run it as admin

**Comment by mifi** [comment]
I have improved it now so it doesn't crash at least. And it will show an error. I think this is related to the [trash](https://github.com/sindresorhus/trash) module. I have upgraded it, maybe it helps. will be released in newest version so if you could test it would be great.

**Comment by mifi** [comment]
in next version may be fixed
