### ISSUE TITLE
LosslessCut is referred to as 'Electron' in some contexts on Windows

### ISSUE THREAD

**Issue by vith** [mifi/lossless-cut#23]
![2017-01-30_11-35-11](https://cloud.githubusercontent.com/assets/3265539/22434087/922ebb9c-e712-11e6-9335-eea179c7a6a4.jpg)

I believe you can fix this by adding arguments to `electron-packager` like `--win32metadata.ProductName='LosslessCut' --win32metadata.FileDescription='Simple, cross platform video editor for lossless trimming / cutting of videos'` (see https://github.com/electron-userland/electron-packager/blob/master/usage.txt).

I'm not 100% sure which fields should have which strings.

I was going to make a PR but I am unable to test it as `extract-ffmpeg` errors with `mv: cannot stat 'extracted/linux_ia32/ffmpeg-3.2-32bit-static/ffmpeg': No such file or directory` on Arch Linux and NixOS, and the `VAR=val command` shell syntax isn't supported on Windows.

**Comment by mifi** [comment]
It seems the contents of the xz file had chaged, i have fixed it now, pull latest master

**Comment by vith** [comment]
OK thanks, I can package successfully now. Turns out `FileDescription` is what shows up in the context menu. So I'm thinking something like this:

```
CompanyName=mifi
FileDescription=LosslessCut
OriginalFilename=LosslessCut.exe
ProductName=LosslessCut
InternalName=LosslessCut
```

Is there a better value for `CompanyName`? If not specified it will be `GitHub, Inc.`

**Comment by mifi** [comment]
This sounds fine:)

**Comment by mifi** [comment]
If you have tested this, feel free to submit a pull request

**Comment by vith** [comment]
It's working but there are some issues. Windows persistently caches the old values in the registry at `HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Windows\Shell\MuiCache` like this:

`C:\Users\vith\Documents\LosslessCut-win32-x64\LosslessCut.exe.FriendlyAppName` = `LosslessCut`

So there was no effect until I cleared that with `regedit`.

It also also requires `wine` to run `rcedit` at package time.

I think it's possible to correct the MuiCache without administrative priveleges but I don't know if it's worth the bother to do it at every app startup and add a new dependency on a registry editing library.

**Comment by mifi** [comment]
We can fix it for new app installations, at least. Wine is already required for building for windows, i think. rcedit is automatically run when using electron-packager --win32metadata.xyz?

**Comment by vith** [comment]
Yeah, rcedit is run automatically to modify the executable: https://github.com/electron-userland/electron-packager/blob/master/win32.js#L57

I'm glad you asked because I just noticed another field that should be set: `app-copyright`

I'll update the PR.

**Comment by vith** [comment]
OK done, bumped the copyright year to 2017 as well. #24

**Comment by mifi** [comment]
Great. Thanks!
