### ISSUE TITLE
No audio when editing a ProRes Quicktime file

### ISSUE THREAD

**Issue by bouvin** [mifi/lossless-cut#232]
This tool would fit _magnificently_ in my workflow, if I could just get it to work.

I am trying, on macOS, to edit a ProRes Quicktime file with an AAC soundtrack. The video plays back without any issues, but there is no audio, and that's what I need for my editing cues.
Other files play back without issues, and I have made various combinations of files remuxing with ffmpeg that shows that if the video format is ProRes, then there is no audio playback, regardless of the audio codec. This is also the case, if the container format is changed from Quicktime to MKV.

[Example-quicktime.zip](https://github.com/mifi/lossless-cut/files/3951029/Example-quicktime.zip)
[Example-media-info.txt](https://github.com/mifi/lossless-cut/files/3951030/Example-media-info.txt)
[Example-console.log](https://github.com/mifi/lossless-cut/files/3951032/Example-console.log)

**Comment by mifi** [comment]
Hi. Unfortunately ProRes is not 100% supported by LosslessCut, so it will render a low FPS preview without audio. Note however that when you do the actual cut, the OUTPUTTED video will still be lossless and contain the audio. I have added a text in the app to clarify this

**Comment by bouvin** [comment]
Ok, thank you for the clarification. In the interim, I have changed the ordering of my workflow, so I first encode, and then edit using LosslessCut. It works very well, and I am _much_ impressed with the speed of LosslessCut.

**Comment by mifi** [comment]
Ok, i'm closing this because it kind of depends on supporting more formats natively in lossless-cut, which i have not figured out yet #88
