### ISSUE TITLE
Using MP3 Files: End Cut Point Selection Not Recognised in output file. 

### ISSUE THREAD

**Issue by CmdrMic** [mifi/lossless-cut#234]
When working with an MP3 file in Lossless-cut appimage on LM19.1, you can select any START POINT along the MP3 to export from fine - and it works in the output file, starting where you selected. However, when you go ahead and select the END POINT for the cut, it shows up fine, but when you EXPORT via the clipping scissors - the END POINT you selected not recognised (ignored), and the audio file gets exported out - to the end of the original. In essence, selecting the END POINT, for a clipping does not appear to work with an MP3 file.

**Comment by mifi** [comment]
I tested with an mp3 file and it works, also end point. can you provide an example file that does not work?

**Comment by mifi** [comment]
Closing because of lack of response. Try with newest version and reopen if this is still an issue.
