### ISSUE TITLE
Change cut time does not update preview

### ISSUE THREAD

**Issue by Symbai** [mifi/lossless-cut#237]
Unlike clicking on the timeline changing the time using the text boxes next to the play button does not update the preview image. This makes it super difficult to cut precisely.

**Comment by mifi** [comment]
Preview image, do you mean cutting unsupported format like h265?

**Comment by Symbai** [comment]
No, I mean the huge video "screen" / player / preview control in the app. If you click in the timeline it jumps to the position. But if you change the time in the text boxes it does not.

**Comment by mifi** [comment]
fixed in newest
