### ISSUE TITLE
[Feature request] Distribute LosslessCut through Microsoft Store

### ISSUE THREAD

**Issue by o-l-a-v** [mifi/lossless-cut#240]
Would be awesome LosslessCut could be distributed through Microsoft Store. And maybe as Snaps or Flatpaks on Linux, and in the Apple store (or whatever it's named) for Mac.

It would make it more convenient, not only for installs but also updates.

**Comment by mifi** [comment]
- I would love to distribute to Microsoft store but Microsoft requires an EV certificate, which costs a lot, and I have no other reasons to get an EV cert than microsoft store so it doesn't make any sense more me. If someone is willing to pay for this then I can add support.
- Apple Mac store seems to not allow electron apps right now, looks like they are working on it: https://github.com/electron/electron/issues/20027
- Snap is already being built
- Flatpak it doesn't seem like Electron is supporting it by default, is it really popular?

**Comment by dddeveloperrr** [comment]
@mifi  Hi, Could you please upload snap binary to snap store?

**Comment by mifi** [comment]
I tried to create a snapcraft account and get an api key for uploading but I didn't find it anywhere in the portal. will have to research more.

**Comment by mifi** [comment]
Closing in favor of #218

**Comment by mifi** [comment]
Added a bounty here to cover costs: https://issuehunt.io/r/mifi/lossless-cut/issues/240

**Comment by mifi** [comment]
I just signed the exe with a free 30 day trial code signing cert from [ascertia](https://account.ascertia.com/shop/buyproducts). Their certs only cost 17EUR/yr. I'm not sure how effective they are. Please download and try the newest windows binaries and see if they still give a warning

**Comment by mifi** [comment]
Now it's in Mac App Store and Windows Store 🙌
