### ISSUE TITLE
App image not working anymore

### ISSUE THREAD

**Issue by arnauldb** [mifi/lossless-cut#241]
Hi,

I cannot cut anymore (used to work fine) using the app image. I receive this error:
![2020-01-27_10-18](https://user-images.githubusercontent.com/13196747/73163496-09d89280-40e8-11ea-907d-b2ea2a256ce7.png)

Using ffmpeg works, e.g. `ffmpeg -i h.mp4 -ss 00:00:05 -codec copy -t 15  Funny_cut.mp4

I am on Linux Mint 18.3 Sylvia , Lossless-cut 2.6.2.

Thank you.
`

**Comment by mifi** [comment]
Hi. Can you identify which version is working, and which one is not? and possibly as suggested in the issue template, provide console output from js console

**Comment by arnauldb** [comment]
My problem was solved using latest version 2.6.3.

**Comment by mifi** [comment]
Ok great!
