### ISSUE TITLE
5 seconds of white frames before each trim

### ISSUE THREAD

**Issue by vjsveskenielsen** [mifi/lossless-cut#242]
No matter the settings, no matter the format, I'm consistently getting a 5 second block of pure white frames before the actual trim when exporting. It seems to not happen when exporting and merging two clips, but will happen when exporting either one or multiple individual clips.

on Mac OSX High Sierra

**Comment by mifi** [comment]
did u try to toggle between kc and nc?

**Comment by mifi** [comment]
Reopen if still an issue in v3
