### ISSUE TITLE
What happened to (portable) zip releases for Windows?

### ISSUE THREAD

**Issue by AdKiller** [mifi/lossless-cut#243]
I was wondering why you stopped releasing portable zip for Windows?

**Comment by joshirio** [comment]
Maybe because it's just an `.exe` file, no need to have a `zip`. The executable is already portable. So nothing changed.

**Comment by opusforlife2** [comment]
It's not a 'true' executable. It's actually just a self-extracting archive that you can browse using 7-Zip (https://en.wikipedia.org/wiki/Nullsoft_Scriptable_Install_System#Generated_installer). It further contains an actual .exe in the folder structure. You can unpack the archive and use that .exe without issue.

@mifi Would you consider releasing the Windows version as a zip again in addition to the .exe? Chocolatey was downloading your zip and unzipping the program directly in a folder structure. So we could manually update ffmpeg without issue, if required. Now it can't be done unless we do the whole exercise of unpacking, modifying, and then repacking with Nullsoft. Which becomes redundant at the very next update.

Change from zip to exe: https://github.com/chtof/chocolatey-packages/commit/d29429d20dffa55afdd056613f176e6eb6bc2a74#diff-d31d7bc402c057f24d6892760f145e9d

**Comment by mifi** [comment]
Ok I added zip in the build now, should be included on next release
