### ISSUE TITLE
No warning when disk full leaving corrupt file.

### ISSUE THREAD

**Issue by ErwinCraps** [mifi/lossless-cut#244]
When cutting the file and not enough disk space the program does not give a warning and leaves a corrupt file behind.
IT would be nice to get a warning at forehand or at least an error when it happens deleting the unfinished file.
Thank you

**Comment by mifi** [comment]
I have not really considered this edge case so important, but I can look into it when time

**Comment by mifi** [comment]
Are you sure that it does not give any error when running out?

**Comment by mifi** [comment]
reopen if still an issue
