### ISSUE TITLE
inverse cutting

### ISSUE THREAD

**Issue by mifi** [mifi/lossless-cut#247]
it will be great to have a reverse option where the selected segments are deleted and the rest of the video is merged (currently the only option is to select the segments that you want to keep)

From #196

**Comment by mifi** [comment]
Now implemented

**Comment by firepol** [comment]
> Now implemented

Hi, I tried to find a way to do that, but didn't find option/button to reverse cut, you wrote it's implemented, but where? I'm using the version from github, I do `git pull` (and compile) regularly and have the latest version...
I saw rotation, zoom etc. but no way to choose to reverse. Please document this, thanks ;)

**Comment by mifi** [comment]
Try the yin yang symbol

**Comment by firepol** [comment]
Ah that doesn't do what I was expecting, my bad... my idea is totally
different, I will create a feature request for it.

I was thinking more to reverse the shot, e.g. with the drone I often shoot
the last minute of the battery, when the drone is landing. The shot is
kinda boring if you can imagine, a nice view, then the drone loses altitude
to arrive at landing. But if you "reverse" the shot, meaning you play it
reversed (or inverted - all editors have this feature, to speed up and also
to reverse the shot) it becomes an interesting shot. Basically lossless cut
is my favorite tool to manage my drone shots and to store only what I need
and the way I need it, e.g. in this case a short reversed, ready to be used
in post production.

As said, feature request will follow.

Thanks for considering it, cheers Paolo

**Comment by Gunstick** [comment]
Reversiong video needs reencoding, so it is not lossless. You need to use a video editor for this.
