### ISSUE TITLE
Feature Request: Add mode to set areas for cutting out

### ISSUE THREAD

**Issue by dquinton** [mifi/lossless-cut#257]
Hi there, I really like LC and I find it a very useful tool, being so fast and also with such a tidy interface.

I do find one thing a little difficult though and that's when I want to chop out a little area of video and keep all the rest - it involves selecting the large ares of video to keep, leaving out the little, sometimes ten frames, that i want to edit out.

If I need to cut out lots of little glitches like black frames, then it adds up to quite a lot of work, selecting to keep instead of cutting out.

I would suggest adding modes to LC:
Mode 1. Select to save (the current operation)
Mode 2. Select to cut (where any small area will be set with in/out markers and that area will be lost when exporting, no need to set an area at the video beginning and another up to the end).

I guess the modes will need a visual indication of which one is in use, to save doing the wrong kind of work and cutting out what one actually wants to keep!

This technique would be closer to Avidemux's approach, and people being used to that program could easily make use of LC.

What do you think?

**Comment by mattack1** [comment]
That exists now.  In the settings, you choose Cut Away to remove the selection, or Keep to keep only the selected sections.

**Comment by mifi** [comment]
Yes this is implemented now. Maybe it is not clear enough how it works?

**Comment by mattack1** [comment]
yeah, also the fact that you hit a ? mark button to get to settings.. and they're at the bottom of the list of keyboard shortcuts.. I see the start of the settings list.. but it's just completely confusing IMHO.

I think there should be a menu item for Preferences or Settings that brings up a separate menu.

**Comment by mattack1** [comment]
Also, maybe the setting could be made slightly clearer.

Selection   KEEP  REMOVE

is _almost_ enough info to make it clear to me.. with the info on the left being a tiny bit more in depth.  "Cut away" just sounds a little bit strange IMHO.

**Comment by mifi** [comment]
Have now improved this, and added a pop up message when toggling.
