### ISSUE TITLE
Error sandboxing

### ISSUE THREAD

**Issue by dquinton** [mifi/lossless-cut#258]
I'm stuck trying to run the latest release. I run with the command
 ./lossless-cut 

and get this error
[23567:0224/195332.055701:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/dav/Downloads/LosslessCut-linux/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap

If there was a Readme file I might know what to do properly.
what can i do?

**Comment by mifi** [comment]
Need to research more. I tried in Ubuntu 18 and it works there

**Comment by allenfoxtc** [comment]
try
```shell
./lossless-cut --no-sandbox
```

it's work for me in debian 9 and ubuntu 18 docker

**Comment by mifi** [comment]
Thanks. I added a readme about this workaround for now. Needs more research

**Comment by mifi** [comment]
Seems like a common problem with Electron. See https://github.com/electron/electron/issues/17972

**Comment by mifi** [comment]
Maybe want to look into bundling a script like this:
https://github.com/electron-userland/electron-builder/issues/4278

**Comment by allefeld** [comment]
Same problem with AppImage on Debian 10.7, `--no-sandbox` works.

**Comment by mgagliol** [comment]
Same issue using the snap install in Debian 10

**Comment by mifi** [comment]
Closing because not much actionable for me. I hope that future versions of electron will fix this #714

**Comment by JaimeACruz** [comment]
Thank you. I updated the application launcher and added "--no-sandbox" and now it starts up and runs as expected.

**Comment by tredondo** [comment]
@mifi

>  I added a readme about this workaround for now. Needs more research

This is no longer in the README?

> I hope that future versions of electron will fix this https://github.com/mifi/lossless-cut/issues/714

Latest Electron still hasn't fixed this.

> Maybe want to look into bundling a script like this:

For other applications like Obsidian, the advice is to [create an /etc/apparmor.d profile](https://askubuntu.com/questions/1512287/obsidian-appimage-the-suid-sandbox-helper-binary-was-found-but-is-not-configu/1528215#1528215). I tried this and it worked for LosslessCut too.

**Comment by mifi** [comment]
> This is no longer in the README?

yes it is: https://github.com/mifi/lossless-cut/blob/master/docs/troubleshooting.md

> For other applications like Obsidian, the advice is to [create an /etc/apparmor.d profile](https://askubuntu.com/questions/1512287/obsidian-appimage-the-suid-sandbox-helper-binary-was-found-but-is-not-configu/1528215#1528215). I tried this and it worked for LosslessCut too.

if there's an easy way to do that with electron-builder, sure.
