### ISSUE TITLE
Redraw issue on timeline around playhead

### ISSUE THREAD

**Issue by dngrlux** [mifi/lossless-cut#259]
I'm noticing a redraw issue in the latest builds. Vertical black bars are appearing around the playhead.

I believe it started somewhere around version 3.8.0, and has not been resolved as of 3.9.1. [macOS Catalina 10.15.3]

![redraw screenshot](https://user-images.githubusercontent.com/12442027/75302629-35d45a00-57f3-11ea-9bcc-a89b063d45fd.png)

**Comment by mifi** [comment]
Did you do something to these screenshots? I added black 1px wide bars to indicate keyframes, but they look more like this:

<img width="368" alt="Screenshot 2020-02-26 at 10 54 13" src="https://user-images.githubusercontent.com/402547/75307303-60232780-5886-11ea-8428-769a0f46a603.png">

If no, how do you reproduce this issue?

**Comment by dngrlux** [comment]
Those screenshots were only cropped. I just downloaded 3.10.0 and there are still redraw oddities, although different than before (screen recording attached). I am dragging a video into the application window, then using the i and o hotkeys to mark in and out points.

[Screen Recording 2020-02-26.zip](https://github.com/mifi/lossless-cut/files/4257319/Screen.Recording.2020-02-26.zip)

**Comment by mifi** [comment]
Interesting! Thanks for sharing screenrec. I think the issue here is that your video has a LOT of keyframes, and they are all being rendered due to the new feature I added of rendering keyframes. I will make a button to toggle showing of keyframes.
What kind of video format is this?

**Comment by EtiamNullam** [comment]
For me black square covering the timeline was following the cursor.
LosslessCut 3.8.0, Windows 10

![0VTgOQBtvW](https://user-images.githubusercontent.com/10875340/75462674-defe8a00-5984-11ea-9e6c-3f168c65e6ec.gif)

Update to LosslessCut 3.11.0 fixed the problem.

**Comment by mifi** [comment]
What kind of file is this @EtiamNullam ? Do you mind to share a short segment from one file? I think this is also caused by keyframes very tightly packed together

**Comment by dngrlux** [comment]
That sounds right… if I zoom into the timeline, they start to spread out.
The video is from a Skydio 2 drone. MP4, H.264 HD (1-1-1), 3840x2160, 60fps, 100mbit/sec.

**Comment by EtiamNullam** [comment]
@mifi: Yes I think you're right. I don't have the previous file anymore but I have encountered similar behavior with different file (using LosslessCut 3.11.0).

![image](https://user-images.githubusercontent.com/10875340/75599177-8a513100-5aa2-11ea-95ee-d35c85d083ed.png)

It's a recording of game using Nvidia Experience (Geforce Share). Codec info:

![image](https://user-images.githubusercontent.com/10875340/75599199-ea47d780-5aa2-11ea-9585-425676f2a711.png)

Hiding keyframes helps, so I guess they were indeed just tightly packed.

**Comment by mifi** [comment]
I want to make it more clear that they are keyframes or hide them altogether when too tightly packed to be useful
