### ISSUE TITLE
First just sound, video follows after a few seconds

### ISSUE THREAD

**Issue by Haringkoning** [mifi/lossless-cut#26]
Hi, when I use LosslesCut on a Mac (macOS Sierra 10.12.23 (16D32) some edited videos have the following problem: video starts, I can hear sound but no video yet, only after a few seconds the video can be seen. From that moment the video plays correct (in sync). Publishing such clips on YouTube is not possible. The file can be uploaded, but can't be processed.  
I have included a sample of such video.
[uhlvjd.mp4-00.32.16.547-00.33.04.956.mp4.zip](https://github.com/mifi/lossless-cut/files/781409/uhlvjd.mp4-00.32.16.547-00.33.04.956.mp4.zip)

**Comment by Haringkoning** [comment]
Some info provided by MediaInfo:
General
Complete name                            : /Users/.../Downloads/uhlvjd.mp4-00.32.16.547-00.33.04.956.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 5.65 MiB
Duration                                 : 48 s 406 ms
Overall bit rate                         : 979 kb/s
Encoded date                             : UTC 1904-01-01 00:00:00
Tagged date                              : UTC 1904-01-01 00:00:00
Writing application                      : Lavf57.56.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L4
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 39 s 0 ms
Bit rate                                 : 1 010 kb/s
Width                                    : 720 pixels
Height                                   : 436 pixels
Display aspect ratio                     : 16:9
Original display aspect ratio            : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.129
Stream size                              : 4.70 MiB (83%)
Encoded date                             : UTC 1904-01-01 00:00:00
Tagged date                              : UTC 1904-01-01 00:00:00
Color range                              : Limited
Color primaries                          : BT.601 PAL
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.601

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 48 s 406 ms
Bit rate mode                            : Constant
Bit rate                                 : 160 kb/s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 spf)
Compression mode                         : Lossy
Stream size                              : 946 KiB (16%)
Language                                 : English
Default                                  : Yes
Alternate group                          : 1
Encoded date                             : UTC 1904-01-01 00:00:00
Tagged date                              : UTC 1904-01-01 00:00:00

**Comment by mifi** [comment]
Does it matter where you do the cut? (start-end points)

**Comment by Haringkoning** [comment]
Nope, some are fine from 00:00:00 till an any point are fine, some not. The same goes for videos edited at any other point.

**Comment by mifi** [comment]
If you do the same cut many times on the same video, sometimes it works on youtube and other times it does not? You're saying it's not deterministic?

**Comment by Haringkoning** [comment]
That's correct; some are fine, some aren't. In general the videos downloaded from YouTube can be edited without problems.

**Comment by codyolsen** [comment]
@mifi This sounds like the same issue in #13

**Comment by TechManiacHD** [comment]
It seems like the same bug to me. I noticed it on many of the cutted videos. I learnt to cut with adding few extra seconds to the clip on both ends.
Although, I am cutting videos in order to save disk space and then I am doing everything else in PowerDirector 16. With Losseless-cut I am only cutting off that footage that I would not use for sure and that way i can safe up to 1/3 space on each project.

**Comment by bnku** [comment]
I confirm the presence of this problem.

**Comment by mifi** [comment]
Yes, unfortunately this is the long standing issue with ffmpeg not being able to consistently cut on the keyframe borders. Long discussion here: #13

@TechManiacHD that's a very good tip, i'm using the same technique. I'll add it to readme.
