### ISSUE TITLE
Make the setting only "Ask for confirmation when closing changed file".

### ISSUE THREAD

**Issue by mattack1** [mifi/lossless-cut#261]
When I launch the app, there's no file open, so quitting the app doesn't cause me any data loss.  Neither would closing the app after I had opened the file, if I hadn't made any edits.

Personally, it's annoying when apps ask for confirmation to quit when there's no chance of data loss.

LosslessCut 3.11.0

**Comment by mifi** [comment]
Thanks, i have now improved this.

**Comment by mattack1** [comment]
Is there any way you can make it so _we_ can close them?  That's the way bugs usually work -- the person who wrote up the bug gets to close it when they have verified that it has been implemented.

**Comment by mifi** [comment]
On github we have a reopen function. Just reopen if the solution is not satisfactory
