### ISSUE TITLE
remove relative seeking / add absolute seeking

### ISSUE THREAD

**Issue by RieGo** [mifi/lossless-cut#264]
First of all: I really love this tool and the improvements you've made recently are great.
but the 5% seeking you introduced destroyed usability for me on big files :(
so it would be great if you could:
 -revert the seeking to the way it was before, it was perfect
 -maybe use different buttons for relative seeking
or
 -make a setting for seeking?

much appreciated!

**Comment by mifi** [comment]
Many people were complaining that the seeking was too short on long files, so i thought to make it more flexible by using percentage at current zoom level. Maybe I revert back this, but use a modifier key like ctrl+left/right for percent jump

**Comment by RieGo** [comment]
I see, it's hard to make everyone happy I guess :)
your suggestion sounds great to me.

**Comment by mifi** [comment]
Ok I implemented this now. ctrl or cmd + arrows will seek 1%, while just arrow is back to 1 sec. will be in next version
