### ISSUE TITLE
New segment end position default to end of video

### ISSUE THREAD

**Issue by Hezer** [mifi/lossless-cut#266]
I like the new functionality, that you create new segment when placing a segment start past the end of segment. But as it is currently, I also sometimes create multiple 10s segments when I try to place the start at the desired position.

Here's my workflow:
I scroll through the clip and place the segment start at the point I where I think there's something worth keeping.
Then I keep watching, realize that my start was too early and try to move the start to the current position. But because by default, it creates a 10 second segment and I'm past that, it creates a new segment.

To counteract this, I need to first place the end at my current position, jump back a little and place the start there.

If new segments would default to end at the end of video, it wouldn't have this issue. Or have new segment length be customizable.

**Comment by mifi** [comment]
Good idea. I agree. 10 sec was just an arbitrary number i chose. I will change it like this and if people object then we can make it to a setting
