### ISSUE TITLE
how to use locales/pak

### ISSUE THREAD

**Issue by Phil171** [mifi/lossless-cut#267]
Hi, 
sorry for my bad english, I'm French.
Using LossLess on Ubuntu, how to use *.pak in /locales/ ?
There are certainly translation but I don't know how to use it... :-(

I use LosslessCut to remove adds or beginning / end of films or huge *.mpeg or *.m2ts with the help of VLC as viewer, it works perfectly !!
Thanks a lot for this very fast and light tool !
Philippe from France

**Comment by mifi** [comment]
Hi! The translations are not for LosslessCut but for Electron. LC does not yet support locales unfortunately. See this issue #29
