### ISSUE TITLE
Unsupported file

### ISSUE THREAD

**Issue by DJ-Tawny** [mifi/lossless-cut#269]
Dragging in a .mp4 file gives 'Unsupported File' error. 

PS. just want to say massive thanks for making Lossless Cut, fantastic software.

**Comment by mifi** [comment]
Can you share a file that reproduces the problem or share log from developer tools as instructed in the new issue template?
Does it work with a previous version of LC?

**Comment by mifi** [comment]
I have now improved the error reporting. Please try pre-release version `v3.18.0` and reopen if still an issue.
