### ISSUE TITLE
End time should be end of video by default.

### ISSUE THREAD

**Issue by vitorgalvao** [mifi/lossless-cut#27]
If we set a *start* time but not an *end* time, and try to export, we get this message:
![](https://i.imgur.com/w8iZB51.png)

However, if we set an *end* time but not a *start* time, and try to export, it simply assumes the start time is the beginning of the video, *which makes perfect sense and is expected*. Similarly, then, the end time should be interpreted as the end of the video, if none is set.

**Comment by mifi** [comment]
I agree. I will implement this when I have time.

**Comment by mifi** [comment]
See #30

**Comment by mifi** [comment]
Implemented in 664878f5919466e675a359091c41e5be7705b803
