### ISSUE TITLE
m2ts audio missing unless using mp4

### ISSUE THREAD

**Issue by ikingjosh** [mifi/lossless-cut#270]
Love the new interface!
Not super experienced, couldn't open developer tools first
Trying to cut a 5 min clip out of a 29gb .m2ts movie file.
Upon loading I get the message that preview will not have audio but file export will.  However, the export, while it has great lossless video in the original .m2ts format, does not include the audio.  Original file does have audio, and I manually check LosslessCut settings to ensure audio track is selected to be included in the export.  This also occurs on my previous version of Lossless, v2.7.1
Attached are some relevant screenshots, in order.
![Untitled](https://user-images.githubusercontent.com/61835527/75991119-9af71200-5ebb-11ea-9fa8-74967742a19d.jpg)

**Comment by ikingjosh** [comment]
Strange, attempted with Ffmpeg, same problem.  However when I changed output file type from .m2ts to .mp4 in Ffmpeg the audio was preserved

**Comment by mifi** [comment]
It works in losslesscut if you change the output file to mp4 also?

**Comment by ikingjosh** [comment]
Unfortunately, no.  When I select output .mp4 and then click export I get the attached message.
![1](https://user-images.githubusercontent.com/61835527/76097525-7e2b0f00-5f8d-11ea-8c86-471e58c6241b.png)
![2](https://user-images.githubusercontent.com/61835527/76097528-81be9600-5f8d-11ea-87d6-8946c2fd75ae.png)

**Comment by mifi** [comment]
Ahh, because subtitle is not supported in mp4. You can either try matroska. or disable the subtitle track from the Tracks selector. I think the reason why ffmpeg command line works is because i think it strips the subtitles.

**Comment by ikingjosh** [comment]
Oh ok got it.  Thanks for looking it to it!
