### ISSUE TITLE
Video cut error "Whoops! ffmpeg was unable to export this video. "

### ISSUE THREAD

**Issue by embryonicmadness** [mifi/lossless-cut#273]
Was working fine all day and suddenly I got this. 

Whoops! ffmpeg was unable to export this video. Try one of the following before exporting again:
1. Select a different output format from the mp4 button (matroska takes almost everything).
2. Exclude unnecessary tracks
3. Try "Normal cut" and "Keyframe cut"

**Comment by mifi** [comment]
Gonna need some more info here. what kind of file etc, did it suddenly stop working with the same file or a different one?

**Comment by embryonicmadness** [comment]
Problem on my end. Sorry about that. ffpeg was not installed correctly.

**Comment by mifi** [comment]
What do you mean ffmpeg was not installed? ffmpeg does not need to be installed, as it is included in losslesscut

**Comment by embryonicmadness** [comment]
My ffmpeg was not installed on my computer correctly I think. I was a very old version and missing a few dependencies. I reinstalled it correctly and Lossless Cut started working back to normal. Not sure if it was that that was causing the problem but it fixed it.  I use Lossless Cut Appimage on LInux Mint.
