### ISSUE TITLE
Output MKVs don't contain attachments

### ISSUE THREAD

**Issue by Cyberavater** [mifi/lossless-cut#275]
Some MKVs have attachments such as subtitles' fonts. After cutting with lossless-cut the attachments are lost!
Eg files:
How it should be; https://anonfiles.com/Vdt2l6hfo6/Kokoro_Connect_ED_2_Cry_OutSakebu_x1_mkv
How it is; https://anonfiles.com/T4t2l7h0o8/Kokoro_Connect_ED_2_Cry_OutSakebu_x2_mkv

In the first one, I manually added font's using MKVToolNix, which lossless-cut missed from the source file.

BTW, thanks for working on this tool! This tool is amazing!

**Comment by mifi** [comment]
Ohh! I've never encountered files with attactment tracks, let alone that many. It seems to work if you open the Tracks panel (top left) and manually toggle all the attachment streams by clicking the icons like this:

<img width="612" alt="Screenshot 2020-03-19 at 23 49 31" src="https://user-images.githubusercontent.com/402547/77086263-7fa01100-6a3c-11ea-97c3-3f858f0d335c.png">

Other than that, i'm not sure how to handle those kinds of streams in general. maybe we should always include attachment streams.

**Comment by Cyberavater** [comment]
Yeah, that'll do, thanks!

**Comment by mifi** [comment]
fixed
