### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by DeStilleGast** [mifi/lossless-cut#277]
Hey, I'm totally new in the program, freshly downloaded the zip file (release 3.16.4) and extracted it, when I tried to start it, it goes to a black screen, the menu's are working but its not working.

![image](https://user-images.githubusercontent.com/3677706/76902807-0f0ebe00-689d-11ea-8742-60cb8f0d54f8.png)

Tried to start it with other graphicscard but no effect

**Comment by DeStilleGast** [comment]
killing the GPU process on the chromium based edge seems like to fix this issue

**Comment by mifi** [comment]
Is there anything special with your setup? what is chromium based edge?

**Comment by DeStilleGast** [comment]
So far I know there is nothing special with my setup. and with chromium based edge I mean the new microsoft edge webbrowser: https://www.microsoft.com/en-us/edge it is based on the google chromium project

**Comment by mifi** [comment]
Ok, that's odd, because losslesscut (electron) bundles a normal chromium inside, afaik.

**Comment by moeinrahimi** [comment]
for me, a couple of first trying to start the app was resulting in black screen, but now it's working just fine no idea what was the issue

**Comment by mifi** [comment]
Windows? From windows store or downloaded zip?

**Comment by mifi** [comment]
Have now improved error reporting
