### ISSUE TITLE
About playback speed

### ISSUE THREAD

**Issue by taozi1996** [mifi/lossless-cut#278]
We can use keyboard  'J','L' to slow down and speed up playback，but if we use keyboard  'k'or space'' to pause and play the video,then the video will play as normal speed.
Can you add a botton like zooming in/out timeline that we can change the playback speed all the time?
I want to always play the video as 1.5x,2x playspeed.

**Comment by mifi** [comment]
I have now changed so that `k` will not reset the playback speed, but `space` will still reset. I hope that's an ok solution
