### ISSUE TITLE
Shortcut conflict

### ISSUE THREAD

**Issue by sojey** [mifi/lossless-cut#279]
ver. 3.17.0 and older verion.
The menu bar has two completely different functions, using the same shortcut !
ctrl+w
File - close & window - close
When I closed the file without closing the software, it puzzled me, and then I discovered that it was a shortcut conflict.

**Comment by mifi** [comment]
Is it on windows? Can you show me a screenshot? On Mac there is no conflict. Only File -> Close is `cmd+w`, which is how I intended it, because it makes no sense to close only the window iwthout closing the app

**Comment by sojey** [comment]
> Is it on windows? Can you show me a screenshot? On Mac there is no conflict. Only File -> Close is `cmd+w`, which is how I intended it, because it makes no sense to close only the window iwthout closing the app

yes, windows 10 x64, but I can't upload pic in here, if you have windows 10, you can follow the menu that I typed. My english is not good, hope you can understand.

**Comment by mifi** [comment]
This is now fixed in newest version

**Comment by mattack1** [comment]
But it does make sense on Mac.. I can't bring up the About window for example, and close it with cmd-W.  The menu flickers, but nothing happens.

Also, though I generally dislike this kind of app, you could make it so closing the window quits the app.  Some single-window-apps use that UI..  e.g. even System Preferences.

**Comment by mifi** [comment]
I agree that cmd-W should close windows, but since there is only one other window in the app (the about window), i don't wanna do anything about that now. It seems like Mac doesn't have the close menu under window

**Comment by mattack1** [comment]
I totally agree that it's a _low_ priority item, but not having cmd-W work for even 'just' the About window is yet another thing that makes the app's UI not be consistent with the Apple GUI.  (But e.g. I use a Java app, kmttg, that's totally weird too..)
