### ISSUE TITLE
Please Make It Work on Audio M4A/AAC Files Too

### ISSUE THREAD

**Issue by caa** [mifi/lossless-cut#28]
It would be great if this worked on audio files too. I get the error:

> Whoops! ffmpeg was unable to cut this video. It may be of an unknown format or codec combination

I confirmed that FFmpeg could losslessly cut this particular file:
ffmpeg -i iKey_002.m4a -ss 00:46:30.094 -to 01:12:56.649 -c copy OutputFile.m4a

Thanks for making a very useful program. It allows non-tech people to do an extraordinary thing!

**Comment by mifi** [comment]
Can you open developer tools (ctrl+shift+i / cmd+alt+i / f12) and see if there is any additional output from ffmpeg when cutting?
Or if possible please share the file or a cut part of the file that can reproduce the problem

**Comment by caa** [comment]
Here's the output:

> Version 1.5.0
Load /Users/chris/Downloads/iKey_003.m4a
getFormat /Users/chris/Downloads/iKey_003.m4a
formats mov,mp4,m4a,3gp,3g2,mj2
Cutting from 2470.640024 to 2768.165971
ffmpeg -i /Users/chris/Downloads/iKey_003.m4a -y -vcodec copy -acodec copy -ss 2470.640024 -t 297.5259470000001 -f m4a /Users/chris/Downloads/iKey_003.m4a-00.41.10.640-00.46.08.165.m4a
stdout: 
stderr: ffmpeg version 3.2-tessus Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 8.0.0 (clang-800.0.38)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzmq --enable-version3 --disable-ffplay --disable-indev=qtkit --disable-indev=x11grab_xcb
  libavutil      55. 34.100 / 55. 34.100
  libavcodec     57. 64.100 / 57. 64.100
  libavformat    57. 56.100 / 57. 56.100
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/chris/Downloads/iKey_003.m4a':
  Metadata:
    major_brand     : M4A 
    minor_version   : 0
    compatible_brands: M4A mp42isom
    creation_time   : 2017-02-22T07:03:08.000000Z
    iTunSMPB        :  00000000 00000840 000002AF 000000000747F511 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
  Duration: 00:46:09.97, start: 0.047891, bitrate: 64 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 62 kb/s (default)
    Metadata:
      creation_time   : 2017-02-22T07:03:08.000000Z
      handler_name    : Core Media Audio
**[NULL @ 0x7fd837000600] Requested output format 'm4a' is not a suitable output format
/Users/chris/Downloads/iKey_003.m4a-00.41.10.640-00.46.08.165.m4a: Invalid argument**

**Comment by mifi** [comment]
I have now implemented a fix for this issue (aac/m4a files) and it will be included in the next release.

**Comment by caa** [comment]
Thanks, that's awesome news!
