### ISSUE TITLE
Wrong output vtag for Panasonic GH5S

### ISSUE THREAD

**Issue by mifi** [mifi/lossless-cut#280]
When converting a video, for example from Panasonic GH5S that has h264 (High 4:2:2) 10bit 4k, ffmpeg will convert the vtag from `avc1` to `aivx`.

input.MOV:
```
Stream #0:0(und): Video: h264 (High 4:2:2) (avc1 / 0x31637661), yuv422p10le(pc, bt709), 3840x2160 [SAR 1:1 DAR 16:9], 142827 kb/s, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc (default)
...
Stream #0:1(und): Audio: pcm_s16be (twos / 0x736F7774), 48000 Hz, stereo, s16, 1536 kb/s (default)
```

output.MOV:
```
Stream #0:0: Video: h264 (aivx / 0x78766961), none, 3840x2160, 142827 kb/s, SAR 1:1 DAR 16:9, 29.97 fps, 29.97 tbr, 90k tbn (default)
...
Stream #0:1: Audio: pcm_s16be (twos / 0x736F7774), 48000 Hz, stereo, s16, 1536 kb/s (default)
```

This causes issues with playback.

Workaround is to append these arguments: `-strict -2 -vtag avc1`

See https://video.stackexchange.com/questions/21330/ffmpeg-h264-vlc-could-not-decode-the-format-aivx

For now you can go to help and then copy the last run command to you terminal and add these arguments before running again.

**Comment by mifi** [comment]
After some more testing, it seems like we don't need to explicitly set `-tag:v avc1`, however `-strict -2` is what fixes the problem and allows ffmpeg to retain avc1 tag also in the output.

**Comment by ktully** [comment]
Thank you, I checked out the code yesterday ready to fix this and came here to post the same conclusion!
