### ISSUE TITLE
Some frames of cut off part are present in merged version

### ISSUE THREAD

**Issue by islamaliev** [mifi/lossless-cut#281]
I wanted to cut off a part of a video from the middle and then merge. I precisely chose the frames (normal cuts) so that the middle part don't show up in the final version. I had to set end frame of the first cut 3 frames earlier to achieve this effect.

**Comment by mifi** [comment]
I'm not sure if I understand. Lossless cutting can not be precise, because it usually needs to happen around keyframes

**Comment by islamaliev** [comment]
but there is distinction between keyframe and normal cutting. I used normal one

**Comment by mifi** [comment]
Normal does not mean that it is necessarily exact. It may still lose some frames depending on the codec.

**Comment by misiektw** [comment]
Even if you cut on keyframes, with keyframe snap, exported file starts one frame earlier than it supposed to. You can sometimes see this also when trying to use previous/next keyframe. Next is working always OK, but previos sometimes rewinds one more than it supposed to.

**Comment by mifi** [comment]
I have now added a message making it more clear that cuts are not accurate, and that you may need to move a few frames before. I experimented alot with this and the behavior is very inconsistent (e.g. if you need 3 frames, 2 frames or exactly the keyframe). It seems to vary from keyframe to keyframe and codec to codec. So I cannot easily program it in.

> Also, it seems that playback does not update keyframe index. So if you snap to keyframe and let it play for a while, then pressing snap to previous/next keyframe references to last keyframe you snapped to, not current playhead/cursor position.

Thanks for reporting this bug. I will fix it.
