### ISSUE TITLE
MTS file not working

### ISSUE THREAD

**Issue by forart** [mifi/lossless-cut#282]
This is a great tool, but seems tha MTS files are not supported/buggy.

I do also tried to cut the remuxed MKV but the files slowsdown when playing.

Tested with this file: https://clicknupload.co/0ooaljx1oqi1

Thanks in advance.

**Comment by mifi** [comment]
Seems like ffmpeg has trouble with MPEGTS files sometimes. Will have to research more
- https://video.stackexchange.com/questions/12156/how-can-i-convert-mts-file-avchd-to-mp4-by-ffmpeg-without-re-encoding-h264-v

**Comment by mifi** [comment]
Just doing a simple `ffmpeg -i ~/Desktop/test.mts -c copy ~/Desktop/test.mp4` causes a corrupted output (not seekable). Even mkv.

**Comment by mifi** [comment]
possibly related to #338

**Comment by mifi** [comment]
I've created a new overview issue for MPEG TS related problems: #1839 - I will close this issue because there isn't any obvious actionable solution.
