### ISSUE TITLE
language

### ISSUE THREAD

**Issue by ShaDow-7** [mifi/lossless-cut#29]
..Would  like to ask if the interface can be changed in other languages? If it can be set to Chinese?

**Comment by ShaDow-7** [comment]
If it can be set to Chinese?

**Comment by mifi** [comment]
Hi. There is currently no language support. Feel free to contribute.

**Comment by EMLVIRUS** [comment]
@mifi I think the point is that you should implement at your side first, aka split out all strings into a single file so that someone else can translate it.

**Comment by wikijm** [comment]
@mifi If needed, I'm available to make a French translation.

**Comment by jose1711** [comment]
just curious.. if there's no language support what are .pak files inside locales directory good for?

**Comment by TechManiacHD** [comment]
If you guys want I can contribute Polish translation.

**Comment by bvillar** [comment]
I can contribute with Portuguese (Brazil) translation.

**Comment by fletin** [comment]
I can contribute with Chinese Translation.

**Comment by causztic** [comment]
Hi @mifi! i'm interested in adding language support for this project, do you see the need for an extensive library like `polygot` or would a simple key-value lookup suffice?

**Comment by CHN-STUDENT** [comment]
hope add muti-language support, perhaps i can contribute for it. Thanks!

**Comment by irmatade** [comment]
I can contribute with the Italian translation.

**Comment by mifi** [comment]
I'm thinking about using this:

https://github.com/i18next/react-i18next

And as a translation service I found these that provide a free version for open source projects:
- https://www.transifex.com/pricing/
- https://poeditor.com/pricing/
- https://crowdin.com/page/open-source-project-setup-request

I have only used poeditor before and it seemed ok.

See also:
- https://alternativeto.net/software/po-editor/

**Comment by trebmuh** [comment]
Hi all, as lossless-cut is a free software, I'd recommend to use another free software for translation. https://hosted.weblate.org/ come to mind. I use it for several other projects, and it works great.

If there, I would be happy to help with the French translation.

**Comment by mifi** [comment]
I have now implemented support for i18n. The following is remaining:

- [] i18n menus and electron.js code
- [] proper interpolation, keys and pluralization, use Trans component
- [] Some text in Settings and App not yet i18n
- [] integrate with weblate (i have sent a request for open source hosted weblate, waiting for answer)

**Comment by mifi** [comment]
In case weblate does not answer in a timely manner, does anyone have any preferences or recommendations for transifex , crowdin or poeditor? Put a like on the one you prefer

**Comment by mifi** [comment]
Transifex

**Comment by mifi** [comment]
Crowdin

**Comment by mifi** [comment]
POEditor

**Comment by mifi** [comment]
weblate didnt reply yet but poeditor replied in 3 minutes so i think i'll try to go with poeditor

**Comment by mifi** [comment]
I have now created a Weblate hosted project for LosslessCut. I think how it works is that anyone can translate the text.

I have created the common requested languages
```
Chinese (Simplified)
French
Norwegian
Polish
Portuguese
Russian
```

English is the base language. Note that the english string is the base key (gettext style), so whenever I change any original text, it will flag everything for re-translation for that key.

Go here to translate :)
https://hosted.weblate.org/projects/losslesscut/losslesscut/

**Comment by trebmuh** [comment]
Nice !
I've done 3 strings translations to check if everything is correctly set up.
I'll wait for these to appear here and then, will keep on translating.

**Comment by mifi** [comment]
Wow Chinese is already done! I will add support for it now

**Comment by mifi** [comment]
Chinese can now be enabled from the settings! Will be available in the next version (3.22.0) when it completes building

**Comment by mifi** [comment]
We can continue here: #346

**Comment by CHN-STUDENT** [comment]
@mifi hi mifi i downloaded the lastest version and i set Chinese as its language. And i find the menu bar is not translated and some translate is not correct. Could you tell me how to improve it? Thanks!

**Comment by mifi** [comment]
You're right. The menu is not yet translated because it is a separate code, and a TODO. See #346

If you want to improve translations I think you can do it here: https://hosted.weblate.org/projects/losslesscut/losslesscut/

Also if you want to write a chinese guide or make a video, I'm happy to add it to the readme!

**Comment by CHN-STUDENT** [comment]
@mifi hi mifi,a good news is i think i know how to use this software, and now i am trying write Chinese guide book and improve Chinese translate, but i do not know some English means like `File exists, bailing`, what bailling means?

**Comment by mifi** [comment]
Cool! `File exists, bailing` means that you tried to save a file but it already exists, so LosslessCut refuses to overwrite the existing file.

`Mouse scroll/wheel left/right` I think some mouses have horizontal scrolling, no? Like Apple magic mouse, as well as TrackPads usually have vertical and horizontal scroll.

> `These options will let you convert files to a format that is supported by the player. You can try different options and see which works with your file. Note that the conversion is for preview only. When you run an export, the output will still be lossless with full quality` ,i guess some video format can convert but not can play in lossless by ffmpeg,so user need to convert it to play format?

Yes this is only to play back for preview. It will not affect the lossless final export.
