### ISSUE TITLE
EXDEV: cross-device link not permitted

### ISSUE THREAD

**Issue by mifi** [mifi/lossless-cut#292]
MS Store version crashes

![78456447-004d4700-76a4-11ea-83fc-3d13ab5d6cb7](https://user-images.githubusercontent.com/402547/78456639-67382380-76d7-11ea-88e4-2594d435cf47.png)

**Comment by mifi** [comment]
@erpy did this happen the first time you opened the app? Does it happen every time you start the app?

**Comment by mifi** [comment]
Also, the red blocks you removed, does it contain the same drive (from `F:` to `F:`)?

**Comment by erpy** [comment]
> Also, the red blocks you removed, does it contain the same drive (from `F:` to `F:`)?

Yes, same drive!
BTW, It started like that... first launch. Run as Admin makes no diff.

**Comment by mifi** [comment]
OK, I'm sorry for this bad first experience. I've never seen this error before. I shall get a fix released as soon as I can.

**Comment by erpy** [comment]
> OK, I'm sorry for this bad first experience. I've never seen this error before. I shall get a fix released as soon as I can.

Thanks, that's ok!
I appreciate the support!

**Comment by mifi** [comment]
Is there any particular about your setup? Are you running Windows 10 in "S mode"? Is your `AppData/Roaming` from LosslessCut stored in drive `F:` also? Is drive `F:` a normal local hard drive?

**Comment by erpy** [comment]
> Is there any particular about your setup? Are you running Windows 10 in "S mode"? Is your `AppData/Roaming` from LosslessCut stored in drive `F:` also? Is drive `F:` a normal local hard drive?

I'm running Win10 Pro. I checked my settings, and looking at the errors it might be the default location. My WindowsApps are in F. So anything installed from the Store app goes there. While the path under red square is C drive.
I hope this helps, thanks!

**Comment by mifi** [comment]
Building new version with workaround now

**Comment by mifi** [comment]
I am not able to reproduce your issue though. Maybe there is a bug in Windows causing this. Anyhow the workaround *should* solve it. Will release to the store asap

**Comment by erpy** [comment]
> I am not able to reproduce your issue though. Maybe there is a bug in Windows causing this. Anyhow the workaround _should_ solve it. Will release to the store asap

Cool! I will have a go as soon as it's available to update.

**Comment by mifi** [comment]
Actually I released a couple of hours ago, so it might be available now, or very soon

**Comment by erpy** [comment]
> Actually I released a couple of hours ago, so it might be available now, or very soon

You're right! And... you fixed it! 

![image](https://user-images.githubusercontent.com/734976/78498538-1cf08a00-774b-11ea-83c6-eb5f4526eebd.png)

**Comment by mifi** [comment]
phew! thank goodness! hope you won't encounter any more troubles
