### ISSUE TITLE
Keep getting error when I try to export

### ISSUE THREAD

**Issue by hreevesofficial** [mifi/lossless-cut#293]
I keep trying to export my clips, but it won't work. Every time I try, I get "Whoops! ffmpeg was unable to export this video. Try one of the following before exporting again:
1. Select a different output format from the mp4 button (matroska takes almost everything).
2. Exclude unnecessary tracks
3. Try 'Normal cut' and 'Keyframe cut'".
I've tried mp4 (original), mov, and mpeg, but none of them work. I didn't know if it would help, but I installed ffmpeg on my PC, but nothing happened.

**Comment by mifi** [comment]
Does it work with matroska (mkv)? What kind of file are you trying to cut? How many streams?

**Comment by shedali** [comment]
I've had the same issue - turns out it was happening because the working directory was unset. After setting it the error goes away. The error message in such a case may therefore be misleading.

**Comment by mifi** [comment]
@shedali which version are you running? If it's App Store variant, then there was a bug in the first versions related to working directory which should be fixed now. Try to upgrade to newest version

**Comment by hreevesofficial** [comment]
@mifi @shedali I had a working directory set, so I almost gave up. Then I realized that my mp4 was in the F:// drive instead of the C:// drive which is where Lossless Cut is. Apparently, it doesn't work unless the file is in the same drive. I moved my mp4 and it worked, except it didn't really. Everything exported, but the second clip and so on was not aligned with the audio and not where I started the clip. Every clip got worse and worse. Any fixes?

**Comment by mifi** [comment]
@hreevesofficial could you open dev tools and see if there is any error when you're cutting?

**Comment by mifi** [comment]
Have now improved error handling in the newest version. If you can try the latest pre-release version `v3.18.0` then it's easier for you to send me the errors.

**Comment by shedali** [comment]
@mifi thanks - the version I was using was via brew cask, version `3.17.9`, which I updated to before posting. I'll check out v3.18.0 update and let you know

**Comment by shedali** [comment]
looks good in `v3.18.0`. Set working directory to a folder which I then deleted. Error now says 'failed to save project file'. @hreevesofficial Also confirm that it works when file or working directory is in a different file system on (using Mac OS X)

**Comment by mifi** [comment]
@shedali  Ok, so the problem was that you had set a working directory to a folder that had later been deleted? And is the problem gone in 3.18.0? When loading a new file the program will now first check if the working dir exists, and if not will reset it. If you delete the working directory while a file is open, then it will generate errors like "failed to save project file".

**Comment by shedali** [comment]
@mifi my original unset working directory problem was fixed in 3.18.0. In order to test the fix I set a working directory and then deleted it to confirm it works. Works great thanks!

**Comment by mifi** [comment]
Thanks!

**Comment by mifi** [comment]
@hreevesofficial do you still have issues with the newest version?

**Comment by caramdache** [comment]
I had the same issue ("Whoops! ffmpeg was unable to export this video. Try one of the following before exporting again."). It turned out my Mac was running low on disk space...

Maybe something to warn about instead?

**Comment by mifi** [comment]
Yup, I will try to get that implemented.

**Comment by mifi** [comment]
Created an issue for that #328
