### ISSUE TITLE
Pre-render all files in dir as 'Convert to friendly codec (slowest)'

### ISSUE THREAD

**Issue by peterhighgrove** [mifi/lossless-cut#295]
I'm using LC to cut out even smaller cuts (5-10 sec) from a lot of small videos (30-45 sec) created with a GoPro and hevc codec. To be able to do the cuts correctly, I need to first convert them using the menu choice Convert to friendly codec (slowest).
I would like to do this more efficiently.
Can anyone help me with a ffmpeg command to be used at a windows10 command line that converts all mp4's in a folder in such a way that LC can use it later?

**Comment by mifi** [comment]
I have implemented a batch function now. Try latest pre-release version when it appears (tools menu -> Batch convert)

**Comment by peterhighgrove** [comment]
Thanks. It's great. Is there a limitation on how many files I can select?

**Comment by mifi** [comment]
Don't think so. Depends on whether your operating system's Open dialog has any limit
