### ISSUE TITLE
update ffmpeg-static

### ISSUE THREAD

**Issue by muelli** [mifi/lossless-cut#296]
ffmpeg-static may have added support for installing the package while being offline
https://github.com/eugeneware/ffmpeg-static/issues/37

This is needed for, e.g. packaging the on Flathub.
Could you update the dependency? It seems that currently 4.0.1 is used while the latest package is 4.1.0.

**Comment by mifi** [comment]
Sure

**Comment by muelli** [comment]
cool, thanks.
Can you update again? 4.1.0 seems to have had some issues and 4.1.1 might work better.

**Comment by mifi** [comment]
What kind of issues? Have you tested with the newest ffmpeg?

**Comment by muelli** [comment]
cf. https://github.com/eugeneware/ffmpeg-static/issues/37
It's about installing the package in an offline environment.

**Comment by mifi** [comment]
have upgraded to 4.2.0

**Comment by muelli** [comment]
cool. thanks.
can you update once again? -.-
4.2.1 may fix it for good.

**Comment by mifi** [comment]
done
