### ISSUE TITLE
convert friendly format (fastest / fast) without audio

### ISSUE THREAD

**Issue by taozi1996** [mifi/lossless-cut#297]
Convert friendly format (fastest / fast) can copy video stream,but cannot keep audio stream.
Such I have a 'input.ts' that its video is 'H.264' and audio is 'AAC',I can use 'ffmpeg -i input.ts -vcodec copy -acodec copy -f mp4 output.mp4 and 'losslesscut' can support output.mp4.
I hope 'convert friendly format fastest' can also keep and copy audio stream.

**Comment by mifi** [comment]
This one is now implemented. try pre-release version `v3.18.0`
