### ISSUE TITLE
Delete file not working if trash is not enabled

### ISSUE THREAD

**Issue by Marte2007** [mifi/lossless-cut#298]
If I try to delete the source file from a drive which does not have the trash enabled, the operation fails with this error in a balloon:
`Failed to trash source file: Command failed: C:\Users\username\AppData\Local\Temp\0211a381-0598-4397-afd6-576e0c0378f2.tmp.exe`
No error appears in the developer console, and it works fine if I do the same on a drive with the trash enabled. It also didn't happen with an old version from about a year ago.
Maybe you can add an option to delete the file directly instead of trashing? Or do that automatically if the drive does not support it?

**Comment by mifi** [comment]
I have now implemented a dialog that asks for permanent delete if trash fails
