### ISSUE TITLE
The last digit of both start point and end point are hidden

### ISSUE THREAD

**Issue by vrbandwagon** [mifi/lossless-cut#301]
The last digit of both start point and end point are hidden. This makes it confusing. For a while, I tried to manually enter my starting point, to no avail. I finally discovered that by pressing the right arrow key, there was a third digit to the frame number.

Also, maybe the area should automatically "trim" the number to avoid having two sets of numbers if someone copy-pastes one.

**Comment by mifi** [comment]
Can you provide a screenshot? Maybe something with the font

**Comment by vrbandwagon** [comment]
Sure.
https://imgur.com/a/JXIGL61

**Comment by mifi** [comment]
Thanks. Yea it seems most text is too big. Will have to look into that. Have you changed your system font?

**Comment by vrbandwagon** [comment]
I haven't. I also checked to see if I had changed the size in the display properties of Windows, and it is still at 100%. I tried 150% for fun, and everything adjusts correctly (and I still cannot see the third digit of course).

**Comment by vrbandwagon** [comment]
Update: I can see the three digits properly on Linux Mint. So it is definitely a Windows 10 issue.

**Comment by mifi** [comment]
Yea I will include a font so the text size will be consistent on all platforms

**Comment by mifi** [comment]
I have now included a consistent font and  I also added your paste suggestions. You can try pre-release version `v3.18.0`  or wait until it gets released to the stores
