### ISSUE TITLE
Mac App Store version: "delete source file" button is not working

### ISSUE THREAD

**Issue by Wildplaces** [mifi/lossless-cut#303]
I just installed LosslessCut on macOS Catalina 10.15.4. (directly from the app store).
It works great. Just the button 'delete source file' is not working. I get always the following message: 'Failed to trash source file: spawn EPERM'

Any ideas about how to solve this problem?

Thanks
Boris

**Comment by mifi** [comment]
Thanks for reporting! You are right, there was a bug there for the App Store version, because of App Store apps having more strict security. I have fixed this now so it will be included in the next version.

**Comment by Yashimaru-snm** [comment]
Hello, it also happens in windows 7 x64, and if you want to delete it from the explorer it is blocked by the program. In version 2.4.0 it does not happen, but in the following ones it does. I must close the program to delete the file and open it again to cut another video and it does not save the size and position of the window. Thank you.
Greetings.

**Comment by mifi** [comment]
@Yashimaru-snm I think your issue is this one #272 am i right?

**Comment by Wildplaces** [comment]
> Thanks for reporting! You are right, there was a bug there for the App Store version, because of App Store apps having more strict security. I have fixed this now so it will be included in the next version.

Thanks! I'll wait for the update in the App Store.

**Comment by Yashimaru-snm** [comment]
> @Yashimaru-snm I think your issue is this one #272 am i right?

That's right, the weird thing is that it doesn't always happen, when several videos are cut it always blocks it. Sometimes with the first video, but when exporting segments only.

**Comment by mifi** [comment]
I have tested with the newest app store version and now it works.

**Comment by Wildplaces** [comment]
I've also tested it today and can firm that it works now. Thanks!
