### ISSUE TITLE
Are there any files that I should be keeping from older versions?

### ISSUE THREAD

**Issue by KevinYork** [mifi/lossless-cut#305]
label:"help wanted" 
I have the current version of LossLessCut and a version from one year ago. [1 file vs. 119 files]
Is there anything from the previous version I should be keeping?
(sorry for the dumb question)
===============================
04/10/2020  93,079,200 LosslessCut-win.exe
---------- versus ---------------
01/28/2019      19,256 api-ms-win-core-console-l1-1-0.dll
01/28/2019      18,744 api-ms-win-core-datetime-l1-1-0.dll
01/28/2019      18,744 api-ms-win-core-debug-l1-1-0.dll
01/28/2019      18,744 api-ms-win-core-errorhandling-l1-1-0.dll
01/28/2019      22,328 api-ms-win-core-file-l1-1-0.dll
01/28/2019      18,744 api-ms-win-core-file-l1-2-0.dll
01/28/2019      18,744 api-ms-win-core-file-l2-1-0.dll
01/28/2019      18,744 api-ms-win-core-handle-l1-1-0.dll
01/28/2019      19,256 api-ms-win-core-heap-l1-1-0.dll
01/28/2019      18,744 api-ms-win-core-interlocked-l1-1-0.dll
01/28/2019      19,256 api-ms-win-core-libraryloader-l1-1-0.dll
01/28/2019      21,304 api-ms-win-core-localization-l1-2-0.dll
01/28/2019      19,256 api-ms-win-core-memory-l1-1-0.dll
01/28/2019      18,744 api-ms-win-core-namedpipe-l1-1-0.dll
01/28/2019      19,768 api-ms-win-core-processenvironment-l1-1-0.dll
01/28/2019      20,792 api-ms-win-core-processthreads-l1-1-0.dll
01/28/2019      19,256 api-ms-win-core-processthreads-l1-1-1.dll
01/28/2019      18,232 api-ms-win-core-profile-l1-1-0.dll
01/28/2019      19,256 api-ms-win-core-rtlsupport-l1-1-0.dll
01/28/2019      18,744 api-ms-win-core-string-l1-1-0.dll
01/28/2019      20,792 api-ms-win-core-synch-l1-1-0.dll
01/28/2019      19,256 api-ms-win-core-synch-l1-2-0.dll
01/28/2019      19,768 api-ms-win-core-sysinfo-l1-1-0.dll
01/28/2019      18,744 api-ms-win-core-timezone-l1-1-0.dll
01/28/2019      17,856 api-ms-win-core-util-l1-1-0.dll
01/28/2019      19,768 api-ms-win-crt-conio-l1-1-0.dll
01/28/2019      22,840 api-ms-win-crt-convert-l1-1-0.dll
01/28/2019      19,256 api-ms-win-crt-environment-l1-1-0.dll
01/28/2019      20,792 api-ms-win-crt-filesystem-l1-1-0.dll
01/28/2019      19,768 api-ms-win-crt-heap-l1-1-0.dll
01/28/2019      19,256 api-ms-win-crt-locale-l1-1-0.dll
01/28/2019      27,064 api-ms-win-crt-math-l1-1-0.dll
01/28/2019      26,936 api-ms-win-crt-multibyte-l1-1-0.dll
01/28/2019      71,480 api-ms-win-crt-private-l1-1-0.dll
01/28/2019      19,768 api-ms-win-crt-process-l1-1-0.dll
01/28/2019      22,464 api-ms-win-crt-runtime-l1-1-0.dll
01/28/2019      24,888 api-ms-win-crt-stdio-l1-1-0.dll
01/28/2019      24,888 api-ms-win-crt-string-l1-1-0.dll
01/28/2019      21,304 api-ms-win-crt-time-l1-1-0.dll
01/28/2019      19,256 api-ms-win-crt-utility-l1-1-0.dll
01/28/2019      26,693 blink_image_resources_200_percent.pak
01/28/2019          15 content_resources_200_percent.pak
01/28/2019   8,682,599 content_shell.pak
01/28/2019   4,173,928 d3dcompiler_47.dll
01/28/2019   1,955,328 ffmpeg.dll
01/28/2019  10,197,040 icudtl.dat
01/28/2019      17,920 libEGL.dll
01/28/2019   3,687,936 libGLESv2.dll
01/28/2019       1,060 LICENSE
01/28/2019   1,811,569 LICENSES.chromium.html
01/28/2019  67,911,168 LosslessCut.exe
01/28/2019     633,152 msvcp140.dll
01/28/2019     221,973 natives_blob.bin
01/28/2019  17,863,680 node.dll
01/28/2019     164,181 pdf_viewer_resources.pak
01/28/2019   1,530,996 snapshot_blob.bin
01/28/2019   1,001,272 ucrtbase.dll
01/28/2019       76,888 ui_resources_200_percent.pak
01/28/2019       87,888 vcruntime140.dll
01/28/2019                6 version
01/28/2019       57,450 views_resources_200_percent.pak
01/28/2019      278,630 locales\*	[54 language files]
01/28/2019  20,035,316 resources\app.asar
01/28/2019       259,311 resources\electron.asar
01/28/2019  61,518,848 resources\app.asar.unpacked\ffmpeg\ffmpeg.exe
01/28/2019  61,428,736 resources\app.asar.unpacked\ffmpeg\ffprobe.exe
     Total Files Listed:        119 File(s)    264,486,383 bytes

**Comment by mifi** [comment]
Just try?

**Comment by KevinYork** [comment]
hmm,... ok
Obviously I already tried it (and it worked fine)... 
But that doesn't/didn't prove that I have tested all the possibilities, 
nor [since this is a portable install] that it will work as well under all versions of Windows OS.

**Comment by mifi** [comment]
Im not sure about you particular setup but in general the downloaded exe should contain all needed files. (The exe is in reality a zip and opens up upon execution

**Comment by mifi** [comment]
please create a new issue if u have any issues
