### ISSUE TITLE
Possibility to delete the files after the merge automatically.

### ISSUE THREAD

**Issue by Mioni** [mifi/lossless-cut#309]
It's possible?

**Comment by mifi** [comment]
You mean delete source files? There is a button and a shortcut for it. I don't want to do it automatically because it may be not something everyone wants. see #87

**Comment by Mioni** [comment]
![](https://i.imgur.com/JZcfswA.png)

I use this merge option a lot when he finished this merge the program automatically deleted these 3 files and left only the merge file, you know?

**Comment by mifi** [comment]
I'm not sure if I understand. Do you want the merge function to delete the 3 files after merging?

**Comment by Mioni** [comment]
Yes!

**Comment by mifi** [comment]
closing in favor of #600
