### ISSUE TITLE
Scrubbing the playhead via two-finger swiping behaves the wrong way around

### ISSUE THREAD

**Issue by tommit** [mifi/lossless-cut#310]
Using:
* macOS Catalina 10.15.4 (19E287)
* LosslessCut 3.17.32 (from Mac App Store)
* Magic Trackpad 2

Swiping with two fingers left or right over the trimming area moves the playhead forward or backward. But it behaves the wrong way around: swiping left moves playhead forward in time, and swiping right moves it backward.

In case it's relevant, this is my **System Preferences > Trackpad** setup:

![System Preferences - Trackpad - Scroll and Zoom](https://user-images.githubusercontent.com/7393895/79159394-aace1400-7de0-11ea-92e6-b831712615e8.png)
![System Preferences - Trackpad - More Gestures](https://user-images.githubusercontent.com/7393895/79159401-ad306e00-7de0-11ea-8f83-54fd157104ba.png)

**Comment by mifi** [comment]
You are right. I had mine set to Reverse, that's why. I consider this to be a bug and I shall fix this. Also adding a setting

**Comment by mifi** [comment]
Newest version is now inverted with a setting to invert back.
