### ISSUE TITLE
Pre-Release and Release questions

### ISSUE THREAD

**Issue by dmp1ce** [mifi/lossless-cut#311]
Why are some builds marked as Pre-Release?

I maintain the AUR package and I'm only updating the builds on Releases, not Pre-Releases. Will Pre-Releases eventually be marked as Release?

**Comment by mifi** [comment]
Pre-releases could be a bit unstable. Releases are more stable. I usually don't change pre-releases to release, but instead I create separate stable release versions. New Release version coming soon!
