### ISSUE TITLE
How to let LC remember last window size+pos?

### ISSUE THREAD

**Issue by pstein** [mifi/lossless-cut#314]
When I open LC, then resize + move the window and exit (later) LC again then the current window size and position is not remembered.

At next start LC window opens again in an initial (small) size.

How can I let LC remember this info?

Peter

**Comment by mifi** [comment]
See #44 
Please leave a 👍 there, and I will implement when I have time

**Comment by 100mph** [comment]
Please add this! I love this tool a lot and use it to trim many clips, the initial size of the window is quite small for me, hate to be that guy, but remembering window size can't be _too_ difficult right? 😜
