### ISSUE TITLE
How to show key frames? Search for next keyframe to set cutpoint?

### ISSUE THREAD

**Issue by pstein** [mifi/lossless-cut#315]
I open a MP4 video with H.264 video codec in LC.

In the lower left corner the tiny icon "show keyframes" is activated.

I wonder how the keyframes in current video are shown (as promised by the lower left icon)?
there are e.g. no vertical lines in the timeline.

Moreover in the upper right corner the button "keyframe cut" is activated.

Now lets say I jump to next frame (NOT keyframe!) somewhere in current video.

When I set now a start cutpoint the LC searches for an apprpriate keyframe since I activated "keyframe cut".
Does LC search for the next keyframe backward or forward to set the cutpoint?

Or does it depend which one is the nearest?

Peter

**Comment by mifi** [comment]
You need to zoom in to see the keyframes. I will add a notification about this.
Keyframe cut will cut at the nerest keyframe **before** the desired cutpoint. I will also add a clarification about this.

**Comment by mifi** [comment]
If zooming is not working, it couldbe the same issue as this #308

**Comment by mattack1** [comment]
> You need to zoom in to see the keyframes. I will add a notification about this.
> Keyframe cut will cut at the nerest keyframe **before** the desired cutpoint. I will also add a clarification about this.

Wouldn't it be closer to what the user expects if the *in* cut was the nearest keyframe before, and the out cut was the nearest keyframe AFTER?  That way, they always get _at least_ what they have selected..

**Comment by mifi** [comment]
I think for most video files, the *out cut* is indeed exact and does not need to be aligned with a keyframe.
