### ISSUE TITLE
Suggestion- Preview video play should be output video with applied rotation. Also request you to add Horizontal flip and Vertical Flip.

### ISSUE THREAD

**Issue by tarve** [mifi/lossless-cut#316]
If you have an issue with cutting a particular file, or an unexpected bug or crash, please open developer tools after starting LosslessCut and before doing the failing operation. Then share the output from the javascript console.

If you have an issue cutting a particular file, please also share the file, if possible. Also please try to cut it with the ffmpeg command line directly.

How to open developer tools:
- Windows: <kbd>F12</kbd> or <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>
- Mac: <kbd>Cmd</kbd>+<kbd>Opt</kbd>+<kbd>I</kbd>

**Comment by mifi** [comment]
Flipping is not possible.
Playing the output video with the applied rotation could be implemented

**Comment by mifi** [comment]
Rotation preview with playback is implemented and can be seen in the next version

**Comment by tarve** [comment]
thanks a lot
