### ISSUE TITLE
Audio sync in MP4 clip export

### ISSUE THREAD

**Issue by pnicolette** [mifi/lossless-cut#317]
Thanks for creating and continuing to enhance Lossless Cut!  

Your UI w/tooltips and green/gray in Win is outstanding.

As a noob editing an MP4 (2 sec keyframes), I felt frustrated when I marked a clip to start between keyframes and the audio in the export lost sync. Keyframe or Normal cut made no difference. How do I avoid this?

If it is expected behavior, perhaps notify the user when they ignorantly choose a start frame that's likely to de-sync? Or default to disallowing it? Thanks for your thoughts.

My track metadata:
{
  "index": 0,
  "codec_name": "h264",
  "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
  "profile": "Main",
  "codec_type": "video",
  "codec_time_base": "1782933/106976000",
  "codec_tag_string": "avc1",
  "codec_tag": "0x31637661",
  "width": 576,
  "height": 360,
  "coded_width": 576,
  "coded_height": 368,
  "has_b_frames": 2,
  "pix_fmt": "yuv420p",
  "level": 30,
  "chroma_location": "left",
  "refs": 1,
  "is_avc": "true",
  "nal_length_size": "4",
  "r_frame_rate": "30/1",
  "avg_frame_rate": "53488000/1782933",
  "time_base": "1/16000",
  "start_pts": 0,
  "start_time": "0.000000",
  "duration_ts": 28526928,
  "duration": "1782.933000",
  "bit_rate": "200123",
  "bits_per_raw_sample": "8",
  "nb_frames": "53488",
  "disposition": {
    "default": 1,
    "dub": 0,
    "original": 0,
    "comment": 0,
    "lyrics": 0,
    "karaoke": 0,
    "forced": 0,
    "hearing_impaired": 0,
    "visual_impaired": 0,
    "clean_effects": 0,
    "attached_pic": 0,
    "timed_thumbnails": 0
  },
  "tags": {
    "language": "und",
    "handler_name": "VideoHandler"
  }
}

{
  "index": 1,
  "codec_name": "aac",
  "codec_long_name": "AAC (Advanced Audio Coding)",
  "profile": "HE-AAC",
  "codec_type": "audio",
  "codec_time_base": "1/48000",
  "codec_tag_string": "mp4a",
  "codec_tag": "0x6134706d",
  "sample_fmt": "fltp",
  "sample_rate": "48000",
  "channels": 2,
  "channel_layout": "stereo",
  "bits_per_sample": 0,
  "r_frame_rate": "0/0",
  "avg_frame_rate": "0/0",
  "time_base": "1/48000",
  "start_pts": 0,
  "start_time": "0.000000",
  "duration_ts": 85571568,
  "duration": "1782.741000",
  "bit_rate": "63999",
  "max_bit_rate": "64000",
  "nb_frames": "41783",
  "disposition": {
    "default": 1,
    "dub": 0,
    "original": 0,
    "comment": 0,
    "lyrics": 0,
    "karaoke": 0,
    "forced": 0,
    "hearing_impaired": 0,
    "visual_impaired": 0,
    "clean_effects": 0,
    "attached_pic": 0,
    "timed_thumbnails": 0
  },
  "tags": {
    "language": "und",
    "handler_name": "SoundHandler"
  }
}

**Comment by mifi** [comment]
Hi! Normally audio/video sync is kept even when setting cutpoint between keyframes, but if it’s not in in your case, then there could be something special about your file. Is it possible to share a small clip that can reproduce the issue?

I could look into changing it so that the UI snaps to keyframes if available

**Comment by grande90210** [comment]
Same problem. Latest version.

**Comment by mifi** [comment]
I improved the help text now

**Comment by mifi** [comment]
because i cannot reproduce this, and there is no response, i'm closing this
