### ISSUE TITLE
When "auto merge", write segment labels as chapters in output file

### ISSUE THREAD

**Issue by Yashimaru-snm** [mifi/lossless-cut#318]
Hi, it is possible to add the option of merge cuts with chapters by segment. Thanks

**Comment by mifi** [comment]
I'm not sure what you mean

**Comment by Yashimaru-snm** [comment]
In option "Auto merge segments to one file during export" ,add chapter mark by joined segment when multiplexing mkv or mp4.
![2020-04-24 19 58 19](https://user-images.githubusercontent.com/63490946/80263162-15474580-8666-11ea-86ac-07f3b1170ed9.png)
![2020-04-24 19 53 15](https://user-images.githubusercontent.com/63490946/80263038-bf729d80-8665-11ea-8acf-1fc7437425f6.png)
![2020-04-24 19 52 29](https://user-images.githubusercontent.com/63490946/80263041-c3062480-8665-11ea-9917-6668eb48fa7c.png)

**Comment by mifi** [comment]
Cool! I think it could be done something like this:

https://medium.com/@dathanbennett/adding-chapters-to-an-mp4-file-using-ffmpeg-5e43df269687

**Comment by Yashimaru-snm** [comment]
Yes it would be more comfortable without the need to use another tool. Thanks

**Comment by Yashimaru-snm** [comment]
Thanks for implementing it works great. Regards
