### ISSUE TITLE
(Request Enhancement)  Advanced scroll/skip options

### ISSUE THREAD

**Issue by NietGiftig** [mifi/lossless-cut#32]
Request
Scrolling with the mouse wheel at higher speed (speed parameter adjustable in seconds skipping)
or
Use arrow-keys in combination with shift/ctrl/alt for different speeds (speed parameter in seconds adjustable for each combination)

Both forwards and backwards

**Comment by mifi** [comment]
What's the most common way to do this in other editors?

**Comment by NietGiftig** [comment]
Most are like VLC

**Comment by mifi** [comment]
It seems like VLC is using these shortcuts:
```
Very short backwards jump	key-jump-extrashort	Shift-Left
Very short forward jump	key-jump+extrashort	Shift-Right
Short backwards jump	key-jump-short	Alt-Left
Short forward jump	key-jump+short	Alt-Right
Medium backwards jump	key-jump-medium	Ctrl-Left
Medium forward jump	key-jump+medium	Ctrl-Right
Long backwards jump	key-jump-long	Alt-Ctrl-Left
Long forward jump	key-jump+long	Alt-Ctrl-Right
```
However none of them seem to be working for me (on a mac)

**Comment by mifi** [comment]
Continue here: #254
