### ISSUE TITLE
No Audio When Previewing A Clip?

### ISSUE THREAD

**Issue by VonSupponnatime** [mifi/lossless-cut#322]
This has been happening to any MKV file I attempt to edit.  When I load the clip, and then hit play (so that I can get to the right spot), the video plays but there is no audio.  The final product (after an attempted guess) does have the audio in playback.

Has anyone else encountered this?

**Comment by mifi** [comment]
Do you see any popup saying something about unsupported file and a low quality preview?

**Comment by ipkpjersi** [comment]
This is happening for me too, with an MKV, no audio when previewing.

**Comment by ipkpjersi** [comment]
It turns out it's not all mkv videos, some mkv videos preview audio just fine, here is one that is fine:
![](https://i.imgur.com/sdLlqpl.png)
```json
{
  "index": 1,
  "codec_name": "aac",
  "codec_long_name": "AAC (Advanced Audio Coding)",
  "profile": "LC",
  "codec_type": "audio",
  "codec_time_base": "1/44100",
  "codec_tag_string": "[0][0][0][0]",
  "codec_tag": "0x0000",
  "sample_fmt": "fltp",
  "sample_rate": "44100",
  "channels": 2,
  "channel_layout": "stereo",
  "bits_per_sample": 0,
  "r_frame_rate": "0/0",
  "avg_frame_rate": "0/0",
  "time_base": "1/1000",
  "start_pts": 0,
  "start_time": "0.000000",
  "disposition": {
    "default": 1,
    "dub": 0,
    "original": 0,
    "comment": 0,
    "lyrics": 0,
    "karaoke": 0,
    "forced": 0,
    "hearing_impaired": 0,
    "visual_impaired": 0,
    "clean_effects": 0,
    "attached_pic": 0,
    "timed_thumbnails": 0
  },
  "tags": {
    "HANDLER_NAME": "ISO Media file produced by Google Inc.",
    "DURATION": "00:52:34.802000000"
  }
}
```

**Comment by mifi** [comment]
I think this is because LosslessCut cannot decode AC3. You can use the Convert to friendly format menu, and choose `slow: low quality encode`. then you will get a preview with audio but it's a bit slow. I'm working on a much faster low quality audio preview generating.

**Comment by mifi** [comment]
Fast audio preview has now been implemented and can be tested in the next release
