### ISSUE TITLE
About label(character encoding)

### ISSUE THREAD

**Issue by taozi1996** [mifi/lossless-cut#323]
Label can support English and number now,but If I use other languages to make label,the output character will be replaced by '_' .

**Comment by mifi** [comment]
Yea, this was because I don't want to get any error from the file system. Depending on whether it's FAT32, NTFS, MacOS or Linux file system, some characters may not be supported.

**Comment by dragongling** [comment]
> Yea, this was because I don't want to get any error from the file system. Depending on whether it's FAT32, NTFS, MacOS or Linux file system, some characters may not be supported.

Filtering characters unsupported by destination filesystem could be done on sanitization step

**Comment by mifi** [comment]
optimally yes, but there are so many different file systems (and OS combinations) out there that i'd rather not keep implementations for each one, in fear of making a mistake, causing unexpected errors for users. Instead there's the "no sanitize" mode that can be used when someone wants to be able to output any character.
