### ISSUE TITLE
fps change at export

### ISSUE THREAD

**Issue by ay3kay** [mifi/lossless-cut#324]
I started using this s/w just yesterday. Loved UI ,features all that stuff. i was genuinely happy with this s/w only till i encountered major error. I record my Game footage at 75 fps and i wanted it lossless so i went with this s/w. I chose the Export + merge option and at first glance i was satisfied with output but after watching for few more seconds i noticed hiccups at each 1 - 2 seconds in the video. then i saw the details of the file and it said 99 fps for some reason. I don't know if it can be fixed within the s/w itself or you guys will have to work on it. Anyway would love to hear about this back from you guys :D

**Comment by mifi** [comment]
Hi. Is it possible to provide a sample video to reproduce the problem? Same issue when you just export without merge?

**Comment by ay3kay** [comment]
Sure, I'll mail you both of them.

**Comment by ay3kay** [comment]
Oh sorry, the issue was on my end. i recently downgraded my vlc media player because it was giving me some screenshot capturing issue. I was recording my original sample that you asked for where i saw the same issue. I Upgraded back my VLC to Latest version and fps shift issue is fix. It was the Player which had issue and not Lossless Cut. Anyway Thanks for looking into this and keep up the good work. really loved the software.

**Comment by mifi** [comment]
Alright, thanks for reporting back. I will close this then:)
