### ISSUE TITLE
Trouble to cut the beginning from WEBM

### ISSUE THREAD

**Issue by VERSEAU44** [mifi/lossless-cut#325]
Hi,

I can't cut the beginning of a WEBM video (when only the end works !) : the original file (12MB) can be downloaded at https://we.tl/t-AmzYxYalvS

"Easiest Movie Editor" does this but is not as ergonomic
https://software-download.name/webm-video-cutter)

Could you help me ?
The log report is below

Thanks
Laurent
___________________________________________________

undefined

{
  "err": {},
  "state": {
    "filePath": "D:\\Users\\Laurent\\Videos\\Cyndi_Lauper-_-Girls_just_want_to_have_fun-Taratata-Live - Copie.webm",
    "fileFormat": "webm",
    "externalStreamFiles": [],
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "vp9",
        "codec_long_name": "Google VP9",
        "profile": "Profile 0",
        "codec_type": "video",
        "codec_time_base": "1/25",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "width": 1280,
        "height": 720,
        "coded_width": 1280,
        "coded_height": 720,
        "has_b_frames": 0,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": -99,
        "color_range": "tv",
        "refs": 1,
        "r_frame_rate": "25/1",
        "avg_frame_rate": "25/1",
        "time_base": "1/1000",
        "start_pts": 0,
        "start_time": "0.000000",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "ENCODER": "Lavc58.19.102 libvpx-vp9",
          "DURATION": "00:04:58.400000000"
        }
      },
      {
        "index": 1,
        "codec_name": "opus",
        "codec_long_name": "Opus (Opus Interactive Audio Codec)",
        "codec_type": "audio",
        "codec_time_base": "1/48000",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/1000",
        "start_pts": -7,
        "start_time": "-0.007000",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "eng",
          "DURATION": "00:04:58.421000000"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "D:\\Users\\Laurent\\Videos\\Cyndi_Lauper-_-Girls_just_want_to_have_fun-Taratata-Live - Copie.webm": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {
        "start": 58.886,
        "end": 288.68,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            335.69251468389825,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "be615755-a281-4a9e-8978-3c3eb70645de"
      }
    ],
    "fileFormatData": {
      "filename": "D:\\Users\\Laurent\\Videos\\Cyndi_Lauper-_-Girls_just_want_to_have_fun-Taratata-Live - Copie.webm",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "matroska,webm",
      "format_long_name": "Matroska / WebM",
      "start_time": "-0.007000",
      "duration": "298.421000",
      "size": "12565992",
      "bit_rate": "336866",
      "probe_score": 100,
      "tags": {
        "ENCODER": "Lavf58.16.100"
      }
    },
    "rotation": 360,
    "shortestFlag": false
  }
}

**Comment by mifi** [comment]
From what I can see, this video only has 1 (😮) keyframe, which is frame 1. Thereby it's not possible to cut anything else than the beginning... Interesting...

**Comment by VERSEAU44** [comment]
Hi mifi 😀
LossLess Cut has a "normal cut" mode wich could cut at frame I want (and not at keyframe), has not ? (How does "Easiest Movie Editor" manage to do it ?)
If not, how can I add / create a keyframe where I want to cut ?
Thanks for your help 👍

**Comment by mifi** [comment]
Hi!
No, normal cut is a bit confusing, but it does not necessarily mean that you can cut outside the keyframes.

I haven't tried Easiest Movie Editor, but I'm guessing it uses non-lossless cutting (re-encode)?
Unfortunately LosslessCut cannot create a keyframe anywhere. Maybe I'm misunderstanding something, maybe there is something I don't understand about the vp9 codec, but I cannot understand how it would be possible to cut this file after the first and only keyframe.

**Comment by VERSEAU44** [comment]
Hi mifi
Normal cut : yes, I've opened another thread because of its "empty portion" ;o)

"Easiest Movie Editor" : the interface offers a "cut video files without re-encoding" option (Cf. screenshot at https://zupimages.net/up/20/17/qhxf.jpg)
BUT with the problematic file with only 1 keyframe, the processing is not immediate (around 5s) : I have the impression that it re-encodes !

Do you know another soft than LosslessCut to create a keyframe without re-encoding ?

What is the "Set custom start offset / timecod" option for? Would it allow me to start the playback (with an external player) of the video at the offset that I specify (this would not play the beginning which is problematic, while keeping the original file) ?

Thanks for your help !

**Comment by mifi** [comment]
I'm not aware of any such software, no. If you need to create a keyframe, then by definition it will be a lossy operation because I think a keyframe is lossy encoded.

Custom offset is only for previewing. I will add a better description in the app

**Comment by VERSEAU44** [comment]
Thanks for all mifi 👍
