### ISSUE TITLE
When I want to merge sequences the result is longer than it should be

### ISSUE THREAD

**Issue by Mattulu** [mifi/lossless-cut#326]
Hi!
I need to merge about 150 sequences of a 10h video (the merged video is about 20 min long). So I selected them in LosslessCut. I press "merge files" and "keyframe cut" and then "export+merge". The cut version is longer than my 150 sequences should be (about 40 min). When i use "normal cut" instead of "keyframe cut" i have to wait hours. Ive never waited until the end because I dont have the time for that. What can I do to get the exact merged video? Ive downloaded the newest version.

Thanks for your help!!

**Comment by mifi** [comment]
Hi. normal cut vs keyframe cut shouldn't have any effect when only merging. Are you using the top menu -> Tools -> Merge files ? try to unselect the all streams options

**Comment by Mattulu** [comment]
I havent used the tools option yet. Should I try this? Since now I just pressed merge cuts near the "?"-button. 

What do you mean with stream options? (Sorry Im just a student without any computer-knowledge...) Thank you!!

**Comment by mifi** [comment]
No worries. Yes use the tools menu, then merge, then select all your files to merge.

**Comment by mifi** [comment]
NOTE: They have to be of the same format, codec and dimensions etc

**Comment by Mattulu** [comment]
Ah okay, when i try this I have to select video files in my folder. So first I have to separate my 10 h video sequences, which I marked before and after that I have to merge them with the tools-option? 

The merge function I used before (the button near the (?)) was without separating first.

**Comment by mifi** [comment]
Oh I misunderstood. I thought you have 120 separate files you want to merge. You want to make 120 cuts in one file and then merge them, right? Im not sure what’s happening here. If you export as separate files, are they also too long? Also check if there are any extra tracks from the Tracks panel and try to disable any other tracks than thevideo.

**Comment by Mattulu** [comment]
When use this option (see the screenshot) and export I get 133 video files. Unfortunately each of them is also longer, than it should be. Video number 132 should be 4.3 sec long. The exported file is 7 sec long. So merging them with the tools-option doesnt solve my problem. 
![Screenshot 2020-04-25 09 22 55](https://user-images.githubusercontent.com/64265948/80273912-b4a42100-86d6-11ea-8ee5-5c10959bd2b0.png)

**Comment by mifi** [comment]
Yea. The problem is that lossless cutting can never be accurate. So depending on the video codec and keyframes, there may be up to many seconds offset fro mthe desired cut point. You can use the keyframe view and zoom in to get an indication of where the cuts will happen

**Comment by Mattulu** [comment]
Okay thank you! Can I be sure that nothing of the selected sequences is missed in the merged version? So it is just longer because the cut-points arent correct but the marked sequences are included?

**Comment by mifi** [comment]
This will all depend on format, codec etc because I don't know the exact inner workings of ffmpeg in every case, but from my experience, when using keyframe cut, the contents of the segments will always be included (with some extra padding added)
