### ISSUE TITLE
Normal cut and its "empty portion"

### ISSUE THREAD

**Issue by VERSEAU44** [mifi/lossless-cut#327]
Hi
"Normal cut" mode normally cuts to the exact position but "could leave an empty portion at the beginning of the video"
This is exactly the result I get but the "empty portion" is actually filled with a few miliseconds frames before my exact position ...
Could this "empty portion" be filled with black frames ?
Thanks

**Comment by mifi** [comment]
I think what is shown will depend on the player used to play back, so not in our control.

**Comment by VERSEAU44** [comment]
Hi mifi
Sorry to insist but I would like to understand better ...
The few frames added before the cut position come from the original video
In "Normal cut" mode, could LossLessCut know the added frames and replace them with black frames ?

**Comment by mifi** [comment]
I’m not sure I understand what you mean by « The few frames added before the cut position come from the original video». Can you provide an example?

**Comment by VERSEAU44** [comment]
Hi mifi

You can download 3 example movies at : https://we.tl/t-YD1DYeKbB3

Normal Cut at : 00.01.10.040-00.07.03.040
BUT 00.01.10.040 is NOT a keyframe : the previous is at 00:01:09.447  and   the next one is at 00:01:14.407

AviDemux (http://avidemux.sourceforge.net) cuts at the previous keyframe (00:01:09.447) : great because the whole part of the video I want is there but AviDemux keeps the frames between the start of the keyframe and the timecode of the cut (rather than replacing them with black keyframes)

LossLessCut cuts at the next keyframe (00:01:14.407) : quite bad because I lose the start of the portion of video I wanted

Question : could LossLessCut start at the previous keyframe (rather than the next) but replacing the frames before the cut position with black frames ?

NB : Sorry for my mixing error but it's been 3 days that I try full of combinations with several softwares to find the one that can meet my needs but, often, I do not get what I want ...

**Comment by mifi** [comment]
Yeah, normal cut is not really recommended. With keyframe cut you should get similar results as avidemux

**Comment by VERSEAU44** [comment]
Hi mifi
You're right 👍
I guess replacing the frames between previous keyframe ant cut position (in Normal Cut mode) with black frames is not possible from LossLessCut because it does not edit movies ?

**Comment by mifi** [comment]
Not as of now, but maybe it could be possible if we implement this: #255

**Comment by VERSEAU44** [comment]
OK : it would work with "normal" movies
But for mines (with keyframe placed on "bad pictures") ... it'll not replace the frames I do not want but add pause between segments (so I'll keep my segment with bad and good pictures within)
It's still a good improvement !

**Comment by mifi** [comment]
Closing this. please let me know if youre still having issues
