### ISSUE TITLE
Handle low disk space

### ISSUE THREAD

**Issue by mifi** [mifi/lossless-cut#328]
currently gives 'Whoops! ffmpeg was unable to export this video. Try one of the following before exporting again.'

Give a better error and remove garbage files.

**Comment by mifi** [comment]
Problem is that ffmpeg just returns code 1 when no disk space.

**Comment by mifi** [comment]
Ok I added a hack to detect out of space.

**Comment by Shakil-Shahadat** [comment]
This issue can be closed now.
