### ISSUE TITLE
MP4 tag information lost after output

### ISSUE THREAD

**Issue by V-Toll** [mifi/lossless-cut#33]
Hey! Thanks for the great app. I love the minimalistic design and the overall speed.
I just have a problem with some lost tag information in mp4 files. Thinks like cover, publisher, etc. get lost after cutting a mp4 file.

Here you see the original tag information in the mp4 file, created via MusicBrainz Picard:
![1](https://cloud.githubusercontent.com/assets/7504584/25972197/4a3f5c10-369f-11e7-99f8-597c9375fd5a.png)

And after putting it through LosslessCut the following happens:
![2](https://cloud.githubusercontent.com/assets/7504584/25972198/4a632816-369f-11e7-93e9-cf2eeabfff28.png)

I didn't test ist with any other video file formats.
I hope this get's fixed sometime in the near feature. Thanks!

**Comment by mifi** [comment]
LosslessCut offloads all this conversion to ffmpeg, so we need to figure out how to make ffmpeg do this. Seems like ffmpeg has an option -map_metadata
If you can try with ffmpeg and confirm this works, then I could add an option for preserving metadata. (maybe not safe to do it by default)

**Comment by V-Toll** [comment]
Hey, this seems to work for me. Any chance of getting this function as an additional option?

**Comment by mifi** [comment]
What do you mean works for you? where does it work for you?

**Comment by V-Toll** [comment]
Sorry, it's been a while ;-)

I tried the -map_metadata option with ffmpeg and all metadata was saved.

**Comment by mifi** [comment]
Which arguments are you using for `-map_metadata`?

Looking at ffmpeg docs, it seems that global metadata is copied by default. is not MP4 tag information global metadata?

> By default, global metadata is copied from the first input file, per-stream and per-chapter metadata is copied along with streams/chapters. These default mappings are disabled by creating any mapping of the relevant type. A negative file index can be used to create a dummy mapping that just disables automatic copying.

**Comment by mifi** [comment]
I have added `-map_metadata 0` and it seems to be working. 61a13ceabed14dc7314a33a5b7726b2b51b6d5ec
