### ISSUE TITLE
How to add Chinese language 怎样添加中文语言

### ISSUE THREAD

**Issue by FanXiangTM** [mifi/lossless-cut#332]
How to add Chinese language 怎样添加中文语言

**Comment by hooke007** [comment]
https://github.com/mifi/lossless-cut/issues/245#issuecomment-584667954

**Comment by mifi** [comment]
See #29

Go here to translate :)
https://hosted.weblate.org/projects/losslesscut/losslesscut/

**Comment by hooke007** [comment]
I have translated, you may have a try.

**Comment by CHN-STUDENT** [comment]
Thank you! :)

**Comment by mifi** [comment]
Awesome job! So fast! Chinese can now be enabled from the settings! Will be available in the next version (3.22.0) when it completes building

**Comment by hooke007** [comment]
:-) Hoping that it will help more rookies to use this tool！

**Comment by CHN-STUDENT** [comment]
@hooke007 有些地方翻译的不是很准确
我提出了一些修改建议。
另外有一些部分需要改
Drop file 拖放文件到此处
Rotation preview 旋转预览
还有一些部分需要等作者确认如何翻译。
