### ISSUE TITLE
Lock Rotation and shortcut for rotation

### ISSUE THREAD

**Issue by tarve** [mifi/lossless-cut#334]
Suggestion :
1. Could you please introduce to  Lock Rotation per session. 
2. Please add shortcut Key for Rotation
3. Rotated preview is blurry , million thanks for adding.

regards,

**Comment by mifi** [comment]
Hi.

1. I'm not sure if I understand. Do you want to apply the same rotation for a lot of videos?
2. Why do you need it? If more people want this I can add
3. I have implemented an option to cancel the preview.

**Comment by tarve** [comment]
1. Case :- While rotating multiple file with 180,90 degree rotation, for every file I have to change the rotation. so if rotation is locked. It will save time and I can  convert more files.
2. I got many file wrong rotation due to mobile recorded videos. It's practical problem for mobile recorded videos.
3. Thanks for the preview option but I request you to consider adding shortcut key for rotation.

regards,

Sachin

**Comment by mifi** [comment]
Do you need a shortcut if rotation is being remembered? See #371

**Comment by tarve** [comment]
Yes. It is required . I'll be very thankful if you add.

**Comment by tarve** [comment]
Hope you are doing well. Long time no updates.

**Comment by mifi** [comment]
I'm good. Just busy!
Closing this in favor of #254 and #371
