### ISSUE TITLE
Focus editor window on file drop

### ISSUE THREAD

**Issue by HugoHeneault** [mifi/lossless-cut#335]
I'm editing my video on macOS (quite impressed by the new update, I came from 2.x and wow! Well done), and my current flow would be improved if the window was focused on file drop instead of keeping the finder focus (maybe it's not possible?)

1. Drop a video on the LosslessCut editor
2. Press space to start playing the video
3. System preview opens instead of playing inside the editor (because finder is still focused)

![Kapture 2020-05-01 at 13 03 32](https://user-images.githubusercontent.com/4112256/80801307-33ec9580-8bac-11ea-9176-f313b911fc2d.gif)

If the editor could get the focus on file drop it would allow to press space as soon as the file opens without having to focus it manually!

Thanks a lot, keep working on that nice editor!!

**Comment by mifi** [comment]
Hi. thanks for the suggestion. I agree that it should focus in this case. I have now implemented focus on drop, but it's not yet working because waiting for this to be resolved:
https://github.com/electron/electron/issues/19920

**Comment by HugoHeneault** [comment]
Awesome! There seems to be a `force` parameter to the focus fonction now, merged into electron master 😋

**Comment by mifi** [comment]
oh I just tested newest version of electron 8.2.5, but it seems the force option is not doing anything. Maybe not released yet.

**Comment by mifi** [comment]
Can confirm this is working now. Please report back if still an issue
