### ISSUE TITLE
Sign AppX from GitHub Releases

### ISSUE THREAD

**Issue by bgiesing** [mifi/lossless-cut#337]
The AppX in Releases can't be installed "App installation failed with error message: error 0x800B0100: The app package must be digitally signed for signature validation. (0x80070570)"

**Comment by mifi** [comment]
Ahh the appx from github is used for app store, I don't think it can be run directly.

**Comment by bgiesing** [comment]
AppX's can be sideloaded separate from the store, you just need to provide the certificate to install alongside it.

A few examples:
- https://github.com/JasonStein/Notepads Zip file includes a script to automate install in Command Prompt
- https://arlo.site/strixmusic/install/nightly/ Uses the native Windows installer instead but the user has to manually download and install the certificate under Additional Links to "Trusted Root Certificate Authorities" before clicking the install button

**Comment by mifi** [comment]
Ok cool! As I'm not using Windows myself and I have 0 experience with Windows app signing, I'm probably not going to spend much time on this. If someone wants to make a PR I'm happy to consider though. As long as it doesn't add too much complexity to the build process and can be 100% automated I'm ok with including signing.

**Comment by mifi** [comment]
Closing this as there's no response and I'm not going to implement this.

**Comment by SaThero** [comment]
there is two valiable options

1. add to manifest file special oid as described here https://learn.microsoft.com/en-us/windows/msix/package/unsigned-package
this will allow install with -allowunsigned option

2. signig appx with azure https://marketplace.visualstudio.com/items?itemName=MSIX.msix-ci-automation-task 

but do we realy need any of this i dunno.
