### ISSUE TITLE
Is there a way to change audio codecs?

### ISSUE THREAD

**Issue by rockingmax** [mifi/lossless-cut#339]
Hi guys!

When exporting an MP4 file. The software shows "Unable to export this file." 

I believe the issue comes from the audio of the video file. When I turn off the sound, I can export the video file normally. Is there any way to change the audio codec to export it out? Thanks!

**Comment by mifi** [comment]
You cannot change audio codec because it is not a lossless operation (then you need to first extract the audio, then convert it using anothe rtool, then import the new audio track). does it not work with mov either? is the input also mp4? please provide more information from the in-app error report

**Comment by mifi** [comment]
Try the experimental setting in the newest version

**Comment by edmundlaugasson** [comment]
You could just add notice, that changing audio isn't lossless operation but still would be useful to allow do that directly in program. Using another conversion tool isn't lossless either - so what point is to enforce users to use another program for audio conversion?  Video remains lossless as promised and in that sense no regression.

**Comment by mifi** [comment]
adding lossy operations is frequently being requested #372 and something that i'm considering. but it's not trivial as there are license problems because many codecs have licenses and patents.

**Comment by edmundlaugasson** [comment]
Hopefully free codecs can be added as their licences should allow to be used.

**Comment by mifi** [comment]
yes, but once some codecs have been added, people will keep asking for more more
