### ISSUE TITLE
LosslessCut does not start/launch (Ubuntu 19.10)

### ISSUE THREAD

**Issue by raphraph** [mifi/lossless-cut#340]
I installed LosslessCut from snap store, and also tried with `snap install losslesscut ` and the app seems installed but when launching it by clicking on the app launcher nothing happens. I tried to run the bin via command line, no changes.
I do not see any process running.
I do not know if there are logs somewhere to get more details.

I did the same procedure a few days before on a Xubuntu install and it worked well.

Any help is appreciated.

**Comment by mifi** [comment]
Was it the same version?

**Comment by raphraph** [comment]
Yes I installed both from snap within these last two weeks. It's version 3.17.30.

**Comment by mifi** [comment]
On the command line, no error message? Could it be related to this? #258

**Comment by raphraph** [comment]
On the command line only a successfully installed message.
I don't know if it's related, I can't manage to have more information on the problem. Tell me if I can do something to get more info.

**Comment by mifi** [comment]
you could try any of the releases here from github

**Comment by zyll71** [comment]
I have the same issue on Xubuntu 20.04 and OpenSuSE Tubleweed: the losslesscut 3.23.8 snap will not launch. No error messages. No window popping up. snapd and snapd.apparmor are up and running, Other snaps seem to work fine.

```
user1@localhost:~> losslesscut
user1@localhost:~> losslesscut --no-sandbox 
user1@localhost:~> 
```

**Comment by mifi** [comment]
Without any error messages, there's not much I can do. As most of this is handled by electron and electron-builder, there is also not much I can do besides googling error messages, so I'm closing this.
