### ISSUE TITLE
Support play back of (non-)segments only

### ISSUE THREAD

**Issue by ComFreek** [mifi/lossless-cut#344]
It would be cool if one could *live-preview* one's own segments in LosslessCut, i.e. playing back of segments only. (Or in the dual Yin-Yang setting: playing back of non-segments only.)

I know the live preview could be deceptive with the cutting mode employed here, but then again I also abuse LosslessCut to just create cut times for further postprocessing.

**Comment by mifi** [comment]
Duplicate of #253
I'm not sure how useful it is though, because cutting is usually very fast anyhow
