### ISSUE TITLE
mp4/mov -movflags +faststart

### ISSUE THREAD

**Issue by mifi** [mifi/lossless-cut#347]
`-movflags +faststart` will allow streaming of output MP4/MOV files

## Downsides to always enabling faststart
- https://www.reddit.com/r/ffmpeg/comments/alxhlj/question_on_when_to_use_movflags_faststart/
- https://superuser.com/questions/856025/any-downsides-to-always-using-the-movflags-faststart-parameter

## mp4 detect if faststart is set on input:
- https://stackoverflow.com/questions/6657759/detect-if-faststart-has-been-applied-to-video/46895695
- https://stackoverflow.com/questions/56963790/how-to-tell-if-faststart-for-video-is-set-using-ffmpeg-or-ffprobe
- https://github.com/gpac/mp4box.js
- https://github.com/videojs/mux.js
- https://github.com/gkozlenko/node-video-lib
- https://github.com/lukeschaefer/mp4js

**Comment by jbruchon** [comment]
I strongly support adding this capability ASAP, preferably with a toggle in the UI. There is a major upside when uploading faststart files to YouTube: the videos get processed while the file is still uploading!

**Comment by desertpogona** [comment]
This feature is really needed

**Comment by mifi** [comment]
because it's christmas, i've now implemented this option and will be included in the next version! 🎅
