### ISSUE TITLE
No picture at the begining and no sound at the end

### ISSUE THREAD

**Issue by watertang** [mifi/lossless-cut#348]
<img width="602" alt="WX20200504-194215@2x" src="https://user-images.githubusercontent.com/64821460/81031179-4bdc4780-8e40-11ea-8195-a900eee902f2.png">

When I cutted a iPhone screen recording file which is 19.82GB, the cutted-small-file were BAD. As you can see when I opened with FinalCut Pro, no pictures at the begining and no sound at the end. Almost all the files are bad. I tried the latest version, it still wrong.

undefined

{
  "err": {},
  "state": {
    "filePath": "/Volumes/WATER MAC 6T/电影/直播/05/_20200503.mp4",
    "fileFormat": "mp4",
    "externalStreamFiles": [],
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_time_base": "1/44100",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "44100",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/44100",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 715609304,
        "duration": "16226.968345",
        "bit_rate": "108244",
        "max_bit_rate": "128000",
        "nb_frames": "698839",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "creation_time": "2020-05-03T17:34:11.000000Z",
          "language": "und",
          "handler_name": "Core Media Audio"
        }
      },
      {
        "index": 1,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_time_base": "811441/36357900",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 886,
        "height": 1920,
        "coded_width": 896,
        "coded_height": 1920,
        "has_b_frames": 1,
        "pix_fmt": "yuvj420p",
        "level": 42,
        "color_range": "pc",
        "color_space": "bt709",
        "color_transfer": "iec61966-2-1",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "60000/1001",
        "avg_frame_rate": "18178950/811441",
        "time_base": "1/600",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 9736152,
        "duration": "16226.920000",
        "bit_rate": "9655314",
        "bits_per_raw_sample": "8",
        "nb_frames": "363579",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "creation_time": "2020-05-03T17:34:11.000000Z",
          "language": "und",
          "handler_name": "Core Media Video"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "/Volumes/WATER MAC 6T/电影/直播/05/_20200503.mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {
        "start": 29.638500793500175,
        "end": 32.087222,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            20.979808647467564,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "d7250484-1b6c-41ab-bd87-de92f035a6b5"
      },
      {
        "start": 168.10029215108682,
        "end": 169.699335,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            243.47204459742977,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "1ee61c6a-d16f-479f-94b2-4ca30e5dc146"
      },
      {
        "start": 347.7613850634938,
        "end": 479.469371,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            105.96428054739198,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "39edcd83-7e2b-4571-95fe-034a38e9fbdd"
      },
      {
        "start": 515.593859436326,
        "end": 525.1013905643615,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            328.4565164973542,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "d0b7c53a-d87b-4856-b709-c53eddd6e92d"
      },
      {
        "start": 715.935959,
        "end": 884.1557586109209,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            190.94875244731634,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "b93312aa-7140-49cc-901d-32a7f8d4bc6d"
      },
      {
        "start": 896.25219492875,
        "end": 918.3917979311236,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            53.440988397278545,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "8abf0d2f-b88c-41c6-8312-9ae7651bdbbc"
      },
      {
        "start": 1335.696532748041,
        "end": 1338.210048,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            275.93322434724075,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "03a1cce1-764e-43f4-8233-f04f0d33eeab"
      },
      {
        "start": 1399.2139824907379,
        "end": 1402.195024,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            138.42546029720296,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "63e08812-31e1-4be6-b4b3-7e05d6a8e32a"
      },
      {
        "start": 1464.1151574210833,
        "end": 1465.866012,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            0.9176962471652246,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "80d5c56c-5859-4e59-9483-3ff3e3357559"
      },
      {
        "start": 1491.6111159885472,
        "end": 1493.407593,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            223.40993219712743,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "88ffded1-81d1-4d3c-b277-a2e9b67fa371"
      },
      {
        "start": 1499.1100137796736,
        "end": 1509.243897,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            85.90216814708964,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "4a06ba00-97f3-4724-b052-b60c96cd8b8b"
      },
      {
        "start": 1513.2150834344118,
        "end": 1515.28282,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            308.39440409705185,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "8e7c1592-8d5a-40b1-94d4-c6adcf23c919"
      },
      {
        "start": 1554.5482938783593,
        "end": 1634.841661,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            170.886640047014,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "4a022df6-8796-4cf2-9ea6-9cb0d5168cc3"
      },
      {
        "start": 1768.4900624073448,
        "end": 1901.136091,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            33.378875996976205,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "19e610df-ad37-46f7-b835-b6c4117ca2b8"
      },
      {
        "start": 2290.5115485217793,
        "end": 2293.457239,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            255.8711119469384,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "a6ae77f7-8392-4782-9c62-1c0415ffa06a"
      },
      {
        "start": 2339.7007471278594,
        "end": 2437.3649635980078,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            118.36334789690062,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "53736673-a831-4174-a37b-ef1254a94950"
      },
      {
        "start": 2554.0888786206024,
        "end": 2768.982945,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            340.8555838468628,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "02b9c6f1-7f62-436a-b1b6-adbc10b90d57"
      },
      {
        "start": 3171.68935,
        "end": 3179.570608,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            203.34781979682498,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "3867b00c-7773-422b-a287-6be29120ad08"
      },
      {
        "start": 3228.27549907998,
        "end": 3229.40335,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            65.84005574678719,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "06c0d255-e650-4b3e-925b-1ccf1505d705"
      },
      {
        "start": 3805.512083811221,
        "end": 3807.510627,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            288.3322916967494,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "320a2b11-f11d-4ac9-b088-ba548b641556"
      },
      {
        "start": 3816.001613459523,
        "end": 3818.546854,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            150.8245276467116,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "d162215e-dd97-447e-abb4-7dc71f833423"
      },
      {
        "start": 3990.083169324961,
        "end": 3992.008741,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            13.316763596673809,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "2ad86b67-8367-430e-94ff-1b84704f31da"
      },
      {
        "start": 4804.0706700331975,
        "end": 5035.554601,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            235.80899954663607,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "b4564846-9c92-4f90-a384-8e3d02cfee51"
      },
      {
        "start": 5289.177939044885,
        "end": 5446.373332,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            98.30123549659822,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "7df1022c-b231-456a-97fb-dc19a81ac945"
      },
      {
        "start": 5475.757657895533,
        "end": 5567.177184,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            320.7934714465605,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "53148e32-d140-45ae-ab34-b8d2bd2b0640"
      },
      {
        "start": 6114.994058292696,
        "end": 6197.004237,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            183.28570739652264,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "eec33e6d-2171-423e-be2d-c9901b972a2b"
      },
      {
        "start": 6418.6101462405695,
        "end": 6638.588074,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            45.77794334648479,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "eb5216aa-90ab-4379-84be-f155d66cdf29"
      },
      {
        "start": 6979.0188472381515,
        "end": 7171.058894,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            268.27017929644705,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "84d39f5c-588f-42e3-960e-18dc8a75a6f1"
      },
      {
        "start": 7394.62740279279,
        "end": 7405.993548,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            130.7624152464092,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "c5e91b2d-7bf5-4941-ae1a-e1358d4d2b52"
      },
      {
        "start": 7475.820825900286,
        "end": 7480.124971,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            353.25465119637147,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "1dd4080e-5222-446e-9ea1-90619cda4e25"
      },
      {
        "start": 7549.87244158766,
        "end": 7555.529515,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            215.74688714633362,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "65d4bf11-6227-4961-bba5-1af425f66c71"
      },
      {
        "start": 7626.423689872077,
        "end": 7630.436586,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            78.23912309629577,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "b9bcd567-0613-40c7-b0e1-2ca4417c6401"
      },
      {
        "start": 7652.535923251893,
        "end": 7663.948583,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            300.73135904625804,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "1dfd7ad3-b707-46f6-ae1f-99050936578a"
      },
      {
        "start": 7681.728061081635,
        "end": 7687.571828,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            163.22359499622019,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "3fe28b58-62fa-4815-beb2-33ec485ea2ad"
      },
      {
        "start": 7702.841029267367,
        "end": 7705.31108,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            25.71583094618245,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "11a753f3-4716-43ab-845c-350fa41e292b"
      },
      {
        "start": 7785.747785,
        "end": 7816.566712,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            248.2080668961446,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "42d88e37-88f5-49ee-84c0-2110549367ce"
      },
      {
        "start": 7818.493673176944,
        "end": 7829.646716,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            110.70030284610687,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "be450b1c-382c-4fb8-80a6-45c63e1e3515"
      },
      {
        "start": 8047.34396469543,
        "end": 8222.999885,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            333.19253879606913,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "1efc1f96-c29c-4813-94d9-5add3061c17e"
      },
      {
        "start": 8339.042161510979,
        "end": 8342.39514,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            195.68477474603128,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "920f0044-6dea-4128-ba02-4702245c142f"
      },
      {
        "start": 8371.80520305078,
        "end": 8441.87677,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            58.17701069599343,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "0ab8cb50-d0bb-41b1-8ad9-9d8f293c27e9"
      },
      {
        "start": 9057.909714642485,
        "end": 9109.077509,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            280.6692466459556,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "b5fa3545-c971-4cec-9e43-bddd9b7881a8"
      },
      {
        "start": 9139.995863677495,
        "end": 9145.733555,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            143.16148259591785,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "11809f4d-1657-4822-bb34-98d5021c821a"
      },
      {
        "start": 9182.923636,
        "end": 9205.479821,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            5.6537185458801105,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "ad14d39b-f1df-4cd8-b511-5251d1456d15"
      },
      {
        "start": 9244.489433493134,
        "end": 9297.736335,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            228.14595449584226,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "8528f922-dfdc-4f3d-ad5b-3bff446a626d"
      },
      {
        "start": 9348.759821826892,
        "end": 9360.14207740271,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            90.63819044580453,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "ef224348-6e82-4607-9681-43cd626ca73e"
      },
      {
        "start": 9380.094501882671,
        "end": 9393.061394,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            313.1304263957668,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "22cd6fff-ca43-4cdd-aa03-9e1ad37a8a31"
      },
      {
        "start": 9457.733465,
        "end": 9632.865244,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            175.62266234572894,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "d9907c62-512c-49e5-9e47-34d9fec0be50"
      },
      {
        "start": 9634.342846038962,
        "end": 9639.258163,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            38.11489829569109,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "54112541-641e-4a03-85ca-78500a76116d"
      },
      {
        "start": 10019.241629687083,
        "end": 10261.917653,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            260.60713424565324,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "bc809fc5-15e9-4968-b7f3-92afc7533b22"
      },
      {
        "start": 10336.561060622313,
        "end": 10363.303586,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            123.0993701956155,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "2e81eb50-09e9-47a6-b695-52ecbd1c7031"
      },
      {
        "start": 10518.218763,
        "end": 10741.931826,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            345.59160614557777,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "dac96b52-010d-4565-b21c-907c7b2172e9"
      },
      {
        "start": 11030.253742597895,
        "end": 11168.536988769978,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            208.08384209553992,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "426d3843-5a4d-497d-8f3e-f220c987866d"
      },
      {
        "start": 12129.958176407328,
        "end": 12306.544435,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            70.57607804550207,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "30d78f62-7307-4c1d-926f-b6eb06f0ae8a"
      },
      {
        "start": 12614.70835504801,
        "end": 12625.923272,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            293.0683139954642,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "9de78d7e-6fa8-4b1a-9859-77e6cedfde10"
      },
      {
        "start": 12886.320218494468,
        "end": 12950.407986,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            155.5605499454265,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "06b9d70d-2555-4c2c-92a5-301858913af2"
      },
      {
        "start": 12992.331422386882,
        "end": 12999.651162,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            18.05278589538875,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "9ae0ae98-051d-484a-871c-99b8a791f355"
      },
      {
        "start": 13214.798723523636,
        "end": 13223.950687,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            240.5450218453509,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "2a38a60e-b926-4860-b9aa-87f4a2efebdd"
      },
      {
        "start": 13574.254818237578,
        "end": 13577.768438,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            103.03725779531317,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "fa54dad8-7626-4ba9-9953-4cdbf53db9c4"
      },
      {
        "start": 13616.525390905415,
        "end": 13824.378391,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            325.5294937452753,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "981f3ed9-8566-4a34-9330-f1b5adbc5541"
      },
      {
        "start": 13825.289349054814,
        "end": 13856.860023,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            188.02172969523758,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "9ad3e62a-6840-45c7-97f8-982e1390688d"
      },
      {
        "start": 15677.20464938844,
        "end": 15916.289748,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            50.51396564519973,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "c8d3140f-e56b-437a-8de3-52ffe477a07a"
      },
      {
        "start": 15997.47007588447,
        "end": 16044.886389,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            273.0062015951619,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "04b0b827-3f2f-4b0c-bc24-1ad894b876dc"
      },
      {
        "start": 16081.430949367263,
        "end": 16084.529199,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            135.49843754512415,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "3915404c-c73e-4e05-9c47-c2e2ceee5508"
      },
      {
        "start": 16116.328529,
        "end": 16133.31163,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            357.9906734950863,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "a8e3057b-46a0-4e2c-96af-904fc147e53d"
      }
    ],
    "fileFormatData": {
      "filename": "/Volumes/WATER MAC 6T/电影/直播/05/_20200503.mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "16226.968333",
      "size": "19815590692",
      "bit_rate": "9769213",
      "probe_score": 100,
      "tags": {
        "major_brand": "mp42",
        "minor_version": "1",
        "compatible_brands": "isommp41mp42",
        "creation_time": "2020-05-03T17:34:11.000000Z"
      }
    },
    "rotation": 360,
    "shortestFlag": false
  }
}

**Comment by mifi** [comment]
Did you use keyframe cut or normal cut?

**Comment by watertang** [comment]
Keyframe cut. It never happen before , I use it everyday , but the iPhone screen recording file is the first time. Both of iPad and HUAWEI screen recording files are good.
在 2020年5月4日 -0700 20:19，Mikael Finstad <notifications@github.com>，写道：

**Comment by watertang** [comment]
I re-encode the file with FinalCutPro, it works good finally. I am not sure which one went wrong, iPhone encoding, or lossless-cut.
在 2020年5月4日 -0700 20:21，Tang Water <watertang7@gmail.com>，写道：

**Comment by mifi** [comment]
Closing in favor of #330
