### ISSUE TITLE
Sync timestamp metadata relative to main video file

### ISSUE THREAD

**Issue by jasalt** [mifi/lossless-cut#35]
When using multiple video cameras and recorders it would be very useful to have the tool keep "Recorded date" timestamp metadata intact relative to the original video file, so that the exported clip would have timestamp with added offset relative to the starting point of the clipping. This way the clips from separate cameras could be easily/automatically synced in timeline.  

Related issue https://github.com/mifi/lossless-cut/issues/33

**Comment by mifi** [comment]
Is this timestamp global metadata or specific to streams? See #33

**Comment by mifi** [comment]
Implemented in 60060d4b73c65276a32c3863f034c8f0cbf818be
