### ISSUE TITLE
App installation failed with error message: error 0x800B0100: The app package must be digitally signed for signature validation. (0x80070570)

### ISSUE THREAD

**Issue by awsumbill** [mifi/lossless-cut#350]
During Installation of APPX file on Windows 10, I get this error:

<img width="490" alt="LosslessCutError" src="https://user-images.githubusercontent.com/47586568/81107521-34e33700-8ecc-11ea-8038-a693f13d083c.png">

Not sure what it means but I can't install using APPX

Windows version:
![image](https://user-images.githubusercontent.com/47586568/81107611-55ab8c80-8ecc-11ea-8c8c-452f6bd80b81.png)

**Comment by awsumbill** [comment]
So I did a little research and I have to install it unpackaged by extracting the .Appx fille and then running this in Powershell...
` Add-AppxPackage -Path C:\Path\to\AppxManifest.xml -Register `

...and it worked!
No issue here.

**Comment by technobulb** [comment]
> So I did a little research and I have to install it unpackaged by extracting the .Appx fille and then running this in Powershell... `Add-AppxPackage -Path C:\Path\to\AppxManifest.xml -Register`
> 
> ...and it worked! No issue here.

Can you be more specific with the steps to install it as an app? How do you extract the .appx file?

**Comment by dinemuatta** [comment]
@technobulb a lil bit late but i just tried and found out you can extract it with 7zip or any other software (but i would prefer 7zip ;)

**Comment by technobulb** [comment]
Thanks, which file do I extract? And does it then install as a store app?
