### ISSUE TITLE
path to ffmpeg is not resolved through ffmpeg-static

### ISSUE THREAD

**Issue by muelli** [mifi/lossless-cut#353]
It appears that lossless-cut hard-codes the path to ffmpeg: https://github.com/mifi/lossless-cut/blob/9b3af1a995ff54018169846325abe1e3ca0ece6e/src/ffmpeg.js#L37

While ffmpeg-static is used, presumably to get hold of ffmpeg, it is not used to resolve the path, i.e. `var pathToFfmpeg = require('ffmpeg-static');`.

This breaks when using a pre-downloaded ffmpeg, cf. https://github.com/eugeneware/ffmpeg-static/issues/37

**Comment by mifi** [comment]
Yeah, this is because of the way Electron and electron-builder works, it packages stuff into the distributable format, and then the only way to get the path is to append `window.process.resourcesPath`. It's a bit of a hack but I'm not sure how else to solve this.

**Comment by muelli** [comment]
The ffmpeg-static package, i.e. @eugeneware, suggests `var pathToFfmpeg = require('ffmpeg-static')`.

**Comment by mifi** [comment]
Need to test if that works in a packaged electron application

**Comment by muelli** [comment]
The package is not a dependency any more :( And the new package breaks offline builds: https://github.com/flathub/no.mifi.losslesscut/pull/11#issuecomment-743332676

**Comment by mifi** [comment]
I think this can be closed because no longer using ffmpeg-static
