### ISSUE TITLE
a video download from YouTube can't cut the merged

### ISSUE THREAD

**Issue by sojey** [mifi/lossless-cut#356]
windows 10 1909 x64

I use a *.bat to merge video and sound, The bat file commands like this:
echo.
set /p audio=请将【音频】文件拖拽到此处，按下回车确认：
set /p video=请将【视频】文件拖拽到此处，按下回车确认：
ffmpeg.exe -i %audio% -i %video% -acodec copy -vcodec copy H:\output.mp4
echo.
echo 合并结束！
echo 文件已经输出到本地的 output.mp4 文件。
pause

the merge video info is:
123.mp4
容器：MPEG-4
总码率：1 797 kb/s
大小：128 MiB
时长：9 min 57 s 381 ms

视频(1)：AVC
Profile：High@L4
码率：1 660 kb/s
文件大小：118 MiB (92%)
分辨率：1920x1080
画面比例：16:9(1.778)
像素宽高比：1.000
帧率：30.000 FPS
色彩空间：YUV
色度抽样：4:2:0
位深度：8 bits
扫描方式：逐行扫描
总帧数：17921
编码库：x264 core 155 r2901 7d0ff22

音频(2)：Opus
大小：9.23 MiB (7%)
码率：130 kb/s
采样率：48.0 kHz
声道数：2

====详细信息====
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 3 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 9 min 57 s
Bit rate                                 : 1 660 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 30.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.027
Stream size                              : 118 MiB (92%)
Title                                    : ISO Media file produced by Google Inc.
Writing library                          : x264 core 155 r2901 7d0ff22
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

ID                                       : 2
Format                                   : Opus
Codec ID                                 : Opus
Duration                                 : 9 min 57 s
Duration_FirstFrame                      : 1 ms
Bit rate mode                            : Variable
Bit rate                                 : 130 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 kHz
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 9.23 MiB (7%)
Language                                 : English
Default                                  : Yes
Alternate group                          : 1

losslesscut Send problem report: 
Please create an issue at https://github.com/mifi/lossless-cut/issues where you describe what you were doing.

Include the following text:

```
undefined

{
  "err": {},
  "state": {
    "filePath": "H:\\和蒂法的亲密接触.mp4",
    "fileFormat": "mp4",
    "externalStreamFiles": [],
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_time_base": "1/60",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1088,
        "has_b_frames": 1,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 40,
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "30/1",
        "avg_frame_rate": "30/1",
        "time_base": "1/15360",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 9175557,
        "duration": "597.366992",
        "bit_rate": "1659578",
        "bits_per_raw_sample": "8",
        "nb_frames": "17921",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "ISO Media file produced by Google Inc."
        }
      },
      {
        "index": 1,
        "codec_name": "opus",
        "codec_long_name": "Opus (Opus Interactive Audio Codec)",
        "codec_type": "audio",
        "codec_time_base": "1/48000",
        "codec_tag_string": "Opus",
        "codec_tag": "0x7375704f",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/48000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 28674288,
        "duration": "597.381000",
        "bit_rate": "129640",
        "nb_frames": "29869",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "eng",
          "handler_name": "SoundHandler"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "H:\\和蒂法的亲密接触.mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {
        "start": 33.2,
        "end": 76.06666666666666,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            193.8757751993952,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "c00647f1-9d1d-4a57-b474-b9b1814fc1b9"
      },
      {
        "start": 142.8,
        "end": 184.66666666666666,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            208.34777157248345,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "f657e9de-3341-478c-8085-4e649eff760a"
      },
      {
        "start": 190.53333333333333,
        "end": 201.4,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            113.72813768782333,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "f79a7b80-52e6-42f3-8405-4e663fe7502a"
      },
      {
        "start": 206.4,
        "end": 252.33333333333334,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            129.74520413060407,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "da30421e-7e41-489e-8e63-a40233bb80e9"
      },
      {
        "start": 294.4,
        "end": 322.3666666666667,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            355.42839230958873,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "e1f1334f-d3a9-4d43-897e-0888775c2391"
      },
      {
        "start": 322.3666666666667,
        "end": 340.3,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            55.18768264624623,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "631da53b-2594-469c-b12e-fc2e5c56d64c"
      },
      {
        "start": 340.3,
        "end": 504.6666666666667,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            108.40195113755289,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "029507d5-af94-4d9f-b4ec-96dffc9a0f11"
      }
    ],
    "fileFormatData": {
      "filename": "H:\\和蒂法的亲密接触.mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "597.381000",
      "size": "134182075",
      "bit_rate": "1796937",
      "probe_score": 100,
      "tags": {
        "major_brand": "isom",
        "minor_version": "512",
        "compatible_brands": "isomiso2avc1mp41",
        "encoder": "Lavf58.42.100"
      }
    },
    "rotation": 360,
    "shortestFlag": false
  }
}
```
OK

**Comment by sojey** [comment]
this merge video can play in LosslessCut, but when set 7 Timestamp, use export then show those text. then I update to this issue.

**Comment by mifi** [comment]
Hi! I'm not sure I understand what's the problem. did you get an error?

**Comment by sojey** [comment]
> Hi! I'm not sure I understand what's the problem. did you get an error?

The above is the error message built into the software, At the same time I added the complete attribute information of this video file.

I don' t know what information you need, or I will send this 100m video to you to test it in person?  to finstaden#gmail.com ok?

**Comment by mifi** [comment]
Ok, you can send to me u can use https://www.filemail.com/ or google drive or similar

**Comment by mifi** [comment]
Ohh, this was because your file has OPUS audio which is not officially supported in MP4. See #336

In the newest version I add an Experimental flag under Settings that you can use to enable Opus support in MP4

**Comment by sojey** [comment]
> Ohh, this was because your file has OPUS audio which is not officially supported in MP4. See #336
> 
> In the newest version I add an Experimental flag under Settings that you can use to enable Opus support in MP4

Thank you very much, I know that the format of this audio is webp, but before there are webp audio and mp4 video compression can be cut, but this time is an exception. But I do n’t know how to make the problem clear with a translator, so. Thank you.

**Comment by mifi** [comment]
Try 3.23.7

**Comment by sojey** [comment]
> Try 3.23.7

Ok, I tried it and it works perfectly. thank you very much.
