### ISSUE TITLE
"Unsupported file" when opening the program

### ISSUE THREAD

**Issue by ThracianKnight1907** [mifi/lossless-cut#357]
Title says it all. If I open it from the menu (so a 'fresh' start) it gives this error, but obviously no file was involved yet. 

Using the Flatpak version 3.22.3

**Comment by mifi** [comment]
Ohh. This is probably related to #215
Can yo ucheck developer tools and see if it logs which argument is being sent to the application?
The thing is that LosslessCut supports opening files via a command line argument, and sometimes operating systems send some strange stuff there. maybe we can ignore anything starting with a dash `-`

**Comment by ThracianKnight1907** [comment]
`2.8b42b57b.chunk.js:2 react-i18next:: i18n.languages were undefined or empty undefined
mifi.no/losslesscut/config.json:1 Failed to load resource: net::ERR_INTERNET_DISCONNECTED
main.0a57e3a0.chunk.js:1 Load 
Object
main.0a57e3a0.chunk.js:1 getFormatData --no-sandbox
main.0a57e3a0.chunk.js:1 ffprobe -of json -show_format -i --no-sandbox
main.0a57e3a0.chunk.js:1 Error: Command failed with exit code 1: /app/lossless-cut/resources/node_modules/ffprobe-static/bin/linux/x64/ffprobe -of json -show_format -i --no-sandbox
ffprobe version 4.0.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2007-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
--no-sandbox: No such file or directory
{

}
    at makeError (/app/lossless-cut/re…eca/lib/error.js:58)
    at handlePromise (/app/lossless-cut/re…/execa/index.js:114)
    at async K (main.0a57e3a0.chunk.js:1)
    at async file:/app/loss…0a57e3a0.chunk.js:1
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/build/static/js/2.8b42b57b.chunk.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/build/static/js/main.0a57e3a0.chunk.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/human-signals/build/src/main.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/human-signals/build/src/signals.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/human-signals/build/src/core.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/human-signals/build/src/realtime.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/strtok3/lib/index.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/strtok3/lib/FsPromise.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/strtok3/lib/core.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/strtok3/lib/ReadStreamTokenizer.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/strtok3/lib/AbstractTokenizer.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/peek-readable/lib/index.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/peek-readable/lib/EndOfFileStream.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/strtok3/lib/BufferTokenizer.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/strtok3/lib/FileTokenizer.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/build/static/css/main.6a98439e.chunk.css.map
`

Seems like it has quite a lot of errors

**Comment by mifi** [comment]
Aha! good old `--no-sandbox`. I will improve the file detection

**Comment by mifi** [comment]
Thanks, have fixed this. will be out in the next version
