### ISSUE TITLE
Feature Request: Flip side by side

### ISSUE THREAD

**Issue by kiatlc** [mifi/lossless-cut#365]
Some videos uploaded to YouTube are forced to be deleted by the copyright system. Which is fair if those videos are movies which affect the benefit of stakeholder. But if some educational videos which I upload just for myself watching using Private setting, they will be taken down also.

Now Loseless-cut can rotate, but it will make the watching experience not good. If left and right can be flipped, then it is perfect, because it won't matter left changed to right vice versa

**Comment by mifi** [comment]
Hi. I'm not sure if I understand. What does flipping have to do with copyright?

**Comment by kiatlc** [comment]
youtube use some clue to discern whether a video infringed copyright or
not. The most important clue is the snapshot at certain point.

Let's say a video of 30min, it uses 10 snapshot at different point to
compare with its database. If 10 of 10 matching its copyright database,
then the system will automatically judge this video as copyright
infringement

When flip side by side, the snapshots it takes from uploader will be
different from snapshots in database, so it won't cause infringement. You
get my point? It is a workaround strategy

Mikael Finstad <notifications@github.com> 于2020年5月18日周一 下午7:22写道：

**Comment by mattack1** [comment]
> On May 18, 2020, at 12:06 PM, kiatlc <notifications@github.com> wrote:
> 
> 
> youtube use some clue to discern whether a video infringed copyright or
> not. The most important clue is the snapshot at certain point.
> 
> Let's say a video of 30min, it uses 10 snapshot at different point to
> compare with its database. If 10 of 10 matching its copyright database,
> then the system will automatically judge this video as copyright
> infringement
> 
> When flip side by side, the snapshots it takes from uploader will be
> different from snapshots in database, so it won't cause infringement. You
> get my point? It is a workaround strategy

So you're trying to violate copyrights..?  Bad.

**Comment by mifi** [comment]
Lossless flipping is AFAIK not possible. See #316
I'm sure google can help you if you need to flip your private videos.
