### ISSUE TITLE
Right click dragging to move zoomed timeline

### ISSUE THREAD

**Issue by Wiethoofd** [mifi/lossless-cut#369]
Currently the only way to skip through the timeline is by scrolling or arrow keys + combination of modifiers.

However, when zoomed in for a more accurate cut (x16 to show keyframes) to quickly jump or move in the timeline requires rapid scrolling, or zooming out and click to skipping to the next section.

It would be a nice to have to 'right click drag' the timeline to move it while zoomed in.

**Comment by mifi** [comment]
Wouldn't right click to drag also require a lot of dragging if zommed in?

**Comment by Wiethoofd** [comment]
This would go hand in hand with #553, where you'd be able to make bigger jumps in the timeline, perhaps also supporting the same modifier keys for faster or slower scroll speeds.

**Comment by mifi** [comment]
closing in favor of #483
