### ISSUE TITLE
Dropping video frames at beginning of merge segment

### ISSUE THREAD

**Issue by gear259** [mifi/lossless-cut#376]
So, not been using this long but I've tried quite a few output formats and keep getting same result, video frames at the beginning of the segment are out of sync with audio.  

What am I doing wrong?

**Comment by mifi** [comment]
You tried all suggested options?

**Comment by gear259** [comment]
Yeah I think it was something to do with keyframes in the end but I found a workaround

Sent from ProtonMail mobile

-------- Original Message --------
