### ISSUE TITLE
[New Feature][Audio waving display panel] Support like the software ARCTIME

### ISSUE THREAD

**Issue by wxyjuly** [mifi/lossless-cut#379]
1. If can added [Audio waving display panel] , the panel may like the software <ARCTIME>,  which can easily to choose cut place. 
2. the waving panel look like below image:
![image](https://user-images.githubusercontent.com/4783631/83086921-9c069c80-a0c2-11ea-880c-6771920c9d9e.png)
3. thanks for your sharing

**Comment by mifi** [comment]
Thanks for the suggestion. See #260
