### ISSUE TITLE
Question: what's the difference between the Windows ZIP and the Windows EXE?

### ISSUE THREAD

**Issue by ghost** [mifi/lossless-cut#382]
I couldn't find anywhere else to ask questions so I figured I'd do it here, if this isn't the place feel free to close this "issue".

What's the difference between these two versions? Is there anyway to run this app in a completely portable mode where it doesn't create files and/or registry entries outside of the EXEs DIR?

**Comment by mifi** [comment]
No, that's not possible. But the app only needs to run as you local user so it will only create files in your AppData folders, not in your system folders.
There shouldn't be any difference between the zip and exe. it's personal preference :)
