### ISSUE TITLE
Display ffmpeg errors for troubleshooting

### ISSUE THREAD

**Issue by duracell** [mifi/lossless-cut#383]
Hi, I had some problems with export+merging which seems to be a problem with the file itself (Error: h264_mp4toannexb filter failed to receive output packets while merging).
But debugging this was really hard because it just merged 2/5 files (just stopped at 60%), deleted then all split files and then said that the export was done. I found no information about this error, even in the developer tools console.
I would suggest to display ffmpeg errors in the gui, that would be helpful.

(If there is anything where I could find this, then it would be great to put this in the Troubleshooting section on the README.)

**Comment by mifi** [comment]
Is this the newest version?

**Comment by duracell** [comment]
I think it was 3.23.7, the newest version at the time I posted this issue.

**Comment by mifi** [comment]
If you can share a file i could look into it

**Comment by mifi** [comment]
closung due to inactivity
