### ISSUE TITLE
Enhancement: Upload Video to Streamable automatic 

### ISSUE THREAD

**Issue by tschuehly** [mifi/lossless-cut#384]
Hello,

It would be great to have a feature where i could upload my exportet clip to Streamable directly.
https://streamable.com/documentation
Me and many of my friends use losslesscut for cutting short highlights and this would be awesome to have as a feature.

Many thanks

**Comment by mifi** [comment]
I'm not sure if this is something many users really need. But if this issue becomes tremendously popular, then I can consider adding it

**Comment by mifi** [comment]
I think this can be solved with a generic afterExport event, see #980 so I will close this
