### ISSUE TITLE
Request: Alert display options

### ISSUE THREAD

**Issue by krogulgit** [mifi/lossless-cut#389]
I am really pleased with the latest version. At first I was put off by the long load times. But I changed my workflow from starting 10, 15, 20 copies to work with a batch of files to just opening two copies and bouncing between the two.

LosslessCut makes my workflow very efficient, especially with using right and left arrows for seeking cut points and finalizing cut points by using seek key frame buttons. 

I only have three suggestions which are nice to haves, but really don't affect my workflow all that much:

1) I don't use the "> Segments to export:" side bar, so it would be nice to have an option to not display those.
2) I was done with the "Note: cutpoints may be inaccurate" warning after about the third time. It would be nice to have an option to disable the warning.
3) It would be nice to have an option on how to handle opening a new file while a current file is already loaded: Prompt (what it currently does), always open the new file, always include tracks.

Thanks for such a useful, well designed app.

**Comment by mifi** [comment]
I believe all these are implemented as of now, so closing this.
