### ISSUE TITLE
Please provide integrity checks for downloads via GitHub

### ISSUE THREAD

**Issue by GrantBirki** [mifi/lossless-cut#394]
It would be a very nice security feature to publish hashes of files for building from source or downloading executable via GitHub. 

If possible to provide a file signature via PGP that would be the icing on the cake. 

https://www.gnupg.org/gph/en/manual/x135.html

**Comment by markusd1984** [comment]
yes please, @mifi in the mean time can you kindly provide a hash for the latest [windows .exe version 3.30.0](https://github.com/mifi/lossless-cut/releases/download/v3.30.0/LosslessCut-win.exe) please?

**Comment by GrantBirki** [comment]
@markusd1984 @mifi I would also strongly suggest using GitHub's code signing as well. More info on this can be found [here](https://docs.github.com/en/github/authenticating-to-github/signing-commits).

**Comment by mifi** [comment]
Is it a feature in github to publish hashes along with binaries? What’s the benefit of that, when all binaries are hosted by Github anyhow? I mean if there was an attacker or hacker inside github he could just fake the hashes also if he wants to fake the files?

Also what’s the benefit of signing commits?

**Comment by markusd1984** [comment]
At least we can verify the download against corruption with the hash, appreciate if you can publish for that reason alone.

**Comment by GrantBirki** [comment]
@mifi Ideally if you just use [Git Commit Signing](https://docs.github.com/en/github/authenticating-to-github/signing-commits) you would provide all users the security of knowing that the code was created by you _and_ it has not been altered or pushed by another entity. When you enable Signing you will get a "Verified" badge on your releases. [Example](https://res.cloudinary.com/practicaldev/image/fetch/s--dWCFJsEL--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://thepracticaldev.s3.amazonaws.com/i/dls5am1kuub98n913my8.png)

Git Commit Signing is very easy to do and will bring a lot of assurance when users are downloading and using new releases.

**Comment by mifi** [comment]
Ah ok. But it isn't actually me who personally creates the github release and upload artifacts - it is github actions. Will it still get a verified badge as long as the commit that was tagged is created by me?

**Comment by GrantBirki** [comment]
I can't find any data in GitHub's documentation that says this would be the case. I believe that if you sign the commit then it will still be verified as the actions are trigged from a signed and authorized commit :)

**Comment by mifi** [comment]
I tried to setup GPG signing. While it works from the command line, I cannot get it to work from my GUI apps. Seems like [github desktop](https://docs.github.com/en/github/authenticating-to-github/signing-commits) doesn't yet support commit signing, so I think this feature is a bit new and bleeding edge, so I think I will wait until it's more established

**Comment by markusd1984** [comment]
Perhaps possible setup signing manually along with GitHub desktop?

https://github.com/desktop/desktop/issues/78#issuecomment-489130367

Another reference I found GPG signing with GitHub desktop.

https://gist.githubusercontent.com/xavierfoucrier/c156027fcc6ae23bcee1204199f177da/raw/b0057c1b554895f408310db71fbcb9f1ef5fbfe5/gpg-signing.md

**Comment by mifi** [comment]
Thanks for research. I had tried most of those steps before, but what I was missing was `git config --global gpg.program /usr/local/bin/gpg`

Now it works also from GUI!

**Comment by mifi** [comment]
How to publish hashes I don't really know how to do, because it's the [electron-builder-action](https://github.com/marketplace/actions/electron-builder-action) that handles all uploads, so I think the support needs to be inside there, or some custom github action to create hashes after upload. (download the uploaded files again and hash them?)

**Comment by GrantBirki** [comment]
@mifi Something like this might be what you are looking for: https://github.com/marketplace/actions/generate-release-hashes

I personally have not used it before though. I see that you are now pushing signed commits which is awesome! For the purpose of this issue that is essentially the security check I was looking for so I'm going to close this issue. Thanks for working with me to further improve the security of this project! I use it all the time and really appreciate your work 💯

**Comment by markusd1984** [comment]
@mifi might this help, [manually generating electron checksum via script](https://github.com/electron-userland/electron-builder/issues/3913#issuecomment-504698845)? 

https://stackoverflow.com/a/60208623/8719001

https://www.electron.build/code-signing

**Comment by mifi** [comment]
Code signing is for windows/mac for signing the binary. Already signing the mac binary for app store (and notarizing the download). Windows I need to buy a certificate and I think it needs a lot of manual work #218 #337
Hashing the files before uplaod can probably be done, you can create a separate feature request for that.
