### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by plk0507** [mifi/lossless-cut#395]
Hi. After I export a file with LosslessCut I can no longer edit or update the metadata. Is there a way to fix this?

**Comment by wallobit** [comment]
Hi. I also have this problem. When recording videos, I work with comments. These are no longer available after exporting with losslesscut.

**Comment by wallobit** [comment]
If you copy the video created with losslessCut with ffmpeg, you can edit the metadata again and the last comment is back: ffmpeg -i <input file> -c copy <output file>
The file originally created with losslesscut does not appear to be in order

**Comment by wallobit** [comment]
If you copy the video created with LosslessCut using ffmpeg, you can edit the metadata again and the last comment is back:
ffmpeg -i <input file> -c copy <output file>
The file originally created with LosslessCut does not appear to be in order.

**Comment by mifi** [comment]
May be related to `-movflags use_metadata_tags` #402 ?

**Comment by mifi** [comment]
In the next version there will be an option to not preserve MOV metadata (disable the `-movflags use_metadata_tags` flag). This should fix your issue.
