### ISSUE TITLE
Hello, the video is split,

### ISSUE THREAD

**Issue by liuyichengwo** [mifi/lossless-cut#396]
Nín hǎo, shìpín fēngē wánchéng, yòu cè xūyào dǎochū de piànduàn, xīwàng kěyǐ tiānjiā xuǎnzhōng yídòng shùnxù gōngnéng
34/5000
Hello, the video is split, the clips that need to be exported on the right, I hope you can add the selected movement order function

**Comment by mifi** [comment]
Try yin yang symbol
