### ISSUE TITLE
Insert keyframe?

### ISSUE THREAD

**Issue by Gaspree** [mifi/lossless-cut#397]
Hi!

I have a deal/question/request:
Do you can implement the Insert Keyframe FFMPEG funciton into the LosslessCut? It would be very useful to insert it automatically when exporting the video.
I found this (on the superuser.com):
You can use ffmpeg to insert keyframes where you want them using the -force_key_frames option.
eg:
./ffmpeg -i input.mp4 -c:a copy -c:v copy -force_key_frames 0:05:00,0:10:00 out.mp4
..with this function mutch more flexibility the cut :D

Thanks a lot for your effort and development, this is a great software !!!
Tamas

**Comment by TheSeanLavery** [comment]
This seems like it would be a great addition, as the current implementation only allows the cuts to happen on existing keyframes.

**Comment by mifi** [comment]
I think `force_key_frames` is only an option for lossy conversion (when encoding), or am I wrong?

**Comment by NicoHeijningen** [comment]
I tried this, and it indeed seems to be the case that no keyframe is added when not encoding
https://superuser.com/questions/1313522/add-keyframe-to-middle-of-video-without-reencoding-entire-video

**Comment by mifi** [comment]
Ok thanks for researching. I will probably not be able to implement this because ffmpeg does not support it.
