### ISSUE TITLE
Feature request: change output resolution (resize/recompress)

### ISSUE THREAD

**Issue by bgr** [mifi/lossless-cut#398]
I know this request goes against the project's name, but is it possible to specify output resolution/scale, bitrate, etc.? Even some dev input field for additional arguments to be passed to ffmpeg would be enough.

My use-case for ffmpeg in 95% of cases is to trim the video (which this app excels in, I tried 8 different horrible ffmpeg GUIs before finding this one), and recompress it so it's small enough for sharing (so basically I mostly use `-i in.mp4 -vf scale="720:-2" out.mp4` which is enough for my needs).

**Comment by bgr** [comment]
I made the input field hack that suits my needs ([link to commit](https://github.com/bgr/lossless-cut/commit/137ebf28aaed1228f777a0f2e673852351524232)):

![LossyCutBgr_2020-06-07_15-15-54](https://user-images.githubusercontent.com/425768/83969716-ca118b00-a8d1-11ea-98f2-53562f90e6b6.png)

Feel free to close the issue if you don't wish to add a proper version of this feature to the app.

**Comment by mifi** [comment]
I'm not sure how we can scale without doing a re-encode. Maybe you are asking for lossy features in losslesscut. It's something I want to consider adding. See #372
