### ISSUE TITLE
Building/running from source on Windows fixes

### ISSUE THREAD

**Issue by bgr** [mifi/lossless-cut#399]
When trying to get the code to run on Windows, I encountered a few hurdles, which I managed to fix.

Disclaimer: I'm not a JS/node dev so I don't know what the proper multi-platform way of fixing this would be, I'm just posting this in case anyone else needs help with this.

Two fixes needed to be made ([link to commit](https://github.com/bgr/lossless-cut/commit/95db306e59ac7bd29f50157484ffbd45ff81055c))

* The following bit had to be adapted to Windows syntax:
`"concurrently -k \"BROWSER=none PORT=3001 react-scripts start\"`
to
` "concurrently -k \"set BROWSER=none&&set PORT=3001&&react-scripts start\"`
(spaces had to be omitted as recommended [here](https://github.com/facebook/create-react-app/issues/873#issuecomment-396803278))
* An error "TypeError: inline_style_prefixer_1.prefix is not a function" would appear when app was run, so I added `"inline-style-prefixer": "^6.0.0"` to package.json

**Comment by mifi** [comment]
Yea Windows has always been the black sheep of open source software development.

1. does it also work on macos/linux? if so then i'm open for a PR
2. I don't understand why adding this dependency without refering to it from anywhere should be needed only on windows

**Comment by mifi** [comment]
See #559
