### ISSUE TITLE
JKL Keys

### ISSUE THREAD

**Issue by Tiim** [mifi/lossless-cut#4]
A nice addition for lossles-cut would be to add `J`, `K`, and `L` shortcuts like most video editors have.

This isn't per se a video editor but I think it would make sense to integrate these shortcuts to find the perfect in/out point easier without using the mouse.

A bit more specific for each shortcut:

   * `K`: act just like the space bar to play/pause the video
   * `L`: start playing at 50% and increase the speed every time pressed.
   * `J`: start playing backwarts at 50% and increase the speed every time pressed.

Keep up the good work :+1:

**Comment by mifi** [comment]
I'm working on this but rewinding might be harder to implement properly.

**Comment by mifi** [comment]
https://github.com/mifi/lossless-cut/commit/2abacd010d5f17edaebe8d7bba6b6d6c4022cb2d

Will be included in next release. Reverse play not implemented
