### ISSUE TITLE
Use external ffmpeg/ffprobe

### ISSUE THREAD

**Issue by soloturn** [mifi/lossless-cut#400]
how could one build / package lossless-cut so operating system installed binaries like ffmpeg, ffprobe will be used?

**Comment by mifi** [comment]
There was a discussion about this in #108

What is the reason for needing to use system installed ffmpeg?

**Comment by soloturn** [comment]
arch linux can install newest electron, ffmpeg.  losslesscut then would not take 337MB as it does now. there is hints how to deal with electron applications: https://wiki.archlinux.org/index.php/Electron_package_guidelines .

**Comment by mifi** [comment]
In order to achieve this we would need to:
1. Make a separate build that excludes the binaries from the bundle
2. Make the ffmpeg/ffprobe executing code fallback to system ffmpeg when not found internally

**Comment by mifi** [comment]
have now added support for selecting a custom ffmpeg/ffprobe path in settings
