### ISSUE TITLE
All exported videos have errors due to incorrect ffmpeg setting

### ISSUE THREAD

**Issue by wallobit** [mifi/lossless-cut#402]
The ffmpeg parameter "-movflags use_metadata_tags" leads to the following errors in the exported videos:

1. Existing tags such as comments are not displayed, but are still in the file. This can be demonstrated by copying the exported data again with "ffmpeg -i inputfile -c copy outputfile". Then they are back. Self-created tags like "MyFavorite=yes" are not displayed at all.

2. For example comments can no longer be written to the damaged file later. You can also demonstrate if you copy the exported file again with "ffmpeg -i inputfile -c copy outputfile". Then comments can be re-entered.

Workaround: Delete the ffmpeg parameter "-movflags use_metadata_tags". So the standard tags such as comments are copied and can also be edited later. However, self-created tags like "MyFavorite=yes" etc. will not be copied. But this mistake was already there before.

The error can be on ffmpeg or there must be a new syntax for copying self-created tags.

**Comment by mifi** [comment]
`use_metadata_tags` was added because of this #99 
maybe that was a mistake...

**Comment by wallobit** [comment]
Mail 2 - Was mein er?
 
Von: Mikael Finstad <notifications@github.com> 
Gesendet: Donnerstag, 9. Juli 2020 13:56
An: mifi/lossless-cut <lossless-cut@noreply.github.com>
Cc: wallobit <wallomail@posteo.de>; Author <author@noreply.github.com>
Betreff: Re: [mifi/lossless-cut] All exported videos have errors due to incorrect ffmpeg setting (#402)
 
use_metadata_tags was added because of this #99 <https://github.com/mifi/lossless-cut/issues/99> 
maybe that was a mistake...

**Comment by mifi** [comment]
In the next version there will be an option to not preserve MOV metadata (disable the `-movflags use_metadata_tags` flag). This should fix your issue.
