### ISSUE TITLE
Exported video capture is slower than audio

### ISSUE THREAD

**Issue by ZombieBrine13092** [mifi/lossless-cut#406]
I've used Lossless Cut only once before, and back when I did, I did not notice that the video in the final export was late until now.

The audio plays just like normal, but the video is started noticeably after the audio is.

I'm not sure if this is just me or not, so don't judge me

Thanks!

JavaScript logs:

![2020-06-15 19_47_00-LosslessCut - Untrimmed GFeX 1080p60 Test mp4](https://user-images.githubusercontent.com/51412993/84717499-f9fd0600-af43-11ea-98a2-9ba1c597a502.png)
![2020-06-15 19_46_11-LosslessCut - Untrimmed GFeX 1080p60 Test mp4](https://user-images.githubusercontent.com/51412993/84717503-fb2e3300-af43-11ea-8f9b-58e983b83187.png)
![2020-06-15 19_46_35-LosslessCut - Untrimmed GFeX 1080p60 Test mp4](https://user-images.githubusercontent.com/51412993/84717504-fbc6c980-af43-11ea-91e4-5fdaea55eed5.png)

**Comment by ZombieBrine13092** [comment]
nevermind, found it

**Comment by mifi** [comment]
How did you solve it?

**Comment by ZombieBrine13092** [comment]
Switched between normal cut and the other one. :/

**Comment by mifi** [comment]
![giphy](https://user-images.githubusercontent.com/402547/87307580-29d70380-c51a-11ea-851d-a726885130aa.gif)
