### ISSUE TITLE
Main app does not fully load when it is located in a path with "#"

### ISSUE THREAD

**Issue by ensisnoctis** [mifi/lossless-cut#408]
I placed LosslessCut executable in a directory in "#" in its name. The application window shows, but never loads the content.

**Comment by mifi** [comment]
Windows?

**Comment by ensisnoctis** [comment]
Yes

czw., 9 lip 2020, 13:43 użytkownik Mikael Finstad <notifications@github.com>
napisał:

**Comment by ensisnoctis** [comment]
Yes, Windows 10.

**Comment by Shakil-Shahadat** [comment]
This issue is now fixed #40.
