### ISSUE TITLE
Voice missing for at least 1 full minute after cut. 

### ISSUE THREAD

**Issue by muhammad-usama-sardar** [mifi/lossless-cut#409]
I wasted much time on this tool. I tried various combinations of the options provided. Each of them has its own problem. Unfortunately, I will not be using any more and now find some other solution. However, it may be useful for you to improve it. 

undefined

{
  "err": {},
  "state": {
    "filePath": "/home/usama/Documents/Conferences/DISCOTEC2020/FOCODILE2020/Usama0-merged.mp4",
    "fileFormat": "mp4",
    "externalStreamFiles": [],
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High 4:4:4 Predictive",
        "codec_type": "video",
        "codec_time_base": "26267/1575960",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 1852,
        "height": 1024,
        "coded_width": 1856,
        "coded_height": 1024,
        "has_b_frames": 0,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "463:256",
        "pix_fmt": "yuv420p",
        "level": 40,
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "30/1",
        "avg_frame_rate": "787980/26267",
        "time_base": "1/15360",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 26897418,
        "duration": "1751.133984",
        "bit_rate": "226199",
        "bits_per_raw_sample": "8",
        "nb_frames": "52532",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "VideoHandler"
        }
      },
      {
        "index": 1,
        "codec_name": "mp3",
        "codec_long_name": "MP3 (MPEG audio layer 3)",
        "codec_type": "audio",
        "codec_time_base": "1/48000",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/48000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 84055680,
        "duration": "1751.160000",
        "bit_rate": "128000",
        "max_bit_rate": "128001",
        "nb_frames": "72965",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "SoundHandler"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "/home/usama/Documents/Conferences/DISCOTEC2020/FOCODILE2020/Usama0-merged.mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {
        "start": 53.902052082540166,
        "end": 63.179327,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            41.84841776487099,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "2e5cd294-4034-4923-b5ff-72c30e618e4b"
      },
      {
        "start": 69.988282,
        "end": 78.426638,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            230.17128650802374,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "1938869e-ab39-4fa9-bf99-0df1c4f30998"
      },
      {
        "start": 113.918581,
        "end": 116.395763,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            292.95841168639777,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "b29a4813-5773-42de-ba0e-49537dfd03ed"
      },
      {
        "start": 131.597393,
        "end": 135.254926,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            222.9737951134489,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "c47745cc-2dd8-4e87-bb20-e4ed0bcf154f"
      },
      {
        "start": 135.67183177238002,
        "end": 274.064794,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            270.69875966717905,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "656d95ba-90bd-4fd2-94df-23fcf66e58e9"
      },
      {
        "start": 276.91247,
        "end": 306.125314,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            126.74678586142795,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "d6594bbe-681a-4bef-99d3-3e0d4ac2f88f"
      },
      {
        "start": 316.24537297900963,
        "end": 370.908865,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            354.50290306399233,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "72f16a04-a68d-4f22-abf0-bf7ba5fbcd76"
      },
      {
        "start": 371.6474821695982,
        "end": 403.225511,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            236.0400402984517,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "f4cb4566-aaa8-44ba-a009-cc66f2840dd1"
      },
      {
        "start": 406.9154915099368,
        "end": 588.2890631741923,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            119.12224760260352,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "b5693826-1055-4ff5-8f8c-9eb5bf551684"
      },
      {
        "start": 599.589493388157,
        "end": 706.654675,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            46.90158461876899,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "478782af-597b-4a9c-94b4-39897849d587"
      },
      {
        "start": 708.6269778420773,
        "end": 747.030158,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            270.6126558638116,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "b501fd5b-b00d-4302-8432-14f9ec328051"
      },
      {
        "start": 763.223302,
        "end": 790.222371,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            250.38742607620327,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "8f2db8d8-fa78-40ad-8090-670c6ee8ac51"
      },
      {
        "start": 799.36992,
        "end": 832.283143,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            179.8749505493672,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "3df80608-3053-44c2-ae18-4e34b9b20351"
      },
      {
        "start": 837.776269,
        "end": 856.023565,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            124.26151825986892,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "2458edf6-c77a-4670-b023-8ee957d0a8b0"
      },
      {
        "start": 864.209433,
        "end": 880.851029,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            256.1791662826927,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "741e240b-f4ac-4722-9505-4e711e12cd06"
      },
      {
        "start": 889.355745,
        "end": 1044.521849,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            219.0827763238044,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "47928f4c-ae8c-49ae-b120-ebc6c9710ebc"
      },
      {
        "start": 1049.270944,
        "end": 1259.988602,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            226.41958659998613,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "7b159968-c892-4e54-bc60-55f52754ebc9"
      },
      {
        "start": 1268.896904,
        "end": 1435.6635,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            253.65539188916432,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "7d7d96a2-a4cd-46e6-9069-92558218614f"
      },
      {
        "start": 1447.7884514835403,
        "end": 1484.638548,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            216.13195506602642,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "9eefebf4-b308-4208-8936-e3d6c651020d"
      },
      {
        "start": 1494.884195,
        "end": 1516.134469,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            169.29959103276474,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "3b24f790-21cd-4319-aab6-beaeac76b3f2"
      },
      {
        "start": 1521.923143,
        "end": 1575.855427,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            337.72346476292114,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "a88cd03a-ca6d-4c20-a4fb-b9e434e538a5"
      },
      {
        "start": 1593.806112,
        "end": 1614.744294,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            345.4873219033525,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "1f673fa2-ae35-4f87-a040-3b563c009683"
      },
      {
        "start": 1646.3817,
        "end": 1702.493015,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            29.493475274172965,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "f9c14e6d-1eea-40f4-88e7-6aa26ae78c77"
      },
      {
        "start": 1711.537842,
        "end": 1745.788906,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            66.5275599353929,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "9dba5d70-4154-4f41-ba5a-88deae0c3bf0"
      }
    ],
    "fileFormatData": {
      "filename": "/home/usama/Documents/Conferences/DISCOTEC2020/FOCODILE2020/Usama0-merged.mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "1751.160000",
      "size": "78654583",
      "bit_rate": "359325",
      "probe_score": 100,
      "tags": {
        "major_brand": "isom",
        "minor_version": "512",
        "compatible_brands": "isomiso2avc1mp41",
        "encoder": "Lavf58.29.100"
      }
    },
    "rotation": 360,
    "shortestFlag": false
  }
}

**Comment by mifi** [comment]
what's they keyframe interval on your video?

**Comment by mifi** [comment]
closing due to no response
