### ISSUE TITLE
Snap can't access /media mount

### ISSUE THREAD

**Issue by derEremit** [mifi/lossless-cut#410]
Hi

I can't access media stored on a mount in /media on ubuntu

quick google found there might be an easy fix

https://askubuntu.com/a/896973

**Comment by PeterMinin** [comment]
In order for the `snap connect` solution to work, the snap itself needs to be modified. Currently it gives an error:
```
$ sudo snap connect losslesscut:removable-media
error: snap "losslesscut" has no plug named "removable-media"
```

From a quick look, I think you need to add `removable-media` to the `plugs` list in your `snapcraft.yaml`.

**Comment by mifi** [comment]
If someone can confirm that works, then I can add it to package.json

```json
{
  "snap": {
    "plugs": ["desktop", "desktop-legacy", "home", "x11", "unity7", "browser-support", "network", "gsettings", "pulseaudio", "opengl", "removable-media"]
  }
}
```

https://www.electron.build/configuration/snap

**Comment by pmartycz** [comment]
Yes, this is the right [interface](https://snapcraft.io/docs/removable-media-interface) for accessing `/media` mounts.

It will however require manual connection by user as demonstrated above by @PeterMinin so a better error message would also be helpful (currently it's just `Unsupported file`).

**Comment by mifi** [comment]
I have fixed the issue where you get Unsupported file in case of the operating system reporting  file doesn't exist (See #451). I'm not sure how to correctly detect the specific error in case of snap permissions.

**Comment by mifi** [comment]
have added removable-media

**Comment by mifi** [comment]
Reopen if not fixed

**Comment by soygabimoreno** [comment]
Hi!
I saw this popup when trying to open a file from a mounted disk on Ubuntu.

![image](https://github.com/mifi/lossless-cut/assets/1880789/43f1f001-2e7d-412e-a2ca-b028aa575026)

**Comment by mifi** [comment]
do you see `removable-media` in the `plugs` list of the app?

**Comment by soygabimoreno** [comment]
> plugs

Thank you for the question, Mikael! TBH, I am not sure where to look at it. I tried looking through the program UI. But not sure if I should see it in another place.

What should be the place to find it out?

**Comment by mifi** [comment]
TBH I'm also not sure because I'm not an expert on snap. but I think somewhere inside the snap app directory/package there should be a config file that has this `plugs` value...

**Comment by soygabimoreno** [comment]
> TBH I'm also not sure because I'm not an expert on snap. but I think somewhere inside the snap app directory/package there should be a config file that has this `plugs` value...

Me neither... I have done a deep search on my computer, but I don't find any `plugs` inside a related file.
Thank you very much, anyway. LosslessCut is awesome!

**Comment by PeterMinin** [comment]
@soygabimoreno, this seems like the user-friendly (i.e. GUI) way to check and configure this: https://snapcraft.io/docs/interface-management#heading--snap-store (just the section "Using a GUI"). In the "Permissions" window look for "Read/write files on removable storage devices" (if their screenshot is fresh enough).

The command-line way would be to open a terminal and type `snap connections losslesscut`, then look for a line that starts with `removable-media`.

**Comment by soygabimoreno** [comment]
You are the one, @PeterMinin!

I didn't have checked that permission.
![image](https://github.com/mifi/lossless-cut/assets/1880789/2575a70d-f79a-4eb3-9cf3-f24143174c9d)

With Kubuntu, it's just to go to Discover (Software Center), select LosslessCut, click "Configure permissions", and ensure `removable-media` is checked.

Now it's working like a charm. :dart:


Thank you so much for the help, Peter and @mifi! :heart:

**Comment by mifi** [comment]
Cool. I wonder if it's possible to give LosslessCut that permission by default. it's already added in the config:
https://github.com/mifi/lossless-cut/blob/166a51d7576597063e98c1405d58ef4299b97fd8/package.json#L426

**Comment by PeterMinin** [comment]
@mifi Looks like this can be done via pre-moderation by your request: https://snapcraft.io/docs/process-for-aliases-auto-connections-and-tracks. I don't have any experience with this, though.

**Comment by mifi** [comment]
woah that's one hell of a process. if anyone wants to do it, i'm happy to do any approvals needed
