### ISSUE TITLE
[Request/Question] Is there lossy-cut version of this app?

### ISSUE THREAD

**Issue by nhantrn** [mifi/lossless-cut#412]
Sorry if this is not on-topic. But I was wondering if there's a lossy-cut version of this app? I want to make precise cut of clips. The normal and keyframe cut modes in this app are not accurate enough. They either create freezeframe or skipping frames. I know it's the nature of lossless reencodeless spits. Making lossy cut would undermine the name of this program, so I was wondering if anyone know of a similar electron app that can do lossy cut?

Or perhaps,  the author can introduce lossy-cut feature? Long shot, but no harm asking :)

**Comment by parasiteoflife** [comment]
#126 & #372

**Comment by nhantrn** [comment]
@parasiteoflife oh nice!
