### ISSUE TITLE
Choose/Disable default conversion method

### ISSUE THREAD

**Issue by happyfilmmaker** [mifi/lossless-cut#414]
1. Currently am working with .TS files that automatically get registered as an unfriendly codec which starts an auto-conversion. However, seeing as other options work better than the default "fastest" setting, It'd be nice to be able to set another option as default when opening files. 

2. It'd also be nice to have the ability to input custom ffmpeg commands. I had a command that for the longest time did something similar to the fast command, and It'd be nice to be able to customize the commands used so that losslesscut can convert to what we've found works well with the losslesscut in our working formats.

**Comment by mifi** [comment]
1. I agree. it's a nice feature to have
2. I've thought about this but I haven't really found a good way to provide custom command options, because there are so many different commands in losslesscut

**Comment by happyfilmmaker** [comment]
Thank you for your comments. I appreciate the work done

I can understand the second option can be difficult to implement. After thinking about it, my thoughts on it would only be good for the initial transcoding process or a single cut, multiple cuts would be difficult i guess.

In the meanwhile I'm just using an older version for cutting straight from .ts. Otherwise, batch converting mkv works with the new one fine.

**Comment by mifi** [comment]
have now implemented a setting to disable the auto convert. as for custom ffmpeg commands, it's tracked in a different issue (i forgot now)
