### ISSUE TITLE
Build RPM on Fedora 32

### ISSUE THREAD

**Issue by ekuester** [mifi/lossless-cut#416]
Perhaps anyone is interested in a SPEC file for building lossless-cut from the tarball. Please strip the .txt extension before using.
[lossless-cut-3.23.7.spec.txt](https://github.com/mifi/lossless-cut/files/4878280/lossless-cut-3.23.7.spec.txt)

**Comment by mifi** [comment]
I'm not sure what you are asking

**Comment by ekuester** [comment]
No asking ... just an addition if anyone likes to compile and build its own RPM file for installation under Fedora or similar distros. Perhaps you can make the file available in your repository, your decision, of course.

**Comment by soloturn** [comment]
what are the dependencies?

**Comment by mifi** [comment]
@soloturn it can't, as of now. See #400

**Comment by ekuester** [comment]
OK, let me explain: my SPEC file is for release v3.23.7 .... for that the dependencies in case of Fedora are yarnpkg (for building) and of course ffmpeg for final installing. The command
`rpmbuild -ba ./rpmnuild/SPECS/lossless-cut-3.23.7.spec`
will build the final rpm package in ./rpmbuild/RPMs/x86_64 as `LosslessCut-3.23.7-1.x86_64.rpm`, if you set up your system as mine with the base folder in `$HOME/rpmbuild` .

**Comment by mifi** [comment]
losslesscut can now use external ffmpeg. i'm not sure what else I can do, so i'll close this due to lack of activity
