### ISSUE TITLE
Feature request: companion tool to process files exported with lossless-cut

### ISSUE THREAD

**Issue by firepol** [mifi/lossless-cut#417]
Use case, I use lossless-cut and I often shoot the last available minute of battery from a nice view, then lowering altitude behind a tree, behind a house or so, until landing. If you think, the shot is kinda boring... but if you "reverse" the shot, meaning you play it reversed (all editors have this feature, to speed up and also to reverse the shot, e.g. in kdenlive: right click clip > change speed > reverse clip) the shot can be really interesting.

My workflow to manage my drone footage is to cut what I don't need with lossless-cut and keep only the footage I need. This saves a lot of space and time later in post-production when I need to find usable parts to use.

To reverse a clip, in ffmpeg the command would be: `ffmpeg -i original.mp4 -vf reverse reversed.mp4` and now I guess I shoot in my legs as I see that this is not an instant operation, but takes a lot of processing time.

Since lossless-cut mission seems not to process files, but simply to cut them, my idea is to add a "companion tool".

Ideally, a queue manager scanning a specific root folder (or several root folders and subfolders, or a simple "db" which can be a txt file, sqlite or whatever) to apply some processing on those clips, e.g. apply a LUT, speed up, speed down, reverse or things like that. It's a different project, but may work very well together with lossless-cut.

Idea, now lossless-cut saves a csv file together with the extracted file. You could save an additional txt file e.g. called exported.mp4.processing and containing the information to process the file, then have a separate program monitoring some specific folders and processing the files as soon as a ".processing" file appears...

Thanks for considering this or for suggesting existing tools that may be used to achieve this goal (maybe there are already some tools that can be used for this, with some little work it could be possible to make some GUI adjustments to lossless-cut to add a dropdown of options when exporting, save the information somewhere as needed, and use existing tool to process that).

**Comment by mifi** [comment]
You mean a single clip video editor? Kind of like the video editor integrated into iPhone Photos? I've been thinking about building something like this but I never really got to it.

![IMG_9559](https://user-images.githubusercontent.com/402547/87308116-06f91f00-c51b-11ea-9ac7-7837d8594a19.jpg)

**Comment by dquinton** [comment]
Ya, this operation would need some processing power.
+1 for the idea of adding fun enhancements to LLcut

**Comment by mifi** [comment]
closing in favor of #372
