### ISSUE TITLE
Allow converting subtitle codec

### ISSUE THREAD

**Issue by soloturn** [mifi/lossless-cut#418]
when cutting an mp4 with mov_text subtitles it does it, the result has the stream, but neither vlc or mpv are able to display it. more reliable is matroska. trying to convert to matroska produced an error though:
```
/usr/share/losslesscut/resources/node_modules/ffmpeg-static/ffmpeg -hide_banner -ss 316.05468 -i m.mp4 -t 4953.48456 -avoid_negative_ts make_zero -c copy -map 0:0 -map 0:1 -map 0:2 -map 0:3 -map 0:4 -map_metadata 0 -movflags use_metadata_tags -ignore_unknown -f matroska -y m-00.05.16.054-01.27.49.539.mkv
```

```
    Stream #0:4(deu): Subtitle: mov_text (tx3g / 0x67337874), 0 kb/s (default)
    Metadata:
      handler_name    : SubtitleHandler
[matroska @ 0x6a95440] Subtitle codec 94213 is not supported.
```

https://newspaint.wordpress.com/2018/06/24/subtitle-codec-94213-is-not-supported/, says: Or, to retain the subtitle information in the Matroska container, it can be converted to the subrip format using the ```-c:s srt``` option.

and this actually makes it work:
```
/usr/share/losslesscut/resources/node_modules/ffmpeg-static/ffmpeg -hide_banner -ss 316.05468 -i m.mp4 -t 4953.48456 -avoid_negative_ts make_zero -c copy -map 0:0 -map 0:1 -map 0:2 -map 0:3 -map 0:4 -map_metadata 0 -movflags use_metadata_tags -ignore_unknown -f matroska -y -c:s srt m-00.05.16.054-01.27.49.539.mkv
```

**Comment by mifi** [comment]
Ohh. Yea I guess subtitle conversion is not necessary a lossy operation, and is probably very fast even though it is a re-encoding, so we might look into that.

**Comment by soloturn** [comment]
@mifi where in the code is this best done?

**Comment by mifi** [comment]
@soloturn I'm not sure I understand what you mean by duration set to 0

**Comment by soloturn** [comment]
the subtitle is displayed for 0 seconds. so it is there but not displayed.

**Comment by mifi** [comment]
I trhink you can do something like this https://superuser.com/questions/1090989/changing-subtitle-format-with-ffmpeg
to convert subtitle format

**Comment by soloturn** [comment]
cool thank you! it works like this. first convert:
```
ffmpeg -i input.mp4 -c copy -map 0 -c:s srt out.mkv
```
then cut with losslesscut.
