### ISSUE TITLE
Feature Request - IOS support (ipad & iphone)

### ISSUE THREAD

**Issue by the123blackjack** [mifi/lossless-cut#419]
The good thing about iphone videos and screen recordings is it would be of same codec and parameters perfect candidates for lossless merging and trimming. Currently lossless trimming is available in photos app and microsoft pix losslessly but not merging.

Please could we have lossless cut in ios

**Comment by mifi** [comment]
I have been thinking about making a simple video tool for iOS/Android (react native), but I haven't had time yet. iPhone's built in lossless video cutting and lossy video editing is really good but it does indeed lack a few features.

**Comment by mifi** [comment]
closing in favor of #818
