### ISSUE TITLE
Some Enhancements - some of which crucial

### ISSUE THREAD

**Issue by alsab200** [mifi/lossless-cut#421]
Hi, thank you again for such a useful tool, I use it very frequently, almost daily..
Here are some requests:
- [x] Major issue: Reordering cut: e.g.  I do 5 cuts in a footage. Then need a 6th cut that should be the 3rd place when merging the cuts. So make the cut - No. 6. then select the option and enter 3 there.. What happens? This No. 6 becomes 3 (OK) No.3 becomes 6 (NOT OK) intead of REORDERING all Cuts so that 3 becomes 4, 4 becomes 5 and so on....
- [x] Also, for reordering cuts, since you have a beautiful UI, instead of asking a number, you can provide a drag and drop option in th eright panel of cuts..
- Cut Labels: There's is an issue of character sets.. I, for instance, use Turkish charecters, and "some" of them arent printed in the file name.. #427
- Speaking of Cuts, I suggested the panel for cuts could be collapsible, and you provided that, thank you.. The reason I suggested that was to be able to work with a bigger size video as much as possible..  Yet currently you gain a very little video size increment on screen.. So instead, a "full screen video" option maybe only  with a single line of playback icons  would do what I intended in the first place.. #543
- [x] MERGING Cuts: With this option the separate cut files are deleted automatically.. For people who need a single merged file that might make them happy.. But for people who need both like me, each time I copy or move separate files to and other folder and then bring them back.. SO, an additional option asking to delete the separate files or not would be very helpful.

**Comment by mifi** [comment]
Have now fixed the ordering

**Comment by mifi** [comment]
For drag drop I'm thinking something like tihs https://codesandbox.io/s/framer-motion-drag-to-reorder-pkm1k
However probably need to support scrolling

**Comment by alsab200** [comment]
Hi, thank you again very much.. Reordering was a huge issue as some others suggested too. The sandbox sample is "perfect"..

Thanks also for allowing to keep the segments for export+merge option..

I think a maximum video screen size request is left pending :) (for annotations and then taking a screenshot of the frame) ..  

an option to collapse/hide or narrowing menu+ timeline etc. could solve the problem..
FYI, Original size is 1920x1080 .. Potplayer's menu+timeline crops it to 1698x954 and LC crops it to 1456x814..
That's why I do my annotations on Potplayer instead of LC..

"pbf" file, I dont know how I can send you one? but when I open it in an IDE, I can see this:

**Comment by alsab200** [comment]
Unfortunately I cant copy paste here, but I can read is like a text file almost with an IDE.. 
then I found some info here: https://github.com/fireattack/chapter_converter
It says:
Format:
First line: [Bookmark]
Other lines: {i}={timestamp_in_ms}*{title}*{some_optional_hash_for_pot_internal_usage}
i starts at 0.
Example:
[Bookmark]
0=1119389*Title1*
1=1154652*Title2*
The above numbers, I changed to show a real example..
When I use "that guys" script.. The EDL file shows: 
1119.3 2
1154.6 2
When I use my script to convert EDL .. the CSV file outcome (for LC) shows:
1119.3  |  1154.6
as a segment..

**Comment by alsab200** [comment]
Sorry, but the stars "*" **before** and **after** Title1 and Title2 disappeared above due to formatting of Github comments ..

**Comment by mifi** [comment]
i added pbf import. will beout in the next version

**Comment by alsab200** [comment]
It's very kind of you. Thank you very much. 
I have only a few left to request/remind .. I hope my requests are not self serving; others will benefit too..
Regarding pbf import I will use it on a daily basis but there's something I realized later..
I do record live TV broadcast and to save time ..  I play the file while being recorded on Potplayer and place bookmarks one for beginning one for the end of the segment for LC.. Many of them during a 2 hour broadcast..
Why Potplayer? That's the only player let me save bookmarks!! that's why..
Then, now, I realized, LC is a video player and may be I wouldn't need PotPlayer at all..
So I tried playing the "ts" file while recording it (with OBS) on LC..
Indeed, it works and I can cut my segments LIVE!! Incredible!..
Yet two issues remain.. 
1- Playing quality is very low I can't even see the timer-skorboard of the game..
2- It only plays a certain fixed amount of the file.. In other words, while being recorded the file grows in size but LC is not reading it unfortunately..
With potplayer, the quality is same as a finished file.. and it will keep playing while the recorded file gets larger..
FYI, it could have been any format but its "ts" because I can play that format with Potplayer while recording..
May be it can help, I checked .. My Potplayer set up is:
Source/SpIitter Filter - MPEG2 TS:   (BOTH WORK SMOOTHLY)
	FFmpeg MPEG2 TS Source/SpIitter 
	Built-in MPEG2 TS Source/SpIitter (Recommended) 

MPEG2: Built-in Decoder (Recommended) 
	 Configuration :
	General Settings 
	Use output queue  YES
	Reduce video frame rate to adapt the rece.„ NO
	Recognition TV and movie interlacing  YES
	Use stream aspect ratio  yes
	Enable Closed Captioning  NO
	H.264 skip Ioop filter. Default 

Hardware acceleration (DXVA) settings:  Use DXVA  NO

Available Video Decoders 
MPEG2/ MPEG4/ H.264/AVC1 H.265/HEVC:  Nvidia CUDA Decoder

Like I said recording with OBS/FFMPEG so any file format which will do the job will also be fine..

Thank you..

**Comment by alsab200** [comment]
While above will be a huge improvement and an asset to LC, I believe, I'd like to make another request I believe would be great regarding UI..
That's to allow a handle to be able to drag both beginning and end of the cut segment ; naturally to shrink/expand a segment.. I presume the video will be stopped-paused and when you drag the video head will move synchronously.. 
Thank you.

**Comment by mifi** [comment]
- I don't think I can implement dynamic reloading of a streamed file as it would be too complicated unfortunately.
- As for playback quality, I have now increased the resolution for the static rendered images so it will be improved inthe next version.
- As for handle to drag cutpoints, see #517

**Comment by alsab200** [comment]
Hi, thanks for "pbf" import..  
I can also see your commit regarding max canvas issue.. For this I didn't tell you to not to mix many ıssues, but I would say, playing with dev tools, I had a "one liner"  like this:

top panel:
height: 22px;

Video div:
    top: 23px;
    left: 0px;
    right: 167px;
    bottom: 31px;
Mute div:
right: 170px;
    bottom: 20px;

right panel:
    width: 166px;
    right: 0px;
    bottom: 31px;
    top: 23px;

bottom panel:
    height: 30px;
	
	1-zoom

	2-timeline:
	position: absolute;
	margin-top: 3px;
    	right: 300px;
    	height: 40px;
    	
	3-play-cut menu
    	position: absolute;    
    	margin-top: 3px;
    	right: 300px;
    	height: 40px;
If that one liner at the bottom could be "adjustable" -again by dragging-  ; say from 30px to 40 px while the size of the icons also growing-shrinking.. it would be great..
By the way, with the adjustments above, the canvas size now grew to 1659x934..

**Comment by alsab200** [comment]
Regarding "dynamic reloading of a streamed file".. I understand.. 
With the other formats than "ts", in Potplayer I could load the file.. then I would hit F5 or something to reload the file while the bookmarks stayed intact..
So, may be it's possible to reload the file (if a stream detected / or as default by an option activated) say with some intervals.. say every 60 sec 30 sec 90 sec etc..  (hitting F5 or something continouosly is pain!)
If the resolution increase you provided is OK, then with the help of above,  this will be satisfactory to work with..

**Comment by alsab200** [comment]
Regarding dragging handles, I don't know what you mean by a modifier key, but dragging just by mouse, gives you the freedom to be away from the keyboard, which is very helpful if you are doing these things while watching games on live TV..
As that gentlemen said, many Software like DaVinci Resolve etc.. allow this while cutting-trimming etc.. and would be really helpful provided the video head moves so that you can see where you are..

**Comment by mifi** [comment]
- dragging Handles: Dragging by mouse only could be a bit problematic because this is already used for scrubbing the timeline. By modifier key I mean holding CTRL/ALT/SHIFT etc while dragging. Or maybe there could be some empty space above segments to drag for scrubbing, to avoid touching the segment handles.
- Auto reloading is I think not something I'm going to implement unfortunately, as it will require regenerating the dummy file each time also, which could take some time.
- full screen mode, I created a feature request #543

**Comment by mifi** [comment]
I have divided this into separate issues. Closing this. can continue discussion under the respective issues (i edited your original post)
