### ISSUE TITLE
Advanced editing (combine cutting and merging multiple files)

### ISSUE THREAD

**Issue by slrslr** [mifi/lossless-cut#423]
Hello,

newbie user, i added an video file .avi, cut new segment i like and then i want to cut next segment from different video file and merge both segments as one video.
what i did was to click "Tracks" and included additional file. But now i do not know how to switch tto that new file so i can cut the segment?

Thank You

**Comment by dquinton** [comment]
I'm not sure about tracks...
What you can do is:
1. (if file formats are similar) merge the two full clips with Merge tool, then work with the new imported clip on the timeline.
2. Work with each clip, save/export what you need from each one, then use the merge tool to stitch them together.

**Comment by mifi** [comment]
like @dquinton says, this needs to be done as separate steps. There isn't support for such complex editing in one timeline.

**Comment by bverkron** [comment]
I would love the ability to do those two workflow steps at once (merge & cutting). This is by FAR the best software I've found to trim / merge gaming clips and I am SO thankful for it. Doing this in 2-3 steps (i.e. merging several clips, opening the merged file, cutting the merged file into segments and re-exporting) is a slight pain. Would be amazing to be able to do it all at once where it just lays the initial individual clips out on the timeline, lets you cut them as you can with a single video file, them merges / exports the final result.

Thanks for making great software!!

**Comment by mifi** [comment]
Closing this as I have gathered info from similar issues like this one and created one feature requests for this with more info: #976
