### ISSUE TITLE
Playback no audio - Windows, .avi, xvid, mp3

### ISSUE THREAD

**Issue by slrslr** [mifi/lossless-cut#424]
Hello,

i am on Windows 10, LC version: 3.23.8

trying to cut a few scenes from .avi file:

Video: Xvid 640x480 29.97fps 770kbps [V: mpeg4 simple profile, yuv420p, 640x480, 770 kb/s]
Audio: MP3 48000Hz stereo 256kbps [A: mp3, 48000 Hz, stereo, 256 kb/s]

But it is hard or to do it without being able to hear the audio. I have to compare times from third party media player and sometimes cut a few times.

Please kindly can you add audio playback support for this basic file type like .avi xvid, mp3 ?

**Comment by mifi** [comment]
try to File -> Convert to supported format "Fastest: Low playback speed". does it help? Related to #445

**Comment by slrslr** [comment]
I forgot which file it was, but found [the file](https://uloz.to/file/ZfrGfypt/hrisna-laska-200-avi) with same video, audio parameters as above and it does not open the file saying it is unsupported file. BUT later, after i quit the LC and start it again, it opened it creating preview file. Then the conversion to supported format and selecting yours mentioned option WORKED to make video with sound. So i will try to remember using this menu option. Can be good if the program would detect no sound and do this conversion automatically upon file opening so noob does not need to discover this conversion option (its alias may be "Fix audio/video issues in preview"?) and use it everytime when no audio is used in preview.

**Comment by mifi** [comment]
sorry for the hideously long delay. If you can link me an exact file with the problem, I can try

**Comment by slrslr** [comment]
Hello, it may be [this file](https://ulozto.net/file/7uSTf1ZHtWLE/hl125-sample-avi) which does not play audio by default.
if not simple to add audio support (Avi, xvid, mp3), then consider following:

May be good if the program would detect no sound and prompt to convert with sound support (or better do this automatically for files <50MB or such

OR

modify pop-up text that appear on unsupported file:
You may convert it from the menu for a better preview with audio.
to something like:
You may convert it from the menu "File -> Convert to supported format" for a preview with audio.

**Comment by mifi** [comment]
I created a new issue about this improvement #827

I also added a new option under "convert to supported format": "Fastest: Low playback speed (audio remux), likely to fail". This will make it much faster to convert files such as your AVI file with mp3 audio, as it will remux the audio to an MKV, and then use the canvas video overlay. Much faster than re-encoding the audio stream as will happen in "Fastest: Low playback speed"

thx for your feedback
