### ISSUE TITLE
Batch Cut Video at Keyframe

### ISSUE THREAD

**Issue by shodesho** [mifi/lossless-cut#429]
Thank you very much for this wonderful software, I just want to know if it is possible to add a feature that can batch cut the video into segmented short videos. Preferably cut at keyframes, but setting a length would be ok too. Cut a segment every x seconds etc.

**Comment by mifi** [comment]
Hi. Why do you need this? I think this is something which can easily be achieved with ffmpeg:
https://medium.com/@taylorjdawson/splitting-a-video-with-ffmpeg-the-great-mystical-magical-video-tool-%EF%B8%8F-1b31385221bd

**Comment by mifi** [comment]
Actually this is now implemented. you can create X segments or 1 segment ever X seconds
