### ISSUE TITLE
Request: offset new audio file in the UI

### ISSUE THREAD

**Issue by vandenbrakel** [mifi/lossless-cut#430]
I use this perfect fast tool to combine external mic recorded audio with camera recorded footage. As I have to align the audio precisely with the video it would be nice to be able to do this in the app. At the moment I find my cue point (hand clap) in the video, crop the audio to start exactly on the clap and the add silence in front of it at the offset of the video clap time.

It works, but sometimes needs three tries to get it right.

Thanks again for this great software.

**Comment by mifi** [comment]
Thanks for your suggestion. I think this is the same as #216 
If not please let me know and I reopen.
