### ISSUE TITLE
Segment panel and timeline improvements

### ISSUE THREAD

**Issue by dquinton** [mifi/lossless-cut#432]
The panel showing segment durations is a good improvement.  Here's some suggestions to make it better - but you'll probably say its already done/in the works!

- [x] Segments should be numbered (in order)
- [x] Segments need to be selectable
- [x] Up/Down buttons in the panel to move a selected segment up or down the order easily
- [x] Labels could be set by clicking somewhere in the segment in panel too.
- [x] Also a [X] remove button in each segment detail box would be handy

(thus only the new Segment button would be needed and that could be moved back under the timeline - or at least these buttons could be a little smaller ?)

- segment details could be editable in the panel - e.g. one can adjust the start/end, increase/decrease duration by a second etc

- [x] Export only selected
Ctrl-click select segments and export them - info at bottom says how many selected and the updated duration.
This might need an Export selected button?

- Overlap error
When segments overlap, there is this error: "Make sure you have no overlapping segments." in the segments panel and then the segments can't be seen in panel, and the segment remove button can't be used to cancel a segment e.g. that was started at the wrong place.
The overlapping segments could be highlighted in the panel to show there's a problem.

But why is overlapping a problem??  If two Keep segments overlap, then surely that means all that area will be kept - if this happens then the program needs to take the start-point of Seg1 and end-point of Seg2 (or last segment in a continuous area)

- [x] New segment
- [x] Shortcut key X to add new
- [x] Shortcut key R to remove (or send to bin?)

- Timeline select
As one can easily click on a segment, is there need for the next/previous buttons under timeline?
OK, can those buttons be moved under the seek buttons, together with start/end set and Add new segment, like this
[Add]  [<-] [->]  [Prev] [Next]  [Discard]
- [x] Shortcut keys for previous/next: K and L 
- [x] Shortcut keys for jump to start/end point: < and > (comma and stop keys)
- [x] [hotkeys change in settings would be good]

- [x] Segment start/end setting
- The two hand-pointing buttons be moved next to each other (as above layout example)
- [x] Shortcut keys to set start/end: [ and ]

- Segment duration
the segments on the timeline could have handles at ends that user drags to incr/decr duration - maybe that breaks simplicity? See #483

- Segment slip
Shift- mouse drag on a segment in timeline could slip the segment up or down on timeline.
This could be very handy! See #483

That's all, thanks!

**Comment by mifi** [comment]
Thanks for your suggestions. I believe that many of these features are already implemented in the nwest version, like segments selectable and numbering, etc.

Are you sure you are running the newest version? If you are, please explain a bit more detailed what you mean by those features.

**Comment by dquinton** [comment]
OK the shortcut keys you have.

One thing that is a little frustrating, at least for mouse control, when I add a new segment -sometimes at an estimated place during playback- moving the mouse across and finding the left edge set button is too much work.  The button sits right next to jump to start which I sometimes click on by mistake

-preferably, the add segment, set left, set right buttons could be together, like underneath the reeking buttons.

**Comment by mifi** [comment]
I'm closing this and moved the remaining features to #392 and #483
