### ISSUE TITLE
Feature request - Crop to aspect ratio or by pixels from edge

### ISSUE THREAD

**Issue by caeldom** [mifi/lossless-cut#433]
For example my video dimensions is 2560 x 1080 and I want to crop to 1920 x 1080 for 16:9 1080p

Similar to croppad in vlc, or handbrake's cropping settings.
https://git.videolan.org/?p=vlc.git;a=blob;f=modules/video_filter/croppadd.c

**Comment by mifi** [comment]
This is not possible to do losslessly. See #372
