### ISSUE TITLE
Lossless cut does nothing on launch

### ISSUE THREAD

**Issue by ChildishGiant** [mifi/lossless-cut#437]
It used to work but no longer does. I download the latest build but had no luck with that either. When run on a command line it closes instantly but when clicked on it takes a while to do nothing. 

![output](https://user-images.githubusercontent.com/13716824/89673957-34997400-d8df-11ea-98d1-1dc441aee8d3.gif)

**Comment by coldimmune** [comment]
3.17.19 just shows a black screen and hangs on video load

Upgraded and cannot seek in video (but it plays and can advance frames manually)

**Comment by mifi** [comment]
@ChildishGiant does it work for you with 3.17.19? When did it stop working? Did you do anything like upgrade antivirus or upgrade your windows?

**Comment by ChildishGiant** [comment]
I've since reinstalled my OS and the very same exe now works so it must have been an environment issue.

**Comment by n8ur** [comment]
I am having the same issue on an updated Linux Mint 19.1 system.  From the command line the program will run once and work fine.  But subsequent attempts to start from the command line simply return to the command line with nothing happening.

**Comment by mifi** [comment]
Closing as stale
