### ISSUE TITLE
Cutting mp4 videos with flac audio

### ISSUE THREAD

**Issue by koopee** [mifi/lossless-cut#439]
I'm having trouble in exporting cuts for videos with flac audio track. Flac audio is still experimental in ffmpeg, but It could be sufficient enough to just add -strict -2 option for flac audio files. Otherwise lossless-cut seems to work fine with these files

I got this video I'm working with by combining mp4 video and flac audio track with ffmpeg like this:

ffmpeg -ss 5.06 -i VID_20200804_172821.mp4 -i wav/SR002MS.WAV -vcodec copy -acodec flac -strict -2 -map 0:0 -map 1:0 merge_1.mp4

----------

Error: Command failed with exit code 1: /snap/losslesscut/35/resources/node_modules/ffmpeg-static/ffmpeg -hide_banner -ss 572.65869 -i merge_1.mp4 -t 237.13693 -avoid_negative_ts make_zero -c copy -map 0:0 -map 0:1 -map_metadata 0 -movflags use_metadata_tags -ignore_unknown -f mp4 -y merge_1-00.09.32.658-00.13.29.795-Tummilla_teill_.mp4
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'merge_1.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.83.100
  Duration: 01:03:42.28, start: 0.000000, bitrate: 21498 kb/s
    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt470bg/bt470bg/smpte170m), 1920x1080, 20000 kb/s, SAR 1:1 DAR 16:9, 30 fps, 30 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: flac (fLaC / 0x43614C66), 48000 Hz, stereo, s32 (24 bit), 1498 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
[mp4 @ 0x6192740] track 1: codec frame size is not set
[mp4 @ 0x6192740] flac in MP4 support is experimental, add '-strict -2' if you want to use it.
Could not write header for output file #0 (incorrect codec parameters ?): Experimental feature
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
    Last message repeated 1 times
    at makeError (/snap/losslesscut/35/resources/app.asar/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/snap/losslesscut/35/resources/app.asar/node_modules/execa/index.js:114:26)

**Comment by koopee** [comment]
Adding '-strict', '-2' to ffmpegArgs solves the problem.

-----------
const ffmpegArgs = [
    '-hide_banner',

    ...inputCutArgs,

    '-c', 'copy',

    ...(shortestFlag ? ['-shortest'] : []),

    ...flatMapDeep(copyFileStreamsFiltered, ({ streamIds }, fileIndex) => streamIds.map(streamId => ['-map', `${fileIndex}:${streamId}`])),
    '-map_metadata', '0',
    // https://video.stackexchange.com/questions/23741/how-to-prevent-ffmpeg-from-dropping-metadata
    ...getMovFlags(outFormat),

    // See https://github.com/mifi/lossless-cut/issues/170
    '-ignore_unknown',

    ...rotationArgs,

    '-f', outFormat, '-strict', '-2', '-y', outPath,
  ];

**Comment by mifi** [comment]
Have you tried "Enable experimental ffmpeg features flag?" under settings? It enables `-strict experimental` which i believe is the same as `-2`

**Comment by koopee** [comment]
> Have you tried "Enable experimental ffmpeg features flag?" under settings? It enables `-strict experimental` which i believe is the same as `-2`

Thank you for the reply! This might be the solution! Yes, indeed, there is a switch for this in version 3.23.7. I'll need to upgrade, though because snap store currently distributes version 3.22.3. This feature is not yet present there.

**Comment by mifi** [comment]
closing for now. can reopen if still an issue
