### ISSUE TITLE
Tools / merge / Include all streams option meaning

### ISSUE THREAD

**Issue by slrslr** [mifi/lossless-cut#440]
Hello,
in v. 3.23.8 is Tools / merge / is a tickbox to inlude all streams, but for a peron who is not audio/video expert, i think this option is questionable. Can be more described (there is enough space on that merge page) or named differently so even noob understand?

**Comment by mifi** [comment]
Thanks. I have now added a help text, which will be included in the next version:

```
If this is checked, all audio/video/subtitle/data tracks will be included. This may not always work for all file types. If not checked, only default streams will be included
```
