### ISSUE TITLE
Implement button to play until end of segment

### ISSUE THREAD

**Issue by andimik** [mifi/lossless-cut#443]
I could not find a button to play the file till the cut end. As I am cutting audio streams (recorded from DAB+) only I'd like to know if the cut end is ok. Therefore, I cannot use the video preview ...

The cut start is very easy to check, on the other hand ...

**Comment by mraxn** [comment]
+1 for this. This is a must-have. I don't know why it's not implemented. When I cut I want to play from the beginning to the end of the cut to see if it's OK. It's a basic feature for any video editing.

**Comment by mifi** [comment]
Not implemented yet because it's not easy to implement in an accurate way. Duplicate of #253
