### ISSUE TITLE
Speed up playback (x2, x3, x4, x8?)

### ISSUE THREAD

**Issue by Linnshet** [mifi/lossless-cut#447]
Speeding up playback would be an extremely useful feature, for when you need to cut long sequences.

**Comment by mifi** [comment]
Doesn't <kbd>L</kbd> cut it?

**Comment by Linnshet** [comment]
Wow, that is amazing! I even thought I tried L, as that would be the logical choice for a shortcut, but apparently I didn't. Thank you, and sorry about that. Great work, this app is a bloody dream!

**Comment by Mae72DE** [comment]
But if I try to slow it down again with 'J' it shows me now "Playback rate: 99%" and not 100% - what can I do to become 100% Playspeed?
'L' speed up to 114% and 'J' speed down to 99% and pressing two times fast 'K' can't help me to come back to 100%
Can't find the Hot-Key to return to 100% Play-speed.
How knows the answer?

**Comment by mifi** [comment]
Oops that's just a mathermatical rounding error, I'll fix that for the next version, thanks.

**Comment by Mae72DE** [comment]
But I found two solutions that work for me:
'Space' starts playing at 100% while 'K' starts playing in the (with ('J'/'L') chosen Speed-Rate.
The other way is to decrease speed to the lowest possible and than I can incrase the speed rain again to 100%.
So fixing may be lower priority - if we can fix the manual: cause I miss that difference between 'Space' and 'K' there.

**Comment by mifi** [comment]
It's already fixed
