### ISSUE TITLE
Start/End Time Edit

### ISSUE THREAD

**Issue by sleepreading** [mifi/lossless-cut#448]
We prefer to replace the old number when we insert a new number! Currently, this action will result in an invalid time format!
We also like to allow the end time is smaller than the start time when we editing the movie because we will correct them after soon!

**Comment by sleepreading** [comment]
![image](https://user-images.githubusercontent.com/7484631/91638051-47ffb100-ea3f-11ea-8213-7fa48c5714d1.png)

**Comment by mifi** [comment]
> We prefer to replace the old number when we insert a new number! Currently, this action will result in an invalid time format!

Care to explain a bit more?

> We also like to allow the end time is smaller than the start time when we editing the movie because we will correct them after soon!

Ok this I can agree

**Comment by sleepreading** [comment]
It's been a long time to come here, sorry about that.

The new version looks great!
