### ISSUE TITLE
MKV File Not Supported?

### ISSUE THREAD

**Issue by gethubguy** [mifi/lossless-cut#45]
Tried to trim a MKV file I made in Handbrake. The error message I get is "this video format is not supported, maybe you can re-format the file first using ffmpeg"

Here's the log
Version 1.8.0
/Applications/LosslessCut.app/Contents/Resources/app.asar/renderer.js:237 Load /Users/UserName/Desktop/FileName.mkv
/Applications/LosslessCut.app/Contents/Resources/app.asar/ffmpeg.js:111 getFormat /Users/UserName/Desktop/FileName.mkv
/Applications/LosslessCut.app/Contents/Resources/app.asar/ffmpeg.js:119 formats matroska,webm
/Applications/LosslessCut.app/Contents/Resources/app.asar/ffmpeg.js:125 fileType detected format {"ext":"mkv","mime":"video/x-matroska"}
/Applications/LosslessCut.app/Contents/Resources/app.asar/renderer.js:418 DOMException: The element has no supported sources.

**Comment by mifi** [comment]
Can you provide a short version of the file? For me mkv files seem to be working.

**Comment by mifi** [comment]
See #68
