### ISSUE TITLE
Request: skip export of previously exported clips

### ISSUE THREAD

**Issue by SignpostMarv** [mifi/lossless-cut#450]
If I'm processing a 2 hour clip in 40 minute bouts, making many sub-five minute clips in amongst the timeline, it would be nice to be able to export and skip export of already exported clips- either by simple filename check, or by sha-2/other reasonable hash check.

**Comment by SignpostMarv** [comment]
@mifi even though the feature has issues with smart cut, is this feature request technically implemented?

**Comment by mifi** [comment]
Yes
