### ISSUE TITLE
[Linux] snap: Cannot access files outside of /home/, misleading error message

### ISSUE THREAD

**Issue by nschloe** [mifi/lossless-cut#451]
When installing losslesscut under Linux via a Snap, it cannot access files outside of the user's home directory (like all snaps). When trying to open a file in `/tmp/`, however, the UI says
```
Unsupported file
```
This had me pulling my hair out for a file, so perhaps the error message can be improved. 

Note that the developer console says
```
/tmp/video.mp4: No such file or directory
```

**Comment by mifi** [comment]
aw snap! so did you manage to solve the underlying issue? so the problem is only that the message is misleading?

**Comment by nschloe** [comment]
The underlying issue is [a snap "bug"](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1643706), but I don't know if it will ever be resolved. The error message should be clearer indeed.

**Comment by mifi** [comment]
I'm not sure how I can make llc support /tmp, but I will fix the issue with unsupported file

**Comment by mifi** [comment]
Could be related to #410

**Comment by mifi** [comment]
LLC will now check for permission to open file before opening it, so this should be resolved
