### ISSUE TITLE
 Inaccurate cuts

### ISSUE THREAD

**Issue by franktntx** [mifi/lossless-cut#454]
Hello, I try to make small cuts but, when I check the cuts they are larger and not the ones I have made

**Comment by bryc** [comment]
That is a common problem with low quality internet videos. You can only cut between **key frames**, because keyframes contain the complete image. A lot of videos spread key frames over multiple seconds, so you have no choice of where it starts.

Using the accurate cut option, you can technically cut between key frames, but any partial frames before the next key frame will not be visible, and will show as gaps or 'lag' in the resulting video.

Also you cannot add key frames without re-encoding it specifically to add more frequent key frames, so it defeats the purpose.

So you must make cuts based on the key frames (black lines in the timeline),

**Comment by franktntx** [comment]
> Ese es un problema común con los videos de Internet de baja calidad. Solo puede cortar entre **fotogramas clave** , porque los fotogramas clave contienen la imagen completa. Muchos videos distribuyen fotogramas clave en varios segundos, por lo que no tiene opción de dónde comienza.
> 
> Con la opción de corte preciso, técnicamente puede cortar entre fotogramas clave, pero los fotogramas parciales antes del siguiente fotograma clave no serán visibles y se mostrarán como espacios o "retrasos" en el video resultante.
> 
> Esta es una limitación sobre cómo funciona la compresión de video, porque solo se almacenan diferencias parciales entre fotogramas clave, por lo que comenzaría con una imagen incompleta y distorsionada. Por lo tanto, debe realizar cortes basados ​​en los fotogramas clave (líneas negras en la línea de tiempo),
> 
> Además, en caso de que se lo pregunte, no puede agregar fotogramas clave sin volver a codificarlos específicamente para agregar fotogramas clave más frecuentes, por lo que frustra el propósito; también podría usar un editor diferente si debe comenzar en un fotograma delta, porque volver a Se requiere codificación.


I tried to cut snippets from a screenshot in Obs Studio

**Comment by franktntx** [comment]
> Ese es un problema común con los videos de Internet de baja calidad. Solo puede cortar entre **fotogramas clave** , porque los fotogramas clave contienen la imagen completa. Muchos videos distribuyen fotogramas clave en varios segundos, por lo que no tiene opción de dónde comienza.
> 
> Con la opción de corte preciso, técnicamente puede cortar entre fotogramas clave, pero los fotogramas parciales antes del siguiente fotograma clave no serán visibles y se mostrarán como espacios o "retrasos" en el video resultante.
> 
> Esta es una limitación sobre cómo funciona la compresión de video, porque solo se almacenan diferencias parciales entre fotogramas clave, por lo que comenzaría con una imagen incompleta y distorsionada. Por lo tanto, debe realizar cortes basados ​​en los fotogramas clave (líneas negras en la línea de tiempo),
> 
> Además, en caso de que se lo pregunte, no puede agregar fotogramas clave sin volver a codificarlos específicamente para agregar fotogramas clave más frecuentes, por lo que frustra el propósito; también podría usar un editor diferente si debe comenzar en un fotograma delta, porque volver a Se requiere codificación.


Thanks a lot, cut with keyframes and it worked! :)

**Comment by franktntx** [comment]
Is there a way to increase keyframes in obs studio?

**Comment by Pentaphon** [comment]
> Is there a way to increase keyframes in obs studio?

Yes. It's in the encoding options.
