### ISSUE TITLE
Feature request: Import cuesheet files (.cue) as segments

### ISSUE THREAD

**Issue by r-a-y** [mifi/lossless-cut#458]
Hi, great app!

I was wondering if it would be possible to import .cue files as segments. It would be very handy for those of us that have rather long audio files, but have already prepared cuesheets and now want to split the long track into individual files.

If you are not familiar with cuesheets, you can read up on it here: https://wiki.hydrogenaud.io/index.php?title=Cue_sheet

In the example file:

```
REM GENRE Alternative
REM DATE 1991
REM DISCID 860B640B
REM COMMENT "ExactAudioCopy v0.95b4"
PERFORMER "My Bloody Valentine"
TITLE "Loveless"
FILE "My Bloody Valentine - Loveless.wav" WAVE
  TRACK 01 AUDIO
    TITLE "Only Shallow"
    PERFORMER "My Bloody Valentine"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "Loomer"
    PERFORMER "My Bloody Valentine"
    INDEX 01 04:17:52
```

The relevant cut points would be the `INDEX` tags. So the first segment would be `00:00:00 - 04:17:52` and the second segment would be `04:17:52 - whatever the third index is or end of track`.

There's already software that handles splitting cuesheets, but they are usually only for `.wav` and `.mp3`. Since LosslessCut already has a nice interface for segments and can handle any audio format that ffmpeg can support (for the most part), this would be a great feature to add.

Thanks for considering!

**Comment by bouscram** [comment]
Good idea. I think that simple text chapter files (as used in Apple .m4v files) could be supported also... 
`00:00:34.000 1st song`
`00:06:21.000 2nd song`
`00:09:12.000 Last song`

**Comment by mifi** [comment]
nice suggestion. shouldn't be too hard.

**Comment by mifi** [comment]
this one is now implemented. will be out in the next version!
