### ISSUE TITLE
Split segment function

### ISSUE THREAD

**Issue by dquinton** [mifi/lossless-cut#460]
I meet a problem when I have set a segment covering, for example, 3 min of time, with delete segment mode on, and then I see some content that I don't want deleted inside that time set as delete segment.

How do I then clear that piece inside segment so it is not deleted?  Well if I have to I will reset the segment end and add another segment after the piece to keep.  But then I have to find the end of the original segment again.  And what if I need to do this for ten segments?

Could there be a 'split segment' button? So segment A becomes B &C, and then need to set end of B and start of C, but end of C is still set from previous end of A.

**Comment by mifi** [comment]
Good idea

**Comment by RobCrossRC** [comment]
Hi, thanks for the excellent work on Lossless which I find to be very useful. I would agree with this post as I sometimes edit Videos then re-edit to a new version with just the very best bits in depending on what I'm using it for. 
What would be really useful for me too in addition, would be something like an option to always export segments in the chronological order of the original. So for example if I make a few edits and export then create a new segment between 1 and 2 in a series of 6, that segment becomes 7 when I'd want it to be 2 and the others move up a number. With the segments identified by start time would it be possible for the new option to then sort them by start time before exporting?
Thanks and best wishes

**Comment by mifi** [comment]
Split segment by cursor is now implemented and can be tested in the next release. @RobCrossRC I'm not sure I understand what you are asking about the chronological order. Are you talking about the export+merge function?

**Comment by RobCrossRC** [comment]
Hi Mikael,
Thanks for the update, I've downloaded 3.24.0 and like the new split
function..
So for me yes I was talking about the export + merge function, I've mocked
up a sample below of how I often end up with my edited videos before I
export and merge them.
What I would like would be a simple option to export and merge in the
chronological order of the original which in this case would be
1,4,6,5,2,3. I guess the easiest way to do that would be a setting to
always export and merge sorted by the start time of each segment. I think
most people would not want this to be the default and may edit videos in a
way they want them to be exported and merged as happens today so a choice
(setting option) to do as I would like or as per happens today maybe the
best way to achieve this?

I know I can re-number the segments but this does take some time and
occasionally I may forget which leaves the end result not always what I
wanted

Fantastic piece of software though, I'll be happy to contribute to your
work,

Cheers
Rob

[image: Lossless Cut Screenshot.jpg]

**Comment by RobCrossRC** [comment]
I emailed the screenshot to you so you should have that if it helps, thanks.

**Comment by mifi** [comment]
Thanks. I couldn't see your emailed image but I think I understand.
Could this be solved by just having a menu button that lets you reorder all segments by time?

**Comment by mifi** [comment]
It was easy to implement a reorder function so I just implemented that. Will be included in the next version under Tools menu

**Comment by RobCrossRC** [comment]
Hi,
Yes both reorder function or menu button would work, but would always need 
to be selected.
For me personally I would have preferred an option setting to reorder that 
was remembered each relaunch.

This would have saved me needing to click on something I might forget from 
time to time but I understand that you need to take into account all of the 
users

Cheers
Rob

**Comment by RobCrossRC** [comment]
Hi again,
I've just downloaded 3.26.0 with the re-order function in and this does
exactly what I wanted it to do.
However it's a bit hidden under the menus. As mentioned in the previous
email for me this would have been something I would have liked as an option
that would stay set. If this isn't the way you want to make it could you at
least assign a shortcut key combination to it please 👍
Thanks
Rob

**Comment by mifi** [comment]
There are a lot of hotkeys requested. I will add the hotkey suggestion here: #254 please leave a vote there 👍

**Comment by slrslr** [comment]
@mifi I am unsure where to find an option that was added thanks to this issue and I am possibly missing similar function as OP:

For example, an option inside Edit menu / Segment / to "Split currently active segment into two segments" which would cut segment at cursor frame (currently active/previewed frame) into 2 segments. Is it good idea? Thank you

**Comment by mifi** [comment]
you can use the <kbd>B</kbd> hotkey or press this button under "segments to export":

<img width="31" alt="Screenshot 2023-10-29 at 23 57 00" src="https://github.com/mifi/lossless-cut/assets/402547/9c66666b-70ba-4109-8e5c-326f4aeec0da">

**Comment by slrslr** [comment]
Indeed, thank you 👍 I have not expected the split segment option in the segment list, instead inside menu, next to the merge option, where it is missing.
[![lc.webp](https://i.postimg.cc/wjpMb4mD/lc.webp)](https://postimg.cc/xc69XRgd)

**Comment by mifi** [comment]
right, i will add it to that menu too, thanks!
