### ISSUE TITLE
GoPro 2,k Video File (4223x2704) gets downsampled to 1520x2704

### ISSUE THREAD

**Issue by FrankyDE** [mifi/lossless-cut#461]
I bought Lossless-Cut, as I have much MP4 Files hight resolution from my GoPro.
The Videos are shot in 2,7K and most of the time I just need 30 Seconds from a 3 Minute Video.
So I needed a cutting tool, that just saves the required part losslessly.
But when I cut a file, the resolution seems to decrease,
GoPro 2,k Video File (4223x2704) gets downsampled to 1520x2704

4223 x 2704 Original
1520 x 2704 Clip

![2020-09-18_11-50-10](https://user-images.githubusercontent.com/1822359/93584155-3574f980-f9a5-11ea-9cfe-4d10233cefbe.jpg)

1520 x 2704 Clip
![2020-09-18_11-50-20](https://user-images.githubusercontent.com/1822359/93584165-39a11700-f9a5-11ea-9e77-94c06d321835.jpg)

**Comment by FrankyDE** [comment]
Any of you has an idea, why that happens?

**Comment by mifi** [comment]
That's odd. LosslessCut doesn't do any re-encoding so the resolution shouldn't change. Is it possible to share a short input file?

**Comment by mifi** [comment]
closing due to lack of response
