### ISSUE TITLE
Feature Request: separate working & output directories

### ISSUE THREAD

**Issue by MarkKahn** [mifi/lossless-cut#464]
See title.  I don't want all the .csv, .mkv files polluting my projects, but it'd be nice to output directly to my project folder

**Comment by mifi** [comment]
The csv files you can disable by going to settings and unchecking the `Auto save project` checkbox. Does that help?

The mkv files should be auto deleted when you close the file. If not then that might be a bug.

**Comment by mifi** [comment]
Project file (LLC) will now be saved next to the source file, see #905
