### ISSUE TITLE
Ubuntu snap: wrong "unsupported file" message

### ISSUE THREAD

**Issue by FMuro** [mifi/lossless-cut#465]
Hi. First of all, thanks a lot for this sort of Swiss knife for my family videos. I wanted to report that, upon startup, the application (installed in Ubuntu as a snap) shows an "unsupported file" message which is probably unintented, as no video file has been loaded. See screenshot. 

![Screenshot from 2020-09-30 13-34-42](https://user-images.githubusercontent.com/17141976/94680552-381b0b80-0322-11eb-9a90-145d1635520a.png)

Also, the snap version is a little bit outdated. There's even a message about it in the menu bar.

**Comment by mifi** [comment]
Could you check the developer tools output log and see what file path it tries to open? (I believe ctrl+alt+I)

**Comment by FMuro** [comment]
Error: Command failed with exit code 1: /snap/losslesscut/35/resources/node_modules/ffprobe-static/bin/linux/x64/ffprobe -of json -show_format -i --no-sandbox
ffprobe version 4.0.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2007-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
--no-sandbox: No such file or directory
{

}
    at makeError (/snap/losslesscut/35/resources/app.asar/node_modules/execa/lib/error.js:58)
    at handlePromise (/snap/losslesscut/35/resources/app.asar/node_modules/execa/index.js:114)
    at async K (main.0a57e3a0.chunk.js:1)
    at async file:/snap/losslesscut/35/resources/app.asar/build/static/js/main.0a57e3a0.chunk.js:1
(anonymous) @ main.0a57e3a0.chunk.js:1

**Comment by mifi** [comment]
Aha! Seems like the same issue as #357 
Do you have the nwest version?

**Comment by FMuro** [comment]
I have the latest stable snap (version 3.22.3), which doesn't seem to be the latest version. Could you please update the snap. Thanks!

**Comment by mifi** [comment]
Have updated the snap now,thanks
