### ISSUE TITLE
feature request: save dialog responses

### ISSUE THREAD

**Issue by MarkKahn** [mifi/lossless-cut#467]
I'm cutting a few hundred videos apart, I *never* want to "include all tracks from the new file".  Would love to see a "save this response" option on popups, or even have them all in the settings

**Comment by MarkKahn** [comment]
Oh, and the same to notifications.  None of my files appear to be natively supported... It's frustrating seeing that every few seconds

**Comment by robozb** [comment]
> I'm cutting a few hundred videos apart, I _never_ want to "include all tracks from the new file". Would love to see a "save this response" option on popups, or even have them all in the settings

I agree with you

**Comment by mifi** [comment]
I agree that we could improve this, but you can always just CTRL+W before opening the new file, then you will not get this message

**Comment by mifi** [comment]
open dialog option has been added to settings. will be out in the next version!

**Comment by mifi** [comment]
I added a setting to hide common information notifications
