### ISSUE TITLE
feature request: file time offsets

### ISSUE THREAD

**Issue by MarkKahn** [mifi/lossless-cut#468]
Just a random feature request: When cutting a file, can you offset the creation time of the new files by the start of the cut time?

e.g.

Source: created: 12:00:00pm

Cut from 2:00-3:00, created should be 12:02:00pm

**Comment by mifi** [comment]
we already do that but I believe not when merging files. Am I right? See #487

**Comment by mifi** [comment]
We already set the modified date to input + offset. Isn't that good enough?

**Comment by mifi** [comment]
this has now been implemented and will be out in the next version

**Comment by slaughtering** [comment]
> We already set the modified date to input + offset. Isn't that good enough?

But created time seemed to be more reasonable, esp for raw video.

**Comment by mifi** [comment]
I dont think it’s possible to change creation time of a file
