### ISSUE TITLE
UI issues with long videos

### ISSUE THREAD

**Issue by taxschool** [mifi/lossless-cut#473]
Working with an approximately 9-hour mp4 file (course recording). In order to see a usable audio waveform, I have to set the zoom level to 256x, and even then it's not persistent. The audio waveform only appears on portions of the screen immediately surrounding the point where I click.

When the mp4 loads it automatically jumps to a point approximately 3 hours and 50 minutes in. When I click the "Jump to start of video" button to go to the beginning, it does so, but any subsequent click in the timeline, no matter where, jumps be back to the middle of the video, so I cannot do any edits in the initial portion of the video. Additionally, there's no audio waveform display at that point.

If I change the zoom scale to 128x, it's a little better, but again I only see a waveform display surrounding the points where I click, which is not useful as the whole point of the editing I am doing is to remove silent pieces, so I need to be able to see them, not play hunt-and-click in order to determine where they are in the video.

**Comment by mifi** [comment]
Ohh. so the timeline marker doesn't work properly with your file? Sounds like it's somehow misinterpreting the duration of your file. does this happen with all files or only files from a particular program or recorder?

**Comment by mifi** [comment]
closing due to lack of response
