### ISSUE TITLE
Error Converting MP4 to WebM

### ISSUE THREAD

**Issue by Blootrix** [mifi/lossless-cut#475]
Error occurred when trying to convert MP4 to WebM.
Tried all WebM formats and none worked.
Converting to MOV worked fine, but that doesn't offer the compression WebM does so isn't useful.
Thanks in advance!

Error: Command failed with exit code 1: C:\Users\Bloo\AppData\Local\Temp\1eT1HcFvyBM1bf4oP07nJ3pk5Ve\resources\node_modules\ffmpeg-static\ffmpeg.exe -hide_banner -i D:\Livestreaming\Highlight Reel\Highlights\2.mp4 -avoid_negative_ts make_zero -c copy -map 0:0 -map 0:1 -map_metadata 0 -movflags use_metadata_tags -ignore_unknown -f webm -y D:\Livestreaming\Highlight Reel\Temp\2-00.00.00.000-00.00.11.733.webm
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'D:\Livestreaming\Highlight Reel\Highlights\2.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    creation_time   : 2020-06-25T23:58:46.000000Z
  Duration: 00:00:11.73, start: 0.000000, bitrate: 16307 kb/s
    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080, 16013 kb/s, 60 fps, 60 tbr, 60k tbn, 120 tbc (default)
    Metadata:
      creation_time   : 2020-06-25T23:58:46.000000Z
      handler_name    : ?Mainconcept Video Media Handler
      encoder         : AVC Coding
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s (default)
    Metadata:
      creation_time   : 2020-06-25T23:58:46.000000Z
      handler_name    : #Mainconcept MP4 Sound Media Handler
[webm @ 000001c905020980] Only VP8 or VP9 or AV1 video and Vorbis or Opus audio and WebVTT subtitles are supported for WebM.
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
    Last message repeated 1 times
    at makeError (C:\Users\Bloo\AppData\Local\Temp\1eT1HcFvyBM1bf4oP07nJ3pk5Ve\resources\app.asar\node_modules\execa\lib\error.js:58:11)
    at handlePromise (C:\Users\Bloo\AppData\Local\Temp\1eT1HcFvyBM1bf4oP07nJ3pk5Ve\resources\app.asar\node_modules\execa\index.js:114:26)
    at async _ (file:///C:/Users/Bloo/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/main.437c0011.chunk.js:1:4342)
    at async L (file:///C:/Users/Bloo/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/main.437c0011.chunk.js:1:5024)
    at async file:///C:/Users/Bloo/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/main.437c0011.chunk.js:1:127583

{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "filePath": "D:\\Livestreaming\\Highlight Reel\\Highlights\\2.mp4",
    "fileFormat": "webm",
    "externalStreamFiles": [],
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_time_base": "1/120",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1088,
        "has_b_frames": 1,
        "pix_fmt": "yuv420p",
        "level": 42,
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "60/1",
        "avg_frame_rate": "60/1",
        "time_base": "1/60000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 702000,
        "duration": "11.700000",
        "bit_rate": "16013338",
        "bits_per_raw_sample": "8",
        "nb_frames": "702",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "creation_time": "2020-06-25T23:58:46.000000Z",
          "language": "eng",
          "handler_name": "Alias Data Handler",
          "encoder": "AVC Coding"
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_time_base": "1/48000",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/48000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 561600,
        "duration": "11.700000",
        "bit_rate": "317375",
        "max_bit_rate": "344250",
        "nb_frames": "550",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "creation_time": "2020-06-25T23:58:46.000000Z",
          "language": "eng",
          "handler_name": "Alias Data Handler"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "D:\\Livestreaming\\Highlight Reel\\Highlights\\2.mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {}
    ],
    "fileFormatData": {
      "filename": "D:\\Livestreaming\\Highlight Reel\\Highlights\\2.mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "11.733333",
      "size": "23917267",
      "bit_rate": "16307227",
      "probe_score": 100,
      "tags": {
        "major_brand": "mp42",
        "minor_version": "0",
        "compatible_brands": "mp42mp41",
        "creation_time": "2020-06-25T23:58:46.000000Z"
      }
    },
    "rotation": 360,
    "shortestFlag": false
  }
}

**Comment by mifi** [comment]
Hi. WebM doesn't support these codecs. You can try Matroska (mkv)

`Only VP8 or VP9 or AV1 video and Vorbis or Opus audio and WebVTT subtitles are supported for WebM.`

**Comment by mifi** [comment]
See #547
