### ISSUE TITLE
Can't cut a specific file. Timeline scrubbing doesn't respond, nor manual time entry

### ISSUE THREAD

**Issue by EladKarni** [mifi/lossless-cut#477]
![image](https://user-images.githubusercontent.com/39969481/95812419-56e6ae00-0ce3-11eb-8103-a7cd502fb7cb.png)
![image](https://user-images.githubusercontent.com/39969481/95812683-f5730f00-0ce3-11eb-9b8f-49cfea1bdeda.png)

I attached the logs you requested. LosslessCut seems to be unable to scrub the timeline for a specific file, and crashes when trying to input the times manually.

The file is 12GB and I only need 1/8 of that, which is why I want to use LosslessCut.

File plays, but when I try to add a cut, it fails, even if I wait to get the the point in the video I need.

Any ideas?

Error Code:
```
TypeError: Expected a finite number
    at e.exports (file:///C:/Users/eladk/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/2.8b42b57b.chunk.js:2:529149)
    at file:///C:/Users/eladk/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/main.437c0011.chunk.js:1:82220
    at Array.map (<anonymous>)
    at file:///C:/Users/eladk/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/main.437c0011.chunk.js:1:81226
    at co (file:///C:/Users/eladk/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/2.8b42b57b.chunk.js:2:641405)
    at Wo (file:///C:/Users/eladk/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/2.8b42b57b.chunk.js:2:649670)
    at Yo (file:///C:/Users/eladk/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/2.8b42b57b.chunk.js:2:649489)
    at Os (file:///C:/Users/eladk/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/2.8b42b57b.chunk.js:2:690143)
    at ml (file:///C:/Users/eladk/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/2.8b42b57b.chunk.js:2:672244)
    at fl (file:///C:/Users/eladk/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/2.8b42b57b.chunk.js:2:672169)

{
  "err": {}
}
```

**Comment by mifi** [comment]
I think this is caused by an unsupported file which has a duration of 0. What kind of file is it?

**Comment by EladKarni** [comment]
> I think this is caused by an unsupported file which has a duration of 0. (reported by ffmpeg) What kind of file is it?

It is a standard OBS recording, that is just longer than most normal recordings I do (about 2h). That being said, I have used LosslessCut with a 3h recording in the past, so I don't know why it isn't working.

**Comment by mifi** [comment]
Could you try Help -> Report an error and then provide the data from there? (after opening the file)

I tried recording with OBS just now and for me it works fine

**Comment by mifi** [comment]
I have managed to reproduce the problem with "live"/streaming webm files.
These files can be created like this:

```bash
ffmpeg -i some_video.webm -c copy -f webm - > live.webm
```

this creates a webm file without a header, which is playable in certain players but does not have a duration set.

```bash
ffprobe -show_format -i live.webm

[FORMAT]
filename=/Users/mifi/out.webm
nb_streams=2
nb_programs=0
format_name=matroska,webm
format_long_name=Matroska / WebM
start_time=0.000000
duration=N/A
size=219221
bit_rate=N/A
probe_score=100
TAG:encoder=Lavf55.8.100
TAG:creation_time=2012-11-10T12:34:56.789123Z
[/FORMAT]
```

note `duration=N/A`.

I found this https://stackoverflow.com/questions/34118013/how-to-determine-webm-duration-using-ffprobe

**Comment by mifi** [comment]
A qucik fix is to run this command on your file before opening in losslesscut:
```
ffmpeg -i input.webm -vcodec copy -acodec copy out.webm
```

I will implement this function inside LC

**Comment by mifi** [comment]
implemented in 3.25.0

**Comment by EladKarni** [comment]
My video was an mkv, so I don't know if that changes anything. I don't know how to recreate it cause I don't have the original file anymore. I just know it was mkv, cause that's the only format OBS exports for me. Apologies for the delayed response!

Regardless, this is great new! I can't tell you how much I appreciate you going the extra mile to solve this issue. Sorry I wasn't much help 😞 Do you have a donation area? I can only throw a few bucks your way, but I at least want to do something.

**Comment by mifi** [comment]
Click the sponsor  button on the top of github. If you cannot afford to donate, then don't worry about it :)
