### ISSUE TITLE
Will cut end of video but not start - Ubuntu 20.04 - 3.23.8

### ISSUE THREAD

**Issue by devyzr** [mifi/lossless-cut#478]
﻿At startup the following is shown, this is for the snap version, but I have the same problem downloading the tarball.

Version 3.23.8
2.8b42b57b.chunk.js:2 react-i18next:: i18n.languages were undefined or empty undefined
y @ 2.8b42b57b.chunk.js:2
DevTools failed to parse SourceMap: file:///snap/losslesscut/47/resources/app.asar/build/static/js/2.8b42b57b.chunk.js.map
DevTools failed to parse SourceMap: file:///snap/losslesscut/47/resources/app.asar/build/static/js/main.117ae403.chunk.js.map
DevTools failed to parse SourceMap: file:///snap/losslesscut/47/resources/app.asar/node_modules/human-signals/build/src/main.js.map
DevTools failed to parse SourceMap: file:///snap/losslesscut/47/resources/app.asar/node_modules/human-signals/build/src/signals.js.map
DevTools failed to parse SourceMap: file:///snap/losslesscut/47/resources/app.asar/node_modules/human-signals/build/src/core.js.map
DevTools failed to parse SourceMap: file:///snap/losslesscut/47/resources/app.asar/node_modules/human-signals/build/src/realtime.js.map
DevTools failed to parse SourceMap: file:///snap/losslesscut/47/resources/app.asar/node_modules/strtok3/lib/index.js.map
DevTools failed to parse SourceMap: file:///snap/losslesscut/47/resources/app.asar/node_modules/strtok3/lib/FsPromise.js.map
DevTools failed to parse SourceMap: file:///snap/losslesscut/47/resources/app.asar/node_modules/strtok3/lib/core.js.map
DevTools failed to parse SourceMap: file:///snap/losslesscut/47/resources/app.asar/node_modules/strtok3/lib/ReadStreamTokenizer.js.map
DevTools failed to parse SourceMap: file:///snap/losslesscut/47/resources/app.asar/node_modules/strtok3/lib/AbstractTokenizer.js.map
DevTools failed to parse SourceMap: file:///snap/losslesscut/47/resources/app.asar/node_modules/peek-readable/lib/index.js.map
DevTools failed to parse SourceMap: file:///snap/losslesscut/47/resources/app.asar/node_modules/peek-readable/lib/EndOfFileStream.js.map
DevTools failed to parse SourceMap: file:///snap/losslesscut/47/resources/app.asar/node_modules/strtok3/lib/BufferTokenizer.js.map
DevTools failed to parse SourceMap: file:///snap/losslesscut/47/resources/app.asar/node_modules/strtok3/lib/FileTokenizer.js.map
DevTools failed to parse SourceMap: file:///snap/losslesscut/47/resources/app.asar/build/static/css/main.3276fdc4.chunk.css.map

Then, after specifying start and end times for the cut, this is displayed:
Load {fp: "/home/coconut/Pictures/simplescreenrecorder-2020-10-13_17.22.30.mp4", cod: undefined, html5FriendlyPathRequested: undefined, dummyVideoPathRequested: undefined}
main.117ae403.chunk.js:1 getFormatData /home/coconut/Pictures/simplescreenrecorder-2020-10-13_17.22.30.mp4
main.117ae403.chunk.js:1 ffprobe -of json -show_format -i '/home/coconut/Pictures/simplescreenrecorder-2020-10-13_17.22.30.mp4'
main.117ae403.chunk.js:1 formats mov,mp4,m4a,3gp,3g2,mj2
main.117ae403.chunk.js:1 fileType detected format {"ext":"mp4","mime":"video/mp4"}
main.117ae403.chunk.js:1 ffprobe -of json -show_entries stream -i '/home/coconut/Pictures/simplescreenrecorder-2020-10-13_17.22.30.mp4'
main.117ae403.chunk.js:1 ffprobe -v error -read_intervals '0%30' -show_packets -select_streams 0 -show_entries 'packet=pts_time,flags' -of json '/home/coconut/Pictures/simplescreenrecorder-2020-10-13_17.22.30.mp4'
main.117ae403.chunk.js:1 ffprobe -v error -read_intervals '0%31.997275204359674' -show_packets -select_streams 0 -show_entries 'packet=pts_time,flags' -of json '/home/coconut/Pictures/simplescreenrecorder-2020-10-13_17.22.30.mp4'
main.117ae403.chunk.js:1 Saving /home/coconut/Pictures/simplescreenrecorder-2020-10-13_17.22.30-llc-edl.csv
main.117ae403.chunk.js:1 ffprobe -v error -read_intervals '0%32.99591280653951' -show_packets -select_streams 0 -show_entries 'packet=pts_time,flags' -of json '/home/coconut/Pictures/simplescreenrecorder-2020-10-13_17.22.30.mp4'
main.117ae403.chunk.js:1 Saving /home/coconut/Pictures/simplescreenrecorder-2020-10-13_17.22.30-llc-edl.csv
main.117ae403.chunk.js:1 ffprobe -v error -read_intervals '0%42.44968210717529' -show_packets -select_streams 0 -show_entries 'packet=pts_time,flags' -of json '/home/coconut/Pictures/simplescreenrecorder-2020-10-13_17.22.30.mp4'
main.117ae403.chunk.js:1 Saving /home/coconut/Pictures/simplescreenrecorder-2020-10-13_17.22.30-llc-edl.csv

Finally, when exporting: 
Exporting from 3 to 12.434
main.117ae403.chunk.js:1 ffmpeg -hide_banner -ss '3.00000' -i '/home/coconut/Pictures/simplescreenrecorder-2020-10-13_17.22.30.mp4' -t '9.43400' -avoid_negative_ts make_zero -c copy -map '0:0' -map_metadata 0 -movflags use_metadata_tags -ignore_unknown -f mp4 -y '/home/coconut/Pictures/simplescreenrecorder-2020-10-13_17.22.30-00.00.03.000-00.00.12.433.mp4'
main.117ae403.chunk.js:1

The time stated in the console is correct, but I'm retunred a 12.4 second video where the first cut is ignored, instead of the expected 9.4 second video.

**Comment by JambonSama** [comment]
I have the same issue on Manjaro kde 20.1.2
I use the gui, so I don't have as many messages to copy paste, but yeah, wherever I put my start cut, it doesn't work.

**Comment by mifi** [comment]
This may be a keyframe issue. How frequent are keyframes? Did you try to cut a segment between two keyframes?
