### ISSUE TITLE
[Request] Make an android port

### ISSUE THREAD

**Issue by Cyberavater** [mifi/lossless-cut#479]
Hi, I really like this tool It'd be really nice if could edit files on android too since I mostly listen to music on android. Hope you'd consider adding support for android too, thanks!

**Comment by mifi** [comment]
Doesn't android have any built in fast cutting tool like iOS has?

**Comment by Cyberavater** [comment]
>Doesn't android have any built-in fast cutting tool like iOS has?

Android is not as singular as iOS, so there are many Android Rom which has a built-in cutting app, while in AOSP you need to install an external app for this job.

>I will probably not be able to "just" add android support, but maybe I will make an iOS/Android losslesscut app one day

Yup, that is what I was asking for, thanks!

**Comment by mifi** [comment]
closing in favor of #818
