### ISSUE TITLE
Combined export option for Separate files + merged

### ISSUE THREAD

**Issue by markusd1984** [mifi/lossless-cut#480]
Feature request: **Combined profile to eliminate changing between merged and separate files export.**

Love lossless-cut, it's exactly what I was looking for an easy to use app to give to people so they can not just trim but cut out parts of the video, without loosing quality or take ages to render. 👍 

Given that **keyframe cut** is probably preferred over normal cut to eliminate the risk of empty portions, and since there is probably no way to simulate a playback of that without exporting it first, I find that exporting first as separate files allows one to check the begnning/ending of each segments and then when happy export as merged.

Therefore when hopefully cut points are well selected in most situations, it could speed up the workflow by having an combined export option to get both a merged file with also separate files, to allow for checking segments and when happy just manually delete them without having to export as merged there after and keep changing export options back and forth.

**Comment by mifi** [comment]
Sure. This could be an option under settings

**Comment by markusd1984** [comment]
@mifi thanks, ideally both, in the "auto merge" settings as well as the button on the top (between output format and keyframe/normakl cut) so one can just click the buttons to cycle between 1) Merge cuts 2) Separate files 3) Merge & Separate files.

**Comment by mifi** [comment]
> Just to clarify, would it be technically possible to have a **preview playback** mode of just the segments how the merged video will look like? As this could also be useful and perhaps eliminate otherwise that step to export and review separate files before merging them.

technically possible yes #253

**Comment by mifi** [comment]
have implelemnted a config option to keep the segments upon merge

**Comment by markusd1984** [comment]
> have implelemnted a config option to keep the segments upon merge

Is that already in the current windows version? I couldn't see it in the settings and neither the export dialogue.

Also the word "single" to me is not very clear/obvious, referring to a selected Segment from the timeline.

![image](https://user-images.githubusercontent.com/24621214/101659948-81808900-3a3e-11eb-98c9-35ba5a8ad279.png)

**Comment by mifi** [comment]
It's under settings. "Auto delete segment files after merge?"

**Comment by mifi** [comment]
I will change it like this and use the color of the current segment, hopefully more clear:

<img width="339" alt="Screenshot 2020-12-10 at 12 57 07" src="https://user-images.githubusercontent.com/402547/101769442-40907f00-3ae7-11eb-8463-a0a23a85fe48.png">

**Comment by markusd1984** [comment]
> It's under settings. "Auto delete segment files after merge?"

Sorry but I didn't find that in the current 3.27 version, are you sure it's in that version already or still to be released?

![image](https://user-images.githubusercontent.com/24621214/101772352-28b6fc00-3ae3-11eb-8ff4-cf98cd32e509.png)

**Comment by mifi** [comment]
Oops! I had not yet released that. Try with 3.29. building now!

**Comment by markusd1984** [comment]
@mifi that's perfect, thanks. Next thing would be segment numbering #536 to identify the split files more quicker/easier for those not too familiar with time codes ;) for purpose of inspecting cut points in the export, until we have a proper playback preview #253.

**Comment by markusd1984** [comment]
> Oops! I had not yet released that. Try with 3.29. building now!

Merging takes ages now for some reason on 3.29.1, on a 1hr video takes almost 3minutes while on v3.23.8 only less than 5 seconds., despite in both using the same project with merge cuts & normal cut mode (auto delete).

**Comment by mifi** [comment]
How many segments are you exporting (and how long are they)?

**Comment by mifi** [comment]
And are you creating chapters or custom metadata?

**Comment by mifi** [comment]
Ok I can reproduce the issue. In 3.29.1 I changed the default to now preserve metadata in files when merging. It seems like this is making ffmpeg a LOT slower

**Comment by mifi** [comment]
I have made preerve metadata on merge default to FALSE, and added an option to enable it

**Comment by markusd1984** [comment]
Does that mean in previous versions this was different configured so that you needed to match that setting again in 3.29.1 or why only now did that impact occur now? I repeated the same project, just different versions.

**Comment by mifi** [comment]
In previous versions of losslesscut metadata would not get preserved when doing a merge.

**Comment by markusd1984** [comment]
Gotcha, would that alone really be so time/processor intensive to make such a big difference? 
Isn't that just a copy/paste of bunch of meta info/text? #99

**Comment by mifi** [comment]
I have no idea why, but it is much slower (I tested with/without it)

**Comment by markusd1984** [comment]
hence I'm asking as it sounds like we might be missing something here that causes a huge delay, might not be just the fact you enabled preserving meta data. If this can be fixed that would be brilliant to avoid unnecessary disabling it just for speedy export sake.

**Comment by mifi** [comment]
created an issue for that

**Comment by markusd1984** [comment]
> @mifi thanks, ideally both, in the "auto merge" settings as well as the button on the top (between output format and keyframe/normakl cut) so one can just click the buttons to cycle between 1) Merge cuts 2) Separate files 3) Merge & Separate files.
> 
> ![image](https://user-images.githubusercontent.com/24621214/97597024-4a5d9780-19fd-11eb-9186-f0411ef710e5.png)
> 

@mifi just to follow up re changes:
1) Just wondering why you opted for creating an additional setting for **auto delete segments** (to keep separate files) rather than _a third option_ **merge+separate files**, that one could quickly cycle through - to decide when to keep separate files or not for a merged export?
Would that not be a better way, especially as it wouldn't require an additional setting during the export dialogue to quickly enable/disable this as it would be integrated in the "**Merge 3 cut segments to one file?**" options?

2) And why did you remove the merge/split button on the main window but kept the output format button?
I would think the format to be of less frequent use vs switching between merge/split - shouldn't we keep either both buttons (in the advanced view) or none of them due to being available in the export dialogue?

**Comment by mifi** [comment]
1. I did it because it was easy to implement. And it's not something that a lot of people requested, so I thought it may not be a setting that most poeple need most of the time
2. I wanted to keep the main UI simpler and I though that this choice is only something you need when you are exporting. I could have removed the output format button too but I thought it would be useful for people who wanted to disable the export dialog and just export immediately. Output format may be something that you need to change all the time depending on the input file.

**Comment by markusd1984** [comment]
Thanks @mifi

1) I suspect that previously many people where generally happy/accepted that cuts are not 100% accurate and that there isn't yet a built in way to preview where the cut will be in the export, and thus don't go through the effort of checking often the individual segments in the file explorer before using them individual or using a merged file (except likely people with generell editing experience would do this to achieve best results).
Thus having a [preview of an export](https://github.com/mifi/lossless-cut/issues/253#issuecomment-759394483)  could help with that and make using such a workflow more attractive to people.
It's not a big priority but would be great if we can put this on a long list of feature/enhancement request? Which then can eliminate that setting.


2) re output format, would have thought that LC automatically uses the same format as input by default, thus not require changing it every time when different formats are imported, expecting the preference usually to be to stay in the same format just as staying lossless as much as possible would be the preference. 

I would expect for regular editing of most people more likely to be using the same type of files anyway (also most content probably is h264 MP4 for videos, which is why i wasn't suprised to see MP4 initially selected).

2.2) But if matching output format with input format is not implemented I would highly suggest this as a feature request.

Perhaps this would then also make a point for possibly removing the button, but then again don't think for an advanced view it should bother one too much, as there is always the simple view mode for a total clean simple UI :)
2.3) There is the though of course to have a configurable UI in the long future :D (nice to have long term enhancement)

2.4) But I still challenge the case that usage/switching of merging Vs splitting to be not that infrequent, after all I think that's why we initially must have had this choice as a button in the first place. Yes we can still set it in the export dialogue but if this is the only thing being changed it would make a case for a preference to disable the export dialogue and regularly switching merge/split/merge+split and only enable back the export dialogue for exceptions.

Recent use case:
I just worked last week on multiple projects of which some where single files that I needed to trim and cut out segments to then check segments until all is good to get a single video file, as well as other projects where I also had to merge multiple files where also had to trim and check and trim etc. And thus in the end was manually deleting merged files as I had to still keep changing the segments (as I had keep segments in settings and didn't wanted to go back and forth with enabling and disabling etc.) 

(Also stated getting messing with selecting right files in the file explorer due to file creation date marching source file creation date instead of the export creation dates - see #611)

Sorry for the long reply, there is a lot in it but hope it makes sense and wonder if the suggested workflow would be beneficial and perhaps become more popular in usage.

**Comment by mifi** [comment]
Yes lc tries to detect the input format by default. I think we could hide the output format button from the main ui in simple mode. We cannotcompletely remove the out format button, because sometimes people might simply want to convert an mkv video into an mp4 for playback on iPhone etc.
I will add the merge+segments option to the button

**Comment by markusd1984** [comment]
You can probably delete the setting for keeping segments as the drop-down selection makes it redundant.

I'm happy seeing the out format button in the advanced view but with that can you please bring back the drop-down for merge/split/merge+split please in advanced UI? :blush:
