### ISSUE TITLE
LAst video of merge upside down

### ISSUE THREAD

**Issue by adambuzz14** [mifi/lossless-cut#481]
I have been using your program to merge some videos and it has done a fantastic job so far.

But i have hit a issue with 5 video files filmed on a samsung s10.  When i merge them, the last file comes out upside-down.  I thought it was an issue with that video at first, but after some trial and error, i have noticed which ever video i put last, this comes out upside down.

Can you support me on this issue?

thanks

If you have an issue with cutting a particular file, or an unexpected bug or crash, please open developer tools after starting LosslessCut and before doing the failing operation. Then share the output from the javascript console.

If you have an issue cutting a particular file, please also share the file, if possible. Also please try to cut it with the ffmpeg command line directly.

How to open developer tools:
- Windows: <kbd>F12</kbd> or <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>
- Mac: <kbd>Cmd</kbd>+<kbd>Opt</kbd>+<kbd>I</kbd>

**Comment by mifi** [comment]
Hi.  I think this is because the last video has been recorded with a different orientation. Then it has been rotated after recording. (using metadata). If this is the case, then unfortunately there is no way for you to merge these losslessly with the correct orientation.

**Comment by adambuzz14** [comment]
Hi Mikael, thanks for getting back to me.

Out of interest, if this one video has been filmed at a different orientation, how does windows media player, windows photos and video, vlc, plex etc, all know to view it the other way around? Even if I drag it into your software to trim / cut the start and end points it displays fine. Its only your software when I am merging that views it the wrong way round.

Thanks for your help and look forward to hearing your thoughts on this.

Thanks



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by mifi** [comment]
Because all video player software will rotate the video before showing it, according to the rotation metadata stored in the file's format. Then, naturally, if you try to merge files with different rotation metadata, the merged output file can only have one rotation, thus some of the sub-clips will have the wrong rotation.

**Comment by adambuzz14** [comment]
Thanks for your reply, that makes sense.
In your lossles cut app, there is a tool to rotate videos.  Am I then right in saying it doesn't actually rotate the video, but instead just changes thr metadata to tell the player to rotate the video?

Thanks again

Adam

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mifi** [comment]
That is correct. It just changes the metadata. It is not possible to rotate videos losslessly other than changing metadtaa.

**Comment by adambuzz14** [comment]
Thanks for getting back to me, that makes sense.  I didn’t really want to run all 5 video files through premier pro, as I don’t like the quality it outputs for h264.  But i’ve noticed if I just run the one troublesome file through, then it messes up playback after the merge,

Do you know of any other tools that can rotate the actual video, and it still be usable to merge with the other 4 files? Or will it be more straight forward to just re encode them all together in editing software?

Thank you

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by mifi** [comment]
AFAIK it's technically impossible to rotate videos without re-encoding. You can use a lossless video codec (or H264 with lossless CRF 0), although you will get huge files then.
