### ISSUE TITLE
app.allowRendererProcessReuse is deprecated

### ISSUE THREAD

**Issue by edmundlaugasson** [mifi/lossless-cut#485]
When to run from command-line (bash) the LosslessCut-linux.AppImage then there will be a message:
`(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397`
Link to the issue - https://github.com/electron/electron/issues/18397

**Comment by mifi** [comment]
Ok. This will have to be done when we upgrade electron version.

**Comment by mifi** [comment]
I'm closing this, as it will be handled by #714
