### ISSUE TITLE
Rotation preview is blurry

### ISSUE THREAD

**Issue by tarve** [mifi/lossless-cut#486]
hi

Rotation preview is blurry, Can you please fix this.

**Comment by mifi** [comment]
This is because it's done real time and needs to be low resolution or it will start lagging. Unfortunately I think I'm probably not going to spend any time on improving this.

**Comment by tarve** [comment]
Thanks for the reply.  can you add rotation shortcut key or lock . The below suggestion is still pending.

https://github.com/mifi/lossless-cut/issues/334.

**Comment by mifi** [comment]
Yup, that is in todo. Put your vote here #254 and maybe I'll able to add that in the next version.

**Comment by tarve** [comment]
Already done , two days back. Hope I win.
