### ISSUE TITLE
Cannot Delete Video File After Being Opened and Closed in LosslessCut

### ISSUE THREAD

**Issue by ibuycar12** [mifi/lossless-cut#488]
The Close function (Ctrl+W) does not allow the video file that is closed to be deleted.  This is a major inconvenience for editing several videos because it one were to delete the original video file after a new edited video is created, one has to close LosslessCut and restart it for the next video.  Hopefully this is a easy issue to fix.

**Comment by mifi** [comment]
I think this is related to #272
