### ISSUE TITLE
thumbnail preview overlaying timeline

### ISSUE THREAD

**Issue by markusd1984** [mifi/lossless-cut#489]
Wondering if the overlay was implemented in preference to use up overall less space?

Would it not be cleaner to have them not overlay and preferable adjust the grey thumbnail timeline to fit the thumbnail height (as their own current size seems a good fit)?

![image](https://user-images.githubusercontent.com/24621214/97596865-171b0880-19fd-11eb-926a-fb922e162ff6.png)

Waveform and thumbnails is now implemented

_Originally posted by @mifi in https://github.com/mifi/lossless-cut/issues/6#issuecomment-592008222_

**Comment by mifi** [comment]
hi!I'm not sure what you're asking. you think the thumbnails are too big?

**Comment by markusd1984** [comment]
> hi!I'm not sure what you're asking. you think the thumbnails are too big?

Thumbnails shouldn't overlay the green timeline. Enabling the audio view doesn't do that.

![image](https://user-images.githubusercontent.com/24621214/101630387-b549b780-3a1a-11eb-84ef-0ad57b16664c.png)

**Comment by mifi** [comment]
yea i wanted the thumbs to be bigger, hence the overlap. but i agree it would be cleaner to increase the size of the grey area.

**Comment by markusd1984** [comment]
Yeah the size is good, just the overlap makes it harder to view the timeline, fixing that will probably look better and more consistent thanks.

What could also be cool is an hover thumbnail option! As this would allow for scanning the timeline without having to holding a click in the timeline and also eliminates the need to keep the thumbnail view open (saving space and easier to use).

**Comment by mifi** [comment]
yes scrubbing would be cool and aws suggested here: #483

**Comment by mifi** [comment]
closing in favor of #483 to keep issue count down
