### ISSUE TITLE
Cannot export a file m2ts to matroska.

### ISSUE THREAD

**Issue by Phil171** [mifi/lossless-cut#490]
Hi, here is the rapport from an error generated by Lossless-cut in text file.
This file can be read correctly (video OK, sound OK) on a USB stick on my TV set, but is readed on VLC without sound. So I'vel try to encode in Matroska to be compatible TV set and VLC.
LLC give me this error and refuse to work.
[Plain Text.txt](https://github.com/mifi/lossless-cut/files/5489976/Plain.Text.txt)

**Comment by mifi** [comment]
duplicate #490
