### ISSUE TITLE
Cannot encode m2ts file to matroska file, error

### ISSUE THREAD

**Issue by Phil171** [mifi/lossless-cut#491]
Hi, here is the rapport from an error generated by Lossless-cut in text file.
This file can be read correctly (video OK, sound OK) on a USB stick on my TV set, but is readed on VLC without sound. So I've try to encode in Matroska to be compatible TV set and VLC.
LLC give me this error and refuse to work.
[Plain Text.txt](https://github.com/mifi/lossless-cut/files/5489976/Plain.Text.txt)

I just tried by using in Terminal this command :
`Dell-XPS-15:~$ ffmpeg -i file-to-modify.m2ts -bsf:a aac_adtstoasc -c:a copy -c:v copy output.mp4
`
And everything is OK, I can hear sound in VLC and on my TV set.
Any idea ?
Thanks, Phil

**Comment by mifi** [comment]
I think the clue here is the `-bsf:a aac_adtstoasc`. Does it work without that?

**Comment by Phil171** [comment]
I'll check this parameter.

**Comment by mifi** [comment]
If this works, then we could probably add support for this flag somehow

**Comment by Phil171** [comment]
Sorry, too busy to check and experiment at the moment, I'll be back with news later, no problem.
Philippe

**Comment by mifi** [comment]
any update?

**Comment by Phil171** [comment]
Promised, Mikael, I will try to do some other tests that I will try to document if it works correctly (sound offset from the image OK) but not currently, I am quite busy.
Sincerely,
Phil

**Comment by mifi** [comment]
closing for now. can reopen if more info resurfaces
