### ISSUE TITLE
FLAC with WAV file merge not prohibited and not functional

### ISSUE THREAD

**Issue by deton24** [mifi/lossless-cut#494]
The program allows to do it, though it's impossible from a technical side and it ends up in distorted audio without 2nd segment. 
At least with WAV as output. 

I'd just prevent users from merging various audio file formats, at least with WAV as output, just by showing some error.

It could be also added an error on the attempt of merging 16/24/32 bit audio files together in wav, because it results in improper decoding between segments anyway. 

I still wonder whether Matroska would handle it. 

From the other hand, it's possible to correctly merge video files with the same codec and resolution but with different framerate in MKVMerge (mp4 files with MKV as output). But it doesn't look like it's supported with different audio files via Matroska MKA container. I checked in MKVMerge, but maybe it's some implementation issues. Or maybe not. Tested with WAV/FLAC, and also with only WAV or FLAC (different bit depth files).

Anyway, great thanks for the app. I looked for such tool for literally ages and it just showed up recently in Google when I needed it :)
I fighting with some sync issues, since cut feature is not precise, and timestamps are not precise when I read it from DAW, but it's cool anyway, and hell a lot better than cutting in hxD...

**Comment by mifi** [comment]
the app could do this, but there are so many different formats/codecs that i don't know the details of which are compatible with which, and this may change from ffmpeg version to the next.

as for precise cutting, i would love to find a solution for determining exactly how the cuts will end up. I tried a lot but it really depends on codec/format parameters, so I was never able to find a consistent way of determining this for all files.

**Comment by deton24** [comment]
Maybe there is always one specific offset per one codec/file format?
Sooner or later I will find out if it's random in all cases and I'll let
you know.

niedz., 15 lis 2020, 20:58 użytkownik Mikael Finstad <
notifications@github.com> napisał:

**Comment by mifi** [comment]
just to be sture: you're taliking about merging multiple concurrent tracks/streams, not concatenating files right? Possibly related #448 547

**Comment by mifi** [comment]
closing due to lack of response

**Comment by deton24** [comment]
From what I understood, you can't set all possible warnings to make the software idiot-proof and prevent people from concatenating not compatible files with each other. Then yes, it can be closed.

But, I also wrote about joining various streams of the same code, but with different parameters like FPS.
In such case I presume you can't just join such two files, because there need to be an information about FPS in header otherwise the video won't be properly decoded, but maybe I'm wrong. Anyways, using MKVMerge you can put e.g. two H.264 files in one container, they will differ by the FPS, but they still will be played from one MKV container. I don't know whether your software supports something like that.
And it might be also bound to some specific codec settings. E.g. I used mp4/h.264 clips from Windows DVR with various FPS settings and joined them in MKVMerge. 
Few videos went fine, one video lost sync with audio joining clips that way, and in that case they even had the same FPS.

**Comment by mifi** [comment]
Just to be sure, you're talking about concatenating only here right? when you say put two h264 files in one container, you don't mean as separate parallell tracks/streams but one after another?

I think it may be possible to improve detection and give the user an error in certain cases, but I also don't want to exclude any use case that I think is not possible, but in reality ffmpeg can do it.

**Comment by deton24** [comment]
Videos are being played one after another after "concatenating" them in a
way of adding files with the same codec to MKV container.
I doubt that simple concatenate of the files with different FPS like in HxD
instead of putting them in the matroska container like in MKVMerge would
decode the file properly. Still, I can be wrong.

And MKVMerge has a nice GUI - MKVToolnix if you want to try out how it
works.



niedz., 20 lut 2022, 13:54 użytkownik Mikael Finstad <
***@***.***> napisał:
