### ISSUE TITLE
edit track meta data such as language or default

### ISSUE THREAD

**Issue by TimetravelerDD** [mifi/lossless-cut#496]
Hi,
I believe LosslessCut would really benefit from the ability to edit track meta data, such as language.

Imagine you add a secondary audio track to a video file  – most people would probably like to set the language for each track so that it will be properly recognized by playback software or hardware. Also marking tracks as default would be useful.

At the moment I use mkvnixtool for that, but sadly it can only output mkv.

**Comment by mifi** [comment]
I'm thinking like this: https://stackoverflow.com/questions/44351606/ffmpeg-set-the-language-of-an-audio-stream/44351749

**Comment by TimetravelerDD** [comment]
yes, that's exactly what I mean :-)

**Comment by Shakil-Shahadat** [comment]
This will be very helpful. Also needed for subtitles.

In addition, for subtitles, if it can detect the language automatically from the language suffix ( like English from '...en.srt' ) that will be very helpful.

**Comment by mifi** [comment]
a basic metadata editor is implemented and will eb include in the next release!

**Comment by mifi** [comment]
closing as this is now live
