### ISSUE TITLE
What kind of IDE do you use dear Mifi? I'd like to set some custom functions in the project! May I?

### ISSUE THREAD

**Issue by robozb** [mifi/lossless-cut#497]
What kind of IDE do you use dear Mifi and what is the process that results the exe file? (I use Netbeans or Eclipse)

I'd like to set some custom functions in the project! May I?

I need constant MOV export, and I'd like to disable all the warning dialogs, and maybe I reset the input-output keystroke!

Thank you so much for the great software as well!

Bela from Hungary

**Comment by mifi** [comment]
hi! i use vscode.

how to run it in dev ? see https://github.com/mifi/lossless-cut/blob/master/developer-notes.md

how to build production? see https://github.com/mifi/lossless-cut/blob/master/.github/workflows/build.yml

**Comment by robozb** [comment]
Thank you so much!
