### ISSUE TITLE
BUG? The settings isn't permanent It restores its state to default on every new clip loading

### ISSUE THREAD

**Issue by robozb** [mifi/lossless-cut#498]
BUG? The settings isn't permanent It restores its state to default on every new clip loading

**Comment by mifi** [comment]
which state are you talking about?

**Comment by robozb** [comment]
e.g. the output format

**Comment by mifi** [comment]
output format defaults to same as input format. it will depend on what kind of file you open up, so i don't think it makes sense to blindly make this permanent.

**Comment by mifi** [comment]
output format can now be locked to one format
