### ISSUE TITLE
Don't cut at -ss 0

### ISSUE THREAD

**Issue by mifi** [mifi/lossless-cut#50]
See https://github.com/mifi/lossless-cut/pull/13#issuecomment-345912721

@gleddamax So what you're saying is that if you cut from exactly 0 (the very beginning of the video), we should exclude the arguments `-ss 0`? That's easy to fix, just have to whether it breaks anything.

**Comment by gleddamax** [comment]
Exactly, within my experiments I experienced no problems by excluding this option.

**Comment by mifi** [comment]
Fixed. Will be included in the next version
