### ISSUE TITLE
Warn about inadvertently closing the whole application when there's unsaved work

### ISSUE THREAD

**Issue by rulatir** [mifi/lossless-cut#501]
I was unaware that LosslessCut was an in-browser app running in its own Chrome. I opened the settings page and thought it was a separate settings dialog. Then I wanted to close it, so I clicked the X button on the window title bar. LosslesCut immediately quit on me without prompting to save my work. Perhaps `onbeforeunload` could be used here?

**Comment by mifi** [comment]
there is a setting "ask before close" which will ask you when you if you close while you have an open file. is that satisfactory?
