### ISSUE TITLE
[Request] Combine two audio streams into one

### ISSUE THREAD

**Issue by LeMansRoman** [mifi/lossless-cut#507]
Hi! I am recording gameplay with in-game sounds. So I make several mp4 videos, merge them in Lossless Cut and after that I want to add a music file. When I do so the video consists two separate audio streams and when I upload it to youtube it sees only the first audio stream (in-game sound) and no music.
Is it possible to somehow combine this 2 audio streams into one (let it be lossy) so I can upload to youtube in-game gameplay with my background music. But the video should be still lossless = fast export time.
Thank you

P.s If anyone knows simple program that can combine 2 audio into one, please let me know

Edit: found this, but I can't understand how to make it work, I need GUI for that xD
https://gist.github.com/LukasKnuth/4d7ee6812ccb221b2775e984516b56d4
ffmpeg -y \

-i "input.mkv" \

-filter_complex "[0:a:2] volume=0.5 [l] ; [0:a:1] [l] amix=inputs=2 [a]" \
-map "0:v:0" \
-map "[a]" \
-c:v copy \
-c:a aac \
-b:a 192k \

"output.mkv"

**Comment by Shakil-Shahadat** [comment]
This kind of workflow is more appropriate for audio editors than lossless-cut. Try [Audacity](https://www.audacityteam.org/).

**Comment by mifi** [comment]
Yea, I'm not going to implement this in losslesscut unfortunately, sorry.
