### ISSUE TITLE
language Russian translation

### ISSUE THREAD

**Issue by naumgod** [mifi/lossless-cut#509]
The program is a masterpiece. Please add the Russian language. Or post a text document so that I can translate more.
Программа шедевр. Прошу добавить Русский язык. Или выложите тактовый документ что б я перевёл ещё.

**Comment by trebmuh** [comment]
You can improve the Russian translation [here](https://hosted.weblate.org/projects/losslesscut/losslesscut/ru/).

**Comment by naumgod** [comment]
guys, I translated up to 100% into Russian. I consider the program a masterpiece and I became a fan of this video editor.

**Comment by trebmuh** [comment]
nice

**Comment by mifi** [comment]
Wow! so fast! thanks for your contribution. I will add Russian support

**Comment by mifi** [comment]
added in ee73384594e223c5c26d6e67e7161fbade7d3223

**Comment by naumgod** [comment]
Hi. Today I updated and supplemented, translated into Russian. Thanks to me)

**Comment by mifi** [comment]
thank you:) it will be included in the next version
