### ISSUE TITLE
Multiple in and out points?

### ISSUE THREAD

**Issue by Sailing74** [mifi/lossless-cut#51]
Would it be possible to set multiple in and out points for videos, so that one can create a clip containing of multiple parts of the original video?

This could, e.g., be helpful to cut out commercials etc.

**Comment by codyolsen** [comment]
@Sailing74 check out this thread -> https://github.com/mifi/lossless-cut/issues/12 Feel free to add any of your ideas there!

**Comment by codyolsen** [comment]
@mifi duplicate. We can close this issue.
