### ISSUE TITLE
Can't cut and edit for convert or advanced export

### ISSUE THREAD

**Issue by uratom962** [mifi/lossless-cut#512]
Hi,

I have lossless-cut 3.23.8, and I can't know how to edit or delete cut (like on this tutorial movie https://www.youtube.com/watch?v=IPQymOSei_Q ) because I don't have some icon for cut and merge, so, in my antix (debian distro), I install this software with snap.

And now, when I want to export, I don't have export advanced setting, for have low resolution, or like on this menu :   converted to support format. So, I don't know how to have this export setting : slow : low in quality encode ... For have an output small size video . if anyone know how to do that, or help me please, thank you.

**Comment by Shakil-Shahadat** [comment]
In order to cut a portion, you have to select the cut start from the timeline and then click left hand icon to mark it as the cut start, then select cut end from the timeline and then click right hand icon. Similarly, mark all your sections and then select merge cut from the top. If you want to change the format, select a different format from the top. Then you click export+merge.

**Comment by mifi** [comment]
In the newest version I have improved this by showing an export summary screen

![Screenshot 2020-11-26 at 15 05 39](https://user-images.githubusercontent.com/402547/100360221-f2648180-2ff8-11eb-90a5-ed948d61df6a.jpg)

**Comment by gabrielbrazs** [comment]
Is there an option to disable this summary somewhere? I cannot find it.

**Comment by mifi** [comment]
I will add an option

**Comment by tarve** [comment]
Silly question from me. But how to use latest commit on top of last release. Can you please guide , how to use the code from github on windows , or this code is for co-lab like platform.

**Comment by mifi** [comment]
See https://github.com/mifi/lossless-cut/blob/master/developer-notes.md
Will release this soon

**Comment by mifi** [comment]
<img width="341" alt="Screenshot 2020-12-11 at 16 55 47" src="https://user-images.githubusercontent.com/402547/101930595-a577d200-3bd8-11eb-93d7-f0f598f9ae4b.png">

have also improved this screen.
