### ISSUE TITLE
auto scroll vscroll bar

### ISSUE THREAD

**Issue by megabugman** [mifi/lossless-cut#513]
after adding many segments, newly added segments are buried below the UI.
auto scrolling the vertical bar could be useful.

**Comment by mifi** [comment]
buried below which UI? Can you show an example?

**Comment by megabugman** [comment]
sure, I made a video to make it more obvious:
![enhancement](https://user-images.githubusercontent.com/17204819/100397008-dd630f00-3047-11eb-8108-d1126b5d2b68.gif)
so, from my understanding, the active segment, should always be visible, 
in my example segment >6 is active but hidden due to the toolbar.

**Comment by mifi** [comment]
gotcha. i agree

**Comment by markusd1984** [comment]
Brilliant, perhaps as well adding a minimal visual scroll bar? 

That ideally only becomes visible when there are more segments then space available (e.g. resized window or adding many segments). That could help those who not naturally think of scrolling up/down, just like many don't realise this on website where scrollbars are missing or using fancy looks that aren't as intuitive/obvious enough (additional up/down scrolling pointers could help as well).

**Comment by mifi** [comment]
I just realized that this is actually implemented already.
