### ISSUE TITLE
[enhancement] add tag for adio/sub in preview pane

### ISSUE THREAD

**Issue by benop923** [mifi/lossless-cut#514]
Great tool, great job.
When I edit video, I usually also delete audio and subs that are not relevant (mostly keeping original and my native language).
Would it be possible to add the associated language tag in this main pane (let's say where type or codec is listed)? It would remove the need to open each detail and scroll down.
Thanks,

**Comment by mifi** [comment]
you mean add language metadata for each stream/track?

**Comment by benop923** [comment]
yes; like fre; ger/deu, eng... in the (i) details;  and the infamous DVB qaa/qad!
tags: {
    language: 'fre',
  },
}

as said, I usually only keep original and local, any other 
I try to discard, so I need to click on each (audio/sub), to see who's who!
thx

**Comment by mifi** [comment]
Ohh, you just want to SHOW it in the table as a column. You don't want to actually change it...

**Comment by benop923** [comment]
yes, SHOW this language tag for faster selection:
as it shows now, there id plenty of space as column "tag" is showing 4 rows for all my DVBs recording.
so adding another  line into column "type" or "codec" to show the existing info would be awesome

**Comment by mifi** [comment]
Ok it was easy to add, so I added that. will be in the next version!

**Comment by benop923** [comment]
you so much rock!!!!
thx
