### ISSUE TITLE
auto convert file fails

### ISSUE THREAD

**Issue by benop923** [mifi/lossless-cut#515]
I mostly record DVB and reauthor it. Codecs are H264 and AC3.
In v3.21, the conversion from unsupported file was done automatically.
In v3.26 (to which I have upgraded today), it fails on openning, and need to be done manually.

**Comment by mifi** [comment]
Thanks for reporting. It was indeed a regression bug. I have now fixed and it will be out in the next version. In the meantime you can click File->convert to supported format -> Fastest: Low playback speed (no audio)
