### ISSUE TITLE
Filename in titlebar doesn't get updated when a new file is dragged in

### ISSUE THREAD

**Issue by mburr** [mifi/lossless-cut#52]
Minor issue: after cutting one file, I drag in the next one but the title bar still displays the old filename.

Everything else about the new filename is fine - in particular when I perform the cut operation on the new file it gets a correct filename.

lossless-cut 1.9.0.0

By the way - thanks for this utility.  It's a very nice tool.

**Comment by mifi** [comment]
Does this happen when you drag an unsupported file?

**Comment by mifi** [comment]
I cannot reproduce this, please reopen if still a problem 🙌
