### ISSUE TITLE
Shortcut "." won't work anymore on French keyboard

### ISSUE THREAD

**Issue by nodarkthings** [mifi/lossless-cut#520]
- [ X] I have tested the newest version
The problem report says "No error".

Hi!
I've been using v3.23.7 for a while with no issue, today I've tried v3.27.0 and found an issue with moving 1 frame forward: though clicking on the arrow works, the usual shortcut of "." doesn't.
I've tried the US keyboard layout and it works, so it's something related to the French keyboard layout — and probably other languages...

By the way: it would be great, for us people who use non-english keyboards if we could customize the shortcuts, at least "," and "." as they are not positioned the same as the english layout — actually, you have to use SHIFT to get "." on the French layout, which is less than ideal...

**There's another way to fix this**: my suggestion is to change those 1 frame shortcuts with _SHIFT+left arrow_ for backward and _SHIFT+right arrow_ for forward.
This way, it would be the same shortcuts for any keyboard layout, with no issue! 👍

**Comment by mifi** [comment]
Thanks for reporting. This was an issue introduced in the newest versions. Have now fixed this and it will be released in the next version. Custom key bindings have been suggested. See #254
Shift-left and right is already bound to cut-start and end

**Comment by nodarkthings** [comment]
Thank you! :-)
I would pledge for shortcuts that are not altered by KB layouts.
AFAICT, any combination of modifier keys with arrows (even vertical arrows) would be great, if they're not all already used by other functions. ;-)

**Comment by mifi** [comment]
I think arrow keys with almost all modifier keys are already in use. You mean multiple at once? Like cmd+Ctrl+alt+shift+left etc?

**Comment by nodarkthings** [comment]
Yes. The most simple still available, if any.
The French KB layout is probably one the most tricky as not only some keys are changed (m becomes ,) but some become signs available only in combination with a letter (\ becomes ` and [ becomes ^ — to give letters such as ê or ò).
So please don't use punctuation keys or [ ] \, etc. ;-) I've already bumped into some app using [ and ] making the app quite unusable...

**Comment by mifi** [comment]
try with ver 3.29!

**Comment by mifi** [comment]
I have now rewritten the keyboard logic to use native events instead of mousetrap. Please test the [newest nightly build](https://mifi.no/llc/nightly/) to see that it still works. Thank you! Note: If you have a lot of custom shortcuts that you are afraid of losing you might want to backup your config.json file first, because there is a one-way migration of the config file happening upon upgrade.

**Comment by nodarkthings** [comment]
Thank you but unfortunately I'm stuck on MacOS 10.14, so I can't test new versions...
