### ISSUE TITLE
Make Installer

### ISSUE THREAD

**Issue by xmha97** [mifi/lossless-cut#521]
Hello,
Please make an installer for Windows 7.
Thanks

**Comment by Shakil-Shahadat** [comment]
I have noticed that the app takes some time to open. I guess, it decompresses its libraries to somewhere. If that's the case, I too request to make an installer, where everything is decompressed in the install folder, so that it runs faster.

**Comment by xmha97** [comment]
You can install LosslessCut using [Chocolatey](https://chocolatey.org/).
Run below command in Powershell:
```
choco install lossless-cut
```

**Comment by Shakil-Shahadat** [comment]
@xmha97 is it the same portable lossless-cut?

**Comment by leon332157** [comment]
Looks like the Chocolatey install does exactly what an installer should do. Extracted the zip release and added start menu.

**Comment by Shakil-Shahadat** [comment]
So, basically, it downloads Lossless-Cut.zip and extracts it and adds a start menu shortcut. It has all the necessary components and starts very fast. Exactly what I was looking for. Although I'll stick to zip version. Thank you so much @xmha97 & @leon332157.

**Comment by jmacasd** [comment]
I do like for system-wide installer.

**Comment by xmha97** [comment]
Duplicate: #86
