### ISSUE TITLE
Losslesscut 3.27.0 does not process Canon eos R6 mp4 files

### ISSUE THREAD

**Issue by JVRR6** [mifi/lossless-cut#522]
I wanted to cut the MP4 file without lossing any original characteristics. 

Error: Command failed with exit code 1: C:\Users\Jos\AppData\Local\Temp\1kqSpFfA6OGcMuz2jiEg83Zoz5q\resources\node_modules\ffmpeg-static\ffmpeg.exe -hide_banner -ss 0.94000 -i F:\Photo\To Evaluate\20201115\2G5A1468.mp4 -t 20.42000 -avoid_negative_ts make_zero -c copy -map 0:0 -map 0:1 -map 0:2 -map_metadata 0 -ignore_unknown -f mp4 -y F:\Photo\To Evaluate\20201115\2G5A1468-00.00.00.940-00.00.21.359.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000019df5bdad40] st: 0 edit list: 1 Missing key frame while searching for timestamp: 1000
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000019df5bdad40] st: 0 edit list 1 Cannot find an index entry before timestamp: 1000.
Guessed Channel Layout for Input Stream #0.1 : stereo
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'F:\Photo\To Evaluate\20201115\2G5A1468.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 1
    compatible_brands: mp42avc1CAEP
    make            : 
    make-eng        : 
    model           : 
    model-eng       : 
    creation_time   : 2020-11-15T15:16:47.000000Z
    timecode        : 00:23:35:32
  Duration: 00:00:30.08, start: 0.000000, bitrate: 222422 kb/s
    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt709), 3840x2160, 220759 kb/s, 50 fps, 50 tbr, 50k tbn, 100k tbc (default)
    Metadata:
      creation_time   : 2020-11-15T15:16:47.000000Z
    Stream #0:1(eng): Audio: pcm_s16be (twos / 0x736F7774), 48000 Hz, stereo, s16, 1536 kb/s (default)
    Metadata:
      creation_time   : 2020-11-15T15:16:47.000000Z
    Stream #0:2(eng): Data: none (tmcd / 0x64636D74), 1 kb/s (default)
    Metadata:
      creation_time   : 2020-11-15T15:16:47.000000Z
      timecode        : 00:23:35:32
[mp4 @ 0000019df5be1ac0] You requested a copy of the original timecode track so timecode metadata are now ignored
[mp4 @ 0000019df5be1ac0] Could not find tag for codec pcm_s16be in stream #1, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
  Stream #0:2 -> #0:2 (copy)
    Last message repeated 1 times
    at makeError (C:\Users\Jos\AppData\Local\Temp\1kqSpFfA6OGcMuz2jiEg83Zoz5q\resources\app.asar\node_modules\execa\lib\error.js:58:11)
    at handlePromise (C:\Users\Jos\AppData\Local\Temp\1kqSpFfA6OGcMuz2jiEg83Zoz5q\resources\app.asar\node_modules\execa\index.js:114:26)
    at async I (file:///C:/Users/Jos/AppData/Local/Temp/1kqSpFfA6OGcMuz2jiEg83Zoz5q/resources/app.asar/build/static/js/main.e914b8f1.chunk.js:1:4496)
    at async L (file:///C:/Users/Jos/AppData/Local/Temp/1kqSpFfA6OGcMuz2jiEg83Zoz5q/resources/app.asar/build/static/js/main.e914b8f1.chunk.js:1:5195)
    at async file:///C:/Users/Jos/AppData/Local/Temp/1kqSpFfA6OGcMuz2jiEg83Zoz5q/resources/app.asar/build/static/js/main.e914b8f1.chunk.js:1:141250

{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "filePath": "F:\\Photo\\To Evaluate\\20201115\\2G5A1468.mp4",
    "fileFormat": "mp4",
    "externalStreamFiles": [],
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_time_base": "1/100",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 3840,
        "height": 2160,
        "coded_width": 3840,
        "coded_height": 2160,
        "has_b_frames": 1,
        "pix_fmt": "yuvj420p",
        "level": 52,
        "color_range": "pc",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "50/1",
        "avg_frame_rate": "50/1",
        "time_base": "1/50000",
        "start_pts": 2000,
        "start_time": "0.040000",
        "duration_ts": 1504000,
        "duration": "30.080000",
        "bit_rate": "220759947",
        "bits_per_raw_sample": "8",
        "nb_frames": "1504",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "creation_time": "2020-11-15T15:16:47.000000Z",
          "language": "eng"
        }
      },
      {
        "index": 1,
        "codec_name": "pcm_s16be",
        "codec_long_name": "PCM signed 16-bit big-endian",
        "codec_type": "audio",
        "codec_time_base": "1/48000",
        "codec_tag_string": "twos",
        "codec_tag": "0x736f7774",
        "sample_fmt": "s16",
        "sample_rate": "48000",
        "channels": 2,
        "bits_per_sample": 16,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/48000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 1443840,
        "duration": "30.080000",
        "bit_rate": "1536000",
        "nb_frames": "1443840",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "creation_time": "2020-11-15T15:16:47.000000Z",
          "language": "eng"
        }
      },
      {
        "index": 2,
        "codec_type": "data",
        "codec_tag_string": "tmcd",
        "codec_tag": "0x64636d74",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "50/1",
        "time_base": "1/50000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 1504000,
        "duration": "30.080000",
        "bit_rate": "1600",
        "nb_frames": "1504",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "creation_time": "2020-11-15T15:16:47.000000Z",
          "language": "eng",
          "timecode": "00:23:35:32"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "F:\\Photo\\To Evaluate\\20201115\\2G5A1468.mp4": {
        "0": true,
        "1": true,
        "2": true
      }
    },
    "cutSegments": [
      {
        "start": 0.94,
        "end": 21.36
      }
    ],
    "fileFormatData": {
      "filename": "F:\\Photo\\To Evaluate\\20201115\\2G5A1468.mp4",
      "nb_streams": 3,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "30.080000",
      "size": "836308292",
      "bit_rate": "222422418",
      "probe_score": 100,
      "tags": {
        "major_brand": "mp42",
        "minor_version": "1",
        "compatible_brands": "mp42avc1CAEP",
        "make": "",
        "make-eng": "",
        "model": "",
        "model-eng": "",
        "creation_time": "2020-11-15T15:16:47.000000Z",
        "timecode": "00:23:35:32"
      }
    },
    "rotation": 360,
    "shortestFlag": false
  }
}

**Comment by mifi** [comment]
Hi. Does it work with previous versions since you wrote 3.27.0? If so, which version works?

**Comment by JVRR6** [comment]
Hello,
No it did not . I tried with this one and the previous one (23.0). 

Met vriendelijke groeten
Kind regards

Jos Van Roosbroeck

**Comment by mifi** [comment]
Can you try:
- Change output format to MOV
- Enable experimental flag (under settings)

**Comment by JVRR6** [comment]
I did the test and it looks ok. MediaInfo gives the same info for both
files.
So I have to enable the experimental flag, or is it only for testing ?



Op di 1 dec. 2020 om 17:37 schreef Mikael Finstad <notifications@github.com

**Comment by mifi** [comment]
if it works without it, then no need to enable experimental flag

**Comment by JVRR6** [comment]
I did another test with different files without the flag and it works ok.
Thanks a lot.




Op di 1 dec. 2020 om 18:17 schreef Mikael Finstad <notifications@github.com

**Comment by mifi** [comment]
Ok, closing this
