### ISSUE TITLE
Pause and Cancel Exporting

### ISSUE THREAD

**Issue by ridwan47** [mifi/lossless-cut#524]
There's no way to Pause or Cancel Exporting. Please add this feature.

**Comment by markusd1984** [comment]
Nice to have and could be useful when export takes much longer e.g. forgot to switch back from keyframe to normal cut or PC becomes sluggish due to too many apps running in the background. :)

**Comment by mifi** [comment]
Yep, for now you have to quit and restart the app to abort

**Comment by mifi** [comment]
implemented abort for all ffmpeg actions. not sure if it's even possible to implement cross-platform pause of an ffmpeg process so i'll close this
