### ISSUE TITLE
File Selection Dialog font issue

### ISSUE THREAD

**Issue by mrb2604** [mifi/lossless-cut#525]
When I try to use merge tool, file selection dialog box shows square boxes instead of text. 
Kindly go through the image file attached.
![image](https://user-images.githubusercontent.com/40474214/100766193-60a4ac00-341e-11eb-92e9-398e14a2738a.png)

Version Used :  3.23.8 installed through snap store on Manjaro Linux KDE 20.2.1

Kindly resolve the issue.
Awaiting a reply.

**Comment by mifi** [comment]
Hi. It looks like you are having some font issue on your computer. Does the  dialog work with other apps inside X11?

**Comment by mrb2604** [comment]
File dialog tested on chromium browser, works ok.
![image](https://user-images.githubusercontent.com/40474214/100785760-20055c80-3437-11eb-9781-6ff4da33fa89.png)
Kindly provide ways to test file dialog with other apps inside x11.
Do I need to add any specific font for losslesscut to work properly.

**Comment by mrb2604** [comment]
Previously I installed Losslesscut through snap store.
Now uninstalled it and reinstalled it by building it through AUR. 
Now it works properly no font issue.
![image](https://user-images.githubusercontent.com/40474214/100792103-26e49d00-3440-11eb-95b5-6159ec15ff2f.png)
I think there is some problem with snap store packaging for the software.
Thank you for the response.
Thank you very much for the great piece of software.

**Comment by mifi** [comment]
Ok that's great to hear! Closing this.
