### ISSUE TITLE
no more audio in preview since updating to Big Sur

### ISSUE THREAD

**Issue by sstadtl** [mifi/lossless-cut#529]
i updated my mac to big sur and now there is no audio when playing the preview.
(mute button does not change anything)
i tried different mp4 files from different sources and all files are affected.
Exported files have audio, so it seems to be an issue only with the preview player.
downloaded latest version  Version 3.27.0 (3.27.0), but problem still persists.

Please let me know how i can help to track down this problem.
this is the stream info of one of the affected files:
<details>
  <summary>Click to expand!</summary>
<pre>
{
  index: 1,
  codec_name: 'aac',
  codec_long_name: 'AAC (Advanced Audio Coding)',
  profile: 'LC',
  codec_type: 'audio',
  codec_time_base: '1/48000',
  codec_tag_string: 'mp4a',
  codec_tag: '0x6134706d',
  sample_fmt: 'fltp',
  sample_rate: '48000',
  channels: 2,
  channel_layout: 'stereo',
  bits_per_sample: 0,
  r_frame_rate: '0/0',
  avg_frame_rate: '0/0',
  time_base: '1/48000',
  start_pts: 0,
  start_time: '0.000000',
  duration_ts: 256247040,
  duration: '5338.480000',
  bit_rate: '124685',
  max_bit_rate: '192084',
  nb_frames: '250242',
  disposition: {
    default: 1,
    dub: 0,
    original: 0,
    comment: 0,
    lyrics: 0,
    karaoke: 0,
    forced: 0,
    hearing_impaired: 0,
    visual_impaired: 0,
    clean_effects: 0,
    attached_pic: 0,
    timed_thumbnails: 0,
  },
  tags: {
    creation_time: '2020-11-23T07:28:55.000000Z',
    language: 'eng',
  },
}
</pre>
</details>

this is the output from the dev console:
<details>
  <summary>Click to expand!</summary>
<pre>Version 3.27.0
2.a73b2d89.chunk.js:2 react-i18next:: i18n.languages were undefined or empty undefined
N @ 2.a73b2d89.chunk.js:2
main.f66a3241.chunk.js:1 Load Objectfp: "/Users/sebastian/Downloads/Tatort-In_der_Familie_(1)-0302115203.mp4"cod: "/Users/sebastian/Downloads"html5FriendlyPathRequested: undefineddummyVideoPathRequested: undefined__proto__: constructor: ƒ Object()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()hasOwnProperty: ƒ hasOwnProperty()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toString: ƒ toString()valueOf: ƒ valueOf()toLocaleString: ƒ toLocaleString()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
main.f66a3241.chunk.js:1 getFormatData /Users/sebastian/Downloads/Tatort-In_der_Familie_(1)-0302115203.mp4
main.f66a3241.chunk.js:1 ffprobe -of json -show_format -i '/Users/sebastian/Downloads/Tatort-In_der_Familie_(1)-0302115203.mp4'
main.f66a3241.chunk.js:1 formats mov,mp4,m4a,3gp,3g2,mj2
main.f66a3241.chunk.js:1 fileType detected format {"ext":"mp4","mime":"video/mp4"}
main.f66a3241.chunk.js:1 ffprobe -of json -show_entries stream -i '/Users/sebastian/Downloads/Tatort-In_der_Familie_(1)-0302115203.mp4'
main.f66a3241.chunk.js:1 ffprobe -i '/Users/sebastian/Downloads/Tatort-In_der_Familie_(1)-0302115203.mp4' -show_chapters -print_format json
main.f66a3241.chunk.js:1 onDurationChange 5338.48
main.f66a3241.chunk.js:1 ffprobe -v error -read_intervals '0%30' -show_packets -select_streams 0 -show_entries 'packet=pts_time,flags' -of json '/Users/sebastian/Downloads/Tatort-In_der_Familie_(1)-0302115203.mp4'
</pre>
</details>

edit: i forgot
File > "convert to support format" did not change anything
highest 2 setting yielded broken file with neither image or audio

**Comment by mifi** [comment]
Hi. Can you confirm 100% that the same file worked before Big Sur?
Also can you try one of the files from here, for example https://github.com/mifi/lossless-cut-fixtures/blob/master/big-buck-bunny_trailer.webm

**Comment by sstadtl** [comment]
it was all fixed with a reboot. all working again 
sorry i have wasted your time.
still puzzles me why videos in finder had sound, but losslesscut was mute.

**Comment by mifi** [comment]
Ohh ok. No worries. Thanks for reporting back

**Comment by mattack1** [comment]
I realize this is already closed..  but for all of the video files I edit (downloaded from my tivo), I always get the "not directly supported" UI.. on multiple macOS versions.  They're just regular MPEG files that can play directly in quicktime player (but there's not a good editing UI there).

**Comment by mifi** [comment]
What do you mean by MPEG? mpeg2?

**Comment by mattack1** [comment]
Yeah I think MPEG 2. if you can give a way I can provide more info (in a separate report?), I will.  All I know is that it's program stream (since for HD channels we nowadays have to download from the Tivo a Transport Stream file that sometimes has glitches, due to the Tivo AFAIK).. so they're e.g. SD recordings of late night talk shows or Saturday Night Live, that I want to edit out a musical performance or two usually.

**Comment by mifi** [comment]
Yea unfortunately such formats cannot be natively supported as of now due to limitations in electron. (mpeg2 is anyhow a very old format, not used so much in modern programs)

But you should still get a low quality preview. If you're not even getting a low quality preview, then please open an issue with a report (Help->Report and error)

**Comment by mattack1** [comment]
yeah I do get a low quality preview.. it's just that I have to wait for that temp file to be created (maybe that always happens)..  and it doesn't get deleted/put in the trash automatically so it's something I have to clean up.

also, IIRC seeking around in that low quality preview can sometimes be slow too.

mpeg 2 is "old", but is a pretty darn popular format I'd say.. all DVDs use it!! 
is there any chance of making it a natively supported format?

**Comment by mifi** [comment]
Yea it used to be a pretty popular format, but I would argue that almost nobody uses DVDs these days :)
I have not yet found a solution to support non-chromium formats yet (which includes mpeg2). See #88
