### ISSUE TITLE
Add a scroll bar after zoom in timeline

### ISSUE THREAD

**Issue by zhuoziqiang** [mifi/lossless-cut#532]
that will be better

**Comment by markusd1984** [comment]
sweet, never occurred to me that one can zoom in via mouse wheel scroll :D despite me using it regularly in premiere pro :) there is a nice empty space in the right bottom corner underneath the timeline.

![image](https://user-images.githubusercontent.com/24621214/101890870-329b3680-3b99-11eb-8b00-84c234226808.png)

**Comment by mifi** [comment]
we already have a zoom selector. I'm not sure whether select or slider is the best. sliders can also become quite fiddly when small

**Comment by mifi** [comment]
closing in favor of #483
