### ISSUE TITLE
Appimage doesn't include update information

### ISSUE THREAD

**Issue by Sugarcrisp-ui** [mifi/lossless-cut#535]
I really like the losslesscut appimage that you provide.  I would like to request that you include the update information with your appimage to allow users to take advantage of programs like appimageupdater to ensure the program is kept up to date

**Comment by mifi** [comment]
Is this the same as #484 ? I don't know which information is needed, please let me know and I can add it. Or submit a PR adding the information

**Comment by Sugarcrisp-ui** [comment]
Hey Mikael,

I did a quick search and found the instructions on
https://github.com/AppImage/AppImageSpec/blob/master/draft.md#update-information.
In the table of contents, you will see a link for "update information".

Thanks for providing the appimage.

Brett

**Comment by mifi** [comment]
Thanks. Will continue discussion in #484. closing this
