### ISSUE TITLE
Include Segment numbering in output file name for separate / single exports

### ISSUE THREAD

**Issue by markusd1984** [mifi/lossless-cut#536]
Include the segment numbering into the file name when exporting separately or single segment export to make it easier/quicker to distinguish them besides just time codes or file creation date/time. :)

e.g. "ORIGINALFILENAME-Segment1-00.08.43.181-00.11.19.218,mp4" or "ORIGINALFILENAME-Segment1of18-00.08.43.181-00.11.19.218,mp4"

Complimentary to manually specifying a custom file name #96 .

**Comment by mifi** [comment]
I'm not sure if this is something everyone wants. I know some people like to sort the files and expect them to be in order of the start times.

**Comment by markusd1984** [comment]
@mifi than we could still have the segment info at the end to allow for sorting?

e.g. "ORIGINALFILENAME-00.08.43.181-00.11.19.218-Segment1,mp4" or "ORIGINALFILENAME-00.08.43.181-00.11.19.218-Segment1of18,mp4" or shorter with Seg1 / Seg1of18.

Most lay person don't care so much about the time code, they just pick the points and need to check if the end result sounds/looks like how they meant to cut it (due to the possibility or inaccurate cuts). Ideally if there were a simulated play function from segment to segment or similar could eliminate that step, otherwise one needs to inspect the exported segments (instead of looking for cut points in the merged file which would take more effort). 
While others may have received notes from somebody on the minute/second marks but still even than that time code format is not right away obvious to everybody 00.08.43.181 vs 00.08.43 or 01:31:17.066 vs 91min17 sec mark, as they are not necessarily familiar with keyframes etc. like video editors are. :)

**Comment by mifi** [comment]
I think we can replace segment label with segment number for segments that have no label

**Comment by markusd1984** [comment]
I only discovered that labels are included at the end of the filename, sweet, so yes a good compromise/best of both worlds I guess.

By default we then get numbered segments but if somebody makes the effort of inserting labels will be happy to work with them instead. 👍
