### ISSUE TITLE
Make sure that the trash function doesn't delete the file if it cannot move it to trash

### ISSUE THREAD

**Issue by markusd1984** [mifi/lossless-cut#537]
Button to "Clear All Segments" in the timeline and make it more obvious compared to the delete/trash icon?

![image](https://user-images.githubusercontent.com/24621214/101775733-d1675a80-3ae7-11eb-8b70-d5fbe702a4be.png)

I had a user working directly with a file on the network which has no recycle bin enabled and in the rush thought the bin icon is to delete/clear the timeline selections (or possible to get rid of the video in the timeline to insert a new one) and thus also ignored the warning message and as a result lost the original video. 

Btw. "source file" may not necessarily be familiar to non techy people, perhaps change wording to "original file" and even include a remark that if they want to clear all segments instead that there is another way to do it (minus button or "clear all segments/timeline").

![image](https://user-images.githubusercontent.com/24621214/101776260-90237a80-3ae8-11eb-821b-cdf9df5f7744.png)

I would be actually in favour to use the trash icon to clear the time line and/or remove the video so it closes the project and present the "Drop Files" screen again (as not everyone thinks of dropping a new file over the existing project or using the file menu option to open one). Unless there is a common workflow more often used to keep adding files that require to delete the source files.... but it's rather easy enough to delete the file within the file explorer if/when needed.

**Comment by mifi** [comment]
I created an issue about the trash problem in the trash module. I think better to NOT delete the file if trash is not available.
I agree that the trash icon is a bit confusing and that the user might think it will trash the segments.
I think many people are used to File->Close (<kbd>CTRL</kbd>+<kbd>W</kbd>) for closing the current file tho

**Comment by markusd1984** [comment]
I think a button to clear the timeline selection and/or video entirely is helpful, as if somebody makes the effort to Close a project via File menu might as well instead click on File > Open and confirm the replace dialogue :) While clearing the video presents the Drag and drop screen that one is used to seeing at the program start (quicker/more intuitive).

Not sure why that trash was created in the first place, but just to use it as a substitute for replacing the existing video file when exporting a merged video seems rather overkill if not dangerous to me, risking loosing the **original** (source) file.

**Comment by mifi** [comment]
Maybe a better option would be:
- Trash icon clear video/timeline exactly like File->Close and CTRL+W, but it ALSO presents the user with a dialog askin them whether they want to delete the original file (with a RED button saying **Yes, delete original**, default to button **No, Keep file**).
Some people use the trash function (or rather the `D` hotkey) as part of their workflow for processing files and then quickly deleting them after

**Comment by mifi** [comment]
i added a dialog like this

<img width="545" alt="Screenshot 2020-12-11 at 21 50 01" src="https://user-images.githubusercontent.com/402547/101954239-0533a480-3bfc-11eb-91c1-b7d1d874e242.png">

**Comment by markusd1984** [comment]
sounds like a good combination, but sure I fuller understand the flow.

Perhaps one click on trash to bring up dialogue with all three option would be better.
> 1) Clear all segment - CTRL + ???
> 2) Close Video (to add new) - CTRL + W
> 3) Delete original source file

**Comment by mifi** [comment]
When is the need to delete all segments? Can't you just hold down backspace until all are gone?

**Comment by markusd1984** [comment]
Didn't even know about backspace and most normal users wouldn't neither. Yeah I suppose it's not a regular use case scenario, if one needs to make changes to segments it's usually 1) amend cut points 2) delete individual segments 3) change order 4) add labels and lastly perhaps if somebody decides to start from scratch to clear all segments (instead of pressing minus symbol several times just like pressing backspace repeatedly).

**Comment by markusd1984** [comment]
@mifi might be enough to just have a clear all segments/clear timeline command under the file menu (for those really need it).

**Comment by mifi** [comment]
Gonna look into switching to [shell.moveItemToTrash](https://www.electronjs.org/docs/api/shell#shellmoveitemtotrashfullpath-deleteonfail)
