### ISSUE TITLE
No .EXE in extracted folders

### ISSUE THREAD

**Issue by dumnonian** [mifi/lossless-cut#54]
Hi,LosslessCut 1.9.0 appears to be exactly the App I have been seeking for a long time, if only I could Run it! I have Downloaded LosslessCut-darwin-x64.zip numerous times, from github.com and videohelp.com. Whenever I Extract All on the downloaded Zip file there is no .EXE present.
I have atempted this Download & Extract on Windows 7 and 10 Systems, running Kaspersky or AVAST AV, using Chrome, Firefox, IE and Edge Browsers, all to no avail. I believe I have read of this issue arising before. Can you offer any suggestions to resolve please?

**Comment by wikijm** [comment]
Hi @dumnonian 

That's because you're not downloading the right release.
You must use one of those links:
- x86 - https://github.com/mifi/lossless-cut/releases/download/v1.9.0/LosslessCut-win32-ia32.zip
- x64 - https://github.com/mifi/lossless-cut/releases/download/v1.9.0/LosslessCut-win32-x64.zip

**Comment by mifi** [comment]
I have a TODO to rename the outputted file names
