### ISSUE TITLE
Can't create GIF file from videos

### ISSUE THREAD

**Issue by Shakil-Shahadat** [mifi/lossless-cut#540]
- [x] I have tested the newest version
- [x] I have checked [readme](https://github.com/mifi/lossless-cut) and **Known issues** / **Troubleshooting**
- [x] I have searched for similar issues

Tried couple of different video files, keyframe cut / normal cut.

Console shows '[gif @ 0000004db1cde900] GIF muxer supports only a single video GIF stream'. Although, I unchecked containing audio stream.

Tried extracting the video stream to a file and then converting it, didn't work either.

I'm not proficient with FFmpeg, so hadn't tried doing it using that yet, but will try next.

Also, the failed attempt creates a gif of size 0, auto-deletion of such files would be nicer.

**Comment by mifi** [comment]
Please provide more info about what you want to do. You want to remux a video to a GIF? I think this is only possible losslessly if the video contains a GIF stream inside.

**Comment by Shakil-Shahadat** [comment]
I want to create gif from videos. The videos I tried are in AVC. I selected gif from the format selection dropdown, removed audio and exported. It showed a warning that it is unable to export the file and asked to change the format and try some other things.

Those videos have only video and audio stream, no gif stream according to MediaInfo. I just want to know if this can't be done or this is a bug. If can't be done, it shouldn't be selectable and shouldn't create an empty file.

**Comment by mifi** [comment]
if you want to create a gif from a video, this is not a lossless operation, so it's better done with another app.
I agree that lc should warn if you try to put an AVC inside a GIF format, however there are over 100 different formats supported by ffmpeg, and I don't have a list of which codecs ffmpeg supports inside which formats, so I cannot really add that unfortunately.

**Comment by Shakil-Shahadat** [comment]
I understand. Thanks for your time.

**Comment by mifi** [comment]
I created an issue about improving this #547
