### ISSUE TITLE
prog starts with "something went wrong" every time

### ISSUE THREAD

**Issue by account-bug** [mifi/lossless-cut#544]
- [ x] I have tested the newest version that comes with linux mint 20
- [ x] I have checked [readme](https://github.com/mifi/lossless-cut) and **Known issues** / **Troubleshooting**
- [ x] I have searched for similar issues

Hi!
I tried to cut an .mp4 file. I set the cut marks. Inverted my decision by the yin-yang button. 1st time did not work- I cant remember what losslesscut commented. 
I restartet losslesscut. Tried the same again- yin-yang button. This time losslesscut ended showing a black screen with message "something went wrong. Cannot read property '0' of undefined. report error".
Next start losslesscut shows that screen from first moment. I reinstalled losslesscut. I restarted linux: Black screen with message is lasting whenever I start losslesscut. Can not use it anymore?!
But I managed to cut the file with the windows version of losslesscut without problems (I have dualboot system).

Dev-console:

Version 3.29.0
2.0bebc16b.chunk.js:2 react-i18next:: i18n.languages were undefined or empty undefined
2.0bebc16b.chunk.js:2 TypeError: Cannot read property '0' of undefined
    at main.d606bc44.chunk.js:1
    at Object.useMemo (2.0bebc16b.chunk.js:2)
    at useMemo (2.0bebc16b.chunk.js:2)
    at main.d606bc44.chunk.js:1
    at co (2.0bebc16b.chunk.js:2)
    at Wo (2.0bebc16b.chunk.js:2)
    at Yo (2.0bebc16b.chunk.js:2)
    at Go (2.0bebc16b.chunk.js:2)
    at Os (2.0bebc16b.chunk.js:2)
    at ml (2.0bebc16b.chunk.js:2)
main.d606bc44.chunk.js:1 componentDidCatch TypeError: Cannot read property '0' of undefined
    at main.d606bc44.chunk.js:1
    at Object.useMemo (2.0bebc16b.chunk.js:2)
    at useMemo (2.0bebc16b.chunk.js:2)
    at main.d606bc44.chunk.js:1
    at co (2.0bebc16b.chunk.js:2)
    at Wo (2.0bebc16b.chunk.js:2)
    at Yo (2.0bebc16b.chunk.js:2)
    at Go (2.0bebc16b.chunk.js:2)
    at Os (2.0bebc16b.chunk.js:2)
    at ml (2.0bebc16b.chunk.js:2) 
Object
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/build/static/js/2.0bebc16b.chunk.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/build/static/js/main.d606bc44.chunk.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/human-signals/build/src/main.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/human-signals/build/src/signals.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/human-signals/build/src/core.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/human-signals/build/src/realtime.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/strtok3/lib/index.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/strtok3/lib/FsPromise.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/strtok3/lib/core.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/strtok3/lib/ReadStreamTokenizer.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/strtok3/lib/AbstractTokenizer.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/peek-readable/lib/index.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/peek-readable/lib/EndOfFileStream.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/strtok3/lib/BufferTokenizer.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/strtok3/lib/FileTokenizer.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/cue-parser/lib/cue.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/chardet/lib/index.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/chardet/lib/fs/node.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/chardet/lib/encoding/utf8.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/chardet/lib/match.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/chardet/lib/encoding/unicode.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/chardet/lib/encoding/mbcs.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/chardet/lib/encoding/sbcs.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/chardet/lib/encoding/iso2022.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/cue-parser/lib/command.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/node_modules/cue-parser/lib/cuesheet.js.map
DevTools failed to parse SourceMap: file:///app/lossless-cut/resources/app.asar/build/static/css/main.698a3655.chunk.css.map
﻿
​
![Bildschirmfoto vom 2020-12-11 13-19-01](https://user-images.githubusercontent.com/75840337/101902771-7c911600-3bb3-11eb-9acb-68defb98d541.png)

thank you.

**Comment by mifi** [comment]
Hi. are you running newest version 3.29.1? Ther was a bug in 3.29.0

**Comment by account-bug** [comment]
No. I run 3.29.0, cause thats comming with mint 20. As far as I understood it is a flatpak programm. I do not know how to instal a flatpak prog manualy.

**Comment by mifi** [comment]
Ok, then either rollback to 3.23.8 (stable) or wait for 3.29.1 in flatpak. This is fixed in that version

**Comment by account-bug** [comment]
the "appimage" version was my rescue!

**Comment by mifi** [comment]
Perfect. note that merging is quite slow in the newest version. fix coming soon.
