### ISSUE TITLE
Project .csv output file include proper time marks and video filename

### ISSUE THREAD

**Issue by markusd1984** [mifi/lossless-cut#545]
If one needs to share time marks a proper time format to be included in a separate columns would be useful.

![image](https://user-images.githubusercontent.com/24621214/101917942-ac92e600-3bc0-11eb-848a-04b8687683fd.png)

As well as potentially having the source file name included in the first row so that ideally **Load Project can auto load the source file** as well (just like opening video first auto loads the project when present in same folder). Similar to #199 #181 #251.

![image](https://user-images.githubusercontent.com/24621214/101918401-39d63a80-3bc1-11eb-8def-a34d7c8b743e.png)

**Comment by mifi** [comment]
Yea, but I think if the project file is going to be more complicated than cutpoints (like file path, cut mode, track data etc), then we should use something like JSON instead. csv will be a hack for that. However I'm not sure if this is something most people need for a quick cutting tool.

**Comment by markusd1984** [comment]
Human readable time marks within a .CSV can be easily read and shared with somebody (who might do further advanced video editing) rather then a JSON, that's why I proposed it.

(Currently one would have to take a screenshot/s of the segments list or write them manually down to do so).

Auto loading video via project file probably shouldn't need the full file path (just like it currently works the other way around looking for an existing .CSV file with same name as video), thus name in first row could be sufficient.

I doubt that more info besides filename, time codes, hour/minute marks and labels would be needed/beneficial thus perhaps no need (yet) for JSON and better maintain .CSV for readability?

**Comment by mifi** [comment]
I think we can provide an "export project" option with a human readable CSV as one of the output formats.

**Comment by mifi** [comment]
I agree that we could auto load video based on name pattern taken from the csv file when someone opens a CSV, but this is already what happens when someone opens a video and there is a corresponding CSV file

**Comment by mifi** [comment]
<img width="436" alt="Screenshot 2020-12-14 at 17 27 18" src="https://user-images.githubusercontent.com/402547/102107120-a6f00700-3e31-11eb-8162-022003eb25a5.png">


<img width="313" alt="Screenshot 2020-12-14 at 17 25 24" src="https://user-images.githubusercontent.com/402547/102106889-68f2e300-3e31-11eb-95a3-f622051b1c00.png">

**Comment by markusd1984** [comment]
@mifi autoload video when open a project prevents the error message I shared above, that's why I would add that and because it's the most common way in other editors to open a project rather then video (to load a project) :smiley:

**Comment by markusd1984** [comment]
@mifi Looks great, but TSV not CSV? :grinning: 

I wouldn't call it human readable, this was more the term I used to differentiate hour/minute timestamps Vs timecode. Perhaps "timestamps".

**Comment by mifi** [comment]
I think TSV is more readable than CSV because got natural spacing between the timestamps. CSV is more cramped. and most programs that can import CSV can also import TSV

**Comment by markusd1984** [comment]
I see, yeah in my entire IT life never heard of TSV, people are mainly familiar with CSV just as they are with TXT thus just wondering if people might wonder why to export as "TSV" or "human readable." Anyway i'd recommend at least to change the wording to laymen terms.

**Comment by mifi** [comment]
Yea I changed the wording to "Timestamps (TSV)" instead of human readable. I can create one CSV option also, it's super easy. I was thinking that txt is easier for people to open in notepad or whatever. They might wonder about how to open a .tsv file if they don't have any app for it. If it's .txt they can just easily glace over the data there, or they can copy paste the data into excel or other programs and it will show up as columns automatically

**Comment by markusd1984** [comment]
why not call it TXT then? :grinning:

"Timestamps (TXT)" makes more sense.

**Comment by mifi** [comment]
Because TSV is also a well recognized format. I think "Timestamps (TSV/TXT)" is nice. and i allow saving both to .tsv and to .txt

**Comment by markusd1984** [comment]
Brilliant

**Comment by quorten** [comment]
Relating to storing more info in a JSON project file format...  For supporting the use case of generating the output video segment(s) via "command-line export" like Inkscape, the export/merge parameters would be additional useful information to store in a project file.

**Comment by mifi** [comment]
The newest version now saves the main project file as .llc which is a JSON5 format and it includes information like per-segment tags, and the name of the media file that it relates to. Can also open the .llc files directly if they are in the same folder as the media file, and losslesscut will open up the file with the segments at the same time. Closing this
