### ISSUE TITLE
Allow modifier keys when using scroll on timeline for rougher jumps/finer control

### ISSUE THREAD

**Issue by Wiethoofd** [mifi/lossless-cut#553]
Currently in the controls help it lists:
> CTRL/cmd + Mouse scroll/wheel up/down - Zoom in/out timeline
> Mouse scroll/wheel left/right - Pan timeline

As seen above the ctrl/cmd + scroll modifier combo is already taken for zooming in and out of the timeline, but this only works when your cursor is actually over the timeline, additionally `shift` and `alt` are still available to possibly use here. And the hotkeys listed under 'seeking' aren't as useful or consistent as having the scroll on timeline.

Holding shift for increased jumps in the timeline would be beneficial to skip through segments more quickly, without having to scroll the default 5s jumps a lot or zooming out of the timeline to manually jump to a time elsewhere.

`ALT` could perhaps be used for finer control, jumps per keyframe or just smaller increments of ~1 second, compared to the default 5.

Alternatively a change to the hotkeys:
- Z + scroll / Z + up/down arrow keys = zoom timeline
- Scroll on timeline = skip 5s
- Alt + scroll on timeline = skip 1s/keyframe
- Ctrl/cmd + scroll on timeline = skip 10s (keeping the original behaviour to zoom when cursor is not on timeline)
- Shift + scroll on timeline = skip 30-60s

**Comment by markusd1984** [comment]
Great idea to improve seeking, we could even make one of them **configurable** , perhaps the largest one default to 30secs and allow in the settings to enter seconds values  (e.g. 45, 60, 120 etc. ).

**Comment by mifi** [comment]
I will change so that mouse wheel scroll works also when the cursor is over the video, not just timeline.

**Comment by mifi** [comment]
Have now added the possibility to change several speed parameters for scrolling and keyboard arrows

> * Z + scroll / Z + up/down arrow keys = zoom timeline

CTRL will already provide this function, why would Z be better?

**Comment by Wiethoofd** [comment]
> CTRL will already provide this function, why would Z be better?

Ctrl is generally considered a modifier key, where 'Z' is currently unused and would make sense for a **Z**oom action hotkey.

**Comment by mifi** [comment]
I think modifier keys are usually used for modifying the behavior of another button or action. Z is not a modifier key, and I'm not sure how common it is to use any non-modifier key as a modifier for another key. (CTRL is already used for modifying up/down to make them zoom in/out)

**Comment by mifi** [comment]
closing in favor of #1884
