### ISSUE TITLE
Zoom dropdown only shows 'zoom' for each level, no scaling factor

### ISSUE THREAD

**Issue by Wiethoofd** [mifi/lossless-cut#555]
- [x] I have tested the [newest version](https://github.com/mifi/lossless-cut/releases/latest) from GitHub: `3.30.0`
- [x] I have searched for similar issues or existing pull requests/commits fixing this issue

Just launching the program shows the issue with the zoom levels in the dropdown not having their scaling factor in it, just says 'Zoom' for all, selecting them still works, just a visual error.

Inspect shows:
![losslesscut_zoom](https://user-images.githubusercontent.com/9917564/102376778-42b17c80-3fc4-11eb-87bc-5c8977c32219.png)

**Comment by mifi** [comment]
Oops! I created this bug. Thanks for reporting
