### ISSUE TITLE
Audio Index:2 / Stream:2 no sound in "Preview"

### ISSUE THREAD

**Issue by dhinoz** [mifi/lossless-cut#558]
hi. i can't find solution / issue for this or i miss somewhere to search.

Win10
Source DVR.MP4 ( SHADOWPLAY nvidiaGeforce ) 
audio preview.

**index / stream 0:1 : GameAudio ( any desktop sound ) < work fine.
index / stream 0:2 : Microphone ( BananaInput etc ) < no sound.**

![IssueLosslesscut](https://user-images.githubusercontent.com/76182701/102540357-e0529c00-40e9-11eb-8cac-cde3c92e669f.JPG)

both metadata same.
export everything fine !
usually i use vlc with batch for review 
`start "" "path vlc" --sout-all --sout #display %1%`

_thank you for the beast tool!_

**Comment by mifi** [comment]
Hi. It's currently not possible to preview audio from secondary tracks/streams. See #256

**Comment by dhinoz** [comment]
ok noted !
