### ISSUE TITLE
Feature request: Set in and out time manually

### ISSUE THREAD

**Issue by ezra100** [mifi/lossless-cut#56]
Hi
I have a computer which doesn't have the greatest CPU (i3-4500U), when I run screen records from my FHD phone it plays smoothly on VLC but Lossless-Cut gets stuck with it (like about 3-5 seconds to response when trying to jump to some point in the video), so it would be very useful for me if I can just watch the video with VLC and then just feed the in and out time textually.
Since clicking on the in/out time is already reserved for seeking the video to that time maybe a double click can be set for manual setting.
Thanks
Ezra

**Comment by TechManiacHD** [comment]
Your CPU is not really "up to date" but I can just guess that Losseless-Cut uses hardware acceleration if available on CPU. I have been using Losseless-cut on MeLE PCG35 APO to cut 4K30FPS footage and it was smooth as hell :)

**Comment by mifi** [comment]
@ezra100 I have been noticing the same too, seeking takes a while on some videos. I think it has to do with the chromium video player. maybe it gets improved in a new version of electron/chromium.

Regarding manual seeking, I agree it could be a nice addition. I don't have time now though.

**Comment by mifi** [comment]
I have implemented this as of 24e1aa5bcd8a3899ab6d166f7f6bbad36a1e8d75, and it will be included in the next release!
