### ISSUE TITLE
renaming files

### ISSUE THREAD

**Issue by senkqs** [mifi/lossless-cut#561]
Hello,
It'd be nice if there was a way in the option to keep the label name of segments at the end of the name of the exported name files when doing separate files exporting, I don't know if it'd be possible

**Comment by markusd1984** [comment]
That's actually brilliant, as an option in the export dialogue or in settings only when the split export option is selected.

**Comment by relief-melone** [comment]
I would also like to just use the label as the exported files name when choosing separate files. I would make this pr myself but unfortunately I'm currently too occupied with another project to work my way through the projects structure. Also haven't used electron yet. I would love to contribute at a later time though.

This is by far the best tool to cut videos i have come across.

**Comment by wallacemaciel13** [comment]
There is any option to rename each file before export?
This program would be perfect to me if a box ask me for file name and save path. Similar whats google chrome does when you set the checkbox "Ask where to save each file before downloading".

**Comment by markusd1984** [comment]
@wallacemaciel13 just try it out with the latest version and click on export where you can set the location and if you right clicked the segments in the list you can also label them which will be used in the filenames, but no custom file naming besides that.

**Comment by mifi** [comment]
I'm not sure if this is different from #96 ? 

Afaik we are already exporting label name at the end of output files

**Comment by mifi** [comment]
Closing this due to lack of response, and I believe this is already impemented
