### ISSUE TITLE
Feature request: Allow specifying target video in script that opens losslesscut

### ISSUE THREAD

**Issue by jackmac92** [mifi/lossless-cut#565]
- [x] I have tested the newest version from GitHub: https://github.com/mifi/lossless-cut/releases/latest
- [x] I have checked [readme](https://github.com/mifi/lossless-cut) and **Known issues** / **Troubleshooting**
- [x] I have searched for similar issues

I'd like to be able to write a script which opens losslesscut with the target video already selected (e.g. no need for drag and drop/ open file dialog)

Is that something you've looked into before?

**Comment by mifi** [comment]
You can do like this: `/path/to/LosslessCut /path/to/your/file.mp4`

**Comment by jackmac92** [comment]
This wasn't working for me with the snap store install, but it is after installing from the latest bz2

**Comment by mifi** [comment]
Ok. I don't have the resources to look into snap issue but if anyone wants i'm happy to accept PR.

**Comment by mifi** [comment]
I have updated snap stable to latest (3.30.0) now, maybe that helps
