### ISSUE TITLE
Problems when merging files

### ISSUE THREAD

**Issue by StarkZaibatsu** [mifi/lossless-cut#566]
There are several issues when dragging two files into the program to merge including:

- If there is an audio file and video file dragged into together and the top file is an audio file, it will merge them into audio files instead of a video file
- Even when the video file is on top and the audio file is second, after merging the frame rate is wrong. In this case, a 23.98 fps file became 66.43

If you would like me to video capture these in action, I can do that for you as well.

**Comment by Droyk** [comment]
What happens if you merge 2 separate video files? or take one video demerge it using lossless cut and then merge that demerged video with another video?  #562 
I'll like to see if this is only happening to me or not? or if this issue is related or not #562?
Can you check into it?

**Comment by StarkZaibatsu** [comment]
I think it's a different issue. If I import an audio file and video file manually by dragging them into the program, then hitting export it works fine. However, if I use the "merge files"  feature that's when things go wrong. Can I email you a sample of the progress?

**Comment by StarkZaibatsu** [comment]
Email sent with video link

**Comment by mifi** [comment]
Hi. I assume you are Christopher. I saw your video. I think you are misunderstanding the merge function. Merge (dragging multiple files) will merge in the time domain (I understand it's confusing). Your second attempt where you drag two files separately is the correct way. I'm not sure why the fps changes though. if you shareinput files that produce this problem I could look into it. I will improve the text on the merge dialog

**Comment by StarkZaibatsu** [comment]
Hi,

Thanks for your reply and thanks for all your work on this awesome program. I seem to this difference in frame rate with every video file I've "merged" so far. Does it not happen for you?

If not, I can send some sample files for you
________________________________

**Comment by mifi** [comment]
Do you merge 2 files with the same fps? If yes, then you could send me the files and I can look at it

**Comment by StarkZaibatsu** [comment]
Hi,

I think I know why, it's because I was trying to merge an audio file with a video file. I've been downloading audio and video files that are separated while streaming online (m3u).

So I had the audio (.m4a) and video component (.mp4) and was trying to combine them to make a new mp4 video file.
________________________________

**Comment by mifi** [comment]
Then try to open the video first, then drag drop the audio after that, and select the second option in the dialog.

**Comment by StarkZaibatsu** [comment]
Yes, that is the way that has been working. I think I misunderstood what the "merge" function meant. It works perfectly when I drag the video and audio file together into the app.
Thanks
________________________________

**Comment by mifi** [comment]
Cool! I agree the terminology is a bit confusing. I'm thinking of renaming "merge" to concatenate or stitch or something else.
