### ISSUE TITLE
fourcc=avc1 doesn't work

### ISSUE THREAD

**Issue by pstein** [mifi/lossless-cut#567]
When I load a *.mp4 video file with AVC/H.265 video codec and with AAC audio codec into LC v3.30.0 then I have problems with the video.
When I click on the "play" control no progress is observable for approx 10 seconds.
After 10 seconds I can hear the audio but the video part remains black.
If I click somewhere on the timeline then it takes again some seconds until I can hear again the audio but video is still black.

If I drag other videos with the same video codec but MP3 audio codec then everything works immediately.
Audio and video are present as expected.

Have a look at the attached snapshot of what the well know tool MediaInfo shows about the codecs and container of the problem video.

Since I can play the video with other videoplayers like VLC the problem must be in LC.
When I drag it into Avidemux I can play and cut it successfully as well.

It seems to me that LC has problems with the handling of AAC.
Can someone confirm this?

![Losslesscut problem with AAC audio codec](https://user-images.githubusercontent.com/2775875/103147994-1f709500-475b-11eb-96a1-544806553415.png)

**Comment by Shakil-Shahadat** [comment]
1. From the [Supported formats](https://github.com/mifi/lossless-cut#supported-formats) part of the `README.md`

> Since LosslessCut is based on Chromium and uses the HTML5 video player, not all ffmpeg supported formats will be supported smoothly.

2. Again, quoting from the same section,

> Unsupported files can still be converted to a supported format/codec from the `File` menu. (Try fastest variant first.) A low quality version of the file (without audio) will then be created and opened in the player.

3. Update your MediaInfo software and select `HTML` from the `View` menu and then share a screenshot or even better, share an exported file from `File > Export`. That way, the dev will have more to work with.

**Comment by pstein** [comment]
Meanwhile I found the problem:

I (re)encoded the original MP4 with the FourCC code=avc1

When I (re)encode it with exactly the same video+audio codec parameters but with different FourCC code=avc3
it works!

This strange.

LosslessCut should be able to handle MP4 video files with FourCC=avc1 too.
At least LC should detect this and pop up a warning "FourCC=avc1 is unsupported"

**Comment by mifi** [comment]
Thanks for sharing your workaround. Indeed it should work with fourcc=avc1 if that is a valid file. If posible to share a short file that has this problem?

**Comment by mifi** [comment]
I believe that AVC is **not** h265. It is h264.

**Comment by mifi** [comment]
closing due to lack of response
