### ISSUE TITLE
[Request Features] File Rename + Looped Preview

### ISSUE THREAD

**Issue by Vaarelsauce** [mifi/lossless-cut#568]
As the title suggests, it would be nice to be able to rename the file before exporting it, saving a lot of hassle. In addition, there could be a checkbox asking the user if they way to delete the original video (of course by "deleting" it simply means moving the old video to the Recycle Bin).

The second feature that would be quite nice is when I'm previewing a certain segment, there could be a toggle to loop back to the preview mark when done.
**EX:** I set the export from the frame at 1:00 to 3:00 mark. I then click the loop toggle, and when I press play, after 2 minutes, it loops back to the 1-minute mark and starts again automatically.
Now if there are multiple segments, next to the toggle there could be an expandable arrow, which shows a looping checkbox for SEGMENT 1, SEGMENT 2, SEGMENT 3, etc., and the user can decide which part gets looped in the preview and which parts don't.

Cheers.

**Comment by markusd1984** [comment]
Some good ideas both somewhat already posted though (please use the search before posting) and should be enhanced there.

Rename #561
Preview #253

**Comment by mifi** [comment]
thanks for suggestions, I need to close this as dup because alot of issues. Please add suggestions in the respective issues.
