### ISSUE TITLE
Add Kbd Shortcuts to help when using a Jog & Shuttle input device

### ISSUE THREAD

**Issue by TheNewbieWoodworker** [mifi/lossless-cut#570]
I use a [ShuttlePRO v2](https://www.contourdesign.com/product/shuttle/) when editing videos. It works mostly by generating keystrokes. So it would be helpful if you could add **keyboard shortcuts** for:

1) Playback 2x, 3x, 4x, etc., up to whatever max speed makes sense. Honestly, anything over, say 6x is probably overkill for LC, but whatever works.
2) Separate Pause and Play shortcuts. The standard "toggle" play/pause shortcut is always useful of course, so I'm not talking about replacing that - just adding new shortcuts to specifically start or stop.
3) If it's possible to add reverse play, that would really be helpful. If you can have speed shortcuts like in `#1`, that would be awesome, but just reverse at normal speed would be great.

You're doing an awesome job with this app, and I'm thrilled with it! I'm a YouTuber, and I end up with tons of video files for each project, which are all shot at 4K so they take up a lot of space. Before LC, I was anal about stopping the camera each time I needed to do some "off camera" work. But now I don't have to do that, because I can just cut it out. Thank you so much.

**Comment by mifi** [comment]
I'm happy to hear your use case!

> * Playback 2x, 3x, 4x, etc., up to whatever max speed makes sense. Honestly, anything over, say 6x is probably overkill for LC, but whatever works.

Doesn't j k l suffice for you?

I think custom keyboard bindings would solve these. See #254 
Also I created a separate request for reverse playback #601

**Comment by TheNewbieWoodworker** [comment]
> Doesn't j k l suffice for you?

Well, sort of, but it would work a lot better to have direct shortcuts to those speeds. When I turn the shuttle, it works better if I can assign a specific speed to each "slot" in the shuttle.

Yes, custom key bindings would work great, assuming there's an associated playback speed action to assign them to. Thanks!

**Comment by mifi** [comment]
> * Playback 2x, 3x, 4x, etc., up to whatever max speed makes sense. Honestly, anything over, say 6x is probably overkill for LC, but whatever works.

I think now that JKL with exponential speed up is implemented, it might solve your usecase.

I will add these to #254 nevertheless, and close this issue in favor of that one.
