### ISSUE TITLE
Confusing error when disk is full

### ISSUE THREAD

**Issue by ErwinCraps** [mifi/lossless-cut#571]
When the storage is full it returns a confusing error that the file can not be exported with a various list of causes but not that the disk is full. The current error rather makes one believe there's an issue with the file.
It would be more clear when it simply says the disk is full.
![Schermafbeelding 2021-01-02 111624](https://user-images.githubusercontent.com/6746662/103455295-3891bc80-4cec-11eb-8677-f5dfcc30b46e.jpg)

**Comment by Shakil-Shahadat** [comment]
For the time being, I have added a warning #572 that says 'Check if the disk is full'.

**Comment by mifi** [comment]
Have improved this now in #328 , will be included in the next version
