### ISSUE TITLE
mov qt files  play  black screen no video show :(((

### ISSUE THREAD

**Issue by drmusti** [mifi/lossless-cut#575]
mov qt files  play  black screen no video show :(((
Sincerely

**Comment by Shakil-Shahadat** [comment]
Did you try converting it to a supported format?

**Comment by drmusti** [comment]
yes big programmer

**Comment by Shakil-Shahadat** [comment]
> yes big programmer

What do you mean by `big programmer` here?

**Comment by drmusti** [comment]
because your software number one on the world.  my english bad. sorry. big programmer = best coder best programmer.

**Comment by mifi** [comment]
please provide a sample video then I can look into it

**Comment by mifi** [comment]
Possibly related #567

**Comment by mifi** [comment]
closung due to inactivity
