### ISSUE TITLE
[Feature Request] Queue / Multiple Video Workflow

### ISSUE THREAD

**Issue by 0xDAFE** [mifi/lossless-cut#584]
- [x] I have tested the newest version from GitHub: https://github.com/mifi/lossless-cut/releases/latest
- [x] I have checked [readme](https://github.com/mifi/lossless-cut) and **Known issues** / **Troubleshooting**
- [x] I have searched for similar issues

Hi everyone,

I am using Losless Cut for quite some time now and would like to thank you for making this awesome tool.

My use case is often processing a number of longer video files (e.g. action cam recordings) and extracting the interesting parts, throwing away the complete file afterwards.

What would be really helpful in my opinion is some kind of video queue, where you can drop a folder or multiple files and jump to the next video as soon as you are done with one e.g. with a key binding or automatically when deleting a video from within Losless Cut.

Best Regards!

**Comment by mifi** [comment]
Hi. I'm glad you like it. This is indeed a great idea, and has been suggested already. Please provide any additional suggestions here #89
