### ISSUE TITLE
[Bugfix] Keyframe seeking rounds wrongly

### ISSUE THREAD

**Issue by thomasbachem** [mifi/lossless-cut#585]
The rounding in [`App.seekAbs()`](https://github.com/mifi/lossless-cut/blob/927c0de461d31639ca8e038cf2031fe84615a28d/src/App.jsx#L295) produces wrong results, i.e. non-existant frame times. This may lead to ffmpeg using the previous keyframe for cutting instead of the intended one.

- [x] `detectedFps` is `59.94` **(correct)**
- [x] `findNearestKeyFrameTime({ time: 10, direction: -1 })` returns `8.660289` **(correct)**
- [ ] `seekAbs(8.660289)` seeks to position `8.658650090908136` **(incorrect, there's no frame at all with this position)**

So  [`this line`](https://github.com/mifi/lossless-cut/blob/927c0de461d31639ca8e038cf2031fe84615a28d/src/App.jsx#L295) messes things up:
```
if (detectedFps) valRounded = Math.round(detectedFps * val) / detectedFps; // Round to nearest frame
````
Maybe it can just be removed these days?

--

**Background Info:**

Video File (MP4):
```
Duration: 00:08:49.17, start: 0.000000, bitrate: 9325 kb/s
    Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(tv, bt709), 3840x2160 [SAR 1:1 DAR 16:9], 9146 kb/s, 59.94 fps, 59.94 tbr, 90k tbn, 180k tbc (default)
```

Frames (excerpt):
```
[...]
{ "pts_time": "8.643600", "flags": "__" },
{ "pts_time": "8.660289", "flags": "K_" },
{ "pts_time": "8.676967", "flags": "__" },
[...]
```

**Comment by mifi** [comment]
I also noticed that there is something funky with the rounding sometimes.

I think we can remove the rounding, but what I wanted to achieve was that when the user scrubs the timeline, inputs a time to jump to, uses the left/right buttons, then I wanted the time to be on an actual frame, and not just an arbitrary time value. Need to think a bit more about how to correctly implement this.

My thought was that `Math.round(detectedFps * requestedTime)` should equal the frame number nearest to the desired seek, then divide that by the FPS to get the time value of that frame. Maybe I'm missing something here.
