### ISSUE TITLE
Improve initial screen (for beginners)

### ISSUE THREAD

**Issue by mifi** [mifi/lossless-cut#587]
Many people just drop their file and ignore the initial DROP FILE ibnstructions. Then they don't know how to set cutpoints with <kbd>I</kbd>/<kbd>O</kbd>. Maybe show these instructions after user has opened a file, but psosibility to disable

**Comment by markusd1984** [comment]
@mifi The help section and hover quick info still are good easy resource for those who don't find the simple interface Intuitive enough.

But sure given the point of the app is to cut videos we could show an overlay of those instructions untill the first segment is selected, than make it dissappear to be less intrusive. :)

**Comment by mifi** [comment]
I think after implementing the simple interface #546, this shouldn't be a big problem anymore. The rest can be solved in #549
