### ISSUE TITLE
Support batch files merge parameter (command line)

### ISSUE THREAD

**Issue by xmha97** [mifi/lossless-cut#591]
- [X] I have tested the newest version from GitHub: https://github.com/mifi/lossless-cut/releases/latest
- [X] I have checked [readme](https://github.com/mifi/lossless-cut) and **Known issues** / **Troubleshooting**
- [X] I have searched for similar issues

Hi, Please support the batch files parameter (command line)
```
"C:\LosslessCut\LosslessCut.exe" "F:\1.mp4" "F:\2.mp4"
```

![Lossless Cut](https://user-images.githubusercontent.com/23485114/104136066-31804380-53a9-11eb-8619-53855d3dc19d.png)

Thnaks.

**Comment by quorten** [comment]
Just use FFMPEG directly:

```
ffmpeg -protocol_whitelist file,pipe -f concat -safe 0 -i - -c copy -y pre_trim.mp4 <<EOF
file '1.mp4'
file '2.mp4'
EOF
```

In my opinion, the way to fix this on the LosslessCut side is to make the command-line generation passed to FFMPEG more transparent to users.

**Comment by mifi** [comment]
Implemented and will be avail in next version

**Comment by roboknight** [comment]
OOOOOHHHH, does this work?  This would be REALLY awesome.  Especially for the project I'm currently working.  When is the next version due?

**Comment by mifi** [comment]
Will release it in the coming days

**Comment by xmha97** [comment]
Fixed on: https://github.com/mifi/lossless-cut/releases/tag/v3.32.0
