### ISSUE TITLE
ffmpeg command was killed with SIGILL (Invalid machine instruction): 

### ISSUE THREAD

**Issue by MartinBarker** [mifi/lossless-cut#592]
Hello, I am trying to make my own electron app that uses ffmpeg for the mac-apple-store (mas), I found your blog post explaining how to do so and tried following it with my own project 'digify', but when I run an ffmpeg command I get an error message in my electron window console that says something like:
```
Error: Command was killed with SIGILL (Invalid machine instruction): /Users/martinbarker/Documents/projects/lossless-cut/dist/mas/LosslessCut.app/Contents/Resources/ffprobe -of json -show_format -i /Users/martinbarker/Documents/testfiles/NEWWOWIEfullAlbum-577-00.00.00.000-00.05.06.500-seg1.mp4
```
I am trying to build lossless-cut for the mac apple store to verify that the outputted `dist/mas/LosslessCut.app` can run ffmpeg commands.

I cloned lossless-cut, the master branch, generated ffmpeg-mac/ and the icons, and ran this series of commands:
```
rm -rf dist/ && electron-builder build --mac && sudo codesign --deep --force --verbose --sign 'CF~~my-id-~~B3' dist/mas/LosslessCut.app
```

Once the mas build has finished and I have signed the .app file, I can open it, but whenever an ffmpeg command gets called, I get the same console error: 
![Screen Shot 2021-01-10 at 4 58 58 PM](https://user-images.githubusercontent.com/27025504/104140214-302d2780-5365-11eb-8e51-887adfb08347.png)

I had to make minor changes to the package.json file in order to get the build to finish: such as adding electron.js and menu.js to the buil: files:[] array, and removing the line `"afterSign": "electron-builder-notarize",'` as it was throwing an error saying electron-builder-notarize module was not found.

Do you know what this error message `Error: Command was killed with SIGILL (Invalid machine instruction): ` means? It only appears when an ffmpeg command tries to run

**Comment by mifi** [comment]
Did you figure it out? was it lack of signing?

**Comment by MartinBarker** [comment]
Yes I was signing with the wrong apple ID
