### ISSUE TITLE
[Feature request] Ask about how to convert unsupported file upon opening

### ISSUE THREAD

**Issue by Rubens10010** [mifi/lossless-cut#595]
- [* ] I have tested the newest version from GitHub: https://github.com/mifi/lossless-cut/releases/latest
- [ *] I have checked [readme](https://github.com/mifi/lossless-cut) and **Known issues** / **Troubleshooting**
- [ *] I have searched for similar issues

Hi I've been using this amazing app for a long time now but I was wondering if you could provide some sort of option to set a default convert format for unsupported codecs. Currently I have to go to file > convert to supported format > fastest - every time.

**Comment by slrslr** [comment]
I am looking for the similar, only i want the default be the one that will play audio and that is not the fastest one per my experience.

Currently, often it convert to the fastest format without audio which is useless for me so this way there have to do one more conversion manually from the file menu (can be confusing to the newbie user). Maybe the best would be if the app shows the dialog upon detecting unsupported file.

**Comment by mifi** [comment]
@Rubens10010  LosslessCut is supposed to do this automatically when it detects an unsupported file. What file is this?

@slrslr I agree that it makes sense to ask about this. Maybe it could even be a configurable setting.

**Comment by Rubens10010** [comment]
@mifi Thanks for your time. I took a random shot available on https://drive.google.com/file/d/1kRHiPx9K-LsTZ4Vyr1Bg-8mWXwugyia5/view?usp=sharing. When I drag it to LosslessCut it loads and app screen gets black, sound plays normally. This was taken with a Lg Bello II.

**Comment by mifi** [comment]
```
Stream #0:0(eng): Video: mpeg4 (Simple Profile) (mp4v / 0x7634706D), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 4728 kb/s, 14.33 fps, 28.58 tbr, 90k tbn, 300 tbc (default)
```

It seems like your file has mpeg4 video, I don't think it's supported by Chrome/Chromium (used by llc).
For some reason it just plays it black without reporting an error. I believe this is a bug in Chromium.

**Comment by Rubens10010** [comment]
Ok. I reported this bug in Chromium as well. Thanks for your support I will be waiting for next update.
