### ISSUE TITLE
req: audio waveform with zoom and thumbnails

### ISSUE THREAD

**Issue by FredThompsonII** [mifi/lossless-cut#6]
Any plan to add audio waveform and a scrollbar with zoom in/out for time scale and thumbnails?
I ask because I'm currently using another app to cut long streaming files into pieces. Finding gaps between content is easier with a waveform (I look for empty regions) and thumbnails which can show standard intro/outro sections.

**Comment by mifi** [comment]
It should be possible but I can imagine that it would require preprocessing in order to create thumbnails/waveform, and this will probably take some time, defeating the purpose of this being a very fast app.

**Comment by TechManiacHD** [comment]
Would be nice to have but not that essential INHO. Program is currently blazing fast so adding this future might hurt it.

**Comment by opusforlife2** [comment]
https://trac.ffmpeg.org/wiki/Waveform

@mifi Have you looked at this filter? It's a part of ffmpeg.

**Comment by mifi** [comment]
Also this: https://github.com/katspaugh/wavesurfer.js

**Comment by mifi** [comment]
Waveform and thumbnails is now implemented

**Comment by WiliTest** [comment]
I wish I could use it to quickly trim audio, but the waveform is too small/basic. Would it be possible to add a real  waveform, just for audio files (it's needed to find the right spot on long audio files)?

**Comment by opusforlife2** [comment]
I agree. With audio files, the entire space kept for video is wasted real estate. The audio waveform could be much bigger and easier to see.

Also, the waveform only shows up for part of the file. If you jump to another frame, the audio waveform gets extended further, but the beginning portion gets cut off. Is it a limitation that the entire waveform cannot be shown at once? One would think since it's a static property of a file, it could be loaded fully just once and that's it.

**Comment by mifi** [comment]
It's a technical limitation because rendering the waveform takes a long time. So it will only render 30 seconds at a time. I'm not sure what is the best way to render a zoomed out waveform overview for the whole clip. See #260

**Comment by opusforlife2** [comment]
I'm not sure I get this. Rendering 30 seconds at a time shouldn't prevent you from still displaying the already rendered waveform. It's fine if a 2 minute song renders in 4 sections. Or is the problem something else?

**Comment by mifi** [comment]
Yes, we could keep the already rendered waveform. I can make that change.

**Comment by opusforlife2** [comment]
> With audio files, the entire space kept for video is wasted real estate. The audio waveform could be much bigger and easier to see.

And what is your opinion on this?

**Comment by mifi** [comment]
> And what is your opinion on this?

You mean you want it to be taller or expandable? That shouldn't be too hard

**Comment by opusforlife2** [comment]
Taller, definitely, like 6-7 times the current height. Something like the size Audacity shows, so that it is easy to comprehend and use.

Expandable is up to you.

**Comment by mifi** [comment]
Closing in favor of #260
