### ISSUE TITLE
icon missing

### ISSUE THREAD

**Issue by jose1711** [mifi/lossless-cut#60]
i've made a pkgbuild for arch linux: https://aur.archlinux.org/packages/losslesscut/ but icon is sorely missing. currently an ugly placeholder is displayed instead. anyone able to make a nice looking icon?

**Comment by mifi** [comment]
Icon can be found here:
https://github.com/mifi/lossless-cut/blob/master/src/icon.svg

**Comment by jose1711** [comment]
thank you, PKGBUILD has been updated accordingly
