### ISSUE TITLE
create keyframe at start cut point?

### ISSUE THREAD

**Issue by allefeld** [mifi/lossless-cut#602]
I understand that the focus of lossless-cut is on, well, lossless cutting, and that means that the original video data is not modified.

I understand – less well – that for a cut to work, it needs to start on a keyframe (I assume, an "I-frame"?) because the other frames do not contain complete images.

However, that sometimes restricts cut points severely. For example, I'm currently trying to get a 15 s clip out of a 1 h 51 min video, and from the place where I would like to cut, the nearest previous keyframe is in another scene which I don't want to include, and the nearest following keyframe is almost 2 s later, losing a significant part of the clip.

Therefore my question: Would it be possible to implement some magic which creates a new keyframe at the chosen start cut point?

**Comment by Shakil-Shahadat** [comment]
See #126.

**Comment by allefeld** [comment]
Yes, seems to be the same.
