### ISSUE TITLE
Add a setting for "Seek forward/backward" period (1 sec by default)

### ISSUE THREAD

**Issue by Aleks-Ya** [mifi/lossless-cut#604]
1 second seeking period is too small for my cases (and 1% is too big). I need 4 sec period. Could you add settings to configure custom period for "Seek forward/backward 1 sec" feature?

Now I have to use SMPlayer to find segment beginning times (it supports custom seek period), write times to a notepad, open video in LosslessCut and enter segments manually. It's really disappointing wasting of time!

PS Otherwise the app is excellent, thank you very much for it!

**Comment by markusd1984** [comment]
Similar to https://github.com/mifi/lossless-cut/issues/553#issuecomment-746023189, ideally to have a setting for custom periods in seconds and also have key mapped for different intervals.

**Comment by mifi** [comment]
I'm thinking about an acceleration when holding a button down (for each auto-repeat event I can increase the seeking speed), then it resets to 1 when left or right key is released. I'm testing it out and it seems to work nicely. could allow configuring the factor

**Comment by mifi** [comment]
https://user-images.githubusercontent.com/402547/105393005-22588b80-5c1c-11eb-8411-c6aed7718242.mov

**Comment by markusd1984** [comment]
Wow that is super cool and practical for general use!

Perhaps there is still the use case for scanning through content at a fixed pace where dynamic speeding up will not allow this properly to view the timeline, just getting quicker to a point in the timeline (eliminating the need to click into the timeline).

Perhaps a setting to set normal scroll speed, dynamic as you showed and fee more factors X2, x3, x4 or way to enter seconds. Best of all worlds. :)

**Comment by mifi** [comment]
Implemented in commit https://github.com/mifi/lossless-cut/commit/8ea08cf65c2e0b756710b1adbdc5c5b566ab6720 (accidentatlly referenced the wrong issue)

**Comment by mifi** [comment]
Closing this as it is implemented now and will be out in the next version

**Comment by markusd1984** [comment]
Sweet, both your dynamic seeking and and multiple custom fixed faster intervals?

**Comment by mifi** [comment]
not multiple intervals but custom seek period (settings) and acceleration (settings). multiple intervals can be a TODO here: #553

**Comment by markusd1984** [comment]
Still exactly sure what you mean by **custom**  seek period and acceleration? Two different settings but what can be set in each? 

Just to enabled or when you say custom to do you mean enter a value in seconds or something?

No probs, i can wait till the next executable is released and surely will try it out, you rock. :smile:

**Comment by mifi** [comment]
yes custom as in seconds, with a slider like wheel sensitivity
I mean the interval that the timeline cursor will jump when the user presses the LEFT or RIGHT button used to be 1 sec, now configurable

**Comment by markusd1984** [comment]
Now work! I just love dynamically going faster, this will save so much time clicking :smiley:

Could we please though use UP/DOWN for frame by frame? 
Really miss this, being used to using left/right for this in most video editors.

Perhaps better even if we could make it so that individual left/right click goes into frame by frame selection Vs long press accelerating? Best of both worlds! :wink:

**Comment by markusd1984** [comment]
sorry we probably should keep the left/right 1 sec advancing for general use and see up/down switches between segments - all though not sure if that gets much regular use, would have thought that precise cuts to be used more often by some. 

1) If we can't use up/down keys perhaps another key combination like CTRL+L/R, ALT+L/R i.e. **CTRL+ALT+L/R** @mifi https://github.com/mifi/lossless-cut/issues/553#issuecomment-74602 ?

2) **more flexibility could be by having these shortcuts configurable in seconds** https://github.com/mifi/lossless-cut/issues/553#issuecomment-746023189? But for now CTRL+ALT+L/R would be easiest and probably sufficient.

Default: L/R 1 sec, ALT+L/R  2sec, CTRL+L/R 35secs, CTRL+ALT+L/R frame by frame, SHIFT+L/R jump to selected segments cuts

3) **ideally SHIFT+LR cycle through all segments cuts, not just the selected one?**

4) I recommend to add a **set back to "default" button** for the timeline sensitivity/seek speed/acceleration settings to easily revert back, as sometimes people may play around and decide they prefer to keep it as it was and may have to guess. :)

**Comment by mifi** [comment]
- [ ] Additional customisable seek intervals to be bound to separate keys - #1611
