### ISSUE TITLE
[Enhancement] Merging audio tracks together?

### ISSUE THREAD

**Issue by DatGameh** [mifi/lossless-cut#607]
I record my games via Shadowplay, and that app separates my voice and game audio into two different audio tracks.
Sometimes, I'd like to use just one audio track, and in other times, use both.

If I do decide to use both, I need to merge the tracks together, as Youtube nor Windows Movie Player cannot output both tracks at the same time.
With some help via [Reddit](https://www.reddit.com/r/ffmpeg/comments/gu5pc8/is_it_possible_to_merge_two_audio_tracks_in_a/), I was able to use ffmpeg to merge/"delete" one of the audio tracks by using the "amix-filter in a complex filtergraph":

`ffmpeg -i shadowplay_file.mkv -filter_complex "[0:a:0][0:a:1]amix=2:longest:weights=X Y[aout]" -map 0:V:0 -map "[aout]" -c:v copy -c:a aac -b:a 320k output.mkv`

Where X and Y are the volumes of each of the audio tracks (1 is the default; >1 increases the volume; 0 mutes the track).
(this code also allows the adjustment of either audio tracks, too, which is a bonus)

It is only after this that I trim the video, as most (light) video trimmers aren't able to detect/process both tracks... until I found this application!

This application is able to recognize the audio tracks, and even leave them untouched after processing the videos which is pretty rad! But, knowing that this application's internal workings is based on ffmpeg as well, I was wondering if this merging/deleting audio track feature could be implemented too!

I'm no programming expert, but I'd think this would be a relatively simple to implement. I'll be very grateful if it can be implemented!

**Comment by mifi** [comment]
This is not a lossless operation so it's out of the scope of losslesscut, but I will add it to the lossy features issue #372

PS my other tool [editly](https://github.com/mifi/editly#arbitrary-audio-tracks can do this)
