### ISSUE TITLE
[Feature Request] export segments without timecode

### ISSUE THREAD

**Issue by ltdeta** [mifi/lossless-cut#608]
When exporting, a timecodeis always appended to the export segment.
What if you could export without timecode?
Because not everyone needs the timecode.

example
[Filename]-00.00.09.694-00.50.05.516-seg1.mp4   => [Filename]-seg1.mp4
[Filename]-00.59.56.372-01.49.47.175-seg2.mp4  => [Filename]-seg2.mp4

**Comment by mifi** [comment]
See #96
