### ISSUE TITLE
Make menu undo/redo action work for segments

### ISSUE THREAD

**Issue by mifi** [mifi/lossless-cut#610]
Beginning next version, undo/redo edit segments will **only work when pressing the keyboard shortcuts**
<kbd>CTRL</kbd>/<kbd>CMD</kbd> + <kbd>Z</kbd> (not when pressing menu Edit->Undo etc).
I think that's a reasonable tradeoff because before that undo/redo didn't work for input fields which I have fixed.

1. I can't find how to listen to the undo/redo events other than using keyboard listeners
2. If I replace the whole undo menu with a custom action, then undo doesn't work for input fields anymore

Maybe need to create fake keyboard events in HTML if `document.activeElement` is not `body`

- https://stackoverflow.com/questions/47531237/what-is-electrons-webcontents-undo-doing
- https://github.com/electron/electron/issues/3365#issuecomment-219879186

**Comment by slrslr** [comment]
It is not currently apparent that the user needs to do Ctrl+Z to revert modification (in my case segment times change https://github.com/mifi/lossless-cut/issues/176 ). Actually this kind of operation is possibly the only one i need to undo and so in possibly 100% case the menu Undo operation fails to do anything. (appear non working)

If you can not make it working, i would even prefer if the Undo menu entry is there but can not be clicked and instead it says like: Use Ctrl + Z keyboard shortcut. That would remove confusion. I assume majority of users use menus.

**Comment by mifi** [comment]
thanks, that's a very good idea, I will add a warning there

**Comment by mifi** [comment]
had to revert the warning because it shows up when using keyboard shortcuts too

**Comment by mifi** [comment]
not yet released new version
