### ISSUE TITLE
[Feature request] setting for export file creation date to use current date/time instead of from source file

### ISSUE THREAD

**Issue by markusd1984** [mifi/lossless-cut#611]
It allows for easier and more clear sorting in the file explore among many files,

especially when files are renamed manually thereafter, as they will appear newer compared to the source file, also when exporting segments multiple times with slight variations (as one doesn't rely on reading timestamp in file name).

As per suggestions https://github.com/mifi/lossless-cut/issues/487#issuecomment-755223421

**Comment by markusd1984** [comment]
Another thought would be to utilize the date modified, so a new export can contain the original creation date and the date/time of when it was exported in date modified. Not sure though how Linux handles these.

But usually most people sort files either  by creation date or name. Thus an export setting 'Use current creation date/time' would probably be more useful/easier to work with in file explorer views.

(Also there is the option to keep meta data which may also contain the original creation date?!?)

@mifi Any chance we can get this in the next release?

**Comment by markusd1984** [comment]
Let's make **preserve time stamp an option feature** so LC behaves like all other common and video editing apps, which is to use creation date/time during saving. Please :)

**Comment by masvil** [comment]
Yep, it should be great.

**Comment by mifi** [comment]
have now implemented a setting for this. currently it defaults to "preserve timestamp", beucase that's what people are used to

**Comment by markusd1984** [comment]
Thanks @mifi, but shouldn't default of other apps influence the default of LC in this regard? Making it a setting many won't necessarily make the effort to change it and just accept the inconvenience distinguishing files in the explorer. Not preserving timestamp provides a better default experience for new people as well as most regular peope who probably don't care as much about a timestamp difference (original vs edited), it's more video editors with larger set of videos who care and ask for preserving timestamps.

**Comment by mifi** [comment]
I know many people want the feature of preserving the source timestamp, including myself. I think it makes a lot of sense because I sort my files by date. When I cut my files, they are basically the same as the original, just with some parts cut out, so I also expect the modify date to be the same so they fit nicely in the timeline as before.

I think you guys are the first who two asked for not preserving the timestamp, so I think it makes sense to default to "preserve". Anyways if the opinion changes, ew can change it in the future, when most people have upgraded to this version and got the setting saved.

BTW if it makes it easier we could offset the output modify date by the cut-from time. That way segments would be sorted by their original date, but also get an offset based on where from the original video they were cut. That way the cut version will come **after** the original when sorting by time. Would that make it easier to distinguish?

Just like "capture screenshot" works already (try to capture in the middle of a video, and you will see the file modified time of the PNG will be offset by the cursor's time)

**Comment by markusd1984** [comment]
Fair enough and thanks for implementing, at least we have an option now. 

Funnily I was coming from the angle of sorting files by date as well, being used to seeing newly edited files on the top rather then hidden in the list when the timestamp is preserved.

I'm just curious if in your case and others, whether the cutted videos are the final videos or will they serve as source files in other video editing projects?

The timeoffset may be no harm to have, but as you said it only helps to distinguish exported videos from the source file chronologically, 

but what I was describing is where this gets more messy when you export the videos into a folder with many files, e.g. videos folder or even downloads, as normally in common video editors all it takes is to click 'sort by dste' descending and the last exported video appears on the very top, easy least. :smile:

**Comment by mifi** [comment]
> I'm just curious if in your case and others, whether the cutted videos are the final videos or will they serve as source files in other video editing projects?

the videos I cut are usually not final. i use this tool to trim videos for storage and later use so i want to keep them like the originals.

> but what I was describing is where this gets more messy when you export the videos into a folder with many files, e.g. the Videos or Downloads folder, as normally after exporting in common video editors all it takes in file explorer is to click 'sort by date' descending and the last exported video appears on the very top/further up at least, easy, just like any other files that are created in other apps. 😄

yea i also sort by date like this. At least on Macos you can still sort by "Date added", which will still become current time (even when preserving source timestamp), I imagine Windows has something similar.

**Comment by markusd1984** [comment]
Just what I thought and I can see why for preparing source files you want to preserve the timestamp, me too 😄.

I look at LC as a powerful tool for that purpose but more so with an expectation of being seen and used as a lossless video editor for uploading and sharing final videos i.e. of recordings for meetings/trainings/streaming sessions and holiday clips. That's where the normal behaviour of not preserving would be better, in future perhaps.

Unfortunately the default windows file explorer view and sort option only contains Name, Date, Type, Size and Length. 
But even the additional Date options I found are not reflecting the difference between source file timestamp and the exports.
![image](https://user-images.githubusercontent.com/24621214/108535419-3bb02e80-72d3-11eb-8907-36f620245799.png)

**Comment by mifi** [comment]
Yea, but now since there is a setting for it, then I think it should be okay, no?

**Comment by markusd1984** [comment]
Year probably, I just forgot that LC is advertised more as for rough cutting :) in that sense it makes sense to use preserving as default.

I think it has more potential though to advertise it for **lossless video editing to create final videos**, especially  from meeting recordings, which has a huge use case in the corporate environment for MS Teams, Zoom, Meet etc. recordings are growing more then ever. 
Just not sure if hiding it as a setting only will be ideal, but for now is probably fine and if there is more people asking for it we can add it to the **Advanced export options**, which I think is a better fit, complimentary to the "**Preserve original metadata**" option, as it will be more apparent/attractive for people to decide how they want files to be saved, in other words whether they are just rough cutting or creating a final video. 😄
