### ISSUE TITLE
subtitle file dose not have a valid duration

### ISSUE THREAD

**Issue by orange-biubiubiu** [mifi/lossless-cut#614]
Hi,

I drop a video file and a subtitle file into LosslessCut ,But subtitle file dose not have a valid duration so I can't see the subtitle.(I tried .str and .ass subtitle files and They can be displayed normally in the player )

Sincerely
![1](https://user-images.githubusercontent.com/77974524/105716961-7e901800-5f5a-11eb-9ee8-8c5def522039.png)

**Comment by mifi** [comment]
What did you actually do. Can you explain a bit better? Did you:
- Select a video and a subtitle file and then drag drop them TOGETHER into losslesscut, and merge them?
- First drag-drop ONLY a video into losslesscut, then drag drop ONLY  a subtitle?
- First drag-drop ONLY a subtitle into losslesscut, then drag drop ONLY a video?

**Comment by mifi** [comment]
If you dropped them TOGETHER then it means merging in the time domain. I see that people find that a bit confusing, so maybe a feature could be to detect if the files contain different codecs, and then instead open them together. If they contain the same codecs, then assume merge (concatenate) like now.

**Comment by orange-biubiubiu** [comment]
thanks for your reply,

I'm tring to cut a Japanese video
but I don't understand Japanese so I downloaded a External subtitles
I don’t want subtitles after export, I just want subtitle shows in the overview window
Then I First drag-drop ONLY a video into losslesscut, then drag drop ONLY a subtitle(I chose "Include all tracks from the new file")

Yestoday my video format is .m4v , it shows "dose not have a valid duration" and I cannot export ，
Today I tried .mkv it can export with subtitles, but still cannot show subtitles in the overview window, 

Forgive me if that's not clear. I'm not good at English.

**Comment by mifi** [comment]
Ohh, showing subtitles over the preview is not supported yet, see #250.
If the video does not have a valid duration, try the "fix incorrect duration" from the file menu

**Comment by gtknowledgeshare** [comment]
VTT files don't seem to work when dragging in with the video, even when selecting "all tracks", pity as for enterprise MS O365 people will have access to MS Streams that provides auto generated transcripts/subtitles in VTT format. I take they would have to manually converted to a supported format, any recommendations what tool to use and format?

Ideally though would be [an option to also burn in subtitles/transcripts](https://github.com/mifi/lossless-cut/issues/250#issuecomment-884861010).

**Comment by mifi** [comment]
I don't know VTT but ffmpeg might be able to convert it. I know ffmpeg can convert other subtitle formats. Closing this issue as the original problem seems to be covered
