### ISSUE TITLE
Set Default Output Container Format

### ISSUE THREAD

**Issue by ChicagoScanningMG** [mifi/lossless-cut#615]
It would be great if we could set a default File Output Container Format.  I love that by default it auto selects the source container format, but at least for my specific use case, I'm creating MKV files in OBS, which I then trim in LosslessCut, but I remux to MP4 on output so that I can use them in Adobe Premiere, or other editing software.

I think you could just add an option to the top of the drop down that is called, "Same as Source."  Otherwise, if you select a specific output format, it will default to converting to the selected container.

Another option would be to make this a setting in the options for, "Default Output Container" and be able to select "Same as Source" or a specific format.  That way, if you change the format on the main screen's drop down, when you drop in a new file, the output format will change back to the default you selected in the settings.  If you do that, you could maybe add an option for, "Last Settings Used" which would hold the container format from whatever it was set to last.

**Comment by markusd1984** [comment]
Selecting between source and a specific format is ideal. Would expect that most people would stay in the same format so default for source makes sense.


Similar to my 2nd point in
https://github.com/mifi/lossless-cut/issues/480#issuecomment-766416693

**Comment by mifi** [comment]
This is now implemented as a lock icon next to the format:
<img width="434" alt="Screenshot 2021-04-07 at 23 27 42" src="https://user-images.githubusercontent.com/402547/113902200-d6b88580-97f9-11eb-9fef-9c3721ded6db.png">

**Comment by markusd1984** [comment]
Brilliant!

**Comment by ChicagoScanningMG** [comment]
Thank you!!!!

**Comment by mifi** [comment]
now out in the newest version

**Comment by UlmosTheWizard** [comment]
That's a cool feature. Now i can convert MTS to MP4 losslessly with just four clicks!
