### ISSUE TITLE
Unsupported file

### ISSUE THREAD

**Issue by malte1989** [mifi/lossless-cut#62]
I get the message "unsupported file" if I drag a MP4 file into the programm.

If I start lossless-cut via the fully build .exe ist has no problems with the same files. Only if I am in developing mode / npm start.

![image](https://user-images.githubusercontent.com/10382669/35199184-0a380548-fefb-11e7-9f4d-3aec874f7099.png)

**Comment by malte1989** [comment]
Filepath in the function `getFfmpegPath()` is
`C:\Users\***\Documents\GitHub\lossless-cut\**app.asar.unpacked**\ffmpeg\ffmpeg.exe`

**Comment by malte1989** [comment]
I think it can be solved with adding ffpmeg to the PATH var

**Comment by Veryapeman** [comment]
same here now.

**Comment by mifi** [comment]
@Veryapeman OS? version of LLC?
