### ISSUE TITLE
no audio

### ISSUE THREAD

**Issue by richardharbord** [mifi/lossless-cut#620]
No error

{
  "state": {
    "filePath": "/home/fen/Videos/2021-01-25 15-45-46.mp4",
    "fileFormat": "mp4",
    "externalStreamFiles": [],
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_time_base": "1/100",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 1364,
        "height": 768,
        "coded_width": 1376,
        "coded_height": 768,
        "closed_captions": 0,
        "has_b_frames": 2,
        "pix_fmt": "yuv420p",
        "level": 32,
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "50/1",
        "avg_frame_rate": "50/1",
        "time_base": "1/90000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 119619000,
        "duration": "1329.100000",
        "bit_rate": "293948",
        "bits_per_raw_sample": "8",
        "nb_frames": "66455",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "VideoHandler"
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_time_base": "1/48000",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/48000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 63795168,
        "duration": "1329.066000",
        "bit_rate": "192000",
        "max_bit_rate": "192000",
        "nb_frames": "62300",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "SoundHandler"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "/home/fen/Videos/2021-01-25 15-45-46.mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {}
    ],
    "fileFormatData": {
      "filename": "/home/fen/Videos/2021-01-25 15-45-46.mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "1329.100000",
      "size": "82703041",
      "bit_rate": "497798",
      "probe_score": 100,
      "tags": {
        "major_brand": "isom",
        "minor_version": "512",
        "compatible_brands": "isomiso2avc1mp41",
        "encoder": "Lavf58.45.100"
      }
    },
    "rotation": 360,
    "shortestFlag": false
  },
  "platform": "linux",
  "version": "3.30.0"
}

**Comment by mifi** [comment]
I believe this was the ubuntu snap permissions issue which is now fixed
