### ISSUE TITLE
Hash for release files

### ISSUE THREAD

**Issue by markusd1984** [mifi/lossless-cut#621]
Hashing release files to verify against download corruption or at a later point in time etc. https://github.com/mifi/lossless-cut/issues/394#issuecomment-767491191

**Comment by mifi** [comment]
latest-mac.yml and latest-linux.yml contain hashes. latest-win.yml seems to be missing, probably due to a bug in electron-builder https://github.com/electron-userland/electron-builder/issues/925

**Comment by mifi** [comment]
not going to spend much time on this, hopefully electron will fix the bug
