### ISSUE TITLE
Detect black-scene change

### ISSUE THREAD

**Issue by adoenz** [mifi/lossless-cut#623]
**Problem**
I've got many videos containing several black sections which I need to seek manually and cut out. 

**Solution**
It would be great if it could detect when a black-frame change happens, and when the normal picture is appearing again.
A luxurious solution would be to have the black-sections removed automatically (saving me hours...).

What would already tremendously help is that I could manually navigate to the next scene change (eg. begin black-section, end black-section); then I'd just manually mark/cut-out those sections.

**Comment by mifi** [comment]
I think black screen is a very specialized use case (maybe other videos will have a static image, a video loop, a counter or something else).
I think you can probably do this with a custom script that generates EDL cut files and then import them into losslesscut.
If it is a common use case that a lot of people need however, we can look into implementing it.

**Comment by mifi** [comment]
We could probably use http://ffmpeg.org/ffmpeg-all.html#blackdetect

**Comment by ShenMengBJ** [comment]
Recommend this auto cut function would be based on the wave graph of volume.

**Comment by mifi** [comment]
could you elaborate? what does wave graph of volume mean?

**Comment by ShenMengBJ** [comment]
> could you elaborate? what does wave graph of volume mean?

Lossless Cut could show the wave graph of video now, and if Lossless Cut will automatically tag and cut the clips of empty or short or noise based on volume, it is very interesting.

**Comment by adoenz** [comment]
I think using the ffmpeg blackdetect filter would be a geat and easy solution (from its description; haven't worked with it yet). Simply giving the user the possibility of tweaking "what black means" based on the filter's parameters (duration, level-of-black).

**Comment by mifi** [comment]
These are interesting features indeed. However I'm worried that the blackdetect command takes some time to finish for long videos. need to test more

**Comment by skinkie** [comment]
For me it takes 1 second per minute of video on DVD resolution.

**Comment by mifi** [comment]
have now implemented this and it will be avail in the next version

**Comment by mifi** [comment]
next version will allow changing parameters
<img width="508" alt="Screenshot 2022-12-28 at 23 52 10" src="https://user-images.githubusercontent.com/402547/209838400-ac9bc96a-d9fd-424e-879b-a78bec3649ae.png">
