### ISSUE TITLE
Improve thumbnails

### ISSUE THREAD

**Issue by adoenz** [mifi/lossless-cut#624]
**Is your feature request related to a problem? Please describe.**
Currently it's not possible to adjust the duration between the thumbnails.

**Describe the solution you'd like**
It would be great to be able to manually adjust the duration between thumbnails (e.g. every 3 seconds, every 10 seconds...)

**Additional context**
This gives better ability to see changes in scenes.

**Comment by Shakil-Shahadat** [comment]
Are you asking for a custom seek speed? For example, if you press left or right keyboard button, the video moves forward/backward by 1 sec. Do you wish to set a custom value? If so, it can be done from settings in the latest release.

**Comment by mifi** [comment]
i think he's asking about the thumbnails:
<img width="797" alt="Screenshot 2021-01-26 at 16 42 35" src="https://user-images.githubusercontent.com/402547/105867535-7fc25300-5ff5-11eb-8df9-c199c8c26098.png">

Maybea a better option would be " Show little thumbnail tooltip picture over the playhead while moving the mouse across the timeline (like IINA player / youtube)" See #483

**Comment by adoenz** [comment]
Yes, that would work as well.

**Comment by mifi** [comment]
btw if you zoom in it will show thumbnails closer together (in time)

**Comment by mifi** [comment]
closing in favor of #483 to keep issue count down
