### ISSUE TITLE
vedio cut by the number or time

### ISSUE THREAD

**Issue by Sailing168** [mifi/lossless-cut#626]
I hope to add a function that vedio can cut by the number or time! Thanks!

**Comment by Shakil-Shahadat** [comment]
Currently, you can do this by editing the CSV file or by inputting the time manually in the UI, hope you know that. About adding an option, let's see what the main dev thinks.

**Comment by mifi** [comment]
I don't understand what you're asking for, please elaborate

**Comment by Sailing168** [comment]
For example, I have a movie, and I want to cut the movie into several segments of the same size or several segments of the same time according to the total length of the movie

**Comment by mifi** [comment]
This is already implemented. See Edit -> Segments -> Create fixed duration segments
