### ISSUE TITLE
add a default button in seek speed/acceleration and wheel sensitivity settings

### ISSUE THREAD

**Issue by markusd1984** [mifi/lossless-cut#627]
[Add a set back to "**default**" button](https://github.com/mifi/lossless-cut/issues/604#issuecomment-767496487) in the new keyboard seek acceleration #604 / keyboard seek speed tuner #553 and trackpad/wheel sensitivity settings.

![image](https://user-images.githubusercontent.com/24621214/105972084-2bfe4b00-6083-11eb-8a1d-8ac31918d5b2.png)

P.S. I think the 3.31.1 release info is missing a reference to the timeline trackpad/wheel sensitivity setting.

**Comment by mifi** [comment]
What's the use case for needing to set it to default very often?

> P.S. I think the 3.31.1 release info is missing a reference to the timeline trackpad/wheel sensitivity setting.

this feature has been in losslesscut for a long time

**Comment by markusd1984** [comment]
@mifi my bad, thought the three were new. Default is not often needed, just makes it easy for new users to get back to defaults. I have seen this in other apps before and think it's a good approach, as the default setting is what you detirmined to be a generally a good usable setting, if somebody plays around with it and realizes it's too slow or too fast they will have to fiddle around to get somewhat back to what it was before, but not knowing it's 1.30 might end up trying several time or leave it at something that's less ideal.

Not a crucial feature request, not even that important, just thought nice to have, tbh. even a text reference in the setting might help somebody :smile:

**Comment by Shakil-Shahadat** [comment]
See [Known issues & limitations](https://github.com/mifi/lossless-cut#known-issues--limitations).

**Comment by Shakil-Shahadat** [comment]
@markusd1984 What is the actual default, 1.30 or 1.50? I have changed mine and don't know the default value now.

I can add a text reference of the default value like this 'Timeline keyboard seek speed ( Default: 1.50 ):' for the starter.

**Comment by markusd1984** [comment]
@Shakil-Shahadat you proofed my point :smile: it's 1.30 as per screenshot above.

**Comment by mifi** [comment]
Thanks for your PRs! I'm thinking whether it's better to have a reset to default button?

**Comment by Shakil-Shahadat** [comment]
That would be definitely better.
