### ISSUE TITLE
SHIFT+L/R cycle through all segments cuts

### ISSUE THREAD

**Issue by markusd1984** [mifi/lossless-cut#628]
[ideally SHIFT+L/R cycle through all segments cuts, not just the selected one](https://github.com/mifi/lossless-cut/issues/604#issuecomment-767496487), thanks.

**Comment by mifi** [comment]
I want to keep all keyboard shortcut suggestions in this issue #254, because there are so many opinions around keyboard shortcuts. please make a comment there that people can vote for. Hopefully one day we will have a binding system, then people can choose themselves.

**Comment by markusd1984** [comment]
Sorry and thanks will do. 254 ideally could include a post with a more updated list of shortcuts as not seem to be mentioned there.
