### ISSUE TITLE
CTRL+ALT jump frames

### ISSUE THREAD

**Issue by markusd1984** [mifi/lossless-cut#629]
Because [using arrow keys feels more native to use for frame by frame moves](https://github.com/mifi/lossless-cut/issues/604#issuecomment-767496487) when we have all the other modifier keys combination for jump moves with arrows and since [CTRL+ALT is not used _anymore_](https://github.com/mifi/lossless-cut/issues/254#issuecomment-589509889) 😄 thanks.

**Comment by mifi** [comment]
I want to keep all keyboard shortcut suggestions in this issue #254, because there are so many opinions around keyboard shortcuts. please make a comment there that people can vote for. Hopefully one day we will have a binding system, then people can choose themselves.

**Comment by mifi** [comment]
I want to keep all keyboard shortcut suggestions in this issue #254, because there are so many opinions around keyboard shortcuts. please make a comment there that people can vote for. Hopefully one day we will have a binding system, then people can choose themselves.

**Comment by markusd1984** [comment]
Sorry, sure will do. We could almost make a reference to that post in the "new issues" description template for easy access and consideration to check shortcuts. 😄
