### ISSUE TITLE
If your output filename has a colon in it the file will be empty

### ISSUE THREAD

**Issue by RagingFlames** [mifi/lossless-cut#631]
**To Reproduce**
1: Open any video in lossless-cut
2: Make any change and click export
3: Give it a name with a colon somewhere in the middle
4: The exported file will be named up to the colon, the rest will be cutoff, the file will be empty

**Expected behavior**
Honestly, the program should say that you can;t give a file a name with a colon in it, but it would also be fine if it just didn't put the colon in the file name, then rendered the video to that file.

**Screenshots**
I don't think this is applicable but I could take a screenshot or make a video if a dev can not reproduce this.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - CPU: 7600k
 - RAM: 32 GB
 - GPU: 970

**Additional context**
The editor did in fact take the time to render the video, but I can't find it anywhere, so I'm not sure what it made or where it put it.

**Comment by mifi** [comment]
Thanks for reporting. This feature is very new so it's probably a bug. will look into it. I'm guessing that Windows thinks the colon is the drive suffix (e.g the colon in `c:/`)
