### ISSUE TITLE
AppImage - Desktop entry is missing Icon

### ISSUE THREAD

**Issue by stoffel2** [mifi/lossless-cut#632]
**Describe the bug**
*.desktop entry created by appimaged is missing an icon.

**To Reproduce**
1. copy AppImage file from https://appimage.github.io/LosslessCut/ to .local/bin/
2. chmod +x ./*.AppImage
3. logout and login

**Expected behavior**
Application entry with icon.

**Desktop (please complete the following information):**
Debian Buster
ii  kde-plasma-desktop                            5:102 

**Additional context**
App requests following text when sending problem report
No error

{
  "state": {
    "filePath": "",
    "externalStreamFiles": [],
    "mainStreams": [],
    "copyStreamIdsByFile": {},
    "cutSegments": [
      {}
    ],
    "rotation": 360,
    "shortestFlag": false
  },
  "platform": "linux",
  "version": "3.31.1"
}

**Comment by mifi** [comment]
Possibly related? #4617

**Comment by shmu26** [comment]
I have this same issue on Kubuntu 23.04

**Comment by mifi** [comment]
electron and electron builder now latest version. please test. i can reopen if it's still an issue on the newest version of losslesscut
