### ISSUE TITLE
Software isn't cutting at specified location

### ISSUE THREAD

**Issue by EladKarni** [mifi/lossless-cut#633]
**Describe the bug**
I'm trying to cut a video, but it won't 

**To Reproduce**
1. Open a video file
2. Cut It into a short segment
3. Cut is ignored

**Expected behavior**
I'd like the cut to happen where it is specified.

**Screenshots**
Video of Issue: https://gfycat.com/DimwittedCoarseBarb

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Shakil-Shahadat** [comment]
See [Known issues & limitations](https://github.com/mifi/lossless-cut#known-issues--limitations).

**Comment by EladKarni** [comment]
Crap, I feel stupid now... I should have checked that first. Apologies for wasting your time. 

What alternatives do I have for more precise cutting?

**Comment by Shakil-Shahadat** [comment]
It's okay, we all have been there.

You can use [FFmpeg](https://ffmpeg.org/ffmpeg.html), but it'll be a lossy process. Also check #372.

**Comment by mifi** [comment]
You can try to toggle to Normal cut and see if that helps. If not then yea the cut is probably too small so ffmpeg cannot do it.
There is a feature request for maybe warning the user in this case #516
