### ISSUE TITLE
File details or type information

### ISSUE THREAD

**Issue by roboknight** [mifi/lossless-cut#639]
**Is your feature request related to a problem? Please describe.**
This is a feature request relating to not supporting audio for certain formats.  I have several files that were generated by the same
device (the Google Pixel if the filename is to be believed PXLxxxxxxxxxxx).  SOME of the files seem to give Lossless cut no issues.  In fact, I've used it to split several video files quite effectively.  Mifi, to your credit, you've nailed this particular problem on the head... lack of easy tools to cut video... so thanks for creating this one.  HOWEVER, I *recently* attempted to split a video from the SAME device only to be presented with the dreaded "Sorry, this video isn't natively supported, so we can't render audio, but your cuts will still have audio" message.  Perfectly understandable (except that I actually NEED the audio to make some of the splits, but we'll get to that).  So, the video is from the same device, it is in the MP4 container format, AND I can't tell what the difference is between the videos that work, and the videos that don't.  It is of course because one set of videos *IS* supported and one set ISN'T supported.  The question I'm trying to answer is "What is the video format that ISN'T" supported so I can tell the person that whatever mode generated those videos, please stop using it.  But, at this point, I don't have any simple way to determine what video format I'm dealing with.  Hence, the feature request for some kind of video clip information that would help determine things like frame rates and so forth (as well as video type).

This of course leads to a second request to support the unknown format, but I can't make that request until I know what I'm dealing with (Told you I'd get to needing the audio to make the cuts).  Because I'd like to be able to carefully cut the audio at appropriate points and sometimes its based on extra audio I don't want or need.

**Describe the solution you'd like**
**Describe alternatives you've considered**
So, the real request is can you provide more detailed clip information somewhere?  I was looking for a simple "clip info" in ffmpeg or something like that.  I'm afraid I'm going to have to resort to vlc or something like this.

**Comment by roboknight** [comment]
Okay, maybe this is more of a bug... The problem might be that when the file is passed on the command line to the AppImage, it seems to get screwed up somehow and think the file is unsupported (when it is actually supported).  Just using the normal GUI interface it appears to work fine.  Or maybe there is no way to pass in a file from the command line?  At any rate, it would still be nice to have more video information.

**Comment by mifi** [comment]
Hi.
Did anything change (software upgrade on your camera or upgraded losslesscut) around the time when you started getting the "unsupported codec" message?
If not then I have no idea why it just stopped working like that.

If you go to the Tracks panel and then press the Info button next to the file name, then you will see information about the file. and underneath you can see info about each of the tracks, so you can use that  to compare the working and non-working files.

**Comment by roboknight** [comment]
No.  I checked with vlc and the video types were the same.  The only difference in how things worked was one way I attempted to open the file by running the appimage from the command line WITH the file (hoping it would bring that file in to be cut).  The other way I just opened the appimage and used the GUI to navigate to the file.  The file was an MP4, avc1 (H264 encoded).  I'll check the tracks.  I didn't see anything there before.  I did check with VLC and they both had all the same things (AAC, H264, avc1, MP4 container)... It appears it was only when I passed the video in from the command line it must have thought it was something else.  So maybe user error (I don't know if you allow videos specified on the command line?).

**Comment by mifi** [comment]
that shouldn't make a difference. Maybe your losslesscut got auto updated. if you can share a file that would be helpful

**Comment by roboknight** [comment]
Let me check, I might be able to do something.  Most are quite large.

**Comment by mifi** [comment]
If you can cut a small piece out of one, and if that piece then gives the same problem when opened in losslesscut

**Comment by roboknight** [comment]
That's what I was testing... it works the same.  Let me attach it here.

https://user-images.githubusercontent.com/200695/106805377-9dff0300-6634-11eb-8630-372616e25488.mp4

**Comment by roboknight** [comment]
Ok, not what I had in mind... I don't know if there is a way to "undisplay" that.

**Comment by mifi** [comment]
Thanks. just edit your comment and remove it, i already downloaded

**Comment by roboknight** [comment]
Thanks.  I'm not sure what the difference is.  But I've been using the last AppImage of lossless cut I had which was 3.30.x or something like that (maybe even 3.31?)... so maybe it is old already?

**Comment by mifi** [comment]
That's very odd. It works for me (on mac). So it must be linux specific. Maybe you can check developer tools for any logs/errors when opening the file

**Comment by roboknight** [comment]
How do I check the logs?  Just standard dmesg, or is there a way to get more verbose command line output?

**Comment by mifi** [comment]
tools -> developer tools

**Comment by roboknight** [comment]
Ahhh... Maybe I found something:   
![Screenshot from 2021-02-03 15-38-30](https://user-images.githubusercontent.com/200695/106806423-f2ef4900-6635-11eb-800a-da3434f67d9d.png)

**Comment by roboknight** [comment]
I wish there was a way to export that log as text.  At any rate, when I open it from the command line, I get that.

**Comment by mifi** [comment]
This is the error given by the chromium html5 video player (used by losslesscut to playback video) when it doesn't support the file. I have no idea why it just stopped working for you like that though. Only thing I can suggest is to try to downgrade losslesscut version and see if it helps

**Comment by roboknight** [comment]
I think it might have to do with the "Failed to load resource" at the start.  Its looking in the root directory for the file I provided on the command line.  Not sure why its looking there.  But it won't find my file there.  So when it tries to load it, it fails.  I'll see if providing some kind of path helps.

**Comment by mifi** [comment]
did you drag-drop the file into losslesscut (or File->Open)?

**Comment by roboknight** [comment]
That was from the command line.. When I drag it or File->Open, I think it gets the correct path and I believe THAT is why one way works and the other doesn't.

**Comment by mifi** [comment]
so it works with drag drop / file->open? then this is only an issue with opening from the command line?

**Comment by roboknight** [comment]
Yes.  From the command line, if I provide the FULL PATH, then it works.  If I do anything else, it fails.

**Comment by roboknight** [comment]
I don't know if there's a way you could even fix that bug unless you have Linux to test with.  Probably not worth fixing.  Maybe just a mention somewhere under a "Hey Linux users beware" or something.

**Comment by mifi** [comment]
> Yes. From the command line, if I provide the FULL PATH, then it works. If I do anything else, it fails.

so it fails also with file->open and drag drop?

**Comment by mifi** [comment]
I tried to open a relative path from command line and it fails for me too, so it's definitely a bug there.

**Comment by roboknight** [comment]
No, those all work fine.  That's why I said it might not be worth fixing.  I normally use the GUI unless I happen to be working in the video directory with the file.

**Comment by mifi** [comment]
Ok. Well I will fix it because it causes confusion and it's currently a very strange way to fail
