### ISSUE TITLE
Opening via command line with file path fails because path has a space in it.

### ISSUE THREAD

**Issue by matthewn4444** [mifi/lossless-cut#641]
**Describe the bug**
I am trying to use this via command line to open (with regedit and context menu) on windows. For this I need to access the application with the video path such as 

`C:\path\to\app\Lossless-cut.exe C:\path\to\video\file.mp4` 

If the path to the video has a space like

`C:\path\to\video with a space in it\video.mp4`

If will fail because of some substring probably `lastIndexOf` for a space. Here is the log in the developer tools for the path

`main.eba51c37.chunk.js:1 Error: ENOENT: no such file or directory, access 'C:\Users\matth\OneDrive\Desktop\folder with spaces\spaces'`

with the path to the video `'C:\Users\matth\OneDrive\Desktop\folder with spaces\video.mp4'`

If you don't have time, I can try to figure out how to compile or bundle this app and just create a merge request when i have time.

**To Reproduce**
1. Open a terminal, cmd or anything with command line access
2. Put a folder with a video in it, make the folder has a space in the name
3. In the cmd/terminal type `C:\path\to\app\Lossless-cut.exe C:\path\to\video with space\file.mp4` 
4. Fails to open saying it is unsupported (but if you drag the video it in works

**Expected behavior**
Supposed to open with video loaded

**Screenshots**
![image](https://user-images.githubusercontent.com/1667384/106955636-5935a380-66ea-11eb-82cb-c9c26f751fd5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (20H2)

Also thanks for making this program, its great

**Comment by Shakil-Shahadat** [comment]
You need to use double quotation mark around any path that has space in it in the command line like this,
`C:\path\to\app\Lossless-cut.exe "C:\path\to\video with space\file.mp4"`

**Comment by matthewn4444** [comment]
Oh ya, i guess i forgot to add escape quotes in my script. Thanks.
