### ISSUE TITLE
3.30.0 ubuntu snap, no audio in preview, export is fine.

### ISSUE THREAD

**Issue by dshimer** [mifi/lossless-cut#644]
This may be fixed when the snap refreshes to the latest version, just mentioning in case.

Tried MOV and MP4 files.  Open the file, hit play to find cutpoints. Display is fine but there is no audio output and I can't find any settings or buttons that may indicate what I could do.  I hit the speaker icon in the lower right corner of the video and it toggles to mute then toggle mute off with no effect.  The export is fine.

 - OS: Ubuntu 20.10

**Comment by mifi** [comment]
Hi. Did it work prior to 3.30.0? If so. Do you know which version worked?

**Comment by dshimer** [comment]
I use it every Saturday morning.  All I know for sure is that the audio output seemed to quit working either 1/23/21 or 1/30/21.  I don't think I changed anything, I just open it, open a file, clip the ends, export and close.  Everything else on my system seems to work fine, and the exported file is normal.  Just no sound when previewing the video.  I'm glad to try something if you need.

**Comment by mifi** [comment]
Ok. Did you by any chance update to ubuntu 20 recently?

**Comment by dshimer** [comment]
> Ok. Did you by any chance update to ubuntu 20 recently?

I apt dist-upgrade on a fairly regular basis (once or twice a week) and I don't really track what snaps are doing in the background.

**Comment by dshimer** [comment]
I just noticed the wording of your question. I run interim releases so would have gone to 20.10 last November.

**Comment by mifi** [comment]
Ok, I have one other user reporting issues with audio in preview on Ubuntu after 3.30.0 so there is definitely something there. Meanwhile you could downgrade losslesscut to the prev version.

**Comment by mifi** [comment]
I just tested now on ubuntu 10.04 fresh install, and audio works with 3.30.0. However only when downloaded from github.
From snap I confirm no audio.

**Comment by mifi** [comment]
I'm pretty sure this is because of #410. I added removable media support `removable-media`

Turns out that documentation at https://www.electron.build/configuration/snap is **wrong**, it states:

`plugs Array<String | SnapOptions.PlugDescriptor> - The list of plugs. Defaults to ["desktop", "desktop-legacy", "home", "x11", "unity7", "browser-support", "network", "gsettings", "pulseaudio", "opengl"].`

However looking at their code:

https://github.com/electron-userland/electron-builder/blob/9fd950bc046ca1748950f63894993947da8185c5/packages/app-builder-lib/src/targets/snap.ts#L15

```js
const defaultPlugs = ["desktop", "desktop-legacy", "home", "x11", "wayland", "unity7", "browser-support", "network", "gsettings", "audio-playback", "pulseaudio", "opengl"]
```

`audio-playback` is missing in their doc. Will now fix this.

https://snapcraft.io/docs/audio-playback-interface

**Comment by mifi** [comment]
Will release a new version which hopefully fixes this

**Comment by dshimer** [comment]
Fantastic

**Comment by richardharbord** [comment]
Is there something I could do now - a path or something I could apply to my installation?

**Comment by dshimer** [comment]
Tested new version last night. Works great. Thanks

**Comment by Mennaruuk** [comment]
Hi! Are there plans to update the Snap in Ubuntu Software? Thank you!

**Comment by mifi** [comment]
Have now updated stable to 3.33.1. note that you can always try out new version by using "edge"

**Comment by Mennaruuk** [comment]
I didn’t know that. Thank you so much, really appreciate it!!
