### ISSUE TITLE
Setting to always discard audio

### ISSUE THREAD

**Issue by KrisGielen** [mifi/lossless-cut#647]
**Is your feature request related to a problem? Please describe.**
Your tool is awesome. I really love it. There's one enhancement that would make me even happier: an option to always discard audio.

**Describe the solution you'd like**
I make a lot of videos outside and in windy conditions. I hardly ever need or even want the audio, so I always have to remember to click the audio button to set it to "discard audio" before exporting.

**Describe alternatives you've considered**
An extra option in Settings specific for audio: Keep / Discard

**Additional context**
An alternative could be an option in Settings about tracks: Keep all tracks / Export each track as individual files
I could then afterwards simply delete all audiofiles.

**Comment by mifi** [comment]
thanks for your suggestion! Already tracking this feature request in #371
