### ISSUE TITLE
[request/bug] use system's ffmpeg & ffprobe

### ISSUE THREAD

**Issue by azev** [mifi/lossless-cut#648]
Ability to use system's `ffmpeg` & `ffprobe` to avoid redundancy (128Mb!).

Nowadays most systems already have `ffmpeg` & `ffprobe` installed and set to `PATH` env var.
But if I delete `LossLessCut\resources\node_modules\ffmpeg-ffprobe-static\` it will show the message `Unsupported file` **even though ffmpeg & ffprobe are installed on my system**

Please allow ffmpeg packto be dowloaded separatedly.

**Comment by mifi** [comment]
Dup #400
