### ISSUE TITLE
jerky/glitchy playback in editor (mac)

### ISSUE THREAD

**Issue by jefflivid55** [mifi/lossless-cut#65]
When I open an MP4 file and play it back in the editor, it is jerky/glitchy at times.
However, the video plays fine in quicktime.

There are no errors in the console.
What could be causing this?

File is H264, AAC, Timecode, 3840x2160

Console output
`Version 1.9.0
/Applications/LosslessCut.app/Contents/Resources/app.asar/renderer.js:243 Load /Volumes/External/Video Editing/GoPro/GH010102.MP4
/Applications/LosslessCut.app/Contents/Resources/app.asar/ffmpeg.js:114 getFormat /Volumes/External/Video Editing/GoPro/20180117/GH010102.MP4
/Applications/LosslessCut.app/Contents/Resources/app.asar/ffmpeg.js:122 formats mov,mp4,m4a,3gp,3g2,mj2
/Applications/LosslessCut.app/Contents/Resources/app.asar/ffmpeg.js:128 fileType detected format {"ext":"mov","mime":"video/quicktime"}`

**Comment by mifi** [comment]
Video playback is done by chromium. Maybe chromium is using software decoding and since it's a high resolution maxing out the cpu? do you get high cpu usage?

**Comment by davidmessem** [comment]
@mifi you might be right. It isn't maxing out my CPU, but Activity Monitor shows VTDecoderXPCService as using around 150% CPU (I have a 4 core machine)

**Comment by jefflivid55** [comment]
@mifi you might be right. It isn't maxing out my CPU, but Activity Monitor does show VTDecoderXPCService as using around 160% CPU (I have a 4 core machine)

**Comment by mifi** [comment]
VTDecoderXPCService is a video player component in Mac OS. So your computer is probably struggling with this 4K video. Do you have an old mac?
