### ISSUE TITLE
J-K-L shortcuts for clip navigation

### ISSUE THREAD

**Issue by aberkl** [mifi/lossless-cut#652]
LosslessCut uses a very uncommon (if not unique) J-K-L implementation, see #4.

Industry standard, well established and much more usefull is
- J Key: Shuttle left (plays backward)
- K Key: Shuttle stop (pause playback)
- L Key: Shuttle right (plays forward)

Multiple key-presses (like currently implemented for "L") increase the speed.

Some web references for J-K-L:
- [No Film School for Adobe Premiere Pro](https://nofilmschool.com/2018/10/how-use-j-k-and-l-keys-premiere-pro-speed-your-workflow) 
- [Avid Media Composer](http://resources.avid.com/SupportFiles/attach/70024_MediaComposer_FilmComposer_Keyboard.pdf)
- [Quicktime Player](https://sites.duke.edu/ddmc/2013/10/31/quicktime-j-k-l-keyboard-shortcuts/)

**Comment by markusd1984** [comment]
Would make sense to adjust to a common standard for similarity of video editors switching to LC and use three new keys in a row for the speed playback settings (which may be used less then backward/pause/forward playback).

Once we have a full key mapping feature this will allow to suit anyone's personal taste. :smile:

**Comment by mifi** [comment]
I believe that the only thing losslesscut does differently from other editors is that losslesscut slows down instead of playing backwards with "J", am I right?

I would love to make "J" work as standard editors (reverse playback), however it's not trivial to implement #601

**Comment by mifi** [comment]
Closing this because of no feedback, and reverse playback is tracked in the other issue.
