### ISSUE TITLE
QUALIFIER KEY + J-K-L shortcuts for clip editing

### ISSUE THREAD

**Issue by aberkl** [mifi/lossless-cut#653]
Some editing software (not as much as with the J-K-L navigation, see #652) use

- CTRL + J Key: Delete everything from **before** current position, this is currently SHORTCUT I
- CTRL + K Key: Cut (Split) at current position, this is currently SHORTCUT B
- CTRL + L Key: Delete everything from **after** current position, this is currently SHORTCUT O

The combination of both navigation and edit using the same keys (only differing by a qualifier key) result in faster navigation/editing - once your brain has connected the wires ;-)

Note: Please do not remove SHORTCUT I and O, these are also pretty common and you should not break the UX of I/O'ers.

**Comment by mifi** [comment]
I moved your suggestion to the keyboard shortcuts issue. I dont want so many shortcut issues around so closing this.
