### ISSUE TITLE
User shortcuts customization

### ISSUE THREAD

**Issue by aberkl** [mifi/lossless-cut#654]
With respect to #652 and #653: I believe LosslessCut cut benefit very much from "User shortcuts customization".

Ideally this would have an entry in "Settings" but a (text, json, ...) config file would be sufficient as well.

Compare to screenshots from DJV View and kdenlive.

![Screenshot from 2021-02-14 17-02-31](https://user-images.githubusercontent.com/9915206/107881919-d630fc00-6ee6-11eb-9429-da3613c6100b.png)
![Screenshot from 2021-02-14 17-04-50](https://user-images.githubusercontent.com/9915206/107881924-db8e4680-6ee6-11eb-9252-1518b465a709.png)

**Comment by markusd1984** [comment]
I think that's one of the longer nice to have features being considered, certainly offers a lot of flexibility for the fastest personal use of LC who like using shortcuts.

A mapping feature would make this the most user friendly, even if that writes it to a local settings file if they feature also gets implemented.

**Comment by mifi** [comment]
thanks for your suggestion. I referenced this issue in the main keyboard shortcuts issue. Need to close some issues (too many)
