### ISSUE TITLE
Segments list improvement: Shortcut for "Label segment"

### ISSUE THREAD

**Issue by aberkl** [mifi/lossless-cut#655]
The Segments list should allow to "Label a segment" by using a shortcut. I could very well image it to be F2 (widely used for "Rename") by default. Plus user definable, see #654.

Using Labels is indeed a very good idea since your brain will much easier "organize" an edit when reading something like "Helicopters come in ...", "Frodo sighs" or "End credits" rather than looking at purely "technical" information like IN and OUT points and DURATION.

![Screenshot from 2021-02-14 17-30-34](https://user-images.githubusercontent.com/9915206/107882570-5c9b0d00-6eea-11eb-9aaa-d448b74aa468.png)

I would also suggest to give the Label a bold typeface or (even more obvious) a different background color which makes it easier to spot.

Personally I think the milliseconds and frames information are of purely academic interest and should be removed.

**Comment by mifi** [comment]
What about Enter? It's often used for changing text

> Personally I think the milliseconds and frames information are of purely academic interest and should be removed.

Some people (including myself) use it sometimes

**Comment by mifi** [comment]
Have implemented it as Enter key for now

**Comment by aberkl** [comment]
Thanks for the fast fix. After trying the ENTER key I find this probably even better than my F2-approach.
