### ISSUE TITLE
Export Segments Merged Into One File

### ISSUE THREAD

**Issue by Libror** [mifi/lossless-cut#663]
I would love to have an option, that if turned on it exports a video file, that contains all segments merged into one file.
Maybe add like an option or a button next to the original export button that is only visible if you have multiple segments.

**Comment by markusd1984** [comment]
That is literallay the main way LC edits videos, exporting a merged video file based on segment selections. It even allows to export only segments or both (to check the exact cut points). Just have a look at the export options to switch between split/merge/split+merge.

**Comment by Libror** [comment]
Didn't know that was possible. Thanks.

**Comment by markusd1984** [comment]
No worries, this can easily missed among the many options. Previously this setting was expose in the app (right top corner) for quick switching between split/merge modes, which now also has the merge+split option which is useful to check the beginning/endings of the individual segments as cut points are not always exact, this you can go back make changes of necessary and when all segments cut in the export are as you desired them to be you can delete them and rest assured that the merged video is the way you intend the cut points to be.

**Comment by mifi** [comment]
i brought the button back!
