### ISSUE TITLE
Setting Output File Name - Cursor Jumps to end of line

### ISSUE THREAD

**Issue by slumbergod** [mifi/lossless-cut#670]
Using 3.32.0 as AppImage under Manjaro
Just a minor issue...

After setting keyframes for the start and end points of the cut, I click EXPORT to bring up the export dialog.
I edit the output file name and while I am typing the cursor suddenly jumps to the end of the line, after ${EXT}.
I'm not hitting the END key accidentally and I can't think of why my typing suddenly stops where I am supposed to be and jumps t the end. Perhaps others have encountered this and have a solution or explanation?

**Comment by mifi** [comment]
I'm not able to reproduce this on Mac. Could you record a video, or specify exactly how to reproduce it?
