### ISSUE TITLE
Mac OS Mojave Java Error : RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by iPhoneAddict** [mifi/lossless-cut#671]
**Context**
- iMac 27'' Late 2013 under Mac OS Mojave 10.14.6 (support 32 bit applications)
- Java build 1.8.0_281-b09 (latest)
- LossLessCut Version 3.32.0 (latest)

**Error**
When right clicking on a video "mp4" (verified with different files of different sizes) in the Finder and selecting "Open with LossLessCut", there is an error showing up in a windows saying :

> LossLessCut
> Unhandled Error
> RangeError: Maximum call stack size exceeded
>     at openFile (/Applications/LosslessCut.app/Contents/Resources/app.asar/build/electron.js:28:28)
>     at openFile (/Applications/LosslessCut.app/Contents/Resources/app.asar/build/electron.js:28:28)
>     at openFile (/Applications/LosslessCut.app/Contents/Resources/app.asar/build/electron.js:28:28)
>     at openFile (/Applications/LosslessCut.app/Contents/Resources/app.asar/build/electron.js:28:28)
>     at openFile (/Applications/LosslessCut.app/Contents/Resources/app.asar/build/electron.js:28:28)
>     at openFile (/Applications/LosslessCut.app/Contents/Resources/app.asar/build/electron.js:28:28)
>     at openFile (/Applications/LosslessCut.app/Contents/Resources/app.asar/build/electron.js:28:28)
>     at openFile (/Applications/LosslessCut.app/Contents/Resources/app.asar/build/electron.js:28:28)
>     at openFile (/Applications/LosslessCut.app/Contents/Resources/app.asar/build/electron.js:28:28)
>     at openFile (/Applications/LosslessCut.app/Contents/Resources/app.asar/build/electron.js:28:28)

The application starts but does not open the file. It's possible then to open the file manually.
Drag & Drop of the file in the App window works correctly.
If the application is already open, the "Open with LossLessCut" still generate the error window.

**Comment by mifi** [comment]
dup #656
already fixed. will b released in next ver
