### ISSUE TITLE
dragging handles for segments

### ISSUE THREAD

**Issue by markusd1984** [mifi/lossless-cut#672]
Because it's common in video editors and sometimes quicker as well as easier to make changes then switching between moving/selecting timeline and going to the in/out handle icons for people who don't really make use of short cuts, i.e. most people.

@mifi you mentioned it may be [problematic with the existing scrubbing timeline](https://github.com/mifi/lossless-cut/issues/421#issuecomment-743165799), but couldn't this be separated code wise and visually by only using/displaying handle bars when hovering exactly over segment cut points?

You probably considered this or even tried this out...
Since most editors have the timeline separately above from the segment layer don't have this complexity of course.

Alternatively perhaps we could enable a thin scrubbing timeline above or maybe better have **handle bars temporarily displayed above during hover** to be less intrusive (i.e. 5-10secs while hovering over a individual segment, or display permanently for all segments or selected segments).

**Comment by mifi** [comment]
I believe dup of #517 ?

**Comment by markusd1984** [comment]
Ah yes sorry missed that one in my quick search.
