### ISSUE TITLE
[Feature Request] MKV attachment support to save frame as cover.jpg

### ISSUE THREAD

**Issue by cyzs233** [mifi/lossless-cut#673]
I noticed after export segment, lossless-cut deleted the attachment "cover.jpg" that I put in the original file. But having a custom thumbnail helps while browsing a specific video within a folder. And if you're trying to put a cover.jpg after exportation, you'll need to refresh the thumbnail cache in order to view your changes, which is not a user-friendly task.
 Suggestion:

- [x] option to choose a file from file explorer as cover.jpg/cover.png
- [ ] option to select a frame from the imported video as cover.jpg/cover.png
- [x] option to keep/discard original cover art within the imported video.

**Comment by mifi** [comment]
Closing due to lack of response
