### ISSUE TITLE
Timeline not jumping to play head anymore on playback when zoomed in

### ISSUE THREAD

**Issue by Wiethoofd** [mifi/lossless-cut#676]
In 3.31.1 when you zoom in to a timeline and start playing the file the timeline occasionally jumps/moves and sets the play head on the left side again. In 3.32.0 there was [this commit](https://github.com/mifi/lossless-cut/commit/79f0d4c61b1b9f800d2b0df23e03dc95c5642779) to make the zoomed timeline more smooth, but now the "recentering" of the timeline to the play head only happens when you pause the playback.

Steps to reproduce:
1. Open any video file
2. Zoom in on the timeline
3. Start playing the video and see the play head move off the right side of the screen
- 3.31.1 - Timeline jumps to move the play head back to the left side of the screen
- 3.32.0 and onwards - Timeline does not move, play head keeps moving further off screen (until paused)
(4. when scrolling to move the timeline both versions jump timeline to move the play head on screen again, but also skips a bit where that obviously doesn't happen during normal playback)

I personally preferred the pre 3.32 behaviour where it jumped the timeline, because it would allow me to click on it to then set my in/out points, without having to pause to recenter it. Somehow a user preference to have the old behaviour of the automatic timeline jumping to keep the play head during playback on screen would be appreciated.

**Comment by mifi** [comment]
thanks for reporting. i have reverted behaviour
