### ISSUE TITLE
Specify preview file 

### ISSUE THREAD

**Issue by ericvaandering** [mifi/lossless-cut#680]
The GoPro Hero8 outputs HEVC files (I think) which my Mac and Lossless cut are not happy with. Converting the 4K files to something the system is happy with takes too long to be really useful. But the GoPro also produces a LRV (low res video) preview file which is mp4 and probably HD resolution. If I could use lossless cut on the preview file but apply the cuts to the full 4K file my problem would be solved.

So, is there a way I can specify a pre-generated preview to use instead of generating one? A way to rename my file to trick lossless cut into thinking it did it already?

**Comment by mifi** [comment]
Ohh. Actually you could try to rename the LRV to `ORIGINAL_FILE_NAME-html5ified-slowest.mp4` and see if that works

**Comment by mifi** [comment]
Try newest version. You can rename your lrv to `ORIGINAL_FILE_NAME-html5ified-XX.XYZ` where XX can be anything and XYZ any extension and it should be picked up.
