### ISSUE TITLE
output videos‘ title cannot display Chinese words rightly instead of"_____"

### ISSUE THREAD

**Issue by MRF3247** [mifi/lossless-cut#685]
First ,thank u for ur coding!It helps me a lot in my works!
But here is the question ,this issue hadn't being solved in all versions I've used.

![image](https://user-images.githubusercontent.com/22931900/109146323-a44d4e80-779e-11eb-8d8d-5e56772657c9.png)
![image](https://user-images.githubusercontent.com/22931900/109146659-145bd480-779f-11eb-8012-0d72968e673b.png)
When I write some Chinese Text in labels,it do display rightly in the panel(like the pic above).

![image](https://user-images.githubusercontent.com/22931900/109147872-7d901780-77a0-11eb-90ea-0fd4d3e32b34.png)

![image](https://user-images.githubusercontent.com/22931900/109146946-6b61a980-779f-11eb-85fd-2f88097c7516.png)
but when I try to out put my clips,it cannot display in Out put window and just shows like "_____"

![image](https://user-images.githubusercontent.com/22931900/109147291-ce534080-779f-11eb-81d1-158637bf4620.png)
And the timestamps files ,opened with EXCEL cannot display Chinese rightly .

![image](https://user-images.githubusercontent.com/22931900/109147756-5afdfe80-77a0-11eb-915c-105fe9713b28.png)
I've tried to find where is wrong with it , when I try to change the file's Character Encoding Type from UTF-8 to UTF-8 with BOM,it worked.

This problem happens on all my Windows 10 PCs(Simple Chinese Version) and all kinds of video formats ,please help , thanks!
p.s. Traditional Chinese system also has this problem.

--------------------
No error

{
  "state": {
    "filePath": "Z:\\OWL比赛录播&复盘素材\\2020\\WEEK2\\DAY2-费城主场 0217\\2-佛罗里达狂欢vs费城融合 0@3\\Full Match PHI @ FLA 17-02-2020.mp4",
    "fileFormat": "mp4",
    "externalStreamFiles": [],
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_time_base": "1001/120000",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1088,
        "closed_captions": 0,
        "has_b_frames": 2,
        "pix_fmt": "yuv420p",
        "level": 42,
        "chroma_location": "left",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "60000/1001",
        "avg_frame_rate": "60000/1001",
        "time_base": "1/60000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 380100721,
        "duration": "6335.012017",
        "bit_rate": "10000662",
        "bits_per_raw_sample": "8",
        "nb_frames": "379721",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "VideoHandler"
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_time_base": "1/48000",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/48000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 304080896,
        "duration": "6335.018667",
        "bit_rate": "160470",
        "max_bit_rate": "160470",
        "nb_frames": "296954",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "SoundHandler"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "Z:\\OWL比赛录播&复盘素材\\2020\\WEEK2\\DAY2-费城主场 0217\\2-佛罗里达狂欢vs费城融合 0@3\\Full Match PHI @ FLA 17-02-2020.mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {
        "start": 1899.858379,
        "end": 1905.170481
      }
    ],
    "fileFormatData": {
      "filename": "Z:\\OWL比赛录播&复盘素材\\2020\\WEEK2\\DAY2-费城主场 0217\\2-佛罗里达狂欢vs费城融合 0@3\\Full Match PHI @ FLA 17-02-2020.mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "6335.019000",
      "size": "8055815787",
      "bit_rate": "10173059",
      "probe_score": 100,
      "tags": {
        "major_brand": "isom",
        "minor_version": "512",
        "compatible_brands": "isomiso2avc1mp41",
        "encoder": "Lavf55.19.104"
      }
    },
    "rotation": 360,
    "shortestFlag": false
  },
  "platform": "win32",
  "version": "3.33.1"
}

**Comment by mifi** [comment]
This is due to not all file systems supporting all characters. See issue #427

**Comment by mifi** [comment]
@HADB try to disable "sanitize", see https://github.com/mifi/lossless-cut/issues/427#issuecomment-903943653

**Comment by HADB** [comment]
> @HADB try to disable "sanitize", see [#427 (comment)](https://github.com/mifi/lossless-cut/issues/427#issuecomment-903943653)

It works, thanks!
