### ISSUE TITLE
win.appx version is saying app is not signed with trusted certificate

### ISSUE THREAD

**Issue by iiTsMus** [mifi/lossless-cut#688]
I am trying to get the latest version. I downloaded the win.appx version but when I try to install it I get an error
![image](https://user-images.githubusercontent.com/79716709/109335591-28b0d780-785a-11eb-93ff-d1e3ff1e8587.png)

**Comment by mifi** [comment]
Unfortunately the appx file is not for installation, I only use it for Windows Store. See #337
