### ISSUE TITLE
Fails to retain subtitles beyond the first track

### ISSUE THREAD

**Issue by jamesdsalehi** [mifi/lossless-cut#69]
When I tested lossless-cut with an .m4v with one subtitle track, it worked well.

But with a different .m4v which has two subtitle tracks, lossless-cut fails to save the second subtitle track in the trimmed version (the first subtitle track is saved OK).

**Comment by CaptaPraelium** [comment]
Possibly related: https://github.com/mifi/lossless-cut/issues/70
I'll try to treat subtitle tracks when I take a shot at fixing audio tracks.

**Comment by mifi** [comment]
This should be fixed when using the new "include all streams"-option. please reopen if it is not
