### ISSUE TITLE
Is that possible to do precise cut? I accept re-encoding

### ISSUE THREAD

**Issue by FurkanGozukara** [mifi/lossless-cut#692]
I am testing and no matter what I do, not available to cut as I wanted

As far as I read, we have to re-encode for precise cutting

I accept that but I have failed to find it in the application

Is it possible?

**Comment by Shakil-Shahadat** [comment]
Not possible in the current version. See #126.

**Comment by mifi** [comment]
Also #372

Just out of curiosity:
Why do people want lossy slow accurate cutting in losslesscut? What's the benefit of using losslesscut instead of something like iMovie, shotcut, openshot etc?

**Comment by ilaw138** [comment]
Hi,

What I’d really like, but have no idea how to achieve, is what was possible with QuickTime 7 Player Pro. This allowed frame accurate editing, but then passed the video and audio streams through to the output file without re-encoding or changing in any visible way. I guess it must play with the key frames and I-nodes and whatever else, but the output file was simply an edited version of the input file.

So I’m not looking for a lossy re-encode but a form of lossless transformation.

As I say Quicktime Player 7 Pro could achieve this, though how I have no real idea...

**Comment by FurkanGozukara** [comment]
@mifi it is open source based and the interface is exactly as I wanted. I have failed to find an open source application that have such feature and interface. point me if there is any

**Comment by mifi** [comment]
It seems like lossy accurate cutting is something alot of people want, so it may be implemented next

**Comment by ulifuqiang** [comment]
I need it too.

**Comment by phu54321** [comment]
When I'm cutting 1 hour segment on 6 hour segment. I want an exact cut with re-encoding at the starting 5~6 seconds and ending 3~4 seconds, and lossless copy&paste for ther remaining 59minutes 50+ seconds.
