### ISSUE TITLE
Keep Created Date - HDR Converted 

### ISSUE THREAD

**Issue by anciltech** [mifi/lossless-cut#693]
Appears that the trimmed file pulled the creation date from the modified date field. 

Version: 3.33.1

Repeat by: Open HDR MOV file, convert to supported format: Fastest (no audio) (step optional), select 1 (maybe multiple) sections, export to MOV 

Example Video Files: https://www.icloud.com/iclouddrive/0iVawXUp94A2k2Wd-2uwg6xQg#LosslessCutExample

<img width="550" alt="Screenshot 2021-03-03 at 12 32 36" src="https://user-images.githubusercontent.com/79978026/109802496-2cf54000-7c20-11eb-8448-addc73893bb1.png">

**Comment by markusd1984** [comment]
FYI - there is a setting for it now but default was left to preserve timestamps https://github.com/mifi/lossless-cut/issues/611 , might be different issue with your use case/video files if that doesn't work.

**Comment by anciltech** [comment]
Ah I see this has been a topic of discussion. IMO Created Date refers to the "Recorded Date", although I can see how that would be debatable. 

I found this because Final Cut organizes by Created Date, and new cut files are strewn about. I'll use a program to change the date myself, but def get a vote from me to implement this option :)
