### ISSUE TITLE
Add audio fade at cut

### ISSUE THREAD

**Issue by webmastak** [mifi/lossless-cut#696]
It would be nice if there were buttons to fade out the sound.

Example:
![01](https://i.imgur.com/bRdKvr9.png)

**Comment by mifi** [comment]
I'm sorry but this is an operation that is not possible to do lossless. See #372

**Comment by webmastak** [comment]
Why, then, everything works here [mp3cut.net]( https://mp3cut.net/) ?

**Comment by mifi** [comment]
mp3cut.net is not a lossless editor. losslesscut may implement it in the future, when it gets lossy operations

**Comment by forart** [comment]
Ok, according to [this reply](https://hydrogenaud.io/index.php?topic=71172.msg1002666#msg1002666) at HA forums:

> The MP3 format can shift volume in 1.5 dB steps. One can achieve a coarse fading effect by successive 1.5 dB volume changes, and mp3directcut can do that.

Hope that helps.

**Comment by mifi** [comment]
I think this is such a narrow use case (only mp3 files) that it's not something losslesscut will support. Maybe for this use case you can use https://mpesch3.de/ to fade/in out the clips, then after that is done, use losslesscut to merge them?
