### ISSUE TITLE
merge multiple videos

### ISSUE THREAD

**Issue by pentium10** [mifi/lossless-cut#7]
merging multiple videos could be also a good feature

**Comment by mifi** [comment]
Are there no tools out there for doing it effectively already? What is the common use case for lossless merging? I think merging a number of videos is a separate kind of function that could be implemented in its own window.

**Comment by Avaray** [comment]
I just wanted to post same suggestion. I belive it might be hard to implement, but might be very useful for some users.

It should work in same way like guy described in this topic: https://github.com/mifi/lossless-cut/issues/12

Multiple start and end points with possibility to set if videos should be extracted separately or merged into one video.

**Comment by TechManiacHD** [comment]
I think this could be problematic especially if files are recorded using different device...

**Comment by Avaray** [comment]
@TechManiacHD I belive we are talking about merging multiple clips from one video file :P

**Comment by TechManiacHD** [comment]
Original question was about merging multiple videos. Anyway, merging multiple clips from one video would be a nice feature. Like to set multiple in and out points on one file and than use "scissors" one to get one file that has all selected scenes :)

**Comment by mifi** [comment]
Like @malte1989 shown already in #12, implementing multi cut is not too complicated, but merging them back into one video, I fear will cause issues with broken keyframes etc., because of the unsolved issues with accurate cutting in ffmpeg discussed in #13

**Comment by GianniGi** [comment]
What's the point of cutting... if you can't join them.

**Comment by mifi** [comment]
@GianniGi  that was a long time ago. You can join them now.

**Comment by GianniGi** [comment]
Lol thanks :-)

Il ven 23 lug 2021, 10:23 Mikael Finstad ***@***.***> ha
scritto:
