### ISSUE TITLE
Multiple audio tracks are lost

### ISSUE THREAD

**Issue by CaptaPraelium** [mifi/lossless-cut#70]
I record gameplay with separate audio tracks for game, chat, mic, music, etc. When I cut with losslesscut, only the first audio track is retained.

**Comment by mifi** [comment]
If anyone can figure out how to do this with ffmpeg command line, i'd be happy to consider including it

**Comment by CaptaPraelium** [comment]
I'll take a shot at it ;) Is there a way to have lossless-cut tell me what ffmpeg command it is going to run, under normal operation? Or perhaps a log file that shows commands sit has run previously? That way, I have something to start from...

**Comment by matdv** [comment]
I have the exact same problem and created a possible solution in #73. 
I'm using ffprobe to get the number of audio streams and their identifiers.
If there are multiple streams, these identifiers are used in the ffmpeg [Map-Option](https://trac.ffmpeg.org/wiki/Map) to include them.

**Comment by CaptaPraelium** [comment]
Thanks Matdv!

**Comment by mifi** [comment]
Hey, thanks for the implementation. But doesn't ffmpeg have built in support for this out of the box with `-map 0`?

And @matdv btw, to see the output ffmpeg cmd, Open the developer tools (Cmd+Alt+J).

**Comment by matdv** [comment]
I just reviewed the map Option and it works it out of the box, thanks!
Tested it with the updated version and pushed my changes.

**Comment by mifi** [comment]
See #76
