### ISSUE TITLE
Adobe Audition csv support ?

### ISSUE THREAD

**Issue by fuchenw** [mifi/lossless-cut#705]
how to use the auditon csv files ?

**Comment by mifi** [comment]
it's not supported (yet), but you can probably use a converter to convert it to one of the other supported import formats.

I believe adobe audition CSV is like this:
- https://github.com/nonoesp/markers2markdown/blob/master/data/markers.csv
- https://github.com/brainrepo/presquile/blob/main/mockData/valid_chaps.cvs
- https://github.com/zombak/csvtocue/blob/master/markers.csv

**Comment by fuchenw** [comment]
> it's not supported (yet), but you can probably use a converter to convert it to one of the other supported import formats.
> 
> I believe adobe audition CSV is like this:
> 
> * https://github.com/nonoesp/markers2markdown/blob/master/data/markers.csv
> * https://github.com/brainrepo/presquile/blob/main/mockData/valid_chaps.cvs
> * https://github.com/zombak/csvtocue/blob/master/markers.csv

thanks ,well i just find out that its supported！！！

just use the "Text Chapters/Youtube"option, it is works !
