### ISSUE TITLE
Request: audio volume editing, removing audio entirely

### ISSUE THREAD

**Issue by Kenkoman** [mifi/lossless-cut#71]
hey, I love how simple and easy this program is to use - its very efficient at quickly clipping vids and works perfectly for what I need to do.
one feature i'd love to have though is the ability to change the volume of the video, or remove the audio track entirely. ffmpeg is able to change volume/remove audio without reencoding, so it would be extremely helpful to include this in the program. thanks for all your efforts!

**Comment by vitawrap** [comment]
calm down

**Comment by mifi** [comment]
Can you provide a sample ffmpeg command line for how to do this losslessly?
Removing the audio track should be easy to implement, but is it that useful?

**Comment by jbruchon** [comment]
If I am submitting a video clip to a stock video site such as Videoblocks, Pond5, Shutterstock, etc. they all indicate that they strongly prefer video clips with no audio track at all and that most submissions with audio will be rejected. It is also useful if your audio is garbage or not useful; I have a quadcopter toy that produces AVIs with junk audio (no mic, just noise) and if I'm slicing footage for later use in an editor and audio track syncing isn't needed, I will typically drop the useless audio as well. Having it in LosslessCut would eliminate that intermediate step.

Regarding audio levels, not all audio formats will support lossless level changes and may require re-encoding. Whatever you do, you don't want to use the ffmpeg/libav AAC encoder as it mangles high frequencies in ways which may not be noticeable until long after the original source file was tossed. That thing has cost me hundreds of re-encodes.

**Comment by mifi** [comment]
I think lossless audio volume changes is out of the scope of this app, if ffmpeg is not able to do this easily.
I have implemented option to delete audio tracks!
