### ISSUE TITLE
Cleanup files - missing option

### ISSUE THREAD

**Issue by ltdeta** [mifi/lossless-cut#715]
With one of the last versions the option "Cleanup files?" was extended.
Now it is possible to select the following options:

- Trash auto-generated files
- Trash project CSV and auto-generated files
- Trash original source file, project CSV and auto-generated files

I am missing the following (old) Option
"Trash original source file"

**Comment by mifi** [comment]
This in now fixed in 02c2d86a45ebac51bbe2e5d10221ac36e4fc94d7 - like this:

![](https://user-images.githubusercontent.com/402547/113597263-a4761f00-9665-11eb-89b0-1d7052b3bade.png)

**Comment by ltdeta** [comment]
:thumbsup:
