### ISSUE TITLE
Cannot select and copy text in segment pane

### ISSUE THREAD

**Issue by leongwaikay** [mifi/lossless-cut#719]
In order to make it easier for me to help you, I ask that you please try these things first:
- Try with the newest version from GitHub: https://github.com/mifi/lossless-cut/releases/latest
It's a new bug after I updated to the newest version

**Describe the bug**
In the main window there is a side panel on the right that shows the "Segments to export:". I used to be able to select the timecode of each segment and copy it. e.g. 00:20:32.412 - 01:21:23.123. Basically I use the timecode with another script to split and merge my subtitle files.

**To Reproduce**
1. Open any video
2. Create a segment
3. Segment timecode cannot be selected and copied. Trying to select on results in dragging the segment.

**Expected behavior**
Timecode should be highlighted like a regular text and can be copied to clipboard

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by mifi** [comment]
Can File -> Export as CSV serve this purpose? You get a neat list of time values

**Comment by mifi** [comment]
I mean File -> Export -> Timestamps (CSV) - hopefully that will satisfy your need. If not, we could have an option to click a button to show or copy the text to clipboard.

**Comment by mifi** [comment]
Closing due to lack of response

**Comment by mifi** [comment]
reopening due to #1088

**Comment by leongwaikay** [comment]
Sorry for the lack of response. My current workflow does not require the copying of timestamps anymore. (I used it to resync subtitles with another script)

Is there a need for something complicated like a copy button? Wouldn't it be easier to make the text selectable while still remaining read only?

**Comment by mifi** [comment]
I think the problem is that the segments are drag-droppable (to reorder), so selecting would not work.

**Comment by leongwaikay** [comment]
Ah so that was what changed that made it unselectable.

In any case, I found there is a place at the bottom to manually input the cut-points which is selectable. Solves my workflow but not sure about https://github.com/mifi/lossless-cut/issues/1088
![image](https://user-images.githubusercontent.com/2689401/167986878-b1ab2b55-45f1-4619-a882-a6b52a36abf4.png)
