### ISSUE TITLE
Set a default output directory

### ISSUE THREAD

**Issue by Defiant1ne** [mifi/lossless-cut#72]
It would be nice to be able to set a default output directory that gets remembered each time the program is opened.

**Comment by mifi** [comment]
Should be easy to implement. Just need to add some persisting framework, I'm thinking one of these:
https://github.com/sindresorhus/electron-store
https://github.com/nathanbuchar/electron-settings
https://github.com/electron-userland/electron-json-storage

**Comment by mifi** [comment]
Closing this. Put an upvote on #149 if you want this implemented
