### ISSUE TITLE
Add metadata when there is none: Cannot read property 'language' of undefined

### ISSUE THREAD

**Issue by syntax68** [mifi/lossless-cut#720]
Hi

**Describe the bug**
An error occurs when i want to add a metadata entry to a subtiltle entry that has no metadata.
If one or more metadata already exist, no error occurs.

**To Reproduce**
1. open a file. I opened a mkv with 2 audio streams.
2. add a srt text file with the option "Inlude more tracks from other file"
3. on the subtitle line, click on the "edit metadata" icon.
4. a popup window appears with the ability to edit and add metadata. Click on the "+ Add metadata" button.
5. a popup window (Add metadata - Enter metadata key) appears. Enter "language" in the edit box. Then click on the Ok button.
6. An error message appears :
"Something went wrong
Cannot read property 'language' of undefined"

**Screenshots**
See screenshot and a log file.
![addmetadata1](https://user-images.githubusercontent.com/82287535/114282935-4cfdf780-9a47-11eb-9214-05466f32f7ae.jpg)
[addmetadata2.log.txt](https://github.com/mifi/lossless-cut/files/6290659/addmetadata2.log.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - LossLessCut version 3.36

**Comment by Shakil-Shahadat** [comment]
I confirm the bug. The same happens to me.

**Comment by mifi** [comment]
Thanks for reporting. Have now fixed it
