### ISSUE TITLE
Only export specific segment 

### ISSUE THREAD

**Issue by alzuhair** [mifi/lossless-cut#723]
Exporting specific segment has been removed in version 3.36.0
It was very useful in 3.34.3
When pressing export there was an option to export one segment e.g. Segment 2

**Comment by mifi** [comment]
the function is still there, but now you instead right click on the segment in the segment list. see screenshot:

<img width="297" alt="Screenshot 2021-04-14 at 14 45 26" src="https://user-images.githubusercontent.com/402547/114673152-174f5c00-9d30-11eb-97d5-5c3590da9400.png">

**Comment by ViperMaul** [comment]
I love your app. One of my top favorite and most used. Absolutely a time saver! 
This change is a minor step backwards in time savings. 
Before it is 2 clicks to export a single segment: Export... Export Selected Segment 
Now it is 4 clicks: Right-click... Include ONLY this segment in export... Export... Export Selected Segment

I see the positive trade off however with the extra options. 
It is fair trade, I cannot argue to much with that. Number of clicks are precious in time saving apps. 

This is more of an opportunity to say **thank you** for continuing to add value to your already extremely valuable app. I use it weekly if not daily. 

Keep up the much appreciated work.

**Comment by mifi** [comment]
Ok I hear ya. I added a suggestion for a keyboard shortcut for selecting only current segment for export in https://github.com/mifi/lossless-cut/issues/254#issuecomment-903590399

That way you will be able to do <kbd>upcoming keyboard shortcut</kbd> -> <kbd>E</kbd> -> <kbd>E</kbd> to export single. When custom keyboard mappings are implemented, I will add that as an available shortcut action. let me know if that sounds ok.
Closing this issue to reduce number of issues.
