### ISSUE TITLE
Remember last directory when opening files

### ISSUE THREAD

**Issue by dandv** [mifi/lossless-cut#724]
**Is your feature request related to a problem? Please describe.**
I'm trying to quickly open a series of videos in the same directory.

**Describe the solution you'd like**
When I click File -> Open, I would like for LosslessCut to default to the last directory from which it open a file. Instead, the file picker opens to the Recent tab. I'm using KDE.

**Describe alternatives you've considered**
Add the directory to the OS's favorites.

**Additional context**
#149

**Comment by mifi** [comment]
I believe this is KDE specific behavior, as on MacOS when I Open, it will show the previously opened directory. Maybe have to provide `defaultPath` to: https://github.com/mifi/lossless-cut/blob/2b2b12af0a2bba3d018fbf26b020e45febee0c1f/public/menu.js#L20

But this is low priority unless it is also a problem on windows
