### ISSUE TITLE
Two suggestions

### ISSUE THREAD

**Issue by alzuhair** [mifi/lossless-cut#725]
1. To make an option to insert value in the setting for playback speed 
2. To make the button of export selected beside export button (similar to version 3.34.3)

**Comment by mifi** [comment]
1. See #729

2. can be achieved with this right click menu now:
<img width="349" alt="Screenshot 2021-08-23 at 16 11 59" src="https://user-images.githubusercontent.com/402547/130421833-1636cb8b-5513-4f06-9b4c-1a14424a249a.png">

I don't think I want to re-implement "export only selected), as it is covered by this function now.
