### ISSUE TITLE
Merging files with different audio parameters resulting in no audio OR audio delay

### ISSUE THREAD

**Issue by slrslr** [mifi/lossless-cut#732]
Hello, LC 3.33.1; Linux
i have tried to use Merge function to merge .avi files, first files was MP3 audio codec and then was couple of AC-3 codec.
Result: audio was not played on in resulting merged file on the part where was AC-3 files.

So i have used ffmpeg to convert these AC-3 files to MP3 (codec of the first files in the merge list):
`read -r -p "Input video file path/name to convert:" f && read -r -p "Input file extension:" e && ffmpeg -i "$f" -vcodec copy -acodec mp3 "$f".mp3."$e"`

Yet now after merging, the resulting video file audio started to be delayed in the part where was AC-3 files

The mediainfo difference:

first file:
```
Audio
ID                                       : 1
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 3
Format settings                          : Joint stereo / MS Stereo
Codec ID                                 : 55
Codec ID/Hint                            : MP3
Duration                                 : 53 s 16 ms
Bit rate mode                            : Variable
Bit rate                                 : 120 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 kHz
Compression mode                         : Lossy
Stream size                              : 775 KiB (14%)
Alignment                                : Aligned on interleaves
Interleave, duration                     : 24  ms (0.60 video frame)
Interleave, preload duration             : 25  ms
```

second file which had AC-3 codec previously and that i converted using ffmpeg:
```
Audio
ID                                       : 1
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 3
Format settings                          : Joint stereo / MS Stereo
Codec ID                                 : 55
Codec ID/Hint                            : MP3
Duration                                 : 1 min 30 s
Bit rate mode                            : Constant
Bit rate                                 : 128 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 44.1 kHz
Compression mode                         : Lossy
Stream size                              : 1.39 MiB (8%)
Alignment                                : Aligned on interleaves
Interleave, duration                     : 26  ms (0.65 video frame)
```
([full media info](https://bin.disroot.org/?d923ddf5c4b3f7ca#EVPgEAQqb4LEE71E2Wxt1tQadN8YhAAjCfDDkqASVyi4))

so how to convert the second file now so audio is right in the resulting merged file?
It can be handy if losslesscut knows which parameters are problematic and either A) convert these or B) report these to user so he knows which file he need to convert and which parameters to modify (quite difficult feat for a regular computer user).

I was already asking elsewhere on [how to clone video file parameters so i can use them on a different file](https://superuser.com/questions/1634076/how-to-ffmpeg-encode-using-same-codecs-and-parameters-as-certain-file-has), but no solution to this. :relieved:

Update: changing sampling rate worked in this case, so after the previous command where i converted to mp3 (which is codec of the first several files that i used for merging) i have ran following one which modiffy the sampling rate to match one in the first files:

> read -r -p "Input video file path/name to convert:" f && read -r -p "Input file extension:" e && ffmpeg -i "$f" -vcodec copy **-ar 48000** "$f".48kHz."$e"

**Comment by slrslr** [comment]
Happened again that the audio was desynchronized after merging files. I have fixed it again by upsampling some of the files audio tracks. Until Losslesscut can be more helpful in this task, i am using [this Linux bash script](https://github.com/slrslr/Miscellaneous-bash-scripts/blob/master/mediainfocomparefiles) to find out differences in files, please improve that script if you have ideas.

**Comment by mifi** [comment]
Hi. Merging (concatenating) multiple files with different audio parameters is not possible to do losslessly, unfortunately, so it's not something that will be supported by LosslessCut.
