### ISSUE TITLE
Full support for dark theme

### ISSUE THREAD

**Issue by SameExpert** [mifi/lossless-cut#733]
**Is your feature request related to a problem? Please describe.**
On **Linux** (**KDE Plasma**) I'm having dark theme. It looks odd if **LosslessCut** stays out light-themed when everything else is dark.

**Describe the solution you'd like**
**LosslessCut** should support for dark mode. There can be an option in settings for **Dark mode** / **Light mode** / **System default** (if possible)

**Describe alternatives you've considered**
As it depends on **gtk3**, system's GTK settings should be used.

**Comment by mifi** [comment]
losslesscut is a cross platform app so it doesn't use native widgets like GTK. it could however try to follow colors. however losslesscut UI is already rather dark. can you provide a screenshot of what you mean by `It looks odd if LosslessCut stays out light-themed when everything else is dark.` ?

**Comment by SameExpert** [comment]
The main windows is OK (even though it's tool-tips are brightened it's not much). But this window is so brightened and doesn't suite for dark themes:
![Screenshot__1](https://user-images.githubusercontent.com/59734562/117146422-b7365d80-ada3-11eb-931e-1d8689f1ef1d.png)

**Comment by Mitch037** [comment]
Any chance we ever get dark mode in LosslessCut?

**Comment by mifi** [comment]
The problem is that the UI components of evergreen-ui don’t look very good on a dark background. But as evergreen now has theming support, I think we could define a dark theme.

if someone wants to try to make a dark theme for evergreen that would be a start

https://evergreen.segment.com/introduction/theming

**Comment by mkibp** [comment]
Am I blind or is the dark mode config setting not exposed anywhere in the UI settings?

**Comment by mifi** [comment]
lower left 
<img width="30" alt="Screenshot 2024-04-03 at 22 38 54" src="https://github.com/mifi/lossless-cut/assets/402547/0161b28b-11c5-4c75-9562-cc90aa6891e2">

**Comment by mkibp** [comment]
Ahhh, in advanced view, thank you. Though I suggest considering perhaps adding it somewhere to the settings view too for completeness sake
