### ISSUE TITLE
Merging files gets stuck at 99.9%

### ISSUE THREAD

**Issue by m07722** [mifi/lossless-cut#734]
I'm using OSX 10.13.6 I was able to resolve the issue rather easily but I thought I'd post here anyway.

I was trying to merge two GoPro files straight from the miniSD while the destination directory was a separate external hard drive. The merging would always get stuck at 99.9% percent which was super frustrating. I tried moving the original files to my desktop and also changed the destination directory to the desktop and it worked like a charm.

**Comment by mifi** [comment]
could you provide some more info? error report, or check developer tools for any error there

**Comment by mifi** [comment]
Actually this seems like it could be the same issue as #762 - please file more info there if you can
