### ISSUE TITLE
Allow LONG Path+File names for export (up to Windows limit of 256 Chars)

### ISSUE THREAD

**Issue by tobwz** [mifi/lossless-cut#735]
Sometimes I want to export a certain interval from an existing *.mp4 into the current directory.

If the MP4 video file name including the prepended path is very long I got an export error from LosslessCut.

If I move the same video file to a folder with short name (e.g.

D:\music\

then everything works fine.

So the reason is in LC.

The exported original path+original filename is below the maximum allowed 256 chars from Windows.

So LC should allow path+filenames up to this limit as well and don't force users to move them at first.

Can this bug be fixed in the next release?

Thank you

**Comment by mifi** [comment]
which error are you getting? can you check developer tools?

**Comment by mifi** [comment]
I think this is the same issue as #745 - closing this as dupe
