### ISSUE TITLE
bit-perfect waveform editor

### ISSUE THREAD

**Issue by Rafawell** [mifi/lossless-cut#736]
Good Morning! The program is very good, but I think it could implement a little something, a bit-perfect waveform editor in the split-and-join scheme for those who just want to edit the audio. Thanks

**Comment by mifi** [comment]
Thanks for your suggestion, i'll add it to the main feature request for improved waveforms #260

**Comment by mifi** [comment]
coming in the next version

<img width="763" alt="Screenshot 2023-03-12 at 16 42 24" src="https://user-images.githubusercontent.com/402547/224533901-594bd1ba-b690-4c3b-9453-b264e751591a.png">
