### ISSUE TITLE
No video only audio using TS files when merging cuts after exporting

### ISSUE THREAD

**Issue by csvnevada** [mifi/lossless-cut#737]
No error

{
  "state": {
    "filePath": "G:\\Video\\New Unedited Dish Net Video\\Chasing Classic Cars-Fly Like an Elgin_s16 ep4.TS",
    "fileFormat": "mp4",
    "externalStreamFiles": [],
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_time_base": "1001/60000",
        "codec_tag_string": "HDMV",
        "codec_tag": "0x564d4448",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1088,
        "closed_captions": 0,
        "has_b_frames": 1,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 40,
        "chroma_location": "left",
        "field_order": "bb",
        "refs": 1,
        "is_avc": "false",
        "nal_length_size": "0",
        "id": "0x1011",
        "r_frame_rate": "30000/1001",
        "avg_frame_rate": "30000/1001",
        "time_base": "1/90000",
        "start_pts": 72027,
        "start_time": "0.800300",
        "duration_ts": 338729391,
        "duration": "3763.659900",
        "bits_per_raw_sample": "8",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        }
      },
      {
        "index": 1,
        "codec_name": "mp2",
        "codec_long_name": "MP2 (MPEG audio layer 2)",
        "codec_type": "audio",
        "codec_time_base": "1/48000",
        "codec_tag_string": "[3][0][0][0]",
        "codec_tag": "0x0003",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "id": "0x1100",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/90000",
        "start_pts": 72027,
        "start_time": "0.800300",
        "duration_ts": 338683680,
        "duration": "3763.152000",
        "bit_rate": "384000",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        }
      }
    ],
    "copyStreamIdsByFile": {
      "G:\\Video\\New Unedited Dish Net Video\\Chasing Classic Cars-Fly Like an Elgin_s16 ep4.TS": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {}
    ],
    "fileFormatData": {
      "filename": "G:\\Video\\New Unedited Dish Net Video\\Chasing Classic Cars-Fly Like an Elgin_s16 ep4.TS",
      "nb_streams": 2,
      "nb_programs": 1,
      "format_name": "mpegts",
      "format_long_name": "MPEG-TS (MPEG-2 Transport Stream)",
      "start_time": "0.800300",
      "duration": "3763.659900",
      "size": "9872332892",
      "bit_rate": "20984537",
      "probe_score": 50
    },
    "rotation": 360,
    "shortestFlag": false
  },
  "platform": "win32",
  "version": "3.36.0"
}

In order to make it easier for me to help you, I ask that you please try these things first:
- Try with the newest version from GitHub: https://github.com/mifi/lossless-cut/releases/latest
- Check https://github.com/mifi/lossless-cut and **Known issues** / **Troubleshooting**
- Search for your problem under Issues or Discussions
- Please try other type of file and see if it works.

**Share information to help me understand**
- If you have an issue cutting a particular file, please also share the file, if possible. (or mail a link to finstaden@gmail.com if private.) Also please try to cut it with the ffmpeg command line directly.
- If you have a problem or an unexpected bug or crash, please open developer tools after starting LosslessCut and before doing the failing operation. Then share the output from the javascript Console. (Menu: Tools > Toggle Developer Tools)
- Please provide the error report if you got one (Menu: Help -> Report an error)

**Describe the bug**

**To Reproduce**
1. Open file '...'
2. Click on '...'
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]

**Additional context**

**Comment by mifi** [comment]
This is probably because TS is not natively supported. try to convert to supported format from the "file" menu then "Fastest: Low playback speed"
