### ISSUE TITLE
Losslesscut snap launches only once

### ISSUE THREAD

**Issue by hvbakel** [mifi/lossless-cut#738]
After installing the losslesscut snap version on Ubuntu 20.04 it will only launch once. All subsequent launches fail silently with no messages in syslog. I tried both the stable and edge versions, with the same results for both.

Uninstalling the snap version with `snap remove --purge losslesscut` and then reinstalling the snap will again allow for a single launch, but it's dead in the water afterwards.

**Comment by mifi** [comment]
could it be related to #340  ? could you try the no-sandbox arg? could you try deleting the losslesscut folder inside `$XDG_CONFIG_HOME` or `~/.config` and see if it allows subsequent launch?

**Comment by hvbakel** [comment]
The no-sandbox argument didn't work, but, interestingly, after deleting the .config folder within the losslesscut snap folder it does allow subsequent launches. I only had to delete the .config folder once and it continues to start. Thanks for the workaround!

**Comment by mifi** [comment]
Ok cool. i don't know what happened there but then i guess this issue is resolved?
