### ISSUE TITLE
Two folders in AppData/Roaming

### ISSUE THREAD

**Issue by Avaray** [mifi/lossless-cut#74]
Lossless Cut is creating two folders in AppData/Roaming directory.
- LosslessCut
- lossless-cut

I think one would be enough :)

// Win 10 Pro 64bit

**Comment by jshrek** [comment]
The two folder issue happens because in your package.json you need to include a `name` and also `productName`. The productName needs to be in two places: (1) on same level as name and (2) under build:

At top of package.json:
"name": "my-app-name",
"productName": "My App Name"

and then also later under BUILD like this:
"build": {
    "appId": "com.myappname",
    "productName": "My App Name",

You will then only get one folder created called My App Name and the my-app-name folder will not get created.

**Comment by Hrxn** [comment]
@jshrek What's the reason for that behaviour?

**Comment by jshrek** [comment]
@Hrxn What I think is happening is this...

`name` can not have any spaces in it but `productName` can have spaces.

Electron creates a folder based on `productName` from the BUILD section.

It then creates a folder based on the `name` from the top section unless you also include `productName` in the top section which will override `name`. So if you include two `productName` with the same name then only one folder will get created.

This is NOT an issue with lossless-cut but an issue with electron (or node.js) itself.

**Comment by mifi** [comment]
@jshrek we don't have any "build" object in the package.json of losslesscut. Is that ok since we are already specifying  `--win32metadata.ProductName=LosslessCut`?
Meaning we only need to add `"productName": "LosslessCut"` next to `"name": "lossless-cut"`?

**Comment by jshrek** [comment]
I honestly don't know the answer to your question, although what you say sounds correct.

I guess try it and let us know if it works or not.

**Comment by Hrxn** [comment]
Anything new here?
Because 2.5.0 changelog mentions
> - change to electron-builder
> - upgrade electron to 7

**Comment by mifi** [comment]
I havent tested yet but feel free to test this in the newest version

**Comment by mifi** [comment]
Reopen if still an issue. now at electron 8

**Comment by Hrxn** [comment]
Just FYI, this seems indeed to be fixed.

I am just having a `AppData\Roaming\LosslessCut` directory now.
