### ISSUE TITLE
When cutting interval at keyframes then first keyframe is not included

### ISSUE THREAD

**Issue by tobwz** [mifi/lossless-cut#742]
Assume I load an .mp4 video and jump to a certain keyframe, set the start cutpoint, move forward to a following e.g. 10th keyframes after it and set the end cutpoint.

Finally I exported the interval to a new .mp4 video.

It works.

However when I play this just created video in a videoplayer like VLC the following happens:

The VLC window remains black at first until the first keyframe AFTER the start of video is reached.
Then I can see and watch the video "us usual".

It seems to me that LC does NOT add the very first start keyframe from start cutpoint into the exported MP4.
When played in an external video player the first frames find no reference keyframe.
So they show just black. If the second keyframe is reached then a reference exists for all subsequent frames.

This is bad.

Cutting mp4 video in such a manner works in other editor tools like Avidemux without problems.

Can you fix this in LC?

Thank you

**Comment by mifi** [comment]
Hi. This is a currently known issue with some file types. You can work around it by moving the cursor to a few frames **after** the desired keyframe. See https://github.com/mifi/lossless-cut/issues/330#issuecomment-827200239
I will update readme
