### ISSUE TITLE
h.265 HEVC no video

### ISSUE THREAD

**Issue by NY-Guy** [mifi/lossless-cut#744]
Trying to trim a video made with PlayOn's new 1080p resolution, which is coded with HEVC/h.265 format.  The files load fine, they trim fine.  But, there's no video in the preview pane, so you can't determine where to make your cuts.  Is there something we can do to enable the picture for HEVC videos?

No error

{
  "state": {
    "filePath": "X:\\Kodi - FILMS\\PlayOn_FILMS - Raw (NEW May)\\Dreamgirls.mp4",
    "fileFormat": "mp4",
    "externalStreamFiles": [],
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "hevc",
        "codec_long_name": "H.265 / HEVC (High Efficiency Video Coding)",
        "profile": "Main",
        "codec_type": "video",
        "codec_time_base": "1001/30000",
        "codec_tag_string": "hvc1",
        "codec_tag": "0x31637668",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1088,
        "closed_captions": 0,
        "has_b_frames": 0,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 123,
        "color_range": "tv",
        "refs": 1,
        "r_frame_rate": "30000/1001",
        "avg_frame_rate": "733375012/30935865",
        "time_base": "1/90000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 713764583,
        "duration": "7930.717589",
        "bit_rate": "2505560",
        "nb_frames": "188008",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "VideoHandler"
        }
      },
      {
        "index": 1,
        "codec_name": "mov_text",
        "codec_long_name": "MOV text",
        "codec_type": "subtitle",
        "codec_time_base": "0/1",
        "codec_tag_string": "tx3g",
        "codec_tag": "0x67337874",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/90000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 704177910,
        "duration": "7824.199000",
        "bit_rate": "82",
        "nb_frames": "4130",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "eng",
          "handler_name": "SubtitleHandler"
        }
      },
      {
        "index": 2,
        "codec_name": "mov_text",
        "codec_long_name": "MOV text",
        "codec_type": "subtitle",
        "codec_time_base": "0/1",
        "codec_tag_string": "tx3g",
        "codec_tag": "0x67337874",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/90000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 704309130,
        "duration": "7825.657000",
        "bit_rate": "80",
        "nb_frames": "3896",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "spa",
          "handler_name": "SubtitleHandler"
        }
      },
      {
        "index": 3,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_time_base": "1/44100",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "44100",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/44100",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 349882697,
        "duration": "7933.848005",
        "bit_rate": "190260",
        "max_bit_rate": "190260",
        "nb_frames": "341683",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "SoundHandler"
        }
      },
      {
        "index": 4,
        "codec_name": "png",
        "codec_long_name": "PNG (Portable Network Graphics) image",
        "codec_type": "video",
        "codec_time_base": "0/1",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "width": 1280,
        "height": 720,
        "coded_width": 1280,
        "coded_height": 720,
        "closed_captions": 0,
        "has_b_frames": 0,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "rgb24",
        "level": -99,
        "color_range": "pc",
        "refs": 1,
        "r_frame_rate": "90000/1",
        "avg_frame_rate": "0/0",
        "time_base": "1/90000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 714046410,
        "duration": "7933.849000",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 1,
          "timed_thumbnails": 0
        }
      }
    ],
    "copyStreamIdsByFile": {
      "X:\\Kodi - FILMS\\PlayOn_FILMS - Raw (NEW May)\\Dreamgirls.mp4": {
        "0": true,
        "1": true,
        "2": true,
        "3": true,
        "4": false
      }
    },
    "cutSegments": [
      {}
    ],
    "fileFormatData": {
      "filename": "X:\\Kodi - FILMS\\PlayOn_FILMS - Raw (NEW May)\\Dreamgirls.mp4",
      "nb_streams": 5,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "7933.849000",
      "size": "2681396363",
      "bit_rate": "2703753",
      "probe_score": 100,
      "tags": {
        "major_brand": "isom",
        "minor_version": "512",
        "compatible_brands": "isomiso2mp41",
        "Browsepath": "HBO Max | Search results for \"dreamgirls\"",
        "Date": "2006",
        "HasChapters": "0",
        "MaxAudioJump": "0.00",
        "MaxSourceFps": "23.96",
        "MaxVideoJump": "3.50",
        "MinSourceFps": "22.30",
        "PLVF": "1",
        "Path": "https://play.hbomax.com/feature/urn:hbo:feature:GYDQXFAD6F4k1qgEAAAA0?autoplay=true&reentered=true",
        "Properties": "PEhhc0FkdmVydGlzZW1lbnRzPkZhbHNlPC9IYXNBZHZlcnRpc2VtZW50cz48VmlkZW9JRD5HWURRWEZBRDZGNGsxcWdFQUFBQTA8L1ZpZGVvSUQ+PElEPnVybjpoYm86ZmVhdHVyZTpHWURRWEZBRDZGNGsxcWdFQUFBQTA8L0lEPjxDb250ZW50UmF0aW5nPlBHLTEzPC9Db250ZW50UmF0aW5nPjxVUk4+dXJuOmhibzpmZWF0dXJlOkdZRFFYRkFENkY0azFxZ0VBQUFBMDwvVVJOPjxVUk5UeXBlPkZlYXR1cmU8L1VSTlR5cGU+PExhcmdlVGh1bWJuYWlsPmh0dHBzOi8vYXJ0aXN0LmFwaS5jZG4uaGJvLmNvbS9pbWFnZXMvR1lEUVhGQUQ2RjRrMXFnRUFBQUEwL3RpbGU/dj02NGZhZmE3MWEwMGJiMWQyYzEyY2E4NzM0Zjk3Y2RhMyZhbXA7c2l6ZT0xMjgweDcyMCZhbXA7Y29tcHJlc3Npb249JTdiJTdiY29tcHJlc3Npb24lN2QlN2QmYW1wO3Byb3RlY3Rpb249JTdiJTdicHJvdGVjdGlvbiU3ZCU3ZCZhbXA7c2NhbGVEb3duVG9GaXQ9JTdiJTdic2NhbGVEb3duVG9GaXQlN2QlN2QmYW1wO3Byb2R1Y3RDb2RlPWhib01heCZhbXA7b3ZlcmxheUltYWdlPXVybiUzYXdhcm5lcm1lZGlhJTNhYnJhbmQlM2FoYm88L0xhcmdlVGh1bWJuYWlsPjxGb3JlaWduTWV0YWRhdGFQcm92aWRlcj5IQk88L0ZvcmVpZ25NZXRhZGF0YVByb3ZpZGVyPjxSZWxlYXNlWWVhcj4yMDA2PC9SZWxlYXNlWWVhcj48YnJvd3NlUGF0aD5IQk8gTWF4IHwgU2VhcmNoIHJlc3VsdHMgZm9yICJkcmVhbWdpcmxzIjwvYnJvd3NlUGF0aD48UGFyZW50YWxDb250cm9sc01vdmllUmVzdHJpY3Rpb24+TkMtMTc8L1BhcmVudGFsQ29udHJvbHNNb3ZpZVJlc3RyaWN0aW9uPjxQYXJlbnRhbENvbnRyb2xzVFZSZXN0cmljdGlvbj5UVi1NQTwvUGFyZW50YWxDb250cm9sc1RWUmVzdHJpY3Rpb24+PFByb3ZpZGVyTmFtZT5IQk8gTWF4PC9Qcm92aWRlck5hbWU+PFByb3ZpZGVySUQ+aGJvbWF4PC9Qcm92aWRlcklEPjxDbG91ZFJlY29yZGluZ0lEPjY2ODE0MjA8L0Nsb3VkUmVjb3JkaW5nSUQ+PENsb3VkRW52aXJvbm1lbnQ+cHJkPC9DbG91ZEVudmlyb25tZW50Pg==",
        "ProviderName": "HBO Max",
        "RecordingTimestamp": "2021-05-12T19:44:11",
        "SourceFps": "23.96",
        "Sourceid": "https://play.hbomax.com/feature/urn:hbo:feature:GYDQXFAD6F4k1qgEAAAA0?autoplay=true&reentered=true",
        "Status": "2",
        "SubsLanguages": "eng,spa",
        "SubsTrack_eng": "﻿WEBVTT\r\nKind: subtitles\r\nLanguage: eng\r\n\r\n00:01:00.163 --> 00:01:01.871 align:middle line:84.66%\r\n(PEOPLE CHEERING)\r\n\r\n00:01:02.788 --> 00:01:04.288 align:middle line:84.66%\r\n(MUSIC PLAYING)\r\n\r\n00:01:08.331 --> 00:01:09.831 align:middle line:84.66%\r\n(PEOPLE WHOOPING)\r\n\r\n00:01:26.788 --> 00:01:28.621 align:middle line:79.33%\r\nM.C.: Ladies and gentlemen,\r\nthe Detroit Theater\r\n\r\n00:01:28.705 

****    (((subtitle text omitted here to save space)))

 --> 02:09:44.324 align:middle line:84.66%\r\n♪ Tú eres mi sueño ♪\r\n\r\n02:09:44.407 --> 02:09:49.115 align:middle line:79.33%\r\n♪ Todas las cosas\r\nQue nunca sabré ♪\r\n\r\n02:09:48.896 --> 02:09:50.854 align:middle line:84.66%\r\n♪ Tú eres mi sueño ♪\r\n\r\n02:09:50.405 --> 02:09:54.697 align:middle line:79.33%\r\n♪ ¿Quién podría creer\r\nQue se volverían realidad? ♪\r\n\r\n02:09:54.989 --> 02:09:58.697 align:middle line:79.33%\r\n♪ ¿Quién podría creer\r\nQue el mundo creerá ♪\r\n\r\n02:09:59.916 --> 02:10:02.708 align:middle line:84.66%\r\n♪ También en mi sueño? ♪\r\n\r\n02:10:03.231 --> 02:10:05.814 align:middle line:84.66%\r\n♪ La primera vez que te vi ♪\r\n\r\n02:10:06.187 --> 02:10:11.145 align:middle line:79.33%\r\n♪ Ah ♪\r\n♪ Dije: \"¡Cielos!\" ♪\r\n\r\n02:10:13.123 --> 02:10:16.748 align:middle line:84.66%\r\n♪ Dije: \"¡Cielos!\" ♪\r\n\r\n02:10:18.883 --> 02:10:25.633 align:middle line:84.66%\r\n♪ \"Ese es mi sueño\" ♪\r\n",
        "Thumbnailurl": "https://artist.api.cdn.hbo.com/images/GYDQXFAD6F4k1qgEAAAA0/tile?v=64fafa71a00bb1d2c12ca8734f97cda3&size=640x360&compression=%7b%7bcompression%7d%7d&protection=%7b%7bprotection%7d%7d&scaleDownToFit=%7b%7bscaleDownToFit%7d%7d&productCode=hboMax&overlayImage=urn%3awarnermedia%3abrand%3ahbo",
        "TotalAudioJumps": "0",
        "TotalVideoJumps": "1",
        "sort_name": "Dreamgirls",
        "media_type": "9",
        "comment": "The hit Broadway musical comes to the screen in this amazing 2006 film about the rise of a 1960s female supergroup--and the price that they pay along the way. Winner of two Academy Awards(R), the film stars Jamie Foxx as the group's Svengali-like manager, Beyoncé Knowles as the group's gorgeous lead and Eddie Murphy as a soul singer who gives the girls their first break.",
        "title": "Dreamgirls",
        "encoder": "Lavf58.33.100"
      }
    },
    "rotation": 360,
    "shortestFlag": false
  },
  "platform": "win32",
  "version": "3.36.0"
}

**Comment by NY-Guy** [comment]
I did find this web page that seems to address this issue but have no idea how to implement it... Can anyone offer any assistance?
https://github.com/mifi/lossless-cut/issues/119

It offers the following advice to fix it, but I still can't figure it out, with respect to LosslessCut:
"heres the solution from the chrnoium developers
https://github.com/henrypp/chromium/blob/master/hevc_support.md
https://github.com/henrypp/chromium/blob/master/hevc_support_new.md"

**Comment by mifi** [comment]
See #88
