### ISSUE TITLE
Preserve also the creation time/date

### ISSUE THREAD

**Issue by parasiteoflife** [mifi/lossless-cut#746]
**Is your feature request related to a problem? Please describe.**
Currently the app preserves the `modification` and `accessed` dates for the output files but the `creation` date is always set to the current one.

**Describe the solution you'd like**
Preserve also the `creation` dates so the output files have all original dates.

**Comment by mifi** [comment]
Actually I'm not sure if this is even possible to do on most operating systems.

**Comment by mifi** [comment]
Seems like it is not really possible to easily do from node.js/electron: https://stackoverflow.com/questions/25484175/nodejs-how-to-change-creation-time-of-file
