### ISSUE TITLE
Mass process files

### ISSUE THREAD

**Issue by Mixka** [mifi/lossless-cut#749]
Add option to mass process clips.

Maybe like:
- User select/drop multiple files to LLC ("Merge/concatenate files" popup would have the option to process multiple files).
- New panel would open and has all the files listed.
- Selecting segments works like everything works now. Users just select file from the list and then select clip segments and continue to select files so far that all files segments are selected.
- "Export" button now has changed to the "Export All" button and it process all listed file segments.

Nice and easy :) Really a life saving with hundreds/thousands of video clips.

Request is quite close to this https://github.com/mifi/lossless-cut/issues/89

**Comment by mifi** [comment]
Trying to keep the number of issues down, so please add ideas to #89 instead. Thanks!
