### ISSUE TITLE
Audio Going Out Of Sync In Long Vídeos

### ISSUE THREAD

**Issue by bvillar** [mifi/lossless-cut#75]
Hello,

First of all, I would like to thank you for the amazing software, quick and easy to use. I'm having problems with the sound, though. Every time I try to cut a video that results in a piece of 5 minutes or more, the audio goes slightly out of sync. And while some players adjust the sync by "pausing" the image while the audio runs, the video itself is sill unsynced. That happens with mp4 files, and when I tried to do the same with a webm video, the sync was lost so badly that no player was able to compensate it. Is there any workaround for this?

Thanks in advance and best regards!

Bruno

**Comment by mifi** [comment]
Hi
Could you share some file that gets out of sync when you cut it, so others can try to reproduce?
Is it out of sync since the first second it starts playing or does it drift out of sync?
Does it matter how far into the video you start cut from? is it consistent?

**Comment by bvillar** [comment]
Sure, sharing right know! I'll put the uploaded files at the end of the post.

It's always out of sync, but some players compensate it when the delay is of a few seconds. Others, like MPC, just stay out of sync all the time. And in the most problematic case, the delay was enormous and no players seemed able to sync it.

From what I saw in the few tests I made, looks like the amount of no-sync depends on the place where I select to cut the video. But besides that, it is indeed consistent.

Audio Sync Issue (stronger):

https://drive.google.com/open?id=1wHLJf6-tLLkGnDnOyCfwvnAUBB2OYOMr

Audio Sync Issue (lighter):

https://drive.google.com/open?id=16cZAvQTQb-SbKazrjTqu9ICk49qbMKIJ

Hope it helps!

**Comment by fc** [comment]
I'm having audio issues too which may be related, install youtube-dl if you haven't already, then:
```
youtube-dl -x --audio-format mp3 https://www.youtube.com/watch?v=2_-7GgxeE5c
```

I try to cut the audio between 25:20 and 25:35 but the audio is offset and it does not cut at the selected range (it's maybe 12 seconds off).

**Comment by mifi** [comment]
In the newest version 1.13.0 I've added a button to the leftmost of the right button row "nc". If you toggle this to "kc" - keyframe cut, then maybe it helps?

**Comment by nathanfarlow** [comment]
Can confirm, using the keyframe cut option fixed the audio desync problem with my long videos.

**Comment by mifi** [comment]
@bvillar @fc fixed for you as well?

**Comment by mikeyaworski** [comment]
Toggling to "kc" solved my sync issue as well

**Comment by johnwoolee** [comment]
Solved my issue as well.

**Comment by Avigd** [comment]
I use version 1.14.0 which is the one available to download. I experience the audio sync loss when I cut long videos. I do not find the toggle switch mentioned in previous posting. Can someone send screenshot with description how to resolve the problem. Many thanks

**Comment by mikeyaworski** [comment]
> I use version 1.14.0 which is the one available to download. I experience the audio sync loss when I cut long videos. I do not find the toggle switch mentioned in previous posting. Can someone send screenshot with description how to resolve the problem. Many thanks

![image](https://user-images.githubusercontent.com/10966214/51438006-5cc96f80-1c74-11e9-8f50-79f1f885a244.png)

At the bottom right, there are these options which can be toggled, the first of which is `nc` and toggles between `kc`

**Comment by Avigd** [comment]
Hello Michael

 

Thanks for your response. When I look at the screen (see attached screenshot) I can not see the options/switches you show me. There is no nc toggle switch. I am using the latest version (V1.14.0).

Can you help ?

Many Thanks

**Comment by Avigd** [comment]
Hi

 

Did not hear from you.  Can you please send me the link to download the version which contain the options you refer in your email (i.e. toggle nc and kc) that can solve the loss of audio sync problem.  The version that I use does not have these options

 

Many Thanks

 

Avi  Peltz

 

From: Avi [mailto:apeltz2002@yahoo.com] 
Sent: Sunday, January 20, 2019 9:42 PM
To: 'mifi/lossless-cut'; 'mifi/lossless-cut'
Cc: 'Comment'
Subject: RE: [mifi/lossless-cut] Audio Going Out Of Sync In Long Vídeos (#75)

 

Hello Michael

 

Thanks for your response. When I look at the screen (see attached screenshot) I can not see the options/switches you show me. There is no nc toggle switch. I am using the latest version (V1.14.0).

Can you help ?

 

Many Thanks

**Comment by Avigd** [comment]
Hello All

Still waiting for help on the issue of audio sync loss when using the lossless-cut program. I am using V1.14.0 version. The answers I received above are not relevant because the screen I see does not the show the toggle options mentioned. I tried to send question directly to Mikael and he answered I should place my request on this website. Can anyone provide help? If there is another version which solves the problem please send me link to where I can download it.

Many Thanks

**Comment by mifi** [comment]
Maybe you can provide a screenshot with the problem @avigd

**Comment by Avigd** [comment]
![losseless_screenshot](https://user-images.githubusercontent.com/46861536/51892087-b5c09400-2355-11e9-891b-aaabbe0da2f8.jpg)
I attach the screenshot. This is version V1.14.0

**Comment by mifi** [comment]
No. this looks like a very old version. It even says "New version" in the menu

**Comment by mifi** [comment]
try 2.1.0

https://github.com/mifi/lossless-cut/releases

**Comment by Avigd** [comment]
Hi there.  
Thanks for the link. Looks like this version (2.10) is working well without loss of audio sync. Thank you so much for your support, How to donate?
P.S.  Is there a manual explaining all the functions of the lossless-cut tool
Thank You

**Comment by mifi** [comment]
closing this

**Comment by Libroru** [comment]
Hey There!
So I am working together with a content creator and we're using Losslesscut to cut down long VODs.
Now, we're getting the same issue like above.
If you play the file inside of VLC or any other media player it works fine and looks good,
but when you import it into any editing software like Vegas or Davinci Resolve, the audio and video shift by like 2 seconds every 5 minutes...

Using the newest version and exporting to mp4 with keyframe cut mode.

**Comment by mifi** [comment]
is there any pattern with the files you're cutting? does it happen when you cut at the beginning of the videos or also if you cut only the end? what about if you export without any cuts? still out of sync? how long are the files you're cutting?

**Comment by Libroru** [comment]
so what we've tried is to export all of the clips individually, which seemed to work. The issue only appeared if we exported the whole thing. The raw footage was about 4-6h long (I don't exactly know the length) and the cut down version was about 50 minutes long.

**Comment by mifi** [comment]
so it only happens when you cut+merge multiple segments?

**Comment by Libroru** [comment]
afaik yes

**Comment by mifi** [comment]
probably similar to #964

**Comment by Libroru** [comment]
We're using mp4 tho, so idk if that's directly related to that issue

**Comment by Github-Username-is-not-available** [comment]
Hi, I also have this issue!

The first part of the video I am using on Lossless-Cut runs OK, but some time into it, the audio gradually goes more & more out of sync! Please help!

(When I play the video on its own, it plays fine, & in-sync. It's only when playing in Lossless Cut that it goes out-of-sync.)

I also have no idea what the "nc" / "kc" icons are, as there's nothing like this displayed on my screen, & I'm using ver.3.43.0

**Comment by DavidOliver** [comment]
It looks like the keyframe cut mode option has moved to Settings (cog, top-right) > Options affecting exported files, and is enabled by default.

<img width="829" height="497" alt="Image" src="https://github.com/user-attachments/assets/5399343e-a60c-406f-9fb8-614f5452b1f0" />

**Comment by mifi** [comment]
The setting is also on the export confirmation page :)
