### ISSUE TITLE
how do I get the full playback control as shown in this screenshot?

### ISSUE THREAD

**Issue by mrjayviper** [mifi/lossless-cut#755]
as above.

https://raw.githubusercontent.com/mifi/lossless-cut/master/main_screenshot.jpg

I just installed the latest version and I "lost" the frame backward/forward control. This is the interface that I remember: https://www.videohelp.com/softwareimages/losslesscut_1667-2.jpg

Thanks

**Comment by mrjayviper** [comment]
> Hi. It looks like you are running a very old version? can you confirm for me that yo uhave the newest version?

Running 4.8.6 (which is not ancient imho)

I’m saying that I don’t think any changes have been made to this file since 2019. 😁

**Comment by mifi** [comment]
I dont know what is scoop but you can find the latest version here  https://github.com/mifi/lossless-cut/releases/tag/v3.36.0

**Comment by mrjayviper** [comment]
so I downloaded the latest version as provided in the releases page and I still cannot get the same controls like in the screenshot (https://raw.githubusercontent.com/mifi/lossless-cut/master/main_screenshot.jpg)

[click here for screenshot](https://i.imgur.com/2fk9TCb.png)

**Comment by Shakil-Shahadat** [comment]
Click on the bottom left button, the button that looks like a baby.

**Comment by mifi** [comment]
![](https://media.giphy.com/media/a0h7sAqON67nO/giphy.gif)
