### ISSUE TITLE
MKV FrameCount metadata not updated

### ISSUE THREAD

**Issue by karussellbremser** [mifi/lossless-cut#756]
When cutting some seconds from the beginning of an MKV file, the resulting cut file has the same value of the MKV FrameCount variable as the original file (as verified with MediaInfo). I believe that it should have been reduced by the number of cut frames?! The "Duration" parameter correctly reflects the shorter runtime. Using latest Lossless Cut 3.36.0 on Windows 10.

MediaInfo general and video portions (I blanked the some irrelevant values):

Original:
`"track": [
{
"@type": "General",
"UniqueID": ----,
"VideoCount": "1",
"AudioCount": "1",
"MenuCount": "1",
"FileExtension": "mkv",
"Format": "Matroska",
"Format_Version": "4",
"FileSize": "14503321545",
"Duration": "5960.299",
"OverallBitRate_Mode": "VBR",
"OverallBitRate": "19466569",
"FrameRate": "23.976",
"FrameCount": "142904",
"StreamSize": "2289020",
"IsStreamable": "Yes",
"Title": ----,
"Movie": ----,
"Encoded_Date": ----,
"File_Created_Date": ----,
"File_Created_Date_Local": ----,
"File_Modified_Date": ----,
"File_Modified_Date_Local": ----,
"Encoded_Application": "mkvmerge v42.0.0 ('Overtime') 64-bit",
"Encoded_Library": "libebml v1.3.10 + libmatroska v1.5.2"
},
{
"@type": "Video",
"StreamOrder": "0",
"ID": "1",
"UniqueID": ----,
"Format": "AVC",
"Format_Profile": "High",
"Format_Level": "4.1",
"Format_Settings_CABAC": "Yes",
"Format_Settings_RefFrames": "3",
"Format_Settings_GOP": "M=3, N=12",
"CodecID": "V_MPEG4/ISO/AVC",
"Duration": "5960.288000000",
"BitRate_Mode": "VBR",
"BitRate": "17902528",
"BitRate_Maximum": "32294400",
"Width": "1920",
"Height": "1080",
"Stored_Height": "1088",
"Sampled_Width": "1920",
"Sampled_Height": "1080",
"PixelAspectRatio": "1.000",
"DisplayAspectRatio": "1.778",
"FrameRate_Mode": "CFR",
"FrameRate": "23.976",
"FrameCount": "142904",
"Standard": "NTSC",
"ColorSpace": "YUV",
"ChromaSubsampling": "4:2:0",
"BitDepth": "8",
"ScanType": "Progressive",
"Delay": "0.000",
"StreamSize": "13338028481",
"Language": "en",
"Default": "Yes",
"Forced": "No",
"BufferSize": "29999616",
"colour_description_present": "Yes",
"colour_description_present_Source": "Stream",
"colour_range": "Limited",
"colour_range_Source": "Stream",
"colour_primaries": "BT.709",
"colour_primaries_Source": "Stream",
"transfer_characteristics": "BT.709",
"transfer_characteristics_Source": "Stream",
"matrix_coefficients": "BT.709",
"matrix_coefficients_Source": "Stream"
},`

after cutting:
`"track": [
{
"@type": "General",
"UniqueID": ----,
"VideoCount": "1",
"AudioCount": "1",
"MenuCount": "1",
"FileExtension": "mkv",
"Format": "Matroska",
"Format_Version": "4",
"FileSize": "14503827608",
"Duration": "5949.829",
"OverallBitRate_Mode": "VBR",
"OverallBitRate": "19501505",
"FrameRate": "24.000",
"FrameCount": "142904",
"StreamSize": "2795083",
"IsStreamable": "Yes",
"Title": ----,
"Movie": ----,
"Encoded_Date": ----,
"File_Created_Date": ----,
"File_Created_Date_Local": ----,
"File_Modified_Date": ----,
"File_Modified_Date_Local": ----,
"Encoded_Application": "Lavf58.45.100",
"Encoded_Library": "Lavf58.45.100",
"extra": {
"ErrorDetectionType": "Per level 1"
}
},
{
"@type": "Video",
"StreamOrder": "0",
"ID": "1",
"UniqueID": ----,
"Format": "AVC",
"Format_Profile": "High",
"Format_Level": "4.1",
"Format_Settings_CABAC": "Yes",
"Format_Settings_RefFrames": "4",
"CodecID": "V_MPEG4/ISO/AVC",
"Duration": "5949.819000000",
"BitRate_Mode": "VBR",
"BitRate": "17902528",
"BitRate_Maximum": "37499904",
"Width": "1920",
"Height": "1080",
"Stored_Height": "1088",
"Sampled_Width": "1920",
"Sampled_Height": "1080",
"PixelAspectRatio": "1.000",
"DisplayAspectRatio": "1.778",
"FrameRate_Mode": "VFR",
"FrameRate": "24.000",
"FrameRate_Original": "23.976",
"FrameCount": "142904",
"ColorSpace": "YUV",
"ChromaSubsampling": "4:2:0",
"BitDepth": "8",
"ScanType": "Progressive",
"Delay": "0.042",
"StreamSize": "13338028481",
"Language": "en",
"Default": "Yes",
"Forced": "No",
"BufferSize": "30000000 / 30000000",
"colour_description_present": "Yes",
"colour_description_present_Source": "Container",
"colour_range": "Limited",
"colour_range_Source": "Container",
"colour_primaries": "BT.709",
"colour_primaries_Source": "Container",
"transfer_characteristics": "BT.709",
"transfer_characteristics_Source": "Container",
"matrix_coefficients": "BT.709",
"matrix_coefficients_Source": "Container"
},`

**Comment by karussellbremser** [comment]
This also applies to the audio streams btw. See MediaInfo output with audio streams included in issue 758.

**Comment by mifi** [comment]
I believe this is an issue with ffmpeg. not much I can do about it. you could try to disable some streams(tracks) and see if it helps

**Comment by OnyxStreaming** [comment]
hey @mifi, i dont think its to do with ffmpeg as i have had the same problem, i have encoded with ffmpeg to start then  used this software to trim the end point. 
how ever i may be wrong and if so hopefully ffmpeg can sort it :)

**Comment by mifi** [comment]
if you want you can try to to take the ffmpeg command `LAST FFMPEG COMMANDS` atthe botttom of "help" and copy it to the command line, and then you can experiment with a newer ffmpeg version and see if it helps

**Comment by mifi** [comment]
See also #1027

**Comment by mifi** [comment]
i'm closing this to keep issue count down, will be tracked in #756
