### ISSUE TITLE
MKV Delays introduced

### ISSUE THREAD

**Issue by karussellbremser** [mifi/lossless-cut#758]
When cutting some seconds from the beginning of an MKV file, the resulting cut file has delays introduced to the video and audio streams (with slightly different values for each). I am not sure if this is a bug, but to my understanding, when cutting at keyframes, an introduced delay should be unnecessary as the result file should be in sync automatically. Using latest Lossless Cut 3.36.0 on Windows 10.

MediaInfo general and video portions (I blanked the some irrelevant values):

Original:
`"track": [
{
"@type": "General",
"UniqueID": ----,
"VideoCount": "1",
"AudioCount": "1",
"MenuCount": "1",
"FileExtension": "mkv",
"Format": "Matroska",
"Format_Version": "4",
"FileSize": "14503321545",
"Duration": "5960.299",
"OverallBitRate_Mode": "VBR",
"OverallBitRate": "19466569",
"FrameRate": "23.976",
"FrameCount": "142904",
"StreamSize": "2289020",
"IsStreamable": "Yes",
"Title": ----,
"Movie": ----,
"Encoded_Date": ----,
"File_Created_Date": ----,
"File_Created_Date_Local": ----,
"File_Modified_Date": ----,
"File_Modified_Date_Local": ----,
"Encoded_Application": "mkvmerge v42.0.0 ('Overtime') 64-bit",
"Encoded_Library": "libebml v1.3.10 + libmatroska v1.5.2"
},
{
"@type": "Video",
"StreamOrder": "0",
"ID": "1",
"UniqueID": ----,
"Format": "AVC",
"Format_Profile": "High",
"Format_Level": "4.1",
"Format_Settings_CABAC": "Yes",
"Format_Settings_RefFrames": "3",
"Format_Settings_GOP": "M=3, N=12",
"CodecID": "V_MPEG4/ISO/AVC",
"Duration": "5960.288000000",
"BitRate_Mode": "VBR",
"BitRate": "17902528",
"BitRate_Maximum": "32294400",
"Width": "1920",
"Height": "1080",
"Stored_Height": "1088",
"Sampled_Width": "1920",
"Sampled_Height": "1080",
"PixelAspectRatio": "1.000",
"DisplayAspectRatio": "1.778",
"FrameRate_Mode": "CFR",
"FrameRate": "23.976",
"FrameCount": "142904",
"Standard": "NTSC",
"ColorSpace": "YUV",
"ChromaSubsampling": "4:2:0",
"BitDepth": "8",
"ScanType": "Progressive",
"Delay": "0.000",
"StreamSize": "13338028481",
"Language": "en",
"Default": "Yes",
"Forced": "No",
"BufferSize": "29999616",
"colour_description_present": "Yes",
"colour_description_present_Source": "Stream",
"colour_range": "Limited",
"colour_range_Source": "Stream",
"colour_primaries": "BT.709",
"colour_primaries_Source": "Stream",
"transfer_characteristics": "BT.709",
"transfer_characteristics_Source": "Stream",
"matrix_coefficients": "BT.709",
"matrix_coefficients_Source": "Stream"
},
{
"@type": "Audio",
"StreamOrder": "1",
"ID": "2",
"UniqueID": ----,
"Format": "DTS",
"Format_Commercial_IfAny": "DTS-HD Master Audio",
"Format_Settings_Mode": "16",
"Format_Settings_Endianness": "Big",
"Format_AdditionalFeatures": "XLL",
"CodecID": "A_DTS",
"Duration": "5960.299000000",
"BitRate_Mode": "VBR",
"BitRate": "1561000",
"Channels": "2",
"ChannelPositions": "Front: L R",
"ChannelLayout": "L R",
"SamplesPerFrame": "512",
"SamplingRate": "48000",
"SamplingCount": "286094352",
"FrameRate": "93.750",
"FrameCount": "558778",
"BitDepth": "16",
"Compression_Mode": "Lossless",
"Delay": "0.000",
"Delay_Source": "Container",
"StreamSize": "1163004044",
"StreamSize_Proportion": "0.08019",
"Language": "en",
"Default": "Yes",
"Forced": "No"
},`

after cutting:
`"track": [
{
"@type": "General",
"UniqueID": ----,
"VideoCount": "1",
"AudioCount": "1",
"MenuCount": "1",
"FileExtension": "mkv",
"Format": "Matroska",
"Format_Version": "4",
"FileSize": "14503827608",
"Duration": "5949.829",
"OverallBitRate_Mode": "VBR",
"OverallBitRate": "19501505",
"FrameRate": "24.000",
"FrameCount": "142904",
"StreamSize": "2795083",
"IsStreamable": "Yes",
"Title": ----,
"Movie": ----,
"Encoded_Date": ----,
"File_Created_Date": ----,
"File_Created_Date_Local": ----,
"File_Modified_Date": ----,
"File_Modified_Date_Local": ----,
"Encoded_Application": "Lavf58.45.100",
"Encoded_Library": "Lavf58.45.100",
"extra": {
"ErrorDetectionType": "Per level 1"
}
},
{
"@type": "Video",
"StreamOrder": "0",
"ID": "1",
"UniqueID": ----,
"Format": "AVC",
"Format_Profile": "High",
"Format_Level": "4.1",
"Format_Settings_CABAC": "Yes",
"Format_Settings_RefFrames": "4",
"CodecID": "V_MPEG4/ISO/AVC",
"Duration": "5949.819000000",
"BitRate_Mode": "VBR",
"BitRate": "17902528",
"BitRate_Maximum": "37499904",
"Width": "1920",
"Height": "1080",
"Stored_Height": "1088",
"Sampled_Width": "1920",
"Sampled_Height": "1080",
"PixelAspectRatio": "1.000",
"DisplayAspectRatio": "1.778",
"FrameRate_Mode": "VFR",
"FrameRate": "24.000",
"FrameRate_Original": "23.976",
"FrameCount": "142904",
"ColorSpace": "YUV",
"ChromaSubsampling": "4:2:0",
"BitDepth": "8",
"ScanType": "Progressive",
"Delay": "0.042",
"StreamSize": "13338028481",
"Language": "en",
"Default": "Yes",
"Forced": "No",
"BufferSize": "30000000 / 30000000",
"colour_description_present": "Yes",
"colour_description_present_Source": "Container",
"colour_range": "Limited",
"colour_range_Source": "Container",
"colour_primaries": "BT.709",
"colour_primaries_Source": "Container",
"transfer_characteristics": "BT.709",
"transfer_characteristics_Source": "Container",
"matrix_coefficients": "BT.709",
"matrix_coefficients_Source": "Container"
},
{
"@type": "Audio",
"StreamOrder": "1",
"ID": "2",
"UniqueID": ----,
"Format": "DTS",
"Format_Commercial_IfAny": "DTS-HD Master Audio",
"Format_Settings_Mode": "16",
"Format_Settings_Endianness": "Big",
"Format_AdditionalFeatures": "XLL",
"CodecID": "A_DTS",
"Duration": "5949.829000000",
"BitRate_Mode": "VBR",
"BitRate": "1561000",
"Channels": "2",
"ChannelPositions": "Front: L R",
"ChannelLayout": "L R",
"SamplesPerFrame": "512",
"SamplingRate": "48000",
"SamplingCount": "285591792",
"FrameRate": "93.750",
"FrameCount": "558778",
"BitDepth": "16",
"Compression_Mode": "Lossless",
"Delay": "0.049",
"Delay_Source": "Container",
"StreamSize": "1163004044",
"StreamSize_Proportion": "0.08019",
"Language": "en",
"Default": "Yes",
"Forced": "No"
},`

**Comment by mifi** [comment]
does the Shift timestamps (avoid_negative_ts) option make a difference? if not, then not much I can do about this, as ffmpeg is doing all this.
