### ISSUE TITLE
Image Update moving cursor incredibly slow in 3.36

### ISSUE THREAD

**Issue by umbertones** [mifi/lossless-cut#759]
**Describe the bug**
When moving the cursor the image update took less than a second in 3.34. In 3.36 it takes 15-20 seconds on the same machine

**To Reproduce**
Open a file
Jump (STRG + Right)
Wait, wait, wait....top shows high ffmpeg cpu load.

**Expected behavior**
Open a file
Jump (STRG + Right)
Check Image, jump further...

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.04, I use the AppImage.
 -  Lenovo Thinkpad T460

**Additional context**
Tried some avi-Files (the same format I always get from my Linux VDR) and they were all slow in 3.3.6
Update: I reverted to 3.34-AppImage losslesscut is slow as well. Must be an issue with ffmpeg, I have version 4.2.4-1ubuntu0.1

**Comment by mifi** [comment]
Thanks for your detailed report. AVI files are not natively supported, however it's odd that it should take that long. Could you confirm that other files work fine? like mp4/h264 or webm. Is it slow with any version of losslesscut? maybe you can share a file with this problem

**Comment by umbertones** [comment]
Thanks for your infos. It's even weirder now. I downgraded to 3.34, had one or two upates (normal ubuntu stuff) and losslesscut behaved normal....But: it is still the same ffmpeg version?!? I have no idea. Next step will be to switch to 3.36 again and check that. I'll report.

**Comment by umbertones** [comment]
Ok, I put up 3.36 and cutted a movie. This worked fine as well. Sorry for the buzz.
