### ISSUE TITLE
No sound on preview of MKV today, but it was fine yesterday

### ISSUE THREAD

**Issue by SuperSaiyanMusashi** [mifi/lossless-cut#760]
**Describe the bug**
Yesterday, I loaded a MKV file and everything worked fine.  Today, I go to cut a new segment from the same MKV file and I get no sound on the preview.  Sound for this video plays when viewed in other programs.

**To Reproduce**
I open Losslesscut, load the MKV.  

**Expected behavior**
I was expecting to be able to hear the sound in Losslessvut's preview plane

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10

file I was editing is 33GB so I can't provide it here.  The same problem happens with the 15 second clip I took from the big one, and that clip, which is also MKV and has all the same audio tracks can be provided by request.  It's 66 MB so I wasn't sure if I should include it.

**Comment by Shakil-Shahadat** [comment]
Did you try to convert it to a supported format from the `File` menu?

**Comment by SuperSaiyanMusashi** [comment]
Just tried that on the smaller clip; it made a preview I could hear.  I will try it with the full movie tomorrow and see if I can still make full quality clips.  I'm still disturbed that it worked perfectly yesterday but has problems today when, as far as I could tell, not a single byte of data on the movie file or the program was changed.

**Comment by SuperSaiyanMusashi** [comment]
Well, it got me an audible preview but now it's refusing to export my 5-10 second segments.  It hangs at 99.9% for far too long, or 33.3% if I try to Export multiple segments at once.  This too, was not a problem when I tried LossLessCut on Thursday.  Did I accidentally trip a setting somewhere that disabled the program?  What do I have to do to get it working beautifully again?

**Comment by mifi** [comment]
It's hard to say what happened with your freeze, but it might have been something that changed in a windows update or anitvirus or similar. if possible try on a different computer and see if you have the same problem. Or you could try to delete the AppData/Roaming folder for losslesscut (note you will loose all settings)

**Comment by mifi** [comment]
I'll reopen if you have some more info.

**Comment by Neurotoxin001** [comment]
There is still no sound with mkv files if it have more than 1 audio track...

Windows 10 / LC 3.58

![image](https://github.com/mifi/lossless-cut/assets/39812401/68d8503b-f1b4-45fe-be0c-466e870c762e)

**Comment by Neurotoxin001** [comment]
I can't test it because I don't have mkv file with 1 track. It's only my guess.

**Comment by mifi** [comment]
what if you used losslesscut to disalbe all tracks except 1 eac3 track and one h264 track, then export? then you have a file with only 1 eac3 track

**Comment by Neurotoxin001** [comment]
Still no sound
![image](https://github.com/mifi/lossless-cut/assets/39812401/f87c5bb7-ad4d-473f-ae41-82f151a36cce)

**Comment by mifi** [comment]
probably the html5 video player doesn't support eac3 audio codec. maybe you can File -> convert to supported format to get audio

**Comment by Neurotoxin001** [comment]
Now I hear the sound but it's broken after I cut that I want and export

![image](https://github.com/mifi/lossless-cut/assets/39812401/c20cd908-a0b8-428e-b413-6c872ae6580d)

https://user-images.githubusercontent.com/39812401/276971680-870f0440-b391-4085-b4ea-3fa8fe46f6fb.mp4

**Comment by mifi** [comment]
see https://github.com/mifi/lossless-cut/blob/master/issues.md#common--known-issues--troubleshooting
