### ISSUE TITLE
Can't Export Segment

### ISSUE THREAD

**Issue by SuperSaiyanMusashi** [mifi/lossless-cut#762]
**Share information to help me understand**
outSegTemplateOrDefault CaptainAmericaSegment
main.356c3555.chunk.js:1 customTagsByFile {}
main.356c3555.chunk.js:1 customTagsByStreamId {}
main.356c3555.chunk.js:1 Exporting from 353.052247 to 363.147763
main.356c3555.chunk.js:1 ffmpeg -hide_banner -ss '353.05225' -i 'D:\Videos\MCU Films\Captain America The First Avenger\Captain America The First Avenger_t00.mkv' -t '10.09552' -avoid_negative_ts make_zero -c copy -map '0:0' -map '0:1' -map '0:2' -map '0:3' -map '0:4' -map '0:5' -map '0:6' -map '0:7' -map '0:8' -map '0:9' -map '0:10' -map '0:11' -map '0:12' -map '0:13' -map '0:14' -map '0:15' -map '0:16' -map_metadata 0 -movflags '+faststart' -ignore_unknown -f matroska -y 'D:\Videos\MCU Films\Captain America The First Avenger\CaptainAmericaSegment'

After that: nothing

**Describe the bug**
Program shows 'Exporting 99.9%' but never finishes or produces clip.

**To Reproduce**
1. Open video
2. Click on Include Only Segment 2
3. Press Export, set filename, press Export again to start

**Expected behavior**
I expected it to produce a 10 second clip from the movie as an MKV file.

**Screenshots**
![image](https://user-images.githubusercontent.com/84951399/120058021-b052e180-c015-11eb-897d-64c69d6ea6be.png)

**Desktop (please complete the following information):**
Windows 10

**Additional context**
Exporting worked fine the first day I tried LossLessCut.  Today it doesn't work at all.

**Comment by SuperSaiyanMusashi** [comment]
Update: I went to one of my clips I made earlier and removed the compatible preview.  I was able to export a segment from that one  However, without the compatible preview, there's no sound in the editor making it difficult to find which parts I want to fish out.

**Comment by mifi** [comment]
That's odd. does the file get created and is it usable? If not, then I would think this is an issue with ffmpeg hanging forever and never completing. What you could try is to disable all tracks except vidoe adn then selectively enable tracks until it freezes, and see which track may be causing it

**Comment by SuperSaiyanMusashi** [comment]
I will try that experiment with my next project

**Comment by mifi** [comment]
Closing due to lack of response. If you can reproduce i can reopen
