### ISSUE TITLE
Strange error just when launching

### ISSUE THREAD

**Issue by RafaelLinux** [mifi/lossless-cut#763]
AppImage Version 3.36.0

**Describe the bug**
Just I try to launch LossLessCut from GUI and it fails to appear, showing a windows with "Unhandled Promise Rejection
Error: Timed out while creating config store
    at Object.init (/tmp/.mount_Losslemtijyl/resources/app.asar/build/configStore.js:75:9)
    at async App.<anonymous> (/tmp/.mount_Losslemtijyl/resources/app.asar/build/electron.js:83:3)"

**To Reproduce**
1. Click on "LossLessCut.AppImage"

**Expected behavior**
To open LossLessCut

**Desktop (please complete the following information):**
 - OS: openSUSE 15.2 Plasma

**Comment by mifi** [comment]
Hi. thanks for your report. could you open developer tools log console if there are any more errors?

**Comment by RafaelLinux** [comment]
I was trying to reproduce issue (3.36.0) but it seems now works like always, like a charm. Meanwhile, I did some updates to Plasma. Maybe it was related to Plasma, not sure about it. So, I'll close this issue cause is not reproducible again.

THANK YOU
