### ISSUE TITLE
The application should make it clearer how to perform a cut

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [mifi/lossless-cut#765]
Thank you for your software.

**Is your feature request related to a problem? Please describe.**
I am frustrated when I open the application, manage - just about - to work out how to make a cut to a video, and then do not know how to save the resulting file. Indeed at that stage I was unsure whether any sort of cut has been made. (I did work it out eventually.)

**Describe the solution you'd like**
The new user should be able to see fairly clearly - just by using the program, or at least by consulting the inbuilt help - how to make a cut and save the resulting (that is, the video-that-has-now-had-something-cut-out-of-it). A video cutting tool is apt to confuse, because the video in question may well show a computer desktop; so it really behoves the application to have a good, intuitive interface.

I could do without the UI animations too: if one is confused already, having windows bounce around does not help.

**Additional context**
Losssless-cut version 3.22.3
Windows 10

**Comment by mifi** [comment]
Thanks for your feedback. I'm having trouble finding something actionable, but you can suggest improvements to the UI here #189
