### ISSUE TITLE
cannot build on raspbian armhf

### ISSUE THREAD

**Issue by mbodomi** [mifi/lossless-cut#767]
<pre><span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> Unexpected platform or architecture: linux/arm
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> It seems there is no binary available for your platform/architecture
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> Try to install PhantomJS globally
</pre>

**Comment by mbodomi** [comment]
`sudo apt install phantomjs -y` seems to solve it

**Comment by mbodomi** [comment]
I mean I can run it but:
<pre>&gt; lossless-cut@3.36.0 pack-linux /home/pi/lossless-cut
&gt; electron-builder --linux

  <font color="#0000AA">\u00e2\u02d8</font> electron-builder  <font color="#0000AA">version</font>=22.10.4 <font color="#0000AA">os</font>=5.10.17-v7l+
  <font color="#0000AA">\u00e2\u02d8</font> loaded configuration  <font color="#0000AA">file</font>=package.json (&quot;build&quot; field)
  <font color="#0000AA">\u00e2\u02d8</font> loaded parent configuration  <font color="#0000AA">preset</font>=react-cra
  <font color="#0000AA">\u00e2\u02d8</font> writing effective config  <font color="#0000AA">file</font>=dist/builder-effective-config.yaml
  <font color="#AA0000">\u00e2\u00a8\u017b</font> <font color="#AA0000">Unsupported arch arm</font>  <font color="#AA0000">stackTrace</font>=
                            Error: Unsupported arch arm
                                at archFromString (/home/pi/lossless-cut/node_modules/builder-util/src/arch.ts:44:13)
                                at computeArchToTargetNamesMap (/home/pi/lossless-cut/node_modules/app-builder-lib/src/targets/targetFactory.ts:30:24)
                                at Packager.doBuild (/home/pi/lossless-cut/node_modules/app-builder-lib/src/packager.ts:425:41)
                                at Packager._build (/home/pi/lossless-cut/node_modules/app-builder-lib/src/packager.ts:369:57)
                                at Packager.build (/home/pi/lossless-cut/node_modules/app-builder-lib/src/packager.ts:333:12)
                                at executeFinally (/home/pi/lossless-cut/node_modules/builder-util/src/promise.ts:12:14)
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">code</font> ELIFECYCLE
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">errno</font> 1
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> lossless-cut@3.36.0 pack-linux: `electron-builder --linux`
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> Exit status 1
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> 
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> Failed at the lossless-cut@3.36.0 pack-linux script.
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> This is probably not a problem with npm. There is likely additional logging output above.

<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> A complete log of this run can be found in:
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span>     /home/pi/.npm/_logs/2021-06-13T02_58_22_936Z-debug.log
</pre>

**Comment by mifi** [comment]
Did you try this? https://github.com/electron-userland/electron-builder/issues/4279
Anyhow losslesscut will not work out of the box because it bundles its own ffmpeg (but not for arm)

**Comment by mifi** [comment]
closing as stale
