### ISSUE TITLE
Allow seeking frame by frame

### ISSUE THREAD

**Issue by jonathancolledge** [mifi/lossless-cut#768]
Please first search for your feature request under Issues or Discussions, maybe someone else already suggested it.
I have found some that seem to be related, but don't seem to be this specific.

**Is your feature request related to a problem? Please describe.**

I have altered the Timeline keyboard seek speed in settings down to 0.1, but instead of being able to move frame by frame, it moves three frames when I press an arrow key (it won't let me set it lower than 0.1). For Timeline trackpad/wheel sensitivity it lets me set it to 0.01, but actually, that skips more frames.

**Describe the solution you'd like**
Please allow seeking frame by frame. 

**Describe alternatives you've considered**
I can't think of an alternative

**Additional context**
I'm trying to cut precisely

**Comment by Shakil-Shahadat** [comment]
You need to use `,` & `.` to seek frame by frame. There are also buttons in UI right beside the play button that can do that.

Regarding precise cut, see pinned issue #126.

**Comment by jonathancolledge** [comment]
Oh, perfect. Though I'm using ProRes and with keyframe cut, it cuts precisely but adds extra time to the beginning and the end (with no associated frames), so the first frame is at 0.012 and the last frame is 0.034 seconds before the timestamps finish, but there are no frames that are visible beyond the last frame, which is, 0.034 seconds before the video ends. Do I need to open another issue, or is that ok here? Normal cut just hangs the whole thing.

**Comment by jonathancolledge** [comment]
Ignore that last one - this a problem with the input file and Ffmpeg.
