### ISSUE TITLE
Allow "Label segment" window to be movable

### ISSUE THREAD

**Issue by hdt551** [mifi/lossless-cut#772]
When applying a label to a segment, the window where you enter the label name covers the center of the picture.  It would be nice if it could be moved around.

**Comment by mifi** [comment]
I think I'm not going to implement this, unfortunately. Alternatively you can request this feature at https://github.com/sweetalert2/sweetalert2/ (which is the "window" component that losslesscut uses).
If they decide it's a good idea to implement movable dialogs, then we can add it here also.
