### ISSUE TITLE
How can I interrupt an export (that is taking a long time)?

### ISSUE THREAD

**Issue by fuhrmanator** [mifi/lossless-cut#775]
**Describe the bug**
An export is taking a very long time (more than 20 mins) and I would like to cancel it. There are no buttons (obvious to me) to allow this. I can (probably) kill the process, but I don't want to lose the marker of the trimmed video.

**To Reproduce**
1. Start an export that takes a long time...
2. Try to "cancel" it
3. There is no (obvious) button

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by mifi** [comment]
currently not possible unfortuately. you need to close the app. I'm not sure what you mean by "I don't want to lose the marker of the trimmed video."

The selected cutpoints should still be there after reopening the file.

**Comment by fuhrmanator** [comment]
Indeed they were. I wrote the issue before actually killing the process.

**Comment by mifi** [comment]
dup of #524
