### ISSUE TITLE
LosslessCut icon showing pixelated

### ISSUE THREAD

**Issue by xmha97** [mifi/lossless-cut#778]
# Issue
LosslessCut icon showing pixelated on the start menu and taskbar:
![Start Menu](https://user-images.githubusercontent.com/23485114/125055936-f8f1c600-e0bc-11eb-9fc2-925deec7e514.png)
For a better understanding, you can compare it to the ProtonVPN icon.
# Solution
You should make more icons with different sizes (`16x16`,`24x24`,`32x32`,`48x48`):
![Resource Hacker](https://user-images.githubusercontent.com/23485114/125054378-60a71180-e0bb-11eb-8594-c893de940ea9.jpg)
I suggest using [Greenfish Icon Editor Pro](http://greenfishsoftware.org/gfie.php).
I make a better icon: [Icon.zip](https://github.com/mifi/lossless-cut/files/6790426/Icon.zip)

**Comment by mifi** [comment]
Is this issue on windows 10? the icon is in svg, and generated automatically on build, but there may be some possible improvements.
see this line: 
https://github.com/mifi/lossless-cut/blob/021a7257959b2af5d4020f86496616341dcac2a5/package.json#L11

**Comment by rubenalamina** [comment]
It should happen across Windows versions from 7 to 11 (can confirm 10 and 11 atm). I'm not familiar with the automated generation but you can probably set more sizes, the expected ones for Windows 16x16, 24x24, 32x32, 64x64, 128x128, 256x256 and 512x512. The current is probably getting distorted by the scaled down when not providing the other sizes.

**Comment by mifi** [comment]
Why can't windows just scale down in a sensible way like everyone else 😅 oh well. I have now updated the code so it will generate an .ico file that includes these sizes: `[16, 24, 32, 40, 48, 64, 96, 128, 256, 512]`, hopefully that will do it.

**Comment by Galaxoid-333** [comment]
I think the current icon design is not relevant for today and it is overloaded with detail, and it will always be pixelated at a small size.

**Comment by mifi** [comment]
what size are you talking about? can you show an example?
