### ISSUE TITLE
Mono audio of 4K video not processed?

### ISSUE THREAD

**Issue by marcelboere** [mifi/lossless-cut#78]
Dear developer(s) I noticed an error in Losless cut with a particular 4K video, mono AAC audio file format, coming from DJI Osmo. Cutting only leaves us with the video :(. here are the specs taken from MAGIX Vegas info:
Video: 00:04:06,840, 25,000 fps progressive, 3840x2160x12, AVC
Audio: 00:04:06,805, 48.000 Hz; Mono, AAC
https://www.dji.com/osmo
Might be me doing something wrong or might be problem with mono wav/AAC? File stored/recorded as MOV file by the way. But hey, thanks for this wonderful piece of sotware anyway!

**Comment by mifi** [comment]
Hi. Can you share a short video, or try cutting with ffmpeg directly from the command line?

**Comment by marcelboere** [comment]
Hi Mikael, thanks for your quick answer. I do not own the camera myself,
the footage with the error is too large and I am not allowed to share it. I
will try ffmeg first if that fails I will ask the owner of the camera to
send a 20 second clip I can send over to you. Which commands should I type
precisely in ffmpeg??
regards,
Marcel Boeré

**Comment by mifi** [comment]
you can try:
`ffmpeg -i osmo-input.mov -acodec copy -vcodec copy -scodec copy -ss 10 -t 20 -map_metadata 0 output.mp4`

also:
`ffmpeg -i osmo-input.mov -acodec copy -vcodec copy -scodec copy -ss 10 -t 20 -map_metadata 0 -map 0 output.mp4`

Also if it doesn't work you can try `output.mov` instead

and then print the output from that command and whether it also drops the audio. Download newest ffmpeg from their homepage

**Comment by marcelboere** [comment]
Thank you so much I will try out later!

**Comment by berts83231** [comment]
I'm also have issues with mono audio.

Sample #1 - lc-test-4.avi
Video Codec: H264 - MPEG-4 AVC (part 10) (H264)
Audio Codec: araw / Mono

Results (In App)
- Wont play video
- Convert to friendly format = stripped audio

Results (Command Line)

My-PC-ID:~/Downloads/Lossless-Cutter-Test/Test Videos$ ffmpeg -i lc-test-4.avi -acodec copy -vcodec copy -scodec copy -ss 10 -t 20 -map_metadata 0 lc-test-4-output.mp4
ffmpeg version 3.4.4-0ubuntu0.18.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
  configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Guessed Channel Layout for Input Stream #0.1 : mono
Input #0, avi, from 'lc-test-4.avi':
  Duration: 00:24:00.40, start: 0.000000, bitrate: 7765 kb/s
    Stream #0:0: Video: h264 (Baseline) (H264 / 0x34363248), yuv420p(progressive), 720x400, 7500 kb/s, 30 fps, 30 tbr, 30 tbn, 60 tbc
    Stream #0:1: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s
Output #0, mp4, to 'lc-test-4-output.mp4':
  Metadata:
    encoder         : Lavf57.83.100
    Stream #0:0: Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p(progressive), 720x400, q=2-31, 7500 kb/s, 30 fps, 30 tbr, 15360 tbn, 30 tbc
    Stream #0:1: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[mp4 @ 0x562641cecac0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
frame=  600 fps=0.0 q=-1.0 Lsize=   18951kB time=00:00:19.96 bitrate=7775.1kbits/s speed= 773x    
video:18310kB audio:625kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.084739%


/////////////////////////////////////////////////////////////////////////////////////////////////////////


My-PC-ID:~/Downloads/Lossless-Cutter-Test/Test Videos$ ffmpeg -i lc-test-4.avi -acodec copy -vcodec copy -scodec copy -ss 10 -t 20 -map_metadata 0 -map 0 lc-test-4-output-2.mp4
ffmpeg version 3.4.4-0ubuntu0.18.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
  configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Guessed Channel Layout for Input Stream #0.1 : mono
Input #0, avi, from 'lc-test-4.avi':
  Duration: 00:24:00.40, start: 0.000000, bitrate: 7765 kb/s
    Stream #0:0: Video: h264 (Baseline) (H264 / 0x34363248), yuv420p(progressive), 720x400, 7500 kb/s, 30 fps, 30 tbr, 30 tbn, 60 tbc
    Stream #0:1: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s
Output #0, mp4, to 'lc-test-4-output-2.mp4':
  Metadata:
    encoder         : Lavf57.83.100
    Stream #0:0: Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p(progressive), 720x400, q=2-31, 7500 kb/s, 30 fps, 30 tbr, 15360 tbn, 30 tbc
    Stream #0:1: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[mp4 @ 0x557dd97555e0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
frame=  600 fps=0.0 q=-1.0 Lsize=   18951kB time=00:00:19.96 bitrate=7775.1kbits/s speed= 743x    
video:18310kB audio:625kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.084739%

**Comment by mifi** [comment]
This is an issue with ffmpeg or the way we use it. Looks like WAV audio.

**Comment by mifi** [comment]
try again with v3. reopen if still an issue
