### ISSUE TITLE
Virus in Losslesscut? libEGL.dll?

### ISSUE THREAD

**Issue by Maverynthia** [mifi/lossless-cut#780]
Scanned Losslesscut.exe with ClamWin AV and this is what it gave me:
LosslessCut\libEGL.dll: Win.Packed.Fugrafa-9877665-0 FOUND
----------- SCAN SUMMARY -----------
Known viruses: 8545008
Engine version: 0.103.0
Scanned directories: 0
Scanned files: 1
Infected files: 1

What's this program doing?

**Comment by Ambush80** [comment]
It may be a false positive,  I have never found this personally
https://forums.malwarebytes.com/topic/236480-false-positive-spotify-libegldll/

**Comment by mifi** [comment]
Where did you download from ? github? I think definitely a false positive. libEGL.dll comes from electron which is used by hundres of apps and millions of people every day. If you want you can try to build losslesscut yourself locally and see if you get the same warning. I'm going to close this. can reopen if there are some more details.
