### ISSUE TITLE
Empty window (no toolbar, nothing) after starting on Win7

### ISSUE THREAD

**Issue by anodynesoftware** [mifi/lossless-cut#781]
I launched 3.36.0 from the Win7 64-bit desktop after downloading the ZIP and extracting all files to a directory. It appears to start, but all I see is a completely blank window, with just the standard windows gadgets at the top left & top right.

Launching from the CMD prompt, I get a load of error messages.  The first few are:
C:\Users\Roger\Downloads\LosslessCut-win>
[3856:0713/184327.991:ERROR:gl_utils.cc(316)] [.DisplayCompositor] GL_OUT_OF_MEMORY: Internal D3D9 error: HRESULT: 0x8007000E: LoadLibrary failed to load D3D Compiler DLL.
[3856:0713/184327.991:ERROR:gl_utils.cc(316)] [.DisplayCompositor] GL_OUT_OF_MEMORY: Context has been lost.
[3856:0713/184327.991:ERROR:gl_utils.cc(316)] [.DisplayCompositor] GL_OUT_OF_MEMORY: Context has been lost.

I suspect I am doing something obviously wrong, but have not a clue what that might be. I have lots of memory (6GB)

Attached is a screenshot.
![Capture-2](https://user-images.githubusercontent.com/17597453/125535255-c4d34bb3-4b48-4f31-af16-62164ce2f0ee.jpg)

**Comment by mifi** [comment]
that's odd! I have no idea whatsoever what's causing thing.
however a quick google finds this: https://github.com/electron/electron/issues/21500
can you try to run from the command line with the flag `--disable-gpu` ?

**Comment by anodynesoftware** [comment]
Thanks, that fixes the problem! Looking at your link, it seems that there's a problem with Win7 and the Electron framework. Anyway, this is a relatively painless workaround, so I'm closing this. Might be a good idea to add a comment to the install instructions.

**Comment by mifi** [comment]
thanks, willadd a note
