### ISSUE TITLE
losslesscut.svg in the .desktop file /usr/share/applications

### ISSUE THREAD

**Issue by arcolinuxz** [mifi/lossless-cut#784]
Not sure if the naming starts here or happens on ArchLinux

Please do not add the extension svg or png or jpg to any desktop file you create in /usr/share/applications

It will break the icon theme on Linux

thanks

**Comment by mifi** [comment]
You mean this file? https://github.com/mifi/lossless-cut/blob/master/no.mifi.losslesscut.desktop

I can't find any .svg there

**Comment by arcolinuxz** [comment]
And this is what we get on ArchLinux

```
[Desktop Entry]
Type=Application
Name=LosslessCut
Comment=GUI tool for lossless trimming/cutting of media files
Exec=losslesscut
Categories=AudioVideo;
Icon=losslesscut.svg
StartupWMClass=losslesscut
```


source : https://aur.archlinux.org/packages/losslesscut-bin/
maintainer : dmp1ce

Will you ask the maintainer to remove the .svg extension in this line?
`
Icon=losslesscut.svg`

**Comment by mifi** [comment]
I think this is not an issue with this repo, but with the arch linux package maintainers. please raise an issue there instead

**Comment by arcolinuxz** [comment]
I had hoped you would raise the issue there.
This issue can be closed here.
