### ISSUE TITLE
[Feature Request] Add a (De)select All option in the track menu 

### ISSUE THREAD

**Issue by Droyk** [mifi/lossless-cut#786]
![image](https://user-images.githubusercontent.com/15848350/126713446-0e829ff3-d54c-4f72-be21-8b07a7a8ae6b.png)
As you can see in the above image, if the video has too many tracks in them it takes too many mouse clicks to deselect what you don't want. so it would be really convenient if you can add [(De)select All] option on the top of the track menu.

- [ ] Select All
&
- [ ] Deselect All

**Comment by mifi** [comment]
thanks for your suggestion. I absolutely agree that this is needed. This is tracked in this issue #482, so I'll close this to avoid too many issues
