### ISSUE TITLE
Fix issues with sweetalert2 v11

### ISSUE THREAD

**Issue by mifi** [mifi/lossless-cut#789]
After upgrading to sweetalert2 in #785 and doing some testing, I noticed a few (potentially breaking) changes:

## overflow of content

Go to Tracks ,then click the "I" for one track and see that the content overflows the whole sweetalert container if too large, even though `overflow: auto` on the content.

This info box: https://github.com/mifi/lossless-cut/blob/a9bc6c555b410fbeb8bb65df2878d1c530591a54/src/StreamsSelector.jsx#L169

<img width="620" alt="Screenshot 2021-07-23 at 22 52 56" src="https://user-images.githubusercontent.com/402547/126810966-3605298e-7ec4-4d2d-8d25-ed0b21f844dd.png">

With sweetalert2 v10 it loks like this:

<img width="742" alt="Screenshot 2021-07-23 at 23 02 09" src="https://user-images.githubusercontent.com/402547/126810951-1fe05eb2-fb4e-44af-9a90-bb797b19b5d7.png">

Not sure how to best fix this, maybe you have some thoughts @limonte ?

## text invisible inside alert

text color for inputs (radio) in sweetalert2 now inherits from body. losslesscut has white body color, so the text now becomes invisible.

- [x] Not sure if it's the "correct" way to do it, but setting black text for swal2-container works:

```css
.swal2-container {
  color: black;
}
```

**Comment by limonte** [comment]
Sorry for missing those details @mifi! Both of them actually look like issues that should be fixed on the sweetalert2's side. I will check that right away.

**Comment by mifi** [comment]
Thanks, this is now resolved
