### ISSUE TITLE
DJI Mavic MOV

### ISSUE THREAD

**Issue by MOVmovMov** [mifi/lossless-cut#79]
Hi, 

After cutting I have a problem with import MOV files from DJI Mavic Pro to Adobe Premiere Pro or After Effects CC. If I use MP4 format from Mavic I dont have this problem. In Premiere its coming this message: The file has no audio or video streams.

**Comment by mifi** [comment]
does the file work with other players? can you try to cut using ffmpeg from the command line?

**Comment by MOVmovMov** [comment]
Yes its working in another players. Dont have a experience with command line. Adobe software accepted original files from DJI Mavic Pro.

**Comment by MOVmovMov** [comment]
Quicktime for win is dead. Adobe PP, AE ... for win have this container "inside". All software I have a last version. Your lossless-cut too.

**Comment by MOVmovMov** [comment]
Ok, something interesting now. One file its working after cutting. But now I was cutting the file in another time and "game over" its not possible import to the PP.

**Comment by MOVmovMov** [comment]
Ok, if I dont cut the file on the left side (from start) and cutting just on right side then I can import the file without problem.

**Comment by mifi** [comment]
So i don't think it's related to which format you are using, but rather the problem with cutting on keyframes. Right?

Then see discussion in #13 - we haven't solved this yet. It's about how ffmpeg does the cuts around keyframes

**Comment by MOVmovMov** [comment]
No, its just Quicktime, and if I cut the file on beginning.

**Comment by VuDuCiel** [comment]
Same issue here. This could really well be the PERFECT editor tool for me to trim drone shots in 4K at lightning speed. Unfortunely, Adobe editing software such as Premiere, After Effect and Media Encoder all fail at importing trimmed videos files from LosslessCut with the error "The file has no audio or video streams". As reported, files without a "head trim" trigger no error.

**Comment by mifi** [comment]
In the newest version 1.13.0 I've added a button to the leftmost of the right button row named **"nc"**. If you toggle this to **"kc"** - *keyframe cut* before doing the cut, then it will instead cut at the closest keyframe, and the output will not contain an empty portion at the beginning of the file. Can you try than and see if the output file works with Adobe tools now?

**Comment by VuDuCiel** [comment]
I just tested version 1.13.0 and I can confirm that the _keyframe cut_ option totally fixed every import errors from every Adobe software mentionned above!!! That is crazy!! I never expected such a rapid fix!!!!! This piece of software is truely an editor's dream!! Thank you so much for your work, there's nothing else as quick&easy as what you made.

**Comment by mifi** [comment]
Great, i will close this and then if @MOVmovMov still has issues he can reopen. In the future i plan on making this setting the default if it seems to work for people. See discussion in #13
