### ISSUE TITLE
450Mb for a video cut app? Enough already

### ISSUE THREAD

**Issue by azev** [mifi/lossless-cut#795]
RIP electron apps.
LOL one time I made a calculator on electron. 200Mb **only**.

I'm switching to avidemux:
http://avidemux.sourceforge.net/

**Comment by mifi** [comment]
Who cares. Please don't waste other people's time by creating such issues

**Comment by azev** [comment]
Stop wasting peoples bandwidth and disk space with your piece.

**Comment by Shakil-Shahadat** [comment]
@azev As none have forced you to use the app, you can't complain anything. Lossless Cut has its use cases whether you see it or not. This issue section is not for whining, thus your comments are utterly useless and completely unnecessary. So, please stop wasting your and other people's time.

**Comment by azev** [comment]
bite me
