### ISSUE TITLE
Ignore the "moov atom not found" error and assume the video have the same format as others.

### ISSUE THREAD

**Issue by NickDoom-IDKFA** [mifi/lossless-cut#796]
Shit happens, and with SD cards it happens too often :( Sometimes, file contain only the data streams, but moov atom is lost because of sudden camera shutdown.
Can you help and add a feature allowing to ignore this error and append those streams anyway? Or "try to append" (to be more accurate). With the same camera settings, those damaged videos probably have the same settings as others, so the moov atom is probably not necessary.

**Comment by mifi** [comment]
This seems like a very narrow use case. Maybe you can use untrunc to repair the files first, then open them in losslesscut. I used it before to repair files with missing moov with success. See https://superuser.com/questions/417100/how-to-open-and-repair-an-m4v-or-mp4-video-file

**Comment by johnss** [comment]
If you want to prevent this, use MKV instead of MP4, MKV do not have moov atom.
