### ISSUE TITLE
Request to introduce an EXIT option under "File-menu".

### ISSUE THREAD

**Issue by saurabhdua82** [mifi/lossless-cut#80]
Hi there!

Using the latest version of this app (32-bit) on my Win 7 Ultimate notebook PC environment.
Why isn't there a EXIT option under its File-menu ??

Similarly, under - 'Help' menu we would like to see an - "About" option as well !

Where are its 'Settings' to permanently customise the >> Output folder ???

Help address all these aspects towards your next release.

Thank you.

**Comment by mifi** [comment]
> Why isn't there a EXIT option under its File-menu ??

ok i fixed in c6a7560

> Similarly, under - 'Help' menu we would like to see an - "About" option as well !

Why do we need an about option? it currently links to github under "learn more"

> Where are its 'Settings' to permanently customise the >> Output folder ???

We could implement a remembering of confi values yes. See #72
