### ISSUE TITLE
Requesting some enhancements if possible

### ISSUE THREAD

**Issue by Rubens10010** [mifi/lossless-cut#802]
Hello, I would like to present some features and improvements that I think are convenient to do:

1.- P: Notifications when taking snapshots are taking too long to close (13000 by default)
     S: Possibility to adjust notifications time on settings or completely disable them when user checks `Hide informational notifications?`

2.- P: Zoom In and Zoom Out
     S: I always tought bottom's zoom menu was to actually zoom video preview but it turns out it was to zoom into timeline.

3.- P: Taking snapshots with current rotation.
     S: when rotation is set other than default I take snapshots but images are not rotated. I looked into the code and find out you're using a Canvas template to show rotation's preview on top of player's preview, which causes snapshots not to take current rotation. This also causes sluggishness on timeline and visualization.

I hope you consider this and illustrate me if there are technical details I don't know which won't allow them to be implemented on the near future. Thanks.

**Comment by mifi** [comment]
> 1.- P: Notifications when taking snapshots are taking too long to close (13000 by default)
> S: Possibility to adjust notifications time on settings or completely disable them when user checks `Hide informational notifications?`

Thanks. I have now fixed this.

> 2.- P: Zoom In and Zoom Out
> S: I always tought bottom's zoom menu was to actually zoom video preview but it turns out it was to zoom into timeline.

See #779

> 3.- P: Taking snapshots with current rotation.
> S: when rotation is set other than default I take snapshots but images are not rotated. I looked into the code and find out you're using a Canvas template to show rotation's preview on top of player's preview, which causes snapshots not to take current rotation. This also causes sluggishness on timeline and visualization.

Created a new feature request for this: #823

Closing this, can continue discussion in respective issues
