### ISSUE TITLE
MP4: Unable to playback this file

### ISSUE THREAD

**Issue by mdmred** [mifi/lossless-cut#804]
**Describe the bug**
Unable to playback a MP4 file, made with sony camera. File format detected as `mp4 - MP4 (MPEG-4 Part 14)`. Issue relevant for all the unprocessed files from the camera. Other, previously edited files work fine. Error message:
`Unable to playback this file. Try to convert to supported format from the menu`

**To Reproduce**
1. Open file '...'
2. Developer tools shows `PIPELINE_ERROR_DECODE` right away
3. Try starting playback at various timestamps 
3. See error

**Expected behavior**
File playback works

**Output from the javascript Console**
```Version 3.37.0
main.8a3a7c71.chunk.js:1 userOpenFiles
main.8a3a7c71.chunk.js:1 ../C0007.MP4
main.8a3a7c71.chunk.js:1 Load Object
main.8a3a7c71.chunk.js:1 getFormatData ../C0007.MP4
main.8a3a7c71.chunk.js:1 ffprobe -of json -show_format -i '../C0007.MP4'
main.8a3a7c71.chunk.js:1 formats mov,mp4,m4a,3gp,3g2,mj2
main.8a3a7c71.chunk.js:1 fileType detected format {"ext":"mp4","mime":"video/mp4"}
main.8a3a7c71.chunk.js:1 ffprobe -of json -show_entries stream -i '../C0007.MP4'
main.8a3a7c71.chunk.js:1 ffprobe -i '../C0007.MP4' -show_chapters -print_format json
main.8a3a7c71.chunk.js:1 onDurationChange 18.52
main.8a3a7c71.chunk.js:1 ffprobe -v error -read_intervals '0%30' -show_packets -select_streams 0 -show_entries 'packet=pts_time,flags' -of json '../C0007.MP4'
main.8a3a7c71.chunk.js:1 PIPELINE_ERROR_DECODE: video decode error!
```

**Error report**
```No error

{
  "state": {
    "filePath": "../C0007.MP4",
    "fileFormat": "mp4",
    "externalStreamFiles": [],
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_time_base": "1001/60000",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 3840,
        "height": 2160,
        "coded_width": 3840,
        "coded_height": 2160,
        "closed_captions": 0,
        "has_b_frames": 1,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuvj420p",
        "level": 51,
        "color_range": "pc",
        "chroma_location": "left",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "30000/1001",
        "avg_frame_rate": "30000/1001",
        "time_base": "1/30000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 555555,
        "duration": "18.518500",
        "bit_rate": "96621204",
        "bits_per_raw_sample": "8",
        "nb_frames": "555",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "creation_time": "2021-04-03T11:15:35.000000Z",
          "language": "und",
          "handler_name": "Video Media Handler",
          "encoder": "AVC Coding"
        }
      },
      {
        "index": 1,
        "codec_name": "pcm_s16be",
        "codec_long_name": "PCM signed 16-bit big-endian",
        "codec_type": "audio",
        "codec_time_base": "1/48000",
        "codec_tag_string": "twos",
        "codec_tag": "0x736f7774",
        "sample_fmt": "s16",
        "sample_rate": "48000",
        "channels": 2,
        "bits_per_sample": 16,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/48000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 888960,
        "duration": "18.520000",
        "bit_rate": "1536000",
        "nb_frames": "888960",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "creation_time": "2021-04-03T11:15:35.000000Z",
          "language": "und",
          "handler_name": "Sound Media Handler"
        }
      },
      {
        "index": 2,
        "codec_type": "data",
        "codec_tag_string": "rtmd",
        "codec_tag": "0x646d7472",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/30000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 555555,
        "duration": "18.518500",
        "bit_rate": "245514",
        "nb_frames": "555",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "creation_time": "2021-04-03T11:15:35.000000Z",
          "language": "und",
          "handler_name": "Timed Metadata Media Handler",
          "timecode": "03:42:26:25"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "../C0007.MP4": {
        "0": true,
        "1": true,
        "2": false
      }
    },
    "cutSegments": [
      {}
    ],
    "fileFormatData": {
      "filename": "../C0007.MP4",
      "nb_streams": 3,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "18.520000",
      "size": "230696230",
      "bit_rate": "99652799",
      "probe_score": 100,
      "tags": {
        "major_brand": "XAVC",
        "minor_version": "16785407",
        "compatible_brands": "XAVCmp42iso2",
        "creation_time": "2021-04-03T11:15:35.000000Z"
      }
    },
    "rotation": 360,
    "shortestFlag": false
  },
  "platform": "darwin",
  "version": "3.37.0"
}
```

**Screenshots**
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/4462650/128936455-748c8d28-5741-4ec8-ba5c-20beccc42738.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.5.1

**Additional context**
Used this to install - https://github.com/mifi/lossless-cut/releases/download/v3.37.0/LosslessCut-mac.dmg  
Sent the sample file to your e-mail

**Comment by Shakil-Shahadat** [comment]
Try to convert it to a supported format from the menu.

**Comment by mdmred** [comment]
> Try to convert it to a supported format from the menu.

I tried it:

- The converted file size is about 40 MB vs 200 original - don't really want to lose anything on this stage
- It would be annoying to convert all the files before cutting
- Converted file has the same detected format as the original one - so why the original fails?

**Comment by Shakil-Shahadat** [comment]
1. The conversation is for playback only. Any cut/merge operations uses original file.
2. LosslessCut is built using Electron which uses chrome and it has some limitations about video playback. The dev can't do anything about it. Just check the readme file.
3. It's probably because of different codec.

**Comment by mdmred** [comment]
Thanks for pointing me out, looks like totally a chromium issue.
Though, there's hardly anything can be done on the lossless-cut side to fix it. I wonder if there's a way to check for such issues right after the file is opened, to prevent any confusion. Or even open convertion window right away, cause there's no way around.

**Comment by Shakil-Shahadat** [comment]
It gives warning most of the cases like the one in the picture you have shared. Maybe the warning can be improved and linked to the relevant section of the documentation for better clarity.

**Comment by mdmred** [comment]
I meant – warning appear only after some time, when I move the timeline slider several times. It looks like some unexpected error, but in fact it's a known limitation, which in my opinion could be handled better.
I'll leave this issue opened in case one wants to link any doc/error handling improvement. Ohterwise I have no furhter objections

**Comment by Shakil-Shahadat** [comment]
I'll try to send a pr to improve the message. Thanks for your correspondence.

**Comment by mifi** [comment]
thanks for your report. I have also noticed that some files will load fine without any error, but when trying to play them back, I get this error.  This is indeed an issue with chromium, and I don't really know how to identiy files causing this in order to give an error message immediately. I'm hesitant to block the user with an error immediately because what if the file is indeed playable, but we don't know it until the user presses play.

**Comment by mattack1** [comment]
Is there any way to 'play' it offscreen/in the background (muted) for a fraction of a second, just to see if you'll get this error?
That would at least check if it is playable at this level hopefully without bugging the user with flickering/playing.

**Comment by mifi** [comment]
Yea but it adds complexity to the file-loading logic of the app so I'm a bit hesitatnt

**Comment by mifi** [comment]
If you can test the same file in the newest google chrome, and see if it plays there, then in the future when electron/chromium is updated for losslesscut, the issue will be automatically resolved.

**Comment by mifi** [comment]
Have now implemented so that losslesscut will automatically convert to supported format also on PIPELINE_ERROR_DECODE.

Other than that I don't think there's much I can do becuase chromium player doesn't seem to handle avc1 well natively.
