### ISSUE TITLE
Working dir set change to unset if i press cancel

### ISSUE THREAD

**Issue by Sopor** [mifi/lossless-cut#805]
**Describe the bug**
If i have the working dir already set and i press the button `Working dir set`, I browse around, but i change my mind so i press cancel to not change the working dir. Now the button change to `Working dir unset`.

**To Reproduce**
1. Open a video
2. Press Working dir set
3. Press Cancel

**Expected behavior**
When i press cancel it means that i want to keep the directory i have selected already. It shouldn't change directory (It seems to change to Same directory as input file).

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 1909
 - LosslessCut 3.37.0

**Comment by mifi** [comment]
Actually this is kind of a "feature", e.g. how to clear the working dir. But I agree it's not really good UX. Could instead put a button next to it to clear it.

**Comment by mifi** [comment]
Have now fixed this with a clear working dir button:

<img width="204" alt="Screenshot 2021-08-23 at 13 47 13" src="https://user-images.githubusercontent.com/402547/130402783-143d47a0-b3df-4e5a-a97c-2103675e73ab.png">
