### ISSUE TITLE
Shortcut Keys and Playback (Enhancement Request)

### ISSUE THREAD

**Issue by syk013** [mifi/lossless-cut#81]
Hi,

First of all, thank you so much for this software, it really is a gem and what I have been looking for, for ages. 

The only things that I think would make the software even better are some additional shortcut keys like the following:

Shortcut key for Exporting (for example ctrl+E or just E, this will speed up the workflow a lot)
Shortcuts for moving current play position to the In and the Out points (for example, down arrow to go to in and up arrow to go to out point)
Shortcut keys to go one frame forward or one frame backwards (left and right arrow keys).
#
Then another thing that would make life a lot easier especially for video editors like myself is the standard playback controls found in editing software.

Pressing K to play/pause
Pressing L to play forward (which it currently does)
Pressing J to play the file backwards (instead of slowing it down)
I get the need for slower playback, but maybe it is possible to map that to a different shortcut key?

Also currently pressing L multiple time makes the clip play faster, but at very small increments which seems unnecessary because I have never come across anyone needing to play it back at x1.3 speed so it then takes a lot more effort to get to x2 or more. In video editing software the speed usually doubles or halfs the speed but that is sometimes to drastic so multipliers of one would work wonders (Pressing L once = x1 speed, pressing it again = x2 speed, pressing it again = x3 speed etc. And if for example if it is playing at x2 speed hitting J will decrease it to x1 speed and hitting J after that will start playing the clip backwards at x1 speed and so on.)

If the above shortcut implementations can be made it would truly make this piece of software the best thing ever :D

An extra bonus would be if support for Apple Prores .mov codecs are added as I know a lot of people work with Apple Prores files and a lot of cameras use that as the shooting codec.

I know this post turned into an essay and there are a lot of things in here. But I believe these are the last things needed in order to make this better than any alternative software out there at the moment.

Thank you once again for creating this, I am loving the time I can save by not having to re-encode my footage :)

Best Regards

**Comment by mifi** [comment]
Hi

Some of the requests you have are already implemented

> Shortcut key for Exporting (for example ctrl+E or just E, this will speed up the workflow a lot)

Already implemented, no?

> Shortcuts for moving current play position to the In and the Out points (for example, down arrow to go to in and up arrow to go to out point)

If you press the arrows next to the numbers, it will do this. Shortcut could be implemented

> Shortcut keys to go one frame forward or one frame backwards (left and right arrow keys).

Need to get the FPS of the video to do this. Could be done with ffprobe maybe.

> Then another thing that would make life a lot easier especially for video editors like myself is the standard playback controls found in editing software.
> 
> Pressing K to play/pause

Already implemented, no?

> Pressing J to play the file backwards (instead of slowing it down)

It's not possible to play backwards in the html5 player as far as i know.

> Also currently pressing L multiple time makes the clip play faster, but at very small increments which seems unnecessary because I have never come across anyone needing to play it back at x1.3 speed so it then takes a lot more effort to get to x2 or more. In video editing software the speed usually doubles or halfs the speed but that is sometimes to drastic so multipliers of one would work wonders (Pressing L once = x1 speed, pressing it again = x2 speed, pressing it again = x3 speed etc. And if for example if it is playing at x2 speed hitting J will decrease it to x1 speed and hitting J after that will start playing the clip backwards at x1 speed and so on.)

We could increase the multiplier yes, but if we cannot go backwards, is it really that useful?

> An extra bonus would be if support for Apple Prores .mov codecs are added as I know a lot of people work with Apple Prores files and a lot of cameras use that as the shooting codec.

Not possible. Chome HTML5 video does not support Prores. It is possible to pre-encode the file and then cut it (from the file-menu), however it can take a while if the video is long.

**Comment by RileyMShea** [comment]
> Shortcuts for moving current play position to the In and the Out points (for example, down arrow to go to in and up arrow to go to out point)

I'd also really appreciate this, along with the ability to change the small seek time from 1 sec.

**Comment by mifi** [comment]
Can discuss further here: #254
