### ISSUE TITLE
CUE sheet - "PERFORMER" variable missing

### ISSUE THREAD

**Issue by BlueMax** [mifi/lossless-cut#814]
Hallo,
when importing a CUE sheet the 'PERFORMER' variable is not taken over to the segments. Only the 'TITLE' variable is shown. Thus, when exporting with ${SEG_LABEL} the file is named "TITLE-TITLE" instead of "PERFORMER-TITLE".

Edit: When using 'YouTube text chapters' its correctly displayed in the segments but still buggy on the export screen ("PERFORMER/TITLE-PERFORMER/TITLE".

Arch Linux 5.13.10
LosslessCut v3.37.0

```
TITLE "Group_Therapy_446_with_Above_Beyond_and_Maxinne-131kbit"
FILE "Group_Therapy_446_with_Above_Beyond_and_Maxinne-131kbit.webm" WEBM
  TRACK 01 AUDIO
    PERFORMER "ABGT"
    TITLE "Intro"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    PERFORMER "StanV"
    TITLE "Lighthouse (Enhanced Progressive)"
    INDEX 01 00:31:00
  TRACK 03 AUDIO
    PERFORMER "Energy 52"
    TITLE "Cafe del Mar [Paul van Dyk XOXO Remix] (Superstition Records)"
    INDEX 01 04:15:00
[...]
```

For full CUE/OPUS files go [here](https://github.com/mifi/lossless-cut/issues/813).

![lc1](https://user-images.githubusercontent.com/1403092/129611347-fe54ca87-c3c9-4c2a-a21b-20d4a817fcd1.png)
![lc2](https://user-images.githubusercontent.com/1403092/129611875-5490adc3-69d2-4661-9759-6154ffaba182.png)

**Comment by mifi** [comment]
I think performer is a very CUE-specific concept, and not something that losslesscut should support

**Comment by BlueMax** [comment]
CUE sheets are for audio files and those obviously need separate 'performer-title'. 
But if you want to concentrate on video only it's ok. I have to manually rename the files then.

**Comment by mifi** [comment]
Losslesscut could however possibly implement a system where the user can select from any metadata/tags from the segments for output file name. For example ${SEG.PERFORMER}. Then for cue files we could store «performer» as a tag for the segments.

**Comment by mifi** [comment]
This has been suggested in #427

**Comment by mifi** [comment]
I have implemented support for tags!

in the next version you can set template to for example `${SEG_TAGS.PERFORMER} - ${SEG_TAGS.TITLE}${EXT}`
and you will get something like this:

<img width="722" alt="Screenshot 2021-08-24 at 00 36 17" src="https://user-images.githubusercontent.com/402547/130494885-8cc1361e-c7f9-4a06-89fe-1acdf6b47b39.png">
<img width="504" alt="Screenshot 2021-08-24 at 00 36 40" src="https://user-images.githubusercontent.com/402547/130494894-4569358f-d4a8-4502-8984-1a90a367231d.png">

Note that tags are not auto saved yet (coming...)

**Comment by BlueMax** [comment]
Yes, that's a good idea. But to be able use the performer tag the segment must be fed with the performer data first. If you look at my first screenshot you can see that lossletcut doesn't import that data in the first place.

**Comment by mifi** [comment]
I have also implemented auto loading of the PERFORMER and TITLE tags from CUE files, so it will be available in the next version.

**Comment by BlueMax** [comment]
Thanks!
