### ISSUE TITLE
[Feature Request] Merge audio tracks

### ISSUE THREAD

**Issue by TrixPone** [mifi/lossless-cut#82]
Can we have an option to merge all audio tracks, or preserve multiple audio tracks ?
It would be useful with shadowplay files, where it uses 2 audio track (1 for desktop, 1 for mic)..

Thank You

Edit: i just saw the 'All Audio Cut' option.. 
So, maybe can we have an option to merge ?

**Comment by mifi** [comment]
Preserve multiple tracks is already possible. Merge is not something that can be done lossleslly, sorry.
