### ISSUE TITLE
New configurable behaviour: delete generated proxy clips

### ISSUE THREAD

**Issue by kdm9** [mifi/lossless-cut#829]
**Is your feature request related to a problem? Please describe.**

Working with 4k 10bit 422 footage, I need to create proxy clips for each input file so LC can function. This writes a whole lot of BLAH.html5ified.mkv files everywhere. I have no use for these files outside LC, and so currently I manually delete these once finished in LC.

**Describe the solution you'd like**

It would be fantastic if there was a way for LC to be asked to delete these proxy files when it is finished with them. I would suggest either on program close or perhaps even project export, but I have no idea of the implications on the innards of LC of these proxy clips being deleted so I don't know when would be best.

**Describe alternatives you've considered**

Selecting and deleting all files named like `*html5ified*.mkv`. I've at least once accidentally deleted an exported segment file and had to re-export, which made me wish this could be handled automagically by LC. This is not a pressing need, but it would be nice!

Best
Kevin

**Comment by mifi** [comment]
Hi. If you click the trash icon at the bottom right (or <kbd>D</kbd>), it will close the current file and you can choose which files to cleanup. Is that what you're asking?

**Comment by mifi** [comment]
I think this can be closed! please let me know if there's anything i missed
