### ISSUE TITLE
Persistent/inconsistent settings below timeline [Show waveform/thumbnails/keyframes]

### ISSUE THREAD

**Issue by Wiethoofd** [mifi/lossless-cut#843]
The settings on the bottom left below the timeline for waveform, thumbnails and keyframes aren't entirely persistent or consistent.

I like to always have the waveform visible when cutting down videos, but I have to always re-enable this after starting LLC, it does not seem to be a persistent setting, where the 'keyframe' one is always enabled after a relaunch.

Currently it also does not seem to be possible to have the waveform and the thumbnails visible, it is a toggle between either option, perhaps somehow indicating this is the case or allowing both to be enabled would be appreciated.

**Comment by mifi** [comment]
closing in favor of #371 and #260 (i added suggestions there)
