### ISSUE TITLE
Use natural language sorting in Merge files dialog

### ISSUE THREAD

**Issue by zhuoziqiang** [mifi/lossless-cut#844]
When there are the following file names: 1, 2, 3, 10, 11
LosslessCut shows: 1, 10, 11, 2, 3, which is obviously wrong.
Hope to fix it

**Comment by mifi** [comment]
You mean the sort button? It sorts alphabetically so it's not really "wrong". If you name your files 01, 02, 03 etc it will sort properly. An alternative would be to use natural language sorting https://fuzzytolerance.info/blog/2019/07/19/The-better-way-to-do-natural-sort-in-JavaScript/

**Comment by mifi** [comment]
Closing in favor of #210
