### ISSUE TITLE
cant merge and create file

### ISSUE THREAD

**Issue by rrrcabral** [mifi/lossless-cut#849]
Error: Command failed with exit code 1: C:\Users\Gabi\AppData\Local\Temp\1voKP8pb6Lorzi7JP9v9F4pYDQ4\resources\node_modules\ffmpeg-ffprobe-static\ffmpeg.exe -hide_banner -ss 6.00600 -i C:\Users\Gabi\Downloads\74995bb3f0767c5d57319af65e73d755-1080p.mp4 -t 88.88880 -avoid_negative_ts make_zero -c copy -map 0:0 -map 0:1 -map_metadata 0 -movflags +faststart -ignore_unknown -f mp4 -y C:\Users\Gabi\Downloads\74995bb3f0767c5d57319af65e73d755-1080p-00.00.06.006-00.01.34.894-seg1.mp4
O sistema n�o pode encontrar o caminho especificado. (the system cannot find the specified path)
    at makeError (C:\Users\Gabi\AppData\Local\Temp\1voKP8pb6Lorzi7JP9v9F4pYDQ4\resources\app.asar\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Users\Gabi\AppData\Local\Temp\1voKP8pb6Lorzi7JP9v9F4pYDQ4\resources\app.asar\node_modules\execa\index.js:114:26)
    at async g (file:///C:/Users/Gabi/AppData/Local/Temp/1voKP8pb6Lorzi7JP9v9F4pYDQ4/resources/app.asar/build/static/js/main.8a3a7c71.chunk.js:1:58484)
    at async file:///C:/Users/Gabi/AppData/Local/Temp/1voKP8pb6Lorzi7JP9v9F4pYDQ4/resources/app.asar/build/static/js/main.8a3a7c71.chunk.js:1:58689
    at async file:///C:/Users/Gabi/AppData/Local/Temp/1voKP8pb6Lorzi7JP9v9F4pYDQ4/resources/app.asar/build/static/js/main.8a3a7c71.chunk.js:1:172633

{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "filePath": "C:\\Users\\Gabi\\Downloads\\74995bb3f0767c5d57319af65e73d755-1080p.mp4",
    "fileFormat": "mp4",
    "externalStreamFiles": [],
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_time_base": "1001/60000",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1088,
        "closed_captions": 0,
        "has_b_frames": 0,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 40,
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "30000/1001",
        "avg_frame_rate": "30000/1001",
        "time_base": "1/30000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 215241026,
        "duration": "7174.700867",
        "bit_rate": "3479152",
        "bits_per_raw_sample": "8",
        "nb_frames": "215026",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "creation_time": "2020-01-23T19:19:44.000000Z",
          "language": "und",
          "handler_name": "ISO Media file produced by Google Inc. Created on: 01/23/2020."
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_time_base": "1/44100",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "44100",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/44100",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 316404736,
        "duration": "7174.710567",
        "bit_rate": "127999",
        "nb_frames": "308989",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "creation_time": "2020-01-23T19:19:44.000000Z",
          "language": "und",
          "handler_name": "ISO Media file produced by Google Inc. Created on: 01/23/2020."
        }
      }
    ],
    "copyStreamIdsByFile": {
      "C:\\Users\\Gabi\\Downloads\\74995bb3f0767c5d57319af65e73d755-1080p.mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {
        "start": 6.006,
        "end": 94.8948
      },
      {
        "start": 509.17533333333336,
        "end": 551.8846666666667
      },
      {
        "start": 735.3012333333334,
        "end": 1372.4377333333334
      },
      {
        "start": 1991.5896,
        "end": 2881.6788
      },
      {
        "start": 3278.742133333333,
        "end": 3423.5534666666667
      },
      {
        "start": 3648.3113333333336,
        "end": 3812.6088
      },
      {
        "start": 3893.522966666667,
        "end": 3996.3924
      },
      {
        "start": 4252.114533333333,
        "end": 5126.588133333334
      },
      {
        "start": 5337.865866666667,
        "end": 5380.308266666667
      },
      {
        "start": 5546.607733333333,
        "end": 7144.704233333334
      }
    ],
    "fileFormatData": {
      "filename": "C:\\Users\\Gabi\\Downloads\\74995bb3f0767c5d57319af65e73d755-1080p.mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "7174.710000",
      "size": "3237276150",
      "bit_rate": "3609652",
      "probe_score": 100,
      "tags": {
        "major_brand": "mp42",
        "minor_version": "0",
        "compatible_brands": "isommp42",
        "creation_time": "2020-01-23T19:19:44.000000Z",
        "encoder": "Google"
      }
    },
    "rotation": 360,
    "shortestFlag": false
  },
  "platform": "win32",
  "version": "3.37.0"
}

**Comment by mifi** [comment]
Did you try to restart losslesscut? also can you try with the zip version download instead?

**Comment by mifi** [comment]
I think LosslessCut could do a POST self-check when starting up, see that ffmpeg/ffprobe are executeable. If not, show an error message that the installation is corrupt. (files missing or cannot be executed, maybe show the error message)
But it should not slow down the startup of losslessCut (async).

**Comment by mehdifirefox** [comment]
I got the audio file several cut
I Can't merge
When I want to export the file
Several number MP3 files
1 file is not

**Comment by mehdifirefox** [comment]
> 
> 
> I think LosslessCut could do a POST self-check when starting up, see that ffmpeg/ffprobe are executeable. If not, show an error message that the installation is corrupt. (files missing or cannot be executed, maybe show the error message)
> But it should not slow down the startup of losslessCut (async).

I got the audio file several cut
I Can't merge
When I want to export the file
Several number MP3 files
1 file is not

**Comment by mifi** [comment]
Im sorry but i dont understand. Please try to explain a bit more detailed or record a video with the problem

**Comment by mifi** [comment]
ffmpeg now runs a startup check as of https://github.com/mifi/lossless-cut/commit/9666ce4a2cb0d6c907b1523b53ab812b1b0af482

Closing this due to lack of response
