### ISSUE TITLE
Metadata inconsistency and request

### ISSUE THREAD

**Issue by RobCrossRC** [mifi/lossless-cut#853]
Hi,

I use MP3tag to tag my Music and Media Monkey to play them and have started to use both on my videos. In the main I use .mp4 formats for all videos as these are excellent for metadata and file size is not my main priority.

I have noticed some inconsistencies when using Lossless Cut regarding Metadata and have listed these below. 
As well as the behaviour below, it would be great for me if Lossless was able to add the ability to set a thumbnail and save it in the export as well as save a thumbnail to a photo.
So basically if I could preserve all the Metadata that's already present (where the metadata can be edited as some fields are dynamic to the file) and add a thumbnail chosen whilst I edit the file.

The behaviours  I'm noticing are below
Choosing just video and audio tracks
If I just Export the file with no changes and Preserve all MP4/MOV metadata set to Yes - No metadata is saved in the exported file
If I just Export the file with no changes and Preserve all MP4/MOV metadata set to No - Metadata is saved for some tags but not any of the custom tags.

If I edit the file and export with Preserve original meta and preserve all MP4/MOV both set to Yes - No metadata is saved in the exported file
If I edit the file and export with Preserve original meta set to Yes and preserve all MP4/MOV set to No - Metadata is saved for some tags but not any of the custom tags.
If I edit the file and export with Preserve original meta set to No and preserve all MP4/MOV set to Yes - No metadata is saved in the exported file
If I edit the file and export with Preserve original meta and preserve all MP4/MOV both set to No - No metadata is saved in the exported file

Adding third track (thumbnail) to output
If I just Export the file with no changes and Preserve all MP4/MOV metadata set to Yes - No metadata is saved in the exported file and no thumbnail is present
If I just Export the file with no changes and Preserve all MP4/MOV metadata set to No - Metadata is saved for some tags but not any of the custom tags. The thumbnail is present in the export.

I've attached-
A Sample mp4 file
A text file with the Metadata that's populated
A screenshot of Lossless view of the metadata before any export or change (it can see all fields I am interested in)

![Lossless Cut Metadata view before any change](https://user-images.githubusercontent.com/72663924/132132138-7c97f75d-8ec4-4cdf-afe1-f01594997b2f.jpg)

[Sample Metadata List.txt](https://github.com/mifi/lossless-cut/files/7111888/Sample.Metadata.List.txt)

https://user-images.githubusercontent.com/72663924/132132103-dfea0443-1561-4fe8-96bf-863dc513043b.mp4

I'm on
Lossless Cut 3.39.0 (latest version)
Windows 10 Pro latest version

Appreciate any help on this as someone who's contributed to this excellent piece of software
Many thanks
Rob

**Comment by mifi** [comment]
Hi. Thanks for your thorough report and sorry for the slow reply. Had a lot of issues to go through. I just tested your file and for me, as long as I set `Preserve all MP4/MOV metadata? YES`, I do get all the custom tags also in the output.
which program are you using to verify that metadata is included or not? Here is my results from `ffprobe`

Preserve all MP4/MOV metadata? YES:
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'metadata-issue-853-cut-merged-1642265323077.mp4':
  Metadata:
    compatible_brands: isom3gp4
    major_brand     : isom
    minor_version   : 0
    creation_time   : 2014-05-24T20:55:36.000000Z
    genre           : Music
    title           : Sample
    QUALITY         : Good
    CUSTOM5         : Edited
    CUSTOM4         : Test Tag
    CUSTOM2         : 00:02
    CUSTOM1         : Old File Name
    grouping        : Test GD
    comment         : Test Comment
    artist          : Test Artist
    ACTORS          : Test Actor
    encoder         : Lavf58.76.100
```

Preserve all MP4/MOV metadata? NO:
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'metadata-issue-853-cut-merged-1642265156356.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 2014-05-24T20:55:36.000000Z
    title           : Sample
    artist          : Test Artist
    encoder         : Lavf58.76.100
    comment         : Test Comment
    genre           : Music
    grouping        : Test GD
```

as described here https://video.stackexchange.com/a/26084/29486 `use_metadata_tags` (`Preserve all MP4/MOV metadata: YES`) may transfer the metadata in a format that not all players can understand, like iTunes. https://github.com/mifi/lossless-cut/issues/331#issuecomment-623401794 I'm thinking that could be the problem

**Comment by RobCrossRC** [comment]
Hi,
Thanks for the response, I can imagine you have been busy.
I've just run an edit using the preserve option and I can see that using FFProbe the metadata is still there. 
However I use VLC, MP3Tag and Media Monkey (V4 or 5) to view or edit and none of these can see the tags which is strange. Looking at the metadata before and after using FFProbe it's the same except the edited file has one tag added. 
  Metadata:
    encoder         : Lavf58.45.100
If I have original and edited files open in MP3Tag I can copy the tags across but it's frustrating that they don't just work without this in all of the player mentioned above so not sure how easy it would be to fix that?
Thanks

**Comment by mifi** [comment]
Ok. I see. Makes sense because not all players can understand the ffmpeg outputted custom metadata. Have you by any chance tried to change output format to .MOV and see if that helps?

**Comment by RobCrossRC** [comment]
I tried MOV but the issue is just the same.
I think you are right that this is an ffmpeg isssue. I've tried all sorts of switches using command line ffmpeg and I'm never able to save any of the custom type tags as visible in any of the other tools I use yet ffprobe shows them as present. 
I can get it to save some of the core tags like Genre but without saving them all there's extra process to follow.
ffprobe on the file before and after edit looks pretty much identical for meta data so I've no idea what it's doing. There's a few threads on the ffmpeg site about this issue but it seems to have been going on for ages so not hopeful of a fix.
I guess for me personally something within Lossless that behaved the same as MP3Tag where tags are concerned would work but also that might break other use case and not be something that's easy to add as an option.
Thanks for looking into it.

**Comment by mifi** [comment]
I also found these ffmpeg ticket with similar results:
- https://trac.ffmpeg.org/ticket/4209
- https://trac.ffmpeg.org/ticket/6193

**Comment by RobCrossRC** [comment]
Hi,
Thanks for the update. The tools I use are mainly the two below for tagging and organising.
MP3Tag https://www.mp3tag.de/en/
MediaMonkey 4 https://www.mediamonkey.com/

The custom tags I write to are called Custom1 to Custom5. When I write these in either MP3Tag or MM they are visible in the other program.  Also they are then visible in VLC and again are called Custom1 to Custom5.
I have just downloaded and run ExitTool against the text file and that is also calling the Tags Custom1 to Custom5, thanks.
