### ISSUE TITLE
No sound at playback in the app

### ISSUE THREAD

**Issue by deeyeej** [mifi/lossless-cut#856]

**Comment by deeyeej** [comment]
No error

{
  "state": {
    "filePath": "C:\\Users\\MIKI\\Desktop\\TV\\The.Walking.Dead.S11E04.mkv",
    "fileFormat": "matroska",
    "externalStreamFiles": [],
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_time_base": "1/48",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1088,
        "closed_captions": 0,
        "has_b_frames": 2,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 40,
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "field_order": "progressive",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "24/1",
        "avg_frame_rate": "24/1",
        "time_base": "1/1000",
        "start_pts": 0,
        "start_time": "0.000000",
        "bits_per_raw_sample": "8",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "BPS": "8336237",
          "NUMBER_OF_FRAMES": "74268",
          "NUMBER_OF_BYTES": "3224560995",
          "_STATISTICS_WRITING_APP": "mkvmerge v61.0.0 ('So') 64-bit",
          "_STATISTICS_WRITING_DATE_UTC": "2021-09-05 10:26:01",
          "_STATISTICS_TAGS": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES",
          "DURATION": "00:43:42.416000000"
        }
      },
      {
        "index": 1,
        "codec_name": "eac3",
        "codec_long_name": "ATSC A/52B (AC-3, E-AC-3)",
        "codec_type": "audio",
        "codec_time_base": "1/48000",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 6,
        "bits_per_sample": 0,
        "dmix_mode": "-1",
        "ltrt_cmixlev": "-1.000000",
        "ltrt_surmixlev": "-1.000000",
        "loro_cmixlev": "-1.000000",
        "loro_surmixlev": "-1.000000",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/1000",
        "start_pts": 16,
        "start_time": "0.016000",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "eng",
          "BPS": "640000",
          "NUMBER_OF_FRAMES": "96703",
          "NUMBER_OF_BYTES": "247559680",
          "_STATISTICS_WRITING_APP": "mkvmerge v61.0.0 ('So') 64-bit",
          "_STATISTICS_WRITING_DATE_UTC": "2021-09-05 10:26:01",
          "_STATISTICS_TAGS": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES",
          "DURATION": "00:43:42.000000000"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "C:\\Users\\MIKI\\Desktop\\TV\\The.Walking.Dead.S11E04.mkv": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {}
    ],
    "fileFormatData": {
      "filename": "C:\\Users\\MIKI\\Desktop\\TV\\The.Walking.Dead.S11E04.mkv",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "matroska,webm",
      "format_long_name": "Matroska / WebM",
      "start_time": "0.000000",
      "duration": "2622.416000",
      "size": "2920963362",
      "bit_rate": "8910755",
      "probe_score": 100,
      "tags": {
        "creation_time": "2021-09-05T10:26:01.000000Z",
        "ENCODER": "Lavf58.45.100"
      }
    },
    "rotation": 360,
    "shortestFlag": false
  },
  "platform": "win32",
  "version": "3.39.0"
}

**Comment by deeyeej** [comment]
No error

{
  "state": {
    "filePath": "C:\\Users\\MIKI\\Desktop\\TV\\The.Walking.Dead.S11E04.mkv",
    "fileFormat": "matroska",
    "externalStreamFiles": [],
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_time_base": "1/48",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1088,
        "closed_captions": 0,
        "has_b_frames": 2,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 40,
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "field_order": "progressive",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "24/1",
        "avg_frame_rate": "24/1",
        "time_base": "1/1000",
        "start_pts": 0,
        "start_time": "0.000000",
        "bits_per_raw_sample": "8",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "BPS": "8336237",
          "NUMBER_OF_FRAMES": "74268",
          "NUMBER_OF_BYTES": "3224560995",
          "_STATISTICS_WRITING_APP": "mkvmerge v61.0.0 ('So') 64-bit",
          "_STATISTICS_WRITING_DATE_UTC": "2021-09-05 10:26:01",
          "_STATISTICS_TAGS": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES",
          "DURATION": "00:43:42.416000000"
        }
      },
      {
        "index": 1,
        "codec_name": "eac3",
        "codec_long_name": "ATSC A/52B (AC-3, E-AC-3)",
        "codec_type": "audio",
        "codec_time_base": "1/48000",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 6,
        "bits_per_sample": 0,
        "dmix_mode": "-1",
        "ltrt_cmixlev": "-1.000000",
        "ltrt_surmixlev": "-1.000000",
        "loro_cmixlev": "-1.000000",
        "loro_surmixlev": "-1.000000",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/1000",
        "start_pts": 16,
        "start_time": "0.016000",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "eng",
          "BPS": "640000",
          "NUMBER_OF_FRAMES": "96703",
          "NUMBER_OF_BYTES": "247559680",
          "_STATISTICS_WRITING_APP": "mkvmerge v61.0.0 ('So') 64-bit",
          "_STATISTICS_WRITING_DATE_UTC": "2021-09-05 10:26:01",
          "_STATISTICS_TAGS": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES",
          "DURATION": "00:43:42.000000000"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "C:\\Users\\MIKI\\Desktop\\TV\\The.Walking.Dead.S11E04.mkv": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {}
    ],
    "fileFormatData": {
      "filename": "C:\\Users\\MIKI\\Desktop\\TV\\The.Walking.Dead.S11E04.mkv",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "matroska,webm",
      "format_long_name": "Matroska / WebM",
      "start_time": "0.000000",
      "duration": "2622.416000",
      "size": "2920963362",
      "bit_rate": "8910755",
      "probe_score": 100,
      "tags": {
        "creation_time": "2021-09-05T10:26:01.000000Z",
        "ENCODER": "Lavf58.45.100"
      }
    },
    "rotation": 360,
    "shortestFlag": false
  },
  "platform": "win32",
  "version": "3.39.0"
}

**Comment by mifi** [comment]
The audio codec is not supported. Try File -> Convert to supported format -> Fastest: Low playback speed

**Comment by deeyeej** [comment]
> The audio codec is not supported. Try File -> Convert to supported format -> Fastest: Low playback speed

Okey! Thank you for the answer.

**Comment by mifi** [comment]
did it work?

**Comment by deeyeej** [comment]
No!!

Den tors 23 sep. 2021 kl 15:51 skrev Mikael Finstad <
***@***.***>:

**Comment by mifi** [comment]
then what happened?

**Comment by mifi** [comment]
closing due to lack of feedback
