### ISSUE TITLE
Allow renaming batch exported files

### ISSUE THREAD

**Issue by mitchcurtis** [mifi/lossless-cut#857]
I wrote this in more detail but I accidentally lost all of it, so this time it is a bit more brief:

From https://github.com/mifi/lossless-cut/issues/89#issuecomment-907765735:

> Currently my workflow is:
> 
> 1. Load a video
> 2. Trim it
> 3. Export
> 4. Rename in file explorer
> 
> It would be awesome if it could instead be:
> 1. Load a video
> 2. Trim it
> 3. Rename it
> 4. Export

It [was mentioned](https://github.com/mifi/lossless-cut/issues/89#issuecomment-907837698) that there is a way to do this in the export dialog, but I don't see such a dialog.

It would be nice if you could do this directly in the batch list:

![image](https://user-images.githubusercontent.com/6002340/132577633-10f512ff-85e5-425f-a450-620b902b6335.png)

**Comment by mitchcurtis** [comment]
Hmmm, now that I think about it, the timestamp that LosslessCut appends to the generated file name has to be removed regardless, and that timestamp isn't shown in the batch list... so maybe allowing choosing the name of the file in an export dialog would be the best way.

**Comment by mifi** [comment]
> It [was mentioned](https://github.com/mifi/lossless-cut/issues/89#issuecomment-907837698) that there is a way to do this in the export dialog, but I don't see such a dialog.

You toggle the export dialog with this button:
<img width="57" alt="Screenshot 2021-09-23 at 12 55 30" src="https://user-images.githubusercontent.com/402547/134460362-74e8196e-7619-4d48-90c1-1dc30b0a848d.png">

**Comment by mitchcurtis** [comment]
Ah, thanks.

**Comment by mitchcurtis** [comment]
Not sure if this is worth is own "question" issue (and I see no way to contact you otherwise - please let me know if there is a better place for this kind of question): which command do you use to get the list of key frames that are "safe" to cut on?

**Comment by mifi** [comment]
Ffmpeg handles this internally. I cannot control it. It depends on the codec.
