### ISSUE TITLE
can cut , but cant merge

### ISSUE THREAD

**Issue by rrrcabral** [mifi/lossless-cut#859]
Error: Command failed with exit code 1: C:\Users\Gabi\AppData\Local\Temp\1voKP8pb6Lorzi7JP9v9F4pYDQ4\resources\node_modules\ffmpeg-ffprobe-static\ffprobe.exe -of json -show_format -i C:\Users\Gabi\Downloads\nhdtb-570-00.10.06.072-00.27.14.933-seg1.mp4
'C:\Users\Gabi\AppData\Local\Temp\1voKP8pb6Lorzi7JP9v9F4pYDQ4\resources\node_modules\ffmpeg-ffprobe-static\ffprobe.exe' n�o � reconhecido como um comando interno
ou externo, um programa oper�vel ou um arquivo em lotes.
    at makeError (C:\Users\Gabi\AppData\Local\Temp\1voKP8pb6Lorzi7JP9v9F4pYDQ4\resources\app.asar\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Users\Gabi\AppData\Local\Temp\1voKP8pb6Lorzi7JP9v9F4pYDQ4\resources\app.asar\node_modules\execa\index.js:114:26)
    at async P (file:///C:/Users/Gabi/AppData/Local/Temp/1voKP8pb6Lorzi7JP9v9F4pYDQ4/resources/app.asar/build/static/js/main.8a3a7c71.chunk.js:1:3971)
    at async D (file:///C:/Users/Gabi/AppData/Local/Temp/1voKP8pb6Lorzi7JP9v9F4pYDQ4/resources/app.asar/build/static/js/main.8a3a7c71.chunk.js:1:4084)
    at async file:///C:/Users/Gabi/AppData/Local/Temp/1voKP8pb6Lorzi7JP9v9F4pYDQ4/resources/app.asar/build/static/js/2.d96bdb74.chunk.js:2:784306

{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "filePath": "C:\\Users\\Gabi\\Downloads\\nhdtb-570.mp4",
    "fileFormat": "mp4",
    "externalStreamFiles": [],
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "Main",
        "codec_type": "video",
        "codec_time_base": "1001/60000",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 856,
        "height": 482,
        "coded_width": 864,
        "coded_height": 496,
        "closed_captions": 0,
        "has_b_frames": 1,
        "sample_aspect_ratio": "964:963",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 40,
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "30000/1001",
        "avg_frame_rate": "30000/1001",
        "time_base": "1/30000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 331630299,
        "duration": "11054.343300",
        "bit_rate": "1293898",
        "bits_per_raw_sample": "8",
        "nb_frames": "331299",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "creation_time": "2021-08-26T18:23:07.000000Z",
          "language": "jpn",
          "handler_name": "VideoHandler"
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_time_base": "1/48000",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/48000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 530611224,
        "duration": "11054.400500",
        "bit_rate": "127969",
        "max_bit_rate": "128000",
        "nb_frames": "518052",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "creation_time": "2021-08-26T18:23:07.000000Z",
          "language": "jpn",
          "handler_name": "SoundHandler"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "C:\\Users\\Gabi\\Downloads\\nhdtb-570.mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {
        "start": 606.0721333333333,
        "end": 1634.9333
      },
      {
        "start": 2191.5226666666667,
        "end": 3401.9986
      },
      {
        "start": 3538.3014333333335,
        "end": 5323.484833333334
      },
      {
        "start": 6305.9997,
        "end": 7422.281533333334
      },
      {
        "start": 8474.3659,
        "end": 8527.9194
      },
      {
        "start": 10038.995633333334,
        "end": 10992.614966666666
      }
    ],
    "fileFormatData": {
      "filename": "C:\\Users\\Gabi\\Downloads\\nhdtb-570.mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "11054.401000",
      "size": "1975700323",
      "bit_rate": "1429801",
      "probe_score": 100,
      "tags": {
        "major_brand": "isom",
        "minor_version": "512",
        "compatible_brands": "isomiso2avc1mp41",
        "creation_time": "2021-08-26T18:23:07.000000Z",
        "encoder": "Lavf58.78.100"
      }
    },
    "rotation": 360,
    "shortestFlag": false
  },
  "platform": "win32",
  "version": "3.37.0"
}

**Comment by mifi** [comment]
#858
