### ISSUE TITLE
Allow audio transcoding during cut [read on to see why]

### ISSUE THREAD

**Issue by trollcop** [mifi/lossless-cut#866]
My camera (HC-X1000) produces MP4 files with LPCM audio:

```
{
  index: 1,
  codec_name: 'pcm_s16be',
  codec_long_name: 'PCM signed 16-bit big-endian',
  codec_type: 'audio',
  codec_time_base: '1/48000',
  codec_tag_string: 'twos',
  codec_tag: '0x736f7774',
  sample_fmt: 's16',
  sample_rate: '48000',
  channels: 2,
  bits_per_sample: 16,
  r_frame_rate: '0/0',
  avg_frame_rate: '0/0',
  time_base: '1/48000',
  start_pts: 0,
  start_time: '0.000000',
  duration_ts: 5717712,
  duration: '119.119000',
  bit_rate: '1536000',
  nb_frames: '5717712',
  disposition: {
    default: 1,
    dub: 0,
    original: 0,
    comment: 0,
    lyrics: 0,
    karaoke: 0,
    forced: 0,
    hearing_impaired: 0,
    visual_impaired: 0,
    clean_effects: 0,
    attached_pic: 0,
    timed_thumbnails: 0,
  },
  tags: {
    creation_time: '2021-09-23T09:28:29.000000Z',
    language: 'eng',
    timecode: '04:29:55;58',
  },
}
```

MP4 does not support LPCM (or at least not s16be) so exporting on default options fails. Which then causes the rest of the exports to fail (even if choosing different container) but that's a separate bug issue.

Anyway, I would like to be able to select audio codec somewhere in the tracks screen (i guess?) or maybe in the export dialog where it asks for keyframes etc, to have an option to leave audio as-is (acodec copy or whatever) vs re-encode it with acodec aac or somesuch. Of course default would be to copy.

**Comment by mifi** [comment]
does it work with MOV, or with Experimental setting enabled?
Re-encoding to a different codec is a lossy operation, so it's not the primary goal of losslesscut. But there is a feature request for adding lossy operations #372

**Comment by trollcop** [comment]
Hi, sorry for late reply
Does it work with mov? -> Yes, if I selected mov in the GUI, it works.

However I cannot repeat the previous bug of where mp4 was selected at start, and after 1st failure to export, choosing mov or mkv or any other format made no difference.

Here's the file which causes mp4 export to fail:
https://drive.google.com/file/d/12aSOQooZby4PUwA83gm6aSkJNpVdITik/view?usp=sharing

Is it possible to somehow see the ffmpeg command line used for the cut operation, so that I can run it in cli myself and see what the error is?

**Comment by mifi** [comment]
> Here's the file which causes mp4 export to fail: https://drive.google.com/file/d/12aSOQooZby4PUwA83gm6aSkJNpVdITik/view?usp=sharing

thanks, I tested your file and for me it works if I change to MOV. Was there a different problem?

> Is it possible to somehow see the ffmpeg command line used for the cut operation, so that I can run it in cli myself and see what the error is?

yes, go to the help menu, it will show up at the bottom. Or open developer tools and you can see thel og

**Comment by trollcop** [comment]
On Thu, Sep 30, 2021, 18:11 Mikael Finstad ***@***.***> wrote:

> Here's the file which causes mp4 export to fail:
> https://drive.google.com/file/d/12aSOQooZby4PUwA83gm6aSkJNpVdITik/view?usp=sharing
>
> thanks, I tested your file and for me it works if I change to MOV. Was
> there a different problem?
>
if mp4 is selected it fails, but for me, after the mp4 failure, if the app
remained opened, any following conversion would fail by creating a 0 byte
file and "succeeding". but i can't repeat this again. i think i went mp4
mkv mov and all those just output 0 byte

> Is it possible to somehow see the ffmpeg command line used for the cut
> operation, so that I can run it in cli myself and see what the error is?
>
> yes, go to the help menu, it will show up at the bottom. Or open developer
> tools and you can see thel og
>
ok, I'll check this.

**Comment by mifi** [comment]
any update?

**Comment by mifi** [comment]
In the upcoming version, mov will automatically selected as the default output format when PCM audio exists #948
