### ISSUE TITLE
Potplayer bookmarks(.pbf) fail to import

### ISSUE THREAD

**Issue by taozi1996** [mifi/lossless-cut#867]
import project-Potplayer bookmarks(.pbf)  failed
Invalid pbf data found

I need Potplayer bookmarks(.pbf) parsed to .csv

examples
[pbf to csv.zip](https://github.com/mifi/lossless-cut/files/7221510/pbf.to.csv.zip)

**Comment by mifi** [comment]
In the upcoming version I did some changes that hopefully will fix this. If not let me know and I will reopen.
