### ISSUE TITLE
ffmpeg:convert to supported format

### ISSUE THREAD

**Issue by taozi1996** [mifi/lossless-cut#870]
V3.39.0

Batch convert to supported format
Should be changed to

fastest:remux
1.fastest:full quality remux(no audio)
ffmpeg -i [input] -c copy -map 0:v -map 0:s? -movflags +faststart -ignore_unknown -strict experimental [output]
It remux all original video and subtitle streams.

2.fastest:full quality remux(only one audio remux)
ffmpeg -i [input] -c copy -map 0:0 -map 0:1 -map 0:s? -movflags +faststart -ignore_unknown -strict experimental [output]
It remux one audio,all original video and subtitle streams.

3.fastest:full quality remux
ffmpeg -i [input] -c copy -map 0:v -map 0:a -map 0:s? -movflags +faststart -ignore_unknown -strict experimental [output]
It remux all original video,audio and subtitle streams.

fast:encode audio
4.fast:only one audio encode,lilely to failed
ffmpeg -i [input] -c copy -map 0:0 -map 0:1 -c:a aac -map 0:s? -movflags +faststart -ignore_unknown -strict experimental [output]
It encode one audio and keep all original video and subtitle streams.

5.fast:all audio encode,lilely to failed
ffmpeg -i [input] -c copy -map 0:v -map 0:a -c:a aac -map 0:s? -movflags +faststart -ignore_unknown -strict experimental [output]
It encode all audio and keep all original video and subtitle streams.

slow:encode video
6.slow:video encode,lilely to failed
ffmpeg -i [input] -c copy -map 0:v -c:v h264 -map 0:a -map 0:s? -movflags +faststart -ignore_unknown -strict experimental [output]
It encode only video and keep all original audio and subtitle streams.

7.slowest:video and audio encode,lilely to failed
ffmpeg -i [input] -map 0:v -c:v h264 -map 0:a -c:a aac -map 0:s? -c:s copy -movflags +faststart -ignore_unknown -strict experimental [output]
It encode vidoe and audio and keep original subtitle streams.

In most cases, the video whose audio is like ac3,eac3  will be no sound in preview.

example1
Meidainfo
RELEASE.NAME..: E01.1080p.NF.WEB-DL.DDP2.0.x264
DURATION..........: 01:16:53.308 (HH:MM:SS.MMM)
CONTAINER........: Matroska
VIDEO.CODEC...: x264 Main@L4 @ 6810 kb/s
FRAME.RATE......: 29.970 (30000/1001) FPS
RESOLUTION.....: 1920 x 1080
AUDIO.................: Korean E-AC-3 2 channels @ 128 kb/s
SUBTITLES.1.......: English/UTF-8
SUBTITLES.2.......: Arabic/UTF-8
SUBTITLES.3.......: Spanish/UTF-8
SUBTITLES.4.......: French/UTF-8
SUBTITLES.5.......: Brazilian/UTF-8
SUBTITLES.6.......: Thai/UTF-8
SUBTITLES.7.......: Turkish/UTF-8
SUBTITLES.8.......: Simplified/UTF-8
SUBTITLES.9.......: Traditional/UTF-8

ffmpeg -i "E01.1080p.NF.WEB-DL.DDP2.0.x264.mkv"  -c copy -map 0:0 -map 0:1 -c:a aac -map 0:s -movflags +faststart -ignore_unknown -strict experimental output.mkv

example2
Meidainfo
RELEASE.NAME...: test
CONTAINER.........: MPEG-TS 
VIDEO.CODEC.....:  AVC at 9 580 kb/s
FRAME.RATE........: 29.970 (30000/1001) FPS
RESOLUTION.......: 1920 x 1080
AUDIO.1................: AC-3 2 channels @ 192 kb/s
AUDIO.2.................: AC-3 2 channels @ 192 kb/s

ffmpeg -i test.ts -c copy -map 0:v -map 0:a -c:a aac -movflags +faststart -ignore_unknown -strict experimental  test.mkv

**Comment by mifi** [comment]
> It only encode audio and it will not use much time.

I'm not sure what you mean by that. Your examples also encode video to h264.

**Comment by taozi1996** [comment]
> > It only encode audio and it will not use much time.
> 
> I'm not sure what you mean by that. Your examples also encode video to h264.
If video that audio is like ac3,eac3 dts will be no sound in losslesscut.I think only encode the audio, we can hear the sound in the preview.

**Comment by mifi** [comment]
I think this can already be done with the current options or am i missing somethng?
<img width="464" alt="Screenshot 2022-01-15 at 00 56 58" src="https://user-images.githubusercontent.com/402547/149562610-6b6e27fa-5fbc-433f-83f5-5450b9063967.png">

these will encode the audio:
- Fastest: low playback speed
- Slow: Low quality encode
- Slowest: High quality encode

Are you proposing to add a new one like the following?
- Fast: Full quality video remux, low quality audio encode

**Comment by taozi1996** [comment]
> I think this can already be done with the current options or am i missing somethng? <img alt="Screenshot 2022-01-15 at 00 56 58" width="464" src="https://user-images.githubusercontent.com/402547/149562610-6b6e27fa-5fbc-433f-83f5-5450b9063967.png">
> 
> these will encode the audio:
> 
> * Fastest: low playback speed
> * Slow: Low quality encode
> * Slowest: High quality encode
> 
> Are you proposing to add a new one like the following?
> 
> * Fast: Full quality video remux, low quality audio encode

yes
