### ISSUE TITLE
Shortcut(s) don't have menu entries

### ISSUE THREAD

**Issue by MikeCowlishaw** [mifi/lossless-cut#876]
Hi, LosslessCut does exactly what I want ... select segments from a drone video, but I only found out how to do that and save the result by luck:

 a) select segments while the video plays  (this was OK, except the icons seem to be backwards?).

 b) export the selected segments to a new file.

The step (b) I only found by accident because it seems that it is only available as a keyboard short cut.   Surely it is so useful and important that it should be in the File or Edit menu?! 

Anyway, thanks for a nice piece of software!

Mike Cowlishaw
http://speleotrove.com/mfc/

**Comment by mifi** [comment]
Hi!

a) im not sure what you mean by backwards? Can you share a screenshot of the icon youre talking about?

b) the export button is the big blue button in the bottom right. I agree that it would make sense also to have it under the File-menu. Can add that.

**Comment by MikeCowlishaw** [comment]
a)  Screen shot attached .. I'm referring to the pointing hands below the
timeline.  I've always used a hand pointing to the right for the start of a
set of images (e.g., a sequence for a panorama) and a hand pointing to the
left to indicate the end.  Just personal preference, I suppose, but it did
confuse me for a while.
 
b)  No idea how I missed that button!   Too busy going through all the
menus, I suppose!!  Thanks.
 
 
Thanks again for the program .. it's just what I need.  MovieMaker was
driving me crazy as it's so slow ...
 
Mike Cowlishaw
http://speleotrove.com/mfc/
 
 
 


  _____

**Comment by mifi** [comment]
a) I can't see your attached screenshot, but the pointing hands has been suggested a change by other people also. I'm tracking it in the issue: #625 - so I will close this. thanks!
