### ISSUE TITLE
[Feature Request] View timestamps as frame count

### ISSUE THREAD

**Issue by Avasam** [mifi/lossless-cut#878]
**Is your feature request related to a problem? Please describe.**
No

**Additional context**
I'm a speedrunner. So I record hours of footage only to take a few minutes out of it to highlight when I beat my personal best.
I've also been using LossLess cut to frame count since I can get an exact start and end point for segments, without having to do the math myself.

**Describe the solution you'd like**
While I've mostly just needed the exact timing down to the hundreth of a second, it would also be beneficial to be able to see the time as frames (current, total, segment length).

**Comment by mifi** [comment]
Hi. Where do you want to see frame count? Did you try to enable frame timestamps inside settings?

**Comment by Avasam** [comment]
If you mean the following setting, I don't see any differences.
![image](https://user-images.githubusercontent.com/1350584/135763724-95a5d436-82ab-4ea6-8cc7-ff135e3a4efc.png)

I'd mainly like to be able to see the current frame on the timeline.
Somewhere else that would be nice is segments total, but I'd very rarely use it as I just realized segments do show framecount and I can add them up.
![image](https://user-images.githubusercontent.com/1350584/135763721-24f3100a-3e54-43ee-9d24-dbf314a8eb8f.png)

Switching between timestamp and frames can also work.

**Comment by Eisa01** [comment]
It would be nice to see this in the export options as well.
e.g.:
`File` > `Export Project` > `Keyframes (CSV)`

**Comment by Eisa01** [comment]
@mifi I just noticed that I typed keyframes instead of frames.
What I mean is exporting the frames of the created segments.

It will be similar to exporting `LosslessCut (CSV)` but will use the frames format.

`LosslessCut (CSV)` Example:
```
3.766,7.56
19.3,23,
36.66,40.8,
```
`Frames (CSV)`  (30fps video) Sample:
```
113,227
579,690,
1100,1224,
```

**Comment by mifi** [comment]
Ah. Yes I agree that makes sense.

**Comment by mifi** [comment]
ok both of these are now implemented and will be included in the upcoming release!
