### ISSUE TITLE
Eye candy features making LosslessCut slow on some computers

### ISSUE THREAD

**Issue by infuse2001** [mifi/lossless-cut#880]
In order to make it easier for me to help you, I ask that you please try these things first:
- Try with the newest version from GitHub: https://github.com/mifi/lossless-cut/releases/latest
- Check https://github.com/mifi/lossless-cut and **Known issues** / **Troubleshooting**
- Search for your problem under Issues or Discussions
- Please try other type of file and see if it works.

**Share information to help me understand**
- If you have an issue cutting a particular file, please also share the file, if possible. (or mail a link to finstaden@gmail.com if private.) Also please try to cut it with the ffmpeg command line directly.
- If you have a problem or an unexpected bug or crash, please open developer tools after starting LosslessCut and before doing the failing operation. Then share the output from the javascript Console. (Menu: Tools > Toggle Developer Tools)
- Please provide the error report if you got one (Menu: Help -> Report an error)

**Describe the bug**
LosslessCut is an amazing tool, but it has eye candy features that adversely affect it's productivity on less powerful computers. Specifically while constantly pressing Alt+-> to key jump forward or back:
1. The cursor takes it's own time to move forward trying to move smoothly. It should JUMP to the next keyframe marker without STEPPING THROUGH the interim duration. Playback software like KM Player, Pot Player, VLC etc jump to the target frame and do NOT use smooth scrolling making their navigation efficient. 
2. On a zoomed in timeline, the "Show keyframes" feature shows only some frames ahead of the cursor (and some behind). When the cursor reaches the last keyframe shown, it pauses till further keyframe markers are created on the timeline. This slows the move process dramatically. 
3. When the cursor reaches the end of the screen, the entire timeline scrolls forward, again stepping/smooth scrolling through the entire duration of the move. The timeline should JUMP to the next screen alignment without smooth scrolling. 
4. The image shown for the current position of the cursor should be shown for each keyframe the cursor is on either forcefully or optionally using a settings parameter. Currently, the image is NOT shown for each keyframe jumped, but one needs to pause a bit for the image to be updated to see where we are in the video file. This issue essentially defeats the Jump by Keyframe feature. 
5. When the "I" key is pressed a new segment bar is created. The color shading of that bar is also smooth changed in at least 4 steps, again reducing the app's productivity. The bar should be created instantly in the final shade. 
6. When the Cut End key "O" is pressed, the end of the segment bounces to the start of the shown frame, then bounces to the last of the shown frame and then stops at the Cut End frame selected. This eye candy feature should also be optional at best. 
7. Lossless Cut slows down even more as the number of segments increases, particularly over 100 segments. 
 
**To Reproduce**
1. Open file '...'
2. Click on '...'
3. See error

**Expected behavior**
All the above dramatically and adversely affect productivity in selecting segments to keep in the video being edited. This is especially true if there are many segments to keep in a longer video. 
Try navigating using left/right arrow keys on a computer with Lossless Cut as well as KM Player installed and a 1.5 GB movie. KMP is responsive while Lossless Cut is very sluggish. 
ANY and ALL smooth scrolling/eye candy features adversely impact productivity. Please remove them, if not as default then as an option. Please. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 7 Professional, x64, SP1
 - Lenovo 2518CGM ThinkPad T410
 - 2.53GHz Intel Core i5 M 540
 - RAM 8052MB usable memory

**Additional context**

**Comment by mifi** [comment]
closing in favor of #371 - i moved it there, to keep issue count down

**Comment by mifi** [comment]
next nightly build will contain a lot of these improvements
