### ISSUE TITLE
Alt key constantly activates File menu

### ISSUE THREAD

**Issue by infuse2001** [mifi/lossless-cut#881]
In order to make it easier for me to help you, I ask that you please try these things first:
- Try with the newest version from GitHub: https://github.com/mifi/lossless-cut/releases/latest
- Check https://github.com/mifi/lossless-cut and **Known issues** / **Troubleshooting**
- Search for your problem under Issues or Discussions
- Please try other type of file and see if it works.

**Share information to help me understand**
- If you have an issue cutting a particular file, please also share the file, if possible. (or mail a link to finstaden@gmail.com if private.) Also please try to cut it with the ffmpeg command line directly.
- If you have a problem or an unexpected bug or crash, please open developer tools after starting LosslessCut and before doing the failing operation. Then share the output from the javascript Console. (Menu: Tools > Toggle Developer Tools)
- Please provide the error report if you got one (Menu: Help -> Report an error)

**Describe the bug**
1. Since the Alt key +-> is used to navigate Keyframes, the issue is that the Alt key constantly activates the File menu of the program. This locks up the program until the ESC or Alt key is pressed a couple of times to cancel this. 
2. Using the Alt+-> keys requires using both hands to navigate key frames. This should be changed to enabling using a single hand for navigation. 
3. Perhaps a key mapping facility could be provided making it easy for anyone to use any key for any action. 

**To Reproduce**
1. Open file '...'
2. Click on '...'
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]

**Additional context**

**Comment by mifi** [comment]
tbh I don't know to fix this because it's a feature in windows. But now as of latest version there's custom keyboard mappoings so you can use another key combo for it

**Comment by infuse2001** [comment]
Sorry,me too,I dontknow how to fiz this

**Comment by mifi** [comment]
@infuse2001  you can change the hotkey to something else in the newest version
