### ISSUE TITLE
Remember excluded clips (selected/deselected segments)

### ISSUE THREAD

**Issue by SignpostMarv** [mifi/lossless-cut#885]
**Is your feature request related to a problem? Please describe.**
Needing to entirely shut the computer down (as opposed to suspending) when the spreading the time spent clipping videos over several days means having to manually restore clips that need to be excluded.
For reference, sometimes the actual process of clipping is done, but it's more convenient to refer back to the GUI to copy & paste clip titles out into other programs than it is to export a CSV & copy text that way.

**Describe the solution you'd like**
Have LosslessCut automatically save the include/exclude flag to the LLC format, and/or as a new field in the CSV

**Describe alternatives you've considered**
- ~~inventing a perpetual motion machine such that the computer never need be shut down~~
- ~~running LosslessCut inside a VM such that the state can be suspended/resumed & allowing the host computer to be shut down~~
- ~~depriving oneself of sleep to get hours of clipping done in one sitting~~

**Comment by SignpostMarv** [comment]
going to add "when you accidentally trigger a BSOD" to the scenarios where exclude restoration would be useful.

**Comment by mifi** [comment]
i put this in #371 - closing this issue

**Comment by mifi** [comment]
next version will have this
