### ISSUE TITLE
Cursor location in video file should be shown as a percentage OR total video duration should be shown throughout

### ISSUE THREAD

**Issue by infuse2001** [mifi/lossless-cut#888]
Please first search for your feature request under Issues or Discussions, maybe someone else already suggested it.

**Is your feature request related to a problem? Please describe.**
I normally use the "z" key to show keyframes in an expanded time line view. From then, I use the Alt+-> key to navigate keyframes. At that time I am lost as I do not know how much of the video I have traversed. 

**Describe the solution you'd like**
I would like to see a percentage counter showing where in the video the cursor is at present. The cursor time is shown prominently on the segment bar but the total duration of the video is not shown once cutting starts. Either of the above: Percentage Counter or Total duration of the video shown at all times, will solve this problem.

**Describe alternatives you've considered**
1. I keep having to press the "z" key to show 1x zoom to view the location of the cursor. And then again press "z" to show the expanded time line to continue editing. 
2. An alternative is to add a new segment. The Cut End counter then shows the time at the last frame of the video. If not required, the new segment can be removed via the backspace key. 

**Additional context**

**Comment by mifi** [comment]
will now show percent:

<img width="236" alt="Screenshot 2022-01-15 at 17 11 42" src="https://user-images.githubusercontent.com/402547/149618081-1aa683dc-593b-4127-aa51-09802b4f1d57.png">
