### ISSUE TITLE
Option to disable blurring of the background in a dialog

### ISSUE THREAD

**Issue by kkhalme** [mifi/lossless-cut#890]
**Is your feature request related to a problem? Please describe.**
The problem with blurring the background hides the video preview, which in some cases could contain important information for naming the exported file. In my case, the exported video name would contain a piece of letters visible in the video that I now have to write down somewhere else first.

**Describe the solution you'd like**
Option in the settings to disable this blurring feature.

**Describe alternatives you've considered**
Nothing. Very simple toggle enable-disable feature for an existing feature.

**Additional context**
-

**Comment by mifi** [comment]
closing in favor of #371 to keep issue count down
