### ISSUE TITLE
File Selection Dialogue: option to chose which file browser to use

### ISSUE THREAD

**Issue by coaxx77** [mifi/lossless-cut#892]
Please implement an option let user change File Browser dialogue. I really wouldt like to use my default File browser dialogue (being on a arch KDE Plasma distro here).

**Comment by mifi** [comment]
LosslessCut uses the built in electron/chromium selection dialog. See here: https://www.electronjs.org/docs/latest/api/dialog
As far as I can see the API doesn't have any option to select which style to use, so not much I can do about that. Closing this, but if you can find a super easy way to do this, I could reopen.
