### ISSUE TITLE
Exporting multiple segments ignores the base filename

### ISSUE THREAD

**Issue by dandv** [mifi/lossless-cut#894]
I'm sure this must've been observed already, but I couldn't find a similar issue.

**Describe the bug**
Using 3.39.0, if I export more than one segment, I expect the resulting filenames to be based on the "Output name(s)" set the in Export Options dialog. Instead, they're based on the input filename.

**To Reproduce**
1. Open a file.
2. Create 2 or more segments.
3. Click Export.
4. Set an output name.
5. Click Preview. **Notice the names are identical.**
6. Export. Notice the output filenames start with the input filename (in my case `DJI_0197-00.00.00.000-00.01.14.073-seg1.MP4` and `DJI_0197-00.01.30.090-00.02.36.156-seg2.MP4`, rather than with the "Output name(s)")

**Expected behavior**
In the screencast, I'd expect the output filenames to be something like "Fly along shore 1.mp4" and "Fly along shore 2.mp4", or with the time intervals instead of `1` and `2`.

**Screenshots**
![Exporting multiple segments ignores the base filename](https://user-images.githubusercontent.com/33569/138417738-6e9e77d5-e6b4-4968-8d2c-7919684121c4.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20

**Comment by mifi** [comment]
have now fixed so that it will also show an error if there are duplicates. will still show not show the actual output filenames however, because then it would be harder to know why the template results in an error
