### ISSUE TITLE
allow to pass filename in command line

### ISSUE THREAD

**Issue by mvreg** [mifi/lossless-cut#9]
It would be great if program could auto-open file passed in command line parameter (we would than start this from another program) - at least for windows version.

example:
LosslessCut.exe X:\cut_135611_136858_Time-2016-10-26_18_00-Nova-TV2016-10-2618-00.mp4

**Comment by mifi** [comment]
This should be easy to implement so I'll do it when i have time.

**Comment by mifi** [comment]
Fixed in 1.3.0
Note: You need absolute path

**Comment by rien333** [comment]
> Note: You need absolute path

Neat feature, but the dependence on absolute paths is a bit unnatural and cumbersome. Any change of supporting regular file passing?
