### ISSUE TITLE
[bug?] Changing export folder for output sets working dir when unset/automatic

### ISSUE THREAD

**Issue by Wiethoofd** [mifi/lossless-cut#905]
I want to be able to use the default behaviour where the .llc (previously .csv) is stored next to the video file in the same folder (no working dir set), but when exporting still be able to use a different output folder.

Currently when there is no working dir set the .llc is with the video file, but then on export as soon as you change the output path for the video (doing that on an SSD instead of HDD where the video file is stored) it also sets a working dir and moves the .llc to the now set output folder.

Then the only way to clear the working dir being set is through the interface top right, where it is impossible in the settings to _clear_ it, you can only set a working dir to a different location or to the same folder, instead of it automatically defaulting to the same folder the video file is in (sometimes causing duplicate and mismatched .llc files in 2 folders.

**Comment by mifi** [comment]
Actually this is not a bug, it's how it's always worked. LosslessCut saves all files to the selected working directory. I'm open to maybe always storing it alongside the input file. I do have a fear that some people expect it to be saved to the output directory, but maybe not too many. Also they can still use the `File -> Export project (LLC)` function to manually save it in the working directory (the save dialog could default to the working directory). Or we could have an extra menu item (or assignable keyboard shortcut) to save the LLC to the working folder

**Comment by Wiethoofd** [comment]
It is inconsistent behaviour with most other programs where you pick 'Save as..' (actually rendering your output from the video) and it suddenly changes your working dir from default to the same location as your saved file and the .llc moves.

I do like the option where to put the .llc project file and pehraps, which (temp) folder to use for the output if not the working dir.

**Comment by mifi** [comment]
Alright, I've changed the behavior now. I don't see any good reason to save the llc file next to the output file. If too many people complain I can make it configurable.
