### ISSUE TITLE
[Feature request] improve output filename serialize

### ISSUE THREAD

**Issue by taozi1996** [mifi/lossless-cut#906]
now 
output number
${SEG_NUM}   1 2 3 4  5 6 7 8 9 10 

serialize
${SEG_NUM:2}  01 02 03 04 05 06 07 08 09 10 
${SEG_NUM:3}  001 002 003 004 005 006 007 008 009 010

**Comment by Aleks-Ya** [comment]
Now it's really annoying to add leading zeros manually. Looking forward to this enhancement implementation.
