### ISSUE TITLE
Auto segmenting is forming incorrectly

### ISSUE THREAD

**Issue by ibrahimyuce07** [mifi/lossless-cut#909]
![image](https://user-images.githubusercontent.com/71738080/139539079-11e0d119-9577-417c-b420-d2b1f8265912.png)

If I separate a file with 5 mins, for example, segment start and end times are the same. And this makes 0-second segments.

**Comment by mifi** [comment]
Hi. Try to toggle the "yin yang" symbol

**Comment by ibrahimyuce07** [comment]
Thanks. The issue is solved so fast. You are great. <3
