### ISSUE TITLE
Video ends prematurely after merging, part missing

### ISSUE THREAD

**Issue by ruckax** [mifi/lossless-cut#911]
Hello guys, 

sometimes (but not always) when I use Losslesscut 3.39 to merge different MP4 videos, part of the video is missing at the end in the merged video. 

The two individual videos are together 1:52:39 long, but the merged video is only 1:48:56 long. 

I have also tried versions older than 3.39, everywhere the same problem. 

How can I solve this? Is the problem already known?

Thanks a lot in advance for helping. 

Best regards

ruckax 

#############

No error

{
  "state": {
    "filePath": "",
    "externalStreamFiles": [],
    "mainStreams": [],
    "copyStreamIdsByFile": {},
    "cutSegments": [
      {}
    ],
    "rotation": 360,
    "shortestFlag": false
  },
  "platform": "win32",
  "version": "3.39.0"
}

**Comment by mifi** [comment]
hi. how many tracks does your file have? could you try to first run them through losslesscut and remove any track except the video and try to see if the merge works then.

**Comment by mifi** [comment]
closing due to lack of feedback
