### ISSUE TITLE
Files are not closed correctly

### ISSUE THREAD

**Issue by ComplexP2** [mifi/lossless-cut#912]
**Description:**
When I close a file (after doing some cuts and exporting the merged result), I cannot move the source file to another folder or rename it, because Windows Explorer tells me that "the file is still opened in LosslessCut".
I'm using the current version 3.39.0

**I can reproduce the issue as follows:**
1. File -> Open: select some mp4 file (the source file)
2. Select a section of the video and export it (settings see screenshot below)
3. File -> Close
4. Do not close LoslessCut
5. In Windows Explorer: Try to rename or move the source file -> Error

**Export settings:**
![image](https://user-images.githubusercontent.com/93616842/139944036-a4d970d0-92f4-471f-b7a1-0fa5f6c554eb.png)

**My system:**
 - OS: Windows 10

**Further notes:**
Using the tool LockHunter, I can actually see that LosslessCut is really still locking the file. Also, I can use LockHunter to unlock the file (see screenshot) and after that, I can rename/move the file as expected:
![image](https://user-images.githubusercontent.com/93616842/139943557-f12bd67d-c551-4017-8111-a9a921e04b24.png)

**Comment by mifi** [comment]
Thank for your testing. This is a dup of #272 
Is the file you are using «not natively supported» or does it play back without any such message? I think it may be related to https://bugs.chromium.org/p/chromium/issues/detail?id=969049
