### ISSUE TITLE
How to attach cover art?

### ISSUE THREAD

**Issue by Kimi-Arthur** [mifi/lossless-cut#913]
Sorry I didn't use the template. It's basically a question.

I see in your description that it can attach a cover art, but I cannot find the option anywhere. I tried to add the file as a track and choosing an option like attached_pic but doesn't seem to work. Any suggestion on how to use that feature or where should I look for documentation on that?

Thanks!

**Comment by mifi** [comment]
I assume you tried this: https://github.com/mifi/lossless-cut/issues/673#issuecomment-907094209

Are you using mp4 as your output and is your cover art a JPEG? I don't know if attached_pic works on anything else than mp4
if it still doesn't work, maybe try with a different file (aac) and/or a different jpeg file, to experiment and see what's causing it to not work.

**Comment by mifi** [comment]
I created a tutorial video here on how to do this: https://www.youtube.com/watch?v=4pYJ93cn80E
