### ISSUE TITLE
Ask before overwriting

### ISSUE THREAD

**Issue by ospeltz** [mifi/lossless-cut#916]
Hey I didn't see anything in the settings about this, but it would be great if the app could ask for confirmation before overwriting files. Currently it overwrites files with the same name silently, which causes me great anxiety when I am cutting up a bunch of footage at once and labeling it based on the contents of the clip. Sometimes my names aren't super unique. Just a thought, thank you! I love this app

**Comment by mifi** [comment]
This is why the app originally only outputted files with a long suffix, to reduce the chance of accidentally overwrite files. But now that output names are customizable I agree it makes sense to somehow prevent overwriting
