### ISSUE TITLE
Lossless cut does not work on Mx Linux debian 10

### ISSUE THREAD

**Issue by Rick654** [mifi/lossless-cut#918]
Greetings! I downloaded your appimage for my MX linux debian 10 (32 bit), made it executable, but the program doesn't start. How to solve? Thanks

**Comment by mifi** [comment]
hi. can you provide some more info. in `ps ax` there is nothing there? any error if you run it from the command line?

**Comment by Rick654** [comment]
Bye! If I launch it, nothing happens and it creates an empty text file in the Home, with the name "Invalid Encoding".

**Comment by mifi** [comment]
no log output from the command line either? if you run `chmod +x losslesscut && ./losslesscut` which arch are you running?

**Comment by mifi** [comment]
download this: https://github.com/mifi/lossless-cut/releases/download/v3.39.0/LosslessCut-linux.tar.bz2
then unpack it and run it from the command line

**Comment by Rick654** [comment]
Sorry I'm late MIfi. I launched from the terminal from the unzipped folder, the result is this: **losslesscut
bash: losslesscut: command not found**
Thanks

**Comment by SMooxx** [comment]
> download this: https://github.com/mifi/lossless-cut/releases/download/v3.39.0/LosslessCut-linux.tar.bz2 then unpack it and run it from the command line

after uppacking this file and setting the permission suggested, it works for me. so how do I do if I install losslesscut via snap or download as AppImage to make it work?

**Comment by mifi** [comment]
I'm sorry but I cannot provide support for all different linux flavors, but I think the clue is to make the file it executeable, and possibly need to disable some security features in the linux distro. I'm closing for now but feel free to provide more info (an error message at least) and I can revisit it if still a problem
