### ISSUE TITLE
Can't change hotkeys, hotkeys won't work in non-English layout

### ISSUE THREAD

**Issue by Zrrg** [mifi/lossless-cut#919]
Changing hotkeys would be really helpful for anyone who uses custom hokeys preset at work, like me. 
If I try to use hotkeys in layout other than English (Russian in  my case) it won't work.

I have high hopes for this software, but all I need to use it as "swiss army knife" is these features. Thanks.

**Comment by nosferatu500** [comment]
Автор использует Mousetrap, который работает только с английской раскладкой. Были попытки использовать react-hotkeys-hook, который работает независимо от раскладки (в том числе и с русским проблем нет), но и с этим компонентом, насколько я помню, были проблемы, поэтому было принято решение вернуться на Mousetrap.

**Comment by mifi** [comment]
I'm working on customizable keyboard shortcuts but it's not done quite yet. Closing in favor of #254
