### ISSUE TITLE
[Request] Adding a tip to show time when mouse is on the progress bar.

### ISSUE THREAD

**Issue by kaikaiiiiiii** [mifi/lossless-cut#92]
It will be much easier when seeking some precise time to set start/end point.

The "timestamp where mouse is hover" can put on the very left/right of the progress bar, or be a hover tip aside to the mouse cursor.

**Comment by mifi** [comment]
Can't you use the red cursor (click+drag?) it shows the time when dragging

**Comment by kaikaiiiiiii** [comment]
Thanks for reply.

1. Actually I can't.  (Windows 10 x64 1709) I just tried but no response when dragging. It will jump to the time where the mouse release the left button, but won't do anything when mouse button down & dragging.

2. I used a video player to seek and decide segments I want to cut. In this case, I already know the time of start & end point. So it would be much easier if lossless-cut showed time where mouse hovered on the progress bar.

**Comment by mifi** [comment]
Do you have the newesr version?

**Comment by kaikaiiiiiii** [comment]
> Do you have the newesr version?

Hey, I tried new version today.

I can drag the red line, by holding mouse left button down. It works. Confirmed.

I noticed that you use div.current-time to show the red line. Actually I posted this issue is to ask if you can add another marker, a div called "mousehover-time", like this:

![losslesscut_kffccwxoms](https://user-images.githubusercontent.com/1635138/51074686-d386cb80-16bc-11e9-8dd5-aa6e50001dc1.png)

May I explain below.

Though using ffmpeg, lossless-cut still be lag when open / drag / seeking progress on some big video files. For example, some games' screenrecord videos by shadowplay by nVidia.

I still prefer using a normal video player, like MPC、PotPlayer to seeking the best point to cut, then back to LLC to mark the time point to cut.

So it would be much convenience to "hover & seeking time point" than "drag with lag to seeking time point". A green mark to show what time where the point mouse stayed, is what I want.

I'm not blaming lag, it's not LLC's fault. It's just much easier to add a marker than to spend a lot time to optimize.

**Comment by mifi** [comment]
I agree. This is a useful feature. Will look into it

**Comment by KoolKeith** [comment]
I vouch for this little request. It's important.

**Comment by mifi** [comment]
This is now implemented

**Comment by doximanman** [comment]
> This is now implemented

Sorry for bringing up an old post, but is this still a thing? When I'm hovering over the timeline I don't see the time. Is there a setting I need to change? I couldn't find one.
![image](https://user-images.githubusercontent.com/56520848/197385590-f3e3d5d1-e74e-453b-b531-f8e203e5e099.png)

**Comment by mifi** [comment]
@doximanman I do not recognise your screenshot. which app is that?

**Comment by doximanman** [comment]
> @doximanman I do not recognise your screenshot. which app is that?

Oh my bad. I googled "potplayer time on hover" and this is one if the first results so I just assumed it was potplayer. 
I deleted my comment.
