### ISSUE TITLE
audio shifting/synching

### ISSUE THREAD

**Issue by gyarmish** [mifi/lossless-cut#929]
Often a video has the audio unsynched. This would require a small shift such as moving the audio -300 ms. 

This can be done now losslessly as follows:  
1. extract the audio 
2. open only the audio in losslesscut and trim the first 300 ms off 
3. export this as a new audio file. 
4. open the original video add a third track (the new audio)
5. export only the video and new audio tracks (without the original unshifted track).

Suggestion is to allow the waveform to shift independently of the video.  
Its lossless and wont require the user to make multiple files of importing and exporting.

**Comment by gyarmish** [comment]
In addition to its usefulness - part of the reason for the post was to show how it can be implemented in a new release - its quite tedious manually but it can be automate this behind the scenes using the standard lossless functions.

**Comment by Adoomy76** [comment]
Thank you for this solution it is very helpful
