### ISSUE TITLE
Cant install APPX untrusted app no certificate 

### ISSUE THREAD

**Issue by tidypy** [mifi/lossless-cut#933]
cannot install: Install button 'greyed out' 
Install error:
This app package is not signed with a trusted certificate. 
Contact your system administrator or the app developer to obtain a new certificate or app package with trusted certificates. 
The root certificate and all immediate certificates of the signature in the app package must be trusted (0x800B010A)

![image](https://user-images.githubusercontent.com/50213641/143301557-e5e3da36-c6ee-4334-86b6-b0a1eaf4f907.png)

**Comment by mifi** [comment]
yea unfortunately windows doesn't allow installing unsigned appx. I use appx only for submitting to Microsoft Store, and I don't know how to sign it. See #337

**Comment by oghaki** [comment]
I thought about trying this, not really sure how it works though.  Last release was 26 May 2021, but there are commits within the last year.  

[appx-util](https://github.com/OSInside/appx-util)
──────────────────────────────────────────────
`appx is a tool which creates and optionally signs Microsoft Windows APPX packages.`

**Comment by mifi** [comment]
See #337
