### ISSUE TITLE
Start of cut is off-by-one keyframe

### ISSUE THREAD

**Issue by HerwigHenseler** [mifi/lossless-cut#939]
Hi developers,

LosslessCut Version 3.39.0, tried it on macOS and Windows, bug is reproducible.

Also tried 3.30.0 to see if this bug was introduced just recently, but it was also in the older version.

Video is H264 - MPEG-4  AVC 60fps, created by OBS.

Reproduced with several different mpgs of different lengths.

When cutting segments as keyframe cuts, the start of the segment is not as indicated in the GUI. Instead, the start is the keyframe prior to the indicated cut.

See attached screenshot.

<img width="912" alt="Bildschirmfoto 2021-11-29 um 11 11 05" src="https://user-images.githubusercontent.com/14800844/143848751-3e27a9f9-3bd5-4c3d-8bfb-41ccdd6a47db.png">

- Open a file
- Click e.g. between second and third keyframe
- click on the "previous keyframe" key symbol -> start is adjusted to second keyframe
- click on "set cut start" left-pointing finger
- export

In the screenshot, the exported segment should start at keyframe 3, include keyframe 4 and should stop there. The resulting length should be 6.199 secs. This is correctly represented in the filename: 2021-11-24 09-55-41-00.00.08.332-00.00.14.532

Bug: The resulting file instead starts at keyframe 2 and is 10 seconds long. Off-by-one keyframe.

Regards,
Herwig

**Comment by Avasam** [comment]
Same issue here! So I won't open a new issue.
The start of the cut is always 1 keyframe too early. MKV recordings from OBS.

**Comment by mifi** [comment]
I think this is a known issue and hard to solve because different codecs/formats/framerates work differently. Does it work if you seek 1 frame (not keyframe) to the right before setting the cut point?
If so, I will close this as a duplicate of #330 - [see my last comment there](https://github.com/mifi/lossless-cut/issues/330#issuecomment-1009702161)

**Comment by HerwigHenseler** [comment]
Yes, adding one frame (by pressing .) results in the cut no longer off-by-one.

Judging from the linked issue, I see that this is not a problem with LosslessCut per so but instead of the underlying ffmpeg which gets confused. Therefore, fixing this is not an option for you.

Since several people have encountered this effect you may document this behaviour more prominently so it does not come up all the time :-)

Regards,
Herwig

**Comment by mifi** [comment]
Yep. I will try to make some improvements to make it less confusing. Just need to find a solution that works consistently for all files

**Comment by Avasam** [comment]
> add option to shift cut start frames

added in https://github.com/mifi/lossless-cut/releases/tag/v3.61.0 essentially resolves this issue! a +4 frames seems to work consistently for my OBS mkv recordings
