### ISSUE TITLE
Convert to Friendly Format or Codec strips audio

### ISSUE THREAD

**Issue by berts83231** [mifi/lossless-cut#94]
The feature that converts the video strips the audio. I've tested the fast & slow method across several file types including .mp4, .avi and .mov. I've also tested it on Ubuntu & Windows.

I have ffmpeg installed. If you tell me what to run on the command line, I can provide the output and sample files.

Thanks

**Comment by mifi** [comment]
The reason I strip audio is to make it faster (by not having to also encode audio). We could make another menu option which preserves audio but will be slower?

**Comment by berts83231** [comment]
Another option might be to convert only a clip of the video. At the end of the day, the main reason I am using this tool is to get a smaller a clip.

I would be working blind. But I could preview the video in VLC to get the relevant start/stop points.
But this might start to clutter the UI.

**Comment by mifi** [comment]
> Another option might be to convert only a clip of the video. At the end of the day, the main reason I am using this tool is to get a smaller a clip.

I'm not sure if I understand

**Comment by mifi** [comment]
But then what to show in the main player? Also how to get the start/end time of the clip to pre-convert? I think the html5 player will not work at all with the raw file

**Comment by bikelike** [comment]
With the footage of my DJI Mavic Air (mp4) LosslessCut works like a charm. Really easy with the shortcuts. However my DJI Osmo Pocket files, also mp4, will load but not export. The label about friendly format appears, very briefly btw.

I may not quite understand the Friendly format and sound thing. Indeed my sound is gone and when I opt for a slower conversion, there is also no sound and the frame size is minuscule. So how can I trim, whilst keeping the sound?

Thanks for an answer and the whole project!

**Comment by mifi** [comment]
If you convert to friendly format, and then export, does the output also not contain any audio?

**Comment by bikelike** [comment]
Both friendly options result in no sound. Anyhow I don't understand why ffmpeg cannot handle the files. Can I send you an example?

**Comment by mifi** [comment]
Sure, upload somwhere and i can check it out

**Comment by bikelike** [comment]
Thanks, I WeTrensfered you.

**Comment by mifi** [comment]
Toggle "all" to "ps" and it works

**Comment by mifi** [comment]
This also seems to be related to format detection of latest version of `file-type`. See #173 
When i tried your file with `all` and mov it works, so it seems that is the main issue.

As for strippoing audio i should make it more clear that this only happens for the preview, not the actual outputted file.

**Comment by mifi** [comment]
Have implemented the option to choose output format in the newest version.

**Comment by themysciraa** [comment]
Hi @mifi,

First off, losslesscut is a great application! It has helped me and saved a lot of time for me to cut multiple clips from a single video.

I'm using the latest 2.4.0 on Mac OS and I have the same problem with bikelike where the audio is stripped when I convert a mkv video to friendly format or friendly codec (ps: friendly codec shrinks the original 4K video resolution to about 480p). Also, I can't find the place to choose output format. Hope you can help me

**Comment by Zovereign** [comment]
Is there going to be an option to convert with audio?

**Comment by mifi** [comment]
implemented in neweest
