### ISSUE TITLE
Can it cut in batches by time? For example, cutting every 10 seconds

### ISSUE THREAD

**Issue by linsamasama** [mifi/lossless-cut#942]
Please first search for your feature request under Issues or Discussions, maybe someone else already suggested it.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mifi** [comment]
Yes. Edit -> Segments -> create fixed duration segments
note that cuts will not be accurate but rounded to the previous keyframe when exporting.
