### ISSUE TITLE
Make the buttons easier to hit.

### ISSUE THREAD

**Issue by WasfiJ** [mifi/lossless-cut#946]
Just removed a useless phrase at the beginning of 47 videos : this software is a life-saver !
Please make the buttons (set start/end segment, play, pause,..) easier to hit: (much !) bigger and further apart !
This was my only frustration with LosslessCut, should be easy enough to do.
Thank you for a wonderful tool.

**Comment by mifi** [comment]
Thanks for your feedback. It's very valuable. Will definitely look into improving this

**Comment by mifi** [comment]
I have now increased size of all these controls and it will be avail in the next version. See screenshot:

<img width="846" alt="Screenshot 2022-02-19 at 17 34 57" src="https://user-images.githubusercontent.com/402547/154795356-8ae7d49d-7675-4e27-9a91-2ca517004af7.png">

**Comment by WasfiJ** [comment]
Thank you, that's definitely "bigger", sort of.. and slightly further apart.
That's definitely **not** "much bigger", though ! Some sniping for buttons might be needed still :)

**Comment by mifi** [comment]
I feel like buttons are almost the same size as other apps I use every day now with the new increase, but I do understand it can be a bit tricky to hit still. I think https://github.com/mifi/lossless-cut/issues/403 could probably improve the problem if the whole ui size could be increased by the user. put a comment here later after you tested the upcoming version if you think it's still an issue, and I can revisit this

**Comment by WasfiJ** [comment]
Will do. 
I didn't dare ask for it, but the notion of "big enough" being subjective, the real solution is a customizable size (or maybe 3 or 4 layouts to satisfy most tastes).
Being a developer myself, I know it's easy to ask for features from an armchair.. Having a responsive developer who listens and tries is already a great blessing !

**Comment by WasfiJ** [comment]
Just tested v3.43.0. Definitely better !
Thank you very much. This little cutter is so freaking practical, great tool !
