### ISSUE TITLE
Videos from the Lumix FZ-2000 - cannot Export the cutted file

### ISSUE THREAD

**Issue by Thomas-Huppertz** [mifi/lossless-cut#947]
hello,

I tried to cut files from my FZ-2000, 4K/30fps, but they will not get exported.
When deactivating the audio it works! 
The informations for the audio are:
     audio | twos | pcm_s16be | 1:30 | 4324320 | 1.5MBit | und | 2c

Appended the longer informations about the audio and the bug-report after the error-message.
Hope that helps, to explain or to find the but?
Thank you,
    Thomas

or longer informations are:

{
  index: 1,
  codec_name: 'pcm_s16be',
  codec_long_name: 'PCM signed 16-bit big-endian',
  codec_type: 'audio',
  codec_time_base: '1/48000',
  codec_tag_string: 'twos',
  codec_tag: '0x736f7774',
  sample_fmt: 's16',
  sample_rate: '48000',
  channels: 2,
  bits_per_sample: 16,
  r_frame_rate: '0/0',
  avg_frame_rate: '0/0',
  time_base: '1/48000',
  start_pts: 0,
  start_time: '0.000000',
  duration_ts: 4324320,
  duration: '90.090000',
  bit_rate: '1536000',
  nb_frames: '4324320',
  disposition: {
    default: 1,
    dub: 0,
    original: 0,
    comment: 0,
    lyrics: 0,
    karaoke: 0,
    forced: 0,
    hearing_impaired: 0,
    visual_impaired: 0,
    clean_effects: 0,
    attached_pic: 0,
    timed_thumbnails: 0,
  },
  tags: {
    creation_time: '2021-11-29T17:41:48.000000Z',
    language: 'und',
    timecode: '05:17:03;02',
  },
}
OK

The whole report after the error-message is:
Error: Command failed with exit code 1: C:\Users\thupp\AppData\Local\Temp\1xMTtfMQLboD7r4ebGikn7zfvcn\resources\node_modules\ffmpeg-ffprobe-static\ffmpeg.exe -hide_banner -ss 37.01266 -i C:\AAA-Fotos\20211129_MS-Videos\SOG-Julia-Regina\P1080826.MP4 -t 50.44689 -avoid_negative_ts make_zero -c copy -map 0:0 -map 0:1 -map_metadata 0 -movflags use_metadata_tags -movflags +faststart -ignore_unknown -strict experimental -f mp4 -y C:\AAA-Fotos\20211129_MS-Videos\SOG-Julia-Regina\P1080826-00.00.37.012-00.01.27.459.MP4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000021fee85f180] st: 0 edit list: 1 Missing key frame while searching for timestamp: 3003
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000021fee85f180] st: 0 edit list 1 Cannot find an index entry before timestamp: 3003.
Guessed Channel Layout for Input Stream #0.1 : stereo
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\AAA-Fotos\20211129_MS-Videos\SOG-Julia-Regina\P1080826.MP4':
  Metadata:
    major_brand     : mp42
    minor_version   : 1
    compatible_brands: mp42avc1
    creation_time   : 2021-11-29T17:41:48.000000Z
  Duration: 00:01:30.09, start: 0.000000, bitrate: 95734 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 3840x2160 [SAR 1:1 DAR 16:9], 94174 kb/s, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc (default)
    Metadata:
      creation_time   : 2021-11-29T17:41:48.000000Z
      timecode        : 05:17:03;02
    Stream #0:1(und): Audio: pcm_s16be (twos / 0x736F7774), 48000 Hz, stereo, s16, 1536 kb/s (default)
    Metadata:
      creation_time   : 2021-11-29T17:41:48.000000Z
      timecode        : 05:17:03;02
    Stream #0:2(und): Data: none (tmcd / 0x64636D74), 0 kb/s (default)
    Metadata:
      creation_time   : 2021-11-29T17:41:48.000000Z
      timecode        : 05:17:03;02
[mp4 @ 0000021ff3388040] Could not find tag for codec pcm_s16be in stream #1, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
    Last message repeated 1 times
    at makeError (C:\Users\thupp\AppData\Local\Temp\1xMTtfMQLboD7r4ebGikn7zfvcn\resources\app.asar\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Users\thupp\AppData\Local\Temp\1xMTtfMQLboD7r4ebGikn7zfvcn\resources\app.asar\node_modules\execa\index.js:114:26)
    at async O (file:///C:/Users/thupp/AppData/Local/Temp/1xMTtfMQLboD7r4ebGikn7zfvcn/resources/app.asar/build/static/js/main.220201e5.chunk.js:1:65013)
    at async file:///C:/Users/thupp/AppData/Local/Temp/1xMTtfMQLboD7r4ebGikn7zfvcn/resources/app.asar/build/static/js/main.220201e5.chunk.js:1:65219
    at async file:///C:/Users/thupp/AppData/Local/Temp/1xMTtfMQLboD7r4ebGikn7zfvcn/resources/app.asar/build/static/js/main.220201e5.chunk.js:1:192095

{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "filePath": "C:\\AAA-Fotos\\20211129_MS-Videos\\SOG-Julia-Regina\\P1080826.MP4",
    "fileFormat": "mp4",
    "externalStreamFiles": [],
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_time_base": "1001/60000",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 3840,
        "height": 2160,
        "coded_width": 3840,
        "coded_height": 2160,
        "closed_captions": 0,
        "has_b_frames": 1,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 51,
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "30000/1001",
        "avg_frame_rate": "30000/1001",
        "time_base": "1/90000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 8108100,
        "duration": "90.090000",
        "bit_rate": "94174637",
        "bits_per_raw_sample": "8",
        "nb_frames": "2700",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "creation_time": "2021-11-29T17:41:48.000000Z",
          "language": "und",
          "timecode": "05:17:03;02"
        }
      },
      {
        "index": 1,
        "codec_name": "pcm_s16be",
        "codec_long_name": "PCM signed 16-bit big-endian",
        "codec_type": "audio",
        "codec_time_base": "1/48000",
        "codec_tag_string": "twos",
        "codec_tag": "0x736f7774",
        "sample_fmt": "s16",
        "sample_rate": "48000",
        "channels": 2,
        "bits_per_sample": 16,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/48000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 4324320,
        "duration": "90.090000",
        "bit_rate": "1536000",
        "nb_frames": "4324320",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "creation_time": "2021-11-29T17:41:48.000000Z",
          "language": "und",
          "timecode": "05:17:03;02"
        }
      },
      {
        "index": 2,
        "codec_type": "data",
        "codec_tag_string": "tmcd",
        "codec_tag": "0x64636d74",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "90000/3003",
        "time_base": "1/90000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 8108100,
        "duration": "90.090000",
        "bit_rate": "959",
        "nb_frames": "2700",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "creation_time": "2021-11-29T17:41:48.000000Z",
          "language": "und",
          "timecode": "05:17:03;02"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "C:\\AAA-Fotos\\20211129_MS-Videos\\SOG-Julia-Regina\\P1080826.MP4": {
        "0": true,
        "1": true,
        "2": false
      }
    },
    "cutSegments": [
      {
        "start": 37.012664,
        "end": 87.45955
      }
    ],
    "fileFormatData": {
      "filename": "C:\\AAA-Fotos\\20211129_MS-Videos\\SOG-Julia-Regina\\P1080826.MP4",
      "nb_streams": 3,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "90.090000",
      "size": "1078094373",
      "bit_rate": "95734876",
      "probe_score": 100,
      "tags": {
        "major_brand": "mp42",
        "minor_version": "1",
        "compatible_brands": "mp42avc1",
        "creation_time": "2021-11-29T17:41:48.000000Z"
      }
    },
    "rotation": 360,
    "shortestFlag": false
  },
  "platform": "win32",
  "version": "3.39.0"
}

**Comment by mifi** [comment]
Possibly related #476 #367
Does it work if you select mov output format? I've created a new issue for this: #948
