### ISSUE TITLE
Not saving completed file

### ISSUE THREAD

**Issue by raspi-four** [mifi/lossless-cut#951]
Losslesscut 3.39.0 installed on Ubuntu 20.10

Loaded video.mp4 made 7 cuts and an .llc file was created. clicked export and 7 .mp4 files were created which viewed perfectly in VLC. However, no output of the final merged was created. ffmpeg is working perfectly. I can't seem to resolved the problem with any settings.

I restarted the computer, loaded the original video.mp4 and imported the .llc file. Everthing worked again when I clicked export but still no output processed file. 

24 hours later, I decided to try other MP4 videos I recorded. The result is the same. All the cuts are saved as individual files with timestamps but still no output of the final video. BTW, I did try to output to other medias, such as Matroska and MOV. No help.

Losslesscut was originally installed from the default packages of Ubuntu. I decided to uninstall it and then just before I reinstalled it, I tried the AppImage version. It worked perfectly. Even though you may close this, I hope you would still look into the Linux package.

**Comment by mifi** [comment]
> Losslesscut was originally installed from the default packages of Ubuntu

what does this mean? I don't distribute losslesscut for ubuntu (as a debian package). Maybe someone else does it. If so, then possibly ther ecould be something wrong with the way they package ffmpeg.
If appImage here from github works, then it suggests that there is something wrong with that other package build, so I'm closing this. thanks!
