### ISSUE TITLE
60fps 1080p mp4 video + m4a audio videos from Youtube do not export. 

### ISSUE THREAD

**Issue by Pentaphon** [mifi/lossless-cut#952]
1) Download a 60 fps 1080p mp4 + m4a audio video from Youtube using yt-dlp. This is easy to obtain.
2) Cut it with keyframe cut. Even just 2 cuts is enough
3) Try to export and merge the 2 cuts into 1 file.
4) See that file will NOT export. 

This is entirely reproducible.

**Comment by mifi** [comment]
You need to provide some more information here for me to help you. Please see the issue template: https://github.com/mifi/lossless-cut/blob/master/.github/ISSUE_TEMPLATE/bug-report.md
For me cutting youtube dl files works

**Comment by Pentaphon** [comment]
I can't seem to reproduce it anymore so I will close this issue.
