### ISSUE TITLE
DNxHD video codec support

### ISSUE THREAD

**Issue by chuckkahn** [mifi/lossless-cut#953]
I was looking for an alternative to QuickTime Pro 7 and installed this and my first test was to open a .mov I had saved with QTPro7 in High Sierra which uses the DNxHD36 codec.  Video appeared black and it seems I could only hear the first audio track.   (.mov was a combination of 1 DNxHD36 video track and 3 AIFF audio tracks).  Needing QuickTime Pro 7 is holding me back from upgrading MacOS to 64-bit and I thought this app would be a solution.  Oh well.  I guess I shouldn't expect other apps to solve Apple's shortsightedness in abandoning QuickTime Pro 7, the Swiss-army knife of video turnarounds.

**Comment by mifi** [comment]
if you use File -> Convert to supported format, you should be able to preview the file.  I have never seen any DNxHD36 file, but if you could share a small such file then I can look more into it. As long as ffmpeg supports it, then losslesscut should also be able to process it (although maybe not very fast)
