### ISSUE TITLE
Question: Re-show Export Options

### ISSUE THREAD

**Issue by Valvify** [mifi/lossless-cut#956]
In the export options dialogue, which appears after clicking the export button, you can toggle "Show this page before exporting?". Once I've hidden those export options in the future by clicking that button, I can't discern a way to re-show them without going into the configuration file.

Am I missing something within the interface?

**Comment by mifi** [comment]
hi. doesn't this ubtton work?

<img width="139" alt="Screenshot 2021-12-19 at 12 02 55" src="https://user-images.githubusercontent.com/402547/146664520-60bfba7b-ee15-4d0b-9954-1ac3f71c0a94.png">

**Comment by Valvify** [comment]
Ah, apologies. I had advanced view turned off so I could not see that button. Thank you!
