### ISSUE TITLE
The first frame of cut videos is black

### ISSUE THREAD

**Issue by rhys-vdw** [mifi/lossless-cut#957]
In order to make it easier for me to help you, I ask that you please try these things first:
- Try with the newest version from GitHub: https://github.com/mifi/lossless-cut/releases/latest
- Check https://github.com/mifi/lossless-cut and **Known issues** / **Troubleshooting**
- Search for your problem under Issues or Discussions
- Please try other type of file and see if it works.

**Share information to help me understand**
- If you have an issue cutting a particular file, please also share the file, if possible. (or mail a link to finstaden@gmail.com if private.) Also please try to cut it with the ffmpeg command line directly.
- If you have a problem or an unexpected bug or crash, please open developer tools after starting LosslessCut and before doing the failing operation. Then share the output from the javascript Console. (Menu: Tools > Toggle Developer Tools)
- Please provide the error report if you got one (Menu: Help -> Report an error)

**Describe the bug**

**To Reproduce**

Open a file, cut at a key frame. The first frame is black.
This is a problem because the first frame is used for twitter + discord thumbnails, meaning that I must make an _imperfect_ cut in video editing software to make the video ready for social sharing.

**Expected behavior**

Would expect the first frame to be the first keyframe that I jumped to.

**Screenshots**

![image](https://user-images.githubusercontent.com/822105/146673860-91dbbfb4-28fe-4f51-83c5-633853b42d73.png)

[Actual video output](https://cdn.discordapp.com/attachments/904525089834410044/922093280118861854/Shadows_--_00.01.14.000_00.01.40.000-1_handbrake.mp4)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Version 3.39.0

**Comment by mifi** [comment]
could you provide a report? and is it the same for keyframe cut vs normal cut mode? what about different avoid_negative_ts modes?

**Comment by rhys-vdw** [comment]
Ah cool. Wasn't sure if it counted as an error. I'll do some cutting and report next time, thanks.

**Comment by mifi** [comment]
Closing for now. I'll reopen when there's more info

**Comment by rhys-vdw** [comment]
Yeah, sorry about that. I will get back to you next time it happens.
