### ISSUE TITLE
Set precise start and end time of the segment

### ISSUE THREAD

**Issue by akurzawa** [mifi/lossless-cut#958]
AFIK there is no option to set the precise time of start and end of an segment.

I need it badly because I work with 8h+ videos and it's imposible to target the precise position by clicking on the timeline.

I tihnk that could be done by allowing to manually set the start/end time on the segment itself, by clicking on the time mark.

![image](https://user-images.githubusercontent.com/20043789/147205096-5c90fd78-6e2b-4b85-a68f-963a86ba7546.png)

**Comment by dbakker** [comment]
@akurzawa One thing you could do is use Ctrl+Mouse Scroll Wheel to zoom into the timeline to click more accurately.

**Comment by mifi** [comment]
can't you use the input boxes below?

<img width="309" alt="Screenshot 2022-01-01 at 15 06 41" src="https://user-images.githubusercontent.com/402547/147846634-86b8c9a1-30cf-4b0c-89f0-8367e777bc89.png">

**Comment by akurzawa** [comment]
I don't have any option to edit time by clicking time control nor two time fields as on yout screenshot

![image](https://user-images.githubusercontent.com/20043789/147873079-a42d2551-2ee2-4d65-8653-3fa7bdd1c8d4.png)

**Comment by mifi** [comment]
Ohh! try to click the baby in the lower left corner, then they will appear. I will make it more clear in the next version

**Comment by akurzawa** [comment]
> Ohh! try to click the baby in the lower left corner, then they will appear. I will make it more clear in the next version

OMG! I would never ever click on that icon ;-) Got it.

Also If you could make move to the keyframe and set start / end buttons more spreaded and change icons to be more understandable - maybe scissors icon, that would be great.

**Comment by mifi** [comment]
> OMG! I would never ever click on that icon ;-) Got it.

in the next version it will look like this:

<img width="193" alt="Screenshot 2022-01-05 at 16 41 08" src="https://user-images.githubusercontent.com/402547/148196300-8a00df30-3418-4014-a8dd-f0739ac403e8.png">

> Also If you could make move to the keyframe and set start / end buttons more spreaded and change icons to be more understandable - maybe scissors icon, that would be great.

yea that's been suggested before and I definitely want to improve those icons, see #625

**Comment by Avasam** [comment]
You can use , and . to navigate frame by frame as well. Same thing as on Youtube.

**Comment by mifi** [comment]
closing this as it seems to be solved
