### ISSUE TITLE
Allow custom filename

### ISSUE THREAD

**Issue by johnnyinthedark** [mifi/lossless-cut#96]
Hello! I want to express my gratitude for Lossless Cut. It's great for Replays during live events. @mifi could you please add the ability to rename output files? I need the output to be called exactly like the original file, without any numbers or markings. 

Thanks!

**Comment by ccoenen** [comment]
It would be awesome to have something like <kbd>Shift</kbd>+<kbd>E</kbd> which would pop up some kind of input field pre-filled to the "regular" export name (`input-intime-outtime.ext`), BUT with the cursor right before the `.ext`. This way, one could add a short note to the filename. Then my clips would not be weirdly numbered, but could contain the reason I cut this clip with very little overhead.

(i'm not for overwriting without HUGE HONKING WARNINGS, though, see #95)

**Comment by mifi** [comment]
Good idea! It’s something i want to look into

**Comment by katodevin** [comment]
I would also love the ability to set a custom file name.  Like the OP, I would simply like for it to be the same file name - but output to a different folder of course.

**Comment by ChicagoScanningMG** [comment]
I also would like custom file name output.  I don't like all of the info that's automatically appended to the end of split files.  I have a full renaming workflow I use AFTERWARD and the appended information interferes with my renaming software's ability to search for the source name to pull the correct information to rename the file to.

For example, I have a spreadsheet set up with "File_001, File 002, File 003, etc" and the corresponding FULL names in another column, "File_001_Full Name, "File_002_Full Name", etc.  When information is appended to the file, such as, "File_001-00.00.01.067-00.35.16.080-seg1" it makes my renaming workflow more difficult.  I also don't need to see the trimmed clip information in the file output name.

To plus 1 another comment, I wouldn't MIND being able to overwrite the source file, but that's not really best practice.  i think it would be better to have the option to "Create Output Folder in Source Directory."  That way you can retain the original file, and you don't need to worry about file name collision.

**Comment by ChicagoScanningMG** [comment]
Lastly, I see there was a concern of multiple clips being made from a master clip.  I think the ideal solution would be to have to the first clip use the master clips name, then additional clips get appended with simple numbers, so, "File_001", File_001_001", "File_001_002", etc.

There's probably a more elegant solution, but that would satisfy my issues.

**Comment by ChicagoScanningMG** [comment]
Sorry, one final comment.  If it's too much to ask to change the appended text on the file name, at the VERY least, I'd like to change the delimiting character.  That is, the cutting information is appended with the leading character "-".  if I could specify which character is used to separate the suffix, I can account for that in my renaming software.

**Comment by mifi** [comment]
It could be a text field prefilled with the input name plus the appended suffix
if the input file is `my-file.mp4`, the default input field could be:
`my-file{{DEFAULT_SUFFIX}}` (which becomes `my-file-00.00.04.448-00.00.14.833-seg1.mp4`)
...then allow the user to change this text and have some variables to choose from:
- `{{LABEL}}` - the segment's label (safely formatted for file names).
- `{{CUT_FROM}}` e.g. `00.00.04.448`
- `{{CUT_TO}}` e.g. `00.00.14.833`
- `{{SEG_NUM}}` e.g. `1`
- `{{EXT}}` e.g. `.mp4`

We could also allow adding a subpath, e.g. `output/to/my-file{{DEFAULT_SUFFIX}}`, then the app will auto-create the folder structure leading to the path (relative to output dir) before outputting the file(s).

Should have some validation:
- filename cannot contain any of these special variables
- if more than one segment is exported, validate that each file name will be unique
- check that output name is not the same as input name
- ...

**Comment by mifi** [comment]
this is now implemented and can be tested in the next version!

<img width="685" alt="Screenshot 2021-01-23 at 22 49 44" src="https://user-images.githubusercontent.com/402547/105614979-4ad3b780-5dcd-11eb-9e70-2063a80431c1.png">

**Comment by ChicagoScanningMG** [comment]
Brilliant!  Thanks!!!!

**Comment by masvil** [comment]
Amazing implementation, hat off.

**Comment by msdobrescu** [comment]
When using cue, for example, the file names and file tags could be based on the contained meta-information, like track number, performer, track title, album title, year. Why not use that too?

**Comment by shinnlu** [comment]
how to show export options again?
i want to use SEG_NUM instead of timecode, after tested i click on the icon "show export options screen before exporting", the filename change back to timecode, and export options icon disappear.
![截圖 2021-07-30 上午11 01 04](https://user-images.githubusercontent.com/570246/127593658-03b0ce96-d418-4bc6-8041-2a482384c437.png)

**Comment by mattack1** [comment]
Can I have it output in the *same* folder as the original file?  (Possibly rename the original file to NAMEORIG.suffix
or whatever, as an option)

I want to effectively edit "in place" since I had the files in the original place I wanted them.. (and all of the cut point info is irrelevant to me in the filename).  I'm usually just saving the musical portion(s) of a talk show/SNL.

**Comment by mifi** [comment]
to output to same folder as original file, just press the button, then select "cancel" in the dialog. I have now improved that so there is a separate button for clearing output directory, see #805

**Comment by mattack1** [comment]
But you mean I have to do that for EVERY single file?  I want it to just default to the same location....

**Comment by mifi** [comment]
I'm not sure if I undertsand. If the button says "working dir unset", then losslesscut will always save the output file to the same directory as the source file, and you don't need to do anything for every new file.

**Comment by plk0507** [comment]
Can someone give directions on how to rename the file output or delete the add-ons entirely? Thank you.

**Comment by mifi** [comment]
Not possible yet. See #938
