### ISSUE TITLE
Fails to open when low space on C: drive

### ISSUE THREAD

**Issue by Echo51** [mifi/lossless-cut#965]
With 200-400mb of space left on my boot/windows/temp/C: drive losslesscut-win.exe fails to open, both 3.39.0 and 3.38.0 exhibited similar issues. Briefly pops up in the task manager then closes with no message.

**Expected behavior**
An error message at minimum

**Desktop (please complete the following information):**
Windows 10

**Additional context**
I assume this is related to electrum not being able to allocate/create the files it would like.
Are there really no plain-text logs created from this app?

**Comment by mifi** [comment]
Try the ZIP version if you haven't already. Not much else I can do. 200mb is too little free space and the exe version is self-extracting, that's why.
