### ISSUE TITLE
LC resets first subtitle track to "Default"

### ISSUE THREAD

**Issue by bigfella237** [mifi/lossless-cut#972]
When muxing my .MKV files I almost always set the "Default track flag" on all my subtitle tracks to "No" (with the exception of "forced" non-local dialogue translations).

However, after trimming an .MKV with Lossless Cut I find the "Default track flag" on the first subtitle track has been reset to "Yes", meaning that track automatically gets displayed during playback.

This is a real pain as it means I need to re-mux everything after I use LC to turn off the subtitles again.

Could Lossless Cut be made to export .MKV files with the same flags as the input file?

**Comment by mifi** [comment]
could you post the offending ffmpeg command from the losslesscut help screen that is causing this issue? and some info about the file(s) you're trying to process?

**Comment by bigfella237** [comment]
Sorry but I don't know anything about ffmpeg commands, I simple open Lossless Cut, drag 'n drop an .MKV file into it, specify the start and end cut points and export.

If I compare the input file to the output file I find the default flag on the first subtitle track always gets changed from "no" to "yes".

This has happened with every .MKV file I've used (well, every one that has subtitles).

**Comment by mifi** [comment]
where do you see the default

> If I compare the input file to the output file I find the default flag on the first subtitle track always gets changed from "no" to "yes".

where can you see this? in losslesscut?

> Sorry but I don't know anything about ffmpeg commands, I simple open Lossless Cut, drag 'n drop an .MKV file into it, specify the start and end cut points and export.

could you go to the help screen after exporting and copy paste the ffmpeg commands here?

**Comment by bigfella237** [comment]
Apologies again for the late reply. I'm talking about Matroska (.mkv file) tags, there are many programs that display/edit them but I'm using MKVmerge (or MKVToolNix as it's now called).

This is a screenshot of a file in MKVmerge before being Lossless Cut:

https://i.postimg.cc/vT7k97Ym/Lossless-Cut-First-Sub-Track-BEFORE.jpg

And this is the same file after being trimmed:

https://i.postimg.cc/8kLqqGRV/Lossless-Cut-First-Sub-Track-AFTER.jpg

As evident, the "Default" tag for the first subtitle track is being reset to "Yes". It's quite common to see this, it seems like 'default' behavior of most programs to set the first audio & subtitle track to Default.

The problem is, this makes most players display the subtitles automatically. If left like this I would have to turn off the subtitles in the player every time I watch the video.

**Comment by mifi** [comment]
Ok I understand. So it's not a problem unique to losslesscut, is that what you're saying? Then I think it's probably an issue with ffmpeg.

looking at [-disposition](https://ffmpeg.org/ffmpeg.html) i see:

> By default, the disposition is copied from the input stream, unless the output stream this option applies to is fed by a complex filtergraph - in that case the disposition is unset by default.

> value is a sequence of items separated by ’+’ or ’-’. The first item may also be prefixed with ’+’ or ’-’, in which case this option modifies the default value. Otherwise (the first item is not prefixed) this options overrides the default value. A ’+’ prefix adds the given disposition, ’-’ removes it. It is also possible to clear the disposition by setting it to 0.

> If no -disposition options were specified for an output file, ffmpeg will automatically set the ’default’ disposition on the first stream of each type, when there are multiple streams of this type in the output file and no stream of that type is already marked as default.

so it seems that ffmpeg will automatically set disposition to default

Also [-default_mode infer_no_subs](https://stackoverflow.com/questions/65672037/disable-default-subtitle-track-with-ffmpeg) https://ffmpeg.org/ffmpeg-formats.html#Options-8 might be worth looking into

However I'm not sure of the consequences for other files (e.g. converting mp4 to mkv and such)

Maybe this could be solved by allowing injecting custom ffmpeg arguments...

**Comment by mifi** [comment]
Seems like `infer` is [indeed the default](https://stackoverflow.com/questions/65672037/disable-default-subtitle-track-with-ffmpeg#comment125078818_65673094) despite ffmpeg docs saying passthrough.

After more research, this option only affects matroska, and I think setting it to `infer_no_subs` seems like a reasonable thing to do.

I tested and it seems to work! so this should be fixed in the next version of losslesscut.
