### ISSUE TITLE
App is ignoring where I am cutting the video at beginning and end. It is often off by a few seconds.

### ISSUE THREAD

**Issue by digidoggie18** [mifi/lossless-cut#977]
No error

{
  "state": {
    "filePath": "D:\\FIX\\Dexters Laboratory 1996\\Season 01\\04 Dexter Dodgeball - Rasslor - Dexter's Assistant-00.07.20.000-00.14.12.000-seg2-reformatted.mp4",
    "fileFormat": "mp4",
    "externalStreamFiles": [],
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "hevc",
        "codec_long_name": "H.265 / HEVC (High Efficiency Video Coding)",
        "profile": "Main",
        "codec_type": "video",
        "codec_time_base": "1001/24000",
        "codec_tag_string": "hvc1",
        "codec_tag": "0x31637668",
        "width": 1280,
        "height": 720,
        "coded_width": 1280,
        "coded_height": 736,
        "closed_captions": 0,
        "has_b_frames": 0,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 156,
        "color_range": "tv",
        "field_order": "progressive",
        "refs": 1,
        "r_frame_rate": "24000/1001",
        "avg_frame_rate": "9912000/413401",
        "time_base": "1/24000",
        "start_pts": 288,
        "start_time": "0.012000",
        "duration_ts": 9921624,
        "duration": "413.401000",
        "bit_rate": "1996074",
        "nb_frames": "9912",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "eng",
          "handler_name": "VideoHandler"
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_time_base": "1/48000",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/48000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 19844096,
        "duration": "413.418667",
        "bit_rate": "192955",
        "max_bit_rate": "192955",
        "nb_frames": "19379",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "eng",
          "handler_name": "SoundHandler"
        }
      },
      {
        "index": 2,
        "codec_name": "bin_data",
        "codec_long_name": "binary data",
        "codec_type": "data",
        "codec_tag_string": "text",
        "codec_tag": "0x74786574",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/1000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 413419,
        "duration": "413.419000",
        "nb_frames": "3",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "eng",
          "handler_name": "SubtitleHandler"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "D:\\FIX\\Dexters Laboratory 1996\\Season 01\\04 Dexter Dodgeball - Rasslor - Dexter's Assistant-00.07.20.000-00.14.12.000-seg2-reformatted.mp4": {
        "0": true,
        "1": true,
        "2": false
      }
    },
    "cutSegments": [
      {}
    ],
    "fileFormatData": {
      "filename": "D:\\FIX\\Dexters Laboratory 1996\\Season 01\\04 Dexter Dodgeball - Rasslor - Dexter's Assistant-00.07.20.000-00.14.12.000-seg2-reformatted.mp4",
      "nb_streams": 3,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "413.419000",
      "size": "113328322",
      "bit_rate": "2192996",
      "probe_score": 100,
      "tags": {
        "major_brand": "isom",
        "minor_version": "512",
        "compatible_brands": "isomiso2mp41",
        "encoder": "Lavf58.45.100"
      }
    },
    "rotation": 360,
    "shortestFlag": false
  },
  "platform": "win32",
  "version": "3.39.0"
}

**Comment by mifi** [comment]
please read https://github.com/mifi/lossless-cut#known-issues--limitations
