### ISSUE TITLE
3.42.0 - appimage - Installation is broken: Command failed with ENOENT: /tmp/.mount_Loss...

### ISSUE THREAD

**Issue by slrslr** [mifi/lossless-cut#985]
Hello, a few hours back i ran:
`/usr/bin/wget -NqO /home/user/LosslessCut-linux.AppImage https://github.com/mifi/lossless-cut/releases/latest/download/LosslessCut-linux.AppImage`
and after running .appimage, it shows this:
![losslesscutissue](https://user-images.githubusercontent.com/6596726/149664214-27c5c577-05d3-4d6b-9d37-1575e1167e27.gif)
For a few seconds, then appear again when trying to open the video file inside LC.
About page of the app shows: You are running version 3.42.0
Manjaro Linux stable, kern. 5.15, based on Arch.

**Comment by Perkolator** [comment]
Same here on Linux Mint 20.2 Cinnamon, kernel 5.4.0-90.101. Was working fine with the previous 3.39.0 version.

**Comment by mifi** [comment]
Ok I see that files are much smaller,
- LosslessCut-linux.AppImage 77.9 MB
- LosslessCut-linux.tar.bz2 67.5 MB

vs old version:
- LosslessCut-linux.AppImage 130 MB
- LosslessCut-linux.tar.bz2 115 MB

so I think ffmpeg is probably missing. will look into it

**Comment by mifi** [comment]
Can you try again now. I re uploaded the build

**Comment by Perkolator** [comment]
Seems to be working fine. Thanks.
