### ISSUE TITLE
New Windows warning in new version 3.42.0, not happened in 3.39.2

### ISSUE THREAD

**Issue by softrare** [mifi/lossless-cut#986]
I am a very new user, just discovered this program in version 3.39.2 last week. I use it to merge files before uploading to youtube, haven't found any other program that can do this without changing important parameters, so happy about that. I saw the upgrade notice yesterday and went ahead, but I notice that suddenly Windows warns me of the new executable. I tried the old executable again and indeed it doesn't come up there. This can be for any number of reasons of course, does anyone know what the particular reason is in this case? Thank you very much in advance!

![okB1vCJjAW](https://user-images.githubusercontent.com/1820497/149665154-6d48bec8-bbc6-46c7-a924-39aab6a5f394.png)

**Comment by mifi** [comment]
Hi! This is probably because the binaries on github are not signed. Maybe the old version worked because windows has "already gotten used to" the previous ffmpeg version. In the newest losslesscut there I upgraded ffmpeg to newest version.

**Comment by mifi** [comment]
closing this as nothing I can relaly do about it, I think as time goes by, microsoft will flag the new version of ffmpeg as safe also and this will possibly go away
