### ISSUE TITLE
Manually entering cut time has small issue (cut end value is not written if time is earlier than cut start)

### ISSUE THREAD

**Issue by slrslr** [mifi/lossless-cut#988]
Hello,

it was happening before and now too when making cuts shorted than 1 minute

**HOW TO REPRODUCE:**
open video in latest LC
Have:

CUT start:
00:05:26.000
CUT end:
00:07:20.000

now try to set CUT end to: 5m. 55s. by nature i first adjust hours, then minutes, then seconds. So i click into 07 value changing it to 05 value
result: value is not written and cursor jumps away to the end of the cut end field.
it happens because cut end would be lower time than cut start at the time of writing.

But this behavior is wrong, because i would then change seconds to 55 instead of 20 so cut end would be later than start.

**WORAROUND:**
you have to remember to first write seconds, then minutes, then hours.. which is not natural to me at least :-/

**FIX idea:**
somehow allow writing any value and report issue later when clicking away or when exporting or silently excluding the erroneous segment at export time or just flip the segment times so defined cut end is cut start at a time of exporting?

**Btw**. i can doubleclick the minutes value to highlight it and then type to overwrite (that is handy), but for seconds value it highlight whole 20.000 (not only sencond, but also miliseconds)).

**Comment by mifi** [comment]
Hi. It would be nice if you could provide some info as requested in the template. like did this work on the previous version? which OS are you on? could you provide a short video showing the issue in action?

**Comment by slrslr** [comment]
Hi, i have already mentioned that "it was happening before and now too", i think it was happening since i began using the app 2 years ago around. System is Linux Manjaro stable. I think that i have written the reproduction steps short and understandable. If not, let me know what You do not understand. Thank you

**Comment by mifi** [comment]
This seems suspiciously similar to #670 - also Manjaro. Probably an issue with input fields controlled by react. I wonder if it's also an issue on other linuxes like ubuntu. On MacOS I cannot reporduce it

**Comment by slrslr** [comment]
> could you provide a short video

i doubt the video is more understandable than the text steps mentioned, but [here it is temporarily stored](https://streamable.com/qz9d7u)

**Comment by mifi** [comment]
I took the liberty of attaching it here:
https://user-images.githubusercontent.com/402547/149786643-1cd41723-f74c-43e8-b8d8-7d43557c9595.mp4

actually it's helpful, because as far as I can see it only happens *some times*, not always, am I right? It's a bit hard for me to fix it because I cannot reproduce it here, but I'm thinking maybe we need to prevent updating the input value if the value is the same as before update (which happens due to the way react controlled updates works).

**Comment by slrslr** [comment]
>  prevent updating the input value if the value is the same as before update (which happens due to the way react controlled updates works).

Yes, maybe it would help, if you make such modification, let me know and i will try to reproduce the issue.

> it only happens some times, not always, am I right?

No, it happens always for me when conditions mentioned in initial post are met.

**Comment by mifi** [comment]
Ok, thanks for the details. I think I understand the issue now. I think it’s due to the fact that we don’t allow negative lengths on segments, so the validation will reject and revert back to the original value. I think what the code should do instead is that the field should be kept in the red «invalid» state, that way it will not be «commited» until it contains a valid gvalue.
I guess it was just a coincidence that the only two users who reported this are running Manjaro😄

**Comment by mifi** [comment]
Ok, I have now fixed this issue and it will be resolved in the next release, thanks!

**Comment by slrslr** [comment]
I am now on Debian 13 with KDE and i am back with issue like this. Can this be re-opened @mifi  ?

ISSUE with LC 3.66.1:
start time: 00:17:30.040
end time :  00:18:58.698
when i try to overwrite "8" in end time minutes, by highlighting it by mouse (insert key and typing before the number 8 does not overwrite), it jumps at the end of the end time (because possibly it thinks for a moment it is 00:01:58.698).
A workaround is to write 178 and then delete number 8. To me, natural is to delete first what i want to delete (or highlight it and type - expecting overwrite).
Actually numerous people like https://github.com/mifi/lossless-cut/issues/1694 wanted overwriting by default, maybe if that works such way, the LC will not complain about negative end time?

**Comment by mifi** [comment]
hmm, how to reproduce exactly?
- I create a segment from `00:17:30.040` to `00:18:58.698`
- In 00:18:58.698 I select the `8` in `18`
- I press for example `9` on my keyboard
- the new time becomes `00:19:58.698` which is expected

**Comment by slrslr** [comment]
I am sorry M., i have been unable to reproduce it same as you. But mine described outcome happens when you type not 9 (as you have shown in your previous post) but 6. In that case end time becomes less than start time. Which is normal for a LC to deny to set such time. Though it is silent and does not feedback user about his/her mistake/error.
This "issue" happens also in opposite order for example you have

start time: 00:1:13.001 (i am unable to add "1" after first "1" due to a start time would be after end time 00:10:28.940
Should there be some user friendly notice or something? Instead of silently moving cursor to the end of the input area?

**Comment by mifi** [comment]
i will make it so that it doesn't move the cursor to the end, and it will mark the text as red color, indicating that there is an error

**Comment by slrslr** [comment]
I think that this is fixed.

I can now write end time that is earlier than start time and the field is highlighted in light red. I do not know if it is strong enough indicator for most users, for me it is fine, but important is that it no longer has this issue:

> value is not written and cursor jumps away to the end of the cut end field.
