### ISSUE TITLE
Lossless Cut doesn't remember it's size and location on the desktop

### ISSUE THREAD

**Issue by bigfella237** [mifi/lossless-cut#989]
Hopefully a basic request... Could Lossless Cut be made to remember it's size and position on the desktop and re-open in the same place next time it's run?

Also, please ensure it can handle negative desktop coordinates for those of us with multiple monitors.

Thanks!

**Comment by mifi** [comment]
Are you running the newest version? It has support for remembering position. If not please procide some more details as requested in the issue template

**Comment by bigfella237** [comment]
I thought I was but as it turns out I wasn't! 

I'll upgrade now and report back.

**Comment by bigfella237** [comment]
Upgraded. 

V3.42.0 now remembers it's position and size, however it doesn't remember that it was maximized. If closed while maximized it re-opens to the restore-down window size.

This doesn't really matter since we can manually resize the window to the same size as if it were maximized and then close it as a work-around.

**Comment by mifi** [comment]
Right. I haven't implemented remembering extra states like maximized or minimized. If it's something that a lot of people request I will look into it, but there may be some unknown edge cases that can cause trouble if I implement those

**Comment by bigfella237** [comment]
It's all good. As before, we can easily adjust the window size manually to mimic a maximized window and the program will effectively re-open the same as if it were maximized.

Thanks again!

**Comment by Galaxoid-333** [comment]
My LLC app doesn't remember full screen mode. Every time I open the app I have to press full screen.

**Comment by Galaxoid-333** [comment]
My LLC app doesn't remember full screen mode. Every time I open the app I have to press full screen.

**Comment by mifi** [comment]
you can test this in the next nightly build
