### ISSUE TITLE
Please preserve original metadata

### ISSUE THREAD

**Issue by reefhound** [mifi/lossless-cut#99]
Losslet Cut is changing the metadata. Attached are files showing output, using exiftool, from the original and from the clip. This is causing errors in other software tools I'm using. Of direct concern are the bolded items below - MIME Type, Major Brand, Minor Brand, Compatible Brands.

======== GH010240.MP4
ExifTool Version Number         : 10.64
File Name                       : GH010240.MP4
Directory                       : .
File Size                       : 193 MB
File Modification Date/Time     : 2018:09:03 09:25:00-05:00
File Access Date/Time           : 2018:10:01 12:37:19-05:00
File Creation Date/Time         : 2018:10:01 12:37:19-05:00
File Permissions                : rw-rw-rw-
File Type                       : MP4
File Type Extension             : mp4
MIME Type                       : **video/mp4**
Major Brand                     : **MP4 v1 [ISO 14496-1:ch13]**
Minor Version                   : **2013.10.18**
Compatible Brands               : **mp41**
Movie Header Version            : 0

======== GH010240.MP4-00.00.11.431-00.00.20.182.MP4
ExifTool Version Number         : 10.64
File Name                       : GH010240.MP4-00.00.11.431-00.00.20.182.MP4
Directory                       : .
File Size                       : 73 MB
File Modification Date/Time     : 2018:09:03 09:25:00-05:00
File Access Date/Time           : 2018:10:01 12:37:21-05:00
File Creation Date/Time         : 2018:10:01 12:37:21-05:00
File Permissions                : rw-rw-rw-
File Type                       : MP4
File Type Extension             : mp4
MIME Type                       : **video/quicktime**
Major Brand                     : **Apple QuickTime (.MOV/QT)**
Minor Version                   : **0.2.0**
Compatible Brands               : **qt**
Movie Data Size                 : 76086001
Movie Data Offset               : 36
Movie Header Version            : 0

A number of other tags are also being changed (Handler tags), some are being dropped, and some are being added.

[original.txt](https://github.com/mifi/lossless-cut/files/2435305/original.txt)
[clipped.txt](https://github.com/mifi/lossless-cut/files/2435307/clipped.txt)

**Comment by mifi** [comment]
Yeah I also noticed that some metadata gets modified when running thru ffmpeg copy, even when using `-map_metadata 0` (which we are doing currently). In particular exif data.

Might be a possible to do this:
`exiftool -overwrite_original -tagsFromFile UNCUT_FILE -ExtractEmbedded CUT_FILE`

But I dunno if it has any side-effects. And I don't know which file formats exiftool works on

**Comment by mifi** [comment]
I have added `-movflags use_metadata_tags`, hopefully it helps. reopen if still an issue
