### ISSUE TITLE
Debian 10: AppImage segfault on startup

### ISSUE THREAD

**Issue by LeSpocky** [mifi/lossless-cut#994]
In order to make it easier for me to help you, I ask that you please try these things first:
- [x] Try with the newest version from GitHub: https://github.com/mifi/lossless-cut/releases/latest
- [x] Check https://github.com/mifi/lossless-cut and **Known issues** / **Troubleshooting**
- [x] Search for your problem under Issues or Discussions
- [ ] Please try other type of file and see if it works.

**Share information to help me understand**
- ~~If you have an issue cutting a particular file, please also share the file, if possible. (or mail a link to finstaden@gmail.com if private.) Also please try to cut it with the ffmpeg command line directly.~~
- ~~If you have a problem or an unexpected bug or crash, please open developer tools after starting LosslessCut and before doing the failing operation. Then share the output from the javascript Console. (Menu: Tools > Toggle Developer Tools)~~
- ~~Please provide the error report if you got one (Menu: Help -> Report an error)~~

**Describe the bug**
The application does not start at all, crashes with a segmentation fault instead.

**To Reproduce**
1. Run Debian GNU/Linux 10 (buster) on arch amd64
2. Download any AppImage release (I tried from 3.33.1 to 3.42.0)
3. Grant execution rights to the binary (`chmod +x`)
4. Start from commandline with parameter `--no-sandbox`

**Expected behavior**
Application starts and show some window.

**Screenshots**
~~If applicable, add screenshots to help explain your problem.~~

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 10 (buster) on arch amd64

**Additional context**
Command line output:

```
% ./LosslessCut-linux.AppImage --no-sandbox               :(
[1]    19450 segmentation fault  ./LosslessCut-linux.AppImage --no-sandbox
```

I can assist in debugging, if I get precise hints what to try.

**Comment by mifi** [comment]
I have no idea how to debug this. May be due to the old electron version lossless-cut is running. But we cannot upgrade yet unfortunately #714

**Comment by LeSpocky** [comment]
I'm afraid I can not reproduce it anymore. Just tried another time no with 3.42.0 and it starts and runs. Closing this, sorry for the noise.
